//------------------------------------------------------------------------------
// SGCL: a C++20 application platform
// Copyright (c) 2022-2026 Sebastian Nibisz
// SPDX-License-Identifier: Apache-2.0
//------------------------------------------------------------------------------
#pragma once
#include "../../detail/cldr.h"

#include <cstdint>

// The time zones of CLDR 46.0 the display names speak of (bcp47/timezone.xml,
// supplemental/metaZones.xml; generated by tools/cldr_tables.py: do not edit):
// their identifiers, their aliases and the metazone each uses today.
namespace sgcl::txt::detail::cldr {
    inline constexpr char8_t ZoneIdChunk0[] =
        u8"Africa/AbidjanAfrica/AccraAfrica/Addis_AbabaAfrica/AlgiersAfrica/AsmeraAfrica/BamakoAfrica/BanguiAfr"
        u8"ica/BanjulAfrica/BissauAfrica/BlantyreAfrica/BrazzavilleAfrica/BujumburaAfrica/CairoAfrica/Casablanc"
        u8"aAfrica/CeutaAfrica/ConakryAfrica/DakarAfrica/Dar_es_SalaamAfrica/DjiboutiAfrica/DoualaAfrica/El_Aai"
        u8"unAfrica/FreetownAfrica/GaboroneAfrica/HarareAfrica/JohannesburgAfrica/JubaAfrica/KampalaAfrica/Khar"
        u8"toumAfrica/KigaliAfrica/KinshasaAfrica/LagosAfrica/LibrevilleAfrica/LomeAfrica/LuandaAfrica/Lubumbas"
        u8"hiAfrica/LusakaAfrica/MalaboAfrica/MaputoAfrica/MaseruAfrica/MbabaneAfrica/MogadishuAfrica/MonroviaA"
        u8"frica/NairobiAfrica/NdjamenaAfrica/NiameyAfrica/NouakchottAfrica/OuagadougouAfrica/Porto-NovoAfrica/"
        u8"Sao_TomeAfrica/TripoliAfrica/TunisAfrica/WindhoekAmerica/AdakAmerica/AnchorageAmerica/AnguillaAmeric"
        u8"a/AntiguaAmerica/AraguainaAmerica/Argentina/La_RiojaAmerica/Argentina/Rio_GallegosAmerica/Argentina/"
        u8"SaltaAmerica/Argentina/San_JuanAmerica/Argentina/San_LuisAmerica/Argentina/TucumanAmerica/Argentina/"
        u8"UshuaiaAmerica/ArubaAmerica/AsuncionAmerica/BahiaAmerica/Bahia_BanderasAmerica/BarbadosAmerica/Belem"
        u8"America/BelizeAmerica/Blanc-SablonAmerica/Boa_VistaAmerica/BogotaAmerica/BoiseAmerica/Buenos_AiresAm"
        u8"erica/Cambridge_BayAmerica/Campo_GrandeAmerica/CancunAmerica/CaracasAmerica/CatamarcaAmerica/Cayenne"
        u8"America/CaymanAmerica/ChicagoAmerica/ChihuahuaAmerica/Ciudad_JuarezAmerica/Coral_HarbourAmerica/Cord"
        u8"obaAmerica/Costa_RicaAmerica/CrestonAmerica/CuiabaAmerica/CuracaoAmerica/DanmarkshavnAmerica/DawsonA"
        u8"merica/Dawson_CreekAmerica/DenverAmerica/DetroitAmerica/DominicaAmerica/EdmontonAmerica/EirunepeAmer"
        u8"ica/El_SalvadorAmerica/Fort_NelsonAmerica/FortalezaAmerica/Glace_BayAmerica/GodthabAmerica/Goose_Bay"
        u8"America/Grand_TurkAmerica/GrenadaAmerica/GuadeloupeAmerica/GuatemalaAmerica/GuayaquilAmerica/GuyanaA"
        u8"merica/HalifaxAmerica/HavanaAmerica/HermosilloAmerica/Indiana/KnoxAmerica/Indiana/MarengoAmerica/Ind"
        u8"iana/PetersburgAmerica/Indiana/Tell_CityAmerica/Indiana/VevayAmerica/Indiana/VincennesAmerica/Indian"
        u8"a/WinamacAmerica/IndianapolisAmerica/InuvikAmerica/IqaluitAmerica/JamaicaAmerica/JujuyAmerica/Juneau"
        u8"America/Kentucky/MonticelloAmerica/KralendijkAmerica/La_PazAmerica/LimaAmerica/Los_AngelesAmerica/Lo"
        u8"uisvilleAmerica/Lower_PrincesAmerica/MaceioAmerica/ManaguaAmerica/ManausAmerica/MarigotAmerica/Marti"
        u8"niqueAmerica/MatamorosAmerica/MazatlanAmerica/MendozaAmerica/MenomineeAmerica/MeridaAmerica/Metlakat"
        u8"laAmerica/Mexico_CityAmerica/MiquelonAmerica/MonctonAmerica/MonterreyAmerica/MontevideoAmerica/Monts"
        u8"erratAmerica/NassauAmerica/New_YorkAmerica/NomeAmerica/NoronhaAmerica/North_Dakota/BeulahAmerica/Nor"
        u8"th_Dakota/CenterAmerica/North_Dakota/New_SalemAmerica/OjinagaAmerica/PanamaAmerica/ParamariboAmerica"
        u8"/PhoenixAmerica/Port-au-PrinceAmerica/Port_of_SpainAmerica/Porto_VelhoAmerica/Puerto_RicoAmerica/Pun"
        u8"ta_ArenasAmerica/Rankin_InletAmerica/RecifeAmerica/ReginaAmerica/ResoluteAmerica/Rio_BrancoAmerica/S"
        u8"antaremAmerica/SantiagoAmerica/Santo_DomingoAmerica/Sao_PauloAmerica/ScoresbysundAmerica/SitkaAmeric"
        u8"a/St_BarthelemyAmerica/St_JohnsAmerica/St_KittsAmerica/St_LuciaAmerica/St_ThomasAmerica/St_VincentAm"
        u8"erica/Swift_CurrentAmerica/TegucigalpaAmerica/ThuleAmerica/TijuanaAmerica/TorontoAmerica/TortolaAmer"
        u8"ica/VancouverAmerica/WhitehorseAmerica/WinnipegAmerica/YakutatAntarctica/CaseyAntarctica/DavisAntarc"
        u8"tica/DumontDUrvilleAntarctica/MacquarieAntarctica/MawsonAntarctica/McMurdoAntarctica/PalmerAntarctic"
        u8"a/RotheraAntarctica/SyowaAntarctica/TrollAntarctica/VostokArctic/LongyearbyenAsia/AdenAsia/AlmatyAsi"
        u8"a/AmmanAsia/AnadyrAsia/AqtauAsia/AqtobeAsia/AshgabatAsia/AtyrauAsia/BaghdadAsia/BahrainAsia/BakuAsia"
        u8"/BangkokAsia/BarnaulAsia/BeirutAsia/BishkekAsia/BruneiAsia/CalcuttaAsia/ChitaAsia/ColomboAsia/Damasc"
        u8"usAsia/DhakaAsia/DiliAsia/DubaiAsia/DushanbeAsia/FamagustaAsia/GazaAsia/HebronAsia/Hong_KongAsia/Hov"
        u8"dAsia/IrkutskAsia/JakartaAsia/JayapuraAsia/JerusalemAsia/KabulAsia/KamchatkaAsia/KarachiAsia/Katmand"
        u8"uAsia/KhandygaAsia/KrasnoyarskAsia/Kuala_LumpurAsia/KuchingAsia/KuwaitAsia/MacauAsia/MagadanAsia/Mak"
        u8"assarAsia/ManilaAsia/MuscatAsia/NicosiaAsia/NovokuznetskAsia/NovosibirskAsia/OmskAsia/OralAsia/Phnom"
        u8"_PenhAsia/PontianakAsia/PyongyangAsia/QatarAsia/QostanayAsia/QyzylordaAsia/RangoonAsia/RiyadhAsia/Sa"
        u8"igonAsia/SakhalinAsia/SamarkandAsia/SeoulAsia/ShanghaiAsia/SingaporeAsia/SrednekolymskAsia/TaipeiAsi"
        u8"a/TashkentAsia/TbilisiAsia/TehranAsia/ThimphuAsia/TokyoAsia/TomskAsia/UlaanbaatarAsia/UrumqiAsia/Ust"
        u8"-NeraAsia/VientianeAsia/VladivostokAsia/YakutskAsia/YekaterinburgAsia/YerevanAtlantic/AzoresAtlantic"
        u8"/BermudaAtlantic/CanaryAtlantic/Cape_VerdeAtlantic/FaeroeAtlantic/MadeiraAtlantic/ReykjavikAtlantic/"
        u8"South_GeorgiaAtlantic/St_HelenaAtlantic/StanleyAustralia/AdelaideAustralia/BrisbaneAustralia/Broken_"
        u8"HillAustralia/DarwinAustralia/EuclaAustralia/HobartAustralia/LindemanAustralia/Lord_HoweAustralia/Me"
        u8"lbourneAustralia/PerthAustralia/SydneyEtc/GMTEtc/GMT+1Etc/GMT+10Etc/GMT+11Etc/GMT+12Etc/GMT+2Etc/GMT"
        u8"+3Etc/GMT+4Etc/GMT+5Etc/GMT+6Etc/GMT+7Etc/GMT+8Etc/GMT+9Etc/GMT-1Etc/GMT-10Etc/GMT-11Etc/GMT-12Etc/G"
        u8"MT-13Etc/GMT-14Etc/GMT-2Etc/GMT-3Etc/GMT-4Etc/GMT-5Etc/GMT-6Etc/GMT-7Etc/GMT-8Etc/GMT-9Etc/UTCEtc/Un"
        u8"knownEurope/AmsterdamEurope/AndorraEurope/AstrakhanEurope/AthensEurope/BelgradeEurope/BerlinEurope/B"
        u8"ratislavaEurope/BrusselsEurope/BucharestEurope/BudapestEurope/BusingenEurope/ChisinauEurope/Copenhag"
        u8"enEurope/DublinEurope/GibraltarEurope/GuernseyEurope/HelsinkiEurope/Isle_of_ManEurope/IstanbulEurope"
        u8"/JerseyEurope/KaliningradEurope/KievEurope/KirovEurope/LisbonEurope/LjubljanaEurope/LondonEurope/Lux"
        u8"embourgEurope/MadridEurope/MaltaEurope/MariehamnEurope/MinskEurope/MonacoEurope/MoscowEurope/OsloEur"
        u8"ope/ParisEurope/PodgoricaEurope/PragueEurope/RigaEurope/RomeEurope/SamaraEurope/San_MarinoEurope/Sar"
        u8"ajevoEurope/SaratovEurope/SimferopolEurope/SkopjeEurope/SofiaEurope/StockholmEurope/TallinnEurope/Ti"
        u8"raneEurope/UlyanovskEurope/VaduzEurope/VaticanEurope/ViennaEurope/VilniusEurope/VolgogradEurope/Wars"
        u8"awEurope/ZagrebEurope/ZurichIndian/AntananarivoIndian/ChagosIndian/ChristmasIndian/CocosIndian/Comor"
        u8"oIndian/KerguelenIndian/MaheIndian/MaldivesIndian/MauritiusIndian/MayotteIndian/ReunionPacific/ApiaP"
        u8"acific/AucklandPacific/BougainvillePacific/ChathamPacific/EasterPacific/EfatePacific/EnderburyPacifi"
        u8"c/FakaofoPacific/FijiPacific/FunafutiPacific/GalapagosPacific/GambierPacific/GuadalcanalPacific/Guam"
        u8"Pacific/HonoluluPacific/KiritimatiPacific/KosraePacific/KwajaleinPacific/MajuroPacific/MarquesasPaci"
        u8"fic/MidwayPacific/NauruPacific/NiuePacific/NorfolkPacific/NoumeaPacific/Pago_PagoPacific/PalauPacifi"
        u8"c/PitcairnPacific/PonapePacific/Port_MoresbyPacific/RarotongaPacific/SaipanPacific/TahitiPacific/Tar"
        u8"awaPacific/TongatapuPacific/TrukPacific/WakePacific/Wallis";
    inline constexpr const char8_t* ZoneIdChunks[] = {ZoneIdChunk0};
    inline constexpr uint16_t ZoneIdChunkSizes[] = {6658};
    inline constexpr char ZoneIdRefsChunk0[] =
        "AAAAAAAAAAAOAAAaAAAsAAA6AABHAABUAABhAABuAAB7AACKAACcAACsAAC4AADJAADVAADjAADvAAEDAAESAAEfAAEuAAE9AAFM"
        "AAFZAAFsAAF3AAGFAAGUAAGhAAGwAAG8AAHNAAHYAAHlAAH2AAIDAAIQAAIdAAIqAAI4AAJIAAJXAAJlAAJ0AAKBAAKSAAKkAAK1"
        "AALEAALSAALeAALtAAL5AAMKAAMaAAMpAAM6AANUAANyAAOJAAOjAAO9AAPWAAPvAAP8AAQMAAQZAAQvAAQ/AARMAARaAARuAAR/"
        "AASNAASaAASuAATDAATXAATlAAT0AAUFAAUUAAUiAAUxAAVCAAVXAAVsAAV7AAWNAAWcAAWqAAW5AAXNAAXbAAXvAAX9AAYMAAYc"
        "AAYsAAY8AAZPAAZiAAZzAAaEAAaTAAakAAa2AAbFAAbXAAboAAb5AAcHAAcWAAckAAc2AAdKAAdhAAd7AAeUAAepAAfCAAfZAAft"
        "AAf7AAgKAAgZAAgmAAg0AAhPAAhhAAhvAAh7AAiOAAigAAi1AAjDAAjSAAjgAAjvAAkBAAkSAAkiAAkxAAlCAAlQAAliAAl1AAmF"
        "AAmUAAmlAAm3AAnJAAnXAAnnAAnzAAoCAAodAAo4AApWAAplAApzAAqFAAqUAAqqAAq/AArSAArlAAr5AAsNAAsbAAspAAs5AAtL"
        "AAtbAAtrAAuAAAuRAAulAAuyAAvHAAvXAAvnAAv3AAwIAAwaAAwvAAxCAAxPAAxeAAxtAAx8AAyNAAyfAAyvAAy+AAzOAAzeAAz3"
        "AA0LAA0cAA0uAA0/AA1RAA1hAA1xAA2CAA2VAA2eAA2pAA2zAA2+AA3IAA3TAA3gAA3rAA33AA4DAA4MAA4YAA4kAA4vAA47AA5G"
        "AA5TAA5dAA5pAA52AA6AAA6JAA6TAA6gAA6uAA63AA7CAA7QAA7ZAA7lAA7xAA7+AA8MAA8WAA8kAA8wAA89AA9KAA9aAA9rAA93"
        "AA+CAA+MAA+YAA+lAA+wAA+7AA/HAA/YAA/oAA/xAA/6ABAJABAXABAlABAvABA8ABBKABBWABBhABBsABB5ABCHABCRABCeABCs"
        "ABC+ABDJABDWABDiABDtABD5ABEDABENABEdABEoABE1ABFDABFTABFfABFxABF9ABGMABGcABGrABG+ABHNABHdABHvABIFABIX"
        "ABInABI5ABJLABJgABJwABJ/ABKPABKhABK0ABLHABLWABLmABLtABL2ABMAABMKABMUABMdABMmABMvABM4ABNBABNKABNTABNc"
        "ABNlABNvABN5ABODABONABOXABOgABOpABOyABO7ABPEABPNABPWABPfABPmABPxABQBABQPABQfABQsABQ7ABRIABRZABRoABR4"
        "ABSHABSWABSlABS2ABTDABTTABTiABTxABUDABUSABUfABUxABU8ABVIABVVABVlABVyABWDABWQABWcABWsABW4ABXFABXSABXd"
        "ABXpABX5ABYGABYRABYcABYpABY6ABZJABZXABZoABZ1ABaBABaRABafABasABa8ABbIABbWABbjABbxABcBABcOABcbABcoABc7"
        "ABdIABdYABdkABdxABeBABeMABebABerABe5ABfHABfTABfjABf3ABgGABgUABghABgyABhBABhNABhdABhuABh9ABiQABicABis"
        "ABi+ABjMABjdABjrABj8ABkKABkXABkjABkyABlAABlRABleABluABl8ABmQABmhABmvABm9ABnLABncABnoABn0ABoC";
    inline constexpr const char* ZoneIdRefsChunks[] = {ZoneIdRefsChunk0};
    inline constexpr Packed ZoneIdRefs{ZoneIdRefsChunks, 13, 4};
    inline constexpr Text ZoneIdTexts{ZoneIdChunks, ZoneIdChunkSizes, ZoneIdRefs};

    // the canonical zones, sorted: their texts

    inline constexpr uint16_t ZoneIds[] = {
        1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29,
        30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56,
        57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83,
        84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103, 104, 105, 106, 107,
        108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128,
        129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149,
        150, 151, 152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169, 170,
        171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 181, 182, 183, 184, 185, 186, 187, 188, 189, 190, 191,
        192, 193, 194, 195, 196, 197, 198, 199, 200, 201, 202, 203, 204, 205, 206, 207, 208, 209, 210, 211, 212,
        213, 214, 215, 216, 217, 218, 219, 220, 221, 222, 223, 224, 225, 226, 227, 228, 229, 230, 231, 232, 233,
        234, 235, 236, 237, 238, 239, 240, 241, 242, 243, 244, 245, 246, 247, 248, 249, 250, 251, 252, 253, 254,
        255, 256, 257, 258, 259, 260, 261, 262, 263, 264, 265, 266, 267, 268, 269, 270, 271, 272, 273, 274, 275,
        276, 277, 278, 279, 280, 281, 282, 283, 284, 285, 286, 287, 288, 289, 290, 291, 292, 293, 294, 295, 296,
        297, 298, 299, 300, 301, 302, 303, 304, 305, 306, 307, 308, 309, 310, 311, 312, 313, 314, 315, 316, 317,
        318, 319, 320, 321, 322, 323, 324, 325, 326, 327, 328, 329, 330, 331, 332, 333, 334, 335, 336, 337, 338,
        339, 340, 341, 342, 343, 344, 345, 346, 347, 348, 349, 350, 351, 352, 353, 354, 355, 356, 357, 358, 359,
        360, 361, 362, 363, 364, 365, 366, 367, 368, 369, 370, 371, 372, 373, 374, 375, 376, 377, 378, 379, 380,
        381, 382, 383, 384, 385, 386, 387, 388, 389, 390, 391, 392, 393, 394, 395, 396, 397, 398, 399, 400, 401,
        402, 403, 404, 405, 406, 407, 408, 409, 410, 411, 412, 413, 414, 415, 416, 417, 418, 419, 420, 421, 422,
        423, 424, 425, 426, 427, 428, 429, 430, 431, 432, 433, 434, 435, 436, 437, 438, 439, 440, 441, 442, 443,
        444, 445, 446,
    };

    inline constexpr char8_t MetazoneChunk0[] =
        u8"AcreAfghanistanAfrica_CentralAfrica_EasternAfrica_FarWesternAfrica_SouthernAfrica_WesternAktyubinskA"
        u8"laskaAlaska_HawaiiAlmatyAmazonAmerica_CentralAmerica_EasternAmerica_MountainAmerica_PacificAnadyrApi"
        u8"aAqtauAqtobeArabianArgentinaArgentina_WesternArmeniaAshkhabadAtlanticAustralia_CentralAustralia_Cent"
        u8"ralWesternAustralia_EasternAustralia_WesternAzerbaijanAzoresBakuBangladeshBeringBhutanBoliviaBorneoB"
        u8"rasiliaBritishBruneiCape_VerdeCaseyChamorroChathamChileChinaChristmasCocosColombiaCookCubaDaccaDavis"
        u8"DominicanDumontDUrvilleDushanbeDutch_GuianaEast_TimorEasterEcuadorEurope_CentralEurope_EasternEurope"
        u8"_Further_EasternEurope_WesternFalklandFijiFrench_GuianaFrench_SouthernFrunzeGMTGalapagosGambierGeorg"
        u8"iaGilbert_IslandsGoose_BayGreenlandGreenland_CentralGreenland_EasternGreenland_WesternGuamGulfGuyana"
        u8"Hawaii_AleutianHong_KongHovdIndiaIndian_OceanIndochinaIndonesia_CentralIndonesia_EasternIndonesia_We"
        u8"sternIranIrishIrkutskIsraelJapanKamchatkaKarachiKazakhstanKazakhstan_EasternKazakhstan_WesternKizilo"
        u8"rdaKoreaKosraeKrasnoyarskKuybyshevKwajaleinKyrgystanLankaLiberiaLine_IslandsLord_HoweMacauMagadanMal"
        u8"ayaMalaysiaMaldivesMarquesasMarshall_IslandsMauritiusMawsonMexico_PacificMongoliaMoscowMyanmarNauruN"
        u8"epalNew_CaledoniaNew_ZealandNewfoundlandNiueNorfolkNoronhaNorth_MarianaNovosibirskOmskOralPakistanPa"
        u8"lauPapua_New_GuineaParaguayPeruPhilippinesPhoenix_IslandsPierre_MiquelonPitcairnPonapePyongyangQyzyl"
        u8"ordaReunionRotheraSakhalinSamaraSamarkandSamoaSeychellesShevchenkoSingaporeSolomonSouth_GeorgiaSurin"
        u8"ameSverdlovskSyowaTahitiTaipeiTajikistanTashkentTbilisiTokelauTongaTrukTurkeyTurkmenistanTuvaluUrals"
        u8"kUruguayUrumqiUzbekistanVanuatuVenezuelaVladivostokVolgogradVostokWakeWallisYakutskYekaterinburgYere"
        u8"vanYukon";
    inline constexpr const char8_t* MetazoneChunks[] = {MetazoneChunk0};
    inline constexpr uint16_t MetazoneChunkSizes[] = {1708};
    inline constexpr char MetazoneRefsChunk0[] =
        "AAAAAAAAAAAEAAAPAAAdAAArAAA8AABLAABZAABjAABpAAB2AAB8AACCAACRAACgAACwAAC/AADFAADJAADOAADUAADbAADkAAD1"
        "AAD8AAEFAAENAAEeAAE2AAFHAAFYAAFiAAFoAAFsAAF2AAF8AAGCAAGJAAGPAAGXAAGeAAGkAAGuAAGzAAG7AAHCAAHHAAHMAAHV"
        "AAHaAAHiAAHmAAHqAAHvAAH0AAH9AAILAAITAAIfAAIpAAIvAAI2AAJEAAJSAAJoAAJ2AAJ+AAKCAAKPAAKeAAKkAAKnAAKwAAK3"
        "AAK+AALNAALWAALfAALwAAMBAAMSAAMWAAMaAAMgAAMvAAM4AAM8AANBAANNAANWAANnAAN4AAOJAAONAAOSAAOZAAOfAAOkAAOt"
        "AAO0AAO+AAPQAAPiAAPrAAPwAAP2AAQBAAQKAAQTAAQcAAQhAAQoAAQ0AAQ9AARCAARJAARPAARXAARfAARoAAR4AASBAASHAASV"
        "AASdAASjAASqAASvAAS0AATBAATMAATYAATcAATjAATqAAT3AAUCAAUGAAUKAAUSAAUXAAUnAAUvAAUzAAU+AAVNAAVcAAVkAAVq"
        "AAVzAAV8AAWDAAWKAAWSAAWYAAWhAAWmAAWwAAW6AAXDAAXKAAXXAAXfAAXpAAXuAAX0AAX6AAYEAAYMAAYTAAYaAAYfAAYjAAYp"
        "AAY1AAY7AAZBAAZIAAZOAAZYAAZfAAZoAAZzAAZ8AAaCAAaGAAaMAAaTAAagAAanAAas";
    inline constexpr const char* MetazoneRefsChunks[] = {MetazoneRefsChunk0};
    inline constexpr Packed MetazoneRefs{MetazoneRefsChunks, 13, 4};
    inline constexpr Text MetazoneTexts{MetazoneChunks, MetazoneChunkSizes, MetazoneRefs};

    // the metazones, sorted

    inline constexpr uint16_t MetazoneIds[] = {
        1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29,
        30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56,
        57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83,
        84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103, 104, 105, 106, 107,
        108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128,
        129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149,
        150, 151, 152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169, 170,
        171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 181, 182, 183, 184, 185, 186, 187, 188, 189, 190,
    };

    // a zone's metazone today, + 1 (0: none)

    inline constexpr uint16_t ZoneMetazones[] = {
        71, 71, 4, 62, 4, 71, 7, 71, 71, 3, 7, 3, 63, 0, 62, 71, 71, 4, 4, 7, 0, 71, 3, 3, 6, 3, 4, 3, 3, 7, 7, 7,
        71, 7, 3, 3, 7, 3, 6, 6, 4, 71, 4, 7, 7, 71, 71, 7, 71, 63, 62, 3, 84, 9, 26, 26, 39, 22, 22, 22, 22, 22,
        22, 22, 26, 142, 39, 13, 26, 39, 13, 26, 12, 50, 15, 22, 15, 12, 14, 181, 22, 68, 14, 13, 13, 15, 14, 22,
        13, 15, 12, 26, 71, 190, 15, 15, 14, 26, 15, 1, 13, 15, 39, 26, 77, 26, 14, 26, 26, 13, 61, 83, 26, 52,
        123, 13, 14, 14, 13, 14, 14, 14, 14, 15, 14, 14, 22, 9, 14, 26, 37, 143, 16, 14, 26, 39, 13, 12, 26, 26,
        13, 123, 22, 13, 13, 9, 13, 146, 26, 13, 177, 26, 14, 14, 9, 134, 13, 13, 13, 13, 14, 162, 15, 14, 26, 12,
        26, 0, 13, 39, 13, 13, 1, 39, 46, 26, 39, 77, 9, 26, 131, 26, 26, 26, 26, 13, 13, 26, 16, 14, 26, 16, 190,
        13, 9, 30, 54, 56, 29, 122, 130, 0, 152, 164, 71, 184, 62, 21, 100, 0, 17, 100, 100, 174, 100, 21, 21, 31,
        89, 0, 63, 109, 41, 87, 187, 87, 0, 34, 59, 82, 167, 0, 63, 63, 85, 86, 95, 92, 91, 96, 2, 98, 139, 128,
        187, 106, 117, 117, 21, 47, 115, 90, 144, 82, 63, 106, 136, 137, 100, 89, 92, 104, 21, 100, 100, 126, 21,
        89, 153, 179, 104, 47, 159, 0, 166, 179, 74, 93, 36, 97, 0, 124, 178, 182, 89, 182, 187, 188, 24, 32, 26,
        65, 42, 65, 65, 71, 161, 71, 66, 27, 29, 27, 27, 28, 29, 29, 113, 29, 30, 29, 71, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 62, 62, 0, 63, 62, 62, 62, 62, 63, 62, 62, 63,
        62, 71, 62, 71, 63, 71, 173, 71, 63, 63, 0, 65, 62, 71, 62, 62, 62, 63, 125, 62, 125, 62, 62, 62, 62, 63,
        62, 154, 62, 62, 0, 125, 62, 63, 62, 63, 62, 0, 62, 62, 62, 63, 183, 62, 62, 62, 4, 88, 48, 49, 4, 69, 157,
        118, 121, 4, 151, 18, 130, 0, 45, 60, 180, 145, 170, 67, 175, 72, 73, 160, 44, 84, 112, 105, 120, 120, 119,
        156, 127, 132, 133, 129, 156, 140, 147, 148, 141, 51, 44, 165, 75, 171, 172, 185, 186,
    };

    // a zone's country, packed as txt::locale packs a region | 0x8000 when the location format names

    // the country (its only zone, or its primary one); 0: none

    inline constexpr uint16_t ZoneRegions[] = {
        32858, 32965, 32923, 32902, 32921, 33131, 32855, 32970, 32980, 33142, 32856, 32831, 32910, 33120, 154,
        32971, 33295, 33334, 32886, 32862, 32911, 33293, 32845, 33493, 33471, 33300, 33342, 33285, 33277, 85,
        33153, 32958, 33315, 32810, 85, 33483, 32974, 33145, 33111, 33307, 33296, 33110, 33070, 33312, 33151,
        33137, 32828, 32832, 33301, 33117, 33322, 33147, 586, 586, 32804, 32802, 72, 45, 45, 45, 45, 45, 45, 45,
        32818, 33225, 72, 375, 32824, 72, 32848, 82, 72, 32864, 586, 45, 82, 72, 375, 33367, 45, 32963, 33090, 586,
        375, 375, 82, 45, 32867, 82, 72, 32872, 201, 82, 82, 586, 586, 32889, 82, 72, 33303, 82, 72, 82, 201, 82,
        33311, 32961, 32973, 32977, 32906, 32982, 82, 32870, 375, 586, 586, 586, 586, 586, 586, 586, 586, 82, 82,
        33051, 45, 586, 586, 32839, 32837, 33205, 586, 586, 33305, 72, 33155, 72, 33125, 33136, 375, 375, 45, 586,
        375, 586, 375, 33213, 82, 375, 33360, 33138, 32841, 586, 586, 72, 586, 586, 586, 375, 33201, 33299, 586,
        33004, 33328, 72, 33218, 93, 82, 72, 82, 82, 72, 72, 32861, 32891, 72, 201, 586, 32834, 82, 33079, 33095,
        33371, 33365, 82, 32998, 201, 375, 82, 33369, 82, 82, 82, 586, 44, 44, 44, 48, 44, 44, 44, 44, 44, 0, 44,
        33291, 33448, 323, 33053, 507, 323, 323, 33321, 323, 33028, 32830, 32821, 33316, 507, 33094, 33072, 32836,
        33025, 507, 33103, 33306, 32826, 33320, 32800, 33318, 106, 451, 451, 32995, 365, 507, 247, 247, 33023,
        32801, 507, 33211, 33162, 507, 507, 33144, 376, 33088, 33134, 507, 247, 33208, 33186, 106, 507, 507, 507,
        323, 33073, 247, 33081, 33228, 323, 323, 33132, 33282, 33376, 507, 593, 33083, 32863, 33288, 507, 33331,
        33361, 32962, 33029, 32842, 33054, 507, 365, 95, 507, 33093, 507, 507, 507, 32808, 452, 32835, 154, 32871,
        32945, 452, 33030, 32976, 33289, 32941, 48, 48, 48, 48, 48, 48, 48, 48, 48, 48, 48, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 33158, 32799, 507, 32975, 33273, 32881,
        33292, 32827, 33269, 33005, 113, 33123, 32887, 33016, 32966, 32964, 32939, 33024, 33326, 33043, 507, 33336,
        507, 33220, 33290, 32959, 33113, 32922, 33139, 32819, 32847, 33122, 507, 33161, 32948, 33124, 32875, 33114,
        33031, 507, 33294, 32823, 507, 568, 33130, 32829, 33286, 32908, 32807, 507, 33101, 33363, 32815, 33112,
        507, 33212, 33002, 32857, 33126, 33026, 32873, 32852, 33078, 33314, 33284, 33141, 33140, 33463, 33259,
        33408, 33172, 439, 404, 93, 33383, 306, 33319, 32940, 33330, 138, 438, 33283, 32978, 586, 306, 175, 359,
        33127, 438, 580, 33164, 33167, 33152, 33149, 32814, 33223, 33214, 175, 439, 32860, 33135, 438, 306, 33323,
        175, 580, 33395,
    };

    inline constexpr char8_t ZoneAliasChunk0[] =
        u8"Africa/AbidjanAfrica/AccraAfrica/Addis_AbabaAfrica/AlgiersAfrica/AsmaraAfrica/AsmeraAfrica/BamakoAfr"
        u8"ica/BanguiAfrica/BanjulAfrica/BissauAfrica/BlantyreAfrica/BrazzavilleAfrica/BujumburaAfrica/CairoAfr"
        u8"ica/CasablancaAfrica/CeutaAfrica/ConakryAfrica/DakarAfrica/Dar_es_SalaamAfrica/DjiboutiAfrica/Douala"
        u8"Africa/El_AaiunAfrica/FreetownAfrica/GaboroneAfrica/HarareAfrica/JohannesburgAfrica/JubaAfrica/Kampa"
        u8"laAfrica/KhartoumAfrica/KigaliAfrica/KinshasaAfrica/LagosAfrica/LibrevilleAfrica/LomeAfrica/LuandaAf"
        u8"rica/LubumbashiAfrica/LusakaAfrica/MalaboAfrica/MaputoAfrica/MaseruAfrica/MbabaneAfrica/MogadishuAfr"
        u8"ica/MonroviaAfrica/NairobiAfrica/NdjamenaAfrica/NiameyAfrica/NouakchottAfrica/OuagadougouAfrica/Port"
        u8"o-NovoAfrica/Sao_TomeAfrica/TimbuktuAfrica/TripoliAfrica/TunisAfrica/WindhoekAmerica/AdakAmerica/Anc"
        u8"horageAmerica/AnguillaAmerica/AntiguaAmerica/AraguainaAmerica/Argentina/Buenos_AiresAmerica/Argentin"
        u8"a/CatamarcaAmerica/Argentina/ComodRivadaviaAmerica/Argentina/CordobaAmerica/Argentina/JujuyAmerica/A"
        u8"rgentina/La_RiojaAmerica/Argentina/MendozaAmerica/Argentina/Rio_GallegosAmerica/Argentina/SaltaAmeri"
        u8"ca/Argentina/San_JuanAmerica/Argentina/San_LuisAmerica/Argentina/TucumanAmerica/Argentina/UshuaiaAme"
        u8"rica/ArubaAmerica/AsuncionAmerica/AtikokanAmerica/AtkaAmerica/BahiaAmerica/Bahia_BanderasAmerica/Bar"
        u8"badosAmerica/BelemAmerica/BelizeAmerica/Blanc-SablonAmerica/Boa_VistaAmerica/BogotaAmerica/BoiseAmer"
        u8"ica/Buenos_AiresAmerica/Cambridge_BayAmerica/Campo_GrandeAmerica/CancunAmerica/CaracasAmerica/Catama"
        u8"rcaAmerica/CayenneAmerica/CaymanAmerica/ChicagoAmerica/ChihuahuaAmerica/Ciudad_JuarezAmerica/Coral_H"
        u8"arbourAmerica/CordobaAmerica/Costa_RicaAmerica/CrestonAmerica/CuiabaAmerica/CuracaoAmerica/Danmarksh"
        u8"avnAmerica/DawsonAmerica/Dawson_CreekAmerica/DenverAmerica/DetroitAmerica/DominicaAmerica/EdmontonAm"
        u8"erica/EirunepeAmerica/El_SalvadorAmerica/EnsenadaAmerica/Fort_NelsonAmerica/Fort_WayneAmerica/Fortal"
        u8"ezaAmerica/Glace_BayAmerica/GodthabAmerica/Goose_BayAmerica/Grand_TurkAmerica/GrenadaAmerica/Guadelo"
        u8"upeAmerica/GuatemalaAmerica/GuayaquilAmerica/GuyanaAmerica/HalifaxAmerica/HavanaAmerica/HermosilloAm"
        u8"erica/Indiana/IndianapolisAmerica/Indiana/KnoxAmerica/Indiana/MarengoAmerica/Indiana/PetersburgAmeri"
        u8"ca/Indiana/Tell_CityAmerica/Indiana/VevayAmerica/Indiana/VincennesAmerica/Indiana/WinamacAmerica/Ind"
        u8"ianapolisAmerica/InuvikAmerica/IqaluitAmerica/JamaicaAmerica/JujuyAmerica/JuneauAmerica/Kentucky/Lou"
        u8"isvilleAmerica/Kentucky/MonticelloAmerica/Knox_INAmerica/KralendijkAmerica/La_PazAmerica/LimaAmerica"
        u8"/Los_AngelesAmerica/LouisvilleAmerica/Lower_PrincesAmerica/MaceioAmerica/ManaguaAmerica/ManausAmeric"
        u8"a/MarigotAmerica/MartiniqueAmerica/MatamorosAmerica/MazatlanAmerica/MendozaAmerica/MenomineeAmerica/"
        u8"MeridaAmerica/MetlakatlaAmerica/Mexico_CityAmerica/MiquelonAmerica/MonctonAmerica/MonterreyAmerica/M"
        u8"ontevideoAmerica/MontrealAmerica/MontserratAmerica/NassauAmerica/New_YorkAmerica/NipigonAmerica/Nome"
        u8"America/NoronhaAmerica/North_Dakota/BeulahAmerica/North_Dakota/CenterAmerica/North_Dakota/New_SalemA"
        u8"merica/NuukAmerica/OjinagaAmerica/PanamaAmerica/PangnirtungAmerica/ParamariboAmerica/PhoenixAmerica/"
        u8"Port-au-PrinceAmerica/Port_of_SpainAmerica/Porto_AcreAmerica/Porto_VelhoAmerica/Puerto_RicoAmerica/P"
        u8"unta_ArenasAmerica/Rainy_RiverAmerica/Rankin_InletAmerica/RecifeAmerica/ReginaAmerica/ResoluteAmeric"
        u8"a/Rio_BrancoAmerica/RosarioAmerica/Santa_IsabelAmerica/SantaremAmerica/SantiagoAmerica/Santo_Domingo"
        u8"America/Sao_PauloAmerica/ScoresbysundAmerica/ShiprockAmerica/SitkaAmerica/St_BarthelemyAmerica/St_Jo"
        u8"hnsAmerica/St_KittsAmerica/St_LuciaAmerica/St_ThomasAmerica/St_VincentAmerica/Swift_CurrentAmerica/T"
        u8"egucigalpaAmerica/ThuleAmerica/Thunder_BayAmerica/TijuanaAmerica/TorontoAmerica/TortolaAmerica/Vanco"
        u8"uverAmerica/VirginAmerica/WhitehorseAmerica/WinnipegAmerica/YakutatAmerica/YellowknifeAntarctica/Cas"
        u8"eyAntarctica/DavisAntarctica/DumontDUrvilleAntarctica/MacquarieAntarctica/MawsonAntarctica/McMurdoAn"
        u8"tarctica/PalmerAntarctica/RotheraAntarctica/South_PoleAntarctica/SyowaAntarctica/TrollAntarctica/Vos"
        u8"tokArctic/LongyearbyenAsia/AdenAsia/AlmatyAsia/AmmanAsia/AnadyrAsia/AqtauAsia/AqtobeAsia/AshgabatAsi"
        u8"a/AshkhabadAsia/AtyrauAsia/BaghdadAsia/BahrainAsia/BakuAsia/BangkokAsia/BarnaulAsia/BeirutAsia/Bishk"
        u8"ekAsia/BruneiAsia/CalcuttaAsia/ChitaAsia/ChoibalsanAsia/ChongqingAsia/ChungkingAsia/ColomboAsia/Dacc"
        u8"aAsia/DamascusAsia/DhakaAsia/DiliAsia/DubaiAsia/DushanbeAsia/FamagustaAsia/GazaAsia/HarbinAsia/Hebro"
        u8"nAsia/Ho_Chi_MinhAsia/Hong_KongAsia/HovdAsia/IrkutskAsia/IstanbulAsia/JakartaAsia/JayapuraAsia/Jerus"
        u8"alemAsia/KabulAsia/KamchatkaAsia/KarachiAsia/KashgarAsia/KathmanduAsia/KatmanduAsia/KhandygaAsia/Kol"
        u8"kataAsia/KrasnoyarskAsia/Kuala_LumpurAsia/KuchingAsia/KuwaitAsia/MacaoAsia/MacauAsia/MagadanAsia/Mak"
        u8"assarAsia/ManilaAsia/MuscatAsia/NicosiaAsia/NovokuznetskAsia/NovosibirskAsia/OmskAsia/OralAsia/Phnom"
        u8"_PenhAsia/PontianakAsia/PyongyangAsia/QatarAsia/QostanayAsia/QyzylordaAsia/RangoonAsia/RiyadhAsia/Sa"
        u8"igonAsia/SakhalinAsia/SamarkandAsia/SeoulAsia/ShanghaiAsia/SingaporeAsia/SrednekolymskAsia/TaipeiAsi"
        u8"a/TashkentAsia/TbilisiAsia/TehranAsia/Tel_AvivAsia/ThimbuAsia/ThimphuAsia/TokyoAsia/TomskAsia/Ujung_"
        u8"PandangAsia/UlaanbaatarAsia/Ulan_BatorAsia/UrumqiAsia/Ust-NeraAsia/VientianeAsia/VladivostokAsia/Yak"
        u8"utskAsia/YangonAsia/YekaterinburgAsia/YerevanAtlantic/AzoresAtlantic/BermudaAtlantic/CanaryAtlantic/"
        u8"Cape_VerdeAtlantic/FaeroeAtlantic/FaroeAtlantic/Jan_MayenAtlantic/MadeiraAtlantic/ReykjavikAtlantic/"
        u8"South_GeorgiaAtlantic/St_HelenaAtlantic/StanleyAustralia/ACTAustralia/AdelaideAustralia/BrisbaneAust"
        u8"ralia/Broken_HillAustralia/CanberraAustralia/CurrieAustralia/DarwinAustralia/EuclaAustralia/HobartAu"
        u8"stralia/LHIAustralia/LindemanAustralia/Lord_HoweAustralia/MelbourneAustralia/NSWAustralia/NorthAustr"
        u8"alia/PerthAustralia/QueenslandAustralia/SouthAustralia/SydneyAustralia/TasmaniaAustralia/VictoriaAus"
        u8"tralia/WestAustralia/YancowinnaBrazil/AcreBrazil/DeNoronhaBrazil/EastBrazil/WestCETCST6CDTCanada/Atl"
        u8"anticCanada/CentralCanada/East-SaskatchewanCanada/EasternCanada/MountainCanada/NewfoundlandCanada/Pa"
        u8"cificCanada/SaskatchewanCanada/YukonChile/ContinentalChile/EasterIslandCubaEETESTEST5EDTEgyptEireEtc"
        u8"/GMTEtc/GMT+0Etc/GMT+1Etc/GMT+10Etc/GMT+11Etc/GMT+12Etc/GMT+2Etc/GMT+3Etc/GMT+4Etc/GMT+5Etc/GMT+6Etc"
        u8"/GMT+7Etc/GMT+8Etc/GMT+9Etc/GMT-0Etc/GMT-1Etc/GMT-10Etc/GMT-11Etc/GMT-12Etc/GMT-13Etc/GMT-14Etc/GMT-"
        u8"2Etc/GMT-3Etc/GMT-4Etc/GMT-5Etc/GMT-6Etc/GMT-7Etc/GMT-8Etc/GMT-9Etc/GMT0Etc/GreenwichEtc/UCTEtc/UTCE"
        u8"tc/UniversalEtc/UnknownEtc/ZuluEurope/AmsterdamEurope/AndorraEurope/AstrakhanEurope/AthensEurope/Bel"
        u8"fastEurope/BelgradeEurope/BerlinEurope/BratislavaEurope/BrusselsEurope/BucharestEurope/BudapestEurop"
        u8"e/BusingenEurope/ChisinauEurope/CopenhagenEurope/DublinEurope/GibraltarEurope/GuernseyEurope/Helsink"
        u8"iEurope/Isle_of_ManEurope/IstanbulEurope/JerseyEurope/KaliningradEurope/KievEurope/KirovEurope/KyivE"
        u8"urope/LisbonEurope/LjubljanaEurope/LondonEurope/LuxembourgEurope/MadridEurope/MaltaEurope/MariehamnE"
        u8"urope/MinskEurope/MonacoEurope/MoscowEurope/NicosiaEurope/OsloEurope/ParisEurope/PodgoricaEurope/Pra"
        u8"gueEurope/RigaEurope/RomeEurope/SamaraEurope/San_MarinoEurope/SarajevoEurope/SaratovEurope/Simferopo"
        u8"lEurope/SkopjeEurope/SofiaEurope/StockholmEurope/TallinnEurope/TiraneEurope/TiraspolEurope/Ulyanovsk"
        u8"Europe/UzhgorodEurope/VaduzEurope/VaticanEurope/ViennaEurope/VilniusEurope/VolgogradEurope/WarsawEur"
        u8"ope/ZagrebEurope/ZaporozhyeEurope/ZurichFactoryGBGB-EireGMTGMT+0GMT-0GMT0GreenwichHSTHongkongIceland"
        u8"Indian/AntananarivoIndian/ChagosIndian/ChristmasIndian/CocosIndian/ComoroIndian/KerguelenIndian/Mahe"
        u8"Indian/MaldivesIndian/MauritiusIndian/MayotteIndian/ReunionIranIsraelJamaicaJapanKwajaleinLibyaMETMS"
        u8"TMST7MDTMexico/BajaNorteMexico/BajaSurMexico/GeneralNZNZ-CHATNavajoPRCPST8PDTPacific/ApiaPacific/Auc"
        u8"klandPacific/BougainvillePacific/ChathamPacific/ChuukPacific/EasterPacific/EfatePacific/EnderburyPac"
        u8"ific/FakaofoPacific/FijiPacific/FunafutiPacific/GalapagosPacific/GambierPacific/GuadalcanalPacific/G"
        u8"uamPacific/HonoluluPacific/JohnstonPacific/KantonPacific/KiritimatiPacific/KosraePacific/KwajaleinPa"
        u8"cific/MajuroPacific/MarquesasPacific/MidwayPacific/NauruPacific/NiuePacific/NorfolkPacific/NoumeaPac"
        u8"ific/Pago_PagoPacific/PalauPacific/PitcairnPacific/PohnpeiPacific/PonapePacific/Port_MoresbyPacific/"
        u8"RarotongaPacific/SaipanPacific/SamoaPacific/TahitiPacific/TarawaPacific/TongatapuPacific/TrukPacific"
        u8"/WakePacific/WallisPacific/YapPolandPortugalROCROKSingaporeTurkeyUCTUS/AlaskaUS/AleutianUS/ArizonaUS"
        u8"/CentralUS/East-IndianaUS/EasternUS/HawaiiUS/Indiana-StarkeUS/MichiganUS/MountainUS/PacificUS/Pacifi"
        u8"c-NewUS/SamoaUTCUniversalW-SUWETZulu";
    inline constexpr const char8_t* ZoneAliasChunks[] = {ZoneAliasChunk0};
    inline constexpr uint16_t ZoneAliasChunkSizes[] = {8536};
    inline constexpr char ZoneAliasRefsChunk0[] =
        "AAAAAAAAAAAOAAAaAAAsAAA6AABHAABUAABhAABuAAB7AACIAACXAACpAAC5AADFAADWAADiAADwAAD8AAEQAAEfAAEsAAE7AAFK"
        "AAFZAAFmAAF5AAGEAAGSAAGhAAGuAAG9AAHJAAHaAAHlAAHyAAIDAAIQAAIdAAIqAAI3AAJFAAJVAAJkAAJyAAKBAAKOAAKfAAKx"
        "AALCAALRAALgAALuAAL6AAMJAAMVAAMmAAM2AANFAANWAAN0AAOPAAOvAAPIAAPfAAP5AAQSAAQwAARHAARhAAR7AASUAAStAAS6"
        "AATKAATaAATmAATzAAUJAAUZAAUmAAU0AAVIAAVZAAVnAAV0AAWIAAWdAAWxAAW/AAXOAAXfAAXuAAX8AAYLAAYcAAYxAAZGAAZV"
        "AAZnAAZ2AAaEAAaTAAanAAa1AAbJAAbXAAbmAAb2AAcGAAcWAAcpAAc5AAdMAAdeAAdvAAeAAAePAAegAAeyAAfBAAfTAAfkAAf1"
        "AAgDAAgSAAggAAgyAAhOAAhiAAh5AAiTAAisAAjBAAjaAAjxAAkFAAkTAAkiAAkxAAk+AAlMAAlnAAmCAAmRAAmjAAmxAAm9AAnQ"
        "AAniAAn3AAoFAAoUAAoiAAoxAApDAApUAApkAApzAAqEAAqSAAqkAAq3AArHAArWAArnAAr5AAsJAAsbAAspAAs5AAtIAAtUAAtj"
        "AAt+AAuZAAu3AAvDAAvSAAvgAAvzAAwFAAwUAAwqAAw/AAxRAAxkAAx3AAyLAAyeAAyyAAzAAAzOAAzeAAzwAAz/AA0TAA0jAA0z"
        "AA1IAA1ZAA1tAA19AA2KAA2fAA2vAA2/AA3PAA3gAA3yAA4HAA4aAA4nAA46AA5JAA5YAA5nAA54AA6GAA6YAA6oAA63AA7KAA7a"
        "AA7qAA8DAA8XAA8oAA86AA9LAA9dAA9yAA+CAA+SAA+jAA+2AA+/AA/KAA/UAA/fAA/pAA/0ABABABAPABAaABAmABAyABA7ABBH"
        "ABBTABBeABBqABB1ABCCABCMABCbABCpABC3ABDDABDNABDaABDkABDtABD3ABEEABESABEbABEmABExABFBABFPABFYABFkABFx"
        "ABF9ABGKABGYABGiABGwABG8ABHIABHWABHjABHwABH8ABIMABIdABIpABI0ABI+ABJIABJUABJhABJsABJ3ABKDABKUABKkABKt"
        "ABK2ABLFABLTABLhABLrABL4ABMGABMSABMdABMoABM1ABNDABNNABNaABNoABN6ABOFABOSABOeABOpABO2ABPBABPNABPXABPh"
        "ABPzABQDABQSABQdABQqABQ4ABRIABRUABRfABRxABR9ABSMABScABSrABS+ABTNABTbABTtABT9ABUPABUlABU3ABVHABVUABVm"
        "ABV4ABWNABWfABWvABW/ABXOABXeABXrABX9ABYQABYjABYwABY/ABZOABZiABZxABaBABaTABalABazABbHABbSABbiABbtABb4"
        "ABb7ABcCABcRABcfABc3ABdFABdUABdnABd1ABeIABeUABelABe3ABe7ABe+ABfBABfIABfNABfRABfYABfhABfqABf0ABf+ABgI"
        "ABgRABgaABgjABgsABg1ABg+ABhHABhQABhZABhiABhsABh2ABiAABiKABiUABidABimABivABi4ABjBABjKABjTABjcABjkABjx"
        "ABj4ABj/ABkMABkXABkfABkvABk9ABlNABlaABloABl3ABmEABmVABmkABm0ABnDABnSABnhABnyABn/ABoPABoeABotABo/ABpO"
        "ABpbABptABp4ABqEABqPABqcABqsABq5ABrKABrXABrjABrzABr/ABsMABsZABsnABsyABs+ABtOABtbABtmABtxABt+ABuPABue"
        "ABusABu9ABvKABvWABvmABv0ABwBABwQABwgABwvABw7ABxJABxWABxkABx0AByBAByOAByfABysAByzABy1ABy8ABy/ABzEABzJ"
        "ABzNABzWABzZABzhABzoABz7AB0IAB0YAB0kAB0xAB1BAB1MAB1bAB1rAB15AB2HAB2LAB2RAB2YAB2dAB2mAB2rAB2uAB2xAB24"
        "AB3IAB3WAB3kAB3mAB3tAB3zAB32AB39AB4JAB4ZAB4tAB48AB5JAB5XAB5kAB51AB6EAB6QAB6gAB6xAB7AAB7TAB7fAB7vAB7/"
        "AB8NAB8fAB8tAB8+AB9MAB9dAB9rAB94AB+EAB+TAB+hAB+yAB+/AB/PAB/eAB/sACAAACARACAfACAsACA6ACBIACBZACBlACBx"
        "ACB/ACCKACCQACCYACCbACCeACCnACCtACCwACC5ACDEACDOACDYACDnACDxACD6ACELACEWACEhACErACE5ACFBACFEACFNACFR"
        "ACFUACFY";
    inline constexpr const char* ZoneAliasRefsChunks[] = {ZoneAliasRefsChunk0};
    inline constexpr Packed ZoneAliasRefs{ZoneAliasRefsChunks, 13, 4};
    inline constexpr Text ZoneAliasTexts{ZoneAliasChunks, ZoneAliasChunkSizes, ZoneAliasRefs};

    // every name of a zone (the IANA ones and CLDR's old ones), sorted, and its canonical zone

    inline constexpr uint16_t ZoneAliasNames[] = {
        1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29,
        30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56,
        57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83,
        84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103, 104, 105, 106, 107,
        108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128,
        129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149,
        150, 151, 152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169, 170,
        171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 181, 182, 183, 184, 185, 186, 187, 188, 189, 190, 191,
        192, 193, 194, 195, 196, 197, 198, 199, 200, 201, 202, 203, 204, 205, 206, 207, 208, 209, 210, 211, 212,
        213, 214, 215, 216, 217, 218, 219, 220, 221, 222, 223, 224, 225, 226, 227, 228, 229, 230, 231, 232, 233,
        234, 235, 236, 237, 238, 239, 240, 241, 242, 243, 244, 245, 246, 247, 248, 249, 250, 251, 252, 253, 254,
        255, 256, 257, 258, 259, 260, 261, 262, 263, 264, 265, 266, 267, 268, 269, 270, 271, 272, 273, 274, 275,
        276, 277, 278, 279, 280, 281, 282, 283, 284, 285, 286, 287, 288, 289, 290, 291, 292, 293, 294, 295, 296,
        297, 298, 299, 300, 301, 302, 303, 304, 305, 306, 307, 308, 309, 310, 311, 312, 313, 314, 315, 316, 317,
        318, 319, 320, 321, 322, 323, 324, 325, 326, 327, 328, 329, 330, 331, 332, 333, 334, 335, 336, 337, 338,
        339, 340, 341, 342, 343, 344, 345, 346, 347, 348, 349, 350, 351, 352, 353, 354, 355, 356, 357, 358, 359,
        360, 361, 362, 363, 364, 365, 366, 367, 368, 369, 370, 371, 372, 373, 374, 375, 376, 377, 378, 379, 380,
        381, 382, 383, 384, 385, 386, 387, 388, 389, 390, 391, 392, 393, 394, 395, 396, 397, 398, 399, 400, 401,
        402, 403, 404, 405, 406, 407, 408, 409, 410, 411, 412, 413, 414, 415, 416, 417, 418, 419, 420, 421, 422,
        423, 424, 425, 426, 427, 428, 429, 430, 431, 432, 433, 434, 435, 436, 437, 438, 439, 440, 441, 442, 443,
        444, 445, 446, 447, 448, 449, 450, 451, 452, 453, 454, 455, 456, 457, 458, 459, 460, 461, 462, 463, 464,
        465, 466, 467, 468, 469, 470, 471, 472, 473, 474, 475, 476, 477, 478, 479, 480, 481, 482, 483, 484, 485,
        486, 487, 488, 489, 490, 491, 492, 493, 494, 495, 496, 497, 498, 499, 500, 501, 502, 503, 504, 505, 506,
        507, 508, 509, 510, 511, 512, 513, 514, 515, 516, 517, 518, 519, 520, 521, 522, 523, 524, 525, 526, 527,
        528, 529, 530, 531, 532, 533, 534, 535, 536, 537, 538, 539, 540, 541, 542, 543, 544, 545, 546, 547, 548,
        549, 550, 551, 552, 553, 554, 555, 556, 557, 558, 559, 560, 561, 562, 563, 564, 565, 566, 567, 568, 569,
        570, 571, 572, 573, 574, 575, 576, 577, 578, 579, 580, 581, 582, 583, 584, 585, 586, 587, 588, 589, 590,
        591, 592, 593, 594, 595, 596, 597, 598, 599, 600,
    };

    inline constexpr uint16_t ZoneAliasZones[] = {
        0, 1, 2, 3, 4, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27,
        28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 5, 49, 50, 51, 52, 53,
        54, 55, 56, 75, 80, 80, 87, 126, 57, 142, 58, 59, 60, 61, 62, 63, 64, 65, 86, 52, 66, 67, 68, 69, 70, 71,
        72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98,
        99, 100, 188, 101, 122, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 122, 115, 116,
        117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 133, 128, 115, 129, 130, 131, 132, 133, 134, 135,
        136, 137, 138, 139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 189, 151, 152, 153, 189, 154,
        155, 156, 157, 158, 104, 159, 160, 124, 161, 162, 163, 164, 172, 165, 166, 167, 193, 168, 169, 170, 171,
        172, 87, 188, 173, 174, 175, 176, 177, 95, 178, 179, 180, 181, 182, 183, 184, 185, 186, 187, 189, 188, 189,
        190, 191, 183, 192, 193, 194, 98, 195, 196, 197, 198, 199, 200, 201, 202, 409, 203, 204, 205, 206, 207,
        208, 209, 210, 211, 212, 213, 213, 214, 215, 216, 217, 218, 219, 220, 221, 222, 223, 224, 281, 271, 271,
        225, 227, 226, 227, 228, 229, 230, 231, 232, 271, 233, 267, 234, 235, 236, 357, 237, 238, 239, 240, 241,
        242, 282, 243, 243, 244, 223, 245, 246, 247, 248, 249, 249, 250, 251, 252, 253, 254, 255, 256, 257, 258,
        259, 260, 261, 262, 263, 264, 265, 266, 267, 268, 269, 270, 271, 272, 273, 274, 275, 276, 277, 239, 278,
        278, 279, 280, 251, 281, 281, 282, 283, 284, 285, 286, 265, 287, 288, 289, 290, 291, 292, 293, 293, 206,
        294, 295, 296, 297, 298, 309, 299, 300, 301, 309, 304, 302, 303, 304, 306, 305, 306, 307, 309, 302, 308,
        300, 299, 309, 304, 307, 308, 301, 172, 155, 176, 137, 346, 83, 112, 193, 170, 189, 98, 180, 191, 170, 192,
        174, 412, 113, 342, 160, 153, 12, 352, 310, 310, 311, 312, 313, 314, 315, 316, 317, 318, 319, 320, 321,
        322, 310, 323, 324, 325, 326, 327, 328, 329, 330, 331, 332, 333, 334, 335, 336, 310, 310, 337, 337, 337,
        338, 337, 339, 340, 341, 342, 364, 343, 344, 345, 346, 347, 348, 349, 350, 351, 352, 353, 354, 355, 356,
        357, 358, 359, 360, 361, 360, 362, 363, 364, 365, 366, 367, 368, 369, 370, 371, 254, 372, 373, 374, 375,
        376, 377, 378, 379, 380, 381, 382, 383, 384, 385, 386, 387, 350, 388, 360, 389, 390, 391, 392, 393, 394,
        395, 360, 396, 338, 364, 364, 310, 310, 310, 310, 310, 422, 234, 295, 397, 398, 399, 400, 401, 402, 403,
        404, 405, 406, 407, 277, 239, 125, 279, 425, 49, 346, 162, 95, 188, 141, 146, 409, 411, 95, 271, 132, 408,
        409, 410, 411, 443, 412, 413, 414, 415, 416, 417, 418, 419, 420, 421, 422, 422, 414, 423, 424, 425, 426,
        427, 428, 429, 430, 431, 432, 433, 434, 435, 436, 436, 437, 438, 439, 433, 440, 441, 442, 443, 444, 445,
        443, 394, 362, 274, 270, 272, 357, 337, 53, 52, 162, 83, 122, 153, 422, 115, 96, 95, 132, 132, 433, 337,
        337, 371, 362, 337,
    };
}
