//------------------------------------------------------------------------------
// SGCL: Smart Garbage Collection Library
// Copyright (c) 2022-2026 Sebastian Nibisz
// SPDX-License-Identifier: Apache-2.0
//------------------------------------------------------------------------------
#pragma once

#include "array.h"
#include "atomic.h"
#include "atomic_ref.h"
#include "channel.h"
#include "collector.h"
#include "concurrent_map.h"
#include "concurrent_queue.h"
#include "concurrent_set.h"
#include "concurrent_stack.h"
#include "concurrent_unordered_map.h"
#include "concurrent_unordered_set.h"
#include "config.h"
#include "copy_on_write.h"
#include "coroutine.h"
#include "deque.h"
#include "expiry_queue.h"
#include "forward_list.h"
#include "list.h"
#include "make_tracked.h"
#include "map.h"
#include "multimap.h"
#include "multiset.h"
#include "queue.h"
#include "root_ptr.h"
#include "set.h"
#include "stack.h"
#include "string.h"
#include "tracked_ptr.h"
#include "unique_ptr.h"
#include "unordered_map.h"
#include "unordered_multimap.h"
#include "unordered_multiset.h"
#include "unordered_set.h"
#include "vector.h"
#include "weak_map.h"
#include "weak_ptr.h"
#include "weak_set.h"

// over the pointers and the maker above
#include "aliases.h"
#include "any.h"
#include "expected.h"
#include "function.h"
#include "variant.h"
