//------------------------------------------------------------------------------
// SGCL: a C++20 application platform
// Copyright (c) 2022-2026 Sebastian Nibisz
// SPDX-License-Identifier: Apache-2.0
//------------------------------------------------------------------------------
#pragma once
#include "detail/registry.h"

#include <cstdint>

// The display names of the locale as (অসমীয়া), CLDR 46.0: the names of languages,
// regions, scripts, currencies and time zones in it.
// Including this header is all a program does: txt::locale::display_name,
// region::display_name, script::display_name and currency::display_name then
// answer in this language. Generated by tools/cldr_tables.py: do not edit.
namespace sgcl::txt::detail::names::l_as {
    inline constexpr char8_t NameChunk0[] =
        u8"আফাৰআবখাজিয়ানআচিনিজআদাংমেআদিগেআফ্ৰিকানছ্আঘেমআইনুআকানআলেউটদাক্ষিণাত্য আল্টাইআমহাৰিকআৰ্গোনিজঅ’ব’ল’আঙ্"
        u8"গিকাআৰবীআধুনিক মানক আৰবীমাপুচেআৰাপাহোনাজডি আৰবীঅসমীয়াআছুএষ্টুৰীয়আতিকামেকআভেৰিকঅৱধীআয়মাৰাআজেৰবাইজা"
        u8"নীবাছখিৰবালিনীজবাছাবেলাৰুছীয়বেম্বাবেনাবুলগেৰীয়হাৰয়ানভিভোজপুৰীবিছলামাবিনিছিক্সিকাআনিবামবাৰাবাংলাতি"
        u8"ব্বতীব্ৰেটনবড়োবছনীয়বগিনীজব্লিনকাতালানকায়ুগাচাক্\u200Cমাচেচেনচিবুৱানোচিগাচামোৰোচুকিজমাৰিচোক্টাউচিপ"
        u8"েউয়ানচেৰোকিচাইয়েনচেণ্ট্ৰেল কুৰ্ডিচচিলক’টিনকোৰ্ছিকানমিচিফদাক্ষিণাত্য ইষ্ট ক্ৰীপ্লেইনছ ক্ৰীনৰ্দাৰ্ন "
        u8"ইষ্ট ক্ৰীমুজ ক্ৰীকেৰ’লিনা আলগংকিয়ানছেছেলৱা ক্ৰিওল ফ্ৰেন্সচেকস্বাম্পী ক্ৰীচাৰ্চ শ্লেভিকচুভাচৱেলচডেনি"
        u8"চডাকোটাদাৰ্গৱাতেইতাজাৰ্মানঅষ্ট্ৰেলিয়ান জাৰ্মানছুইচ হাই জাৰ্মানডোগ্ৰিবঝাৰ্মাডোগ্ৰীল’ৱাৰ ছোৰ্বিয়ানডু"
        u8"ৱালাদিবেহিজোলা-ফ’নিজোংখাদাজাগাএম্বুইৱেএফিকএকাজুকগ্ৰীকইংৰাজীঅষ্ট্ৰেলিয়ান ইংৰাজীকানাডিয়ান ইংৰাজীব্ৰি"
        u8"টিছ ইংৰাজীআমেৰিকান ইংৰাজীএস্পেৰান্তোস্পেনিচলেটিন আমেৰিকান স্পেনিচইউৰোপীয়ান স্পেনিচমেক্সিকান স্পেনিচ"
        u8"এষ্টোনিয়বাস্কইওন্দোফাৰ্ছীদাৰিফুলাহফিনিচফিলিপিনোফিজিয়ানফাৰোইজফ’নফ্ৰেন্সকানাডিয়ান ফ্ৰেন্সছুইচ ফ্ৰেন"
        u8"্সকেজ’ন ফৰাছীনৰ্দাৰ্ন ফ্ৰিছিয়ানফ্ৰিউলিয়ানৱেষ্টাৰ্ণ ফ্ৰিছিয়ানআইৰিচগাস্কটিচ গেইলিকগীজগিলবাৰ্টিছগেলি"
        u8"চিয়ানগুৱাৰাণীগোৰোন্তালোছুইচ জাৰ্মানগুজৰাটীগুছিমেংক্সজিউইচিনহাউছাহেইডাহাৱাইদাক্ষিণাত্যৰ হাইডাহিব্ৰুহ"
        u8"িন্দীহিলিগায়নোনহমংক্ৰোৱেচিয়ানআপাৰ ছোৰ্বিয়ানহেইটিয়ান ক্ৰিয়লহাঙ্গেৰিয়ানহুপাহেলকোমেলেমআৰ্মেনীয়হে"
        u8"ৰেৰোইণ্টাৰলিংগুৱাইবানইবিবিওইণ্ডোনেচিয়ইণ্টাৰলিংগুৱেইগ্বোছিচুৱান ইৱেষ্টাৰ্ণ কানাডিয়ান ইনক্টিটুটইলোকো"
        u8"ইংগুচইডোআইচলেণ্ডিকইটালিয়ানইনুক্টিটুটজাপানীলোজ্বাননগোম্বামেকহেমজাভানীজৰ্জিয়ানকাবাইলকাচিনজজুকাম্বাকা"
        u8"বাৰ্ডিয়ানত্যাপমাকোণ্ডকাবুভেৰ্ডিয়ানুকোৰোকেইংগাংখাচিকোয়াৰ চিনিকিকুয়ুকুয়ানিয়ামাকাজাখকাকোকালালিছুট"
        u8"কালেনজিনখমেৰকিম্বুন্দুকানাড়াকোৰিয়ানকোংকণীকেপেলকানুৰিকাৰাচে-বাল্কাৰকেৰেলিয়ানকুৰুখকাশ্মিৰীচাম্বালাব"
        u8"াফিয়াকোলোগনিয়ানকুৰ্ডিচকুমিককোমিকোৰ্নিচক্বাকৱালাকুভিকিৰ্গিজলেটিনলাডিনোলাংগিলাক্সেমবাৰ্গিচলেজঘিয়ানগ"
        u8"ান্দালিম্বুৰ্গিচলিংগুৰিয়ানলিল্লোৱেটলাকোটাল’ম্বাৰ্ডলিংগালালাওলুইজিয়ানা কেৰ’ললোজিউদীচ্য লুৰিচামিয়াল"
        u8"িথুৱানিয়ানলুবা-কাটাংগালুবা-লুলুৱালুণ্ডালুওমিজোলুইয়ালাটভিয়ানমাদুৰেছেমাগাহিমৈথিলীমাকাছাৰমাছাইমোক্সা"
        u8"মেণ্ডেমেৰুমৰিছিয়ানমালাগাছীমাখুৱা-মিট্টোমেটামাৰ্চলিজমাওৰিমিকমেকমিনাংকাবাউমেচিডোনীয়মালায়ালমমংগোলীয়"
        u8"মণিপুৰীইন্নু-আইমুনমোহোকমোছিমাৰাঠীমালয়মাল্টিজমুণ্ডাংএকাধিক ভাষাক্ৰীকমিৰাণ্ডিজবাৰ্মীজএৰজিয়ামাজেন্দাৰ"
        u8"ানিনাউৰুনিয়াপোলিটেননামানৰৱেজিয়ান বোকমালউত্তৰ নিবেবেলেল’ জাৰ্মাননেপালীনেৱাৰিএন্দোঙ্গানিয়াছনিয়ুৱান"
        u8"ডাচফ্লেমিচকোৱাছিঅ’নৰৱেজিয়ান নায়নোৰ্স্কনিয়েম্বোননৰৱেজিয়াননোগাইএন্কোদক্ষিণ দেবেলউদীচ্য ছোথোনুয়েৰন"
        u8"াভাজোন্যাঞ্জান্যানকোলঅ’চিটাননৰ্থ-ৱেষ্টাৰ্ণ অজিবৱাচেন্ট্ৰেক অজিবৱাঅ’জি-ক্ৰীৱেষ্টাৰ্ণ অজিবৱাঅ’কানাগানও"
        u8"ৰোমোওড়িয়াওছেটিকপাঞ্জাবীপংগাছিনানপাম্পান্গাপাপিয়ামেণ্টোপালাউৱাননাইজেৰিয়ান পিজিনপিজিনপ’লিচমালিছীট-"
        u8"পাছামাকু’ডীপ্ৰুছিয়ানপুস্তপৰ্তুগীজব্ৰাজিলিয়ান পৰ্তুগীজইউৰোপীয়ান পৰ্তুগীজকুৱেচুৱাকিচিয়েৰাজস্থানীৰা"
        u8"পানুইৰাৰোতোঙ্গনৰোহিঙ্গিয়াৰোমানচৰুন্দিৰোমানীয়মোল্ডাভিয়ানৰোম্বোৰাছিয়ানআৰোমানীয়কিনয়াৰোৱাণ্ডাৰৱাসং"
        u8"স্কৃতছান্দাৱেছাখাছাম্বুৰুচাওতালিনাংম্বেছাঙ্গুছাৰ্ডিনিয়ানছিচিলিয়ানস্কটছসিন্ধীউদীচ্য ছামিছেনাকোইৰাবো"
        u8"ৰো চেন্নিছাঙ্গোতাচেলহিটচানসিংহলাশ্লোভাকশ্লোভেনিয়ানদাক্ষিণাত্যৰ লুছুটচীডছামোনদাক্ষিণাত্য ছামিলুলে ছা"
        u8"মিইনাৰি ছামিস্কোল্ট ছামিচোনাছোনিনকেছোমালিআলবেনীয়ছাৰ্বিয়ানস্ৰানান টোঙ্গোস্বাতিছাহোদাক্ষিণাত্য ছোথোষ"
        u8"্ট্ৰেইটছ ছেলিশ্বছুণ্ডানীজছুকুমাছুইডিচস্বাহিলিকঙ্গো স্বাহিলিকোমোৰিয়ানচিৰিয়াকছাইলেছিয়ানতামিলদাক্ষিণ"
        u8"াত্যৰ টুটচ’নতেলুগুটিম্নেতেছোতেতুমতাজিকটেগিশ্বথাইটাহলটানটিগৰিনিয়াতাইগ্ৰেতুৰ্কমেনক্লিংগনলিংগিটছোৱানাট"
        u8"োঙ্গানট’কি প’নাটোক পিছিনতুৰ্কীতাৰোকোছোঙ্গাতাতাৰনৰ্দাৰ্ন টুটচ’নতুম্বুকাটুভালুটাছাৱাকতাহিতিয়ানতুভিনিয"
        u8"়ানচেণ্ট্ৰেল এটলাছ টামাজাইটউদমুৰ্তউইঘুৰইউক্ৰেইনীয়উম্বুন্দুঅজ্ঞাত ভাষাউৰ্দুউজবেকভাইভেণ্ডাভেনেছিয়ানভ"
        u8"িয়েটনামীমাখুৱাভোলাপুকভুঞ্জুৱালুনৱালছেৰওলেইটাৱাৰেৱোলাফৱু চাইনিজকাল্মিকহোছাকাংগৰিছোগায়াংবেনয়েম্বাইদ"
        u8"্দিছইউৰুবাহিংগাটোকেণ্টোনীজঝুৱাংষ্টেণ্ডাৰ্ড মোৰোক্কান তামাজাইটচীনাসৰলীকৃত চীনাপৰম্পৰাগত চীনাঝুলুঝুনিক"
        u8"োনো ভাষা সমল নাইঝাঝাবিশ্বআফ্ৰিকাউত্তৰ আমেৰিকাদক্ষিণ আমেৰিকাঅ’চেনীয়াপাশ্চাত্য আফ্ৰিকামধ্য আমেৰিকাপ্ৰ"
        u8"াচ্য আফ্ৰিকাউদীচ্য আফ্ৰিকামধ্য আফ্ৰিকাদাক্ষিণাত্য আফ্ৰিকাআমেৰিকাছ্উদীচ্য আমেৰিকাকেৰিবিয়ানপ্ৰাচ্য এছ"
        u8"িয়াদাক্ষিণাত্য এছিয়াদক্ষিণ-পূব এছিয়াদাক্ষিণাত্য ইউৰোপঅষ্ট্ৰেলেছিয়ামেলানেছিয়ামাইক্ৰোনেচিয় ক্ষেত"
        u8"্ৰপলিনেচিয়াএছিয়ামধ্য এছিয়াপাশ্চাত্য এছিয়াইউৰোপপ্ৰাচ্য ইউৰোপউদীচ্য ইউৰোপপাশ্চাত্য ইউৰোপউপ-ছাহাৰান"
        u8" আফ্ৰিকালেটিন আমেৰিকাএচেনচিয়ন দ্বীপআন্দোৰাসংযুক্ত আৰব আমিৰাতআফগানিস্তানএণ্টিগুৱা আৰু বাৰ্বুডাএনগুইল"
        u8"াআলবেনিয়াআৰ্মেনিয়াএংগোলাএণ্টাৰ্কটিকাআৰ্জেণ্টিনাআমেৰিকান চামোৱাঅষ্ট্ৰিয়াঅষ্ট্ৰেলিয়াআৰুবাআলণ্ড দ্ব"
        u8"ীপপুঞ্জআজাৰবেইজানব’ছনিয়া আৰু হাৰ্জেগ’ভিনাবাৰ্বাডোচবাংলাদেশবেলজিয়ামবুৰকিনা ফাচোবুলগেৰিয়াবাহৰেইনবুৰ"
        u8"ুণ্ডিবেনিনছেইণ্ট বাৰ্থলেমেবাৰ্মুডাব্ৰুনেইবলিভিয়াকেৰিবিয়ান নেদাৰলেণ্ডছব্ৰাজিলবাহামাছভুটানবুভে দ্বীপ"
        u8"ব’টচোৱানাবেলাৰুছবেলিজকানাডাকোকোচ (কীলিং) দ্বীপপুঞ্জকঙ্গো - কিনচাছামধ্য আফ্রিকান প্রজাতন্ত্রকঙ্গো - ব"
        u8"্রাজাভিলচুইজাৰলেণ্ডকোটে ডি আইভৰকুক দ্বীপপুঞ্জচিলিকেমেৰুণচীনকলম্বিয়াক্লিপাৰটোন দ্বীপকোষ্টা ৰিকাকিউবা"
        u8"কেপ ভার্দেকুৰাকাওখ্ৰীষ্টমাছ দ্বীপচাইপ্ৰাছচিজেচিয়াজাৰ্মানীডিয়েগো গাৰ্চিয়াজিবুটিডেনমাৰ্কড’মিনিকাড’ম"
        u8"িনিকান ৰিপাব্লিকআলজেৰিয়াচেউটা আৰু মেলিলাইকুৱেডৰইষ্টোনিয়াইজিপ্তপশ্চিমীয় ছাহাৰাএৰিত্ৰিয়াস্পেইনইথিঅ"
        u8"’পিয়াইউৰোপীয় সংঘইউৰোজ’নফিনলেণ্ডফিজিফকলেণ্ড দ্বীপপুঞ্জমাইক্ৰোনেচিয়াফাৰো দ্বীপপুঞ্জফ্ৰান্সগেবনসংযুক"
        u8"্ত ৰাজ্যগ্ৰেনাডাজৰ্জিয়াফ্ৰান্স গয়ানাগোৰেনচিঘানাজিব্ৰাল্টৰগ্ৰীণলেণ্ডগাম্বিয়াগিনিগুৱাডেলুপইকুৱেটৰিয"
        u8"়েল গিনিগ্ৰীচদক্ষিণ জৰ্জিয়া আৰু দক্ষিণ চেণ্ডৱিচ দ্বীপপুঞ্জগুৱাটেমালাগুৱামগিনি-বিছাওগায়ানাহং কং এছ."
        u8" এ. আৰ. চীনহাৰ্ড দ্বীপ আৰু মেকডোনাল্ড দ্বীপপুঞ্জহন্দুৰাছক্ৰোৱেছিয়াহাইটিহাংগেৰীকেনেৰী দ্বীপপুঞ্জইণ্ড"
        u8"োনেচিয়াআয়াৰলেণ্ডইজৰাইলআইল অফ মেনভাৰতব্ৰিটিছ ইণ্ডিয়ান অ’চন টেৰিট’ৰিইৰাকইৰানআইচলেণ্ডইটালিজাৰ্চিজামা"
        u8"ইকাজৰ্ডানজাপানকেনিয়াকিৰ্গিজস্তানকম্বোডিয়াকিৰিবাটিকোমোৰোজছেইণ্ট কিটছ আৰু নেভিছউত্তৰ কোৰিয়াদক্ষিণ ক"
        u8"োৰিয়াকুৱেইটকেইমেন দ্বীপপুঞ্জকাজাখাস্তানলাওচলেবাননছেইণ্ট লুচিয়ালিচটেনষ্টেইনশ্রীলংকালিবেৰিয়ালেছ’থ’ল"
        u8"িথুৱানিয়ালাক্সেমবাৰ্গলাটভিয়ালিবিয়ামৰক্কোমোনাকোমোলডোভামণ্টেনেগ্ৰুছেইণ্ট মাৰ্টিনমাদাগাস্কাৰমাৰ্শ্বা"
        u8"ল দ্বীপপুঞ্জউত্তৰ মেচিডোনীয়ামালিম্যানমাৰ (বাৰ্মা)মঙ্গোলিয়ামাকাও এছ. এ. আৰ. চীনউত্তৰ মাৰিয়ানা দ্বী"
        u8"পপুঞ্জমাৰ্টিনিকমাউৰিটানিয়াম’ণ্টছেৰাটমাল্টামৰিছাছমালদ্বীপমালাৱিমেক্সিকোমালয়েচিয়াম’জামবিকনামিবিয়ান"
        u8"িউ কেলিডোনিয়ানাইজাৰন’ৰফ’ক দ্বীপনাইজেৰিয়ানিকাৰাগুৱানেডাৰলেণ্ডনৰৱেনেপালনিউনিউজিলেণ্ডওমানপানামাপেৰুফ্"
        u8"ৰান্স পোলেনচিয়াপাপুৱা নিউ গিনিফিলিপাইনছপাকিস্তানপোলেণ্ডছেইণ্ট পিয়েৰে আৰু মিকিউৱেলনপিটকেইৰ্ণ দ্বীপপ"
        u8"ুঞ্জপুৱেৰ্টো ৰিকোফিলিস্তিন অঞ্চলপৰ্তুগালপালাউপাৰাগুৱেকাটাৰআউটলায়িং অ’চিয়ানিয়াৰিইউনিয়নৰোমানিয়াছা"
        u8"ৰ্বিয়াৰাছিয়াৰোৱাণ্ডাচৌডি আৰবিয়াচোলোমোন দ্বীপপুঞ্জছিচিলিছচুডানচুইডেনছিংগাপুৰছেইণ্ট হেলেনাশ্লোভেনিয"
        u8"়াচাভালবাৰ্ড আৰু জন মেয়নশ্লোভাকিয়াচিয়েৰা লিঅ’নচান মাৰিনোচেনেগালচোমালিয়াছুৰিনামদক্ষিণ চুডানচাও টো"
        u8"মে আৰু প্ৰিনচিপেএল ছেলভেড’ৰচিণ্ট মাৰ্টেনচিৰিয়াইচ্চুটিনিত্ৰিস্তান দ্যা কুনহাটাৰ্কছ অৰু কেইক’ছ দ্বীপপ"
        u8"ুঞ্জচাডদক্ষিণ ফ্ৰান্সৰ অঞ্চলটোগোথাইলেণ্ডতাজিকিস্তানটোকেলাউটিমোৰ-লেচটেতুৰ্কমেনিস্তানটুনিচিয়াটংগাতুৰ্"
        u8"কিয়েট্ৰিনিডাড আৰু টোবাগোটাইৱানতাঞ্জানিয়াইউক্ৰেইনউগাণ্ডাইউ. এছ. আউটলায়িং দ্বীপপুঞ্জৰাষ্ট্ৰসংঘমাৰ্ক"
        u8"িন যুক্তৰাষ্ট্ৰউৰুগুৱেউজবেকিস্তানভেটিকান চিটিছেইণ্ট ভিনচেণ্ট আৰু গ্ৰীণাডাইনছভেনিজুৱেলাব্ৰিটিছ ভাৰ্জি"
        u8"ন দ্বীপপুঞ্জইউ. এছ. ভাৰ্জিন দ্বীপপুঞ্জভিয়েটনামভানাটুৱালিছ আৰু ফুটুনাচামোৱাছুডু-একচেণ্টছুডু-বিডিকচ’ভ"
        u8"’য়েমেনমায়োট্টেদক্ষিণ আফ্রিকাজাম্বিয়াজিম্বাবৱেঅজ্ঞাত ক্ষেত্ৰএডলামনাষ্টালিকবোপোমোফোব্ৰেইলচাকমাইউনিফ"
        u8"াইড কানাডিয়ান এব’ৰিজিনেল ছিলেবিকছচেৰ’কীচিৰিলিকদেৱনাগৰীইথিঅ’পিকগুৰুমুখীবোপোমোফোৰ সৈতে হানহেঙ্গুলহানস"
        u8"ৰলীকৃতপৰম্পৰাগতহিৰাগানাজাপানী ছিলেবেৰিজজামোকাটাকানামঙ্গোলিয়মেইতেই মায়েকম্যানমাৰএন্\u200Dক’অ’ল চিকি"
        u8"হানিফিসিংহলীছাণ্ডানিজছিৰিয়াকটিফিনাঘথানায়িগাণিতিক চিহ্নইম’জিপ্ৰতীকঅলিখিতকোমোনঅজ্ঞাত লিপিসৰলীকৃত হান"
        u8"পৰম্পৰাগত হানসংযুক্ত আৰব আমিৰাত ডিৰহেমUAE ডিৰহেমআফগান আফগানীআলবেনীয় লেকআৰ্মেনিয়ান ড্ৰামএংগোলান কোৱ"
        u8"াঞ্জাআৰ্জেণ্টাইন পেছোঅষ্ট্ৰেলিয়ান ডলাৰআৰুবান ফ্ল’ৰিনআজেৰবাইজানী মানাতব’ছনিয়া আৰু হাৰ্জেগ’ভিনা কনভা"
        u8"ৰ্টিব্\u200Cল মাৰ্কবাৰ্বাডিয়ান ডলাৰবাংলাদেশী টাকাবুলগেৰীয় লেভবাহৰেইনী ডিনাৰবুৰুণ্ডিয়ান ফ্ৰেংকবাৰ্"
        u8"মুডান ডলাৰব্ৰুনেই ডলাৰবলিভিয়ান বলিভিয়ানোব্ৰাজিলিয়ান ৰিয়েলবাহামিয়ান ডলাৰভুটানী নংগলট্ৰামব’টচোৱান"
        u8"ান পুলাবেলাৰুছীয় ৰুবেলবেলিজ ডলাৰকানাডিয়ান ডলাৰকংগো ফ্ৰেংকচুইছ ফ্ৰেংকচিলিয়ান পেছোচীনা ইউৱানকলম্বিয"
        u8"়ান পেছোকোষ্টা ৰিকান কোলনকিউবান পেছোকেপ ভাৰ্দে এছকুডোচেক কোৰুনাজিবুটি ফ্ৰেংকডেনিচ ক্ৰোনড’মিনিকান পেছ"
        u8"োআলজেৰীয় ডিনাৰইজিপ্তৰ পাউণ্ডএৰিট্ৰিয়ন নাক্\u200Cফাইথিঅ’পিয়ান বিৰইউৰোফিজিয়ান ডলাৰফকলেণ্ড দ্বীপপুঞ"
        u8"্জৰ পাউণ্ডব্ৰিটিছ পাউণ্ডজৰ্জিয়ান লাৰিঘানাৰ চেডিজিব্ৰাল্টৰ পাউণ্ডগাম্বিয়া ডালাছিগিনি ফ্ৰেংকগুৱাটেমা"
        u8"লা কুৱেৎজালগায়ানিজ ডলাৰহং কং ডলাৰহোন্দুৰান লেম্পিৰাহাইটিয়ান গৌৰ্ডহাংগেৰীয়ান ফ’ৰিণ্টইণ্ডোনেচিয়ান "
        u8"ৰুপিয়াহইজৰাইলী নিউ শ্বেকেলভাৰতীয় ৰুপীইৰাকী ডিনাৰইৰানীয়ান ৰিয়েলআইচলেণ্ডিক ক্ৰোনাআইচলেণ্ডিক ক্ৰোনা"
        u8"ৰজামাইকান ডলাৰজৰ্ডানিয়ান ডিনাৰজাপানী য়েনকেনিয়ান শ্বিলিংকিৰ্গিস্তানী ছোমকেম্ব’ডিয়ান ৰিয়েলক’মোৰিয"
        u8"়ান ফ্ৰেংকউত্তৰ কোৰিয়াৰ ওৱানদক্ষিণ কোৰিয়াৰ ওৱানকুৱেইটি ডিনাৰকেইমেন দ্বীপপুঞ্জৰ ডলাৰকাজাখস্তানী তেঞ"
        u8"্জলাওচিয়ান কিপলেবানীজ পাউণ্ডশ্ৰীলংকান ৰুপীলাইবেৰিয়ান ডলাৰলেচোথো লোটিলেচোথো লোটিচলিবিয়ান ডিনাৰমৰোক"
        u8"্কান ডিৰহামমোলডোভান লেউমোলডোভান লেইমালাগাছী এৰিয়াৰীমেচিডোনীয় ডেনাৰম্যানমাৰ কিয়াটমঙ্গোলিয়ান টুৰ্গ"
        u8"িকমেকানীজ পাটাকাম’ৰিটেনিয়ান ঔগুইয়ামৰিচিয়ান ৰুপীমালডিভিয়ান ৰুফিয়ামালাউইয়ান কোৱাচামেক্সিকান পেছো"
        u8"মালায়েচিয়ান ৰিংগিটমোজাম্বিকান মেটিকলনামিবিয়ান ডলাৰনাইজেৰিয়ান নাইৰানিকাৰাগুৱান কোৰ্ডোবানৰৱেজিয়ান"
        u8" ক্ৰোননৰৱেজিয়ান ক্ৰোনাৰনেপালী ৰুপীনিউজিলেণ্ড ডলাৰওমানি ৰিয়েলপানামেনিয়ান বাল্বোৱাপেৰুভিয়ান ছ’লপাপ"
        u8"ুৱা নিউ গিনি কিনাফিলিপিন পেইছ’পাকিস্তানী ৰুপীপ’লিচ জোল্টীপাৰাগুয়ান গুৱাৰানিকাটাৰি ৰিয়েলৰোমানীয় লে"
        u8"উচাৰ্বিয়ান ডিনাৰৰাছিয়ান ৰুব্\u200Cলৰোৱান্দান ফ্ৰেংকচৌডি ৰিয়েলচোলোমোন দ্বীপপুঞ্জৰ ডলাৰছেচেলৱা ৰুপী"
        u8"চুডানী পাউণ্ডচুইডিছ ক্ৰোনাচুইডিছ ক্ৰোনোৰছিংগাপুৰ ডলাৰছেইণ্ট হেলেনা পাউণ্ডচিয়েৰা লিঅ’নৰ লিঅ’নচোমালি "
        u8"শ্বিলিংছুৰিনামী ডলাৰদক্ষিণ চুডানীজ পাউণ্ডচাও টোমে আৰু প্ৰিনচিপে ডোব্\u200Cৰাচিৰিয়ান পাউণ্ডস্বাজি লি"
        u8"লেংগেনিস্বাজি এমেলানজেনিথাই বাততাজিকিস্তানী ছোমনিতুৰ্কমেনিস্তানী মানাতটুনিচিয়ান ডিনাৰটংগান পাআংগাতু"
        u8"ৰ্কীৰ লিৰাট্ৰিনিডাড আৰু টোবাগো ডলাৰনিউ টাইৱান ডলাৰটানজানিয়ান শ্বিলিংইউক্ৰেইনীয় হৃভনিয়াউগাণ্ডান শ্"
        u8"বিলিংইউ. এছ. ডলাৰউৰুগুৱেয়ান পেছোউজবেকিস্তানী ছোমভেনিজুৱেলান বলিভাৰভেনিজুৱেলান ব’লিভাৰভেনিজুৱেলান ব’"
        u8"লিভাৰছ্ভিয়েটনামীজ ডংভানাটুৰ ভাটুছামোৱান টালামধ্য আফ্ৰিকান CFA ফ্ৰেংকইষ্ট কেৰিবিয়ান ডলাৰপশ্চিম আফ্ৰ"
        u8"িকান CFA ফ্ৰেংকCFP ফ্ৰেংকঅজ্ঞাত মুদ্ৰা(মুদ্ৰাৰ অজ্ঞাত একক)(অজ্ঞাত মুদ্ৰা)য়েমেনী ৰিয়েলদক্ষিণ আফ্ৰিক"
        u8"াৰ ৰাণ্ডজাম্বিয়ান কোৱাচাসমন্বিত সাৰ্বজনীন সময়UTCঅজ্ঞাত চহৰডুবাইকাবুলএণ্টিগুৱাটাইৰেনয়েৰেভানলুৱাণ্ড"
        u8"াৰোথেৰাপামৰট্ৰোলস্বোৱামাউছনডেভিছভোষ্টককেছীডুমোণ্ট ডি আৰ্ভিলৰমেকমুৰ্ডুৰিঅ’ গালেগোছমেণ্ডোজাছেন জুৱানউচ"
        u8"ুআইয়ালা ৰিওজাছেন লুইচকাটামাৰ্কাছাল্টাজুজুইটুকুমনকোৰ্ডোবাবুনছ আয়াৰ্ছপাগো পাগোভিয়েনাপাৰ্থইউক্লাডাৰউ"
        u8"ইনএডিলেইডব্ৰোকেন হিলমেলব’ৰ্ণহোবাৰ্টলিণ্ডমানচিডনীব্ৰিচবেনমেক্\u200Cকুৱেৰীলৰ্ড হাওমাৰিয়াহেমবাকুছাৰাজে"
        u8"ভোঢাকাব্ৰুছলেছঔগাডোগোছোফিয়াবুজুম্বুৰাপোৰ্টো-নোভোলা পাজক্ৰালেণ্ডিজিকইৰুনেপেৰিঅ’ ব্ৰাংকোপোৰ্টো ভেল্"
        u8"\u200Cহোবোৱা ভিষ্টামানাছকুইআবাছেণ্টাৰেমকেম্পো গ্ৰেণ্ডেবেলেমআৰাগায়েনাছাও পাউলোবাহিয়াফোৰ্টালেজামেচিও"
        u8"ৰেচাইফনোৰোন্\u200Cহানাছাউথিম্ফুগাবোৰোণমিংস্কডাওছনহোৱাইটহৰ্চইনুভিকভেনকুভেৰফ’ৰ্ট নেলছনডাওছন ক্ৰীকক্ৰেষ"
        u8"্টনএডমণ্টনছুইফ্ট কাৰেণ্টকেমব্ৰিজ উপসাগৰৰেজিনাৱিনিপেগৰিজ’লিউটৰেংকিন ইনলেটআটিকোকানট’ৰ’ণ্টোইকালুইটমন্"
        u8"\u200Cকটনহেলিফেক্সগুছ উপসাগৰগ্লেচ উপসাগৰব্লাংক-ছেবলোনছেইণ্ট জনচ্কোকোছকিংচাছালুবুম্বাচিবাংগুইব্ৰাজাভি"
        u8"লেজুৰিখআবিডজানৰাৰোটোঙ্গাইষ্টাৰপুণ্টা এৰিনাছছেণ্টিয়াগোউৰুম্\u200Cকিছাংহাইবোগোটাহাভানাকেপ ভাৰ্দেখ্ৰীষ"
        u8"্টমাছনিকোছিয়াফামাগুস্তাপ্ৰাগবুছিনজেনবাৰ্লিনকোপেনহাগেনডমিনিকাছাণ্টো ডোমিংগোআলজিয়াৰ্ছগালাপাগোছগায়াক"
        u8"ুইলতেলিনকাইৰোএল আইয়ুনআস্মাৰাকেনেৰীচেউটামাদ্ৰিদআদ্দিছ আবাবাহেলছিংকিষ্টেন্\u200Cলীচ্চুকপোনপেইকোছৰায়ে"
        u8"ফাৰোপেৰিছলিব্ৰিভিলেলণ্ডনব্ৰিটিছ গ্ৰীষ্মকালীন সময়টিবলিচিকেয়েনএক্ৰাথ্যুলেনুকইটোকোৰ্টোৰমিটডেনমাৰ্কশ্ব"
        u8"নবেঞ্জুলকোনাক্ৰীমালাবোএথেন্সদক্ষিণ জৰ্জিয়াবিছাউহং কংটেগুচিগাল্পাজাগ্ৰেবপ’ৰ্ট-ঔ-প্ৰিন্সবুডাপেষ্টজাকা"
        u8"ৰ্টাপোণ্টিয়াংকজায়াপুৰাডাবলিনআইৰিচ মান সময়জেৰুজালেমকলকাতাচাগোছবাগদাদতেহৰানৰেইকজাভিকৰোমআম্মানটকিঅ’ন"
        u8"াইৰোবিবিশ্ব্\u200Cকেকনোম পেন্\u200Cহএণ্ডৰবাৰীকিৰিটিমাটিতাৰাৱাকোমোৰোছেইণ্ট কিটছপ্যংয়াংছিউলকেইমেনএক্য"
        u8"োট্যাওঅ’ৰেলএটৰাউএক্যোটবক’ষ্টেনীকেজিলোৰ্ডাআলমাটিভিয়েণ্টিয়ানবেইৰুটভাদুজকলম্বোমোনৰোভিয়ামাছেৰুভিলনিয়"
        u8"াছৰিগাত্ৰিপোলিকাছাব্লাংকাচিছিনাউপোডগোৰিকামেৰিগোটএণ্টানানাৰিভোকোৱাজালিনমাজুৰোস্কোপ্জেবামাকোয়াঙোনহোভ্"
        u8"\u200Cডউলানবাটাৰমাকাওছাইপাননৌআকচোটমণ্টছেৰাটব্লাণ্টায়াৰতিজুৱানাহাৰ্মোছিল্লোচিউডে‘ড জৰেজমাজাট্\u200Cল"
        u8"ানচিহুআহুৱাবাহিয়া বান্দেৰাছঅ’জিনাগামণ্টেৰেৰীমেক্সিকো চিটীমাটামোৰোছমেৰিডাকেনকুনকুৱালালুমপুৰকুচিংমাপু"
        u8"টোৱিণ্ডহোকনউমিয়ানিয়ামীন’ৰফ’কলাগোছমানাগুৱাআমষ্টাৰডামওস্লোকাঠমাণ্ডুনাৰুনিয়োচাথামঅকলেণ্ডমুস্কেটলিমাত"
        u8"াহিতিমাৰ্কছাছগেম্বিয়াৰপ’ৰ্ট মোৰেছ্\u200Cবিবোগেইনভিলেমানিলাকৰাচীৱাৰছাওমিকিউৱেলনপিটকেইৰ্ণগাজাহেব্ৰোনএ"
        u8"জোৰেছমাডেৰালিছবনআছুনচিয়নবুচাৰেষ্টবেলগ্ৰেডকালিনিনগ্ৰাডমস্কোভোল্গোগ্ৰাডছাৰাটোভআষ্ট্ৰাখানউল্যানোভ্"
        u8"\u200Cস্ককিৰোভছামাৰায়েকাটেৰিণবাৰ্গওমস্কনোভোছিবিৰ্স্কবাৰ্নুলতোম্\u200Cস্কনোভোকুজনেত্স্কক্ৰাছনোয়াৰ্স"
        u8"্কইৰ্কুত্স্কচিটায়াকুত্স্কভ্লাডিভোষ্টকখাণ্ডিগাছাখালিনউষ্ট-নেৰামাগাদানস্ৰেডনিকোলিমস্ককামচত্কাআনাডিৰকি"
        u8"গালীৰিয়াধগুৱাডলকানালমাহেখাৰ্টুমষ্টকহোমল্যুবেলজানালংগেইৰবায়েনব্ৰাটিছলাভাফ্ৰিটাউনডাকাৰমোগাদিচুপাৰামা"
        u8"ৰিবোজুবাচাও টোমেল’ৱাৰ প্ৰিন্সেছ কোৱাৰ্টাৰডামাস্কাছএম্বাবেনগ্ৰেণ্ড টাৰ্কনেদজামেনাকেৰগুলেনলোমবেংককডুছা"
        u8"নবেফাকাওফোডিলিআশ্ব্গা\u200Cবাটটুনিছটংগাটাপুইস্তানবুলপ’ৰ্ট অৱ স্পেইনফুনাফুটিটাইপেইডাৰ এছ ছালামকিভছিম্"
        u8"ফেৰোপোলকাম্পালামিডৱেৱেকআডাকনোমএংকোৰেজয়াকুটাটছিট্\u200C\u200Cকাজুনেউমেটলাকাট্\u200Cলালছ এঞ্জেলছ্ব’ইজ"
        u8"েফিনিক্সডেনভাৰবেউলাহ, উত্তৰ ডাকোটানিউ ছালেম, উত্তৰ ডাকোটাচেণ্টাৰ, উত্তৰ ডাকোটাচিকাগোমেনোমিনীভিনচেনেছ"
        u8", ইণ্ডিয়ানাপিটাৰ্ছবাৰ্গ, ইণ্ডিয়ানাটেল চিটী, ইণ্ডিয়ানানক্স, ইণ্ডিয়ানাউইনামেক, ইণ্ডিয়ানামাৰেংগো, "
        u8"ইণ্ডিয়ানাইণ্ডিয়ানাপ’লিছলুইছভিলেভেভে, ইণ্ডিয়ানামণ্টিচেলো, কেণ্টুকীডেট্ৰোইটনিউ ইয়ৰ্কমণ্টেভিডিঅ’ছাম"
        u8"াৰকাণ্ডতাছকেণ্টভেটিকানছেইণ্ট ভিনচেণ্টকাৰাকাছটোৰ্টোলাছেইণ্ট থমাছহো চি মিন চিটীএফেটৱালিছআপিয়াআদেনজোহা"
        u8"ন্সবাৰ্গলুছাকাহাৰাৰেআফগানিস্তানৰ সময়মধ্য আফ্ৰিকাৰ সময়পূব আফ্ৰিকাৰ সময়দক্ষিণ আফ্ৰিকাৰ মান সময়পশ্চ"
        u8"িম আফ্ৰিকাৰ সময়পশ্চিম আফ্ৰিকাৰ মান সময়পশ্চিম আফ্ৰিকাৰ গ্ৰীষ্মকালীন সময়আলাস্কাৰ সময়আলাস্কাৰ মান স"
        u8"ময়আলাস্কাৰ ডেলাইট সময়আমাজনৰ সময়আমাজনৰ মান সময়আমাজনৰ গ্ৰীষ্মকালীন সময়উত্তৰ আমেৰিকাৰ কেন্দ্ৰীয় স"
        u8"ময়উত্তৰ আমেৰিকাৰ কেন্দ্ৰীয় মান সময়উত্তৰ আমেৰিকাৰ কেন্দ্ৰীয় ডেলাইট সময়উত্তৰ আমেৰিকাৰ প্ৰাচ্য সময"
        u8"়উত্তৰ আমেৰিকাৰ প্ৰাচ্য মান সময়উত্তৰ আমেৰিকাৰ প্ৰাচ্য ডেলাইট সময়উত্তৰ আমেৰিকাৰ পৰ্ব্বতীয় সময়উত্ত"
        u8"ৰ আমেৰিকাৰ পৰ্ব্বতীয় মান সময়উত্তৰ আমেৰিকাৰ পৰ্ব্বতীয় ডেলাইট সময়উত্তৰ আমেৰিকাৰ প্ৰশান্ত সময়উত্তৰ"
        u8" আমেৰিকাৰ প্ৰশান্ত মান সময়উত্তৰ আমেৰিকাৰ ডেলাইট সময়আপিয়াৰ সময়আপিয়াৰ মান সময়আপিয়াৰ ডেলাইট সময়"
        u8"আৰবীয় সময়আৰবীয় মান সময়আৰবীয় ডেলাইট সময়আৰ্জেণ্টিনাৰ সময়আৰ্জেণ্টিনাৰ মান সময়আৰ্জেণ্টিনাৰ গ্ৰীষ"
        u8"্মকালীন সময়পাশ্চাত্য আৰ্জেণ্টিনাৰ সময়পাশ্চাত্য আৰ্জেণ্টিনাৰ মান সময়পাশ্চাত্য আৰ্জেণ্টিনাৰ গ্ৰীষ্ম"
        u8"কালীন সময়আৰ্মেনিয়াৰ সময়আৰ্মেনিয়াৰ মান সময়আৰ্মেনিয়াৰ গ্ৰীষ্মকালীন সময়আটলাণ্টিক সময়আটলাণ্টিক ম"
        u8"ান সময়আটলাণ্টিক ডেলাইট সময়মধ্য অষ্ট্ৰেলিয়াৰ সময়অষ্ট্ৰেলিয়াৰ কেন্দ্ৰীয় মান সময়অষ্ট্ৰেলিয়াৰ কে"
        u8"ন্দ্ৰীয় ডেলাইট সময়অষ্ট্ৰেলিয়াৰ কেন্দ্ৰীয় পাশ্চাত্য সময়অষ্ট্ৰেলিয়াৰ কেন্দ্ৰীয় পাশ্চাত্য মান সম"
        u8"য়অষ্ট্ৰেলিয়াৰ কেন্দ্ৰীয় পাশ্চাত্য ডেলাইট সময়প্ৰাচ্য অষ্ট্ৰেলিয়াৰ সময়অষ্ট্ৰেলিয়াৰ প্ৰাচ্য মান "
        u8"সময়অষ্ট্ৰেলিয়াৰ প্ৰাচ্য ডেলাইট সময়পাশ্চাত্য অষ্ট্ৰেলিয়াৰ সময়অষ্ট্ৰেলিয়াৰ পাশ্চাত্য মান সময়অষ্"
        u8"ট্ৰেলিয়াৰ পাশ্চাত্য ডেলাইট সময়আজেৰবাইজানৰ সময়আজেৰবাইজানৰ মান সময়আজেৰবাইজানৰ গ্ৰীষ্মকালীন সময়আজো"
        u8"ৰেছ সময়আজোৰেছৰ মান সময়আজোৰেছৰ গ্ৰীষ্মকালীন সময়বাংলাদেশৰ সময়বাংলাদেশৰ মান সময়বাংলাদেশৰ গ্ৰীষ্মকা"
        u8"লীন সময়ভুটানৰ সময়বলিভিয়াৰ সময়ব্ৰাজিলিয়াৰ সময়ব্ৰাজিলিয়াৰ মান সময়ব্ৰাজিলিয়াৰ গ্ৰীষ্মকালীন সময"
        u8"়ব্ৰুনেই ডাৰুছালেমৰ সময়কেপ ভাৰ্দেৰ সময়কেপ ভাৰ্দেৰ মান সময়কেপ ভাৰ্দেৰ গ্ৰীষ্মকালীন সময়চামোৰোৰ মান"
        u8" সময়চাথামৰ সময়চাথামৰ মান সময়চাথামৰ ডেলাইট সময়চিলিৰ সময়চিলিৰ মান সময়চিলিৰ গ্ৰীষ্মকালীন সময়চীনৰ"
        u8" সময়চীনৰ মান সময়চীনৰ ডেলাইট সময়খ্ৰীষ্টমাছ দ্বীপৰ সময়কোকোছ দ্বীপপুঞ্জৰ সময়কলম্বিয়াৰ সময়কলম্বিয"
        u8"়াৰ মান সময়কলম্বিয়াৰ গ্ৰীষ্মকালীন সময়কুক দ্বীপপুঞ্জৰ সময়কুক দ্বীপপুঞ্জৰ মান সময়কুক দ্বীপপুঞ্জৰ "
        u8"অৰ্ধ গ্ৰীষ্মকালীন সময়কিউবাৰ সময়কিউবাৰ মান সময়কিউবাৰ ডেলাইট সময়ডেভিছৰ সময়ডুমোণ্ট-ডি আৰ্ভিলৰ সময়"
        u8"পূব তিমোৰৰ সময়ইষ্টাৰ দ্বীপৰ সময়ইষ্টাৰ দ্বীপৰ মান সময়ইষ্টাৰ দ্বীপৰ গ্ৰীষ্মকালীন সময়ইকুৱেডৰৰ সময়ম"
        u8"ধ্য ইউৰোপীয় সময়মধ্য ইউৰোপীয় মান সময়মধ্য ইউৰোপীয় গ্ৰীষ্মকালীন সময়প্ৰাচ্য ইউৰোপীয় সময়প্ৰাচ্য ই"
        u8"উৰোপীয় মান সময়প্ৰাচ্য ইউৰোপীয় গ্ৰীষ্মকালীন সময়অগ্ৰ-প্ৰাচ্য ইউৰোপীয় সময়পাশ্চাত্য ইউৰোপীয় সময়প"
        u8"াশ্চাত্য ইউৰোপীয় মান সময়পাশ্চাত্য ইউৰোপীয় গ্ৰীষ্মকালীন সময়ফকলেণ্ড দ্বীপপুঞ্জৰ সময়ফকলেণ্ড দ্বীপপ"
        u8"ুঞ্জৰ মান সময়ফকলেণ্ড দ্বীপপুঞ্জৰ গ্ৰীষ্মকালীন সময়ফিজিৰ সময়ফিজিৰ মান সময়ফিজিৰ গ্ৰীষ্মকালীন সময়ফ্"
        u8"ৰান্স গয়ানাৰ সময়দক্ষিণ ফ্ৰান্স আৰু এণ্টাৰ্কটিক সময়গালাপাগোছৰ সময়গেম্বিয়াৰ সময়জৰ্জিয়াৰ সময়জৰ্"
        u8"জিয়াৰ মান সময়জৰ্জিয়াৰ গ্ৰীষ্মকালীন সময়গিলবাৰ্ট দ্বীপপুঞ্জৰ সময়গ্ৰীণউইচ মান সময়পূব গ্ৰীণলেণ্ডৰ "
        u8"সময়পূব গ্ৰীণলেণ্ডৰ মান সময়পূব গ্ৰীণলেণ্ডৰ গ্ৰীষ্মকালীন সময়পশ্চিম গ্ৰীণলেণ্ডৰ সময়পশ্চিম গ্ৰীণলেণ্"
        u8"ডৰ মান সময়পশ্চিম গ্ৰীণলেণ্ডৰ গ্ৰীষ্মকালীন সময়উপসাগৰীয় মান সময়গায়ানাৰ সময়হাৱাই-এলিউশ্বনৰ সময়হা"
        u8"ৱাই-এলিউশ্বনৰ মান সময়হাৱাই-এলিউশ্বনৰ ডেলাইট সময়হং কঙৰ সময়হং কঙৰ মান সময়হং কঙৰ গ্ৰীষ্মকালীন সময়হ"
        u8"োভ্\u200Cডৰ সময়হোভ্\u200Cডৰ মান সময়হোভ্\u200Cডৰ গ্ৰীষ্মকালীন সময়ভাৰতীয় মান সময়ভা. স.ভাৰত মহাসাগ"
        u8"ৰীয় সময়ইণ্ডোচাইনাৰ সময়মধ্য ইণ্ডোনেচিয়াৰ সময়প্ৰাচ্য ইণ্ডোনেচিয়াৰ সময়পাশ্চাত্য ইণ্ডোনেচিয়াৰ সম"
        u8"য়ইৰানৰ সময়ইৰানৰ মান সময়ইৰানৰ ডেলাইট সময়ইৰ্কুটস্কৰ সময়ইৰ্কুটস্কৰ মান সময়ইৰ্কুটস্কৰ গ্ৰীষ্মকালীন"
        u8" সময়ইজৰাইলৰ সময়ইজৰাইলৰ মান সময়ইজৰাইলৰ ডেলাইট সময়জাপানৰ সময়জাপানৰ মান সময়জাপানৰ ডেলাইট সময়কাজা"
        u8"খস্তানৰ সময়পূব কাজাখস্তানৰ সময়পশ্চিম কাজাখস্তানৰ সময়কোৰিয়াৰ সময়কোৰিয়াৰ মান সময়কোৰিয়াৰ ডেলাইট"
        u8" সময়কোছৰায়ে সময়ক্ৰাছনোয়াৰ্স্কৰ সময়ক্ৰাছনোয়াৰ্স্কৰ মান সময়ক্ৰাছনোয়াৰ্স্ক গ্ৰীষ্মকালীন সময়কিৰ"
        u8"্গিজস্তানৰ সময়লাইন দ্বীপপুঞ্জৰ সময়লৰ্ড হাওৰ সময়লৰ্ড হাওৰ মান সময়লৰ্ড হাওৰ ডেলাইট সময়মাগাদানৰ সম"
        u8"য়মাগাদানৰ মান সময়মাগাদানৰ গ্ৰীষ্মকালীন সময়মালয়েচিয়াৰ সময়মালদ্বীপৰ সময়মাৰ্কছেছৰ সময়মাৰ্শ্বাল "
        u8"দ্বীপপুঞ্জৰ সময়মৰিছাছৰ সময়মৰিছাছৰ মান সময়মৰিছাছৰ গ্ৰীষ্মকালীন সময়মাউছনৰ সময়মেক্সিকোৰ প্ৰশান্ত স"
        u8"ময়মেক্সিকোৰ প্ৰশান্ত মান সময়মেক্সিকোৰ প্ৰশান্ত ডেলাইট সময়উলানবাটাৰৰ সময়উলানবাটাৰৰ মান সময়উলানবা"
        u8"টাৰৰ গ্ৰীষ্মকালীন সময়মস্কোৰ সময়মস্কোৰ মান সময়মস্কোৰ গ্ৰীষ্মকালীন সময়ম্যানমাৰৰ সময়নাউৰুৰ সময়নেপ"
        u8"ালৰ সময়নিউ কেলিডোনিয়াৰ সময়নিউ কেলিডোনিয়াৰ মান সময়নিউ কেলিডোনিয়াৰ গ্ৰীষ্মকালীন সময়নিউজিলেণ্ডৰ "
        u8"সময়নিউজিলেণ্ডৰ মান সময়নিউজিলেণ্ডৰ ডেলাইট সময়নিউফাউণ্ডলেণ্ডৰ সময়নিউফাউণ্ডলেণ্ডৰ মান সময়নিউফাউণ্ড"
        u8"লেণ্ডৰ ডেলাইট সময়নিয়ুৰ সময়ন’ৰফ’ক দ্বীপৰ সময়ন’ৰফ’ক দ্বীপৰ মান্য সময়ন’ৰফ’ক দ্বীপৰ গ্ৰীষ্মকালীন সম"
        u8"য়ফাৰ্নাণ্ডো ডে নোৰোন্\u200Cহাৰ সময়ফাৰ্নাণ্ডো ডে নোৰোন্\u200Cহাৰ মান সময়ফাৰ্নাণ্ডো ডে নোৰোন্\u200C"
        u8"হাৰ গ্ৰীষ্মকালীন সময়নভোছিবিৰ্স্কৰ সময়নভোছিবিৰ্স্কৰ মান সময়নভোছিবিৰ্স্কৰ গ্ৰীষ্মকালীন সময়ওমস্কৰ স"
        u8"ময়ওমস্কৰ মান সময়ওমস্কৰ গ্ৰীষ্মকালীন সময়পাকিস্তানৰ সময়পাকিস্তানৰ মান সময়পাকিস্তানৰ গ্ৰীষ্মকালীন "
        u8"সময়পালাউৰ সময়পাপুৱা নিউ গিনিৰ সময়পাৰাগুৱেৰ সময়পাৰাগুৱেৰ মান সময়পাৰাগুৱেৰ গ্ৰীষ্মকালীন সময়পেৰুৰ"
        u8" সময়পেৰুৰ মান সময়পেৰুৰ গ্ৰীষ্মকালীন সময়ফিলিপাইনৰ সময়ফিলিপাইনৰ মান সময়ফিলিপাইনৰ গ্ৰীষ্মকালীন সময"
        u8"়ফিনিক্স দ্বীপপুঞ্জৰ সময়ছেইণ্ট পিয়েৰে আৰু মিকিউৱেলনৰ সময়ছেইণ্ট পিয়েৰে আৰু মিকিউৱেলনৰ মান সময়ছেই"
        u8"ণ্ট পিয়েৰে আৰু মিকিউৱেলনৰ ডেলাইট সময়পিটকেইৰ্ণৰ সময়পোনাপেৰ সময়প্যংয়াংৰ সময়ৰিইউনিয়নৰ সময়ৰোথেৰা"
        u8"ৰ সময়ছাখালিনৰ সময়ছাখালিনৰ মান সময়ছাখালিনৰ গ্ৰীষ্মকালীন সময়ছামোৱাৰ সময়ছামোৱাৰ মান সময়ছামোৱাৰ ডে"
        u8"লাইট সময়ছিচিলিছৰ সময়ছিংগাপুৰৰ মান সময়চোলোমোন দ্বীপপুঞ্জৰ সময়দক্ষিণ জৰ্জিয়াৰ সময়ছুৰিনামৰ সময়স্"
        u8"বোৱা সময়তাহিতিৰ সময়টাইপেইৰ সময়টাইপেইৰ মান সময়টাইপেইৰ ডেলাইট সময়তাজিকিস্তানৰ সময়টোকেলাউৰ সময়টং"
        u8"গাৰ সময়টংগাৰ মান সময়টংগাৰ গ্ৰীষ্মকালীন সময়চ্চুকৰ সময়তুৰ্কমেনিস্তানৰ সময়তুৰ্কমেনিস্তানৰ মান সময়"
        u8"তুৰ্কমেনিস্তানৰ গ্ৰীষ্মকালীন সময়টুভালাউৰ সময়উৰুগুৱেৰ সময়উৰুগুৱেৰ মান সময়উৰুগুৱেৰ গ্ৰীষ্মকালীন সম"
        u8"য়উজবেকিস্তানৰ সময়উজবেকিস্তানৰ মান সময়উজবেকিস্তানৰ গ্ৰীষ্মকালীন সময়ভানাটুৰ সময়ভানাটুৰ মান সময়ভা"
        u8"নাটুৰ গ্ৰীষ্মকালীন সময়ভেনিজুৱেলাৰ সময়ভ্লাডিভোষ্টোকৰ সময়ভ্লাডিভোষ্টোকৰ মান সময়ভ্লাডিভোষ্টোকৰ গ্ৰী"
        u8"ষ্মকালীন সময়ভোল্গোগ্ৰাডৰ সময়ভোল্গোগ্ৰাডৰ মান সময়ভোল্গোগ্ৰাডৰ গ্ৰীষ্মকালীন সময়ভোষ্টকৰ সময়ৱেক দ্ব"
        u8"ীপৰ সময়ৱালিছ আৰু ফুটুনাৰ সময়য়াকুত্স্কৰ সময়য়াকুত্স্কৰ মান সময়য়াকুত্স্কৰ গ্ৰীষ্মকালীন সময়য়েকা"
        u8"টেৰিণবাৰ্গৰ সময়য়েকাটেৰিণবাৰ্গৰ মান সময়য়েকাটেৰিণবাৰ্গৰ গ্ৰীষ্মকালীন সময়য়ুকোন সময়{0} ({1}){0}, "
        u8"{1}{0} সময়{0} (+0) মান সময়{0} (+1) ডেলাইট সময়{1} ({0}){0} {1}";
    inline constexpr const char8_t* NameChunks[] = {NameChunk0};
    inline constexpr uint16_t NameChunkSizes[] = {55765};
    inline constexpr char NameRefsChunk0[] =
        "AAAAAAAAAAAMAAAqAAA8AABOAABdAAB7AACHAACTAACfAACuAADiAAD3AAEPAAEhAAE2AAFCAAFuAAGAAAGVAAGxAAHGAAHPAAHq"
        "AAICAAIUAAIgAAI1AAJWAAJoAAJ9AAKJAAKnAAK5AALFAALgAAL7AAMQAAMlAAMxAANJAANSAANnAAN2AAOLAAOdAAOpAAO7AAPN"
        "AAPcAAPxAAQGAAQbAAQqAARCAAROAARgAARvAAR7AASQAASrAAS9AATSAAUDAAUbAAU2AAVFAAWAAAWiAAXUAAXqAAYhAAZfAAZo"
        "AAaNAAayAAbBAAbNAAbcAAbuAAcDAAcSAAcnAAdkAAeQAAelAAe3AAfJAAf3AAgJAAgbAAg0AAhDAAhVAAhkAAhtAAh5AAiLAAia"
        "AAisAAjmAAkXAAk/AAlqAAmLAAmgAAneAAoSAApDAApeAAptAAp/AAqRAAqdAAqsAAq7AArTAArrAAr9AAsGAAsbAAtPAAtxAAuQ"
        "AAvHAAvoAAwiAAwxAAw3AAxcAAxlAAyDAAyhAAy5AAzXAAz5AA0OAA0aAA0sAA1BAA1QAA1fAA1uAA2iAA20AA3GAA3nAA3wAA4U"
        "AA4/AA5wAA6UAA6gAA6+AA7ZAA7rAA8SAA8eAA8wAA9RAA94AA+HAA+gAA/2ABAFABAUABAdABA7ABBWABB0ABCGABCbABCwABDC"
        "ABDUABDvABEBABEQABEZABErABFPABFeABFzABGgABGsABHBABHNABHsABIBABIlABI0ABJAABJbABJzABJ/ABKdABKyABLKABLc"
        "ABLrABL9ABMlABNDABNSABNqABOCABOXABO4ABPNABPcABPoABP9ABQYABQkABQ5ABRIABRaABRpABSTABSuABTAABThABUCABUd"
        "ABUvABVKABVfABVoABWWABWiABXBABXWABX6ABYcABY7ABZNABZWABZiABZ0ABaPABanABa5ABbLABbgABbvABcBABcTABcfABc6"
        "ABdSABd3ABeDABebABeqABe8ABfaABf4ABgTABgrABhAABhfABhuABh6ABiMABibABiwABjFABjkABjzABkOABkjABk4ABlcABlr"
        "ABmPABmbABnMABn0ABoQABoiABo0ABpPABphABp5ABqCABqXABqvABrvABsNABsrABs6ABtJABtrABuKABucABuuABvGABveABvz"
        "ABwuABxcABx1AByjABy+ABzNABziABz0AB0MAB0nAB1FAB1sAB2EAB21AB3EAB3TAB4KAB4oAB43AB5PAB6MAB7DAB7bAB7wAB8L"
        "AB8gAB8+AB9fAB9xAB+DAB+bAB+/AB/RAB/pACAEACAuACA3ACBMACBkACBwACCIACCdACCyACDEACDoACEGACEVACEnACFGACFS"
        "ACGAACGSACGqACGzACHFACHaACH+ACI7ACJKACJ4ACKRACKtACLPACLbACLwACMCACMaACM4ACNgACNyACN+ACOsACPdACP4ACQK"
        "ACQcACQ0ACRcACR6ACSSACSzACTCACT5ACULACUdACUpACU4ACVHACVcACVlACV6ACWYACWtACXFACXaACXsACX+ACYTACYsACZF"
        "ACZXACZpACZ7ACaKACa1ACbNACbfACb0ACcSACcwACd0ACeJACeYACe5ACfUACfzACgCACgRACgaACgsAChKAChoACh6ACiPACih"
        "ACiwACjCACjUACjgACjvACkIACkdACkpACk7AClHAClcAClxACmDACmVACmqACnFACnUACoqACo2ACpYACqAACqMACqYACrFACrR"
        "ACrgACr1ACsaACtCACtdACuOACuwACvbACwDACwlACxcACx3ACyfACy9ACzlAC0ZAC1IAC15AC2jAC3EAC4BAC4fAC4xAC5QAC5+"
        "AC6NAC6yAC7UAC7/AC8xAC9WAC+BAC+WAC/IAC/pADAnADA8ADBXADB1ADCHADCrADDMADD3ADEVADE5ADFIADF2ADGUADHbADH2"
        "ADIOADIpADJLADJpADJ+ADKWADKlADLTADLrADMAADMYADNYADNtADOCADORADOtADPIADPdADPsADP+ADQ+ADRlADSsADTZADT6"
        "ADUaADVCADVOADVjADVsADWHADW1ADXUADXjADX/ADYUADZCADZaADZ1ADaNADa+ADbQADboADcAADc3ADdSADd+ADeTADexADfD"
        "ADfxADgPADghADg/ADhhADh2ADiOADiaADjOADj4ADkjADk4ADlEADlpADmBADmZADnBADnWADniADoAADoeADo5ADpFADpgADqR"
        "ADqgADsgADs+ADtNADtpADt+ADuqADwRADwpADxKADxZADxuADyfADzDADzhADzzAD0NAD0ZAD1wAD18AD2IAD2gAD2vAD3BAD3W"
        "AD3oAD33AD4MAD4wAD5OAD5mAD57AD60AD7ZAD8BAD8TAD9EAD9lAD9xAD+DAD+rAD/PAD/nAEACAEAUAEA1AEBZAEBxAECGAECY"
        "AECqAEC/AEDgAEEIAEEpAEFjAEGUAEGgAEHNAEHrAEIZAEJjAEJ+AEKiAELAAELSAELkAEL8AEMOAEMmAENHAENfAEN6AEOlAEO3"
        "AEPZAEP3AEQVAEQzAEQ/AEROAERXAER1AESBAESTAESfAETTAET8AEUXAEUyAEVHAEWVAEXPAEX0AEYfAEY3AEZGAEZeAEZtAEat"
        "AEbIAEbjAEb+AEcTAEcrAEdNAEeBAEeWAEelAEe3AEfPAEf0AEgVAEhUAEh1AEiaAEi2AEjLAEjmAEj7AEkdAElZAEl4AEmdAEmy"
        "AEnNAEoFAEpTAEpcAEqXAEqjAEq7AErcAErxAEsQAEs6AEtVAEthAEt8AEu0AEvGAEvnAEv/AEwUAExeAEx8AEy2AEzLAEzsAE0O"
        "AE1lAE2DAE3NAE4RAE4sAE4+AE5qAE58AE6eAE63AE7GAE7YAE7zAE8bAE82AE9RAE95AE+IAE+jAE+7AE/NAE/cAFBLAFBdAFBy"
        "AFCKAFCiAFC6AFDsAFEBAFEKAFEfAFE6AFFSAFGAAFGMAFGkAFG/AFHkAFH8AFIOAFIkAFI2AFJIAFJjAFJ7AFKQAFKcAFKlAFLK"
        "AFLZAFLrAFL9AFMMAFMrAFNKAFNvAFO0AFPKAFPsAFQOAFQ/AFRtAFSbAFTPAFT3AFUoAFWkAFXVAFX9AFYiAFZKAFaBAFapAFbL"
        "AFcFAFc8AFdnAFeVAFfAAFfuAFgKAFg1AFhUAFhzAFiYAFi0AFjfAFkOAFktAFlcAFl4AFmdAFm8AFnkAFoMAFo0AFpoAFqTAFqf"
        "AFrEAFsOAFs2AFteAFt6AFurAFvZAFv4AFwvAFxUAFxuAFyiAFzNAF0EAF1EAF15AF2bAF26AF3oAF4ZAF5NAF5yAF6jAF7CAF7w"
        "AF8eAF9VAF+GAF+7AF/zAGAYAGBZAGCKAGCvAGDXAGD/AGEtAGFMAGFuAGGWAGHBAGHjAGIFAGI2AGJkAGKPAGLGAGLuAGMoAGNQ"
        "AGOHAGO4AGPgAGQaAGROAGR5AGSqAGTkAGUSAGVGAGVlAGWQAGWyAGXvAGYXAGZNAGZyAGadAGa/AGb2AGcbAGc9AGdrAGeWAGfE"
        "AGfjAGgnAGhJAGhuAGiTAGi7AGjgAGkYAGlQAGl4AGmdAGnYAGoqAGpVAGqDAGq0AGrHAGr7AGs4AGtmAGuIAGuqAGvvAGwYAGxP"
        "AGyJAGy3AGzTAG0BAG0vAG1jAG2aAG3XAG3/AG4hAG5DAG5/AG63AG75AG8PAG80AG9oAG+PAG+3AG/yAHAjAHBhAHBkAHCAAHCP"
        "AHCeAHC5AHDLAHDjAHD7AHENAHEZAHEoAHE6AHFJAHFYAHFqAHF2AHGoAHHDAHHlAHH9AHIWAHIuAHJEAHJaAHJ4AHKKAHKZAHKr"
        "AHLDAHLlAHL+AHMTAHMiAHM0AHNGAHNbAHN6AHOSAHOnAHO/AHPOAHPmAHQHAHQdAHQ7AHRHAHRfAHRrAHSDAHSYAHStAHTLAHTq"
        "AHT6AHUhAHU2AHVYAHWAAHWfAHWuAHXAAHXbAHYGAHYVAHYzAHZMAHZhAHZ/AHaOAHagAHa7AHbKAHbcAHbxAHcDAHcSAHcwAHdC"
        "AHdaAHd5AHeYAHewAHfFAHftAHgYAHgqAHg/AHhXAHh5AHiRAHipAHi+AHjTAHjuAHkKAHksAHlRAHlwAHl/AHmUAHmyAHnEAHni"
        "AHnxAHoGAHokAHo2AHpbAHp8AHqUAHqmAHq4AHrKAHrmAHsEAHsfAHs9AHtMAHtkAHt5AHuXAHusAHvUAHvyAHwNAHwoAHw3AHxG"
        "AHxfAHx0AHyGAHyVAHyqAHzMAHzkAHz/AH0OAH0gAH04AH1EAH1TAH1xAH2AAH3HAH3cAH3uAH39AH4PAH4YAH4/AH5jAH54AH6Q"
        "AH6iAH60AH7fAH7uAH77AH8fAH80AH9dAH94AH+QAH+xAH/MAH/eAIAEAIAfAIAxAIBAAIBSAIBkAIB/AICIAICaAICpAIC+AIDc"
        "AID4AIETAIExAIFDAIFVAIF0AIGMAIGYAIGqAIHIAIHXAIHmAIH7AIITAIIxAIJDAIJqAIJ8AIKLAIKdAIK7AILNAILoAIL0AIMM"
        "AIMtAINCAINdAINyAIOZAIO0AIPGAIPeAIPwAIQCAIQUAIQvAIQ+AIRQAIRlAISAAISkAIS8AITgAIUCAIUgAIU7AIVsAIWEAIWf"
        "AIXEAIXfAIXxAIYDAIYnAIY2AIZIAIZgAIZ1AIaKAIacAIarAIbDAIbhAIbwAIcLAIcXAIcmAIc1AIdKAIdfAIdrAId9AIeVAIez"
        "AIfeAIf8AIgOAIgdAIgvAIhKAIhlAIhxAIiGAIiYAIiqAIi5AIjUAIjvAIkHAIkrAIk6AIlbAIlwAImOAIm1AInEAInWAIoDAIoS"
        "AIo5AIpOAIpmAIqQAIq9AIrbAIrnAIsFAIspAItBAItWAItvAIuEAIuxAIvJAIvbAIvtAIv/AIwgAIwsAIxBAIxWAIx3AIybAIy8"
        "AIzUAIzjAIz7AI0ZAI0lAI07AI2CAI2dAI21AI3aAI31AI4NAI4WAI4lAI46AI5PAI5bAI58AI6LAI6jAI6+AI7nAI7/AI8RAI8x"
        "AI86AI9bAI9zAI+CAI+LAI+XAI+gAI+1AI/NAI/lAI/0AJAYAJA3AJBGAJBbAJBtAJCjAJDgAJEZAJErAJFDAJF7AJG/AJH1AJIh"
        "AJJWAJKLAJK4AJLQAJL8AJMxAJNJAJNlAJOGAJOkAJO8AJPRAJP8AJQRAJQpAJRIAJRsAJR4AJSHAJSZAJSlAJTJAJTbAJTtAJUe"
        "AJVQAJV/AJXBAJX5AJY7AJaYAJa9AJbsAJckAJdDAJdsAJewAJgEAJhiAJjJAJkUAJlpAJnHAJobAJp5AJrgAJsuAJuGAJvOAJvw"
        "AJwcAJxRAJxwAJyZAJzLAJz8AJ03AJ2NAJ3aAJ4xAJ6jAJ7RAJ8JAJ9cAJ+EAJ+2AJ/xAKAyAKCPAKD1AKFkAKHdAKJfAKKpAKL9"
        "AKNaAKOqAKQEAKRnAKSVAKTNAKUgAKU/AKVrAKWyAKXaAKYMAKZZAKZ4AKagAKbRAKcMAKdiAKejAKfPAKgFAKhWAKiCAKihAKjK"
        "AKj8AKkYAKk+AKl/AKmYAKm7AKnnAKolAKpjAKqOAKrDAKsTAKtLAKuNAKv3AKwWAKw/AKxxAKyQAKzPAKz4AK0qAK1mAK29AK3i"
        "AK4UAK5QAK6nAK7iAK8nAK+HAK/PALAQALBbALDBALEFALFTALG8ALHYALH+ALI/ALJ3ALLYALMDALMuALNWALOIALPVALQcALRL"
        "ALSDALTFALUiALVjALWuALYUALZGALZrALajALblALcwALdNALd0ALe2ALfYALgEALhLALh3ALiDALi7ALjpALkqALl0ALnEALng"
        "ALoGALo1ALpgALqVALrlALsHALszALtoALuHALuwALviALwQALxIALyJALyuALzdAL0VAL06AL13AL2+AL4dAL5RAL6MAL6yAL7i"
        "AL8bAL9AAL9vAL+5AL/qAMASAMA6AMCEAMCmAMDSAMEZAME4AMF5AMHEAMIYAMJDAMJ4AMLIAMLnAMMQAMNUAMN8AMObAMO6AMP1"
        "AMQ6AMSaAMTIAMUAAMVBAMV7AMW/AMYMAMYrAMZdAMafAMb2AMdHAMeiAMgYAMhMAMiKAMjjAMkCAMkrAMlvAMmaAMnPAMofAMo+"
        "AMp3AMqfAMrRAMseAMs6AMtgAMuhAMvJAMv7AMxIAMyMAMzqAM1SAM3DAM3uAM4QAM44AM5jAM6FAM6qAM7ZAM8jAM9FAM9xAM+m"
        "AM/LAM/9ANBBANB8ANChANDAANDiANEEANEwANFlANGWANG7ANHXANH9ANI+ANJdANKXANLbANM6ANNfANOEANOzANP9ANQuANRp"
        "ANS/ANThANUNANVUANWCANW5ANX6ANZWANaHANbCANcYANc6ANdjANefANfNANgFANhYANiVANjcANk+ANldANlmANluANl+ANmd"
        "ANnFANnOANnV";
    inline constexpr const char* NameRefsChunks[] = {NameRefsChunk0};
    inline constexpr Packed NameRefs{NameRefsChunks, 13, 4};
    inline constexpr Text NameTexts{NameChunks, NameChunkSizes, NameRefs};

    inline constexpr char LanguageKeysChunk0[] =
        "AAhAAiAAmAArAAtAAuAAyAAzAA2AA5AA6ABBABFABHABJABNABOABPABSABTABhABlABoABvABzAB1AB2AB5ACBACFACWACaAClA"
        "CsACuACvACzAC0AC1ADBADGADJADKADPADSADZADhADkADsADuAD1AD2AEBAEFAEJAESAEUAEVAEZAEaAEhAEkAElAEnAEpAEvAE"
        "zAE0AE1AFBAFWAFhAFpAFqAFrAFsAFtAFuAFvAFyAFzAF1AF2AF3AF5AGBAGCAGHAGJAGOAGPAGUAGVAGWAGnAGoAGpAGrAGsAGu"
        "AGyAGzAG0AG5AHBAHCAHEAHFAHHAHMAHOAHPAHSAHWAHZAHjAHtAHyAHzAIBAIMAITAIUAI1AJNAJOAJPAJVAJXAJhAJjAJkAJlA"
        "JnAJpAJrAJsAJtAJuAJvAJxAJyAJzAJ0AJ1AJ2AJ3AKBAKFAKHAKIAKJAKLAKOAKPAKSAKTAKUAKZAKnAKrAKyAK6ALFALJALPAL"
        "hALvAMIAMpAMvANBANIANVARlASBASZATxAUuAWFAWUAXOAXQAZOAZQAZTAZhAZ0AaKAbhAguAgzAitAi6AjjAkPAkuAmBAmPApY"
        "AqnAsuAw5AxwAyiAznA0LA0NA0PA0QA0SA0ZA1iA2DA5HA5KA5LA5MA5NA5SA5TA53BArBAyBA2BDyBFFBHpBJiBKhBMvBNHBRVB"
        "TJBVhBbvBksBnuBpDBpSBqyBwhBy6B0sB3yB53B66B7pCApCA3CA4CEsCGuCJiCKwCKyCRBCRCCV0CWPCXIChPCjvCmjCwiCwjCw"
        "qCwtCxECxnCyFCyhCzPCzwC0BC0RC1qC2OC2iC3rC4FC5DC5MC5VC5iC5mC5oC6tC7rC8WDAkDAnDC6DEqDEsDF0DGvDH1DH6DJD"
        "DJtDKhDKuDKvDKzDK5DQkDQnDQpDQrDQzDSGDSuDSyDTFDToDTvDUjDUuDXJDXlDXoDXzDahDasDazDbsDc2DdODgwDgxDiTDi3D"
        "khDk1DmnDnIDnnDovDpvDqzDsuD1CD1DD1TD1XD1hEAnEAtEAwEA1EBtEEzEItEJHEajEgqEgwEgyEkHEnmEqwErrEwkEwoEwxEw"
        "0ExBExQExuExvEyoEyzE0JE0OE2IE2hE2qE2uE2zE3LE5OE55E6SE6rE7iE8yE9MFBlFCtFCvFC0FD4FEUFEnFGIFGJFHrFIJFJW"
        "FKNFKtFLMFLxFM2FNNFSNFWiFXEFgpFijFm3FquFwlFwsFwyF61GAsGHSGHnGQ2GRCGZMGalGjoGquGsYGtB";
    inline constexpr const char* LanguageKeysChunks[] = {LanguageKeysChunk0};
    inline constexpr Packed LanguageKeys{LanguageKeysChunks, 13, 3};

    inline constexpr char LanguageNamesChunk0[] =
        "AABAACAAGAAJAAMAANAAQAAVAAZAAbAAcAAdAAgAAjAAmAAqAArAAsAAtAAvAAyAA1AA4ABBABJABLABMABNABOABSABaABcABfA"
        "BiABjABoABpABtABuABwAByABzAB1AB2AB4AB+AB/ACBACEACFACIACKACMACQACRACUACWACXACaACbACcACfACgAChACiACmAC"
        "nACoACpACqACuACvAC8AC9AC+ADAADCADEADFADIADMADQADSADTADWADXADaADcADdADiADjADoADpADvAD5AD8AD9AEAAEBAEC"
        "AEHAEIAEJAEOAERAEUAEVAEXAEZAEcAEfAEhAEkAEnAEoAEqAEwAExAEyAEzAE6AE9AE+AFBAFHAFIAFJAFMAFOAFQAFXAFaAFbA"
        "FeAFhAFiAFjAFlAFqAFsAFtAFuAFwAFyAF0AF2AF3AF8AF+AGCAGEAGGAGIAGLAGMAGPAGRAGSAGXAGbAGcAGfAGgAGiAGkAGmAG"
        "oAGsAGvAG0AG1AG4AG6AG9AADAAEAAFAAHAAIAAKAALAAOAAPAASAATAAUAAWAAXAAYAAaAAeAAfAAhAAiAAkAAlAAnAAoAApAAu"
        "AAwAAxAAzAA0AA2AA3AA5AA6AA7AA8AA9AA+AA/ABAABCABDABEABFABGABHABIABKABPABQABRABVABWABXABYABZABbABdABeA"
        "BgABhABvAB0AB3AB7AB8AB9ACAACCACDACGACHACJACLACNACOACPACSACTACVACYACZACdACeACjACkAClACrACsACtACwACxAC"
        "yACzAC0AC1AC2AC3AC4AC5AC6AC7AC/ADBADDADGADHADJADKADLADNADOADPADRADUADVADYADZADbADeADfADgADhADkADlADm"
        "ADnADqADrADsADtADuADwADxADyADzAD0AD1AD2AD3AD4AD6AD7AD+AD/AEDAEEAEFAEGAEKAELAEMAENAEPAEQAESAETAEWAEYA"
        "EaAEbAEeAEgAEiAEjAElAEmAEpAErAEsAEtAEuAEvAE0AE1AE2AE3AE4AE5AE7AE8AFCAFDAFEAFFAFGAFLAFNAFPAFRAFSAFTAF"
        "UAFVAFWAFYAFZAFcAFdAFfAFgAFkAFmAFnAFoAFpAFrAFvAFxAFzAF1AF5AF6AF7AF9AF/AGAAGBAGDAGFAGHAGJAGKAGNAGOAGQ"
        "AGTAGUAGVAGWAGYAGZAGaAGdAGeAGhAGjAGlAGnAGpAGqAGrAGtAGuAGwAGxAGyAGzAG2AG3AG5AG+AG/AHA";
    inline constexpr const char* LanguageNamesChunks[] = {LanguageNamesChunk0};
    inline constexpr Packed LanguageNames{LanguageNamesChunks, 13, 3};

    inline constexpr const uint64_t* TaggedKeys = nullptr;

    inline constexpr const uint16_t* TaggedNames = nullptr;

    inline constexpr char RegionKeysChunk0[] =
        "AAeAAfAAgAAhAAiAAkAAnAAoAAqAAsAAtAAuAAvAAwAAyAAzAA1AA3AA4AA6AA7AA8AA9AA+AA/ABAABCABDABEABFABHABIABJA"
        "BKABMABNABPABQABSABUABVABXABYABZABaABcABdABeABfABgABhABjABmABnABoABpABqABrABxABzAB2AB3AB5AB7ACGACIAC"
        "KACMACOACPACZACaACbACcAChACrACsACtACvACxAC0AC+AC/ADBADCADDADEADFADGADJADKADLADNADOADPADQADRADSADUADW"
        "ADjADlADmADqADsADtAD2AD3AD4AD/AEAAEBAECAEEAEFAEGAEHAETAEbAEdAEeAEuAEwAExAEyAE2AE3AE5AE7AFAAFCAFDAFFA"
        "FGAFHAFNAFPAFWAFXAFYAFZAFaAFdAFgAFiAFjAFkAFlAFmAFnAFqAFrAFsAFtAFuAFvAFwAFxAFyAFzAF0AF1AF2AF3AF4AF5AF"
        "7AF9AF/AGAAGBAGDAGGAGJAGKAGMAGPAGUAGiAGxAG1AG2AG3AG4AG7AG8AG9AG+AHCAHDAHEAHHAHJAHMAHaAHrAH1AH5AH7AH9"
        "AICAIDAIEAIFAIGAIIAIJAIKAILAIMAINAIOAIPAIQAITAIUAIVAIXAIZAIaAIbAIdAIfAIgAIiAIjAIkAImAInAIoAIpAIqAIrA"
        "IuAIwAIyAIzAI2AI4AI+AJEAJFAJKAJQAJRAJTAJVAJXAJZAJbAJgAJnAJzAKAAKJAKKAKTAKoAK3AK/ALLALVALYALaALbALcAL"
        "eALiALkALmALnALoALqALrALsALuAL2AL3AL7AL8AMAAMOAMPAMSAMWANnANoANqANvANwANzAN0AOjAR8";
    inline constexpr const char* RegionKeysChunks[] = {RegionKeysChunk0};
    inline constexpr Packed RegionKeys{RegionKeysChunks, 13, 3};

    inline constexpr char RegionNamesChunk0[] =
        "AHgAHhAHiAHjAHkAHlAHmAHnAHoAHpAHqAHrAHsAHtAHuAHvAHwAHxAHyAHzAH0AH1AH2AH3AH4AH5AH6AH7AH8AH9AH+AH/AIAA"
        "IBAICAIDAIEAIFAIGAIHAIIAIJAIKAILAIMAINAIOAIPAIQAIRAISAITAIUAIVAIWAIXAIYAIZAIaAIbAIcAIdAIeAIfAIgAIhAI"
        "iAIjAIkAIlAImAInAIoAIpAIqAIrAIsAItAIuAIvAIwAIxAIyAIzAI0AI1AI2AI3AI4AI5AI6AI7AI8AI9AI+AI/AJAAJBAJCAJD"
        "AJEAJFAJGAJHAJIAJJAJKAJLAJMAJNAJOAJPAJQAJRAJSAJTAJUAJVAJWAJXAJYAJZAJaAJbAJcAJdAJeAJfAJgAJhAJiAJjAJkA"
        "JlAJmAJnAJoAJpAJqAJrAJsAJtAJuAJvAJwAJxAJyAJzAJ0AJ1AJ2AJ3AJ4AJ5AJ6AJ7AJ8AJ9AJ+AJ/AKAAKBAKCAKDAKEAKFAK"
        "GAKHAKIAKJAKKAKLAKMAKNAKOAERAKPAKQAKRAKSAKTAKUAKVAKWAKXAKYAKZAKaAKbAKcAKdAKeAKfAKgAKhAKiAKjAKkAKlAKm"
        "AKnAKoAKpAKqAKrAKsAKtAKuAKvAKwAKxAKyAKzAK0AK1AK2AK3AK4AK5AK6AK7AK8AK9AK+AK/ALAALBALCALDALEALFALGALHA"
        "LIALJAGVALKALLALMALNALOALPALQALRALSALTALUALVALWALXALYALZALaALbALcALdALeALfALgALhALiALjALkAHBAHCAHDAH"
        "EAHFAHGAHHAHIAHJAHKAHLAHMAHNAHOAHPAHQAHRAHSAHTAHUAHVAHWAHXAHYAHZAHaAHbAHcAHdAHeAHf";
    inline constexpr const char* RegionNamesChunks[] = {RegionNamesChunk0};
    inline constexpr Packed RegionNames{RegionNamesChunks, 13, 3};

    inline constexpr char ScriptKeysChunk0[] =
        "AJGNAMgiAMguAMmuARXHAT4PAUgpAYVtAYXTAaCyAeZMAhbBAtEJA5XyA8irA9VSA9ZVBAXCBAXHBAXJBAXTBAXUBBRSBCZBBEl0"
        "BQWvBUAuBYXBBaGyBbiBBb5FBgXvBgaOBrMtBr3HBtCpBuWyBy3vB7BrB8shCT0HCaXICdXECeZDCgWsChWVChnHCiAhCiApCiRU"
        "CwUpDKUpDTaIDU8lDU8tDWMYDWc5DWta";
    inline constexpr const char* ScriptKeysChunks[] = {ScriptKeysChunk0};
    inline constexpr Packed ScriptKeys{ScriptKeysChunks, 13, 4};

    inline constexpr char ScriptNamesChunk0[] =
        "ALlAAQALmACaAArALnALoALpALqALrALsALtALuACvABiACIALvALwALxALyALzAL0ACQAL1AL2AL3ACqAL4ADCADEADFADjADXA"
        "EBAL5AL6AL7AL8AL9AExAL+AL/AMAAMBAF8AF+AMCAMDAGEAAsAGhAMEAMFAMGAMHAMIAMJAMK";
    inline constexpr const char* ScriptNamesChunks[] = {ScriptNamesChunk0};
    inline constexpr Packed ScriptNames{ScriptNamesChunks, 13, 3};

    inline constexpr char AloneKeysChunk0[] =
        "BAXTBAXU";
    inline constexpr const char* AloneKeysChunks[] = {AloneKeysChunk0};
    inline constexpr Packed AloneKeys{AloneKeysChunks, 13, 4};

    inline constexpr char AloneNamesChunk0[] =
        "AMLAMM";
    inline constexpr const char* AloneNamesChunks[] = {AloneNamesChunk0};
    inline constexpr Packed AloneNames{AloneNamesChunks, 13, 3};

    inline constexpr char CurrencyKeysChunk0[] =
        "ASkATOAWMAWkAXhAZTAakAbnAdOAgtAhEAiUAjuAkEAkmAmkAnEAniApMApkAqOArwAsuAtEAwkAyGA0GA2QA3ZA3wA5DA6wA7FA"
        "9LBFGBFrBHwBNEBTwBZOBaCBayBlEBlwBxQBysB0TB0wB2kB3GB6RB8kCFkCHMCKHCKmCSSCWTCXSCYkCZSCZrCmkCnkCoZCyzCz"
        "zC0SC2mC4XC5XC7kC8kC9UDArDBQDFyDJEDJsDMkDQkDSMDThDVkDWrDXUDXwDZVDayDbSDbrDcODcyDdODgkDjuDkvDnrDoSDtE"
        "D2yEAiECuEDrEEQEFyEGOEMnEQyEnuEpkEqiErmEwyExEExyEyHEyrEzkE0QE2FE3zE5EE5wE6OE8wE9MFECFFTFG0FHEFHwFJZF"
        "KEFLkFNTFQoFT4FZkFc1FdTFizFnEFq2F50GAmGBkGHmGIGGMYGSyGgyGm3";
    inline constexpr const char* CurrencyKeysChunks[] = {CurrencyKeysChunk0};
    inline constexpr Packed CurrencyKeys{CurrencyKeysChunks, 13, 3};

    inline constexpr char CurrencyNamesChunk0[] =
        "AMNAAAAMOAAAAAAAAAAMOAMPAAAAAAAAAAAAAAAAAAAMQAAAAAAAAAAAAAAAAAAAMRAAAAAAAAAAAAAAAAAAAMSAAAAAAAAAAAAA"
        "AAAAAAMTAAAAAAAAAAAAAAAAAAAMUAAAAAAAAAAAAAAAAAAAMVAAAAAAAAAAAAAAAAAAAMWAAAAAAAAAAAAAAAAAAAMXAAAAAAAA"
        "AAAAAAAAAAAMYAAAAAAAAAAAAAAAAAAAMZAAAAAAAAAAAAAAAAAAAMaAAAAAAAAAAAAAAAAAAAMbAAAAAAAAAAAAAAAAAAAMcAAA"
        "AAAAAAAAAAAAAAAAMdAAAAAAAAAAAAAAAAAAAMeAAAAAAAAAAAAAAAAAAAMfAAAAAAAAAAAAAAAAAAAMgAAAAAAAAAAAAAAAAAAA"
        "MhAAAAAAAAAAAAAAAAAAAMiAAAAAAAAAAAAAAAAAAAMjAAAAAAAAAAAAAAAAAAAMkAAAAAAAAAAAAAAAAAAAMlAAAAAAAAAAAAAA"
        "AAAAAMmAAAAAAAAAAAAAAAAAAAMnAAAAAAAAAAAAAAAAAAAMoAAAAAAAAAAAAAAAAAAAMpAAAAAAAAAAAAAAAAAAAMqAAAAAAAAA"
        "AAAAAAAAAAMrAAAAAAAAAAAAAAAAAAAMsAAAAAAAAAAAAAAAAAAAMtAAAAAAAAAAAAAAAAAAAMuAAAAAAAAAAAAAAAAAAAMvAAAA"
        "AAAAAAAAAAAAAAAMwAAAAAAAAAAAAAAAAAAAMxAAAAAAAAAAAAAAAAAAAMyAAAAAAAAAAAAAAAAAAAMzAAAAAAAAAAAAAAAAAAAM"
        "0AAAAAAAAAAAAAAAAAAAM1AAAAAAAAAAAAAAAAAAAM2AAAAAAAAAAAAAAAAAAAM3AAAAAAAAAAAAAAAAAAAM4AAAAAAAAAAAAAAA"
        "AAAAM5AAAAAAAAAAAAAAAAAAAM6AAAAAAAAAAAAAAAAAAAM7AAAAAAAAAAAAAAAAAAAM8AAAAAAAAAAAAAAAAAAAM9AAAAAAAAAA"
        "AAAAAAAAAM+AAAAAAAAAAAAAAAAAAAM/AAAAAAAAAAAAAAAAAAANAAAAAAAAAAAAAAAAAAAANBAAAAAAAAAAAAAAAAAAANCAAAAA"
        "AAAAAAAAAAAAAANDAAAAAAAAAAAAAAAAAAANEAAAAAAAAAAAAAAAAAAANFAAAAAAAAAAAAAAAAAAANGAAAAAAAAAAAAAAAAAAANH"
        "AAAAAAAAAAAAAAAAAAANIAAAAAAAAAAAAAAAAAAANJAAAAAAAAAAAAAAAAAAANKAAAAAAAAAAAAAAAAAAANLAAAANLAAAAAAAAAA"
        "NMANNAAAAAAAAAAAAAAAAAAANOAAAAAAAAAAAAAAAAAAANPAAAAAAAAAAAAAAAAAAANQAAAAAAAAAAAAAAAAAAANRAAAAAAAAAAA"
        "AAAAAAAANSAAAAAAAAAAAAAAAAAAANTAAAAAAAAAAAAAAAAAAANUAAAAAAAAAAAAAAAAAAANVAAAAAAAAAAAAAAAAAAANWAAAAAA"
        "AAAAAAAAAAAAANXAAAAAAAAAAAAAAAAAAANYAAAAAAAAAAAAAAAAAAANZAAAAAAAAAAAAAAAAAAANaAAAAAAAAAAAAAAAAAAANbA"
        "AAAAAAAAAAAAAAAAAANcAAAAAAAAAAAAAAAAAAANdAAAANdAAAAAAAAAANeANfAAAAAAAAAAAAAAAAAAANgAAAAAAAAAAAAAAAAA"
        "AANhAAAANhAAAAAAAAAANiANjAAAAAAAAAAAAAAAAAAANkAAAAAAAAAAAAAAAAAAANlAAAAAAAAAAAAAAAAAAANmAAAAAAAAAAAA"
        "AAAAAAANnAAAAAAAAAAAAAAAAAAANoAAAAAAAAAAAAAAAAAAANpAAAAAAAAAAAAAAAAAAANqAAAAAAAAAAAAAAAAAAANrAAAAAAA"
        "AAAAAAAAAAAANsAAAAAAAAAAAAAAAAAAANtAAAAAAAAAAAAAAAAAAANuAAAAAAAAAAAAAAAAAAANvAAAAAAAAAAAAAAAAAAANwAA"
        "AAAAAAAAAAAAAAAAANxAAAAAAAAAAAAAAAAAAANyAAAANyAAAAAAAAAANzAN0AAAAAAAAAAAAAAAAAAAN1AAAAAAAAAAAAAAAAAA"
        "AN2AAAAAAAAAAAAAAAAAAAN3AAAAAAAAAAAAAAAAAAAN4AAAAAAAAAAAAAAAAAAAN5AAAAAAAAAAAAAAAAAAAN6AAAAAAAAAAAAA"
        "AAAAAAN7AAAAAAAAAAAAAAAAAAAN8AAAAAAAAAAAAAAAAAAAN9AAAAAAAAAAAAAAAAAAAN+AAAAAAAAAAAAAAAAAAAN/AAAAAAAA"
        "AAAAAAAAAAAOAAAAAAAAAAAAAAAAAAAAOBAAAAAAAAAAAAAAAAAAAOCAAAAAAAAAAAAAAAAAAAODAAAAAAAAAAAAAAAAAAAOEAAA"
        "AAAAAAAAAAAAAAAAOFAAAAAAAAAAAAAAAAAAAOGAAAAAAAAAAAAAAAAAAAOHAAAAOHAAAAAAAAAAOIAOJAAAAAAAAAAAAAAAAAAA"
        "OKAAAAAAAAAAAAAAAAAAAOLAAAAAAAAAAAAAAAAAAAOMAAAAAAAAAAAAAAAAAAAONAAAAAAAAAAAAAAAAAAAOOAAAAAAAAAAAAAA"
        "AAAAAOPAAAAAAAAAAAAAAAAAAAOQAAAAAAAAAAAAAAAAAAAORAAAAORAAAAAAAAAAOSAOTAAAAAAAAAAAAAAAAAAAOUAAAAAAAAA"
        "AAAAAAAAAAOVAAAAAAAAAAAAAAAAAAAOWAAAAAAAAAAAAAAAAAAAOXAAAAAAAAAAAAAAAAAAAOYAAAAAAAAAAAAAAAAAAAOZAAAA"
        "AAAAAAAAAAAAAAAOaAAAAAAAAAAAAAAAAAAAObAAAAAAAAAAAAAAAAAAAOcAAAAAAAAAAAAAAAAAAAOdAAAAAAAAAAAAAAAAAAAO"
        "eAAAAAAAAAAAAAAAAAAAOfAAAAAAAAAAAAAAAAAAAOgAAAAAAAAAAAAAAAAAAAOhAAAAOiAAAAAAAAAAOjAOkAAAAAAAAAAAAAAA"
        "AAAAOlAAAAAAAAAAAAAAAAAAAOmAAAAAAAAAAAAAAAAAAAOnAAAAAAAAAAAAAAAAAAAOoAAAAAAAAAAAAAAAAAAAOpAAAAAAAAAA"
        "AAAAAAAAAOqAAAAAAAAAAAAAAAAAAAOrAAAAOsAAAAAAAAAAOtAOuAAAAAAAAAAAAAAAAAAAOvAAAAAAAAAAAAAAAAAAAOwAAAAA"
        "AAAAAAAAAAAAA";
    inline constexpr const char* CurrencyNamesChunks[] = {CurrencyNamesChunk0};
    inline constexpr Packed CurrencyNames{CurrencyNamesChunks, 13, 3};

    inline constexpr char ZoneKeysChunk0[] =
        "AAAAABAACAADAAEAAFAAGAAHAAIAAJAAKAALAAMAANAAOAAPAAQAARAASAATAAUAAVAAWAAXAAYAAZAAaAAbAAcAAdAAeAAfAAgA"
        "AhAAiAAjAAkAAlAAmAAnAAoAApAAqAArAAsAAtAAuAAvAAwAAxAAyAAzAA0AA1AA2AA3AA4AA5AA6AA7AA8AA9AA+AA/ABAABBAB"
        "CABDABEABFABGABHABIABJABKABLABMABNABOABPABQABRABSABTABUABVABWABXABYABZABaABbABcABdABeABfABgABhABiABj"
        "ABkABlABmABnABoABpABqABrABsABtABuABvABwABxAByABzAB0AB1AB2AB3AB4AB5AB6AB7AB8AB9AB+AB/ACAACBACCACDACEA"
        "CFACGACHACIACJACKACLACMACNACOACPACQACRACSACTACUACVACWACXACYACZACaACbACcACdACeACfACgAChACiACjACkAClAC"
        "mACnACoACpACqACrACsACtACuACvACwACxACyACzAC0AC1AC2AC3AC4AC5AC6AC7AC8AC9AC+AC/ADAADBADCADDADEADFADGADH"
        "ADIADJADKADLADMADNADOADPADQADRADSADTADUADVADWADXADYADZADaADbADcADdADeADfADgADhADiADjADkADlADmADnADoA"
        "DpADqADrADsADtADuADvADwADxADyADzAD0AD1AD2AD3AD4AD5AD6AD7AD8AD9AD+AD/AEAAEBAECAEDAEEAEFAEGAEHAEIAEJAE"
        "KAELAEMAENAEOAEPAEQAERAESAETAEUAEVAEWAEXAEYAEZAEaAEbAEcAEdAEeAEfAEgAEhAEiAEjAEkAElAEmAEnAEoAEpAEqAEr"
        "AEsAEtAEuAEvAEwAExAEyAEzAE0AE1AFRAFSAFTAFUAFVAFWAFXAFYAFZAFaAFbAFcAFdAFeAFfAFgAFhAFiAFjAFkAFlAFmAFnA"
        "FoAFpAFqAFrAFsAFtAFuAFvAFwAFxAFyAFzAF0AF1AF2AF3AF4AF5AF6AF7AF8AF9AF+AF/AGAAGBAGCAGDAGEAGFAGGAGHAGIAG"
        "JAGKAGLAGMAGNAGOAGPAGQAGRAGSAGTAGUAGVAGWAGXAGYAGZAGaAGbAGcAGdAGeAGfAGgAGhAGiAGjAGkAGlAGnAGoAGpAGqAGr"
        "AGsAGtAGuAGvAGwAGxAGyAGzAG0AG1AG2AG3AG4AG5AG6AG7AG8AG9";
    inline constexpr const char* ZoneKeysChunks[] = {ZoneKeysChunk0};
    inline constexpr Packed ZoneKeys{ZoneKeysChunks, 13, 3};

    inline constexpr char ZoneNamesChunk0[] =
        "AQaAAAAAAAAAAAAAAAAAAAREAAAAAAAAAAAAAAAAAAAQ3AAAAAAAAAAAAAAAAAAAQtAAAAAAAAAAAAAAAAAAAQzAAAAAAAAAAAAA"
        "AAAAAASFAAAAAAAAAAAAAAAAAAAQXAAAAAAAAAAAAAAAAAAARJAAAAAAAAAAAAAAAAAAAROAAAAAAAAAAAAAAAAAAASNAAAAAAAA"
        "AAAAAAAAAAAQYAAAAAAAAAAAAAAAAAAAPlAAAAAAAAAAAAAAAAAAAQxAAAAAAAAAAAAAAAAAAAR9AAAAAAAAAAAAAAAAAAAQ1AAA"
        "AAAAAAAAAAAAAAAARKAAAAAAAAAAAAAAAAAAATiAAAAAAAAAAAAAAAAAAAT5AAAAAAAAAAAAAAAAAAAIcAAAAAAAAAAAAAAAAAAA"
        "BZAAAAAAAAAAAAAAAAAAAQyAAAAAAAAAAAAAAAAAAAThAAAAAAAAAAAAAAAAAAAP7AAAAAAAAAAAAAAAAAAAUqAAAAAAAAAAAAAA"
        "AAAAAUoAAAAAAAAAAAAAAAAAAATlAAAAAAAAAAAAAAAAAAAT8AAAAAAAAAAAAAAAAAAATcAAAAAAAAAAAAAAAAAAATYAAAAAAAAA"
        "AAAAAAAAAAQVAAAAAAAAAAAAAAAAAAAShAAAAAAAAAAAAAAAAAAAQ/AAAAAAAAAAAAAAAAAAATtAAAAAAAAAAAAAAAAAAAO5AAAA"
        "AAAAAAAAAAAAAAAQWAAAAAAAAAAAAAAAAAAAUpAAAAAAAAAAAAAAAAAAARLAAAAAAAAAAAAAAAAAAAScAAAAAAAAAAAAAAAAAAAR"
        "5AAAAAAAAAAAAAAAAAAATpAAAAAAAAAAAAAAAAAAATjAAAAAAAAAAAAAAAAAAAR4AAAAAAAAAAAAAAAAAAARiAAAAAAAAAAAAAAA"
        "AAAATrAAAAAAAAAAAAAAAAAAASfAAAAAAAAAAAAAAAAAAASLAAAAAAAAAAAAAAAAAAAPjAAAAAAAAAAAAAAAAAAAPmAAAAAAAAAA"
        "AAAAAAAAATmAAAAAAAAAAAAAAAAAAAR8AAAAAAAAAAAAAAAAAAATzAAAAAAAAAAAAAAAAAAASdAAAAAAAAAAAAAAAAAAAT/AAAAA"
        "AAAAAAAAAAAAAAUBAAAAAAAAAAAAAAAAAAAHlAAAAAAAAAAAAAAAAAAAO2AAAAAAAAAAAAAAAAAAAPyAAAAAAAAAAAAAAAAAAAPI"
        "AAAAAAAAAAAAAAAAAAAPEAAAAAAAAAAAAAAAAAAAPLAAAAAAAAAAAAAAAAAAAPGAAAAAAAAAAAAAAAAAAAPJAAAAAAAAAAAAAAAA"
        "AAAPNAAAAAAAAAAAAAAAAAAAPHAAAAAAAAAAAAAAAAAAAHuAAAAAAAAAAAAAAAAAAAS7AAAAAAAAAAAAAAAAAAAP0AAAAAAAAAAA"
        "AAAAAAAASTAAAAAAAAAAAAAAAAAAAHyAAAAAAAAAAAAAAAAAAAPxAAAAAAAAAAAAAAAAAAAIFAAAAAAAAAAAAAAAAAAAQSAAAAAA"
        "AAAAAAAAAAAAAPsAAAAAAAAAAAAAAAAAAAQhAAAAAAAAAAAAAAAAAAAUHAAAAAAAAAAAAAAAAAAAPPAAAAAAAAAAAAAAAAAAAQGA"
        "AAAAAAAAAAAAAAAAAAPwAAAAAAAAAAAAAAAAAAASZAAAAAAAAAAAAAAAAAAAUgAAAAAAAAAAAAAAAAAAAPKAAAAAAAAAAAAAAAAA"
        "AARDAAAAAAAAAAAAAAAAAAARsAAAAAAAAAAAAAAAAAAAUNAAAAAAAAAAAAAAAAAAASSAAAAAAAAAAAAAAAAAAASQAAAAAAAAAAAA"
        "AAAAAAAQLAAAAAAAAAAAAAAAAAAAPOAAAAAAAAAAAAAAAAAAAITAAAAAAAAAAAAAAAAAAAQDAAAAAAAAAAAAAAAAAAAPuAAAAAAA"
        "AAAAAAAAAAAAIWAAAAAAAAAAAAAAAAAAARIAAAAAAAAAAAAAAAAAAAP9AAAAAAAAAAAAAAAAAAAQCAAAAAAAAAAAAAAAAAAAUJAA"
        "AAAAAAAAAAAAAAAAAUZAAAAAAAAAAAAAAAAAAAQrAAAAAAAAAAAAAAAAAAAQEAAAAAAAAAAAAAAAAAAAPpAAAAAAAAAAAAAAAAAA"
        "AK4AAAAAAAAAAAAAAAAAAAQBAAAAAAAAAAAAAAAAAAAP1AAAAAAAAAAAAAAAAAAAQRAAAAAAAAAAAAAAAAAAARGAAAAAAAAAAAAA"
        "AAAAAAQQAAAAAAAAAAAAAAAAAAATqAAAAAAAAAAAAAAAAAAAIzAAAAAAAAAAAAAAAAAAAI8AAAAAAAAAAAAAAAAAAAJAAAAAAAAA"
        "AAAAAAAAAAAQvAAAAAAAAAAAAAAAAAAAJDAAAAAAAAAAAAAAAAAAAQPAAAAAAAAAAAAAAAAAAAQiAAAAAAAAAAAAAAAAAAASPAAA"
        "AAAAAAAAAAAAAAAAUSAAAAAAAAAAAAAAAAAAAUUAAAAAAAAAAAAAAAAAAAUQAAAAAAAAAAAAAAAAAAAURAAAAAAAAAAAAAAAAAAA"
        "UXAAAAAAAAAAAAAAAAAAAUPAAAAAAAAAAAAAAAAAAAUTAAAAAAAAAAAAAAAAAAAUVAAAAAAAAAAAAAAAAAAAP/AAAAAAAAAAAAAA"
        "AAAAAQNAAAAAAAAAAAAAAAAAAAJWAAAAAAAAAAAAAAAAAAAPMAAAAAAAAAAAAAAAAAAAUEAAAAAAAAAAAAAAAAAAAUYAAAAAAAAA"
        "AAAAAAAAAAPoAAAAAAAAAAAAAAAAAAAPnAAAAAAAAAAAAAAAAAAASrAAAAAAAAAAAAAAAAAAAUGAAAAAAAAAAAAAAAAAAAUWAAAA"
        "AAAAAAAAAAAAAAATnAAAAAAAAAAAAAAAAAAAP2AAAAAAAAAAAAAAAAAAASiAAAAAAAAAAAAAAAAAAAPtAAAAAAAAAAAAAAAAAAAS"
        "AAAAAAAAAAAAAAAAAAAAJ8AAAAAAAAAAAAAAAAAAASXAAAAAAAAAAAAAAAAAAASRAAAAAAAAAAAAAAAAAAAPFAAAAAAAAAAAAAAA"
        "AAAAUOAAAAAAAAAAAAAAAAAAASYAAAAAAAAAAAAAAAAAAAUFAAAAAAAAAAAAAAAAAAASWAAAAAAAAAAAAAAAAAAAS0AAAAAAAAAA"
        "AAAAAAAAAQOAAAAAAAAAAAAAAAAAAASVAAAAAAAAAAAAAAAAAAAUbAAAAAAAAAAAAAAAAAAASMAAAAAAAAAAAAAAAAAAAP5AAAAA"
        "AAAAAAAAAAAAAAUaAAAAAAAAAAAAAAAAAAAUAAAAAAAAAAAAAAAAAAAAP4AAAAAAAAAAAAAAAAAAAUKAAAAAAAAAAAAAAAAAAAUM"
        "AAAAAAAAAAAAAAAAAAAULAAAAAAAAAAAAAAAAAAASUAAAAAAAAAAAAAAAAAAAKSAAAAAAAAAAAAAAAAAAATkAAAAAAAAAAAAAAAA"
        "AAAUIAAAAAAAAAAAAAAAAAAARSAAAAAAAAAAAAAAAAAAAT2AAAAAAAAAAAAAAAAAAAPrAAAAAAAAAAAAAAAAAAAKbAAAAAAAAAAA"
        "AAAAAAAAQdAAAAAAAAAAAAAAAAAAAQKAAAAAAAAAAAAAAAAAAAP3AAAAAAAAAAAAAAAAAAAQHAAAAAAAAAAAAAAAAAAAQJAAAAAA"
        "AAAAAAAAAAAAAPqAAAAAAAAAAAAAAAAAAAPvAAAAAAAAAAAAAAAAAAAQeAAAAAAAAAAAAAAAAAAAQsAAAAAAAAAAAAAAAAAAAPzA"
        "AAAAAAAAAAAAAAAAAARHAAAAAAAAAAAAAAAAAAAUDAAAAAAAAAAAAAAAAAAAH6AAAAAAAAAAAAAAAAAAAQTAAAAAAAAAAAAAAAAA"
        "AARpAAAAAAAAAAAAAAAAAAAJmAAAAAAAAAAAAAAAAAAAUiAAAAAAAAAAAAAAAAAAAUfAAAAAAAAAAAAAAAAAAAQFAAAAAAAAAAAA"
        "AAAAAAARQAAAAAAAAAAAAAAAAAAARFAAAAAAAAAAAAAAAAAAASOAAAAAAAAAAAAAAAAAAAQMAAAAAAAAAAAAAAAAAAAUhAAAAAAA"
        "AAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAP+AAAAAAAAAAAAAAAAAAAQIAAAAAAAAAAAAAAAAAAAUCAAAAAAAAAAAAAAAAAAAPBAA"
        "AAAAAAAAAAAAAAAAAO/AAAAAAAAAAAAAAAAAAAPCAAAAAAAAAAAAAAAAAAAPcAAAAAAAAAAAAAAAAAAAO+AAAAAAAAAAAAAAAAAA"
        "APDAAAAAAAAAAAAAAAAAAAO7AAAAAAAAAAAAAAAAAAAO6AAAAAAAAAAAAAAAAAAAO9AAAAAAAAAAAAAAAAAAAO8AAAAAAAAAAAAA"
        "AAAAAAPAAAAAAAAAAAAAAAAAAAATfAAAAAAAAAAAAAAAAAAAUnAAAAAAAAAAAAAAAAAAARzAAAAAAAAAAAAAAAAAAARgAAAAAAAA"
        "AAAAAAAAAAATXAAAAAAAAAAAAAAAAAAARtAAAAAAAAAAAAAAAAAAARwAAAAAAAAAAAAAAAAAAATyAAAAAAAAAAAAAAAAAAARvAAA"
        "AAAAAAAAAAAAAAAARcAAAAAAAAAAAAAAAAAAAH3AAAAAAAAAAAAAAAAAAAPfAAAAAAAAAAAAAAAAAAATuAAAAAAAAAAAAAAAAAAA"
        "TJAAAAAAAAAAAAAAAAAAAR1AAAAAAAAAAAAAAAAAAARjAAAAAAAAAAAAAAAAAAAH8AAAAAAAAAAAAAAAAAAARaAAAAAAAAAAAAAA"
        "AAAAATOAAAAAAAAAAAAAAAAAAAR3AAAAAAAAAAAAAAAAAAAToAAAAAAAAAAAAAAAAAAAPhAAAAAAAAAAAAAAAAAAATxAAAAAAAAA"
        "AAAAAAAAAAO0AAAAAAAAAAAAAAAAAAATvAAAAAAAAAAAAAAAAAAAQmAAAAAAAAAAAAAAAAAAAS2AAAAAAAAAAAAAAAAAAAS3AAAA"
        "AAAAAAAAAAAAAAARPAAAAAAAAAAAAAAAAAAASHAAAAAAAAAAAAAAAAAAATNAAAAAAAAAAAAAAAAAAARUAAAAAAAAAAAAAAAAAAAR"
        "WAAAAAAAAAAAAAAAAAAARZAAAAAAAAAAAAAAAAAAAO1AAAAAAAAAAAAAAAAAAATWAAAAAAAAAAAAAAAAAAASyAAAAAAAAAAAAAAA"
        "AAAASlAAAAAAAAAAAAAAAAAAATRAAAAAAAAAAAAAAAAAAATMAAAAAAAAAAAAAAAAAAASaAAAAAAAAAAAAAAAAAAASbAAAAAAAAAA"
        "AAAAAAAAAJhAAAAAAAAAAAAAAAAAAASJAAAAAAAAAAAAAAAAAAATUAAAAAAAAAAAAAAAAAAADzAAAAAAAAAAAAAAAAAAASxAAAAA"
        "AAAAAAAAAAAAAASqAAAAAAAAAAAAAAAAAAAQlAAAAAAAAAAAAAAAAAAATLAAAAAAAAAAAAAAAAAAATIAAAAAAAAAAAAAAAAAAATH"
        "AAAAAAAAAAAAAAAAAAARuAAAAAAAAAAAAAAAAAAARkAAAAAAAAAAAAAAAAAAARVAAAAAAAAAAAAAAAAAAARqAAAAAAAAAAAAAAAA"
        "AAAKgAAAAAAAAAAAAAAAAAAARxAAAAAAAAAAAAAAAAAAARyAAAAAAAAAAAAAAAAAAASGAAAAAAAAAAAAAAAAAAATZAAAAAAAAAAA"
        "AAAAAAAAUjAAAAAAAAAAAAAAAAAAATSAAAAAAAAAAAAAAAAAAAUcAAAAAAAAAAAAAAAAAAARrAAAAAAAAAAAAAAAAAAAQgAAAAAA"
        "AAAAAAAAAAAAAKsAAAAAAAAAAAAAAAAAAATVAAAAAAAAAAAAAAAAAAAT4AAAAAAAAAAAAAAAAAAAUdAAAAAAAAAAAAAAAAAAARCA"
        "AAAAAAAAAAAAAAAAAARdAAAAAAAAAAAAAAAAAAAP6AAAAAAAAAAAAAAAAAAARhAAAAAAAAAAAAAAAAAAATKAAAAAAAAAAAAAAAAA"
        "AASIAAAAAAAAAAAAAAAAAAAQfAAAAAAAAAAAAAAAAAAATTAAAAAAAAAAAAAAAAAAAR0AAAAAAAAAAAAAAAAAAATQAAAAAAAAAAAA"
        "AAAAAAATPAAAAAAAAAAAAAAAAAAATGAAAAAAAAAAAAAAAAAAAO4AAAAAAAAAAAAAAAAAAAS4AAAAAAAAAAAAAAAAAAAH7AAAAAAA"
        "AAAAAAAAAAAAQ0AAAAAAAAAAAAAAAAAAAQjAAAAAAAAAAAAAAAAAAAQ9AAAAAAAAAAAAAAAAAAAS5AAAAAAAAAAAAAAAAAAAReAA"
        "AAAAAAAAAAAAAAAAARNAAAAAAAAAAAAAAAAAAAKtAAAAAAAAAAAAAAAAAAAQ5AAAAAAAAAAAAAAAAAAAPVAAAAAAAAAAAAAAAAAA"
        "APbAAAAAAAAAAAAAAAAAAAPWAAAAAAAAAAAAAAAAAAAPUAAAAAAAAAAAAAAAAAAAPTAAAAAAAAAAAAAAAAAAAPYAAAAAAAAAAAAA"
        "AAAAAAPZAAAAAAAAAAAAAAAAAAAPdAAAAAAAAAAAAAAAAAAAPXAAAAAAAAAAAAAAAAAAAPSAAAAAAAAAAAAAAAAAAAPaAAAAAAAA"
        "AAAAAAAAAAAAAAAAAOxAAAAAAAOyAAAAOzAAAAAAAAAAAAAAAAAAASjAAAAAAAAAAAAAAAAAAAHhAAAAAAAAAAAAAAAAAAATCAAA"
        "AAAAAAAAAAAAAAAARMAAAAAAAAAAAAAAAAAAAS9AAAAAAAAAAAAAAAAAAAQpAAAAAAAAAAAAAAAAAAATgAAAAAAAAAAAAAAAAAAA"
        "PiAAAAAAAAAAAAAAAAAAAS8AAAAAAAAAAAAAAAAAAARTAAAAAAAAAAAAAAAAAAAQoAAAAAAAAAAAAAAAAAAAR+AAAAAAAAAAAAAA"
        "AAAAAQqAAAAAAAAAAAAAAAAAAARXAAAAAAARYAAAAAAAAAAI4AAAAAAAAAAAAAAAAAAAI2AAAAAAAAAAAAAAAAAAAQ4AAAAAAAAA"
        "AAAAAAAAAAJOAAAAAAAAAAAAAAAAAAAT1AAAAAAAAAAAAAAAAAAAJVAAAAAAAAAAAAAAAAAAAS+AAAAAAAAAAAAAAAAAAAT6AAAA"
        "AAAAAAAAAAAAAAATEAAAAAAAAAAAAAAAAAAAS6AAAAAAAAAAAAAAAAAAATeAAAAAAAAAAAAAAAAAAARAAAAAAAARBAAAAAAAAAAJ"
        "sAAAAAAAAAAAAAAAAAAAQ2AAAAAAAAAAAAAAAAAAAJ/AAAAAAAAAAAAAAAAAAAPeAAAAAAAAAAAAAAAAAAAP8AAAAAAAAAAAAAAA"
        "AAAAJwAAAAAAAAAAAAAAAAAAAS/AAAAAAAAAAAAAAAAAAASkAAAAAAAAAAAAAAAAAAAQ+AAAAAAAAAAAAAAAAAAAR/AAAAAAAAAA"
        "AAAAAAAAAQnAAAAAAAAAAAAAAAAAAAR7AAAAAAAAAAAAAAAAAAARfAAAAAAAAAAAAAAAAAAATFAAAAAAAAAAAAAAAAAAAKyAAAAA"
        "AAAAAAAAAAAAAAPgAAAAAAAAAAAAAAAAAAATBAAAAAAAAAAAAAAAAAAAT7AAAAAAAAAAAAAAAAAAASEAAAAAAAAAAAAAAAAAAAPk"
        "AAAAAAAAAAAAAAAAAAATdAAAAAAAAAAAAAAAAAAAQwAAAAAAAAAAAAAAAAAAAO3AAAAAAAAAAAAAAAAAAATDAAAAAAAAAAAAAAAA"
        "AAAR2AAAAAAAAAAAAAAAAAAAUeAAAAAAAAAAAAAAAAAAAPRAAAAAAAAAAAAAAAAAAAR6AAAAAAAAAAAAAAAAAAATAAAAAAAAAAAA"
        "AAAAAAAASzAAAAAAAAAAAAAAAAAAARRAAAAAAAAAAAAAAAAAAAQZAAAAAAAAAAAAAAAAAAASBAAAAAAAAAAAAAAAAAAARbAAAAAA"
        "AAAAAAAAAAAAAQkAAAAAAAAAAAAAAAAAAAQUAAAAAAAAAAAAAAAAAAARoAAAAAAAAAAAAAAAAAAATsAAAAAAAAAAAAAAAAAAATbA"
        "AAAAAAAAAAAAAAAAAAKBAAAAAAAAAAAAAAAAAAAKAAAAAAAAAAAAAAAAAAAALgAAAAAAAAAAAAAAAAAAAKiAAAAAAAAAAAAAAAAA"
        "AAUmAAAAAAAAAAAAAAAAAAASpAAAAAAAAAAAAAAAAAAASwAAAAAAAAAAAAAAAAAAASoAAAAAAAAAAAAAAAAAAAQcAAAAAAAAAAAA"
        "AAAAAAAUkAAAAAAAAAAAAAAAAAAARlAAAAAAAAAAAAAAAAAAATwAAAAAAAAAAAAAAAAAAAIsAAAAAAAAAAAAAAAAAAAT3AAAAAAA"
        "AAAAAAAAAAAAQuAAAAAAAAAAAAAAAAAAASuAAAAAAAAAAAAAAAAAAATaAAAAAAAAAAAAAAAAAAAJBAAAAAAAAAAAAAAAAAAARmAA"
        "AAAAAAAAAAAAAAAAAQ8AAAAAAAAAAAAAAAAAAASCAAAAAAAAAAAAAAAAAAASDAAAAAAAAAAAAAAAAAAAStAAAAAAAAAAAAAAAAAA"
        "AT9AAAAAAAAAAAAAAAAAAASmAAAAAAAAAAAAAAAAAAASnAAAAAAAAAAAAAAAAAAASgAAAAAAAAAAAAAAAAAAASeAAAAAAAAAAAAA"
        "AAAAAAPQAAAAAAAAAAAAAAAAAAAKeAAAAAAAAAAAAAAAAAAAS1AAAAAAAAAAAAAAAAAAAQ7AAAAAAAAAAAAAAAAAAASvAAAAAAAA"
        "AAAAAAAAAAAQbAAAAAAAAAAAAAAAAAAASKAAAAAAAAAAAAAAAAAAASsAAAAAAAAAAAAAAAAAAARnAAAAAAAAAAAAAAAAAAAT0AAA"
        "AAAAAAAAAAAAAAAAQ6AAAAAAAAAAAAAAAAAAAT+AAAAAAAAAAAAAAAAAAAUlAAAAAAAAAAAAAAAAAA";
    inline constexpr const char* ZoneNamesChunks[] = {ZoneNamesChunk0};
    inline constexpr Packed ZoneNames{ZoneNamesChunks, 13, 3};

    inline constexpr char MetaKeysChunk0[] =
        "AABAACAADAAFAAGAAIAALAAMAANAAOAAPAARAAUAAVAAWAAXAAZAAaAAbAAcAAdAAeAAfAAhAAjAAkAAmAAoAApAArAAsAAtAAuA"
        "AvAAwAAxAAyAAzAA1AA3AA6AA7AA8AA9AA+AA/ABAABBABCABDABEABGABHABIABJABKABOABPABRABSABTABUABVABWABXABYAB"
        "ZABaABbABcABeABfABgABjABkABlABnABoABpABsABvABwAByAB0AB1AB2AB3AB4AB5AB6AB7AB8AB9AB+AB/ACAACBACCACDACE"
        "ACFACHACIACKACLACMACNACOACPACQACRACSACTACUACWACXACYACbACcACeACfACgAChACjACkAClACmACpACqACrACtACuACwA"
        "CyACzAC0AC1AC2AC3AC4AC5AC6AC7AC9";
    inline constexpr const char* MetaKeysChunks[] = {MetaKeysChunk0};
    inline constexpr Packed MetaKeys{MetaKeysChunks, 13, 3};

    inline constexpr char MetaNamesChunk0[] =
        "AAAAUrAAAAAAAAAAAAAAAAUsAAAAAAAAAAAAAAAAUtAAAAAAAAAAAAAAAAUuAAAAAAAAAAAAAUvAUwAUxAAAAAAAAAAUyAUzAU0A"
        "AAAAAAAAAU1AU2AU3AAAAAAAAAAU4AU5AU6AAAAAAAAAAU7AU8AU9AAAAAAAAAAU+AU/AVAAAAAAAAAAAVBAVCAVDAAAAAAAAAAV"
        "EAVFAVGAAAAAAAAAAVHAVIAVJAAAAAAAAAAVKAVLAVMAAAAAAAAAAVNAVOAVPAAAAAAAAAAVQAVRAVSAAAAAAAAAAVTAVUAVVAAA"
        "AAAAAAAVWAVXAVYAAAAAAAAAAVZAVaAVbAAAAAAAAAAVcAVdAVeAAAAAAAAAAVfAVgAVhAAAAAAAAAAViAVjAVkAAAAAAAAAAVlA"
        "VmAVnAAAAAAAAAAVoAVpAVqAAAAAAAAAAAAAVrAAAAAAAAAAAAAAAAVsAAAAAAAAAAAAAVtAVuAVvAAAAAAAAAAAAAVwAAAAAAAA"
        "AAAAAVxAVyAVzAAAAAAAAAAAAAV0AAAAAAAAAAAAAV1AV2AV3AAAAAAAAAAV4AV5AV6AAAAAAAAAAV7AV8AV9AAAAAAAAAAAAAV+"
        "AAAAAAAAAAAAAAAAV/AAAAAAAAAAAAAWAAWBAWCAAAAAAAAAAWDAWEAWFAAAAAAAAAAWGAWHAWIAAAAAAAAAAAAAWJAAAAAAAAAA"
        "AAAAAAWKAAAAAAAAAAAAAAAAWLAAAAAAAAAAAAAWMAWNAWOAAAAAAAAAAAAAWPAAAAAAAAAAAAAWQAWRAWSAAAAAAAAAAWTAWUAW"
        "VAAAAAAAAAAAAAWWAAAAAAAAAAAAAWXAWYAWZAAAAAAAAAAWaAWbAWcAAAAAAAAAAWdAWeAWfAAAAAAAAAAAAAWgAAAAAAAAAAAA"
        "AAAAWhAAAAAAAAAAAAAAAAWoAAAAAAAAAAAAAAAAWiAAAAAAAAAAAAAAAAWjAAAAAAAAAAAAAWkAWlAWmAAAAAAAAAAAAAWnAAAA"
        "AAAAAAAAAWpAWqAWrAAAAAAAAAAWsAWtAWuAAAAAAAAAAAAAWvAAAAAAAAAAAAAAAAWwAAAAAAAAAAAAAWxAWyAWzAAAAAAAAAAW"
        "0AW1AW2AAAAAAAAAAW3AW4AW5AAAAAAAAAAAAAW6AAAAAAAW7AAAAAAAW8AAAAAAAAAAAAAAAAW9AAAAAAAAAAAAAAAAW+AAAAAA"
        "AAAAAAAAAAW/AAAAAAAAAAAAAAAAXAAAAAAAAAAAAAAXBAXCAXDAAAAAAAAAAXEAXFAXGAAAAAAAAAAXHAXIAXJAAAAAAAAAAXKA"
        "XLAXMAAAAAAAAAAAAAXNAAAAAAAAAAAAAAAAXOAAAAAAAAAAAAAAAAXPAAAAAAAAAAAAAXQAXRAXSAAAAAAAAAAAAAXTAAAAAAAA"
        "AAAAAXUAXVAXWAAAAAAAAAAAAAXXAAAAAAAAAAAAAAAAXYAAAAAAAAAAAAAXZAXaAXbAAAAAAAAAAXcAXdAXeAAAAAAAAAAAAAXf"
        "AAAAAAAAAAAAAAAAXgAAAAAAAAAAAAAAAAXhAAAAAAAAAAAAAAAAXiAAAAAAAAAAAAAXjAXkAXlAAAAAAAAAAAAAXmAAAAAAAAAA"
        "AAAXnAXoAXpAAAAAAAAAAXqAXrAXsAAAAAAAAAAXtAXuAXvAAAAAAAAAAAAAXwAAAAAAAAAAAAAAAAXxAAAAAAAAAAAAAAAAXyAA"
        "AAAAAAAAAAAXzAX0AX1AAAAAAAAAAX2AX3AX4AAAAAAAAAAX5AX6AX7AAAAAAAAAAAAAX8AAAAAAAAAAAAAX9AX+AX/AAAAAAAAA"
        "AYAAYBAYCAAAAAAAAAAYDAYEAYFAAAAAAAAAAYGAYHAYIAAAAAAAAAAYJAYKAYLAAAAAAAAAAAAAYMAAAAAAAAAAAAAAAAYNAAAA"
        "AAAAAAAAAYOAYPAYQAAAAAAAAAAYRAYSAYTAAAAAAAAAAYUAYVAYWAAAAAAAAAAAAAYXAAAAAAAAAAAAAYYAYZAYaAAAAAAAAAAA"
        "AAYbAAAAAAAAAAAAAAAAYcAAAAAAAAAAAAAAAAYdAAAAAAAAAAAAAAAAYeAAAAAAAAAAAAAAAAYfAAAAAAAAAAAAAYgAYhAYiAAA"
        "AAAAAAAYjAYkAYlAAAAAAAAAAAAAYmAAAAAAAAAAAAAAAAYnAAAAAAAAAAAAAAAAYoAAAAAAAAAAAAAAAAYpAAAAAAAAAAAAAAAA"
        "YqAAAAAAAAAAAAAAAAYrAAAAAAAAAAAAAAAAYsAAAAAAAAAAAAAYtAYuAYvAAAAAAAAAAAAAYwAAAAAAAAAAAAAAAAYxAAAAAAAA"
        "AAAAAYyAYzAY0AAAAAAAAAAAAAY1AAAAAAAAAAAAAY2AY3AY4AAAAAAAAAAAAAY5AAAAAAAAAAAAAY6AY7AY8AAAAAAAAAAY9AY+"
        "AY/AAAAAAAAAAZAAZBAZCAAAAAAAAAAAAAZDAAAAAAAAAAAAAZEAZFAZGAAAAAAAAAAZHAZIAZJAAAAAAAAAAAAAZKAAAAAAAAAA"
        "AAAAAAZLAAAAAAAAAAAAAAAAZMAAAAAAAAAAAAAZNAZOAZPAAAAAAAAAAZQAZRAZSAAAAAAAAAAAAAZTAAAAAAAAAAAA";
    inline constexpr const char* MetaNamesChunks[] = {MetaNamesChunk0};
    inline constexpr Packed MetaNames{MetaNamesChunks, 13, 3};

    inline constexpr uint16_t Formats[] = {
        1620, 1621, 1622, 1623, 1624, 1625, 0, 0, 0, 0, 0, 1626,
    };

    inline constexpr Table table{
        0x617300000000, 0,
        NameTexts,
        LanguageKeys, LanguageNames, 428,
        nullptr, Packed{}, 0,
        RegionKeys, RegionNames, 294,
        ScriptKeys, ScriptNames, 58,
        AloneKeys, AloneNames, 2,
        CurrencyKeys, CurrencyNames, 153,
        ZoneKeys, ZoneNames, 418,
        MetaKeys, MetaNames, 144,
        Formats,
    };

    // the table registered when the header is included, once a program
    inline Registration registration{&table};
}
