//------------------------------------------------------------------------------
// SGCL: a C++20 application platform
// Copyright (c) 2022-2026 Sebastian Nibisz
// SPDX-License-Identifier: Apache-2.0
//------------------------------------------------------------------------------
#pragma once
#include "detail/registry.h"

#include <cstdint>

// The display names of the locale bal-Latn (Balóchi (Látin)), CLDR 46.0: the names of languages,
// regions, scripts, currencies and time zones in it.
// Including this header is all a program does: txt::locale::display_name,
// region::display_name, script::display_name and currency::display_name then
// answer in this language. Generated by tools/cldr_tables.py: do not edit.
namespace sgcl::txt::detail::names::l_bal_Latn {
    inline constexpr char8_t NameChunk0[] =
        u8"AparAbkháziAprikáiAgemAkanAmhariAragóniObólóLatwiái ArabiArabiArabi (Donyá)MapucheAsámiAsuAsturiáiÁz"
        u8"erbáijániBashkarBalóchiBalóchi (Látin)BasáBélárusiBembáBetawiBenáBolgáriáiHaryánuiBalóchi (Róbarkati"
        u8")BójpuriAniTái DamBambaráBangáliTebbatiBrétónBodóBusniáiAkuseBlinKatálanKaddó-kadAtsamChakmáChechenC"
        u8"hebuánóChigáChoktawCherukiChekkásawMyáni KordiKorsikiChekSwampi KriCharch SláwiChuwashWéliDenmárkiTá"
        u8"itáJarmanZarmahDogriLáwar SorbiDuáláDiwéhiJólá-PóniDzongkáEmbóEweYunániEngréziEngrézi (Kaynadhá)Espe"
        u8"rántuEspiniEspini (Látini Amriká)Espini (Meksikó)EstóniáiBaskEwondóPársiPársi (AF)PuláFenlándiPelpin"
        u8"iParóeseParánsiParánsi (Kaynadhá)Kájon PránsiShemáli PrésiPriuliFerisi (Róbarkati)ÁeriGaaEskáti Géli"
        u8"GézGalékiGuáriánSwiz JarmanGojrátiGusiManksHausáHawáiEbrániHendiHendi (Látin Engrézi (Látin) Engrézi"
        u8" (Látin, Amrikáay Tepákén Están) syáhag: Látini)Hmang NjuáKróshiáiBorzi SorbiáiHangáriArminiáiMyánzo"
        u8"bániEndónésiMyánzobánIgbóSichuái YiIdóIslándiItáliáiInuktitutJápániLojbanNgombáMakamiJáwániJárjiáiKa"
        u8"ra-KalpakKabáileJjuKambáTyápMakondeKubuwerdiánóKinyangKáingángKoirá ChiniKikuyuKázákKákóKalállisutKa"
        u8"lenjinKhmérKannadáKuriáiKonkaniKpelleKashmiriShambaláBapiáKologniKordiKorneshKuwiKirgezLátiniLangiLo"
        u8"gzemborgiGandáLiguriLakótáLadinLombardLingáláLáóLuisiáná KrióleShemáli LoriLitwániáiLatgaliLubá-Kata"
        u8"ngáLuóLuiáLatwiáiMaitéliMasaiMokshaMéruMurisénMalagaseMakuá-MitóMétáMóchénóMuriMikmawMakduniMalyálam"
        u8"MangóliManipuriMohawkMaráthiMalaiMaltizMundangBáz zobánMuskógiBarmáiErziáMázendarániNamaNárwiji Bokm"
        u8"álShemáli NedébéleLáw JarmanLáw Jarman (NL)NépáliDacchDacch (Béljiam)KwásiuNárwiji NókénNgembunNárwi"
        u8"jiNkoZerbári NedebéliShemáli SotóNuérNawájóNyanjáNyankóleOsitiOromóOdiOsétiOságáPanjábiPápiámentóNái"
        u8"jiri PidginPijenPólayndiPrushiáiPashtóPortagáliKwichuKichiRájestániRóhengiáRipiRumanshRóndiRumániáiR"
        u8"umániái (MD)RombóRusiKenyarwandáRwaSanskeretYakutSamboróSantaliSanguSardéniáiSesiliáiSendiZerbári Ko"
        u8"rdiShemáli SámiSenáKoryáburó SenniSangóTachelhitShanSenháláSidámóSolwákSaráekiSolwiniáiZerbári SámiL"
        u8"ule SámiInári SámiEskált SámiShonáSómáliAlbániáiSarbiáiSwátiSahóZerbári SutóSudániSwidiSwáhéliSwáhél"
        u8"i (CD)SiriekSelisiTámelTelgóTésóTájekTáiTigriniáTigréTrkmTuswánáTonganTóki PónáTok PisinTorkTorokóTo"
        u8"rwáliTesungáTátarTasawakTuwiniTzmYughorYukriniNagisshetagén zobánUrduOzbekWáiWendáWenetiWietnámiMaku"
        u8"wáWolápukWunjóWallunWelserWolettáWarlpiriWolopKhusháKangriSugáYangbenYeddiYorobáNingátuKantóniZhuáng"
        u8"Gisshetqagén Moróki TamáziChiniZuluHecch zobánDonyáAfrikáShemáli AmrikáZerbári AmrikáUshiánáRónendi "
        u8"AprikáMyáni AmrikáRódarátki AprikáShemáli AprikáMyáni AprikáJonubi AprikáAmrikáShemáli AmrikaKerébia"
        u8"nRódarátki ÁsiáZerbári ÁsiáZerbárródarátki ÁsiáZerbári YuropÁstrálásiáMelanésiáMáekrónési DamagPólin"
        u8"isiáÁsiáMyáni ÁsiáRónendi ÁsiáYuropRódarátki YuropShemáli YuropRónendi YuropSab-Sahári AprikáLátini "
        u8"AmrikáAsenshan IslándAndorráEmárátAwghánestánAntiga o BarbudaAngwilaAlbániáÁrminiáAngóláAntárktikáAr"
        u8"jentináAmriki SamóáÁstriáÁsthréliáArubaÁwlánd IslándÁzerbáijánBósniáBarbadósBangaladéshBéljiamBurkin"
        u8"á PásóBalgáriáBahrenBorondiBeninSt. BartélémiBarmudáBrunáiBoliwiáKerébi NedarlándBrázilBahamasButhán"
        u8"Bówet IslándBostwánáBélárusBelizeKaynadháKukus Islánd (Kileng)Kángó-KenshásáMyáni Apriki EshtánKángó"
        u8"-BrázáwilleSwizarlándKóté diáwóriKuk IslándChilayKaymrunChinKólambiáKlipperton IslándSárkKóstá RikáK"
        u8"yubáKap WardéChurácháóKresmes IslándSáiprasChéchiáJarmaniDiégó GárshiáDjebutiDenmárkDuminikáDuminiki"
        u8" EstánAljiriáSiótó o MeliláEkwádórEstóniáMesrRóbarkati SaháráEritiriáEspinEtupiáYuropi YunianYurop-d"
        u8"amagFenlándFijiPáklánd IslándMikrónéshiáFaróé IslándParánsGabonBartániáGerenáJárjiáPránsi GwiánáGwer"
        u8"nsayGánáGibráltarGrinlándGambiáGiniáGwádelópEkwáturi GiniáYunánZerbári JárjiáGwátémáláGuámGiniá-Biss"
        u8"áuGoyánáHáng Káng o SAR ChinHard o Mekdónald IslándHondurasKróshiáHaytiHangariKanaray IslándEndhonés"
        u8"hiáÁerlándEsráilÁisale MardomHendostánBartáni Hendi ZerdamagErákÉránÁeslándItáliáJerséJamáekáOrdonJá"
        u8"pánKiniáKarghazestánKambódhiáKiribátiKomórósSt. Kitts o NewisShamáli KóriáZerbári KóriáKwaytKaymi Is"
        u8"lándKázakhestánLáusLebnánSt. LusiáLichtensténSari LankáLáibériáLesótóLituániáLoksembórgLatwiáLibyáMo"
        u8"rókóMonákóMoldowáMontenegróSt. MártinMadagáskarMarshall IslándShemáli MakduniáMáliMyanmár (Barmá)Man"
        u8"góliáMakaó SAR ChinShemáli Máriáná IslándMártinikMuritániáMontserratMáltáMurishiasMáldipMaláwiMeksik"
        u8"óMaléshiáMózambikNamibiáNiu KáledóniáNáigerNórfolk IslándNáijériáNekárágóáNedarlándNárwayNépálNáuruN"
        u8"iuéNyu ZilándOmánPánámáPéruParánsi PulinishiáPápuá Niu GiniáPelpinPákestánPólándSt. Péri o MikwélinP"
        u8"itkarén IslándPiuró RikóPalastinay DamagPortogálPaláuParágóayGatarTálánén ZerbahragRéyunianRumániáSa"
        u8"rbiáRusRwándháSaudi ArabSolomán IslándSéchelesSudánSwidhanSengápurSt. HelénáSlowiniáSwalbard o Jan M"
        u8"ayénSlowákiáSierrá LeóneSan MariánóSenigálSómáliáSurinaymZerbári SudánSáó Tóme o PrensipEl SalwadórS"
        u8"int MártenSuriáEswatiniTristan dá ChonháTork o Káikói IslándChádPránsi Zerbári DamagTógóTáilándTájek"
        u8"estánTokéláuTémur-LesteTorkmenestánTunishiáTongáTurkiyeTrinidad o TobágóTuwaluTáiwánTanzániáYukrénYu"
        u8"gandháU.S. Daráén IslándMyánostománi GalAmrikáay Tepákén EstánYurógóayOzbekestánWátikán SethiSt. Wen"
        u8"sent o GrenádinWenezwéláBretáni Ajgén IslándAmriki Ajgén IslándWietnámWanuátuWális o FutunáSamóáKesá"
        u8"si-GálwárKesási- BidiKósówóYamanMayotteZerbári AprikáZambiáZembábwéNagisshetagén damagAdlamKákáshi A"
        u8"lbániNastalikShahensháhi AramáiArmanAwestáiBáléniBámumBassa WahBatakBangBaykdukiBópóBrahmiBráiBugini"
        u8"BuhidChakmaKaynadhái Asligén SilábiCharianCheokiChorasmikoptekSáepró-MinóiSáepriótAhdi SerelekDéwáDi"
        u8"wes AkuruDograDeseretDuplui ShárthandMesri hiróglepsElbásiÉlimáiEtyupiGarayJárjGalgolitiGunjála Gónd"
        u8"iMasáram GóndiGótiGrantáYunGojrGurong KhémáGurukukiHán gón BópómópóáHangulHanHanunuHán (sádah kortag"
        u8"én)Hán (asligén)HatranHirágánáAnátólyái HéróglepsPahaw HmongNiákeng Puáche HamungJápáni SelibariAhdi"
        u8" HangariAhdi ItáliáiJamóJáwáKáyah LiKatakanáKáwiKaróshtiKójkiKitan gwandhén syáhagKóriáiKirat RaiKai"
        u8"tiLannáLáuPraktur LátinGéli LátinLátin Engrézi (Látin) Engrézi (Látin, Amrikáay Tepákén Están) syáha"
        u8"g: LátiniLepcháLimbuLayni ALayni BPrásarLisiáiLidiáiMahájaniMakasarMandáinManicháiMarchenMedepáidrin"
        u8"MendeMeriuti KarsiMeriutiMódiMongóliMróMiyeti MáyekMoltániMyanmárNag MundariNandinagariAhdi Shemáli "
        u8"ArabiNabatáiNewáNekóNushuOghámOl chekiOl OnalOrkhonÓdiáOséjOsmániaAhdi YógherPalmrénPáu Chen HáuAhdi"
        u8" PermiPags-paKondahi PahlawiPsáltar PahlawiPhónisiPólli TawáriKondahi PártiZawgiRejangHanipiRuniSamá"
        u8"riAhdi Zerbári ArabiSáuráshtriNeshánnebisiSháwiSharadáSeddamKodáwadiSenhaláSógdiáiAhdi SógdiáiSurá S"
        u8"ompengSoyombóSunuwarSiluti NagriEstrangló SiriekRónendi SiriekRódarátki SiriekTagbanwáTakriTái LéNók"
        u8"én Tái LéTangutTái WietTelegóTipinagTagalogTánaTebatiTirhutáTangsáTódriTótóTulu-TigálariYugaritiWitk"
        u8"ukiWarang KshitiWanchóAhdi PársiSumer-Akádi KyunipármYezidiYiZanabazar EskwáerEnheriHesábi NeshánEmó"
        u8"jiNeshánNebeshtah nabutagén syáhagHórénKódh nakortagén syáhagEmáráti DarhamEmáráti darhamAwgáni Awgá"
        u8"niAlbániái LekAlbániái lekÁrminiái DramÁrminiái dramAngólái KwanzáAngólái kwanzáArjentinái PaysóArje"
        u8"ntinái paysóÁstráliái DhálarÁstráliái dhálarArubi FlórinArubi flórinÁzerbáijáni ManatÁzerbáijáni man"
        u8"atBósniá-Herzigówinái Badali MarkBósniá-Herzigówinái badali markBarbadi DhálarBarbadi dhálarBangalad"
        u8"éshi ThakkáBangaladéshi thakkáBulgáriái LewBulgáriái lewBahreni DinárBahreni dinárBurundi FránkBurun"
        u8"di fránkBermudá DhálarBrunái DhálarBrunái dhálarBoliwiái BoliwiánóBoliwiái boliwiánóBrázili riálBaha"
        u8"mi DhálarBahami dhálarButháni NgultrumButháni ngultrumBotswánái PuláBotswánái puláBélárusi RubelBélá"
        u8"rusi rubelBelizé DhálarBelizé dhálarKaynadhái DhálarKaynadhái dhálarKángói FránkKángói fránkSwizi Fr"
        u8"ánkSwizi fránkChilayi PaysóChilayi paysóChini YuánChini yuánKolambiái PaysóKolambiái paysóKóstá Riká"
        u8"i KolónKyubái PaysóKyubái paysóKayp Werdi EskudóKayp Werdi eskudóChek KorunáChek korunáDjebuti Fránk"
        u8"Djebuti fránkDanmárki KoronDanmárki koronDominiki PaysóDominiki paysóAljiriái DinárAljiriái dinárMes"
        u8"ri PawndhMesri pawndhEritiriái NakfáEritiriái nakfáEtiupiái BirrEtiupiái birrYuróFiji DhálarFiji dhá"
        u8"larFálklánd Islándi PawndhFálklánd Islándi pawndhBartáni pawndhJárjiái LariJárjiái lariGánái SédiGán"
        u8"ái sédiGibraltar PawndhGibraltar pawndhGambiái DalasiGambiái dalasiGwiniái FránkGwiniái fránkGwátemá"
        u8"lái KwetzalGóyánái DhálarGóyánái dhálarHáng Káng DhálarHáng Káng dhálarHondurái LempiráHondurái lemp"
        u8"iráHaiti GurdeHaiti gurdeHungáriái ForintHungáriái forintEndhónishiái RupiáEndhónishiái rupiáEsráili"
        u8" Nókén ShekelEsráili nókén shekelHendostáni RupiEráki DinárEráki dinárÉráni RyálIsláni KrónáIsláni k"
        u8"rónáJamáiki DhálarJamáiki dhálarOrdoni DinárOrdoni dinárJápáni YenKinyái ShillingKinyái shillingKarg"
        u8"estáni SomKargestáni somKambódhiái RiélKambódhiái riélKomóriái ÉránkKomóriái fránkShemáli Kóriái Won"
        u8"Shemáli Kóriái wonZerbári Kóriái WonZerbári Kóriái wonKwayti DinárKwayti dinárKayman Islándi DhálarK"
        u8"ayman Islándi dhálarKázakestáni TengéKázakestáni tengéLaótiái KipLaótiái kipLebnáni PawndhLebnáni pa"
        u8"wndhSri Lankái RupiSri Lankái rupiLáibiriái DhálarLáibiriái dhálarLesótó LótiLesótó lótiLibyái Dinár"
        u8"Libyái dinárMórokói DarhamMórokói darhamMoldówi LeuMoldówi leuMalagasi AriáriMalagasi ariáriMakduniá"
        u8"i DinárMakduniái dinárMyanmár KyátMyanmár kyátMongóliái TugrikMongóliái tugrikMakani PatakáMakani pa"
        u8"takáMauritániái UgwiyáMauritániái ugwiyáMuritániái RupiMuritániái rupiMáldipi RupiyáMáldipi rupiyáMa"
        u8"lawi KwacháMalawi kwacháMeksikói PaysóMeksikói paysóMalishiái RinggitMalishiái ringgitMózambiki Meti"
        u8"kalMózambiki metikalNamibiái DhálarNamibiái dhálarNáijiriái NairáNáijiriái nairáNikárágóái KordobáNi"
        u8"kárágóái kordobáNárwéji KoronNárwéji koronNépáli RupiNépáli rupiNyu Zilánd DhálarNyu Zilánd dhálarOm"
        u8"áni RiálOmáni riálPanamániái BalbóáPanamániái balbóáPéruwi SólPéruwi sólPápuá Nyu Gwini KináPápuá Ny"
        u8"u Gwini kináPelpini PaysóPelpini paysóPákestáni RupiPólándi ZlótiPólándi zlótiPayráguyái GwaraniPayr"
        u8"águyái gwaraniGatari RiálGatari riálRumániái LeuRumániái leuSarbiái DinárSarbiái dinárRusi RubelRwán"
        u8"dái FránkRwándái fránkSaudi RiálSaudi riálSolomán Islánd DhálarSolomán Islánd dhálarSeychelli RupiSe"
        u8"ychelli rupiSudáni PawndhSudáni pawndhSwidi KoronSwidi koronSingápur DhálarSingápur dhálarSt. Heléná"
        u8"i PawndhSt. Helénái pawndhSiérá Leóni LeónSiérá Leóni leónSómáli ShillingSómáli shillingSurinami Dhá"
        u8"larSurinami dhálarZerbári Sudáni PawndhZerbári Sudáni pawndhSáó Tómé o Prensip DobráSáó Tómé o Prens"
        u8"ip dobráSuriái PawndhSuriái pawndhSwázi LilangeniSwázi lilangeniTái BahtTái bahtTájekestáni SomoniTá"
        u8"jekestáni somoniTRKMTorkmánestáni manatTunisi DinárTunisi dinárTongan PángáTongan pángáTorki LiráTor"
        u8"ki liráTrinidadi o Tobagó DhálarTrinidadi o Tobagó dhálarNyu Táiwán DhálarNyu Táiwán dhálarTanzániái"
        u8" ShillingTanzániái shillingYukrayni HriwniáYukrayni hriwniáYugandhái ShillingYugandhái shillingAmrik"
        u8"i dhálarYurógóyái PaysóYurógóyái paysóOzbekestáni SomOzbekestáni somWénezwélái BoliwarWénezwélái bol"
        u8"iwarWietnámi DongWietnámi dongWanuátu WátuWanuátu wátuSamóan TaláSamóan taláDelgáhi Aprikái CFA Frán"
        u8"kDelgáhi Aprikái CFA fránkRódarátki Karibiái DhálarRódarátki Karibiái dhálarRónendi Aprikái CFA Frán"
        u8"kRónendi Aprikái CFA fránkCFP FránkCFP fránkNazántagén ZarrYamani RiálYamani riálZerbári Aprikái Ran"
        u8"dZerbári Aprikái randZambiái KwacháZambiái kwacháHamdárén Jaháni wahdUTCNámálumén shahrDabaiKábolAnt"
        u8"iguáAnguilláTiráneYerewánLuandáSyówáDawisWostokKáséDumont UrwilaMendozáUshwáiáChatamarkáJojuiTukuman"
        u8"KortobaWiennáPertYukláAdilédMelbornSedhniMakwáerArubáBákuSarajéwóDhákaSofiáBujomburaPortó-NówóLá Paz"
        u8"IrunépéRió BrankóPortó welhóBóá WistáKwaibáChampo GrandeSáó PaulóPortalezáMachióRechipéNoronháThimpu"
        u8"GaboronéInuwikWankuwarDawson KrékKrestónSwift KarrantKambrej BayResólutAtikókanTorontóIkálwitMonkton"
        u8"HalifaksGlays BayBlanch-SablónKukusKenshásaLubumbáshiBrazzawilayZyurekhÁbedjánIstharSantiagóDouáláUr"
        u8"umkiShangáiHawánáChorácháóKresmesNikóshiáPamagustáPrágDjebótiKopenhágenDominikáSantó DomingóGwáyakil"
        u8"KáeróEl ÁiunAsmaráKanarayKyutáAddis AbabáStánléKósraiPayresLibrewilayLandanBartániái garmági wahdGre"
        u8"nadáTebilisiChayennGuernséyAkkráTuléIttokkorturmitDanmarkshawnKonakriMalábóÁtenShemáli JárjiáGuyánaH"
        u8"áng KángTeguchigalpáPórt-au-PrensBudápestJakártáJaypurÁeri anjári wahdUrshalimKalkataChagósBagdádTeh"
        u8"ránReykjawikRumJerséyAmmánTókyóNérubiKomóróPyongyángSeólKaymanAktauOrálAtirauAktubéKastanayKizilordá"
        u8"AlmatiWientiánéBérutWaduzKólambóMonrówiáMaséróWilniusLogzemborgTripóliKasablankáPodgorikáAntananariw"
        u8"óKopjéBamakóHówdUlánbátarMakáóMatinikNouakshottMurishasBlantirayTijuánaChiudad JuárezChihuahuáBahía "
        u8"de BanderásMonterrayMeksikó ShahrChanchunKwálá LampurMaputóWindoekNiaméyNurpolkLagósÓslóAwklándMaska"
        u8"tPanámáLimáMarkesásBógáinwilayKaráchiWársáMekwelonPitkarinPuertó RikóHebrónAzóresAsunchiónBukhárestB"
        u8"elgrádMáskóWolgogradSaratówUlyanówskKirówNowosibirskNowokuznetskWladiwóstokKhandigaSrednekólimskAnad"
        u8"irRyázGuadalkanalMahéKhartumEsthákholmSt. HelenáLjubljanáBratislawáPeritháónSan MarinóMógádéshóParam"
        u8"aribóJubáSáó ToméDamáskasMbabanéNdjamenáKargwelenLóméBengkákDoshambehFakaófóDehliTunesEstambólPórt E"
        u8"spinTáipiDár es salámSimperópólKampálaAnchoragéJuniuLás EnjelesPóeniksDenwérBeulah, Nárt DakótáNyu S"
        u8"alem, Nárt DakótáSanthar, Nárt DakótáShekágóMenominiWinsennes, IndiánáPetersburg, IndiánáTell Sithi,"
        u8" IndiánáKnoks, IndiánáWinamak, IndiánáMarengó IndiánáIndiánápolisLuiswillayWeway, IndiánáMontichelló"
        u8", KentukiNyu YárkMontewidióTáshkandWatikanSt. WinsentCharakásTortoláSt. TómasHó Chi MennEfátiApiáAda"
        u8"nMayótayJohannesbargLusákáHaráréSt. BarthélemySt. John’sChuukPohnpeiFaroeNuukSt. KittsYangonMéridaKa"
        u8"thmanduLower Prince’s QuarterKyivAwgánestánay wahdDelgáhi Aprikáay wahdRódarátki Aprikáay wahdRódará"
        u8"tki Aprikáay anjári wahdRónendi Aprikáay wahdRónendi Aprikáay anjári wahdRónendi Aprikáay garmági wa"
        u8"hdAláskáay wahdAláskáay anjári wahdAláskáay garmági wahdAmázónay wahdAmázónay anjári wahdAmázónay ga"
        u8"rmági wahdDelgáhi Amrikáay wahdDelgáhi Amrikáay anjári wahdDelgáhi Amrikáay garmági wahdRódarátki Am"
        u8"rikáay wahdRódarátki Amrikáay anjári wahdRódarátki Amrikáay garmági wahdKóhestagi Amrikáay wahdKóhes"
        u8"tagi Amrikáay anjári wahdKóhestagi Amrikáay garmági wahdÁrámzeri Amrikáay wahdÁrámzeri Amrikáay anjá"
        u8"ri wahdÁrámzeri Amrikáay garmági wahdApiáay wahdApiáay anjári wahdApiáay róchi wahdArabi wahdArabi a"
        u8"njári wahdArabi róchi wahdArjentináay wahdArjentináay anjári wahdArjentináay garmági wahdRónendi Arj"
        u8"entináay wahdRónendi Arjentináay anjári wahdRónendi Arjentináay gramági wahdÁrminiáay wahdÁrminiáay "
        u8"anjári wahdÁrminiáay garmági wahdAtlantáay wahdAtlantáay anjári wahdAtlantáay róchi wahdDelgáhi Ástr"
        u8"éliáay wahdDelgáhi Ástréliáay anjári wahdDelgáhi Ástréliáay garmági wahdDelgáhirónendi Ástréliáay wa"
        u8"hdDelgáhirónendi Ástréliáay anjári wahdDelgáhirónendi Ástréliáay garmági wahdRódarátki Ástréliáay wa"
        u8"hdRódarátki Ástréliáay anjári wahdRódarátki Ástréliáay garmági wahdRónendi Ástréliáay wahdRónendi Ás"
        u8"tréliáay anjári wahdRónendi Ástréliáay garmági wahdÁzerbáijánay wahdÁzerbáijánay anjári wahdÁzerbáij"
        u8"ánay garmági wahdAzóresay wahdAzóresay anjári wahdAzóresay garmági wahdBangaladéshay wahdBangaladésh"
        u8"ay anjári wahdBangaladéshay garmági wahdButhánay wahdBoliwiáay wahdBrázilay wahdBrázilay anjári wahd"
        u8"Brázilay garmági wahdBrunáiay wahdKap Wardéay wahdKap Wardéay anjári wahdKap Wardéay garmági wahdCha"
        u8"morróay wahdChatam wahdChatam anjári wahdChatam róchi wahdChilayay wahdChilayay anjári wahdChilayay "
        u8"garmági wahdChinay wahdChinay anjári wahdChinay róchi wahdKresmes Islánday wahdKukus Islánday wahdKo"
        u8"lambiáay wahdKolambiáay anjári wahdKolambiáay garmági wahdKuk Islánday wahdKuk Islánday anjári wahdK"
        u8"uk Islánday ném-garmági wahdKyubáay wahdKyubáay anjári wahdKyubáay róchay wahdDawisay wahdDumont Urw"
        u8"ilay wahdRódarátki Timuray wahdIsthar Islánday wahdIsthar Islánday anjári wahdIsthar Islánday garmág"
        u8"i wahdEkwádóray wahdDelgáhi Yuropay wahdDelgáhi Yuropay anjári wahdDelgáhi Yuropay garmági wahdRódar"
        u8"átki Yuropay wahdRódarátki Yuropay anjári wahdRódarátki Yuropay garmági wahdDémterén Ródarátki Yurop"
        u8"ay anjári wahdRónendi Yuropay wahdRónendi Yuropay anjári wahdRónendi Yuropay garmági wahdPalklánd Is"
        u8"lánday wahdPalklánd Islánday anjári wahdPalklánd Islánday garmági wahdFijiay wahdFijiay anjári wahdF"
        u8"ijiay garmági wahdParánsi Gwináay wahdZerbári Paransi o Antárktikáay wahdGalapagosay wahdGambiray wa"
        u8"hdJárjiáay wahdJárjiáay anjári wahdJárjiáay garmági wahdGelbart Islánday wahdGrinwech Min WahdRódará"
        u8"tki Grinlánday wahdRódarátki Grinlánday anjári wahdRódarátki Grinlánday garmági wahdRónendi Grinlánd"
        u8"ay wahdRónendi Grinlánday anjári wahdRónendi Grinlánd Garmági WahdKhalijay anjári wahdGuyánáay wahdH"
        u8"awái/Alushiay wahdHawái/Alushiay anjári wahdHawái/Alushiay garmági wahdHáng Kángay wahdHáng Kángay a"
        u8"njári wahdHáng Kángay garmági wahdHówday wahdHówday anjári wahdHówday garmági wahdHenday anjári wahd"
        u8"Hendi zeray wahdHendóchinay wahdDelgáhi Endhonishiáay anjári wahdRódarátki Endhonishiáay anjári wahd"
        u8"Rónendi Endhonishiáay anjári wahdÉránay wahdÉránay anjári wahdÉránay róchi wahdErkuskay wahdErkuskay"
        u8" anjári wahdErkuskay garmági wahdEsráilay wahdEsráilay anjári wahdEsráilay róchi wahdJápánay wahdJáp"
        u8"ánay anjári wahdJápánay róchi wahdKázakestánay wahdRódarátki Kázekestánay anjári wahdRónendi Kázekes"
        u8"tánay anjári wahdKóriáay wahdKóriáay anjári wahdKóriáay róchi wahdKósraiay wahdKrasnóyáskay wahdKras"
        u8"nóyáskay anjári wahdKrasnóyáskay garmági wahdKargezestánay wahdLiné Islánday wahdÁstréliáay, Ládhawa"
        u8"y wahdÁstréliáay, Ládhaway anjári wahdÁstréliáay, Ládhaway garmági wahdMágadánay wahdMágadánay anjár"
        u8"i wahdMágadánay garmági wahdMalishiáay wahdMáldipay wahdMarkésásay wahdMárshal Islánday wahdMuritáni"
        u8"áay wahdMuritániáay anjári wahdMuritániáay garmági wahdMawsonay wahdÁrámzeri Meksikóay wahdÁrámzeri "
        u8"Meksikóay anjári wahdÁrámzeri Meksikóay garmági wahdUlánbátaray wahdUlánbátaray anjári wahdUlánbátar"
        u8"ay garmági wahdMáskóay wahdMáskóay anjári wahdMáskóay garmági wahdMyanmáray wahdNauruay wahdNépálay "
        u8"wahdNyu Kaledóniáay wahdNyu Kaledóniáay anjári wahdNyu Kaledóniáay garmági wahdNiu Zilánday wahdNiu "
        u8"Zilánday anjári wahdNiu Zilánday róchi wahdNipándlaynday wahdNipándlaynday anjári wahdNipándlaynday "
        u8"garmági wahdNiuay wahdNurpolk Islánday wahdNurpolk Islánday anjári wahdNurpolk Islánday róchi wahdNo"
        u8"ronáay wahdNoronáay anjári wahdNoronáay garmági wahdNawásibiskay wahdNawásibiskay anjári wahdNawásib"
        u8"iskay garmági wahdÓmskay wahdÓmskay anjári wahdÓmskay garmági wahdPákestánay wahdPákestánay anjári w"
        u8"ahdPákestánay garmági wahdPaláuay wahdPápuá Niu Giniáay wahdParagóayay wahdParagóayay anjári wahdPar"
        u8"agóayay garmági wahdPéróay wahdPéróay anjári wahdPéróay garmági wahdPelpinay wahdPelpinay anjári wah"
        u8"dPelpinay garmági wahdPhoeneks Islánday wahdSt. Péri o Mikwélin wahdSt. Péri o Mikwélin ajári wahdSt"
        u8". Péri o Mikwélin róchi wahdPitkarénay wahdPónpiay wahdPyongyángay wahdRéyunianay wahdRothéráay wahd"
        u8"Sakhálinay wahdSakhálinay anjári wahdSakhálinay garmági wahdSamóáway wahdSamóáway anjári wahdSamóáwa"
        u8"y róchi wahdSéchelesay wahdSengápuray anjári wahdSolomán Islánday wahdZerbári Járjiáay wahdSurinayma"
        u8"y wahdSyówáay wahdTahitiay wahdTáipiay wahdTáipiay anjári wahdTáipiay róchi wahdTájekestánay wahdTok"
        u8"eláuay wahdTongáay wahdTongáay anjári wahdTongáay garmági wahdChukay wahdTorkmenestánay wahdTorkmene"
        u8"stánay anjári wahdTorkmenestánay garmági wahdTuwáluay wahdYurógóayay wahdYurógóayay anjári wahdYuróg"
        u8"óayay garmági wahdOzbekestánay wahdOzbekestánay anjári wahdOzbekestánay garmági wahdWánuátuay wahdWá"
        u8"nuátuay anjári wahdWánuátuay garmági wahdWenezwéláay wahdWaládiwástókay wahdWaládiwástókay anjári wa"
        u8"hdWaládiwástókay garmági wahdWolgograday wahdWolgograday anjári wahdWolgograday garmági wahdWostokay"
        u8" wahdWayk Islánday wahdWallis o Futunáay wahdYákuskay wahdYákuskay anjári wahdYákuskay garmági wahdY"
        u8"akátrinborgay wahdYakátrinborgay anjári wahdYakátrinborgay garmági wahdYukón wahd{0} ({1}){0}, {1}{0"
        u8"}{0} (+0){0} (+1){1} ({0}){0} {1}";
    inline constexpr const char8_t* NameChunks[] = {NameChunk0};
    inline constexpr uint16_t NameChunkSizes[] = {22032};
    inline constexpr char NameRefsChunk0[] =
        "AAAAAAAAAAAEAAAMAAAUAAAYAAAcAAAiAAAqAAAxAAA/AABEAABSAABZAABfAABiAABrAAB5AACAAACIAACZAACeAACoAACuAAC0"
        "AAC5AADEAADNAADiAADqAADtAAD1AAD9AAEFAAEMAAEUAAEZAAEhAAEmAAEqAAEyAAE8AAFBAAFIAAFPAAFZAAFfAAFmAAFtAAF3"
        "AAGDAAGKAAGOAAGYAAGlAAGsAAGxAAG6AAHBAAHHAAHNAAHSAAHeAAHlAAHsAAH4AAIAAAIFAAIIAAIPAAIXAAIrAAI1AAI7AAJT"
        "AAJkAAJuAAJyAAJ5AAJ/AAKKAAKPAAKYAAKfAAKnAAKvAALDAALRAALgAALmAAL5AAL+AAMBAAMOAAMSAAMZAAMiAAMtAAM1AAM5"
        "AAM+AANEAANKAANRAANWAAO1AAPAAAPKAAPYAAPgAAPpAAP1AAP/AAQKAAQPAAQaAAQeAAQmAAQvAAQ4AARAAARGAARNAARTAARb"
        "AARkAARvAAR3AAR6AASAAASFAASMAASaAAShAASrAAS3AAS9AATEAATKAATVAATdAATjAATrAATyAAT5AAT/AAUHAAUQAAUWAAUd"
        "AAUiAAUpAAUtAAUzAAU6AAU/AAVKAAVQAAVWAAVeAAVjAAVqAAVzAAV4AAWKAAWXAAWiAAWpAAW3AAW7AAXAAAXIAAXQAAXVAAXb"
        "AAXgAAXoAAXwAAX8AAYCAAYMAAYQAAYWAAYdAAYmAAYuAAY2AAY8AAZEAAZJAAZPAAZWAAZhAAZpAAZwAAZ2AAaDAAaHAAaXAAaq"
        "AAa1AAbFAAbNAAbSAAbiAAbpAAb5AAcAAAcIAAcLAAcdAAcrAAcwAAc4AAc/AAdIAAdNAAdTAAdWAAdcAAdjAAdrAAd4AAeHAAeM"
        "AAeVAAeeAAelAAevAAe1AAe6AAfFAAfPAAfTAAfaAAfgAAfqAAf5AAf/AAgDAAgPAAgSAAgbAAggAAgoAAgvAAg0AAg/AAhIAAhN"
        "AAhbAAhpAAhuAAh/AAiFAAiOAAiSAAibAAijAAiqAAiyAAi8AAjKAAjUAAjgAAjtAAjzAAj7AAkFAAkNAAkTAAkYAAkmAAktAAky"
        "AAk7AAlJAAlPAAlVAAlbAAlhAAlnAAltAAlxAAl6AAmAAAmEAAmNAAmTAAmfAAmoAAmsAAmzAAm7AAnDAAnJAAnQAAnWAAnZAAnf"
        "AAnmAAn7AAn/AAoEAAoIAAoOAAoUAAodAAokAAosAAoyAAo4AAo+AApGAApOAApTAApaAApgAAplAApsAApxAAp4AAqAAAqIAAqP"
        "AAqsAAqxAAq1AArBAArHAArOAAreAAruAAr3AAsHAAsVAAsoAAs4AAtGAAtUAAtbAAtqAAtzAAuFAAuUAAutAAu7AAvJAAvUAAvn"
        "AAvyAAv4AAwFAAwUAAwZAAwqAAw4AAxGAAxZAAxoAAx4AAyAAAyIAAyVAAylAAysAAy1AAy+AAzGAAzSAAzcAAzqAAzyAAz+AA0D"
        "AA0TAA0gAA0oAA0xAA09AA1FAA1UAA1eAA1kAA1rAA1wAA1/AA2HAA2OAA2WAA2oAA2vAA22AA29AA3LAA3VAA3eAA3kAA3tAA4D"
        "AA4VAA4qAA4+AA5JAA5ZAA5kAA5qAA5xAA51AA5/AA6RAA6WAA6jAA6pAA6zAA6/AA7OAA7WAA7fAA7mAA73AA7+AA8GAA8PAA8e"
        "AA8mAA83AA9AAA9JAA9NAA9gAA9pAA9uAA91AA+CAA+NAA+VAA+ZAA+qAA+4AA/HAA/OAA/TAA/dAA/kAA/sAA/8ABAEABAKABAU"
        "ABAdABAkABAqABA0ABBEABBKABBbABBoABBtABB7ABCDABCZABCyABC6ABDDABDIABDPABDeABDrABD0ABD7ABEJABETABEqABEv"
        "ABE1ABE+ABFGABFMABFVABFaABFhABFnABF0ABF/ABGIABGRABGiABGyABHCABHHABHUABHhABHmABHtABH3ABIDABIOABIZABIh"
        "ABIrABI2ABI9ABJDABJLABJTABJbABJmABJxABJ8ABKMABKeABKjABK0ABK+ABLNABLoABLxABL8ABMGABMNABMWABMdABMkABMs"
        "ABM2ABM/ABNHABNXABNeABNuABN5ABOGABOQABOXABOeABOkABOpABO0ABO5ABPCABPHABPbABPtABPzABP9ABQFABQaABQrABQ3"
        "ABRHABRQABRWABRgABRlABR5ABSCABSLABSSABSVABSeABSoABS4ABTBABTHABTOABTXABTjABTsABUBABULABUZABUmABUuABU4"
        "ABVAABVPABVkABVwABV8ABWCABWKABWdABW0ABW5ABXPABXVABXeABXqABXzABX/ABYMABYVABYbABYiABY1ABY7ABZDABZNABZU"
        "ABZdABZyABaEABaeABaoABazABbCABbZABbkABb7ABcQABcYABcgABcwABc3ABdHABdUABddABdiABdpABd5ABeAABeKABeeABej"
        "ABe0ABe8ABfQABfVABfdABflABfrABf0ABf5ABf9ABgFABgLABgRABgWABgcABghABgnABhCABhJABhPABhXABhdABhsABh2ABiC"
        "ABiIABiTABiYABifABiwABjAABjHABjPABjVABjaABjfABjoABj3ABkGABkLABkSABkVABkZABknABkvABlHABlNABlQABlWABlt"
        "ABl8ABmCABmNABmlABmwABnHABnYABnkABnyABn3ABn9ABoGABoPABoUABodABojABo6ABpCABpLABpQABpWABpaABpoABp0ABrL"
        "ABrSABrXABreABrlABrsABrzABr6ABsDABsKABsSABsbABsiABsuABszABtAABtHABtMABtUABtYABtlABttABt1ABuAABuLABue"
        "ABumABurABuwABu1ABu7ABvDABvKABvQABvWABvbABvjABvvABv3ABwFABwPABwWABwlABw1ABw9ABxLABxZABxeABxkABxqABxu"
        "ABx1AByIAByUAByhABynAByvABy1ABy+ABzGABzPABzdABzqABzyABz5AB0FAB0WAB0lAB03AB1AAB1FAB1NAB1dAB1jAB1sAB1z"
        "AB16AB2BAB2GAB2MAB2UAB2bAB2hAB2nAB21AB29AB3EAB3RAB3YAB3jAB36AB4AAB4CAB4UAB4aAB4pAB4vAB42AB5SAB5ZAB5y"
        "AB6CAB6SAB6hAB6vAB69AB7MAB7bAB7sAB79AB8PAB8hAB81AB9JAB9WAB9jAB93AB+LAB+uAB/RAB/gAB/vACAEACAZACAoACA3"
        "ACBFACBTACBhACBvACB/ACCOACCdACCyACDHACDVACDjACDxACECACETACEkACE1ACFFACFVACFkACFzACGFACGXACGmACG1ACHB"
        "ACHNACHbACHpACH0ACH/ACIQACIhACI2ACJEACJSACJkACJ2ACKCACKOACKcACKqACK5ACLIACLXACLmACL2ACMGACMSACMeACMv"
        "ACNAACNOACNcACNhACNtACN5ACOTACOtACO8ACPKACPYACPlACPyACQCACQSACQhACQwACQ/ACROACRjACR1ACSHACSaACStACS/"
        "ACTRACTcACTnACT5ACULACUgACU1ACVMACVjACVzACWAACWNACWaACWpACW4ACXIACXYACXlACXyACX+ACYOACYeACYtACY8ACZO"
        "ACZgACZyACaDACaYACatACbCACbXACbkACbxACcIACcfACczACdHACdUACdhACdwACd/ACePACefACeyACfFACfTACfhACfvACf9"
        "ACgNACgdACgpACg1AChFAChVAChmACh3ACiFACiTACilACi3ACjFACjTACjoACj9ACkOACkfACkvACk/AClNAClbAClrACl7ACmN"
        "ACmfACmxACnDACnUACnlACn3ACoJACogACo3ACpGACpVACpiACpvACqCACqVACqhACqtACrCACrXACrjACrvACsGACsdACsrACs5"
        "ACtJACtZACtpACt9ACuRACudACupACu3ACvFACvUACvjACvtACv9ACwNACwYACwjACw7ACxTACxhACxvACx9ACyLACyWACyhACyy"
        "ACzDACzXACzrACz/AC0TAC0kAC01AC1FAC1VAC1sAC2DAC2gAC29AC3LAC3ZAC3pAC35AC4CAC4LAC4fAC4zAC43AC5MAC5ZAC5m"
        "AC50AC6CAC6NAC6YAC6zAC7OAC7iAC72AC8KAC8eAC8vAC9AAC9TAC9mAC90AC+HAC+aAC+qAC+6AC/PAC/kAC/yADAAADAOADAc"
        "ADApADA2ADBSADBuADCLADCoADDEADDgADDqADD0ADEFADERADEdADEzADFJADFZADFpADGAADGDADGVADGaADGgADGoADGxADG4"
        "ADHAADHHADHOADHTADHZADHfADHsADH0ADH9ADIIADINADIUADIbADIiADImADIsADIzADI6ADJAADJIADJOADJTADJdADJjADJp"
        "ADJyADJ/ADKGADKPADKbADKoADK0ADK7ADLIADLUADLeADLlADLtADL1ADL7ADMEADMKADMSADMeADMmADMzADM+ADNGADNPADNX"
        "ADNfADNmADNuADN3ADOFADOKADOTADOeADOpADOwADO5ADO/ADPIADPQADPWADPeADPmADPyADP5ADQDADQNADQSADQaADQlADQu"
        "ADQ9ADRGADRNADRVADRcADRjADRpADR1ADR9ADSEADSKADSUADSaADSzADS7ADTDADTKADTTADTZADTeADTsADT4ADT/ADUHADUM"
        "ADUdADUkADUvADU8ADVKADVTADVcADViADV0ADV8ADWDADWKADWRADWYADWhADWkADWrADWxADW4ADW/ADXHADXRADXWADXcADXh"
        "ADXmADXsADXzADX7ADYFADYLADYWADYcADYhADYqADY0ADY8ADZDADZNADZVADZgADZqADZ3ADZ9ADaEADaJADaUADabADaiADas"
        "ADa0ADa9ADbFADbUADbeADbxADb6ADcIADcQADceADclADcsADczADc6ADdAADdGADdOADdUADdcADdhADdqADd3ADd/ADeGADeO"
        "ADeWADejADeqADexADe7ADfFADfNADfUADfdADflADfvADf1ADgAADgMADgYADggADguADg0ADg5ADhEADhJADhQADhbADhmADhw"
        "ADh7ADiGADiRADieADipADiuADi5ADjCADjKADjTADjcADjiADjqADjzADj8ADkBADkGADkPADkaADkgADkuADk6ADlCADlMADlR"
        "ADldADllADlsADmCADmbADmyADm7ADnDADnXADnsADoBADoRADojADo1ADpDADpNADpdADpyADp7ADqGADqPADqWADqhADqqADqy"
        "ADq8ADrIADrOADrTADrXADrfADrrADrzADr7ADsKADsWADsbADsiADsnADsrADs0ADs6ADtBADtKADtiADtmADt5ADuQADuqADvM"
        "ADvjADwCADwiADwxADxIADxgADxvADyGADyeADy1ADzUADz0AD0OAD0wAD1TAD1sAD2NAD2vAD3IAD3pAD4LAD4XAD4rAD4+AD5I"
        "AD5aAD5rAD58AD6VAD6vAD7JAD7rAD8OAD8eAD82AD9PAD9eAD91AD+LAD+mAD/JAD/tAEAQAEA7AEBnAECFAECrAEDSAEDtAEEQ"
        "AEE0AEFIAEFkAEGBAEGPAEGlAEG8AEHPAEHqAEIGAEIUAEIjAEIxAEJHAEJeAEJsAEJ9AEKWAEKwAELAAELLAELeAELwAEL9AEMS"
        "AEMoAEMzAENGAENYAENuAEOCAEOSAEOqAEPDAEPVAEPvAEQPAEQcAEQxAERGAERSAERlAER9AESSAESvAETNAETdAETyAEUPAEUt"
        "AEVFAEVlAEWGAEWxAEXGAEXjAEYBAEYZAEY5AEZaAEZlAEZ4AEaMAEaiAEbIAEbYAEblAEb0AEcLAEcjAEc5AEdKAEdmAEeKAEev"
        "AEfIAEfpAEgJAEgeAEgtAEhBAEhdAEh6AEiMAEimAEjBAEjNAEjhAEj2AEkJAEkZAEkqAElOAEl1AEmZAEmmAEm7AEnPAEncAEnx"
        "AEoHAEoVAEorAEpAAEpOAEpkAEp5AEqMAEqzAErXAErlAEr7AEsQAEseAEsxAEtMAEtoAEt7AEuPAEusAEvRAEv3AEwHAEwfAEw4"
        "AExIAExWAExnAEx+AEyQAEyqAEzFAEzSAEzsAE0OAE0xAE1DAE1dAE14AE2GAE2cAE2zAE3CAE3OAE3cAE3yAE4QAE4vAE5BAE5b"
        "AE50AE6HAE6iAE6+AE7IAE7eAE78AE8ZAE8nAE89AE9UAE9mAE+AAE+bAE+nAE+7AE/QAE/hAE/6AFAUAFAhAFA6AFBKAFBiAFB7"
        "AFCIAFCdAFCzAFDAAFDVAFDrAFECAFEcAFE9AFFeAFFuAFF7AFGMAFGcAFGsAFG8AFHUAFHtAFH8AFITAFIpAFI5AFJRAFJoAFKA"
        "AFKPAFKdAFKqAFK3AFLMAFLgAFLzAFMCAFMPAFMkAFM6AFNFAFNZAFN1AFOSAFOgAFOxAFPKAFPkAFP2AFQQAFQrAFQ7AFRTAFRs"
        "AFR+AFSUAFSyAFTRAFThAFT5AFUSAFUfAFUyAFVJAFVXAFVtAFWEAFWYAFW0AFXRAFXcAFXlAFXtAFXwAFX4AFYAAFYJAFYQ";
    inline constexpr const char* NameRefsChunks[] = {NameRefsChunk0};
    inline constexpr Packed NameRefs{NameRefsChunks, 13, 4};
    inline constexpr Text NameTexts{NameChunks, NameChunkSizes, NameRefs};

    inline constexpr char LanguageKeysChunk0[] =
        "AAhAAiAAmAArAAtAAuAAyAAzAA6ABBABFABHABNABOABPABSABTABhABlABvABzAB1AB2AB5ACBACFACWACaAClACsACuACvACzA"
        "C0AC1ADBADGADJADPADSADZADhADkADsADuAD1AD2AEBAEFAEJAESAEVAEZAEhAEkAElAEnAEpAEvAEzAE0AE1AFBAFWAFhAFpAF"
        "rAFsAFtAFuAFvAFzAF1AF3AF5AGBAGCAGHAGOAGPAGUAGVAGWAGnAGpAGrAGsAGuAGyAGzAG0AG5AHCAHEAHFAHMAHOAHPAHSAHW"
        "AHZAHjAHtAHyAHzAIBAIMAITAIUAI1AJNAJOAJPAJVAJXAJhAJjAJkAJlAJnAJpAJrAJsAJuAJvAJxAJyAJzAJ0AJ1AJ2AJ3AKBA"
        "KFAKHAKIAKJAKLAKOAKPAKSAKTAKUAKnAKrAKyAK6ALFALJALPALhALvAMIAMpAMvANBANIANVATxAXOAYDAZOAZhAZ0AgsAgzAi"
        "tAi3Ai6AjjAjuAkPAmPAmUApYApzAsuAwkAxoAxwAyiAznA0PA0SA0jA1iA53BA2BFFBHpBJiBKhBMvBRVBbvBksBpDBpSBqyBwh"
        "By6B53B66CA3CHKCJiChPCjvCmjCwhCwiCwqCwtCxnCyFCyhCyuCzwC0RC1qC2OC3rC4FC5iC5mC5oC8WDAnDEqDF0DGEDGvDH1D"
        "JDDKHDKvDK5DQpDQzDSGDSyDTFDToDTvDUODUjDXJDXoDahDasDazDc2DdODgxDiTDmnDnIDovDpvDqzDsuD5hEAwEBtEEzEJHEa"
        "jEgqEkHEkmEnmErrEwoEwxEw0ExQExuEyIEyoEyzE0JE0OE0kE1yE2hE2qE2uE2zE55E8yE9MFCvFEnFHrFIJFJWFJXFLxFM2FNN"
        "FXEFgpFijFm3FquFwlFwsFxQGHSGHnGQ2GZMGalGjoGsY";
    inline constexpr const char* LanguageKeysChunks[] = {LanguageKeysChunk0};
    inline constexpr Packed LanguageKeys{LanguageKeysChunks, 13, 3};

    inline constexpr char LanguageNamesChunk0[] =
        "AABAACAADAAFAAGAAHAAKAANAAQAARAAVAAZAAfAAgAAhAAiAAkAAnAArAAyAAzAA1AA2AA3AA4AA6AA/ABBABDABEABFABHABIA"
        "BLABMABOABQABRABTABUABZABaABcABeABfABhABjABkABmABnABqABsABtABuABvABwABxAByABzAB0AB1AB2AB3AB7AB8ACHAC"
        "IACKACMACNACOACRACVACWACYACZACbACcAChACiAClACnACqACwAC0AC2AC3AC4AC7AC8AC9ADBADFADGADJADKADNADPADRADU"
        "ADVADXADYADZADaADcADgADiADjADkADpADqADrADuADvADxAD2AD4AD6AD9AEAAECAEEAEJAEKAELAEMAENAEPAEQAERAESAEWA"
        "EXAEZAEaAEbAEdAEeAEfAEiAElAEmAEqAErAEtAEuAEwAEyAE0AE2AE6AE7AE/AFAAFDAFFAFGAAEAAIAAJAAMAAOAAPAASAAUAA"
        "WAAXAAYAAaAAbAAcAAdAAeAAjAAlAAmAAoAApAAqAAsAAtAAuAAvAAwAAxAA0AA5AA7AA8AA9AA+ABAABCABNABSABWABXABYABb"
        "ABdABgABiABlABpABrAB4AB5AB6AB9AB+AB/ACAACBACCACDACEACFACGACJACLACPACQACSACTACUACXACaACdACeACfACgACjA"
        "CkACmACoACpACrACsACtACuACvACxACyACzAC1AC5AC6AC+AC/ADAADCADDADEADHADMADOADQADSADTADWADbADdADeADfADhAD"
        "lADmADnADoADtADwADyADzAD0AD1AD3AD5AD7AD8AD+AD/AEBAEDAEFAEGAEHAEIAEOAEUAEVAEYAEcAEgAEhAEjAEkAEnAEoAEp"
        "AEsAEvAExAEzAE1AE3AE4AE5AE8AE9AE+AFBAFCAFEAFH";
    inline constexpr const char* LanguageNamesChunks[] = {LanguageNamesChunk0};
    inline constexpr Packed LanguageNames{LanguageNamesChunks, 13, 3};

    inline constexpr const uint64_t* TaggedKeys = nullptr;

    inline constexpr const uint16_t* TaggedNames = nullptr;

    inline constexpr char RegionKeysChunk0[] =
        "AAeAAfAAgAAhAAiAAkAAnAAoAAqAAsAAtAAuAAvAAwAAyAAzAA1AA3AA4AA6AA7AA8AA9AA+AA/ABAABCABDABEABFABHABIABJA"
        "BKABMABNABPABQABSABUABVABXABYABZABaABcABdABeABfABgABhABiABjABmABnABoABpABqABrABxABzAB2AB3AB5AB7ACGAC"
        "IACKACMACOACPACZACaACbACcAChACrACsACtACvACxAC0AC+AC/ADBADCADDADEADFADGADJADKADLADNADOADPADQADRADSADU"
        "ADWADjADlADmADqADsADtAD2AD3AD4AD/AEAAEBAECAEEAEFAEGAEHAETAEbAEdAEeAEuAEwAExAEyAE2AE3AE5AE7AFAAFCAFDA"
        "FFAFGAFHAFNAFPAFWAFXAFYAFZAFaAFdAFgAFiAFjAFkAFlAFmAFnAFqAFrAFsAFtAFuAFvAFwAFxAFyAFzAF0AF1AF2AF3AF4AF"
        "5AF7AF9AF/AGAAGBAGDAGGAGJAGKAGMAGPAGUAGiAGxAG1AG2AG3AG4AG7AG8AG9AG+AHCAHDAHEAHHAHJAHMAHaAHrAH1AH5AH7"
        "AH9AICAIDAIEAIFAIGAIIAIJAIKAILAIMAINAIOAIPAIQAITAIUAIVAIXAIZAIaAIbAIdAIfAIgAIiAIjAIkAImAInAIoAIpAIqA"
        "IrAIuAIwAIyAIzAI2AI4AI+AJEAJFAJKAJQAJRAJTAJVAJXAJZAJbAJgAJnAJzAKAAKJAKKAKTAKoAK3AK/ALLALVALYALaALbAL"
        "cALeALiALkALmALnALoALqALrALsALuAL2AL3AL7AL8AMAAMOAMPAMSAMWANnANoANqANvANwANzAN0AOjAR8";
    inline constexpr const char* RegionKeysChunks[] = {RegionKeysChunk0};
    inline constexpr Packed RegionKeys{RegionKeysChunks, 13, 3};

    inline constexpr char RegionNamesChunk0[] =
        "AFnAFoAFpAFqAFrAFsAFtAFuAFvAFwAFxAFyAFzAF0AF1AF2AF3AF4AF5AF6AF7AF8AF9AF+AF/AGAAGBAGCAGDAGEAGFAGGAGHA"
        "GIAGJAGKAGLAGMAGNAGOAGPAGQAGRAGSAGTAGUAGVAGWAGXAGYAGZAGaAGbAGcAGdAGeAGfAGgAGhAGiAGjAGkAGlAGmAGnAGoAG"
        "pAGqAGrAGsAGtAGuAGvAGwAGxAGyAGzAG0AG1AG2AG3AG4AG5AG6AG7AG8AG9AG+AG/AHAAHBAHCAHDAHEAHFAHGAHHAHIAHJAHK"
        "AHLAHMAHNAHOAHPAHQAHRAHSAHTAHUAHVAHWAHXAHYAHZAHaAHbAHcAHdAHeAHfAHgAHhAHiAHjAHkAHlAHmAHnAHoAHpAHqAHrA"
        "HsAHtAHuAHvAHwAHxAHyAHzAH0AH1AH2AH3AH4AH5AH6AH7AH8AH9AH+AH/AIAAIBAICAIDAIEAIFAIGAIHAIIAIJAIKAILAIMAI"
        "NAIOAIPAIQAIRAISAITAIUAIVAIWAIXAIYAIZAIaAIbAIcAIdAIeAIfAIgAIhAIiAIjAIkAIlAImAInAIoAIpAIqAIrAIsAItAIu"
        "AIvAIwAIxAIyAIzAI0AI1AI2AI3AI4AI5AI6AI7AI8AI9AI+AI/AJAAJBAJCAJDAJEAJFAJGAJHAJIAJJAJKAJLAJMAJNAJOAJPA"
        "JQAJRAJSAJTAJUAJVAJWAJXAJYAJZAJaAJbAJcAJdAJeAJfAJgAJhAJiAJjAJkAJlAJmAJnAJoAJpAJqAJrAJsAJtAJuAFIAFJAF"
        "KAFLAFMAFNAFOAFPAFQAFRAFSAFTAFUAFVAFWAFXAFYAFZAFaAFbAFcAFdAFeAFfAFgAFhAFiAFjAFkAFlAFm";
    inline constexpr const char* RegionNamesChunks[] = {RegionNamesChunk0};
    inline constexpr Packed RegionNames{RegionNamesChunks, 13, 3};

    inline constexpr char ScriptKeysChunk0[] =
        "AJGNAJ0CAMgiAMguAMmpAMmuANp0AQWJAQW1AQZzAQaLARXHASFzAT4PAUgoAUgpAVTpAVUEAYVtAYXTAYZJAaCyAaJTAb4UAcGu"
        "AcJUAeZMAeZTAhbBAiQrAjzyAk5UAlYMAp8wArBBArMtAtEJA4ZBA5XyA7AnA73HA73NA76IA8guA8irA9VSA9VoA9ZVBAXCBAXH"
        "BAXJBAXPBAXTBAXUBAaSBBRSBCZBBDK3BDXHBDXQBEl0BFXHBNAsBQWvBQbBBUAuBYWJBYXBBYbpBaAyBaGyBaHqBaaTBbiBBb5F"
        "BcgpBdEJBgXBBgXvBgaGBgaHBgaOBhYDBiWiBiXBBiXCBiZ1BmRpBmSJBoUKBoVhBoXEBoXJBoZDBpSGBpXEBpZDBpZPBrMtBryJ"
        "Br3HBsnvBtCpBtWUBuWyBwTtBwXEBwZCBwg0BxbhBy3vB00VB5wtB7BrB7gvB8loB8shB8zlB82hB9TyCAWNCAajCBZNCCAnCCGJ"
        "CCGQCCHYCDJECEqJCIQnCSnHCT0HCVXSCYWyCYZCCYayCZ3XCaA3CaJECaSECaXECaXICbzkCbzvCb5BCb8vCdXECdXVCeWPCeZD"
        "CeZFCeZKCeZOCgTiCgVyCgWFCgWVCgWsCgXHCgbUChWVChnHCh2HCiAhCiApCiRUCiZICjphCjySCj6PClaHCpwyCwUpCyaIC4ZB"
        "C40PDECvDE64DJdJDKUpDQXCDSXIDTaIDU8lDU8tDWMYDWc5DWta";
    inline constexpr const char* ScriptKeysChunks[] = {ScriptKeysChunk0};
    inline constexpr Packed ScriptKeys{ScriptKeysChunks, 13, 4};

    inline constexpr char ScriptNamesChunk0[] =
        "AJvAJwAAKAJxAJyAJzAJ0AJ1AJ2AJ3AJ4AJ5AJ6AJ7AJ8AJ9AJ+AJ/AKAAKBAKCAKDAKEAKFAKGAKHADuAKIAKJAKKAKLAKMAKNA"
        "KOAKPAKQAKRAKSAKTAKUAKVAKWAKXAKYAKZAKaAKbAKcAKdAKeAKfAKgAKhAKiAKjABmAKkAKlAKmAKnAKoAKpAKqAKrAKsAB3AK"
        "tAKuAKvAKwACMAKxAKyACNAKzAK0AK1AK2AK3AK4AK5AK6AK7AK8AK9AK+AK/ALAALBALCALDALEALFALGALHALIALJALKAC3ALL"
        "ALMALNALOALPALQALRALSALTALUALVALWALXALYALZALaALbALcALdALeALfALgALhALiALjALkALlALmALnALoALpALqALrALsA"
        "LtALuALvALwALxALyALzAL0AL1AL2AL3AL4AL5AEQAL6AL7AEUAL8AL9AL+AL/AMAAMBAMCAEWAMDAMEAMFAMGAMHAMIAEaAMJAM"
        "KAMLAMMAMNAMOAMPAEvAMQAMRAMSAMTAMUAMVAMWAMXAMYAMZAMaAMbAMcAMdAMe";
    inline constexpr const char* ScriptNamesChunks[] = {ScriptNamesChunk0};
    inline constexpr Packed ScriptNames{ScriptNamesChunks, 13, 3};

    inline constexpr const uint32_t* AloneKeys = nullptr;

    inline constexpr const uint16_t* AloneNames = nullptr;

    inline constexpr char CurrencyKeysChunk0[] =
        "ASkATOAWMAWkAXhAZTAakAbnAdOAgtAhEAiUAjuAkEAkmAmkAnEAniApMApkAqOArwAsuAtEAwkAyGA0GA2QA3ZA3wA5DA6wA7FA"
        "9LBFGBFrBHwBNEBTwBZOBaCBayBlEBlwBxQBysB0TB0wB2kB3GB6RB8kCFkCHMCKHCKmCSSCWTCXSCYkCZSCZrCmkCnkCoZCyzCz"
        "zC0SC2mC4XC5XC7kC8kC9UDArDBQDFyDJEDJsDMkDQkDSMDThDVkDWrDXUDXwDZVDayDbSDbrDcODcyDdODgkDjuDkvDnrDoSDtE"
        "D2yEAiECuEDrEEQEFyEGOEMnEQyEnuEpkEqiErmEwyExEExyEyHEyrEzkE0QE2FE3zE5EE5wE6OE8wE9MFECFFTFG0FHEFHwFJZF"
        "KEFLkFNTFQoFT4FZkFc1FdTFizFnEFq2F50GAmGBkGHmGIGGMYGSyGgyGm3";
    inline constexpr const char* CurrencyKeysChunks[] = {CurrencyKeysChunk0};
    inline constexpr Packed CurrencyKeys{CurrencyKeysChunks, 13, 3};

    inline constexpr char CurrencyNamesChunk0[] =
        "AMfAAAAMgAAAAAAAAAAMgAMhAAAAMhAAAAAAAAAAMhAMiAAAAMjAAAAAAAAAAMjAMkAAAAMlAAAAAAAAAAMlAMmAAAAMnAAAAAAA"
        "AAAMnAMoAAAAMpAAAAAAAAAAMpAMqAAAAMrAAAAAAAAAAMrAMsAAAAMtAAAAAAAAAAMtAMuAAAAMvAAAAAAAAAAMvAMwAAAAMxAA"
        "AAAAAAAAMxAMyAAAAMzAAAAAAAAAAMzAM0AAAAM1AAAAAAAAAAM1AM2AAAAM3AAAAAAAAAAM3AM4AAAAM5AAAAAAAAAAM5AM6AAA"
        "AM7AAAAAAAAAAM7AM8AAAAM8AAAAAAAAAAM8AM9AAAAM+AAAAAAAAAAM+AM/AAAANAAAAAAAAAAANAANBAAAAAAAAAAAAAAAAAAA"
        "NCAAAANDAAAAAAAAAANDANEAAAANFAAAAAAAAAANFANGAAAANHAAAAAAAAAANHANIAAAANJAAAAAAAAAANJANKAAAANLAAAAAAAA"
        "AANLANMAAAANNAAAAAAAAAANNANOAAAANPAAAAAAAAAANPANQAAAANRAAAAAAAAAANRANSAAAANTAAAAAAAAAANTANUAAAANVAAA"
        "AAAAAAANVANWAAAANXAAAAAAAAAANXANYAAAANYAAAAAAAAAANYANZAAAANaAAAAAAAAAANaANbAAAANcAAAAAAAAAANcANdAAAA"
        "NeAAAAAAAAAANeANfAAAANgAAAAAAAAAANgANhAAAANiAAAAAAAAAANiANjAAAANkAAAAAAAAAANkANlAAAANmAAAAAAAAAANmAN"
        "nAAAANoAAAAAAAAAANoANpAAAANqAAAAAAAAAANqANrAAAANsAAAAAAAAAANsANtAAAAAAAAAAAAAAAAAAANuAAAANvAAAAAAAAA"
        "ANvANwAAAANxAAAAAAAAAANxANyAAAAAAAAAAAAAAAAAAANzAAAAN0AAAAAAAAAAN0AN1AAAAN2AAAAAAAAAAN2AN3AAAAN4AAAA"
        "AAAAAAN4AN5AAAAN6AAAAAAAAAAN6AN7AAAAN8AAAAAAAAAAN8AN9AAAAN9AAAAAAAAAAN9AN+AAAAN/AAAAAAAAAAN/AOAAAAAO"
        "BAAAAAAAAAAOBAOCAAAAODAAAAAAAAAAODAOEAAAAOFAAAAAAAAAAOFAOGAAAAOHAAAAAAAAAAOHAOIAAAAOJAAAAAAAAAAOJAOK"
        "AAAAOLAAAAAAAAAAOLAOMAAAAAAAAAAAAAAAAAAAONAAAAOOAAAAAAAAAAOOAOPAAAAAAAAAAAAAAAAAAAOQAAAAORAAAAAAAAAA"
        "ORAOSAAAAOTAAAAAAAAAAOTAOUAAAAOVAAAAAAAAAAOVAOWAAAAAAAAAAAAAAAAAAAOXAAAAOYAAAAAAAAAAOYAOZAAAAOaAAAAA"
        "AAAAAOaAObAAAAOcAAAAAAAAAAOcAOdAAAAOeAAAAAAAAAAOeAOfAAAAOgAAAAAAAAAAOgAOhAAAAOiAAAAAAAAAAOiAOjAAAAOk"
        "AAAAAAAAAAOkAOlAAAAOmAAAAAAAAAAOmAOnAAAAOoAAAAAAAAAAOoAOpAAAAOqAAAAAAAAAAOqAOrAAAAOsAAAAAAAAAAOsAOtA"
        "AAAOuAAAAAAAAAAOuAOvAAAAOwAAAAAAAAAAOwAOxAAAAOyAAAAAAAAAAOyAOzAAAAO0AAAAAAAAAAO0AO1AAAAO2AAAAAAAAAAO"
        "2AO3AAAAO4AAAAAAAAAAO4AO5AAAAO6AAAAAAAAAAO6AO7AAAAO8AAAAAAAAAAO8AO9AAAAO+AAAAAAAAAAO+AO/AAAAPAAAAAAA"
        "AAAAPAAPBAAAAPCAAAAAAAAAAPCAPDAAAAPEAAAAAAAAAAPEAPFAAAAPGAAAAAAAAAAPGAPHAAAAPIAAAAAAAAAAPIAPJAAAAPKA"
        "AAAAAAAAAPKAPLAAAAPMAAAAAAAAAAPMAPNAAAAPOAAAAAAAAAAPOAPPAAAAPQAAAAAAAAAAPQAPRAAAAPSAAAAAAAAAAPSAPTAA"
        "AAPUAAAAAAAAAAPUAPVAAAAPWAAAAAAAAAAPWAPXAAAAPYAAAAAAAAAAPYAPZAAAAPaAAAAAAAAAAPaAPbAAAAPcAAAAAAAAAAPc"
        "APdAAAAPeAAAAAAAAAAPeAPfAAAAPgAAAAAAAAAAPgAPhAAAAPiAAAAAAAAAAPiAPjAAAAPkAAAAAAAAAAPkAPlAAAAPmAAAAAAA"
        "AAAPmAPnAAAAAAAAAAAAAAAAAAAPoAAAAPpAAAAAAAAAAPpAPqAAAAPrAAAAAAAAAAPrAPsAAAAPtAAAAAAAAAAPtAPuAAAAPvAA"
        "AAAAAAAAPvAPwAAAAPxAAAAAAAAAAPxAPyAAAAAAAAAAAAAAAAAAAPzAAAAP0AAAAAAAAAAP0AP1AAAAP2AAAAAAAAAAP2AP3AAA"
        "AP4AAAAAAAAAAP4AP5AAAAP6AAAAAAAAAAP6AP7AAAAP8AAAAAAAAAAP8AP9AAAAP+AAAAAAAAAAP+AP/AAAAQAAAAAAAAAAAQAA"
        "QBAAAAQCAAAAAAAAAAQCAQDAAAAQEAAAAAAAAAAQEAQFAAAAQGAAAAAAAAAAQGAQHAAAAQIAAAAAAAAAAQIAQJAAAAQKAAAAAAAA"
        "AAQKAQLAAAAQMAAAAAAAAAAQMAQNAAAAQOAAAAAAAAAAQOAQPAAAAQQAAAAAAAAAAQQAQRAAAAQSAAAAAAAAAAQSAQTAAAAQUAAA"
        "AAAAAAAQUAQVAAAAQWAAAAAAAAAAQWAQXAAAAQYAAAAAAAAAAQYAQZAAAAQaAAAAAAAAAAQaAQbAAAAQcAAAAAAAAAAQcAQdAAAA"
        "QeAAAAAAAAAAQeAQfAAAAQgAAAAAAAAAAQgAQhAAAAQiAAAAAAAAAAQiAQjAAAAQkAAAAAAAAAAQkAQlAAAAQmAAAAAAAAAAQmAQ"
        "nAAAAAAAAAAAAAAAAAAAQoAAAAQpAAAAAAAAAAQpAQqAAAAQrAAAAAAAAAAQrAQsAAAAQtAAAAAAAAAAQtAQuAAAAQvAAAAAAAAA"
        "AQvAQwAAAAQxAAAAAAAAAAQxAQyAAAAQzAAAAAAAAAAQzAQ0AAAAQ1AAAAAAAAAAQ1AQ2AAAAQ3AAAAAAAAAAQ3AQ4AAAAQ5AAAA"
        "AAAAAAQ5AQ6AAAAQ7AAAAAAAAAAQ7AQ8AAAAAAAAAAAAAAAAAAAQ9AAAAQ+AAAAAAAAAAQ+AQ/AAAARAAAAAAAAAAARAARBAAAAR"
        "CAAAAAAAAAARC";
    inline constexpr const char* CurrencyNamesChunks[] = {CurrencyNamesChunk0};
    inline constexpr Packed CurrencyNames{CurrencyNamesChunks, 13, 3};

    inline constexpr char ZoneKeysChunk0[] =
        "AAAAABAACAAEAAFAAJAAKAALAAMAANAAOAAPAARAASAATAAUAAVAAWAAXAAYAAZAAaAAbAAdAAeAAfAAgAAhAAiAAjAAkAAlAAmA"
        "AnAAoAApAAqAArAAsAAtAAvAAwAAxAAyAAzAA1AA2AA3AA+AA/ABAABBABDABHABIABMABNABOABPABQABRABSABTABUABVABWAB"
        "XABYABZABaABbABcABeABfABhABjABkABmABnABoABrABsABtABuABvABwABxABzAB0AB1AB2AB3AB4AB5AB6AB7AB8AB9AB+AB/"
        "ACAACCACDACEACFACGACHACLACOACPACQACSACTACUACVACWACZACbACcACdACeACgAChACiACjACkAClACmACpACrACsACuACvA"
        "CwACxACzAC0AC1AC2AC3AC4AC5AC6AC7AC8AC9AC+AC/ADDADEADFADGADLADNADPADQADRADSADTADUADWADXADYADZADaADcAD"
        "eADfADhADiADjADkADlADmADnADpADqADrADtADuADvADwADyADzAD0AD2AD4AD5AD9AD+AD/AEAAECAEFAEGAEHAEIAEJAEKAEL"
        "AEOAEPAEQAERAESAETAEUAEVAEWAEXAEZAEaAEcAEdAEgAEhAEjAEkAElAEnAEoAEpAEqAErAEvAEzAE0AE1AFRAFSAFWAFXAFZA"
        "FbAFcAFfAFgAFiAFlAFmAFoAFpAFrAFsAFtAFyAFzAF0AF1AF2AF3AF5AF7AF8AF9AF+AF/AGAAGBAGDAGEAGFAGGAGHAGIAGJAG"
        "KAGMAGNAGOAGPAGQAGRAGSAGTAGUAGVAGWAGXAGYAGZAGaAGcAGdAGfAGkAGoAGrAGvAGzAG0AG7";
    inline constexpr const char* ZoneKeysChunks[] = {ZoneKeysChunk0};
    inline constexpr Packed ZoneKeys{ZoneKeysChunks, 13, 3};

    inline constexpr char ZoneNamesChunk0[] =
        "ASHAAAAAAAAAAAAAAAAAAASoAAAAAAAAAAAAAAAAAAASdAAAAAAAAAAAAAAAAAAASaAAAAAAAAAAAAAAAAAAATbAAAAAAAAAAAAA"
        "AAAAAATiAAAAAAAAAAAAAAAAAAASFAAAAAAAAAAAAAAAAAAARkAAAAAAAAAAAAAAAAAAASYAAAAAAAAAAAAAAAAAAATXAAAAAAAA"
        "AAAAAAAAAAAScAAAAAAAAAAAAAAAAAAASsAAAAAAAAAAAAAAAAAAAUnAAAAAAAAAAAAAAAAAAASTAAAAAAAAAAAAAAAAAAASKAAA"
        "AAAAAAAAAAAAAAAASZAAAAAAAAAAAAAAAAAAAUUAAAAAAAAAAAAAAAAAAARzAAAAAAAAAAAAAAAAAAAVNAAAAAAAAAAAAAAAAAAA"
        "VLAAAAAAAAAAAAAAAAAAAUYAAAAAAAAAAAAAAAAAAAUpAAAAAAAAAAAAAAAAAAAUPAAAAAAAAAAAAAAAAAAASDAAAAAAAAAAAAAA"
        "AAAAATvAAAAAAAAAAAAAAAAAAAShAAAAAAAAAAAAAAAAAAAUeAAAAAAAAAAAAAAAAAAARMAAAAAAAAAAAAAAAAAAASEAAAAAAAAA"
        "AAAAAAAAAAVMAAAAAAAAAAAAAAAAAAAStAAAAAAAAAAAAAAAAAAATrAAAAAAAAAAAAAAAAAAATTAAAAAAAAAAAAAAAAAAAUbAAAA"
        "AAAAAAAAAAAAAAAUWAAAAAAAAAAAAAAAAAAATSAAAAAAAAAAAAAAAAAAATCAAAAAAAAAAAAAAAAAAAUcAAAAAAAAAAAAAAAAAAAT"
        "tAAAAAAAAAAAAAAAAAAATgAAAAAAAAAAAAAAAAAAARlAAAAAAAAAAAAAAAAAAAUZAAAAAAAAAAAAAAAAAAATWAAAAAAAAAAAAAAA"
        "AAAAUjAAAAAAAAAAAAAAAAAAATsAAAAAAAAAAAAAAAAAAAUqAAAAAAAAAAAAAAAAAAARJAAAAAAAAAAAAAAAAAAARIAAAAAAAAAA"
        "AAAAAAAAARWAAAAAAAAAAAAAAAAAAARTAAAAAAAAAAAAAAAAAAARfAAAAAAAAAAAAAAAAAAAT+AAAAAAAAAAAAAAAAAAATmAAAAA"
        "AAAAAAAAAAAAAASBAAAAAAAAAAAAAAAAAAARqAAAAAAAAAAAAAAAAAAAR5AAAAAAAAAAAAAAAAAAARsAAAAAAAAAAAAAAAAAAATp"
        "AAAAAAAAAAAAAAAAAAAVDAAAAAAAAAAAAAAAAAAARUAAAAAAAAAAAAAAAAAAASmAAAAAAAAAAAAAAAAAAATGAAAAAAAAAAAAAAAA"
        "AAAUyAAAAAAAAAAAAAAAAAAATlAAAAAAAAAAAAAAAAAAATkAAAAAAAAAAAAAAAAAAAR7AAAAAAAAAAAAAAAAAAARXAAAAAAAAAAA"
        "AAAAAAAAGbAAAAAAAAAAAAAAAAAAAR3AAAAAAAAAAAAAAAAAAARrAAAAAAAAAAAAAAAAAAASOAAAAAAAAAAAAAAAAAAASrAAAAAA"
        "AAAAAAAAAAAAAR2AAAAAAAAAAAAAAAAAAAUuAAAAAAAAAAAAAAAAAAASVAAAAAAAAAAAAAAAAAAARnAAAAAAAAAAAAAAAAAAAJBA"
        "AAAAAAAAAAAAAAAAAARuAAAAAAAAAAAAAAAAAAASAAAAAAAAAAAAAAAAAAAAVTAAAAAAAAAAAAAAAAAAASkAAAAAAAAAAAAAAAAA"
        "AAHEAAAAAAAAAAAAAAAAAAAHIAAAAAAAAAAAAAAAAAAASXAAAAAAAAAAAAAAAAAAASwAAAAAAAAAAAAAAAAAAAR/AAAAAAAAAAAA"
        "AAAAAAASNAAAAAAAAAAAAAAAAAAAU3AAAAAAAAAAAAAAAAAAAU5AAAAAAAAAAAAAAAAAAAU1AAAAAAAAAAAAAAAAAAAU2AAAAAAA"
        "AAAAAAAAAAAAU8AAAAAAAAAAAAAAAAAAAU0AAAAAAAAAAAAAAAAAAAU4AAAAAAAAAAAAAAAAAAAU6AAAAAAAAAAAAAAAAAAAR0AA"
        "AAAAAAAAAAAAAAAAAR9AAAAAAAAAAAAAAAAAAAHeAAAAAAAAAAAAAAAAAAARVAAAAAAAAAAAAAAAAAAAUrAAAAAAAAAAAAAAAAAA"
        "AU9AAAAAAAAAAAAAAAAAAARmAAAAAAAAAAAAAAAAAAAT0AAAAAAAAAAAAAAAAAAAUsAAAAAAAAAAAAAAAAAAAU7AAAAAAAAAAAAA"
        "AAAAAAVYAAAAAAAAAAAAAAAAAAARvAAAAAAAAAAAAAAAAAAATfAAAAAAAAAAAAAAAAAAARSAAAAAAAAAAAAAAAAAAAUzAAAAAAAA"
        "AAAAAAAAAAAVWAAAAAAAAAAAAAAAAAAAToAAAAAAAAAAAAAAAAAAAT5AAAAAAAAAAAAAAAAAAAR+AAAAAAAAAAAAAAAAAAATnAAA"
        "AAAAAAAAAAAAAAAAU/AAAAAAAAAAAAAAAAAAAU+AAAAAAAAAAAAAAAAAAARxAAAAAAAAAAAAAAAAAAAUvAAAAAAAAAAAAAAAAAAA"
        "UxAAAAAAAAAAAAAAAAAAAUwAAAAAAAAAAAAAAAAAAATzAAAAAAAAAAAAAAAAAAAUXAAAAAAAAAAAAAAAAAAAUtAAAAAAAAAAAAAA"
        "AAAAASzAAAAAAAAAAAAAAAAAAAUlAAAAAAAAAAAAAAAAAAARpAAAAAAAAAAAAAAAAAAAT7AAAAAAAAAAAAAAAAAAARwAAAAAAAAA"
        "AAAAAAAAAAR6AAAAAAAAAAAAAAAAAAARoAAAAAAAAAAAAAAAAAAASJAAAAAAAAAAAAAAAAAAASWAAAAAAAAAAAAAAAAAAARtAAAA"
        "AAAAAAAAAAAAAAASqAAAAAAAAAAAAAAAAAAAVOAAAAAAAAAAAAAAAAAAAVPAAAAAAAAAAAAAAAAAAAVUAAAAAAAAAAAAAAAAAAAH"
        "uAAAAAAAAAAAAAAAAAAAVFAAAAAAAAAAAAAAAAAAAVCAAAAAAAAAAAAAAAAAAAR4AAAAAAAAAAAAAAAAAAASyAAAAAAAAAAAAAAA"
        "AAAASpAAAAAAAAAAAAAAAAAAATjAAAAAAAAAAAAAAAAAAAR8AAAAAAAAAAAAAAAAAAAVEAAAAAAAAAAAAAAAAAAAR1AAAAAAAAAA"
        "AAAAAAAAARQAAAAAAAAAAAAAAAAAAAROAAAAAAAAAAAAAAAAAAARRAAAAAAAAAAAAAAAAAAAReAAAAAAAAAAAAAAAAAAARNAAAAA"
        "AAAAAAAAAAAAAARPAAAAAAAAAAAAAAAAAAAVJAAAAAAAAAAAAAAAAAAATNAAAAAAAAAAAAAAAAAAATAAAAAAAAAAAAAAAAAAAAUL"
        "AAAAAAAAAAAAAAAAAAATHAAAAAAAAAAAAAAAAAAATKAAAAAAAAAAAAAAAAAAATJAAAAAAAAAAAAAAAAAAAS7AAAAAAAAAAAAAAAA"
        "AAAF+AAAAAAAAAAAAAAAAAAARgAAAAAAAAAAAAAAAAAAAUfAAAAAAAAAAAAAAAAAAATPAAAAAAAAAAAAAAAAAAAGDAAAAAAAAAAA"
        "AAAAAAAAS5AAAAAAAAAAAAAAAAAAATRAAAAAAAAAAAAAAAAAAAUaAAAAAAAAAAAAAAAAAAARiAAAAAAAAAAAAAAAAAAAUiAAAAAA"
        "AAAAAAAAAAAAARGAAAAAAAAAAAAAAAAAAAUgAAAAAAAAAAAAAAAAAAASRAAAAAAAAAAAAAAAAAAAT8AAAAAAAAAAAAAAAAAAASxA"
        "AAAAAAAAAAAAAAAAAATcAAAAAAAAAAAAAAAAAAAS1AAAAAAAAAAAAAAAAAAAS2AAAAAAAAAAAAAAAAAAAS4AAAAAAAAAAAAAAAAA"
        "AARHAAAAAAAAAAAAAAAAAAAT3AAAAAAAAAAAAAAAAAAAVXAAAAAAAAAAAAAAAAAAAUJAAAAAAAAAAAAAAAAAAATqAAAAAAAAAAAA"
        "AAAAAAAHpAAAAAAAAAAAAAAAAAAATeAAAAAAAAAAAAAAAAAAATyAAAAAAAAAAAAAAAAAAASQAAAAAAAAAAAAAAAAAAAUHAAAAAAA"
        "AAAAAAAAAAAAUGAAAAAAAAAAAAAAAAAAATIAAAAAAAAAAAAAAAAAAATEAAAAAAAAAAAAAAAAAAAIpAAAAAAAAAAAAAAAAAAATLAA"
        "AAAAAAAAAAAAAAAAATMAAAAAAAAAAAAAAAAAAAVVAAAAAAAAAAAAAAAAAAAUMAAAAAAAAAAAAAAAAAAAVGAAAAAAAAAAAAAAAAAA"
        "ATFAAAAAAAAAAAAAAAAAAASMAAAAAAAAAAAAAAAAAAAI1AAAAAAAAAAAAAAAAAAAUKAAAAAAAAAAAAAAAAAAAUmAAAAAAAAAAAAA"
        "AAAAAAVAAAAAAAAAAAAAAAAAAAASlAAAAAAAAAAAAAAAAAAAS8AAAAAAAAAAAAAAAAAAARyAAAAAAAAAAAAAAAAAAATBAAAAAAAA"
        "AAAAAAAAAAATdAAAAAAAAAAAAAAAAAAASLAAAAAAAAAAAAAAAAAAATOAAAAAAAAAAAAAAAAAAAUIAAAAAAAAAAAAAAAAAAARLAAA"
        "AAAAAAAAAAAAAAAAT9AAAAAAAAAAAAAAAAAAASbAAAAAAAAAAAAAAAAAAAGdAAAAAAAAAAAAAAAAAAAVSAAAAAAAAAAAAAAAAAAA"
        "S9AAAAAAAAAAAAAAAAAAASvAAAAAAAAAAAAAAAAAAAURAAAAAAAAAAAAAAAAAAASeAAAAAAAAAAAAAAAAAAARbAAAAAAAAAAAAAA"
        "AAAAARaAAAAAAAAAAAAAAAAAAARcAAAAAAAAAAAAAAAAAAARZAAAAAAAAAAAAAAAAAAARdAAAAAAAAAAAAAAAAAAAAAAAAARDAAA"
        "AAAAREAAAARFAAAAAAAAAAAAAAAAAAASuAAAAAAAAAAAAAAAAAAAUAAAAAAAAAAAAAAAAAAAAUTAAAAAAAAAAAAAAAAAAAT/AAAA"
        "AAAAAAAAAAAAAAAS0AAAAAAAAAAAAAAAAAAASUAAAAAAAAAAAAAAAAAAAAAAAAAAAAS3AAAAAAAAAASnAAAAAAAAAAAAAAAAAAAU"
        "kAAAAAAAAAAAAAAAAAAAS/AAAAAAAAAAAAAAAAAAAVZAAAAAAAAAAAAAAAAAAAUFAAAAAAAAAAAAAAAAAAAUSAAAAAAAAAAAAAAA"
        "AAAASiAAAAAAASjAAAAAAAAAATVAAAAAAAAAAAAAAAAAAAH4AAAAAAAAAAAAAAAAAAAUBAAAAAAAAAAAAAAAAAAATwAAAAAAAAAA"
        "AAAAAAAAASgAAAAAAAAAAAAAAAAAAATYAAAAAAAAAAAAAAAAAAASSAAAAAAAAAAAAAAAAAAAS+AAAAAAAAAAAAAAAAAAAUVAAAAA"
        "AAAAAAAAAAAAAARhAAAAAAAAAAAAAAAAAAAUDAAAAAAAAAAAAAAAAAAAUoAAAAAAAAAAAAAAAAAAATaAAAAAAAAAAAAAAAAAAARj"
        "AAAAAAAAAAAAAAAAAAAUQAAAAAAAAAAAAAAAAAAARKAAAAAAAAAAAAAAAAAAAUEAAAAAAAAAAAAAAAAAAATQAAAAAAAAAAAAAAAA"
        "AAAVBAAAAAAAAAAAAAAAAAAARYAAAAAAAAAAAAAAAAAAATUAAAAAAAAAAAAAAAAAAAUCAAAAAAAAAAAAAAAAAAAT4AAAAAAAAAAA"
        "AAAAAAAASGAAAAAAAAAAAAAAAAAAATZAAAAAAAAAAAAAAAAAAAS6AAAAAAAAAAAAAAAAAAASPAAAAAAAAAAAAAAAAAAASCAAAAAA"
        "AAAAAAAAAAAAATDAAAAAAAAAAAAAAAAAAAUdAAAAAAAAAAAAAAAAAAAUOAAAAAAAAAAAAAAAAAAAIJAAAAAAAAAAAAAAAAAAAThA"
        "AAAAAAAAAAAAAAAAAAVKAAAAAAAAAAAAAAAAAAAIrAAAAAAAAAAAAAAAAAAAVIAAAAAAAAAAAAAAAAAAATxAAAAAAAAAAAAAAAAA"
        "AAT2AAAAAAAAAAAAAAAAAAASIAAAAAAAAAAAAAAAAAAAVHAAAAAAAAAAAAAAAAAAAUhAAAAAAAAAAAAAAAAAAAUNAAAAAAAAAAAA"
        "AAAAAAASfAAAAAAAAAAAAAAAAAAAT1AAAAAAAAAAAAAAAAAAATuAAAAAAAAAAAAAAAAAAAT6AAAAAAAAAAAAAAAAAAAVRAAAAAAA"
        "AAAAAAAAAAAAVQAAAAAAAAAAAAAAAAAA";
    inline constexpr const char* ZoneNamesChunks[] = {ZoneNamesChunk0};
    inline constexpr Packed ZoneNames{ZoneNamesChunks, 13, 3};

    inline constexpr char MetaKeysChunk0[] =
        "AABAACAADAAFAAGAAIAALAAMAANAAOAAPAARAAUAAVAAWAAXAAZAAaAAbAAcAAdAAeAAfAAhAAjAAkAAmAAoAApAArAAsAAtAAuA"
        "AvAAwAAxAAyAAzAA1AA3AA6AA7AA8AA9AA+AA/ABAABBABCABDABEABGABHABIABJABKABOABPABRABSABTABUABVABWABXABYAB"
        "ZABaABbABcABeABfABgABjABkABlABnABoABpABsABvABwAByAB0AB1AB2AB3AB4AB5AB6AB7AB8AB9AB+AB/ACAACBACCACDACE"
        "ACFACHACIACKACLACMACNACOACPACQACRACSACTACUACWACXACYACbACcACeACfACgAChACjACkAClACmACpACqACrACtACuACwA"
        "CyACzAC0AC1AC2AC3AC4AC5AC6AC7AC9";
    inline constexpr const char* MetaKeysChunks[] = {MetaKeysChunk0};
    inline constexpr Packed MetaKeys{MetaKeysChunks, 13, 3};

    inline constexpr char MetaNamesChunk0[] =
        "AAAAVaAAAAAAAAAAAAAAAAVbAAAAAAAAAAAAAAAAVcAAAAAAAAAAAAAAAAVdAAAAAAAAAAAAAVeAVfAVgAAAAAAAAAAVhAViAVjA"
        "AAAAAAAAAVkAVlAVmAAAAAAAAAAVnAVoAVpAAAAAAAAAAVqAVrAVsAAAAAAAAAAVtAVuAVvAAAAAAAAAAVwAVxAVyAAAAAAAAAAV"
        "zAV0AV1AAAAAAAAAAV2AV3AV4AAAAAAAAAAV5AV6AV7AAAAAAAAAAV8AV9AV+AAAAAAAAAAV/AWAAWBAAAAAAAAAAWCAWDAWEAAA"
        "AAAAAAAWFAWGAWHAAAAAAAAAAWIAWJAWKAAAAAAAAAAWLAWMAWNAAAAAAAAAAWOAWPAWQAAAAAAAAAAWRAWSAWTAAAAAAAAAAWUA"
        "WVAWWAAAAAAAAAAWXAWYAWZAAAAAAAAAAAAAWaAAAAAAAAAAAAAAAAWbAAAAAAAAAAAAAWcAWdAWeAAAAAAAAAAAAAWfAAAAAAAA"
        "AAAAAWgAWhAWiAAAAAAAAAAAAAWjAAAAAAAAAAAAAWkAWlAWmAAAAAAAAAAWnAWoAWpAAAAAAAAAAWqAWrAWsAAAAAAAAAAAAAWt"
        "AAAAAAAAAAAAAAAAWuAAAAAAAAAAAAAWvAWwAWxAAAAAAAAAAWyAWzAW0AAAAAAAAAAW1AW2AW3AAAAAAAAAAAAAW4AAAAAAAAAA"
        "AAAAAAW5AAAAAAAAAAAAAAAAW6AAAAAAAAAAAAAW7AW8AW9AAAAAAAAAAAAAW+AAAAAAAAAAAAAW/AXAAXBAAAAAAAAAAXCAXDAX"
        "EAAAAAAAAAAAAAXFAAAAAAAAAAAAAXGAXHAXIAAAAAAAAAAXJAXKAXLAAAAAAAAAAXMAXNAXOAAAAAAAAAAAAAXPAAAAAAAAAAAA"
        "AAAAXQAAAAAAAAAAAAAAAAXXAAAAAAAAAAAAAAAAXRAAAAAAAAAAAAAAAAXSAAAAAAAAAAAAAXTAXUAXVAAAAAAAAAAAAAXWAAAA"
        "AAAAAAAAAXYAXZAXaAAAAAAAAAAXbAXcAXdAAAAAAAAAAAAAXeAAAAAAAAAAAAAAAAXfAAAAAAAAAAAAAXgAXhAXiAAAAAAAAAAX"
        "jAXkAXlAAAAAAAAAAXmAXnAXoAAAAAAAAAAAAAXpAAAAAAAAAAAAAAAAXqAAAAAAAAAAAAAAAAXrAAAAAAAAAAAAAAAAXsAAAAAA"
        "AAAAAAAAAAXtAAAAAAAAAAAAAAAAXuAAAAAAAAAAAAAXvAXwAXxAAAAAAAAAAXyAXzAX0AAAAAAAAAAX1AX2AX3AAAAAAAAAAX4A"
        "X5AX6AAAAAAAAAAAAAX7AAAAAAAAAAAAAAAAX8AAAAAAAAAAAAAAAAX9AAAAAAAAAAAAAX+AX/AYAAAAAAAAAAAAAAYBAAAAAAAA"
        "AAAAAYCAYDAYEAAAAAAAAAAAAAYFAAAAAAAAAAAAAAAAYGAAAAAAAAAAAAAYHAYIAYJAAAAAAAAAAYKAYLAYMAAAAAAAAAAAAAYN"
        "AAAAAAAAAAAAAAAAYOAAAAAAAAAAAAAAAAYPAAAAAAAAAAAAAAAAYQAAAAAAAAAAAAAYRAYSAYTAAAAAAAAAAAAAYUAAAAAAAAAA"
        "AAAYVAYWAYXAAAAAAAAAAYYAYZAYaAAAAAAAAAAYbAYcAYdAAAAAAAAAAAAAYeAAAAAAAAAAAAAAAAYfAAAAAAAAAAAAAAAAYgAA"
        "AAAAAAAAAAAYhAYiAYjAAAAAAAAAAYkAYlAYmAAAAAAAAAAYnAYoAYpAAAAAAAAAAAAAYqAAAAAAAAAAAAAYrAYsAYtAAAAAAAAA"
        "AYuAYvAYwAAAAAAAAAAYxAYyAYzAAAAAAAAAAY0AY1AY2AAAAAAAAAAY3AY4AY5AAAAAAAAAAAAAY6AAAAAAAAAAAAAAAAY7AAAA"
        "AAAAAAAAAY8AY9AY+AAAAAAAAAAY/AZAAZBAAAAAAAAAAZCAZDAZEAAAAAAAAAAAAAZFAAAAAAAAAAAAAZGAZHAZIAAAAAAAAAAA"
        "AAZJAAAAAAAAAAAAAAAAZKAAAAAAAAAAAAAAAAZLAAAAAAAAAAAAAAAAZMAAAAAAAAAAAAAAAAZNAAAAAAAAAAAAAZOAZPAZQAAA"
        "AAAAAAAZRAZSAZTAAAAAAAAAAAAAZUAAAAAAAAAAAAAAAAZVAAAAAAAAAAAAAAAAZWAAAAAAAAAAAAAAAAZXAAAAAAAAAAAAAAAA"
        "ZYAAAAAAAAAAAAAAAAZZAAAAAAAAAAAAAAAAZaAAAAAAAAAAAAAZbAZcAZdAAAAAAAAAAAAAZeAAAAAAAAAAAAAAAAZfAAAAAAAA"
        "AAAAAZgAZhAZiAAAAAAAAAAAAAZjAAAAAAAAAAAAAZkAZlAZmAAAAAAAAAAAAAZnAAAAAAAAAAAAAZoAZpAZqAAAAAAAAAAZrAZs"
        "AZtAAAAAAAAAAZuAZvAZwAAAAAAAAAAAAAZxAAAAAAAAAAAAAZyAZzAZ0AAAAAAAAAAZ1AZ2AZ3AAAAAAAAAAAAAZ4AAAAAAAAAA"
        "AAAAAAZ5AAAAAAAAAAAAAAAAZ6AAAAAAAAAAAAAZ7AZ8AZ9AAAAAAAAAAZ+AZ/AaAAAAAAAAAAAAAAaBAAAAAAAAAAAA";
    inline constexpr const char* MetaNamesChunks[] = {MetaNamesChunk0};
    inline constexpr Packed MetaNames{MetaNamesChunks, 13, 3};

    inline constexpr uint16_t Formats[] = {
        1666, 1667, 1668, 1669, 1670, 1671, 0, 0, 0, 0, 0, 1672,
    };

    inline constexpr Table table{
        0x62616c6068e000, 0,
        NameTexts,
        LanguageKeys, LanguageNames, 315,
        nullptr, Packed{}, 0,
        RegionKeys, RegionNames, 295,
        ScriptKeys, ScriptNames, 188,
        Packed{}, Packed{}, 0,
        CurrencyKeys, CurrencyNames, 153,
        ZoneKeys, ZoneNames, 292,
        MetaKeys, MetaNames, 144,
        Formats,
    };

    // the table registered when the header is included, once a program
    inline Registration registration{&table};
}
