//------------------------------------------------------------------------------
// SGCL: a C++20 application platform
// Copyright (c) 2022-2026 Sebastian Nibisz
// SPDX-License-Identifier: Apache-2.0
//------------------------------------------------------------------------------
#pragma once
#include "detail/registry.h"
#include "es-419.h"

#include <cstdint>

// The display names of the locale es-GT (español), CLDR 46.0: the names of languages,
// regions, scripts, currencies and time zones in it, what differs from es-419 (included).
// Including this header is all a program does: txt::locale::display_name,
// region::display_name, script::display_name and currency::display_name then
// answer in this language. Generated by tools/cldr_tables.py: do not edit.
namespace sgcl::txt::detail::names::l_es_GT {
    inline constexpr char8_t NameChunk0[] =
        u8"acehnésarapahobhojpurieuskeragriego antiguosotho septentrionalpunyabísiswatisuajilisuajili del Congo"
        u8"setswanawoloftamazight marroquí estándarBosnia y HerzegovinaTimor-LesteIslas menores alejadas de EE."
        u8" UU.quetzalquetzales{0} ({1}){0}, {1}hora de {0}hora estándar de {0}hora de verano de {0}{1} ({0}){0"
        u8"} {1}";
    inline constexpr const char8_t* NameChunks[] = {NameChunk0};
    inline constexpr uint16_t NameChunkSizes[] = {310};
    inline constexpr char NameRefsChunk0[] =
        "AAAAAAAAAAAIAAAPAAAXAAAeAAAsAAA/AABHAABOAABVAABmAABuAABzAACQAACkAACvAADQAADXAADgAADpAADxAAD8AAERAAEm"
        "AAEvAAE2";
    inline constexpr const char* NameRefsChunks[] = {NameRefsChunk0};
    inline constexpr Packed NameRefs{NameRefsChunks, 13, 4};
    inline constexpr Text NameTexts{NameChunks, NameChunkSizes, NameRefs};

    inline constexpr char LanguageKeysChunk0[] =
        "AC1AIBAJzAJ3AKOALvARlAZQAkPB5DDpvGjo";
    inline constexpr const char* LanguageKeysChunks[] = {LanguageKeysChunk0};
    inline constexpr Packed LanguageKeys{LanguageKeysChunks, 13, 3};

    inline constexpr char LanguageNamesChunk0[] =
        "AAEAAHAAIAAJAALAAMAABAACAADAAFAAGAAN";
    inline constexpr const char* LanguageNamesChunks[] = {LanguageNamesChunk0};
    inline constexpr Packed LanguageNames{LanguageNamesChunks, 13, 3};

    inline constexpr const uint64_t* TaggedKeys = nullptr;

    inline constexpr const uint16_t* TaggedNames = nullptr;

    inline constexpr char RegionKeysChunk0[] =
        "AA3AIoAJE";
    inline constexpr const char* RegionKeysChunks[] = {RegionKeysChunk0};
    inline constexpr Packed RegionKeys{RegionKeysChunks, 13, 3};

    inline constexpr char RegionNamesChunk0[] =
        "AAOAAPAAQ";
    inline constexpr const char* RegionNamesChunks[] = {RegionNamesChunk0};
    inline constexpr Packed RegionNames{RegionNamesChunks, 13, 3};

    inline constexpr const uint32_t* ScriptKeys = nullptr;

    inline constexpr const uint16_t* ScriptNames = nullptr;

    inline constexpr const uint32_t* AloneKeys = nullptr;

    inline constexpr const uint16_t* AloneNames = nullptr;

    inline constexpr char CurrencyKeysChunk0[] =
        "B6R";
    inline constexpr const char* CurrencyKeysChunks[] = {CurrencyKeysChunk0};
    inline constexpr Packed CurrencyKeys{CurrencyKeysChunks, 13, 3};

    inline constexpr char CurrencyNamesChunk0[] =
        "AARAAAAARAAAAAAAAAAAS";
    inline constexpr const char* CurrencyNamesChunks[] = {CurrencyNamesChunk0};
    inline constexpr Packed CurrencyNames{CurrencyNamesChunks, 13, 3};

    inline constexpr const uint16_t* ZoneKeys = nullptr;

    inline constexpr const uint16_t* ZoneNames = nullptr;

    inline constexpr const uint16_t* MetaKeys = nullptr;

    inline constexpr const uint16_t* MetaNames = nullptr;

    inline constexpr uint16_t Formats[] = {
        19, 20, 21, 22, 23, 24, 0, 0, 0, 0, 0, 25,
    };

    inline constexpr Table table{
        0x6573000001a2, 0x6573000008f8,
        NameTexts,
        LanguageKeys, LanguageNames, 12,
        nullptr, Packed{}, 0,
        RegionKeys, RegionNames, 3,
        Packed{}, Packed{}, 0,
        Packed{}, Packed{}, 0,
        CurrencyKeys, CurrencyNames, 1,
        Packed{}, Packed{}, 0,
        Packed{}, Packed{}, 0,
        Formats,
    };

    // the table registered when the header is included, once a program
    inline Registration registration{&table};
}
