//------------------------------------------------------------------------------
// SGCL: a C++20 application platform
// Copyright (c) 2022-2026 Sebastian Nibisz
// SPDX-License-Identifier: Apache-2.0
//------------------------------------------------------------------------------
#pragma once
#include "detail/registry.h"
#include "es-419.h"

#include <cstdint>

// The display names of the locale es-SV (español), CLDR 46.0: the names of languages,
// regions, scripts, currencies and time zones in it, what differs from es-419 (included).
// Including this header is all a program does: txt::locale::display_name,
// region::display_name, script::display_name and currency::display_name then
// answer in this language. Generated by tools/cldr_tables.py: do not edit.
namespace sgcl::txt::detail::names::l_es_SV {
    inline constexpr char8_t NameChunk0[] =
        u8"acehnésarapahobhojpurigriego antiguosotho septentrionalsiswatiwolofIslas menores alejadas de EE. UU."
        u8"{0} ({1}){0}, {1}hora de {0}hora estándar de {0}hora de verano de {0}{1} ({0}){0} {1}";
    inline constexpr const char8_t* NameChunks[] = {NameChunk0};
    inline constexpr uint16_t NameChunkSizes[] = {187};
    inline constexpr char NameRefsChunk0[] =
        "AAAAAAAAAAAIAAAPAAAXAAAlAAA4AAA/AABEAABlAABuAAB2AACBAACWAACrAAC0AAC7";
    inline constexpr const char* NameRefsChunks[] = {NameRefsChunk0};
    inline constexpr Packed NameRefs{NameRefsChunks, 13, 4};
    inline constexpr Text NameTexts{NameChunks, NameChunkSizes, NameRefs};

    inline constexpr char LanguageKeysChunk0[] =
        "AJzALvARlAZQAkPB5DDpv";
    inline constexpr const char* LanguageKeysChunks[] = {LanguageKeysChunk0};
    inline constexpr Packed LanguageKeys{LanguageKeysChunks, 13, 3};

    inline constexpr char LanguageNamesChunk0[] =
        "AAGAAHAABAACAADAAEAAF";
    inline constexpr const char* LanguageNamesChunks[] = {LanguageNamesChunk0};
    inline constexpr Packed LanguageNames{LanguageNamesChunks, 13, 3};

    inline constexpr const uint64_t* TaggedKeys = nullptr;

    inline constexpr const uint16_t* TaggedNames = nullptr;

    inline constexpr char RegionKeysChunk0[] =
        "AJE";
    inline constexpr const char* RegionKeysChunks[] = {RegionKeysChunk0};
    inline constexpr Packed RegionKeys{RegionKeysChunks, 13, 3};

    inline constexpr char RegionNamesChunk0[] =
        "AAI";
    inline constexpr const char* RegionNamesChunks[] = {RegionNamesChunk0};
    inline constexpr Packed RegionNames{RegionNamesChunks, 13, 3};

    inline constexpr const uint32_t* ScriptKeys = nullptr;

    inline constexpr const uint16_t* ScriptNames = nullptr;

    inline constexpr const uint32_t* AloneKeys = nullptr;

    inline constexpr const uint16_t* AloneNames = nullptr;

    inline constexpr const uint16_t* CurrencyKeys = nullptr;

    inline constexpr const uint16_t* CurrencyNames = nullptr;

    inline constexpr const uint16_t* ZoneKeys = nullptr;

    inline constexpr const uint16_t* ZoneNames = nullptr;

    inline constexpr const uint16_t* MetaKeys = nullptr;

    inline constexpr const uint16_t* MetaNames = nullptr;

    inline constexpr uint16_t Formats[] = {
        9, 10, 11, 12, 13, 14, 0, 0, 0, 0, 0, 15,
    };

    inline constexpr Table table{
        0x65730000042e, 0x6573000008f8,
        NameTexts,
        LanguageKeys, LanguageNames, 7,
        nullptr, Packed{}, 0,
        RegionKeys, RegionNames, 1,
        Packed{}, Packed{}, 0,
        Packed{}, Packed{}, 0,
        Packed{}, Packed{}, 0,
        Packed{}, Packed{}, 0,
        Packed{}, Packed{}, 0,
        Formats,
    };

    // the table registered when the header is included, once a program
    inline Registration registration{&table};
}
