//------------------------------------------------------------------------------
// SGCL: a C++20 application platform
// Copyright (c) 2022-2026 Sebastian Nibisz
// SPDX-License-Identifier: Apache-2.0
//------------------------------------------------------------------------------
#pragma once
#include "detail/registry.h"

#include <cstdint>

// The display names of the locale id (Indonesia), CLDR 46.0: the names of languages,
// regions, scripts, currencies and time zones in it.
// Including this header is all a program does: txt::locale::display_name,
// region::display_name, script::display_name and currency::display_name then
// answer in this language. Generated by tools/cldr_tables.py: do not edit.
namespace sgcl::txt::detail::names::l_id {
    inline constexpr char8_t NameChunk0[] =
        u8"AfarAbkhazAcehAcoliAdangmeAdygeiAvestaArab TunisiaAfrikaansAfrihiliAghemAinuAkanAkkadiaAlabamaAleutA"
        u8"ltai SelatanAmharikAragonInggris KunoOboloAngikaArabArab Standar ModernAramMapucheArapahoArab Aljaza"
        u8"irArab NajdiArawakArab MarokoArab MesirAssamAsuBahasa Isyarat AmerikaAsturiaAtikamekwAvarAwadhiAymar"
        u8"aAzerbaijaniBashkirBaluchiBaliBavariaBasaBamunBatak TobaGhomalaBelarusiaBejaBembaBetawiBenaBafutBulg"
        u8"ariaHaryanviBalochi BaratBhojpuriBislamaBikolBiniBanjarKomSiksikaAniiBambaraBengaliTibetBretonBrajBo"
        u8"doBosniaAkooseBuriatBugisBuluBlinMedumbaKatalanKadoKaribiaCayugaAtsamChakmaChechenCebuanoKigaChamorr"
        u8"oChibchaChagataiChuukeMariJargon ChinookKoktawChipewyanCherokeeCheyenneKurdi SoraniChilcotinKorsikaK"
        u8"optikKreeMichifTatar KrimeaEast Cree SelatanCree DataranEast Cree UtaraMoose CreeCarolina Algonquian"
        u8"Seselwa Kreol PrancisCekoKashubiaCree RawaBahasa Gereja SlavoniaChuvashWelshDanskDakotaDargwaTaitaJe"
        u8"rmanJerman Tinggi (Swiss)DelawareSlaveDogribDinkaZarmaDogriSorbia HilirDualaBelanda Abad Pertengahan"
        u8"DivehiJola-FonyiDyulaDzongkhaDazagaEmbuEweEfikMesir KunoEkajukYunaniElamInggrisInggris (Britania)Ing"
        u8"gris Abad PertengahanEsperantoSpanyolSpanyol (Eropa)EstoniaBasqueEwondoPersiaPersia DariFangFantiFul"
        u8"aSuomiFilipinoFijiFaroeFonPrancisPrancis CajunPrancis Abad PertengahanPrancis KunoArpitanFrisia Utar"
        u8"aFrisia TimurFriuliFrisia BaratIrlandiaGaGagauzGayoGbayaGaelik SkotlandiaGeezGilbertGalisiaGilakiJer"
        u8"man Abad PertengahanGuaraniJerman KunoGondiGorontaloGotikGreboYunani KunoJerman (Swiss)GujaratGusiiM"
        u8"anxGwich’inHausaHaidaHawaiiHaida SelatanIbraniHindiHindi FijiHiligaynonHititHmongHiri MotuKroasiaSor"
        u8"bia HuluKreol HaitiHungariaHupaHalkomelemArmeniaHereroInterlinguaIbanIbibioIndonesiaInterlingueIgboS"
        u8"ichuan YiInupiakInuktitut Kanada BaratIlokoIngushetiaIdoIslandiaItaliaInuktitutJepangLojbanNgombaMac"
        u8"hameIbrani-PersiaIbrani-ArabJawaGeorgiaKara-KalpakKabyleKachinJjuKambaKawiKabardiKanembuTyapMakondeK"
        u8"abuverdianuKenyangKoroKongoKaingangKhasiKhotanKoyra ChiiniKikuyuKuanyamaKazakhKakoKalaallisutKalenji"
        u8"nKhmerKimbunduKannadaKoreaKomi-PermyakKonkaniKosreKpelleKanuriKarachai BalkarKrioKareliaKurukKashmir"
        u8"ShambalaBafiaDialek KolschKurdiKumykKutenaiKomiKornishKwakʼwalaKuviKirgizLatinLadinoLangiLahndaLamba"
        u8"LuksemburgLezghiaGandaLimburgiaLiguriaLillooetLakotaLombardLingalaLaoMongoKreol LouisianaLoziLuri Ut"
        u8"araSaamiaLituaniaLuba-KatangaLuba-LuluaLuisenoLundaLuoMizoLuyiaLatviaLazMaduraMafaMagahiMaithiliMaka"
        u8"sarMandingoMasaiMabaMokshaMandarMendeMeruMorisienMalagasiIrlandia Abad PertengahanMakhuwa-MeettoMeta"
        u8"’MarshallMaoriMikmakMinangkabauMakedoniaMalayalamMongoliaManchuriaManipuriInnu-aimunMohawkMossiMarat"
        u8"hiMelayuMaltaMundangBeberapa BahasaBahasa MuskogeeMirandaMarwariMentawaiBurmaMyeneEryzaMazanderaniNa"
        u8"uruNeapolitanNamaBokmål NorwegiaNdebele UtaraJerman RendahNepaliNewariNdongaNiasNiueaBelandaKwasioNy"
        u8"norsk NorwegiaNgiemboonNorwegiaNogaiNorse KunoN’KoNdebele SelatanSotho UtaraNuerNavajoNewari KlasikN"
        u8"yanjaNyamweziNyankoleNyoroNzimaOsitaniaOjibwaOjibwe Barat LautOjibwe TengahOji-CreeOjibwe BaratOkana"
        u8"ganOromoOriyaOssetiaOsageTurki OsmaniPunjabiPangasinaPahleviPampangaPapiamentoPalauPidgin NigeriaJer"
        u8"man PennsylvaniaPersia KunoFunisiaPaliPijinPolskiPohnpeiaMaliseet-PassamaquoddyPrusiaProvencal LamaP"
        u8"ashtoPortugisPortugis (Eropa)QuechuaKʼicheʼRajasthaniRapanuiRarotongaRohingyaReto-RomanRundiRumaniaM"
        u8"oldaviaRomboRomaniRotumaRusiaAromaniaKinyarwandaRwaSanskertaSandaweSakhaAram SamariaSamburuSasakSant"
        u8"aliNgambaiSanguSardiniaSisiliaSkotlandiaSindhiKurdi SelatanSami UtaraSenecaSenaSeriSelkupKoyraboro S"
        u8"enniSangoIrlandia KunoSerbo-KroasiaTachelhitShanArab SuwaSinhalaSidamoSlovakSloveniaLushootseed Sela"
        u8"tanSilesia RendahSelayarSamoaSami SelatanLule SamiInari SamiSkolt SamiShonaSoninkeSomaliaSogdienAlba"
        u8"niaSerbiaSranan TongoSererSwatiSahoSotho SelatanSalish SelatSundaSukumaSusuSumeriaSwediaSwahiliSwahi"
        u8"li (Kongo)KomoriaSuriah KlasikSuriahSilesiaTamilTutchone SelatanTuluTeluguTimneTesoTerenoTetunTajikT"
        u8"agishThaiTahltanTigrinyaTigreTivTurkmenTokelauTagalogKlingonTlingitTamashekTswanaTongaNyasa TongaTok"
        u8"i PonaTok PisinTurkiTuroyoTarokoTsongaTsimshiaTatarTutchone UtaraTat MuslimTumbukaTuvaluTwiTasawaqTa"
        u8"hitiTuviniaTamazight Maroko TengahUdmurtUyghurUgaritUkrainaUmbunduBahasa Tidak DikenalUrduUzbekVaiVe"
        u8"ndaVenesiaVietnamMakhuwaVolapukVotiaVunjoWalloonWalserWalamoWaraiWashoWarlpiriWolofWu TionghoaKalmuk"
        u8"XhosaKangriSogaYaoYapoisYangbenYembaYiddishYorubaNheengatuKantonZhuangZapotekBlissymbolZenagaTamazig"
        u8"ht Maroko StandarTionghoaZuluZuniTidak ada konten linguistikZazaDuniaAfrikaAmerika UtaraAmerika Sela"
        u8"tanOseaniaAfrika Bagian BaratAmerika TengahAfrika Bagian TimurAfrika Bagian UtaraAfrika Bagian Tenga"
        u8"hAfrika Bagian SelatanAmerikaAmerika Bagian UtaraKepulauan KaribiaAsia Bagian TimurAsia Bagian Selat"
        u8"anAsia TenggaraEropa Bagian SelatanAustralasiaMelanesiaWilayah MikronesiaPolinesiaAsiaAsia TengahAsi"
        u8"a Bagian BaratEropaEropa Bagian TimurEropa Bagian UtaraEropa Bagian BaratAfrika Sub-SaharaAmerika La"
        u8"tinPulau AscensionAndorraUni Emirat ArabAfganistanAntigua dan BarbudaAnguillaAngolaAntarktikaArgenti"
        u8"naSamoa AmerikaAustriaAustraliaArubaKepulauan AlandAzerbaijanBosnia dan HerzegovinaBarbadosBanglades"
        u8"hBelgiaBurkina FasoBahrainBurundiBeninSaint BarthélemyBermudaBruneiBoliviaBelanda KaribiaBrasilBaham"
        u8"aBhutanPulau BouvetBotswanaBelarusBelizeKanadaKepulauan Cocos (Keeling)Kongo - KinshasaRepublik Afri"
        u8"ka TengahKongo - BrazzavilleSwissCôte d’IvoireKepulauan CookCileKamerunTiongkokKolombiaPulau Clipper"
        u8"tonKosta RikaKubaTanjung VerdeCuraçaoPulau NatalSiprusDiego GarciaJibutiDenmarkDominikaRepublik Domi"
        u8"nikaAljazairCeuta dan MelillaEkuadorMesirSahara BaratEritreaEtiopiaUni EropaZona EuroFinlandiaKepula"
        u8"uan FalklandMikronesiaKepulauan FaroeGabonInggris RayaGrenadaGuyana PrancisGuernseyGhanaGibraltarGre"
        u8"enlandGambiaGuineaGuadeloupeGuinea EkuatorialGeorgia Selatan & Kep. Sandwich SelatanGuatemalaGuamGui"
        u8"nea-BissauGuyanaHong Kong DAK TiongkokPulau Heard dan Kepulauan McDonaldHondurasHaitiKepulauan Canar"
        u8"iaIsraelPulau ManIndiaWilayah Inggris di Samudra HindiaIrakIranJerseyJamaikaYordaniaKenyaKirgizstanK"
        u8"ambojaKiribatiKomoroSaint Kitts dan NevisKorea UtaraKorea SelatanKuwaitKepulauan CaymanKazakhstanLao"
        u8"sLebanonSaint LuciaLiechtensteinSri LankaLiberiaLesothoLibyaMarokoMonakoMoldovaMontenegroSaint Marti"
        u8"nMadagaskarKepulauan MarshallMakedonia UtaraMaliMyanmar (Burma)Makau DAK TiongkokKepulauan Mariana U"
        u8"taraMartinikMauritaniaMontserratMauritiusMaladewaMalawiMeksikoMalaysiaMozambikNamibiaKaledonia BaruN"
        u8"igerKepulauan NorfolkNigeriaNikaraguaNepalNiueSelandia BaruOmanPanamaPeruPolinesia PrancisPapua Nugi"
        u8"niFilipinaPakistanPolandiaSaint Pierre dan MiquelonKepulauan PitcairnPuerto RikoWilayah PalestinaPor"
        u8"tugalParaguayQatarOseania LuarRéunionRwandaArab SaudiKepulauan SolomonSeychellesSudanSingapuraSaint "
        u8"HelenaKepulauan Svalbard dan Jan MayenSlovakiaSierra LeoneSan MarinoSenegalSurinameSudan SelatanSao "
        u8"Tome dan PrincipeEl SalvadorSint MaarteneSwatiniTristan da CunhaKepulauan Turks dan CaicosChadWilaya"
        u8"h Selatan PrancisTogoThailandTajikistanTimor LesteTurkmenistanTunisiaTrinidad dan TobagoTaiwanTanzan"
        u8"iaUgandaKepulauan Terluar ASPerserikatan Bangsa-BangsaAmerika SerikatUruguayUzbekistanVatikanSaint V"
        u8"incent dan GrenadineVenezuelaKepulauan Virgin Britania RayaKepulauan Virgin Amerika SerikatVanuatuKe"
        u8"pulauan Wallis dan FutunaAksen AsingPseudo-BidiKosovoYamanMayotteAfrika SelatanZambiaZimbabweWilayah"
        u8" Tidak DikenalAdlamAfakaAlbania KaukasiaNastaliqAram ImperialBamumBassa VahBatakBhaiksukiBopomofoBra"
        u8"hmiBrailleBuhidSimbol Aborigin Kanada KesatuanKariaChorasmianCirthCypro-MinoanSirilikGereja Slavonia"
        u8" Sirilik LamaDewanagariDives AkuruDograDeseretStenografi DuployanDemotik MesirHieratik MesirHierogli"
        u8"p MesirElbasanElymaicGeorgian KhutsuriGlagoliticGunjala GondiMasaram GondiGothicGranthaGurmukhiHan d"
        u8"engan BopomofoHangulHanHanunooSederhanaTradisionalHatranHiraganaHieroglif AnatoliaPahawh HmongNyiake"
        u8"ng Puachue HmongKatakana atau HiraganaHungaria KunoIndusItalia LamaJurchenKayah LiKatakanaKharoshthi"
        u8"KhojkiSkrip kecil KhitanKaithiLannaLatin FrakturLatin GaelikLepchaLimbuLinear ALinear BFraserLomaLyc"
        u8"iaLydiaMahajaniMakassarMandaeManikheiMarchenHieroglip MayaMedefaidrinKursif MeroitikMeroitikMoonMroM"
        u8"eitei MayekMultaniMyanmarNandinagariArab Utara KunoNabataeaNaxi GebaNushuOghamChiki LamaOrkhonOsmany"
        u8"aUyghur LamaPalmiraPau Cin HauPermik KunoPhags-paMazmur PahleviKitab PahleviPhoenixFonetik PollardPr"
        u8"asasti ParthiaZawgyiRejangHanifiRongorongoRunikSamariaSaratiArab Selatan KunoSaurashtraTulisan Isyar"
        u8"atShaviaSharadaSiddhamKhudawadiSogdianSogdian LamaSora SompengSoyomboSyloti NagriSuriah EstrangeloSu"
        u8"riah BaratSuriah TimurTagbanwaTakriTai LeTai Lue BaruTangutTai VietTenghwarTifinaghThaanaTirhutaTang"
        u8"saToto (txo)UgaritikUcapan TerlihatVithkuqiVarang KshitiWanchoWoleaiCuneiform Sumero-AkkadiaYezidiYi"
        u8"Zanabazar SquareWarisanNotasi MatematikaEmojiSimbolTidak TertulisUmumSkrip Tidak DikenalHan Sederhan"
        u8"aHan TradisionalDirham Uni Emirat ArabAfgani AfganistanLek AlbaniaDram ArmeniaKwanza AngolaPeso Arge"
        u8"ntinaDolar AustraliaFlorin ArubaManat AzerbaijanMark Konvertibel Bosnia-HerzegovinaDolar BarbadosTak"
        u8"a BangladeshLev BulgariaDinar BahrainFranc BurundiDolar BermudaDolar BruneiBolivianoReal BrasilDolar"
        u8" BahamaNgultrum BhutanPula BotswanaRubel BelarusiaDolar BelizeDolar KanadaFranc KongoFranc SwissPeso"
        u8" CileYuan TiongkokPeso KolombiaColon Kosta RikaPeso KubaEscudo Tanjung VerdeKoruna CekoFranc JibutiK"
        u8"rone DenmarkPeso DominikaDinar AljazairPound MesirNakfa EritreaBirr EtiopiaEuroDolar FijiPound Kepul"
        u8"auan FalklandPound InggrisLari GeorgiaCedi GhanaPound GibraltarDalasi GambiaFranc GuineaQuetzal Guat"
        u8"emalaDolar GuyanaDolar Hong KongLempira HondurasGourde HaitiForint HungariaRupiah IndonesiaShekel Ba"
        u8"ru IsraelRupee IndiaDinar IrakRial IranKrona IslandiaDolar JamaikaDinar YordaniaYen JepangShilling K"
        u8"enyaSom KirgizstanRiel KambojaFranc KomoroWon Korea UtaraWon Korea SelatanDinar KuwaitDolar Kepulaua"
        u8"n CaymanTenge KazakhstanKip LaosPound LebanonRupee Sri LankaDolar LiberiaLoti LesothoDinar LibyaDirh"
        u8"am MarokoLeu MoldovaAriary MadagaskarDenar MakedoniaKyat MyanmarTugrik MongoliaPataca MakauOuguiya M"
        u8"auritaniaRupee MauritiusRufiyaa MaladewaKwacha MalawiPeso MeksikoRinggit MalaysiaMetical MozambikDol"
        u8"ar NamibiaNaira NigeriaCordoba NikaraguaKrone NorwegiaRupee NepalDolar Selandia BaruRial OmanBalboa "
        u8"PanamaSol PeruKina Papua NuginiPeso FilipinaRupee PakistanZloty PolandiaGuarani ParaguayRial QatarLe"
        u8"u RumaniaDinar SerbiaRubel RusiaFranc RwandaRiyal Arab SaudiDolar Kepulauan SolomonRupee SeychellesP"
        u8"ound SudanKrona SwediaDolar SingapuraPound Saint HelenaLeone Sierra LeoneShilling SomaliaDolar Surin"
        u8"amePound Sudan SelatanDobra Sao Tome dan PrincipePound SuriahLilangeni SwazilandBaht ThailandSomoni "
        u8"TajikistanManat TurkmenistanDinar TunisiaPaʻanga TongaLira TurkiDolar Trinidad dan TobagoDolar Baru "
        u8"TaiwanShilling TanzaniaHryvnia UkrainaShilling UgandaDolar Amerika SerikatPeso UruguaySom Uzbekistan"
        u8"Bolivar VenezuelaDong VietnamVatu VanuatuTala SamoaFranc CFA Afrika TengahSilverEmasUnit Gabungan Er"
        u8"opaUnit Keuangan EropaSatuan Hitung Eropa (XBC)Satuan Hitung Eropa (XBD)Dolar Karibia TimurHak Khusu"
        u8"s MenggambarSatuan Mata Uang EropaFranc Gold PerancisFranc UIC PerancisFranc CFA Afrika BaratPalladi"
        u8"umFranc CFPPlatinumDana RINETKode Mata Uang PengujianMata Uang Tidak Dikenal(mata uang tidak dikenal"
        u8")Rial YamanRand Afrika SelatanKwacha ZambiaHonoluluWaktu Universal TerkoordinasiUTCKota Tidak Dikena"
        u8"lAnguilaWinaNikosiaPrahaKopenhagenAljirKairoWaktu Musim Panas InggrisAthenaGeorgia SelatanWaktu Stan"
        u8"dar IrlandiaYerusalemTeheranRomaEnderburyAktauAktobeKostanayKolomboKishinevRangoonMakauCiudad Juarez"
        u8"Bahia BanderasMeridaCancunMuskatWarsawaBeogradMoskwaGuadalkanalDamaskusKievBeulah, Dakota UtaraNew S"
        u8"alem, Dakota UtaraCenter, Dakota UtaraDumont d’UrvilleSt. BarthélemyAtikokanSt. John’sAsmaraChuukPoh"
        u8"npeiNuukIttoqqortoormiitKolkataSt. KittsSt. LuciaKathmanduAsunciónSt. HelenaSão ToméLower Prince’s Q"
        u8"uarterVincennes, IndianaPetersburg, IndianaTell City, IndianaKnox, IndianaWinamac, IndianaMarengo, I"
        u8"ndianaVevay, IndianaMonticello, KentuckySt. VincentSt. ThomasHo Chi MinhWaktu AcreWaktu Standar Acre"
        u8"Waktu Musim Panas AcreWaktu AfganistanWaktu Afrika TengahWaktu Afrika TimurWaktu Standar Afrika Sela"
        u8"tanWaktu Afrika BaratWaktu Standar Afrika BaratWaktu Musim Panas Afrika BaratWaktu AlaskaWaktu Stand"
        u8"ar AlaskaWaktu Musim Panas AlaskaAKTAKSTAKDTWaktu AlmatyWaktu Standar AlmatyWaktu Musim Panas Almaty"
        u8"Waktu AmazonWaktu Standar AmazonWaktu Musim Panas AmazonWaktu TengahWaktu Standar TengahWaktu Musim "
        u8"Panas TengahCTCSTCDTWaktu TimurWaktu Standar TimurWaktu Musim Panas TimurETESTEDTWaktu PegununganWak"
        u8"tu Standar PegununganWaktu Musim Panas PegununganMTMSTMDTWaktu PasifikWaktu Standar PasifikWaktu Mus"
        u8"im Panas PasifikPTPSTPDTWaktu AnadyrWaktu Standar AnadyrWaktu Musim Panas AnadyrWaktu ApiaWaktu Stan"
        u8"dar ApiaWaktu Musim Panas ApiaWaktu AqtauWaktu Standar AqtauWaktu Musim Panas AqtauWaktu AqtobeWaktu"
        u8" Standar AqtobeWaktu Musim Panas AqtobeWaktu ArabWaktu Standar ArabWaktu Musim Panas ArabWaktu Argen"
        u8"tinaWaktu Standar ArgentinaWaktu Musim Panas ArgentinaWaktu Argentina Bagian BaratWaktu Standar Arge"
        u8"ntina Bagian BaratWaktu Musim Panas Argentina Bagian BaratWaktu ArmeniaWaktu Standar ArmeniaWaktu Mu"
        u8"sim Panas ArmeniaWaktu AtlantikWaktu Standar AtlantikWaktu Musim Panas AtlantikATASTADTWaktu Tengah "
        u8"AustraliaWaktu Standar Tengah AustraliaWaktu Musim Panas Tengah AustraliaWaktu Barat Tengah Australi"
        u8"aWaktu Standar Barat Tengah AustraliaWaktu Musim Panas Barat Tengah AustraliaWaktu Timur AustraliaWa"
        u8"ktu Standar Timur AustraliaWaktu Musim Panas Timur AustraliaWaktu Barat AustraliaWaktu Standar Barat"
        u8" AustraliaWaktu Musim Panas Barat AustraliaWaktu AzerbaijanWaktu Standar AzerbaijanWaktu Musim Panas"
        u8" AzerbaijanWaktu AzoresWaktu Standar AzoresWaktu Musim Panas AzoresWaktu BangladeshWaktu Standar Ban"
        u8"gladeshWaktu Musim Panas BangladeshWaktu BhutanWaktu BoliviaWaktu BrasilWaktu Standar BrasilWaktu Mu"
        u8"sim Panas BrasilWaktu Brunei DarussalamWaktu Tanjung VerdeWaktu Standar Tanjung VerdeWaktu Musim Pan"
        u8"as Tanjung VerdeWaktu CaseyWaktu Standar ChamorroWaktu ChathamWaktu Standar ChathamWaktu Musim Panas"
        u8" ChathamWaktu CileWaktu Standar CileWaktu Musim Panas CileWaktu TiongkokWaktu Standar TiongkokWaktu "
        u8"Musim Panas TiongkokWaktu Pulau NatalWaktu Kepulauan CocosWaktu KolombiaWaktu Standar KolombiaWaktu "
        u8"Musim Panas KolombiaWaktu Kep. CookWaktu Standar Kep. CookWaktu Tengah Musim Panas Kep. CookWaktu Ku"
        u8"baWaktu Standar KubaWaktu Musim Panas KubaCT (Kuba)CST (Kuba)CDT (Kuba)Waktu DavisWaktu Dumont-d’Urv"
        u8"illeWaktu Timor LesteWaktu Pulau PaskahWaktu Standar Pulau PaskahWaktu Musim Panas Pulau PaskahWaktu"
        u8" EkuadorWaktu Eropa TengahWaktu Standar Eropa TengahWaktu Musim Panas Eropa TengahWaktu Eropa TimurW"
        u8"aktu Standar Eropa TimurWaktu Musim Panas Eropa TimurWaktu Eropa Timur JauhWaktu Eropa BaratWaktu St"
        u8"andar Eropa BaratWaktu Musim Panas Eropa BaratWaktu Kepulauan FalklandWaktu Standar Kepulauan Falkla"
        u8"ndWaktu Musim Panas Kepulauan FalklandWaktu FijiWaktu Standar FijiWaktu Musim Panas FijiWaktu Guyana"
        u8" PrancisWaktu Wilayah Selatan dan Antarktika PrancisWaktu GalapagosWaktu GambierWaktu GeorgiaWaktu S"
        u8"tandar GeorgiaWaktu Musim Panas GeorgiaWaktu Kep. GilbertGreenwich Mean TimeWaktu Greenland TimurWak"
        u8"tu Standar Greenland TimurWaktu Musim Panas Greenland TimurEGTEGSTEGDTWaktu Greenland BaratWaktu Sta"
        u8"ndar Greenland BaratWaktu Musim Panas Greenland BaratWaktu GuamWaktu Standar TelukWaktu GuyanaWaktu "
        u8"Hawaii-AleutianWaktu Standar Hawaii-AleutianWaktu Musim Panas Hawaii-AleutianHATHASTHADTWaktu Hong K"
        u8"ongWaktu Standar Hong KongWaktu Musim Panas Hong KongWaktu HovdWaktu Standar HovdWaktu Musim Panas H"
        u8"ovdWaktu IndiaWaktu Samudera HindiaWaktu IndochinaWaktu Indonesia TengahWITAWaktu Indonesia TimurWIT"
        u8"Waktu Indonesia BaratWIBWaktu IranWaktu Standar IranWaktu Musim Panas IranWaktu IrkutskWaktu Standar"
        u8" IrkutskWaktu Musim Panas IrkutskWaktu IsraelWaktu Standar IsraelWaktu Musim Panas IsraelWaktu Jepan"
        u8"gWaktu Standar JepangWaktu Musim Panas JepangWaktu Petropavlovsk-KamchatskyWaktu Standar Petropavlov"
        u8"sk-KamchatskyWaktu Musim Panas Petropavlovsk-KamchatskiWaktu KazakhstanWaktu Kazakhstan TimurWaktu K"
        u8"azakhstan BaratWaktu KoreaWaktu Standar KoreaWaktu Musim Panas KoreaWaktu KosraeWaktu KrasnoyarskWak"
        u8"tu Standar KrasnoyarskWaktu Musim Panas KrasnoyarskWaktu KirgizstanWaktu LankaWaktu Kep. LineWaktu L"
        u8"ord HoweWaktu Standar Lord HoweWaktu Musim Panas Lord HoweWaktu MakauWaktu Standar MakauWaktu Musim "
        u8"Panas MakauWaktu MagadanWaktu Standar MagadanWaktu Musim Panas MagadanWaktu MalaysiaWaktu MaladewaWa"
        u8"ktu MarquesasWaktu Kep. MarshallWaktu MauritiusWaktu Standar MauritiusWaktu Musim Panas MauritiusWak"
        u8"tu MawsonWaktu Pasifik MeksikoWaktu Standar Pasifik MeksikoWaktu Musim Panas Pasifik MeksikoWaktu Ul"
        u8"an BatorWaktu Standar Ulan BatorWaktu Musim Panas Ulan BatorWaktu MoskowWaktu Standar MoskowWaktu Mu"
        u8"sim Panas MoskowWaktu MyanmarWaktu NauruWaktu NepalWaktu Kaledonia BaruWaktu Standar Kaledonia BaruW"
        u8"aktu Musim Panas Kaledonia BaruWaktu Selandia BaruWaktu Standar Selandia BaruWaktu Musim Panas Selan"
        u8"dia BaruWaktu NewfoundlandWaktu Standar NewfoundlandWaktu Musim Panas NewfoundlandNTNSTNDTWaktu Niue"
        u8"Waktu Pulau NorfolkWaktu Standar Pulau NorfolkWaktu Musim Panas Pulau NorfolkWaktu Fernando de Noron"
        u8"haWaktu Standar Fernando de NoronhaWaktu Musim Panas Fernando de NoronhaWaktu Kep. Mariana UtaraWakt"
        u8"u NovosibirskWaktu Standar NovosibirskWaktu Musim Panas NovosibirskWaktu OmskWaktu Standar OmskWaktu"
        u8" Musim Panas OmskWaktu PakistanWaktu Standar PakistanWaktu Musim Panas PakistanWaktu PalauWaktu Papu"
        u8"a NuginiWaktu ParaguayWaktu Standar ParaguayWaktu Musim Panas ParaguayWaktu PeruWaktu Standar PeruWa"
        u8"ktu Musim Panas PeruWaktu FilipinaWaktu Standar FilipinaWaktu Musim Panas FilipinaWaktu Kepulauan Ph"
        u8"oenixWaktu Saint Pierre dan MiquelonWaktu Standar Saint Pierre dan MiquelonWaktu Musim Panas Saint P"
        u8"ierre dan MiquelonPMTPMSTPMDTWaktu PitcairnWaktu PonapeWaktu PyongyangWaktu QyzylordaWaktu Standar Q"
        u8"yzylordaWaktu Musim Panas QyzylordaWaktu ReunionWaktu RotheraWaktu SakhalinWaktu Standar SakhalinWak"
        u8"tu Musim Panas SakhalinWaktu SamaraWaktu Standar SamaraWaktu Musim Panas SamaraWaktu SamoaWaktu Stan"
        u8"dar SamoaWaktu Musim Panas SamoaWaktu SeychellesWaktu Standar SingapuraWaktu Kepulauan SolomonWaktu "
        u8"Georgia SelatanWaktu SurinameWaktu SyowaWaktu TahitiWaktu TaipeiWaktu Standar TaipeiWaktu Musim Pana"
        u8"s TaipeiWaktu TajikistanWaktu TokelauWaktu TongaWaktu Standar TongaWaktu Musim Panas TongaWaktu Chuu"
        u8"kWaktu TurkmenistanWaktu Standar TurkmenistanWaktu Musim Panas TurkmenistanWaktu TuvaluWaktu Uruguay"
        u8"Waktu Standar UruguayWaktu Musim Panas UruguayWaktu UzbekistanWaktu Standar UzbekistanWaktu Musim Pa"
        u8"nas UzbekistanWaktu VanuatuWaktu Standar VanuatuWaktu Musim Panas VanuatuWaktu VenezuelaWaktu Vladiv"
        u8"ostokWaktu Standar VladivostokWaktu Musim Panas VladivostokWaktu VolgogradWaktu Standar VolgogradWak"
        u8"tu Musim Panas VolgogradWaktu VostokWaktu Kepulauan WakeWaktu Wallis dan FutunaWaktu YakutskWaktu St"
        u8"andar YakutskWaktu Musim Panas YakutskWaktu YekaterinburgWaktu Standar YekaterinburgWaktu Musim Pana"
        u8"s YekaterinburgWaktu Yukon{0} ({1}){0}, {1}Waktu {0}Waktu Standar {0}Waktu Musim Panas {0}{1} ({0}){"
        u8"0} {1}";
    inline constexpr const char8_t* NameChunks[] = {NameChunk0};
    inline constexpr uint16_t NameChunkSizes[] = {19035};
    inline constexpr char NameRefsChunk0[] =
        "AAAAAAAAAAAEAAAKAAAOAAATAAAaAAAgAAAmAAAyAAA7AABDAABIAABMAABQAABXAABeAABjAABwAAB3AAB9AACJAACOAACUAACY"
        "AACrAACvAAC2AAC9AADKAADUAADaAADlAADvAAD0AAD3AAENAAEUAAEdAAEhAAEnAAEtAAE4AAE/AAFGAAFKAAFRAAFVAAFaAAFk"
        "AAFrAAF0AAF4AAF9AAGDAAGHAAGMAAGUAAGcAAGpAAGxAAG4AAG9AAHBAAHHAAHKAAHRAAHVAAHcAAHjAAHoAAHuAAHyAAH2AAH8"
        "AAICAAIIAAINAAIRAAIVAAIcAAIjAAInAAIuAAI0AAI5AAI/AAJGAAJNAAJRAAJZAAJgAAJoAAJuAAJyAAKAAAKGAAKPAAKXAAKf"
        "AAKrAAK0AAK7AALBAALFAALLAALXAALoAAL0AAMDAAMNAAMgAAM1AAM5AANBAANKAANgAANnAANsAANxAAN3AAN9AAOCAAOIAAOd"
        "AAOlAAOqAAOwAAO1AAO6AAO/AAPLAAPQAAPoAAPuAAP4AAP9AAQFAAQLAAQPAAQSAAQWAAQgAAQmAAQsAAQwAAQ3AARJAARhAARq"
        "AARxAASAAASHAASNAASTAASZAASkAASoAAStAASxAAS2AAS+AATCAATHAATKAATRAATeAAT2AAUCAAUJAAUVAAUhAAUnAAUzAAU7"
        "AAU9AAVDAAVHAAVMAAVdAAVhAAVoAAVvAAV1AAWMAAWTAAWeAAWjAAWsAAWxAAW2AAXBAAXPAAXWAAXbAAXfAAXpAAXuAAXzAAX5"
        "AAYGAAYMAAYRAAYbAAYlAAYqAAYvAAY4AAY/AAZKAAZVAAZdAAZhAAZrAAZyAAZ4AAaDAAaHAAaNAAaWAAahAAalAAavAAa2AAbM"
        "AAbRAAbbAAbeAAbmAAbsAAb1AAb7AAcBAAcHAAcOAAcbAAcmAAcqAAcxAAc8AAdCAAdIAAdLAAdQAAdUAAdbAAdiAAdmAAdtAAd5"
        "AAeAAAeEAAeJAAeRAAeWAAecAAeoAAeuAAe2AAe8AAfAAAfLAAfTAAfYAAfgAAfnAAfsAAf4AAf/AAgEAAgKAAgQAAgfAAgjAAgq"
        "AAgvAAg2AAg+AAhDAAhQAAhVAAhaAAhhAAhlAAhsAAh2AAh6AAiAAAiFAAiLAAiQAAiWAAibAAilAAisAAixAAi6AAjBAAjJAAjP"
        "AAjWAAjdAAjgAAjlAAj0AAj4AAkCAAkIAAkQAAkcAAkmAAktAAkyAAk1AAk5AAk+AAlEAAlHAAlNAAlRAAlXAAlfAAlmAAluAAlz"
        "AAl3AAl9AAmDAAmIAAmMAAmUAAmcAAm1AAnDAAnKAAnSAAnXAAndAAnoAAnxAAn6AAoCAAoLAAoTAAodAAojAAooAAovAAo1AAo6"
        "AApBAApQAApfAApmAAptAAp1AAp6AAp/AAqEAAqPAAqUAAqeAAqiAAqyAAq/AArMAArSAArYAAreAAriAArnAAruAAr0AAsEAAsN"
        "AAsVAAsaAAskAAsqAAs5AAtEAAtIAAtOAAtbAAthAAtpAAtxAAt2AAt7AAuDAAuJAAuaAAunAAuvAAu7AAvDAAvIAAvNAAvUAAvZ"
        "AAvlAAvsAAv1AAv8AAwEAAwOAAwTAAwhAAw0AAw/AAxGAAxKAAxPAAxVAAxdAAxzAAx5AAyHAAyNAAyVAAylAAysAAy1AAy/AAzG"
        "AAzPAAzXAAzhAAzmAAztAAz1AAz6AA0AAA0GAA0LAA0TAA0eAA0hAA0qAA0xAA02AA1CAA1JAA1OAA1VAA1cAA1hAA1pAA1wAA16"
        "AA2AAA2NAA2XAA2dAA2hAA2lAA2rAA26AA2/AA3MAA3ZAA3iAA3mAA3vAA32AA38AA4CAA4KAA4dAA4rAA4yAA43AA5DAA5MAA5W"
        "AA5gAA5lAA5sAA5zAA56AA6BAA6HAA6TAA6YAA6dAA6hAA6uAA66AA6/AA7FAA7JAA7QAA7WAA7dAA7sAA7zAA8AAA8GAA8NAA8S"
        "AA8iAA8mAA8sAA8xAA81AA87AA9AAA9FAA9LAA9PAA9WAA9eAA9jAA9mAA9tAA90AA97AA+CAA+JAA+RAA+XAA+cAA+nAA+wAA+5"
        "AA++AA/EAA/KAA/QAA/YAA/dAA/rAA/1AA/8ABACABAFABAMABASABAZABAwABA2ABA8ABBCABBJABBQABBkABBoABBtABBwABB1"
        "ABB8ABCDABCKABCRABCWABCbABCiABCoABCuABCzABC4ABDAABDFABDQABDWABDbABDhABDlABDoABDuABD1ABD6ABEBABEHABEQ"
        "ABEWABEcABEjABEtABEzABFLABFTABFXABFbABF2ABF6ABF/ABGFABGSABGhABGoABG7ABHJABHcABHvABIDABIYABIfABIzABJE"
        "ABJVABJoABJ1ABKJABKUABKdABKvABK4ABK8ABLHABLYABLdABLvABMBABMTABMkABMxABNAABNHABNWABNgABNzABN7ABOBABOL"
        "ABOUABOhABOoABOxABO2ABPFABPPABPlABPtABP3ABP9ABQJABQQABQXABQcABQtABQ0ABQ6ABRBABRQABRWABRcABRiABRuABR2"
        "ABR9ABSDABSJABSiABSyABTIABTbABTgABTwABT+ABUCABUJABURABUZABUpABUzABU3ABVEABVMABVXABVdABVpABVvABV2ABV+"
        "ABWPABWXABWoABWvABW0ABXAABXHABXOABXXABXgABXpABX7ABYFABYUABYZABYlABYsABY6ABZCABZHABZQABZZABZfABZlABZv"
        "ABaAABanABawABa0ABbBABbHABbdABb/ABcHABcMABcdABcjABcsABcxABdSABdWABdaABdgABdnABdvABd0ABd+ABeFABeNABeT"
        "ABeoABezABfAABfGABfWABfgABfkABfrABf2ABgDABgMABgTABgaABgfABglABgrABgyABg8ABhIABhSABhkABhzABh3ABiGABiY"
        "ABivABi3ABjBABjLABjUABjcABjiABjpABjxABj5ABkAABkOABkTABkkABkrABk0ABk5ABk9ABlKABlOABlUABlYABlpABl1ABl9"
        "ABmFABmNABmmABm4ABnDABnUABncABnkABnpABn1ABn9ABoDABoNABoeABooABotABo2ABpCABpiABpqABp2ABqAABqHABqPABqc"
        "ABqxABq8ABrIABrQABrgABr6ABr+ABsVABsZABshABsrABs2ABtCABtJABtcABtiABtqABtwABuEABueAButABu0ABu+ABvFABvg"
        "ABvpABwHABwnABwuABxJABxUABxfABxlABxqABxxABx/AByFAByNAByiABynABysABy8ABzEABzRABzWABzfABzkABztABz1ABz7"
        "AB0CAB0HAB0mAB0rAB01AB06AB1GAB1NAB1pAB1zAB1+AB2DAB2KAB2dAB2qAB24AB3HAB3OAB3VAB3mAB3wAB39AB4KAB4QAB4X"
        "AB4fAB4yAB44AB47AB5CAB5LAB5WAB5cAB5kAB52AB6CAB6YAB6uAB67AB7AAB7LAB7SAB7aAB7iAB7sAB7yAB8EAB8KAB8PAB8c"
        "AB8oAB8uAB8zAB87AB9DAB9JAB9NAB9SAB9XAB9fAB9nAB9tAB91AB98AB+KAB+VAB+kAB+sAB+wAB+zAB+/AB/GAB/NAB/YAB/n"
        "AB/vAB/4AB/9ACACACAMACASACAZACAkACArACA2ACBBACBJACBXACBkACBrACB6ACCKACCQACCWACCcACCmACCrACCyACC4ACDJ"
        "ACDTACDiACDoACDvACD2ACD/ACEGACESACEeACElACExACFCACFOACFaACFiACFnACFtACF5ACF/ACGHACGPACGXACGdACGkACGq"
        "ACG0ACG8ACHLACHTACHgACHmACHsACIEACIKACIMACIcACIjACI0ACI5ACI/ACJNACJRACJkACJxACKAACKWACKnACKyACK+ACLL"
        "ACLZACLoACL0ACMEACMnACM1ACNEACNQACNdACNqACN3ACODACOMACOXACOjACOyACO/ACPOACPaACPmACPxACP8ACQFACQSACQf"
        "ACQvACQ4ACRMACRXACRjACRwACR9ACSLACSWACSjACSvACSzACS9ACTVACTiACTuACT4ACUHACUUACUgACUxACU9ACVMACVcACVo"
        "ACV3ACWHACWZACWkACWuACW3ACXFACXSACXgACXqACX4ACYGACYSACYeACYtACY+ACZKACZgACZwACZ4ACaFACaUACahACatACa4"
        "ACbFACbQACbhACbwACb8ACcLACcXACcpACc4ACdIACdVACdhACdxACeBACeOACebACesACe6ACfFACfYACfhACfuACf2ACgHACgU"
        "ACgiACgwAChAAChKAChVAChhAChsACh4ACiIACifACivACi6ACjGACjVACjnACj5ACkJACkXACkqAClFAClRAClkAClxACmCACmU"
        "ACmhACmvACm5ACnSACnjACn0ACoDACoSAConACozACpBACpSACpeACpqACp0ACqLACqRACqVACqoACq7ACrUACrtACsAACsVACsr"
        "ACs+ACtQACtmACtvACt4ACuAACuKACuiACu5ACvSACvcACvvACv8ACwEACwhACwkACw2ACw9ACxBACxIACxNACxXACxcACxhACx6"
        "ACyAACyPACylACyuACy1ACy5ACzCACzHACzNACzVACzcACzkACzrACzwACz9AC0LAC0RAC0XAC0dAC0kAC0rAC0xAC08AC1EAC1I"
        "AC1cAC1zAC2HAC2ZAC2oAC2wAC28AC3CAC3HAC3OAC3SAC3iAC3pAC3yAC37AC4EAC4NAC4XAC4hAC45AC5LAC5eAC5wAC59AC6N"
        "AC6dAC6rAC6/AC7KAC7UAC7fAC7pAC77AC8RAC8hAC80AC9GAC9iAC90AC+OAC+sAC+4AC/MAC/kAC/nAC/rAC/vAC/7ADAPADAn"
        "ADAzADBHADBfADBrADB/ADCXADCZADCcADCfADCqADC9ADDUADDWADDZADDcADDsADEEADEgADEiADElADEoADE1ADFKADFjADFl"
        "ADFoADFrADF3ADGLADGjADGtADG/ADHVADHgADHzADIKADIWADIqADJCADJMADJeADJ0ADKDADKaADK1ADLRADL1ADMdADMqADM/"
        "ADNYADNmADN8ADOWADOYADObADOeADO0ADPSADP0ADQQADQ0ADRcADRxADSOADSvADTEADThADUCADUSADUqADVGADVSADVmADV+"
        "ADWOADWmADXCADXOADXbADXnADX7ADYTADYqADY9ADZYADZ3ADaCADaYADalADa6ADbTADbdADbvADcFADcTADcpADdDADdUADdp"
        "ADd3ADeNADenADe2ADfNADfvADf5ADgLADghADgqADg0ADg+ADhJADhhADhyADiEADieADi8ADjJADjbADj1ADkTADkkADk9ADla"
        "ADlwADmBADmaADm3ADnPADnvADoTADodADovADpFADpZADqFADqUADqhADquADrDADrcADruADsBADsWADszADtUADtXADtbADtf"
        "ADt0ADuRADuyADu8ADvPADvbADvwADwNADwuADwxADw1ADw5ADxIADxfADx6ADyEADyWADysADy3ADzMADzbADzxADz1AD0KAD0N"
        "AD0iAD0lAD0vAD1BAD1XAD1kAD15AD2SAD2eAD2yAD3KAD3WAD3qAD4CAD4gAD5GAD5wAD6AAD6WAD6sAD63AD7KAD7hAD7tAD7+"
        "AD8XAD80AD9EAD9PAD9eAD9tAD+EAD+fAD+qAD+9AD/UAD/hAD/2AEAPAEAdAEArAEA6AEBNAEBcAEBzAECOAECaAECvAEDMAEDt"
        "AED9AEEVAEExAEE9AEFRAEFpAEF2AEGBAEGMAEGgAEG8AEHcAEHvAEIKAEIpAEI7AEJVAEJzAEJ1AEJ4AEJ7AEKFAEKYAEKzAELS"
        "AELrAEMMAEMxAENJAENaAENzAEOQAEOaAEOsAEPCAEPQAEPmAEQAAEQLAEQdAEQrAERBAERbAERlAER3AESNAESbAESxAETLAETi"
        "AEUBAEUoAEVTAEVWAEVaAEVeAEVsAEV4AEWHAEWWAEWtAEXIAEXVAEXiAEXwAEYGAEYgAEYsAEZAAEZYAEZjAEZ2AEaNAEadAEa0"
        "AEbLAEbgAEbuAEb5AEcFAEcRAEclAEc9AEdNAEdaAEdlAEd4AEePAEeaAEesAEfGAEfkAEfwAEf9AEgSAEgrAEg7AEhTAEhvAEh8"
        "AEiRAEiqAEi5AEjKAEjjAEkAAEkPAEkmAElBAElNAElhAEl4AEmFAEmaAEmzAEnGAEnhAEoAAEoLAEoUAEocAEolAEo2AEpLAEpU"
        "AEpb";
    inline constexpr const char* NameRefsChunks[] = {NameRefsChunk0};
    inline constexpr Packed NameRefs{NameRefsChunks, 13, 4};
    inline constexpr Text NameTexts{NameChunks, NameChunkSizes, NameRefs};

    inline constexpr char LanguageKeysChunk0[] =
        "AAhAAiAAlAAmAArAAtAAuAAyAAzAA2AA5AA6ABBABFABHABJABNABOABPABSABTABhABlABoABvAByABzAB1AB2AB5ACBACFACWA"
        "CaAClACsACuACvACzAC0AC1ADBADGADJADKADPADSADZADhADkADsADuAD1AD2AEBAEFAEJAEPAESAEUAEVAEZAEaAEhAEkAElAE"
        "nAEpAErAEvAEzAE0AE1AFBAFWAFhAFnAFpAFqAFrAFsAFtAFuAFvAFyAFzAF1AF2AF3AF5AGBAGCAGHAGJAGOAGPAGUAGVAGWAGn"
        "AGoAGpAGrAGsAGuAGyAGzAG0AG5AHBAHCAHEAHFAHHAHMAHOAHPAHSAHWAHZAHjAHqAHtAHyAHzAIBAIJAIMAITAIUAI1AJNAJOA"
        "JPAJVAJXAJhAJjAJkAJlAJnAJoAJpAJrAJsAJtAJuAJvAJxAJyAJzAJ0AJ1AJ2AJ3AKBAKFAKHAKIAKJAKLAKMAKOAKPAKSAKTAK"
        "UAKXAKZAKnAKrAKyAK6ALFALJALPALhALvAMIAMpAMvANBANIANVARlARoASBASZASiATIATxAUuAVrAV6AWFAWUAXHAXOAXQAZD"
        "AZOAZQAZRAZTAZXAZZAZaAZhAZlAZ0AaKAbhAgsAguAgyAgzAg4AhDAhKAiqAitAi3Ai6AjEAjjAjuAkPAkrAkuAlOAltAmBAmPA"
        "pBApYApzAqhAqnAqtAsuAs2AwkAwyAw5AxoAxwAyiAznA0CA0HA0LA0NA0OA0PA0QA0SA0ZA1iA2DA3wA5HA5IA5KA5LA5MA5NA5"
        "SA5TA5iA53BArBAyBA2BCsBCuBDyBEuBFFBHpBJiBKhBKtBMvBM1BNHBRVBTJBT5BVhBWYBXNBbvBguBg0BksBnuBpDBpNBpPBpQ"
        "BpSBpTBqyBwhBwnBw5BxBBy6B0sB2LB2oB3oB3uB3yB30B5CB5DB53B66B7pCApCA3CA4CEmCEsCE0CGuCJiCKwCKyCRBCRCCV0C"
        "WPCXIChPCjvCmjCoSCpCCwhCwiCwjCwqCwtCw3CxECxMCxnCyFCyhCyuCzPCzwC0BC0PC0RC1qC2OC2iC3pC3rC3zC4FC5DC5JC5"
        "MC5VC5iC5mC5oC6tC60C7rC8WDAkDAnDAoDAtDC6DEqDEsDF0DGvDHsDH1DH6DJDDJtDKhDKpDKuDKvDKzDK5DNaDQkDQmDQnDQp"
        "DQrDQuDQzDSFDSGDSSDSuDSyDTFDThDToDTvDUjDUuDXDDXJDXlDXoDXzDahDasDazDbsDbyDb2DclDc2DdODgwDgxDiTDi3DkhD"
        "k1DmnDnIDnnDnuDovDpvDqzDrjDstDsuDsvDtJD1CD1DD1TD1XD1hD5hD6BEAnEAsEAtEAwEA1EBtECDECvEEOEEzEHuEItEJHEJ"
        "PEajEgqEgwEgyEkHEnmEntEqNEqwErrEwkEwoEwtEwxEwzEw0ExBExQExuExvEyIEylEyoEypEysEyzEzhE0JE0OE0VE0kE2IE2J"
        "E2ZE2hE2qE2uE2zE3LE3nE5OE5SE55E6SE6rE6zE64E7iE8jE8yE9MFBlFB5FCtFCvFCyFC0FD4FEUFEnFE2FFsFGIFGJFGoFHnF"
        "HrFIJFJVFJWFJpFKNFKUFKtFLMFLxFM2FNNFSNFThFWiFXEFgpFijFm3Fn0FquFwlFwsFwyFwzFxQF61GAsGHSGHnGQvGQwGQ2GR"
        "CGZMGalGgwGhMGiuGjoGquGsYGtB";
    inline constexpr const char* LanguageKeysChunks[] = {LanguageKeysChunk0};
    inline constexpr Packed LanguageKeys{LanguageKeysChunks, 13, 3};

    inline constexpr char LanguageNamesChunk0[] =
        "AABAACAAHAAJAANAASAATAAXAAhAAmAAoAApAAqAAyAA4AA8ABDABEABFABGABJABQABWABZABlABnABwABzAB0AB1AB2AB6ACFA"
        "CIACLACPACRACUACVACXACYACaACeACfAChACiACkACsACtACyAC1AC4ADAADCADEADIADJADOADPADRADSADVADWADXADaADbAD"
        "cADdADeADiADjADkADlADmADsADtAD7AEAAEBAECAEEAEGAEIAEJAEOAETAEXAEaAEbAEeAEfAEkAEmAEnAEsAEtAEzAE0AE7AFK"
        "AFOAFPAFSAFTAFUAFaAFbAFcAFjAFnAFqAFrAFtAFvAFyAF0AF2AF6AF9AF/AGEAGFAGLAGMAGNAGQAGaAGcAGhAGiAGkAGqAGrA"
        "GsAGxAGzAG1AG+AHBAHDAHJAHLAHPAHRAHSAHWAHbAHdAHfAHgAHjAHlAHnAHrAHsAHyAH1AH6AH8AH+AIBAIDAIHAIIAIMAIPAI"
        "RAIWAIYAIcAIeAIhAIiAIkAImAIoAIrAIxAI0AI7AI8AI/AJEAJFAADAAEAAFAAGAAIAAKAALAAMAAOAAPAAQAARAAUAAVAAWAAZ"
        "AAaAAbAAcAAdAAeAAfAAgAAiAAjAAkAAlAAnAArAAsAAtAAuAAvAAwAAxAAzAA0AA1AA2AA3AA5AA6AA7AA9AA+AA/ABAABBABCA"
        "BHABIABKABLABMABNABOABPABRABSABTABUABVABXABYABaABbABcABdABeABfABgABhABiABjABkABmABoABpABqABrABsABtAB"
        "uABvABxAByAB3AB4AB5AB8AB9AB+AB/ACAACBACCACDACEACGACHACJACKACMACNACOACQACTACZACcACdACgACjAClACmACnACo"
        "ACpACqACrACuACvACwACxACzAC0AC2AC3AC5AC6AC7AC8AC9AC+AC/ADBADDADFADGADHADKADLADMADNADQADTADUADYADZADfA"
        "DgADhADnADoADpADqADrADuADvADwADxADyADzAD0AD1AD2AD3AD4AD5AD6AD8AD9AD+AD/AEDAEFAEHAEKAELAEMAENAEPAEQAE"
        "RAESAEUAEVAEWAEYAEZAEcAEdAEgAEhAEiAEjAElAEoAEpAEqAErAEuAEvAEwAExAEyAE1AE2AE3AE4AE5AE6AE8AE9AE+AE/AFA"
        "AFBAFCAFDAFEAFFAFGAFHAFIAFJAFLAFMAFNAFQAFRAFVAFWAFXAFYAFZAFdAFeAFfAFgAFhAFiAFkAFlAFmAFoAFpAFsAFuAFwA"
        "FxAFzAF1AF3AF4AF5AF7AF8AF+AGAAGBAGCAGDAGGAGHAGIAGJAGKAGOAGPAGRAGSAGTAGUAGVAGWAGXAGYAGZAGbAGdAGeAGfAG"
        "gAGlAGmAGnAGoAGpAGuAGvAGwAGyAG0AG2AG3AG4AG5AG6AG7AG8AG9AG/AHAAHCAHEAHFAHGAHHAHIAHKAHMAHNAHOAHQAHTAHU"
        "AHVAHXAHYAHZAHaAHcAHeAHhAHiAHkAHmAHoAHpAHqAHuAHvAHwAHxAHzAH0AH2AH3AH4AH5AH7AH9AH/AIAAICAIEAIFAIGAIJA"
        "IKAILAINAIOAIQAISAITAIUAIVAIXAIZAIaAIbAIdAIfAIgAIjAIlAInAIpAIqAIsAItAIuAIvAIwAIyAIzAI1AI2AI3AI4AI5AI"
        "6AI9AI+AJAAJBAJCAJDAJGAJHAJI";
    inline constexpr const char* LanguageNamesChunks[] = {LanguageNamesChunk0};
    inline constexpr Packed LanguageNames{LanguageNamesChunks, 13, 3};

    inline constexpr const uint64_t* TaggedKeys = nullptr;

    inline constexpr const uint16_t* TaggedNames = nullptr;

    inline constexpr char RegionKeysChunk0[] =
        "AAeAAfAAgAAhAAiAAkAAnAAoAAqAAsAAtAAuAAvAAwAAyAAzAA1AA3AA4AA6AA7AA8AA9AA+AA/ABAABCABDABEABFABHABIABJA"
        "BKABMABNABPABQABSABUABVABXABYABZABaABcABdABeABfABgABhABjABmABnABoABpABqABrABxABzAB2AB3AB5AB7ACGACIAC"
        "KACMACOACPACZACaACbACcAChACrACsACtACvACxAC0AC+AC/ADBADCADDADEADFADGADJADKADLADNADOADPADQADRADSADUADW"
        "ADjADlADmADqADsADtAD2AD3AD4AD/AEAAEBAECAEEAEFAEGAEHAETAEbAEdAEeAEuAEwAExAEyAE2AE3AE5AE7AFAAFCAFDAFFA"
        "FGAFHAFNAFPAFWAFXAFYAFZAFaAFdAFgAFiAFjAFkAFlAFmAFnAFqAFrAFsAFtAFuAFvAFwAFxAFyAFzAF0AF1AF2AF3AF4AF5AF"
        "7AF9AF/AGAAGBAGDAGGAGJAGKAGMAGPAGUAGiAGxAG1AG2AG3AG4AG7AG8AG9AG+AHCAHDAHEAHHAHJAHMAHaAHrAH1AH5AH7AH9"
        "AICAIDAIEAIFAIGAIIAIJAIKAILAIMAINAIOAIPAIQAITAIUAIVAIXAIZAIaAIbAIdAIfAIgAIiAIjAIkAImAInAIoAIpAIqAIrA"
        "IuAIwAIyAIzAI2AI4AI+AJEAJFAJKAJQAJRAJTAJVAJXAJZAJbAJgAJnAJzAKAAKJAKKAKTAKoAK3AK/ALLALVALYALaALbALcAL"
        "eALiALkALmALnALoALqALrALsALuAL2AL3AL7AL8AMAAMOAMPAMSAMWANnANoANqANvANwANzAN0AOjAR8";
    inline constexpr const char* RegionKeysChunks[] = {RegionKeysChunk0};
    inline constexpr Packed RegionKeys{RegionKeysChunks, 13, 3};

    inline constexpr char RegionNamesChunk0[] =
        "AJoAJpAJqAJrAJsAJtAHfADVAJuAJvAJwAJxAJyAJzAJ0AJ1AJ2AJ3AJ4AJ5AJ6AJ7AA4AJ8AJ9AJ+AJ/AKAAKBAKCAKDAKEAKFA"
        "KGAKHAKIAKJAKKAKLAKMAKNAKOAKPAKQAKRAKSAKTAKUAKVAKWAKXAKYAKZAKaAKbAKcAKdABwAB6AKeAKfAKgAKhAKiAKjAKkAK"
        "lACXAKmAKnAKoACVAKpAKqAKrAKsAChAKtAKuAKvACkAKwAKxAKyADtAKzAK0AK1AK2AK3AK4AK5AK6AK7ACPAK8AK9AK+AK/ALA"
        "ALBALCALDADPALEADSALFADaACtALGALHALIALJALKALLADjADkALMALNALOADmALPALQALRALSALTALUALVALWALXALYALZALaA"
        "LbALcALdALeALfALgAEzAEkAE7ALhALiALjALkALlALmALnALoALpALqALrAFUALsALtALuALvALwAFcALxALyALzAL0AL1AL2AL"
        "3AL4AL5AL6AL7AL8AFyAF2AL9AFnAL+AL/AMAAMBAMCAMDAMEAMFAMGAMHAMIAMJAMKAMLAMMAGVAMNAMOAMPAMQAGsAHgAGxAMR"
        "AMSAMTAMUAMVAHrAMWAMXAHSAMYAMZAMaAMbAMcAHdAMdAMeAMfAMgAMhAHwAMiAMjAMkAMlAMmAMnAMoAMpAICAMqAMrAMsAIIA"
        "IMAMtAIVAMuAMvAIeAMwAMxAMyAMzAM0AM1AM2AM3AM4AM5AM6AImAM7AM8AHWAM9AM+AM/ANAANBANCANDANEANFAJJAJKAJLAJ"
        "MAJNAJOAJPAJQAJRAJSAJTAJUAJVAJWAJXAJYAJZAJaAJbAJcAJdAJeAJfAJgAJhAJiAJjAJkAJlAJmAJn";
    inline constexpr const char* RegionNamesChunks[] = {RegionNamesChunk0};
    inline constexpr Packed RegionNames{RegionNamesChunks, 13, 3};

    inline constexpr char ScriptKeysChunk0[] =
        "AJGNAJgrAJ0CAMguAMmpAMmuANp0AQW1AQZzAQaLARXHASFzATEzAT4PAUgoAUgpAVTpAVUEAYVtAYXTAYZJAaCyAaJTAaZUAb4U"
        "AcGuAcJUAeZMAeZTAhbBAiQrAjzyAk5UAlYMAp8kAp8oAp8wArBBArMtAtEJA5XrA5XyA7AnA73HA73NA76IA8guA8irA9VSA9ZV"
        "BAXCBAXHBAXJBAXPBAXTBAXUBAaSBBRSBCZBBDK3BDXHBDXQBEl0BFXHBLiTBNAsBQbBBUAuBVZDBYWJBYXBBaAyBaGyBaHqBaaT"
        "BbiBBb5FBcCsBdEJBgXBBgXvBgaGBgaHBgaOBhYDBiWiBiXBBiXCBiZ1Bj2hBmRpBmSJBoUKBoVhBoXEBoXJBoZDBochBpSGBpXE"
        "BpZDBpZPBrMtBr3HBr3uBsnvBtCpBtWUBuWyBwXEBwZCBwg0ByziBy3vB00VB5wtB7BrB8loB8shB8zlB82hB9TyCAWNCAajCBZN"
        "CCAnCCGJCCGQCCGWCCHYCDJECEqJCIQnCSnHCT0HCT5PCVXSCYWyCYZBCYZCCYayCZ3XCaA3CaJECaSECaXECaXICbzkCbzvCb5B"
        "Cb8vCdXECeWPCeZDCeZFCeZKCeZOCgTiCgVyCgWFCgWVCgWsCgXHCgbUChWVChXHChnHCh2HCiAhCiRUCiZICjphCj6PCpwyCwUp"
        "CyZwCyaIC4ZBC40PC72FDECvDE64DJdJDKUpDQXCDSXIDTaIDU8lDU8tDWMYDWc5DWta";
    inline constexpr const char* ScriptKeysChunks[] = {ScriptKeysChunk0};
    inline constexpr Packed ScriptKeys{ScriptKeysChunks, 13, 4};

    inline constexpr char ScriptNamesChunk0[] =
        "ANGANHANIANJANKADVAAHANLANMANNABEANOAJBANPANQANRABMANSABVANTANUABhANVANWABmANXAKdANYANZANaANbANcANdA"
        "NeANfANgANhANiANjAKpANkADtANlANmANnANoANpACPADAANqANrANsANtANuANvANwANxADIANyANzAN0AN1AN2AN3AN4AN5AD"
        "sADmAN6AN7AN8AN9AEGAN+AN/AEIAEJAENAOAAOBALaAOCAODAEfAOEAOFAOGAOHAOIAOJAOKAOLAOMAONAOOAOPAOQAORAOSAFH"
        "AOTAOUAFTAFUAOVAOWAOXAOYAOZAOaAObAOcAOdAF5AOeAOfAOgAOhAGMAGOAOiAOjAOkAOlAOmAOnAGSAOoAOpAOqAOrAOsAOtA"
        "OuAOvAOwAOxAOyAOzAO0AO1AO2AO3AO4AO5AO6AHPAO7AO8AO9AO+AHnAO/AHwAPAAPBAPCAPDAPEAPFAPGAHyAPHAPIAH1APJAP"
        "KAIDAPLABFAPMAPNAPOAPPAIjAPQAPRAPSAPTAPUAGYAPVAPWAPXAPYAPZAPaAPbAPcAPdAPeAPf";
    inline constexpr const char* ScriptNamesChunks[] = {ScriptNamesChunk0};
    inline constexpr Packed ScriptNames{ScriptNamesChunks, 13, 3};

    inline constexpr char AloneKeysChunk0[] =
        "BAXTBAXU";
    inline constexpr const char* AloneKeysChunks[] = {AloneKeysChunk0};
    inline constexpr Packed AloneKeys{AloneKeysChunks, 13, 4};

    inline constexpr char AloneNamesChunk0[] =
        "APgAPh";
    inline constexpr const char* AloneNamesChunks[] = {AloneNamesChunk0};
    inline constexpr Packed AloneNames{AloneNamesChunks, 13, 3};

    inline constexpr char CurrencyKeysChunk0[] =
        "ASkATOAWMAWkAXhAZTAakAbnAdOAgtAhEAiUAjuAkEAkmAmkAnEAniApMApkAqOArwAsuAtEAwkAyGA0GA2QA3ZA3wA5DA6wA7FA"
        "9LBFGBFrBHwBNEBTwBZOBaCBayBlEBlwBxQBysB0TB0wB2kB3GB6RB8kCFkCHMCKHCKmCSSCWTCXSCYkCZSCZrCmkCnkCoZCyzCz"
        "zC0SC2mC4XC5XC7kC8kC9UDArDBQDFyDJEDJsDMkDQkDSMDThDVkDWrDXUDXwDZVDayDbSDbrDcODcyDdODgkDjuDkvDnrDoSDtE"
        "D2yEAiECuEDrEEQEFyEGOEMnEQyEnuEpkEqiErmEwyExEExyEyHEyrEzkE0QE2FE3zE5EE5wE6OE8wE9MFECFFTFG0FHEFHwFJZF"
        "KEFLkFNTFQoFT4FZkFc1FdTFizFnEFq2F50GAmGAnGA1GBBGBCGBDGBEGBkGCSGC1GDPGDVGHmGIEGIGGIUGJFGKTGMYGSyGgyGm"
        "3";
    inline constexpr const char* CurrencyKeysChunks[] = {CurrencyKeysChunk0};
    inline constexpr Packed CurrencyKeys{CurrencyKeysChunks, 13, 3};

    inline constexpr char CurrencyNamesChunk0[] =
        "APiAAAAAAAAAAAAAAAAAAAPjAAAAAAAAAAAAAAAAAAAPkAAAAAAAAAAAAAAAAAAAPlAAAAAAAAAAAAAAAAAAAPmAAAAAAAAAAAAA"
        "AAAAAAPnAAAAAAAAAAAAAAAAAAAPoAAAAAAAAAAAAAAAAAAAPpAAAAAAAAAAAAAAAAAAAPqAAAAAAAAAAAAAAAAAAAPrAAAAAAAA"
        "AAAAAAAAAAAPsAAAAAAAAAAAAAAAAAAAPtAAAAAAAAAAAAAAAAAAAPuAAAAAAAAAAAAAAAAAAAPvAAAAAAAAAAAAAAAAAAAPwAAA"
        "AAAAAAAAAAAAAAAAPxAAAAAAAAAAAAAAAAAAAPyAAAAAAAAAAAAAAAAAAAPzAAAAAAAAAAAAAAAAAAAP0AAAAAAAAAAAAAAAAAAA"
        "P1AAAAAAAAAAAAAAAAAAAP2AAAAAAAAAAAAAAAAAAAP3AAAAAAAAAAAAAAAAAAAP4AAAAAAAAAAAAAAAAAAAP5AAAAAAAAAAAAAA"
        "AAAAAP6AAAAAAAAAAAAAAAAAAAP7AAAAAAAAAAAAAAAAAAAP8AAAAAAAAAAAAAAAAAAAP9AAAAAAAAAAAAAAAAAAAP+AAAAAAAAA"
        "AAAAAAAAAAP/AAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAQBAAAAAAAAAAAAAAAAAAAQCAAAAAAAAAAAAAAAAAAAQDAAAA"
        "AAAAAAAAAAAAAAAQEAAAAAAAAAAAAAAAAAAAQFAAAAAAAAAAAAAAAAAAAQGAAAAAAAAAAAAAAAAAAAQHAAAAAAAAAAAAAAAAAAAQ"
        "IAAAAAAAAAAAAAAAAAAAQJAAAAAAAAAAAAAAAAAAAQKAAAAAAAAAAAAAAAAAAAQLAAAAAAAAAAAAAAAAAAAQMAAAAAAAAAAAAAAA"
        "AAAAQNAAAAAAAAAAAAAAAAAAAQOAAAAAAAAAAAAAAAAAAAQPAAAAAAAAAAAAAAAAAAAQQAAAAAAAAAAAAAAAAAAAQRAAAAAAAAAA"
        "AAAAAAAAAQSAAAAAAAAAAAAAAAAAAAQTAAAAAAAAAAAAAAAAAAAQUAAAAAAAAAAAAAAAAAAAQVAAAAAAAAAAAAAAAAAAAQWAAAAA"
        "AAAAAAAAAAAAAAQXAAAAAAAAAAAAAAAAAAAQYAAAAAAAAAAAAAAAAAAAQZAAAAAAAAAAAAAAAAAAAQaAAAAAAAAAAAAAAAAAAAQb"
        "AAAAAAAAAAAAAAAAAAAQcAAAAAAAAAAAAAAAAAAAQdAAAAAAAAAAAAAAAAAAAQeAAAAAAAAAAAAAAAAAAAQfAAAAAAAAAAAAAAAA"
        "AAAQgAAAAAAAAAAAAAAAAAAAQhAAAAAAAAAAAAAAAAAAAQiAAAAAAAAAAAAAAAAAAAQjAAAAAAAAAAAAAAAAAAAQkAAAAAAAAAAA"
        "AAAAAAAAQlAAAAAAAAAAAAAAAAAAAQmAAAAAAAAAAAAAAAAAAAQnAAAAAAAAAAAAAAAAAAAQoAAAAAAAAAAAAAAAAAAAQpAAAAAA"
        "AAAAAAAAAAAAAQqAAAAAAAAAAAAAAAAAAAQrAAAAAAAAAAAAAAAAAAAQsAAAAAAAAAAAAAAAAAAAQtAAAAAAAAAAAAAAAAAAAQuA"
        "AAAAAAAAAAAAAAAAAAQvAAAAAAAAAAAAAAAAAAAQwAAAAAAAAAAAAAAAAAAAQxAAAAAAAAAAAAAAAAAAAQyAAAAAAAAAAAAAAAAA"
        "AAQzAAAAAAAAAAAAAAAAAAAQ0AAAAAAAAAAAAAAAAAAAQ1AAAAAAAAAAAAAAAAAAAQ2AAAAAAAAAAAAAAAAAAAQ3AAAAAAAAAAAA"
        "AAAAAAAQ4AAAAAAAAAAAAAAAAAAAQ5AAAAAAAAAAAAAAAAAAAQ6AAAAAAAAAAAAAAAAAAAQ7AAAAAAAAAAAAAAAAAAAQ8AAAAAAA"
        "AAAAAAAAAAAAQ9AAAAAAAAAAAAAAAAAAAQ+AAAAAAAAAAAAAAAAAAAQ/AAAAAAAAAAAAAAAAAAARAAAAAAAAAAAAAAAAAAAARBAA"
        "AAAAAAAAAAAAAAAAARCAAAAAAAAAAAAAAAAAAARDAAAAAAAAAAAAAAAAAAAREAAAAAAAAAAAAAAAAAAARFAAAAAAAAAAAAAAAAAA"
        "ARGAAAAAAAAAAAAAAAAAAARHAAAAAAAAAAAAAAAAAAARIAAAAAAAAAAAAAAAAAAARJAAAAAAAAAAAAAAAAAAARKAAAAAAAAAAAAA"
        "AAAAAARLAAAAAAAAAAAAAAAAAAARMAAAAAAAAAAAAAAAAAAARNAAAAAAAAAAAAAAAAAAAROAAAAAAAAAAAAAAAAAAARPAAAAAAAA"
        "AAAAAAAAAAARQAAAAAAAAAAAAAAAAAAARRAAAAAAAAAAAAAAAAAAARSAAAAAAAAAAAAAAAAAAARTAAAAAAAAAAAAAAAAAAARUAAA"
        "AAAAAAAAAAAAAAAARVAAAAAAAAAAAAAAAAAAARWAAAAAAAAAAAAAAAAAAARXAAAAAAAAAAAAAAAAAAARYAAAAAAAAAAAAAAAAAAA"
        "RZAAAAAAAAAAAAAAAAAAARaAAAAAAAAAAAAAAAAAAARbAAAAAAAAAAAAAAAAAAARcAAAAAAAAAAAAAAAAAAARdAAAAAAAAAAAAAA"
        "AAAAAReAAAAAAAAAAAAAAAAAAARfAAAAAAAAAAAAAAAAAAARgAAAAAAAAAAAAAAAAAAARhAAAAAAAAAAAAAAAAAAARiAAAAAAAAA"
        "AAAAAAAAAARjAAAAAAAAAAAAAAAAAAARkAAAAAAAAAAAAAAAAAAARlAAAAAAAAAAAAAAAAAAARmAAAAAAAAAAAAAAAAAAARnAAAA"
        "AAAAAAAAAAAAAAARoAAAAAAAAAAAAAAAAAAARpAAAAAAAAAAAAAAAAAAARqAAAAAAAAAAAAAAAAAAARrAAAAAAAAAAAAAAAAAAAR"
        "sAAAAAAAAAAAAAAAAAAARtAAAAAAAAAAAAAAAAAAARuAAAAAAAAAAAAAAAAAAARvAAAAAAAAAAAAAAAAAAARwAAAAAAAAAAAAAAA"
        "AAAARxAAAAAAAAAAAAAAAAAAARyAAAAAAAAAAAAAAAAAAARzAAAAAAAAAAAAAAAAAAAR0AAAAAAAAAAAAAAAAAAAR1AAAAAAAAAA"
        "AAAAAAAAAR2AAAAAAAAAAAAAAAAAAAR3AAAAAAAAAAAAAAAAAAAR4AAAAAAAAAAAAAAAAAAAR5AAAAAAAAAAAAAAAAAAAR6AAAAA"
        "AAAAAAAAAAAAAAR7AAAAAAAAAAAAAAAAAAAR8AAAAAAAAAAAAAAAAAAAR9AAAAAAAAAAAAAAAAAAAR+AAAAAAAAAAAAAAAAAAAR/"
        "AAAAAAAAAAAAAAAAAAASAAAAAAAAAAAAAAAAAAAASBAAAAAAAAAAAAAAAAAAASCAAAAAAAAAAAAAAAAAAASDAAAAAAAAAAAAAAAA"
        "AAASEAAAAAAAAAAAAAAAAAAASFAAAAAAAAAAAAAAAASGASHAAAAAAAAAAAAAAAAAAASIAAAAAAAAAAAAAAAAAAASJAAAAAAAAAAA"
        "AAAAAAA";
    inline constexpr const char* CurrencyNamesChunks[] = {CurrencyNamesChunk0};
    inline constexpr Packed CurrencyNames{CurrencyNamesChunks, 13, 3};

    inline constexpr char ZoneKeysChunk0[] =
        "AADAAEAAMAAwAA2ABBABDABOABVABWABYABbABhABoABzAB0AB1AB2AB3AB4AB5ACAACGACLACQACcACdACeACxACzAC0AC1AC2A"
        "C3AC4ADFADTADUADfADhADiADvADzAD5AD9AD+AEHAEJAELAEQAEVAEkAElAEoAEpAFRAFSAFWAFXAFeAFfAFgAFkAFoAFsAFtAF"
        "yAFzAF3AF5AGGAGHAGKAGRAGUAGXAGeAGkAGmAG0AG7";
    inline constexpr const char* ZoneKeysChunks[] = {ZoneKeysChunk0};
    inline constexpr Packed ZoneKeys{ZoneKeysChunks, 13, 3};

    inline constexpr char ZoneNamesChunk0[] =
        "ASTAAAAAAAAAAAAAAAAAAAS2AAAAAAAAAAAAAAAAAAASUAAAAAAAAAAAAAAAAAAATBAAAAAAAAAAAAAAAAAAASOAAAAAAAAAAAAA"
        "AAAAAAS/AAAAAAAAAAAAAAAAAAASlAAAAAAAAAAAAAAAAAAASnAAAAAAAAAAAAAAAAAAASkAAAAAAAAAAAAAAAAAAAS0AAAAAAAA"
        "AAAAAAAAAAAKYAAAAAAAAAAAAAAAAAAAKbAAAAAAAAAAAAAAAAAAAKhAAAAAAAAAAAAAAAAAAAS5AAAAAAAAAAAAAAAAAAATGAAA"
        "AAAAAAAAAAAAAAAATIAAAAAAAAAAAAAAAAAAATEAAAAAAAAAAAAAAAAAAATFAAAAAAAAAAAAAAAAAAATJAAAAAAAAAAAAAAAAAAA"
        "TDAAAAAAAAAAAAAAAAAAATHAAAAAAAAAAAAAAAAAAATKAAAAAAAAAAAAAAAAAAATCAAAAAAAAAAAAAAAAAAALuAAAAAAAAAAAAAA"
        "AAAAASmAAAAAAAAAAAAAAAAAAASvAAAAAAAAAAAAAAAAAAASxAAAAAAAAAAAAAAAAAAASwAAAAAAAAAAAAAAAAAAAS6AAAAAAAAA"
        "AAAAAAAAAASzAAAAAAAAAAAAAAAAAAAS1AAAAAAAAAAAAAAAAAAAS8AAAAAAAAAAAAAAAAAAAS9AAAAAAAAAAAAAAAAAAATMAAAA"
        "AAAAAAAAAAAAAAATLAAAAAAAAAAAAAAAAAAASyAAAAAAAAAAAAAAAAAAASdAAAAAAAAAAAAAAAAAAASeAAAAAAAAAAAAAAAAAAAS"
        "7AAAAAAAAAAAAAAAAAAASgAAAAAAAAAAAAAAAAAAAStAAAAAAAAAAAAAAAAAAASZAAAAAAAAAAAAAAAAAAAS+AAAAAAAAAAAAAAA"
        "AAAASjAAAAAAAAAAAAAAAAAAASoAAAAAAAAAAAAAAAAAAASQAAAAAAAAAAAAAAAAAAASfAAAAAAAAAAAAAAAAAAASiAAAAAAAAAA"
        "AAAAAAAAATNAAAAAAAAAAAAAAAAAAAMWAAAAAAAAAAAAAAAAAAASaAAAAAAAAAAAAAAAAAAAKaAAAAAAAAAAAAAAAAAAACiAAAAA"
        "AAAAAAAAAAAAAASXAAAAAAAAAAAAAAAAAAATAAAAAAAAAAAAAAAAAAAAAAAAAASLAAAAAAASMAAAASNAAAAAAAAAAAAAAAAAAASW"
        "AAAAAAAAAAAAAAAAAAASqAAAAAAAAAAAAAAAAAAAShAAAAAAAAAAAAAAAAAAASSAAAAAAAAAAAAAAAAAAAAAAAAAAAASYAAAAAAA"
        "AAALHAAAAAAAAAAAAAAAAAAASuAAAAAAAAAAAAAAAAAAAAAAAAAAAASVAAAAAAAAAAEkAAAAAAAAAAAAAAAAAAALjAAAAAAAAAAA"
        "AAAAAAAASrAAAAAAAAAAAAAAAAAAASRAAAAAAAAAAAAAAAAAAASbAAAAAAAAAAAAAAAAAAAM2AAAAAAAAAAAAAAAAAAASPAAAAAA"
        "AAAAAAAAAAAAASpAAAAAAAAAAAAAAAAAAALTAAAAAAAAAAAAAAAAAAALyAAAAAAAAAAAAAAAAAAAMQAAAAAAAAAAAAAAAAAAAScA"
        "AAAAAAAAAAAAAAAAAASsAAAAAAAAAAAAAAAAAAASKAAAAAAAAAAAAAAAAAAAS4AAAAAAAAAAAAAAAAAAAS3AAAAAAAAAAAAAAAAA"
        "A";
    inline constexpr const char* ZoneNamesChunks[] = {ZoneNamesChunk0};
    inline constexpr Packed ZoneNames{ZoneNamesChunks, 13, 3};

    inline constexpr char MetaKeysChunk0[] =
        "AAAAABAACAADAAFAAGAAIAAKAALAAMAANAAOAAPAAQAARAASAATAAUAAVAAWAAXAAZAAaAAbAAcAAdAAeAAfAAhAAjAAkAAmAAoA"
        "ApAAqAArAAsAAtAAuAAvAAwAAxAAyAAzAA1AA3AA6AA7AA8AA9AA+AA/ABAABBABCABDABEABGABHABIABJABKABOABPABQABRAB"
        "SABTABUABVABWABXABYABZABaABbABcABeABfABgABhABjABkABlABnABoABpABsABtABvABwABxAByAB0AB1AB2AB3AB4AB5AB6"
        "AB7AB8AB9AB+AB/ACAACBACCACDACEACFACGACHACIACKACLACMACNACOACPACQACRACSACTACUACVACWACXACYACZACbACcACeA"
        "CfACgAChACjACkAClACmACpACqACrACtACuACwACyACzAC0AC1AC2AC3AC4AC5AC6AC7AC9";
    inline constexpr const char* MetaKeysChunks[] = {MetaKeysChunk0};
    inline constexpr Packed MetaKeys{MetaKeysChunks, 13, 3};

    inline constexpr char MetaNamesChunk0[] =
        "ATOATPATQAAAAAAAAAAAAATRAAAAAAAAAAAAAAAATSAAAAAAAAAAAAAAAATTAAAAAAAAAAAAAAAATUAAAAAAAAAAAAATVATWATXA"
        "AAAAAAAAATYATZATaATbATcATdATeATfATgAAAAAAAAAAThATiATjAAAAAAAAAATkATlATmATnAToATpATqATrATsATtATuATvAT"
        "wATxATyATzAT0AT1AT2AT3AT4AT5AT6AT7AT8AT9AT+AAAAAAAAAAT/AUAAUBAAAAAAAAAAUCAUDAUEAAAAAAAAAAUFAUGAUHAAA"
        "AAAAAAAUIAUJAUKAAAAAAAAAAULAUMAUNAAAAAAAAAAUOAUPAUQAAAAAAAAAAURAUSAUTAAAAAAAAAAUUAUVAUWAUXAUYAUZAUaA"
        "UbAUcAAAAAAAAAAUdAUeAUfAAAAAAAAAAUgAUhAUiAAAAAAAAAAUjAUkAUlAAAAAAAAAAUmAUnAUoAAAAAAAAAAUpAUqAUrAAAAA"
        "AAAAAUsAUtAUuAAAAAAAAAAAAAUvAAAAAAAAAAAAAAAAUwAAAAAAAAAAAAAUxAUyAUzAAAAAAAAAAAAAU0AAAAAAAAAAAAAU1AU2"
        "AU3AAAAAAAAAAAAAU4AAAAAAAAAAAAAAAAU5AAAAAAAAAAAAAU6AU7AU8AAAAAAAAAAU9AU+AU/AAAAAAAAAAVAAVBAVCAAAAAAA"
        "AAAAAAVDAAAAAAAAAAAAAAAAVEAAAAAAAAAAAAAVFAVGAVHAAAAAAAAAAVIAVJAVKAAAAAAAAAAVLAVMAVNAVOAVPAVQAAAAVRAA"
        "AAAAAAAAAAAAAAVSAAAAAAAAAAAAAAAAVTAAAAAAAAAAAAAVUAVVAVWAAAAAAAAAAAAAVXAAAAAAAAAAAAAVYAVZAVaAAAAAAAAA"
        "AVbAVcAVdAAAAAAAAAAAAAVeAAAAAAAAAAAAAVfAVgAVhAAAAAAAAAAViAVjAVkAAAAAAAAAAVlAVmAVnAAAAAAAAAAAAAVoAAAA"
        "AAAAAAAAAAAAVpAAAAAAAAAAAAAAAAVwAAAAAAAAAAAAAAAAVqAAAAAAAAAAAAAAAAVrAAAAAAAAAAAAAVsAVtAVuAAAAAAAAAAA"
        "AAVvAAAAAAAAAAAAAVxAVyAVzAV0AV1AV2AV3AV4AV5AAAAAAAAAAAAAV6AAAAAAAAAAAAAAAAV7AAAAAAAAAAAAAAAAV8AAAAAA"
        "AAAAAAAV9AV+AV/AWAAWBAWCAWDAWEAWFAAAAAAAAAAWGAWHAWIAAAAAAAAAAAAAWJAAAAAAAAAAAAAAAAWKAAAAAAAAAAAAAAAA"
        "WLAAAAAAAAAAAAAAAAWMAAAAAAAWNAAAAAAAWOAAAAAAAWPAAAAAAAWQAAAAAAAWRAAAAWSAWTAWUAAAAAAAAAAWVAWWAWXAAAAA"
        "AAAAAWYAWZAWaAAAAAAAAAAWbAWcAWdAAAAAAAAAAWeAWfAWgAAAAAAAAAAAAAWhAAAAAAAAAAAAAAAAWiAAAAAAAAAAAAAAAAWj"
        "AAAAAAAAAAAAAWkAWlAWmAAAAAAAAAAAAAWnAAAAAAAAAAAAAWoAWpAWqAAAAAAAAAAAAAWrAAAAAAAAAAAAAAAAWsAAAAAAAAAA"
        "AAAAAAWtAAAAAAAAAAAAAWuAWvAWwAAAAAAAAAAWxAWyAWzAAAAAAAAAAW0AW1AW2AAAAAAAAAAAAAW3AAAAAAAAAAAAAAAAW4AA"
        "AAAAAAAAAAAAAAW5AAAAAAAAAAAAAAAAW6AAAAAAAAAAAAAW7AW8AW9AAAAAAAAAAAAAW+AAAAAAAAAAAAAW/AXAAXBAAAAAAAAA"
        "AXCAXDAXEAAAAAAAAAAXFAXGAXHAAAAAAAAAAAAAXIAAAAAAAAAAAAAAAAXJAAAAAAAAAAAAAAAAXKAAAAAAAAAAAAAXLAXMAXNA"
        "AAAAAAAAAXOAXPAXQAAAAAAAAAAXRAXSAXTAXUAXVAXWAAAAXXAAAAAAAAAAAAAXYAXZAXaAAAAAAAAAAXbAXcAXdAAAAAAAAAAA"
        "AAXeAAAAAAAAAAAAAXfAXgAXhAAAAAAAAAAXiAXjAXkAAAAAAAAAAXlAXmAXnAAAAAAAAAAAAAXoAAAAAAAAAAAAAAAAXpAAAAAA"
        "AAAAAAAXqAXrAXsAAAAAAAAAAXtAXuAXvAAAAAAAAAAXwAXxAXyAAAAAAAAAAAAAXzAAAAAAAAAAAAAX0AX1AX2AX3AX4AX5AAAA"
        "X6AAAAAAAAAAAAAAAAX7AAAAAAAAAAAAAAAAX8AAAAAAAAAAAAAX9AX+AX/AAAAAAAAAAAAAYAAAAAAAAAAAAAAAAAYBAAAAAAAA"
        "AAAAAYCAYDAYEAAAAAAAAAAYFAYGAYHAAAAAAAAAAYIAYJAYKAAAAAAAAAAAAAYLAAAAAAAAAAAAAAAAYMAAAAAAAAAAAAAAAAYN"
        "AAAAAAAAAAAAAAAAYOAAAAAAAAAAAAAAAAYPAAAAAAAAAAAAAAAAYQAAAAAAAAAAAAAAAAYRAAAAAAAAAAAAAYSAYTAYUAAAAAAA"
        "AAAAAAYVAAAAAAAAAAAAAAAAYWAAAAAAAAAAAAAYXAYYAYZAAAAAAAAAAAAAYaAAAAAAAAAAAAAYbAYcAYdAAAAAAAAAAAAAYeAA"
        "AAAAAAAAAAAYfAYgAYhAAAAAAAAAAYiAYjAYkAAAAAAAAAAYlAYmAYnAAAAAAAAAAAAAYoAAAAAAAAAAAAAYpAYqAYrAAAAAAAAA"
        "AYsAYtAYuAAAAAAAAAAAAAYvAAAAAAAAAAAAAAAAYwAAAAAAAAAAAAAAAAYxAAAAAAAAAAAAAYyAYzAY0AAAAAAAAAAY1AY2AY3A"
        "AAAAAAAAAAAAY4AAAAAAAAAAAA";
    inline constexpr const char* MetaNamesChunks[] = {MetaNamesChunk0};
    inline constexpr Packed MetaNames{MetaNamesChunks, 13, 3};

    inline constexpr uint16_t Formats[] = {
        1593, 1594, 1595, 1596, 1597, 1598, 0, 0, 0, 0, 0, 1599,
    };

    inline constexpr Table table{
        0x696400000000, 0,
        NameTexts,
        LanguageKeys, LanguageNames, 576,
        nullptr, Packed{}, 0,
        RegionKeys, RegionNames, 294,
        ScriptKeys, ScriptNames, 192,
        AloneKeys, AloneNames, 2,
        CurrencyKeys, CurrencyNames, 167,
        ZoneKeys, ZoneNames, 81,
        MetaKeys, MetaNames, 157,
        Formats,
    };

    // the table registered when the header is included, once a program
    inline Registration registration{&table};
}
