//------------------------------------------------------------------------------
// SGCL: a C++20 application platform
// Copyright (c) 2022-2026 Sebastian Nibisz
// SPDX-License-Identifier: Apache-2.0
//------------------------------------------------------------------------------
#pragma once
#include "detail/registry.h"

#include <cstdint>

// The display names of the locale ko (한국어), CLDR 46.0: the names of languages,
// regions, scripts, currencies and time zones in it.
// Including this header is all a program does: txt::locale::display_name,
// region::display_name, script::display_name and currency::display_name then
// answer in this language. Generated by tools/cldr_tables.py: do not edit.
namespace sgcl::txt::detail::names::l_ko {
    inline constexpr char8_t NameChunk0[] =
        u8"아파르어압카즈어아체어아콜리어아당메어아디게어아베스타어튀니지 아랍어아프리칸스어아프리힐리어아그햄어아이누어아칸어아카드어알류트어남부 알타이어암하라어아라곤어고대 영어오볼로어앙가어아랍어현대 표"
        u8"준 아랍어아람어마푸둥군어아라파호어알제리 아랍어아랍어(나즈디)아라와크어모로코 아랍어이집트 아랍어아삼어아수어아스투리아어아티카메쿠어아바릭어아와히어아이마라어아제르바이잔어바슈키르어발루치어발"
        u8"리어바사어바문어고말라어벨라루스어베자어벰바어베나어바푸트어불가리아어하리안비어서부 발로치어호즈푸리어비슬라마어비콜어비니어콤어식시카어아니이어밤바라어벵골어티베트어브르타뉴어브라지어브라후이어보도"
        u8"어보스니아어아쿠즈어부리아타부기어불루어브린어메둠바어카탈로니아어카도어카리브어카유가어앗삼어차크마어체첸어세부아노어치가어차모로어치브차어차가타이어추크어마리어치누크 자곤촉토어치페우얀체로키어샤이"
        u8"엔어소라니 쿠르드어칠코틴어코르시카어콥트어크리어미치프어크리민 터키어; 크리민 타타르어남동부 크리어평원 크리어북동부 크리어무스크리어캐롤라이나 알곤킨어세이셸 크리올 프랑스어체코어카슈비아"
        u8"어습지 크리어교회 슬라브어추바시어웨일스어덴마크어다코타어다르그와어타이타어독일어고지 독일어(스위스)델라웨어어슬라브어도그리브어딩카어자르마어도그리어저지 소르비아어두알라어중세 네덜란드어디베"
        u8"히어졸라 포니어드율라어종카어다장가어엠부어에웨어이픽어고대 이집트어이카죽어그리스어엘람어영어중세 영어에스페란토어스페인어스페인어(유럽)에스토니아어바스크어이원도어페르시아어다리어팡그어판티어풀"
        u8"라어핀란드어필리핀어피지어페로어폰어프랑스어케이준 프랑스어중세 프랑스어고대 프랑스어북부 프리지아어동부 프리슬란드어프리울리어서부 프리지아어아일랜드어가어가가우스어간어가요어그바야어조로아스터"
        u8" 다리어스코틀랜드 게일어게이즈어키리바시어갈리시아어길라키어중세 고지 독일어과라니어고대 고지 독일어곤디어고론탈로어고트어게르보어고대 그리스어독일어(스위스)구자라트어구시어맹크스어그위친어하"
        u8"우사어하이다어하카어하와이어남부 하이다어히브리어힌디어피지 힌디어헤리가뇬어하타이트어히몸어히리 모투어크로아티아어고지 소르비아어샹어아이티어헝가리어후파어할코멜렘어아르메니아어헤레로어인터링구아"
        u8"이반어이비비오어인도네시아어인테르링구에이그보어쓰촨 이어이누피아크어캐나다 서부 이누크티투트어이로코어인귀시어이도어아이슬란드어이탈리아어이눅티투트어일본어로반어응곰바어마차메어유대-페르시아어유"
        u8"대-아라비아어자바어조지아어카라칼파크어커바일어카친어까꼬토끄어캄바어카위어카바르디어카넴부어티얍어마콘데어크리올어코로어콩고어카잉강어카시어호탄어코이라 친니어코와르어키쿠유어쿠안야마어카자흐어카코"
        u8"어그린란드어칼렌진어크메르어킴분두어칸나다어한국어코미페르먀크어코카니어코스라이엔어크펠레어칸누리어카라챠이-발카르어카렐리야어쿠르크어카슈미르어샴발라어바피아어콜로그니안어쿠르드어쿠믹어쿠테네어코미"
        u8"어콘월어곽왈라어쿠비어키르기스어라틴어라디노어랑기어라한다어람바어룩셈부르크어레즈기안어링구아 프랑카 노바간다어림버거어리구리아어릴루엣어라코타어롬바르드어링갈라어라오어몽고어루이지애나 크리올어로"
        u8"지어북부 루리어사미아어리투아니아어루바-카탄가어루바-룰루아어루이세노어룬다어루오어루샤이어루야어라트비아어마두라어마파어마가히어마이틸리어마카사어만딩고어마사이어마바어모크샤어만다르어멘데어메루어"
        u8"모리스얀어말라가시어중세 아일랜드어마크후와-메토어메타어마셜어마오리어미크맥어미낭카바우어마케도니아어말라얄람어몽골어만주어마니푸리어이누아문모호크어모시어마라티어서부 마리어말레이어몰타어문당어다"
        u8"중 언어크리크어미란데어마르와리어버마어미예네어엘즈야어마잔데라니어나우루어민난어나폴리어나마어노르웨이어(보크말)북부 은데벨레어저지 독일어저지 색슨어네팔어네와르어느동가어니아스어니웨언어네덜란"
        u8"드어플라망어크와시오어노르웨이어(니노르스크)느기엠본어노르웨이어노가이어고대 노르웨이어응코어남부 은데벨레어북부 소토어누에르어나바호어고전 네와르어냔자어니암웨지어니안콜어뉴로어느지마어오크어오"
        u8"지브와어북서부 오지브와어중앙 오지브와어오지 크리어서부 오지브와어오카나간어오로모어오리야어오세트어오세이지어오스만 터키어펀잡어판가시난어팔레비어팜팡가어파피아먼토어팔라우어나이지리아 피진어고"
        u8"대 페르시아어페니키아어팔리어피진어폴란드어폰틱어폼페이어말리시트 파사마쿼디어프러시아어고대 프로방스어파슈토어포르투갈어포르투갈어(유럽)케추아어키체어라자스탄어라파뉴이라로통가어로힝야어로만시어"
        u8"룬디어루마니아어몰도바어롬보어집시어러시아어루신어아로마니아어르완다어르와어산스크리트어산다웨어야쿠트어사마리아 아랍어삼부루어사사크어산탈리어느감바이어상구어사르디니아어시칠리아어스코틀랜드어신디어"
        u8"남부 쿠르드어북부 사미어세네카어세나어셀쿠프어코이야보로 세니어산고어고대 아일랜드어세르비아-크로아티아어타셸히트어샨어차디언 아라비아어싱할라어시다모어슬로바키아어슬로베니아어남부 루슈트시드어"
        u8"사모아어남부 사미어룰레 사미어이나리 사미어스콜트 사미어쇼나어소닌케어소말리아어소그디엔어알바니아어세르비아어스라난 통가어세레르어시스와티어사호어남부 소토어해안 살리시어순다어수쿠마어수수어수"
        u8"메르어스웨덴어스와힐리어콩고 스와힐리어코모로어고전 시리아어시리아어실레시아어타밀어남부 투톤어텔루구어팀니어테조어테레노어테툼어타지크어타기시어태국어탈탄어티그리냐어티그레어티브어투르크멘어토켈라"
        u8"우제도어차후르어타갈로그어클링온어틀링깃족어탈리쉬어타마섹어츠와나어통가어니아사 통가어도기 보나토크 피신어튀르키예어타로코어총가어트심시안어타타르어북부 투톤어툼부카어투발루어트위어타사와크어타히"
        u8"티어투비니안어중앙 모로코 타마지트어우드말트어위구르어유가리틱어우크라이나어움분두어알 수 없는 언어우르두어우즈베크어바이어벤다어베네치아어베트남어마쿠와어볼라퓌크어보틱어분조어왈론어월저어월라이"
        u8"타어와라이어와쇼어왈피리어월로프어우어칼미크어코사어캉리어소가어야오족어얍페세어양본어옘바어이디시어요루바어넨가투어광둥어주앙어사포테크어블리스 심볼제나가어표준 모로코 타마지트어중국어줄루어주니어"
        u8"언어 관련 내용 없음자자어세계아프리카북아메리카남아메리카오세아니아서부 아프리카중앙 아메리카동부 아프리카북부 아프리카중부 아프리카남부 아프리카아메리카 대륙북부 아메리카카리브 제도동아시"
        u8"아남아시아동남아시아남유럽오스트랄라시아멜라네시아미크로네시아 지역폴리네시아아시아중앙 아시아서아시아유럽동유럽북유럽서유럽사하라 사막 이남 아프리카라틴 아메리카어센션섬안도라아랍에미리트아프가"
        u8"니스탄앤티가 바부다앵귈라알바니아아르메니아앙골라남극 대륙아르헨티나아메리칸 사모아오스트리아오스트레일리아아루바올란드 제도아제르바이잔보스니아 헤르체고비나바베이도스방글라데시벨기에부르키나파소"
        u8"불가리아바레인부룬디베냉생바르텔레미버뮤다브루나이볼리비아네덜란드령 카리브브라질바하마부탄부베섬보츠와나벨라루스벨리즈캐나다코코스 제도콩고-킨샤사중앙 아프리카 공화국콩고-브라자빌스위스코트디부"
        u8"아르쿡 제도칠레카메룬중국콜롬비아클리퍼턴섬코스타리카쿠바카보베르데퀴라소크리스마스섬키프로스체코독일디에고 가르시아지부티덴마크도미니카도미니카 공화국알제리세우타 및 멜리야에콰도르에스토니아이집"
        u8"트서사하라에리트리아스페인에티오피아유럽 연합유로존핀란드피지포클랜드 제도미크로네시아페로 제도프랑스가봉영국그레나다조지아프랑스령 기아나건지가나지브롤터그린란드감비아기니과들루프적도 기니그리스"
        u8"사우스조지아 사우스샌드위치 제도과테말라괌기니비사우가이아나홍콩(중국 특별행정구)허드 맥도널드 제도온두라스크로아티아아이티헝가리카나리아 제도인도네시아아일랜드이스라엘맨섬인도영국령 인도양 "
        u8"지역이라크이란아이슬란드이탈리아저지자메이카요르단일본케냐키르기스스탄캄보디아키리바시코모로세인트키츠 네비스북한대한민국쿠웨이트케이맨 제도카자흐스탄라오스레바논세인트루시아리히텐슈타인스리랑카라이"
        u8"베리아레소토리투아니아룩셈부르크라트비아리비아모로코모나코몰도바몬테네그로생마르탱마다가스카르마셜 제도북마케도니아말리미얀마몽골마카오(중국 특별행정구)북마리아나제도마르티니크모리타니몬트세라트몰"
        u8"타모리셔스몰디브말라위멕시코말레이시아모잠비크나미비아뉴칼레도니아니제르노퍽섬나이지리아니카라과네덜란드노르웨이네팔나우루니우에뉴질랜드오만파나마페루프랑스령 폴리네시아파푸아뉴기니필리핀파키스탄폴란"
        u8"드생피에르 미클롱핏케언 제도푸에르토리코팔레스타인 지구포르투갈팔라우파라과이카타르오세아니아 외곽레위니옹루마니아세르비아러시아르완다사우디아라비아솔로몬 제도세이셸수단스웨덴싱가포르세인트헬레나"
        u8"슬로베니아스발바르제도-얀마웬섬슬로바키아시에라리온산마리노세네갈소말리아수리남남수단상투메 프린시페엘살바도르신트마르턴시리아에스와티니트리스탄다쿠나터크스 케이커스 제도차드프랑스령 남방 지역토"
        u8"고태국타지키스탄토켈라우동티모르투르크메니스탄튀니지통가튀르키예트리니다드 토바고투발루대만탄자니아우크라이나우간다미국령 해외 제도국제연합미국우루과이우즈베키스탄바티칸 시국세인트빈센트그레나딘베"
        u8"네수엘라영국령 버진아일랜드미국령 버진아일랜드베트남바누아투왈리스-푸투나 제도사모아유사 억양유사 양방향코소보예멘마요트남아프리카잠비아짐바브웨알려지지 않은 지역아들람 문자아파카 문자코카시"
        u8"안 알바니아 문자아랍 문자나스탈리크체아랍제국 문자아르메니아 문자아베스타 문자발리 문자바뭄 문자바사바흐 문자바타크 문자벵골 문자블리스기호 문자주음부호브라미브라유 점자부기 문자부히드 "
        u8"문자차크마 문자통합 캐나다 원주민 음절문자카리 문자칸 고어체로키 문자키르쓰콥트 문자키프로스 문자키릴 문자고대교회슬라브어 키릴문자데바나가리 문자디저렛 문자듀플로이안 문자고대 이집트 "
        u8"민중문자고대 이집트 신관문자고대 이집트 신성문자엘바산 문자에티오피아 문자그루지야 쿠츠리 문자조지아 문자글라골 문자고트 문자그란타 문자그리스 문자구자라트 문자구르무키 문자주음 자모한"
        u8"글한자하누누 문자간체번체히브리 문자히라가나아나톨리아 상형문자파하우 몽 문자고대 헝가리 문자인더스 문자고대 이탈리아 문자자모자바 문자일본 문자줄첸 문자카야 리 문자가타카나카로슈티 문"
        u8"자크메르 문자코즈키 문자칸나다 문자한국 문자크펠레 문자카이시 문자란나 문자라오 문자독일식 로마자아일랜드식 로마자로마자렙차 문자림부 문자선형 문자(A)선형 문자(B)프레이저 문자로마"
        u8" 문자리키아 문자리디아 문자마하자니 문자만다이아 문자마니교 문자마야 상형 문자멘데 문자메로에 필기체메로에 문자말라얄람 문자몽골 문자문 문자므로 문자메이테이 마옉 문자미얀마 문자옛 "
        u8"북부 아라비아 문자나바테아 문자나시 게바 문자응코 문자누슈 문자오검 문자올 치키 문자오르혼어오리야 문자오스마니아 문자팔미라 문자고대 페름 문자파스파 문자명문 팔라비 문자솔터 팔라비"
        u8" 문자북 팔라비 문자페니키아 문자폴라드 표음 문자명문 파라티아 문자저지 문자레장 문자하니피 문자롱고롱고룬 문자사마리아 문자사라티옛 남부 아라비아 문자사우라슈트라 문자수화 문자샤비안"
        u8" 문자사라다 문자실담자쿠다와디 문자신할라 문자소라 솜펭 문자순다 문자실헤티 나가리시리아 문자에스트랑겔로식 시리아 문자서부 시리아 문자동부 시리아 문자타그반와 문자타크리 문자타이 레"
        u8" 문자신 타이 루에타밀 문자탕구트 문자태국 베트남 문자텔루구 문자텡과르 문자티피나그 문자타갈로그 문자타나 문자타이 문자티베트 문자티르후타 문자우가리트 문자바이 문자시화법바랑 크시티"
        u8" 문자울레아이고대 페르시아 문자수메르-아카드어 설형문자이 문자구전 문자수학 기호이모티콘기호구전일반 문자알 수 없는 문자한자 간체한자 번체아랍에미리트 디르함아프가니스탄 아프가니알바니"
        u8"아 레크아르메니아 드람앙골라 콴자아르헨티나 페소호주 달러아루바 플로린아제르바이잔 마나트보스니아-헤르체고비나 태환 마르크바베이도스 달러방글라데시 타카불가리아 레프바레인 디나르부룬디 "
        u8"프랑버뮤다 달러부루나이 달러볼리비아 볼리비아노브라질 레알바하마 달러부탄 눌투눔보츠와나 풀라벨라루스 루블벨리즈 달러캐나다 달러콩고 프랑스위스 프랑칠레 페소중국 위안화콜롬비아 페소코스"
        u8"타리카 콜론쿠바 페소카보베르데 에스쿠도체코 코루나지부티 프랑덴마크 크로네도미니카 페소알제리 디나르이집트 파운드에리트리아 나크파에티오피아 비르유로피지 달러포클랜드제도 파운드영국 파운"
        u8"드조지아 라리가나 세디지브롤터 파운드감비아 달라시기니 프랑과테말라 케트살가이아나 달러홍콩 달러온두라스 렘피라아이티 구르드헝가리 포린트인도네시아 루피아이스라엘 신권 세켈인도 루피이라"
        u8"크 디나르이란 리얄아이슬란드 크로나자메이카 달러요르단 디나르일본 엔화케냐 실링키르기스스탄 솜캄보디아 리엘코모르 프랑조선 민주주의 인민 공화국 원대한민국 원쿠웨이트 디나르케이맨 제도"
        u8" 달러카자흐스탄 텡게라오스 키프레바논 파운드스리랑카 루피라이베리아 달러레소토 로티리비아 디나르모로코 디르함몰도바 레이마다가스카르 아리아리마케도니아 디나르미얀마 키얏몽골 투그릭마카오"
        u8" 파타카모리타니 우기야모리셔스 루피몰디브 제도 루피아말라위 콰차멕시코 페소말레이시아 링깃모잠비크 메티칼나미비아 달러나이지리아 나이라니카라과 코르도바노르웨이 크로네네팔 루피뉴질랜드 "
        u8"달러오만 리알파나마 발보아페루 솔파푸아뉴기니 키나필리핀 페소파키스탄 루피폴란드 즈워티파라과이 과라니카타르 리얄루마니아 레우세르비아 디나르러시아 루블르완다 프랑사우디아라비아 리얄솔로"
        u8"몬 제도 달러세이셸 루피수단 파운드스웨덴 크로나싱가포르 달러세인트헬레나 파운드시에라리온 리온소말리아 실링수리남 달러남수단 파운드상투메 프린시페 도브라시리아 파운드스와질란드 릴랑게니"
        u8"태국 바트타지키스탄 소모니투르크메니스탄 마나트튀니지 디나르통가 파앙가튀르키예 리라트리니다드 토바고 달러신 타이완 달러탄자니아 실링우크라이나 그리브나우간다 실링미국 달러우루과이 페소"
        u8"우즈베키스탄 숨베네수엘라 볼리바르베트남 동바누아투 바투서 사모아 탈라중앙아프리카 CFA 프랑은화금유르코 (유럽 회계 단위)유럽 통화 동맹유럽 계산 단위 (XBC)유럽 계산 단위 ("
        u8"XBD)동카리브 달러특별인출권유럽 환율 단위프랑스 프랑 (Gold)프랑스 프랑 (UIC)서아프리카 CFA 프랑팔라듐CFP 프랑백금RINET 기금테스트 통화 코드알 수 없는 통화 단"
        u8"위(알 수 없는 통화 단위)예멘 리알남아프리카 랜드잠비아 콰차호놀룰루협정 세계시UTC알 수 없는 장소두바이카불안티과앙귈라티라나예레반루안다로데라파머트롤쇼와모슨데이비스보스토크케이시뒤몽"
        u8" 뒤르빌맥머도리오 가예고스멘도사산후안우수아이아라 리오하산루이스카타마르카살타후후이투쿠만코르도바부에노스 아이레스파고파고비엔나퍼스유클라다윈애들레이드브로컨힐멜버른호바트린데만시드니브리스베인"
        u8"맥쿼리로드 하우마리에함바쿠사라예보다카브뤼셀와가두구소피아부줌부라포르토노보라파스크라렌디즈크아이루네페히우 브랑쿠포르토벨료보아 비스타마나우스쿠이아바산타렘캄포 그란데벨렘아라과이나상파울루바히"
        u8"아포르탈레자마세이오레시페노롱야나소팀부가보로네민스크도슨화이트호스이누빅벤쿠버포트 넬슨도슨크릭크레스톤에드먼턴스위프트커런트케임브리지 베이리자이나위니펙리졸루트랭킹 인렛코랄하버토론토이칼루이트"
        u8"몽턴핼리팩스구즈베이글라스베이블랑 사블롱세인트존스코코스킨샤사루붐바시방기브라자빌취리히아비장라로통가이스터 섬푼타아레나스산티아고두알라우루무치상하이보고타하바나카보 베르데크리스마스니코시아파마"
        u8"구스타프라하뷔지겐베를린코펜하겐산토도밍고알제갈라파고스과야킬탈린카이로엘아이운아스메라세우타마드리드아디스아바바헬싱키스탠리트루크포나페코스레파리리브르빌런던영국 하계 표준시트빌리시카옌아크라툴레"
        u8"고드호프스코레스바이선드덴마크샤븐반줄코나크리말라보아테네사우스조지아비사우홍콩테구시갈파자그레브포르토프랭스부다페스트자카르타폰티아나크마카사르자야푸라더블린아일랜드 표준시예루살렘콜카타차고스바그"
        u8"다드테헤란레이캬비크로마암만도쿄나이로비비슈케크프놈펜엔더베리키리티마티타라와세인트키츠평양서울케이맨아크타우오랄아티라우악토브코스타나이키질로르다알마티비엔티안베이루트파두츠콜롬보몬로비아마세루빌니"
        u8"우스리가트리폴리카사블랑카키시나우포드고리차마리곳안타나나리보콰잘렌마주로스코페바마코랑군호브드울란바토르마카오사이판마티니크누악쇼트몬세라트블랜타이어티후아나에르모시요시우다드후아레스마사틀란치와와"
        u8"바이아 반데라스오히나가몬테레이멕시코 시티마타모로스메리다칸쿤쿠알라룸푸르쿠칭마푸토빈트후크누메아니아메노퍽라고스마나과암스테르담오슬로카트만두채텀오클랜드무스카트리마타히티마퀘사스감비어포트모르즈"
        u8"비부갱빌마닐라카라치바르샤바미클롱핏케언가자헤브론아조레스마데이라리스본아순시온부쿠레슈티베오그라드칼리닌그라드모스크바볼고그라트사라토프아스트라한울리야노프스크키로프사마라예카테린부르크옴스크노보시"
        u8"비르스크바르나울톰스크노보쿠즈네츠크크라스노야르스크이르쿠츠크치타야쿠츠크블라디보스토크한디가사할린우스티네라마가단스레드네콜림스크캄차카아나디리키갈리리야드과달카날마헤카르툼스톡홀름세인트 헬레나류"
        u8"블랴나롱이어비엔브라티슬라바프리타운다카르모가디슈파라마리보주바상투메로워 프린스 쿼터다마스쿠스음바바네그랜드 터크엔자메나케르켈렌로메방콕두샨베파카오푸딜리아슈하바트튀니스통가타푸이스탄불포트오브"
        u8"스페인푸나푸티타이베이다르에스살람키예프심페로폴캄팔라미드웨이웨이크에이닥놈앵커리지야쿠타트싯카주노메틀라카틀라로스앤젤레스보이시피닉스덴버노스다코타주, 베라노스다코타주, 뉴살렘중부, 노스다코타"
        u8"시카고메노미니인디애나주, 빈센스인디애나주, 피츠버그인디애나주, 텔시티인디애나주, 녹스인디애나주, 위너맥인디애나주, 머렝고인디애나폴리스루이빌인디애나주, 비비켄터키주, 몬티첼로디트로이"
        u8"트뉴욕몬테비데오사마르칸트타슈켄트바티칸세인트빈센트카라카스토르톨라세인트토마스사이공에파테월리스아피아아덴메요트요하네스버그루사카하라레아크레 시간아크레 표준시아크레 하계 표준시아프가니스탄 시"
        u8"간중앙아프리카 시간동아프리카 시간남아프리카 시간서아프리카 시간서아프리카 표준시서아프리카 하계 표준시알래스카 시간알래스카 표준시알래스카 하계 표준시알마티 표준 시간알마티 표준 표준시"
        u8"알마티 하계 표준시아마존 시간아마존 표준시아마존 하계 표준시미 중부 시간미 중부 표준시미 중부 하계 표준시미 동부 시간미 동부 표준시미 동부 하계 표준시미 산지 시간미 산악 표준시"
        u8"미 산지 하계 표준시미 태평양 시간미 태평양 표준시미 태평양 하계 표준시아나디리 시간아나디리 표준시아나디리 하계 표준시아피아 시간아피아 표준시아피아 하계 표준시악타우 표준 시간악타"
        u8"우 표준 표준시악타우 하계 표준시악퇴베 표준 시간악퇴베 표준 표준시악퇴베 하계 표준시아라비아 시간아라비아 표준시아라비아 하계 표준시아르헨티나 시간아르헨티나 표준시아르헨티나 하계 표"
        u8"준시아르헨티나 서부 시간아르헨티나 서부 표준시아르헨티나 서부 하계 표준시아르메니아 시간아르메니아 표준시아르메니아 하계 표준시대서양 시간대서양 표준시대서양 하계 표준시오스트레일리아 "
        u8"중부 시간오스트레일리아 중부 표준시오스트레일리아 중부 하계 표준시오스트레일리아 중서부 시간오스트레일리아 중서부 표준시오스트레일리아 중서부 하계 표준시오스트레일리아 동부 시간오스트레"
        u8"일리아 동부 표준시오스트레일리아 동부 하계 표준시오스트레일리아 서부 시간오스트레일리아 서부 표준시오스트레일리아 서부 하계 표준시아제르바이잔 시간아제르바이잔 표준시아제르바이잔 하계 "
        u8"표준시아조레스 시간아조레스 표준시아조레스 하계 표준시방글라데시 시간방글라데시 표준시방글라데시 하계 표준시부탄 시간볼리비아 시간브라질리아 시간브라질리아 표준시브라질리아 하계 표준시브"
        u8"루나이 시간카보 베르데 시간카보 베르데 표준시카보 베르데 하계 표준시케이시 시간차모로 시간채텀 시간채텀 표준시채텀 하계 표준시칠레 시간칠레 표준시칠레 하계 표준시중국 시간중국 표준"
        u8"시중국 하계 표준시크리스마스섬 시간코코스 제도 시간콜롬비아 시간콜롬비아 표준시콜롬비아 하계 표준시쿡 제도 시간쿡 제도 표준시쿡 제도 절반 하계 표준시쿠바 시간쿠바 표준시쿠바 하계 "
        u8"표준시데이비스 시간뒤몽뒤르빌 시간동티모르 시간이스터섬 시간이스터섬 표준시이스터섬 하계 표준시에콰도르 시간중부유럽 시간중부유럽 표준시중부유럽 하계 표준시동유럽 시간동유럽 표준시동유럽"
        u8" 하계 표준시극동유럽 표준시서유럽 시간서유럽 표준시서유럽 하계 표준시포클랜드 제도 시간포클랜드 제도 표준시포클랜드 제도 하계 표준시피지 시간피지 표준시피지 하계 표준시프랑스령 가이"
        u8"아나 시간프랑스령 남부 식민지 및 남극 시간갈라파고스 시간감비에 시간조지아 시간조지아 표준시조지아 하계 표준시길버트 제도 시간그리니치 표준시그린란드 동부 시간그린란드 동부 표준시그"
        u8"린란드 동부 하계 표준시그린란드 서부 시간그린란드 서부 표준시그린란드 서부 하계 표준시걸프만 표준시가이아나 시간하와이 알류샨 시간하와이 알류샨 표준시하와이 알류샨 하계 표준시홍콩 "
        u8"시간홍콩 표준시홍콩 하계 표준시호브드 시간호브드 표준시호브드 하계 표준시인도 표준시인도양 시간인도차이나 시간중부 인도네시아 시간동부 인도네시아 시간서부 인도네시아 시간이란 시간이란"
        u8" 표준시이란 하계 표준시이르쿠츠크 시간이르쿠츠크 표준시이르쿠츠크 하계 표준시이스라엘 시간이스라엘 표준시이스라엘 하계 표준시일본 시간일본 표준시일본 하계 표준시페트로파블롭스크-캄차츠"
        u8"키 시간페트로파블롭스크-캄차츠키 표준시페트로파블롭스크-캄차츠키 하계 표준시카자흐스탄 시간동부 카자흐스탄 시간서부 카자흐스탄 시간대한민국 시간대한민국 표준시대한민국 하계 표준시코스라"
        u8"에섬 시간크라스노야르스크 시간크라스노야르스크 표준시크라스노야르스크 하계 표준시키르기스스탄 시간라인 제도 시간로드 하우 시간로드 하우 표준시로드 하우 하계 표준시마카오 시간마카오 표"
        u8"준 시간마카오 하계 표준시마가단 시간마가단 표준시마가단 하계 표준시말레이시아 시간몰디브 시간마르키즈 제도 시간마셜 제도 시간모리셔스 시간모리셔스 표준시모리셔스 하계 표준시모슨 시간"
        u8"멕시코 태평양 시간멕시코 태평양 표준시멕시코 태평양 하계 표준시울란바토르 시간울란바토르 표준시울란바토르 하계 표준시모스크바 시간모스크바 표준시모스크바 하계 표준시미얀마 시간나우루 "
        u8"시간네팔 시간뉴칼레도니아 시간뉴칼레도니아 표준시뉴칼레도니아 하계 표준시뉴질랜드 시간뉴질랜드 표준시뉴질랜드 하계 표준시뉴펀들랜드 시간뉴펀들랜드 표준시뉴펀들랜드 하계 표준시니우에 시간"
        u8"노퍽섬 시간노퍽섬 표준시노퍽섬 하계 표준시페르난도 데 노로냐 시간페르난도 데 노로냐 표준시페르난도 데 노로냐 하계 표준시노보시비르스크 시간노보시비르스크 표준시노보시비르스크 하계 표"
        u8"준시옴스크 시간옴스크 표준시옴스크 하계 표준시파키스탄 시간파키스탄 표준시파키스탄 하계 표준시팔라우 시간파푸아뉴기니 시간파라과이 시간파라과이 표준시파라과이 하계 표준시페루 시간페루 "
        u8"표준시페루 하계 표준시필리핀 시간필리핀 표준시필리핀 하계 표준시피닉스 제도 시간세인트피에르 미클롱 시간세인트피에르 미클롱 표준시세인트피에르 미클롱 하계 표준시핏케언 시간포나페 시간"
        u8"평양 시간키질로르다 시간키질로르다 표준 시간키질로르다 하계 표준시레위니옹 시간로데라 시간사할린 시간사할린 표준시사할린 하계 표준시사마라 시간사마라 표준시사마라 하계 표준시사모아 시"
        u8"간사모아 표준시사모아 하계 표준시세이셸 시간싱가포르 표준시솔로몬 제도 시간사우스 조지아 시간수리남 시간쇼와 시간타히티 시간대만 시간대만 표준시대만 하계 표준시타지키스탄 시간토켈라우"
        u8" 시간통가 시간통가 표준시통가 하계 표준시추크 시간투르크메니스탄 시간투르크메니스탄 표준시투르크메니스탄 하계 표준시투발루 시간우루과이 시간우루과이 표준시우루과이 하계 표준시우즈베키스"
        u8"탄 시간우즈베키스탄 표준시우즈베키스탄 하계 표준시바누아투 시간바누아투 표준시바누아투 하계 표준시베네수엘라 시간블라디보스토크 시간블라디보스토크 표준시블라디보스토크 하계 표준시볼고그라"
        u8"드 시간볼고그라드 표준시볼고그라드 하계 표준시보스톡 시간웨이크섬 시간월리스푸투나 제도 시간야쿠츠크 시간야쿠츠크 표준시야쿠츠크 하계 표준시예카테린부르크 시간예카테린부르크 표준시예카테"
        u8"린부르크 하계 표준시유콘 시간{0}({1}){0}, {1}{0} 시간{0} 표준시{0} 하계 표준시{1}({0}){0} {1}";
    inline constexpr const char8_t* NameChunks[] = {NameChunk0};
    inline constexpr uint16_t NameChunkSizes[] = {30464};
    inline constexpr char NameRefsChunk0[] =
        "AAAAAAAAAAAMAAAYAAAhAAAtAAA5AABFAABUAABnAAB5AACLAACXAACjAACsAAC4AADEAADXAADjAADvAAD8AAEIAAERAAEaAAEx"
        "AAE6AAFJAAFYAAFrAAF/AAGOAAGhAAG0AAG9AAHGAAHYAAHqAAH2AAICAAIRAAImAAI1AAJBAAJKAAJTAAJcAAJoAAJ3AAKAAAKJ"
        "AAKSAAKeAAKtAAK8AALPAALeAALtAAL2AAL/AAMFAAMRAAMdAAMpAAMyAAM+AANNAANZAANoAANxAAOAAAOMAAOYAAOhAAOqAAOz"
        "AAO/AAPRAAPaAAPmAAPyAAP7AAQHAAQQAAQfAAQoAAQ0AARAAARPAARYAARhAARxAAR6AASGAASSAASeAAS0AATAAATPAATYAATh"
        "AATtAAUYAAUrAAU7AAVOAAVdAAV5AAWZAAWiAAWxAAXBAAXUAAXgAAXsAAX4AAYEAAYTAAYfAAYoAAZDAAZSAAZeAAZtAAZ2AAaC"
        "AAaOAAakAAawAAbGAAbSAAbiAAbuAAb3AAcDAAcMAAcVAAceAAcxAAc9AAdJAAdSAAdYAAdlAAd3AAeDAAeXAAepAAe1AAfBAAfQ"
        "AAfZAAfiAAfrAAf0AAgAAAgMAAgVAAgeAAgkAAgwAAhGAAhZAAhsAAiCAAibAAiqAAjAAAjPAAjVAAjkAAjqAAjzAAj/AAkYAAkx"
        "AAk9AAlMAAlbAAlnAAl+AAmKAAmhAAmqAAm5AAnCAAnOAAnhAAn1AAoEAAoNAAoZAAolAAoxAAo9AApGAApSAAplAApxAAp6AAqK"
        "AAqZAAqoAAqxAArBAArTAArpAArvAAr7AAsHAAsQAAsfAAsxAAs9AAtMAAtVAAtkAAt2AAuIAAuUAAuhAAuzAAvZAAvlAAvxAAv6"
        "AAwMAAwbAAwtAAw2AAw/AAxLAAxXAAxtAAyDAAyMAAyYAAyqAAy2AAy/AAzOAAzXAAzgAAzvAAz7AA0EAA0QAA0cAA0lAA0uAA06"
        "AA1DAA1MAA1fAA1rAA13AA2GAA2SAA2bAA2qAA22AA3CAA3OAA3aAA3jAA34AA4EAA4WAA4iAA4uAA5HAA5WAA5iAA5xAA59AA6J"
        "AA6bAA6nAA6wAA68AA7FAA7OAA7aAA7jAA7yAA77AA8HAA8QAA8cAA8lAA83AA9GAA9gAA9pAA91AA+EAA+QAA+cAA+rAA+3AA/A"
        "AA/JAA/lAA/uAA/+ABAKABAcABAvABBCABBRABBaABBjABBvABB4ABCHABCTABCcABCoABC3ABDDABDPABDbABDkABDwABD8ABEF"
        "ABEOABEdABEsABFCABFYABFhABFqABF2ABGCABGUABGmABG1ABG+ABHHABHWABHiABHuABH3ABIDABITABIfABIoABIxABI+ABJK"
        "ABJWABJlABJuABJ6ABKGABKYABKkABKtABK5ABLCABLcABLyABMCABMSABMbABMnABMzABM/ABNLABNaABNmABN1ABOVABOkABOz"
        "ABO/ABPVABPeABP0ABQEABQQABQcABQvABQ4ABRHABRTABRcABRoABRxABSAABSZABSvABS/ABTVABTkABTwABT8ABUIABUXABUq"
        "ABUzABVCABVOABVaABVsABV4ABWRABWnABW2ABW/ABXIABXUABXdABXpABYIABYXABYtABY5ABZIABZfABZrABZ0ABaDABaPABae"
        "ABaqABa2ABa/ABbOABbaABbjABbsABb4ABcBABcTABcfABcoABc6ABdGABdSABdoABd0ABeAABeMABebABekABe2ABfFABfXABfg"
        "ABfzABgDABgPABgYABgkABg9ABhGABhcABh7ABiKABiQABipABi1ABjBABjTABjlABj+ABkKABkaABkqABk9ABlQABlZABllABl0"
        "ABmDABmSABmhABm0ABnAABnPABnYABnoABn7ABoEABoQABoZABolABoxABpAABpWABpiABp1ABqBABqQABqZABqpABq1ABq+ABrH"
        "ABrTABrcABroABr0ABr9ABsGABsVABshABsqABs5ABtOABtaABtpABt1ABuEABuQABucABuoABuxABvEABvRABvhABvwABv8ABwF"
        "ABwUABwgABwwABw8ABxIABxRABxgABxsABx7ABybAByqABy2ABzFABzXABzjABz4AB0EAB0TAB0cAB0lAB00AB1AAB1MAB1bAB1k"
        "AB1tAB12AB1/AB2OAB2aAB2jAB2vAB27AB3BAB3NAB3WAB3fAB3oAB30AB4AAB4JAB4SAB4eAB4qAB42AB4/AB5IAB5XAB5nAB5z"
        "AB6TAB6cAB6lAB6uAB7JAB7SAB7YAB7kAB7zAB8CAB8RAB8kAB83AB9KAB9dAB9wAB+DAB+WAB+pAB+5AB/FAB/RAB/gAB/pAB/+"
        "ACANACAmACA1ACA+ACBOACBaACBgACBpACByACB7ACCfACCyACC+ACDHACDZACDrACD+ACEHACETACEiACErACE4ACFHACFdACFs"
        "ACGBACGKACGaACGsACHLACHaACHpACHyACIEACIQACIZACIiACIoACI6ACJDACJPACJbACJ0ACJ9ACKGACKMACKVACKhACKtACK2"
        "ACK/ACLPACLfACL8ACMPACMYACMqACM0ACM6ACNDACNJACNVACNkACNzACN5ACOIACORACOjACOvACO1ACO7ACPRACPaACPjACPv"
        "ACQFACQOACQlACQxACRAACRJACRVACRkACRtACR8ACSJACSSACSbACShACS0ACTGACTTACTcACTiACToACT0ACT9ACUTACUZACUf"
        "ACUrACU3ACVAACVGACVSACVfACVoACWXACWjACWmACW1ACXBACXfACX5ACYFACYUACYdACYmACY5ACZIACZUACZgACZmACZsACaG"
        "ACaPACaVACakACawACa2ACbCACbLACbRACbXACbpACb1ACcBACcKACcjACcpACc1ACdBACdRACdgACdpACdyACeEACeWACeiACex"
        "ACe6ACfJACfYACfkACftACf2ACf/ACgIACgXACgjACg1AChCAChUAChaAChjAChpACiKACifACiuACi6ACjJACjPACjbACjkACjt"
        "ACj2ACkFACkRACkdACkvACk4AClBAClQAClcACloACl0ACl6ACmDACmMACmYACmeACmnACmtACnJACnbACnkACnwACn5ACoPACof"
        "ACoxACpHACpTACpcACpoACpxACqHACqTACqfACqrACq0ACq9ACrSACriACrrACrxACr6ACsGACsYACsnACtGACtVACtkACtwACt5"
        "ACuFACuOACuXACutACu8ACvLACvUACvjACv4ACwVACwbACw1ACw7ACxBACxQACxcACxoACx9ACyGACyMACyYACyxACy6ACzAACzM"
        "ACzbACzkACz7AC0HAC0NAC0ZAC0rAC07AC1ZAC1oAC2EAC2gAC2pAC21AC3PAC3YAC3lAC31AC3+AC4EAC4NAC4cAC4lAC4xAC5L"
        "AC5bAC5rAC6LAC6YAC6qAC69AC7TAC7mAC7zAC8AAC8TAC8jAC8wAC9GAC9SAC9bAC9rAC94AC+IAC+YAC+/AC/MAC/WAC/mAC/v"
        "AC/8ADAPADAcADBBADBXADBnADB9ADCaADC3ADDUADDkADD6ADEXADEnADE3ADFEADFUADFkADF3ADGKADGXADGdADGjADGzADG5"
        "ADG/ADHPADHbADH3ADILADIiADIyADJMADJSADJfADJsADJ5ADKKADKWADKpADK5ADLJADLZADLmADL2ADMGADMTADMgADMzADNM"
        "ADNVADNiADNvADN/ADOPADOiADOvADO/ADPPADPiADP1ADQFADQZADQmADQ5ADRJADRcADRpADRzADSAADSaADSqADTIADTbADTv"
        "ADT8ADUJADUWADUnADUzADVDADVZADVpADV9ADWNADWkADW7ADXPADXiADX5ADYTADYgADYtADY9ADZJADZTADZmADZvADaNADam"
        "ADazADbDADbTADbcADbvADb/ADcTADcgADczADdDADdpADeAADeXADeqADe6ADfLADfcADfpADf5ADgQADggADgwADhDADhWADhj"
        "ADhwADiAADiTADimADizADi8ADjTADjfADj5ADkcADkmADkzADlAADlMADlSADlYADllADl6ADmHADmUADmwADnPADniADn4ADoI"
        "ADoeADorADo+ADpaADqKADqgADq2ADrJADrcADrsADr8ADsPADsrADs7ADtLADtbADtuADuBADuRADuhADuuADu+ADvLADvbADvu"
        "ADwEADwRADwtADw9ADxNADxgADxzADyGADyZADyyADzIADzOADzbADz3AD0HAD0XAD0kAD06AD1NAD1aAD1wAD2DAD2QAD2mAD25"
        "AD3MAD3lAD3/AD4MAD4fAD4sAD5FAD5YAD5rAD54AD6FAD6bAD6uAD6+AD7mAD72AD8MAD8jAD85AD9JAD9cAD9vAD+FAD+VAD+o"
        "AD+7AD/LAD/qAEADAEATAEAjAEA2AEBMAEBfAEB5AECJAECZAECvAEDFAEDYAEDxAEEKAEEgAEEtAEFAAEFNAEFgAEFqAEGDAEGT"
        "AEGmAEG5AEHPAEHfAEHyAEIIAEIYAEIoAEJEAEJbAEJrAEJ7AEKOAEKhAEK9AELTAELmAEL2AEMJAEMpAEM8AENYAENlAEN+AEOd"
        "AEOwAEPAAEPTAEPzAEQHAEQaAEQ2AERGAERTAERmAER8AESYAESlAES4AETMAETpAETvAETyAEUSAEUmAEVAAEVaAEVtAEV8AEWQ"
        "AEWnAEW9AEXXAEXgAEXqAEXwAEX8AEYTAEYvAEZNAEZaAEZwAEaAAEaMAEacAEafAEa0AEa9AEbDAEbMAEbVAEbeAEbnAEbwAEb5"
        "AEb/AEcFAEcLAEcRAEcdAEcpAEcyAEdCAEdLAEdeAEdnAEdwAEd/AEeMAEeYAEenAEetAEe2AEe/AEfLAEfkAEfwAEf5AEf/AEgI"
        "AEgOAEgdAEgpAEgyAEg7AEhEAEhNAEhcAEhlAEhyAEh+AEiEAEiQAEiWAEifAEirAEi0AEjAAEjPAEjYAEjqAEj5AEkJAEkYAEko"
        "AEk0AElAAElJAElZAElfAEluAEl6AEmDAEmSAEmeAEmnAEmwAEm2AEm8AEnIAEnRAEnXAEnmAEnvAEn4AEoFAEoRAEodAEopAEo+"
        "AEpUAEpgAEppAEp1AEqCAEqOAEqXAEqmAEqsAEq4AErEAErTAErjAEryAEr7AEsEAEsQAEsWAEsiAEsrAEs0AEtAAEtNAEtfAEtr"
        "AEt0AEuAAEuJAEuSAEubAEurAEu6AEvGAEvVAEveAEvnAEvwAEv8AEwLAEwRAEwgAEwpAEwvAEw4AExEAExQAExZAExlAEx3AEyA"
        "AEyJAEySAEybAEykAEyqAEy2AEy8AEzTAEzfAEzlAEzuAEz0AE0AAE0YAE0nAE0tAE05AE1CAE1LAE1dAE1mAE1sAE17AE2HAE2Z"
        "AE2oAE20AE3DAE3PAE3bAE3kAE36AE4GAE4PAE4YAE4kAE4tAE48AE5CAE5IAE5OAE5aAE5mAE5vAE57AE6KAE6TAE6iAE6oAE6u"
        "AE63AE7DAE7JAE7VAE7eAE7tAE78AE8FAE8RAE8dAE8mAE8vAE87AE9EAE9QAE9WAE9iAE9xAE99AE+MAE+VAE+nAE+wAE+5AE/C"
        "AE/LAE/RAE/aAE/pAE/yAE/7AFAHAFATAFAfAFAuAFA6AFBJAFBhAFBtAFB2AFCMAFCYAFCkAFC0AFDDAFDMAFDSAFDkAFDqAFDz"
        "AFD/AFEIAFERAFEXAFEgAFEpAFE4AFFBAFFNAFFTAFFfAFFrAFFxAFF6AFGGAFGPAFGhAFGqAFGzAFG8AFHIAFHRAFHaAFHgAFHp"
        "AFH1AFIBAFIKAFIWAFIlAFI0AFJGAFJSAFJhAFJtAFJ8AFKRAFKaAFKjAFK4AFLBAFLWAFLiAFLrAFMAAFMYAFMnAFMtAFM5AFNO"
        "AFNXAFNgAFNvAFN4AFOQAFOZAFOlAFOuAFO3AFPDAFPJAFPSAFPeAFPxAFP9AFQMAFQeAFQqAFQzAFQ/AFROAFRUAFRdAFR0AFSD"
        "AFSPAFSfAFSrAFS3AFS9AFTDAFTMAFTYAFTeAFTtAFT2AFUCAFUOAFUjAFUvAFU7AFVNAFVWAFViAFVrAFV3AFWAAFWJAFWMAFWY"
        "AFWkAFWqAFWwAFXCAFXUAFXdAFXmAFXsAFYGAFYjAFY6AFZDAFZPAFZpAFaGAFagAFa3AFbRAFbrAFcAAFcJAFcgAFc6AFdJAFdP"
        "AFdeAFdtAFd5AFeCAFeUAFegAFesAFe+AFfHAFfQAFfZAFfiAFfoAFfxAFgDAFgMAFgVAFglAFg4AFhSAFhrAFiEAFiaAFiwAFjG"
        "AFjfAFj/AFkSAFkoAFlFAFlcAFl2AFmQAFmgAFmzAFnNAFneAFnyAFoNAFoeAFoyAFpNAFpeAFpyAFqNAFqhAFq4AFrWAFrpAFr/"
        "AFscAFssAFs/AFtZAFtwAFuKAFukAFu7AFvVAFvvAFwCAFwYAFw1AFxLAFxkAFyEAFyhAFzBAFzoAFz+AF0XAF03AF1HAF1aAF10"
        "AF2XAF29AF3qAF4QAF45AF5pAF6MAF6yAF7fAF8CAF8oAF9VAF9uAF+KAF+tAF/AAF/WAF/zAGAJAGAiAGBCAGBPAGBiAGB4AGCR"
        "AGCxAGDEAGDbAGD1AGEWAGEmAGE2AGFDAGFTAGFqAGF3AGGHAGGeAGGrAGG7AGHSAGHrAGICAGIVAGIrAGJIAGJZAGJtAGKPAGKc"
        "AGKsAGLDAGLWAGLsAGL/AGMSAGMoAGNFAGNYAGNrAGOBAGOeAGOuAGPBAGPbAGPxAGQBAGQUAGQuAGRIAGRlAGSJAGSWAGSmAGS9"
        "AGTdAGUMAGUiAGUyAGVCAGVVAGVvAGWGAGWcAGW2AGXTAGX3AGYRAGYuAGZSAGZlAGZ4AGaSAGavAGbTAGbgAGbwAGcHAGcXAGcq"
        "AGdEAGdUAGdkAGd6AGeXAGe0AGfRAGfeAGfuAGgFAGgbAGg0AGhUAGhnAGh9AGiaAGinAGi3AGjOAGj6AGkpAGlfAGl1AGmSAGmv"
        "AGnCAGnYAGn1AGoLAGoqAGpMAGp1AGqOAGqiAGq2AGrNAGrrAGr7AGsSAGssAGs8AGtPAGtpAGt/AGuPAGupAGu9AGvQAGvmAGwD"
        "AGwQAGwqAGxHAGxrAGyBAGyaAGy6AGzNAGzjAG0AAG0QAG0gAG0tAG1GAG1iAG2FAG2YAG2uAG3LAG3hAG36AG4aAG4qAG46AG5N"
        "AG5nAG6IAG6sAG7XAG7zAG8SAG84AG9IAG9bAG91AG+IAG+eAG+7AG/LAG/kAG/3AHANAHAqAHA3AHBHAHBeAHBuAHCBAHCbAHCy"
        "AHDVAHD7AHEoAHE4AHFIAHFVAHFrAHGIAHGoAHG7AHHLAHHbAHHuAHIIAHIYAHIrAHJFAHJVAHJoAHKCAHKSAHKoAHK/AHLZAHLp"
        "AHL2AHMGAHMTAHMjAHM6AHNQAHNjAHNwAHOAAHOXAHOkAHPAAHPfAHQFAHQVAHQoAHQ+AHRbAHR0AHSQAHSzAHTGAHTcAHT5AHUP"
        "AHUrAHVKAHVwAHWGAHWfAHW/AHXPAHXiAHYCAHYVAHYrAHZIAHZkAHaDAHapAHa2AHa+AHbGAHbQAHbdAHbxAHb5AHcA";
    inline constexpr const char* NameRefsChunks[] = {NameRefsChunk0};
    inline constexpr Packed NameRefs{NameRefsChunks, 13, 4};
    inline constexpr Text NameTexts{NameChunks, NameChunkSizes, NameRefs};

    inline constexpr char LanguageKeysChunk0[] =
        "AAhAAiAAlAAmAArAAtAAuAAyAAzAA2AA5AA6ABBABFABHABJABNABOABPABSABTABhABlABoABvAByABzAB1AB2AB5ACBACFACWA"
        "CaAClACsACuACvACzAC0AC1ADBADGADJADKADPADSADZADhADkADsADuAD1AD2AEBAEFAEJAEPAESAEUAEVAEZAEaAEhAEkAElAE"
        "nAEpAErAEvAEzAE0AE1AFBAFWAFhAFnAFpAFqAFrAFsAFtAFuAFvAFyAFzAF1AF2AF3AF5AGBAGCAGHAGJAGOAGPAGUAGVAGWAGn"
        "AGoAGpAGrAGsAGuAGyAGzAG0AG5AHBAHCAHEAHFAHHAHMAHOAHPAHSAHWAHZAHjAHqAHtAHyAHzAIBAIJAIMAITAIUAI1AJNAJOA"
        "JPAJVAJXAJhAJjAJkAJlAJnAJoAJpAJrAJsAJtAJuAJvAJxAJyAJzAJ0AJ1AJ2AJ3AKBAKFAKHAKIAKJAKLAKMAKOAKPAKSAKTAK"
        "UAKXAKZAKnAKrAKyAK6ALFALJALPALhALvAMIAMpAMvANBANIANVARlARoASBASZASiATIATxAUuAVrAWFAWUAXHAXOAXQAZDAZO"
        "AZQAZRAZTAZXAZZAZaAZhAZ0AaKAbhAgsAguAgzAg4AhKAiqAitAi6AjEAjjAjuAkPAkrAkuAltAmBAmPApBApIApYApzAqhAqnA"
        "qtAsuAs2AwkAwyAw5AxoAxwAyiAznA0CA0HA0LA0NA0OA0PA0QA0SA0ZA1iA2DA3wA5HA5IA5KA5LA5MA5NA5SA5TA5iA53BArBA"
        "yBA2BCsBCuBDyBEuBFFBHpBJiBKhBKtBMvBM1BNHBRVBTJBT5BVhBWYBXNBbvBguBg0BksBnuBpDBpNBpPBpSBpTBqyBwhBwnBwu"
        "Bw5BxBBxaBy6B0sB2LB2oB3oB3uB3yB30B5CB5DB53B66B7pCApCArCA3CA4CEmCEsCE0CGuCJiCJuCKwCKyCRBCRCCV0CWPCXIC"
        "hPCjvCmjCoSCpCCwhCwiCwjCwqCwtCw3CxECxMCxnCyFCyhCzPCzwC0BC0PC0RC0XC1qC2OC2iC3pC3rC3zC4FC5DC5MC5VC5iC5"
        "mC5oC6tC60C7rC8WDAkDAnDAoDAtDC6DDODEqDEsDF0DGvDHsDH1DH6DJDDJtDKhDKpDKuDKvDKzDK5DQkDQmDQnDQpDQrDQuDQz"
        "DSFDSGDSSDSuDSyDTFDThDToDTvDUjDUuDXDDXJDXlDXoDXzDZKDahDasDazDbsDbyDclDc2DdODguDgwDgxDiTDi3DkhDk1DmnD"
        "nIDnnDnuDovDpvDqzDrjDstDsuDsvDtJD1CD1DD1TD1XD1hD5hD6BEAnEAsEAtEAwEA1EBtECvEEOEEzEHUEHuEItEJHEJPEajEg"
        "qEgwEgyEkHEnmEntEqlEqwErrEwkEwoEwtEwxEwzEw0ExBExQExuExvEyIEylEyoEysEyzEzhE0JE0OE0VE0kE2IE2hE2qE2uE2z"
        "E3LE3nE5OE5SE55E6SE6rE6zE64E7iE8jE8yE9MFBlFCtFCvFCyFC0FD4FEUFEnFE2FFsFFyFGIFGJFGZFGoFHnFHrFIJFJWFJpF"
        "KNFKtFLMFLxFM2FNNFSNFThFWiFXEFgpFijFm3Fn0FquFwlFwsFwyFwzFxQF61GAsGHSGHnGQvGQwGQ2GRCGZMGalGgwGhMGiuGj"
        "oGquGsYGtB";
    inline constexpr const char* LanguageKeysChunks[] = {LanguageKeysChunk0};
    inline constexpr Packed LanguageKeys{LanguageKeysChunks, 13, 3};

    inline constexpr char LanguageNamesChunk0[] =
        "AABAACAAHAAJAANAARAASAAWAAgAAkAAmAAnAAoAAuAAzAA3AA9AA+AA/ABAABEABLABRABUABgABiABrABuABvABwABxAB1ACAA"
        "CDACGACKACMACOACPACRACSACUACYACZACbACcACeAClACmACtACwACzAC7AC9AC/ADEADFADKADLADOADPADSADTADUADXADYAD"
        "ZADaADbADfADgADhADiADjADpADqAD3AD9AD+AD/AEBAEDAEFAEGAELAEPAETAEWAEXAEaAEbAEgAEjAEkAEpAEqAEwAExAE4AFG"
        "AFKAFLAFOAFPAFQAFWAFYAFZAFfAFjAFnAFoAFrAFtAFwAFzAF1AF5AF8AF+AGDAGEAGKAGLAGMAGPAGYAGaAGgAGhAGjAGpAGqA"
        "GrAGvAGyAG0AG9AHAAHCAHHAHJAHNAHPAHQAHSAHXAHZAHbAHcAHfAHhAHjAHnAHoAHuAHwAH1AH3AH5AH8AH/AIEAIFAIJAILAI"
        "NAIRAITAIXAIZAIcAIdAIfAIhAIjAImAIsAIvAI2AI3AI6AI/AJAAADAAEAAFAAGAAIAAKAALAAMAAOAAPAAQAATAAUAAVAAYAAZ"
        "AAaAAbAAcAAdAAeAAfAAhAAiAAjAAlAApAAqAArAAsAAtAAvAAwAAxAAyAA0AA1AA2AA4AA5AA6AA7AA8ABBABCABDABFABGABHA"
        "BIABJABKABMABNABOABPABQABSABTABVABWABXABYABZABaABbABcABdABeABfABhABjABkABlABmABnABoABpABqABsABtAByAB"
        "zAB0AB3AB4AB5AB6AB7AB8AB9AB+AB/ACBACCACEACFACHACIACJACLACNACTACWACXACaACdACfACgAChACiACjACkACnACoACp"
        "ACqACrACsACuACvACxACyAC0AC1AC2AC3AC4AC5AC6AC8AC+ADAADBADCADDADGADHADIADJADMADNADQADRADVADWADcADdADeA"
        "DkADlADmADnADoADrADsADtADuADvADwADxADyADzAD0AD1AD2AD4AD5AD6AD7AD8AEAAECAEEAEHAEIAEJAEKAEMAENAEOAEQAE"
        "RAESAEUAEVAEYAEZAEcAEdAEeAEfAEhAEiAElAEmAEnAEoAErAEsAEtAEuAEvAEyAEzAE0AE1AE2AE3AE5AE6AE7AE8AE9AE+AE/"
        "AFAAFBAFCAFDAFEAFFAFHAFIAFJAFMAFNAFRAFSAFTAFUAFVAFXAFaAFbAFcAFdAFeAFgAFhAFiAFkAFlAFmAFpAFsAFuAFvAFyA"
        "F0AF2AF3AF4AF6AF7AF9AF/AGAAGBAGCAGFAGGAGHAGIAGJAGNAGOAGQAGRAGSAGTAGUAGVAGWAGXAGZAGbAGcAGdAGeAGfAGkAG"
        "lAGmAGnAGoAGtAGuAGwAGxAGzAG1AG2AG3AG4AG5AG6AG7AG8AG+AG/AHBAHDAHEAHFAHGAHIAHKAHLAHMAHOAHRAHTAHUAHVAHW"
        "AHYAHaAHdAHeAHgAHiAHkAHlAHmAHqAHrAHsAHtAHvAHxAHyAHzAH0AH2AH4AH6AH7AH9AH+AIAAIBAICAIDAIGAIHAIIAIKAIMA"
        "IOAIPAIQAISAIUAIVAIWAIYAIaAIbAIeAIgAIiAIkAIlAInAIoAIpAIqAIrAItAIuAIwAIxAIyAIzAI0AI1AI4AI5AI7AI8AI9AI"
        "+AJBAJCAJD";
    inline constexpr const char* LanguageNamesChunks[] = {LanguageNamesChunk0};
    inline constexpr Packed LanguageNames{LanguageNamesChunks, 13, 3};

    inline constexpr const uint64_t* TaggedKeys = nullptr;

    inline constexpr const uint16_t* TaggedNames = nullptr;

    inline constexpr char RegionKeysChunk0[] =
        "AAeAAfAAgAAhAAiAAkAAnAAoAAqAAsAAtAAuAAvAAwAAyAAzAA1AA3AA4AA6AA7AA8AA9AA+AA/ABAABCABDABEABFABHABIABJA"
        "BKABMABNABPABQABSABUABVABXABYABZABaABcABdABeABfABgABhABjABmABnABoABpABqABrABxABzAB2AB3AB5AB7ACGACIAC"
        "KACMACOACPACZACaACbACcAChACrACsACtACvACxAC0AC+AC/ADBADCADDADEADFADGADJADKADLADNADOADPADQADRADSADUADW"
        "ADjADlADmADqADsADtAD2AD3AD4AD/AEAAEBAECAEEAEFAEGAEHAETAEbAEdAEeAEuAEwAExAEyAE2AE3AE5AE7AFAAFCAFDAFFA"
        "FGAFHAFNAFPAFWAFXAFYAFZAFaAFdAFgAFiAFjAFkAFlAFmAFnAFqAFrAFsAFtAFuAFvAFwAFxAFyAFzAF0AF1AF2AF3AF4AF5AF"
        "7AF9AF/AGAAGBAGDAGGAGJAGKAGMAGPAGUAGiAGxAG1AG2AG3AG4AG7AG8AG9AG+AHCAHDAHEAHHAHJAHMAHaAHrAH1AH5AH7AH9"
        "AICAIDAIEAIFAIGAIIAIJAIKAILAIMAINAIOAIPAIQAITAIUAIVAIXAIZAIaAIbAIdAIfAIgAIiAIjAIkAImAInAIoAIpAIqAIrA"
        "IuAIwAIyAIzAI2AI4AI+AJEAJFAJKAJQAJRAJTAJVAJXAJZAJbAJgAJnAJzAKAAKJAKKAKTAKoAK3AK/ALLALVALYALaALbALcAL"
        "eALiALkALmALnALoALqALrALsALuAL2AL3AL7AL8AMAAMOAMPAMSAMWANnANoANqANvANwANzAN0AOjAR8";
    inline constexpr const char* RegionKeysChunks[] = {RegionKeysChunk0};
    inline constexpr Packed RegionKeys{RegionKeysChunks, 13, 3};

    inline constexpr char RegionNamesChunk0[] =
        "AJjAJkAJlAJmAJnAJoAJpAJqAJrAJsAJtAJuAJvAJwAJxAJyAJzAJ0AJ1AJ2AJ3AJ4AJ5AJ6AJ7AJ8AJ9AJ+AJ/AKAAKBAKCAKDA"
        "KEAKFAKGAKHAKIAKJAKKAKLAKMAKNAKOAKPAKQAKRAKSAKTAKUAKVAKWAKXAKYAKZAKaAKbAKcAKdAKeAKfAKgAKhAKiAKjAKkAK"
        "lAKmAKnAKoAKpAKqAKrAKsAKtAKuAKvAKwAKxAKyAKzAK0AK1AK2AK3AK4AK5AK6AK7AK8AK9AK+AK/ALAALBALCALDALEALFALG"
        "ALHALIALJALKALLALMALNALOALPALQALRALSALTALUALVALWALXALYALZALaALbALcALdALeALfALgALhALiALjALkALlALmALnA"
        "LoALpALqALrALsALtALuALvALwALxALyALzAL0AL1AL2AL3AL4AL5AL6AL7AL8AL9AL+AL/AMAAMBAMCAMDAMEAMFAMGAMHAMIAM"
        "JAMKAMLAMMAMNAMOAMPAMQAMRAMSAMTAMUAMVAMWAMXAMYAMZAMaAMbAMcAMdAMeAMfAMgAMhAMiAMjAMkAMlAMmAMnAMoAMpAMq"
        "AMrAMsAMtAMuAMvAMwAMxAMyAMzAM0AM1AM2AM3AM4AM5AM6AM7AM8AM9AM+AM/ANAANBANCANDANEANFANGANHANIANJANKANLA"
        "NMANNANOANPANQANRANSANTANUANVANWANXANYANZANaANbANcANdANeANfANgANhANiANjANkANlANmANnANoANpAJEAJFAJGAJ"
        "HAJIAJJAJKAJLAJMAJNAJOAJPAJQAJRAJSAJTAJUAJVAJWAJXAJYAJZAJaAJbAJcAJdAJeAJfAJgAJhAJi";
    inline constexpr const char* RegionNamesChunks[] = {RegionNamesChunk0};
    inline constexpr Packed RegionNames{RegionNamesChunks, 13, 3};

    inline constexpr char ScriptKeysChunk0[] =
        "AJGNAJgrAJ0CAMgiAMguAMmpAMmuANp0AQWJAQW1AQZzAQaLARXHATEzAT4PAUgoAUgpAVTpAVUEAYVtAYXTAYZJAaAtAaCyAaZU"
        "Ab4UAcJUAeZMAeZTAhbBAk5UAlYMAp8kAp8oAp8wArBBAtEJA5XrA5XyA7AnA76IA8guA8irA9VSA9ZVBAXCBAXHBAXJBAXPBAXT"
        "BAXUBBRSBCZBBDK3BDXHBEl0BFXHBLiTBNAsBQWvBQbBBUAuBVZDBYWJBYXBBaAyBaGyBaHqBbiBBb5FBcCsBdEJBgXBBgXvBgaG"
        "BgaHBgaOBhYDBiWiBiXBBiXCBiZ1Bj2hBmRpBmSJBoUKBoXEBoXJBochBpXEBpZDBpZPBrMtBr3HBr3uBsnvBtCpBuWyBwZCBwg0"
        "ByziBy3vB00VB5wtB7BrB8loB8shB82hCAWNCBZNCCAnCCGJCCGQCCGWCCHYCDJECEqJCIQnCSnHCT0HCT5PCVXSCYWyCYZBCYZC"
        "CYayCZ3XCaA3CaJECaSECaXECaXICb5BCdXECeWPCeZDCeZFCeZKCeZOCgTiCgVyCgWFCgWVCgWsCgXHCgbUChWVChXHChnHCh2H"
        "CiAhCiApCiRUCiZICpwyCwUpCyZwC4ZBC72FDECvDE64DKUpDSXIDTaIDU8lDU8tDWMYDWc5DWta";
    inline constexpr const char* ScriptKeysChunks[] = {ScriptKeysChunk0};
    inline constexpr Packed ScriptKeys{ScriptKeysChunks, 13, 4};

    inline constexpr char ScriptNamesChunk0[] =
        "ANqANrANsANtANuANvANwANxANyANzAN0AN1AN2AN3AN4AN5AN6AN7AN8AN9AN+AN/AOAAOBAOCAODAOEAOFAOGAOHAOIAOJAOKA"
        "OLAOMAONAOOAOPAOQAORAOSAOTAOUAOVAOWAOXAOYAOZAOaAObAOcAOdAOeAOfAOgAK6AOhAOiAOjAOkAOlAOmAOnAOoAOpAOqAO"
        "rAOsAOtAOuAOvAOwAOxAOyAOzAO0AO1AO2AO3AO4AO5AO6AO7AO8AO9AO+AO/APAAPBAPCAPDAPEAPFAPGAPHAPIAPJAPKAPLAPM"
        "APNAPOAPPAPQAPRAPSAPTAPUAPVAPWAPXAPYAPZAPaAPbAPcAPdAPeAPfAPgAPhAPiAPjAPkAPlAPmAPnAPoAPpAPqAPrAPsAPtA"
        "PuAPvAPwAPxAPyAPzAP0AP1AP2AP3AP4AP5AP6AP7AP8AP9AP+AP/AQAAQBAQCAQDAQEAQFAQGAQHAQIAQJAQKAQLAQMAQNAQOAQ"
        "PAQQAQR";
    inline constexpr const char* ScriptNamesChunks[] = {ScriptNamesChunk0};
    inline constexpr Packed ScriptNames{ScriptNamesChunks, 13, 3};

    inline constexpr char AloneKeysChunk0[] =
        "BAXTBAXU";
    inline constexpr const char* AloneKeysChunks[] = {AloneKeysChunk0};
    inline constexpr Packed AloneKeys{AloneKeysChunks, 13, 4};

    inline constexpr char AloneNamesChunk0[] =
        "AQSAQT";
    inline constexpr const char* AloneNamesChunks[] = {AloneNamesChunk0};
    inline constexpr Packed AloneNames{AloneNamesChunks, 13, 3};

    inline constexpr char CurrencyKeysChunk0[] =
        "ASkATOAWMAWkAXhAZTAakAbnAdOAgtAhEAiUAjuAkEAkmAmkAnEAniApMApkAqOArwAsuAtEAwkAyGA0GA2QA3ZA3wA5DA6wA7FA"
        "9LBFGBFrBHwBNEBTwBZOBaCBayBlEBlwBxQBysB0TB0wB2kB3GB6RB8kCFkCHMCKHCKmCSSCWTCXSCYkCZSCZrCmkCnkCoZCyzCz"
        "zC0SC2mC4XC5XC7kC8kC9UDArDBQDFyDJEDJsDMkDQkDSMDThDVkDWrDXUDXwDZVDayDbSDbrDcODcyDdODgkDjuDkvDnrDoSDtE"
        "D2yEAiECuEDrEEQEFyEGOEMnEQyEnuEpkEqiErmEwyExEExyEyHEyrEzkE0QE2FE3zE5EE5wE6OE8wE9MFECFFTFG0FHEFHwFJZF"
        "KEFLkFNTFQoFT4FZkFc1FdTFizFnEFq2F50GAmGAnGA1GBBGBCGBDGBEGBkGCSGC1GDPGDVGHmGIEGIGGIUGJFGKTGMYGSyGgyGm"
        "3";
    inline constexpr const char* CurrencyKeysChunks[] = {CurrencyKeysChunk0};
    inline constexpr Packed CurrencyKeys{CurrencyKeysChunks, 13, 3};

    inline constexpr char CurrencyNamesChunk0[] =
        "AQUAAAAAAAAAAAAAAAAAAAQVAAAAAAAAAAAAAAAAAAAQWAAAAAAAAAAAAAAAAAAAQXAAAAAAAAAAAAAAAAAAAQYAAAAAAAAAAAAA"
        "AAAAAAQZAAAAAAAAAAAAAAAAAAAQaAAAAAAAAAAAAAAAAAAAQbAAAAAAAAAAAAAAAAAAAQcAAAAAAAAAAAAAAAAAAAQdAAAAAAAA"
        "AAAAAAAAAAAQeAAAAAAAAAAAAAAAAAAAQfAAAAAAAAAAAAAAAAAAAQgAAAAAAAAAAAAAAAAAAAQhAAAAAAAAAAAAAAAAAAAQiAAA"
        "AAAAAAAAAAAAAAAAQjAAAAAAAAAAAAAAAAAAAQkAAAAAAAAAAAAAAAAAAAQlAAAAAAAAAAAAAAAAAAAQmAAAAAAAAAAAAAAAAAAA"
        "QnAAAAAAAAAAAAAAAAAAAQoAAAAAAAAAAAAAAAAAAAQpAAAAAAAAAAAAAAAAAAAQqAAAAAAAAAAAAAAAAAAAQrAAAAAAAAAAAAAA"
        "AAAAAQsAAAAAAAAAAAAAAAAAAAQtAAAAAAAAAAAAAAAAAAAQuAAAAAAAAAAAAAAAAAAAQvAAAAAAAAAAAAAAAAAAAQwAAAAAAAAA"
        "AAAAAAAAAAQxAAAAAAAAAAAAAAAAAAAQyAAAAAAAAAAAAAAAAAAAQzAAAAAAAAAAAAAAAAAAAQ0AAAAAAAAAAAAAAAAAAAQ1AAAA"
        "AAAAAAAAAAAAAAAQ2AAAAAAAAAAAAAAAAAAAQ3AAAAAAAAAAAAAAAAAAAQ4AAAAAAAAAAAAAAAAAAAQ5AAAAAAAAAAAAAAAAAAAQ"
        "6AAAAAAAAAAAAAAAAAAAQ7AAAAAAAAAAAAAAAAAAAQ8AAAAAAAAAAAAAAAAAAAQ9AAAAAAAAAAAAAAAAAAAQ+AAAAAAAAAAAAAAA"
        "AAAAQ/AAAAAAAAAAAAAAAAAAARAAAAAAAAAAAAAAAAAAAARBAAAAAAAAAAAAAAAAAAARCAAAAAAAAAAAAAAAAAAARDAAAAAAAAAA"
        "AAAAAAAAAREAAAAAAAAAAAAAAAAAAARFAAAAAAAAAAAAAAAAAAARGAAAAAAAAAAAAAAAAAAARHAAAAAAAAAAAAAAAAAAARIAAAAA"
        "AAAAAAAAAAAAAARJAAAAAAAAAAAAAAAAAAARKAAAAAAAAAAAAAAAAAAARLAAAAAAAAAAAAAAAAAAARMAAAAAAAAAAAAAAAAAAARN"
        "AAAAAAAAAAAAAAAAAAAROAAAAAAAAAAAAAAAAAAARPAAAAAAAAAAAAAAAAAAARQAAAAAAAAAAAAAAAAAAARRAAAAAAAAAAAAAAAA"
        "AAARSAAAAAAAAAAAAAAAAAAARTAAAAAAAAAAAAAAAAAAARUAAAAAAAAAAAAAAAAAAARVAAAAAAAAAAAAAAAAAAARWAAAAAAAAAAA"
        "AAAAAAAARXAAAAAAAAAAAAAAAAAAARYAAAAAAAAAAAAAAAAAAARZAAAAAAAAAAAAAAAAAAARaAAAAAAAAAAAAAAAAAAARbAAAAAA"
        "AAAAAAAAAAAAARcAAAAAAAAAAAAAAAAAAARdAAAAAAAAAAAAAAAAAAAReAAAAAAAAAAAAAAAAAAARfAAAAAAAAAAAAAAAAAAARgA"
        "AAAAAAAAAAAAAAAAAARhAAAAAAAAAAAAAAAAAAARiAAAAAAAAAAAAAAAAAAARjAAAAAAAAAAAAAAAAAAARkAAAAAAAAAAAAAAAAA"
        "AARlAAAAAAAAAAAAAAAAAAARmAAAAAAAAAAAAAAAAAAARnAAAAAAAAAAAAAAAAAAARoAAAAAAAAAAAAAAAAAAARpAAAAAAAAAAAA"
        "AAAAAAARqAAAAAAAAAAAAAAAAAAARrAAAAAAAAAAAAAAAAAAARsAAAAAAAAAAAAAAAAAAARtAAAAAAAAAAAAAAAAAAARuAAAAAAA"
        "AAAAAAAAAAAARvAAAAAAAAAAAAAAAAAAARwAAAAAAAAAAAAAAAAAAARxAAAAAAAAAAAAAAAAAAARyAAAAAAAAAAAAAAAAAAARzAA"
        "AAAAAAAAAAAAAAAAAR0AAAAAAAAAAAAAAAAAAAR1AAAAAAAAAAAAAAAAAAAR2AAAAAAAAAAAAAAAAAAAR3AAAAAAAAAAAAAAAAAA"
        "AR4AAAAAAAAAAAAAAAAAAAR5AAAAAAAAAAAAAAAAAAAR6AAAAAAAAAAAAAAAAAAAR7AAAAAAAAAAAAAAAAAAAR8AAAAAAAAAAAAA"
        "AAAAAAR9AAAAAAAAAAAAAAAAAAAR+AAAAAAAAAAAAAAAAAAAR/AAAAAAAAAAAAAAAAAAASAAAAAAAAAAAAAAAAAAAASBAAAAAAAA"
        "AAAAAAAAAAASCAAAAAAAAAAAAAAAAAAASDAAAAAAAAAAAAAAAAAAASEAAAAAAAAAAAAAAAAAAASFAAAAAAAAAAAAAAAAAAASGAAA"
        "AAAAAAAAAAAAAAAASHAAAAAAAAAAAAAAAAAAASIAAAAAAAAAAAAAAAAAAASJAAAAAAAAAAAAAAAAAAASKAAAAAAAAAAAAAAAAAAA"
        "SLAAAAAAAAAAAAAAAAAAASMAAAAAAAAAAAAAAAAAAASNAAAAAAAAAAAAAAAAAAASOAAAAAAAAAAAAAAAAAAASPAAAAAAAAAAAAAA"
        "AAAAASQAAAAAAAAAAAAAAAAAAASRAAAAAAAAAAAAAAAAAAASSAAAAAAAAAAAAAAAAAAASTAAAAAAAAAAAAAAAAAAASUAAAAAAAAA"
        "AAAAAAAAAASVAAAAAAAAAAAAAAAAAAASWAAAAAAAAAAAAAAAAAAASXAAAAAAAAAAAAAAAAAAASYAAAAAAAAAAAAAAAASYASZAAAA"
        "AAAAAAAAAAAAAAASaAAAAAAAAAAAAAAAAAAASbAAAAAAAAAAAAAAAAAAAScAAAAAAAAAAAAAAAAAAASdAAAAAAAAAAAAAAAAAAAS"
        "eAAAAAAAAAAAAAAAAAAASfAAAAAAAAAAAAAAAAAAASgAAAAAAAAAAAAAAAAAAAShAAAAAAAAAAAAAAAAAAASiAAAAAAAAAAAAAAA"
        "AAAASjAAAAAAAAAAAAAAAAAAASkAAAAAAAAAAAAAAAAAAASlAAAAAAAAAAAAAAAAAAASmAAAAAAAAAAAAAAAAAAASnAAAAAAAAAA"
        "AAAAAAAAASoAAAAAAAAAAAAAAAAAAASpAAAAAAAAAAAAAAAAAAASqAAAAAAAAAAAAAAAAAAASrAAAAAAAAAAAAAAAAAAASsAAAAA"
        "AAAAAAAAAAAAAAStAAAAAAAAAAAAAAAAAAASuAAAAAAAAAAAAAAAAAAASvAAAAAAAAAAAAAAAAAAASwAAAAAAAAAAAAAAAAAAASx"
        "AAAAAAAAAAAAAAAAAAASyAAAAAAAAAAAAAAAAAAASzAAAAAAAAAAAAAAAAAAAS0AAAAAAAAAAAAAAAAAAAS1AAAAAAAAAAAAAAAA"
        "AAAS2AAAAAAAAAAAAAAAAAAAS3AAAAAAAAAAAAAAAAS4AS5AAAAAAAAAAAAAAAAAAAS6AAAAAAAAAAAAAAAAAAAS7AAAAAAAAAAA"
        "AAAAAAA";
    inline constexpr const char* CurrencyNamesChunks[] = {CurrencyNamesChunk0};
    inline constexpr Packed CurrencyNames{CurrencyNamesChunks, 13, 3};

    inline constexpr char ZoneKeysChunk0[] =
        "AAAAABAACAADAAEAAFAAGAAHAAIAAJAAKAALAAMAANAAOAAPAAQAARAASAATAAUAAVAAWAAXAAYAAZAAaAAbAAcAAdAAeAAfAAgA"
        "AhAAiAAjAAkAAlAAmAAnAAoAApAAqAArAAsAAtAAuAAvAAwAAxAAyAAzAA0AA1AA2AA3AA4AA5AA6AA7AA8AA9AA+AA/ABAABBAB"
        "CABDABEABFABGABHABIABJABKABLABMABNABOABPABQABRABSABTABUABVABWABXABYABZABaABbABcABdABeABfABgABhABiABj"
        "ABkABlABmABnABoABpABqABrABsABtABuABvABwABxAByABzAB0AB1AB2AB3AB4AB5AB6AB7AB8AB9AB+AB/ACAACBACCACDACEA"
        "CFACGACHACIACJACKACLACMACNACOACPACQACRACSACTACUACVACWACXACYACZACaACbACcACdACeACfACgAChACiACjACkAClAC"
        "mACnACoACpACqACrACsACtACuACvACwACxACyACzAC0AC1AC2AC3AC4AC5AC6AC7AC8AC9AC+AC/ADAADBADCADDADEADFADGADH"
        "ADIADJADKADLADMADNADOADPADQADRADSADTADUADVADWADXADYADZADaADbADcADdADeADfADgADhADiADjADkADlADmADnADoA"
        "DpADqADrADsADtADuADvADwADxADyADzAD0AD1AD2AD3AD4AD5AD6AD7AD8AD9AD+AD/AEAAEBAECAEDAEEAEFAEGAEHAEIAEJAE"
        "KAELAEMAENAEOAEPAEQAERAESAETAEUAEVAEWAEXAEYAEZAEaAEbAEcAEdAEeAEfAEgAEhAEiAEjAEkAElAEmAEnAEoAEpAEqAEr"
        "AEsAEtAEuAEvAEwAExAEyAEzAE0AE1AFRAFSAFTAFUAFVAFWAFXAFYAFZAFaAFbAFcAFdAFeAFfAFgAFhAFiAFjAFkAFlAFmAFnA"
        "FoAFpAFqAFrAFsAFtAFuAFvAFwAFxAFyAFzAF0AF1AF2AF3AF4AF5AF6AF7AF8AF9AF+AF/AGAAGBAGCAGDAGEAGFAGGAGHAGIAG"
        "JAGKAGLAGMAGNAGOAGPAGQAGRAGSAGTAGUAGVAGWAGXAGYAGZAGaAGbAGcAGdAGeAGfAGgAGhAGiAGjAGkAGlAGmAGnAGoAGpAGq"
        "AGrAGsAGtAGuAGvAGwAGxAGyAGzAG0AG1AG2AG3AG4AG5AG6AG7AG8AG9";
    inline constexpr const char* ZoneKeysChunks[] = {ZoneKeysChunk0};
    inline constexpr Packed ZoneKeys{ZoneKeysChunks, 13, 3};

    inline constexpr char ZoneNamesChunk0[] =
        "AUnAAAAAAAAAAAAAAAAAAAVPAAAAAAAAAAAAAAAAAAAVDAAAAAAAAAAAAAAAAAAAU6AAAAAAAAAAAAAAAAAAAVAAAAAAAAAAAAAA"
        "AAAAAAWQAAAAAAAAAAAAAAAAAAAUkAAAAAAAAAAAAAAAAAAAVUAAAAAAAAAAAAAAAAAAAVZAAAAAAAAAAAAAAAAAAAWZAAAAAAAA"
        "AAAAAAAAAAAUlAAAAAAAAAAAAAAAAAAATyAAAAAAAAAAAAAAAAAAAU+AAAAAAAAAAAAAAAAAAAWIAAAAAAAAAAAAAAAAAAAVBAAA"
        "AAAAAAAAAAAAAAAAVVAAAAAAAAAAAAAAAAAAAXtAAAAAAAAAAAAAAAAAAAYEAAAAAAAAAAAAAAAAAAAKfAAAAAAAAAAAAAAAAAAA"
        "UsAAAAAAAAAAAAAAAAAAAU/AAAAAAAAAAAAAAAAAAAXsAAAAAAAAAAAAAAAAAAAUIAAAAAAAAAAAAAAAAAAAY2AAAAAAAAAAAAAA"
        "AAAAAY0AAAAAAAAAAAAAAAAAAAXwAAAAAAAAAAAAAAAAAAAYHAAAAAAAAAAAAAAAAAAAXmAAAAAAAAAAAAAAAAAAAXiAAAAAAAAA"
        "AAAAAAAAAAUiAAAAAAAAAAAAAAAAAAAWtAAAAAAAAAAAAAAAAAAAVKAAAAAAAAAAAAAAAAAAAX4AAAAAAAAAAAAAAAAAAATGAAAA"
        "AAAAAAAAAAAAAAAUjAAAAAAAAAAAAAAAAAAAY1AAAAAAAAAAAAAAAAAAAVWAAAAAAAAAAAAAAAAAAAWoAAAAAAAAAAAAAAAAAAAW"
        "EAAAAAAAAAAAAAAAAAAAX0AAAAAAAAAAAAAAAAAAAXuAAAAAAAAAAAAAAAAAAAWDAAAAAAAAAAAAAAAAAAAVuAAAAAAAAAAAAAAA"
        "AAAAX2AAAAAAAAAAAAAAAAAAAWrAAAAAAAAAAAAAAAAAAAWXAAAAAAAAAAAAAAAAAAATwAAAAAAAAAAAAAAAAAAATzAAAAAAAAAA"
        "AAAAAAAAAXxAAAAAAAAAAAAAAAAAAAWHAAAAAAAAAAAAAAAAAAAX+AAAAAAAAAAAAAAAAAAAWpAAAAAAAAAAAAAAAAAAAYKAAAAA"
        "AAAAAAAAAAAAAAYMAAAAAAAAAAAAAAAAAAATDAAAAAAAAAAAAAAAAAAATCAAAAAAAAAAAAAAAAAAAT/AAAAAAAAAAAAAAAAAAATV"
        "AAAAAAAAAAAAAAAAAAATRAAAAAAAAAAAAAAAAAAATYAAAAAAAAAAAAAAAAAAATTAAAAAAAAAAAAAAAAAAATWAAAAAAAAAAAAAAAA"
        "AAATaAAAAAAAAAAAAAAAAAAATUAAAAAAAAAAAAAAAAAAAJxAAAAAAAAAAAAAAAAAAAXFAAAAAAAAAAAAAAAAAAAUBAAAAAAAAAAA"
        "AAAAAAAAWfAAAAAAAAAAAAAAAAAAAJ1AAAAAAAAAAAAAAAAAAAT+AAAAAAAAAAAAAAAAAAAKIAAAAAAAAAAAAAAAAAAAUfAAAAAA"
        "AAAAAAAAAAAAAT5AAAAAAAAAAAAAAAAAAAUvAAAAAAAAAAAAAAAAAAAYSAAAAAAAAAAAAAAAAAAATcAAAAAAAAAAAAAAAAAAAUTA"
        "AAAAAAAAAAAAAAAAAAT9AAAAAAAAAAAAAAAAAAAWlAAAAAAAAAAAAAAAAAAAYrAAAAAAAAAAAAAAAAAAATXAAAAAAAAAAAAAAAAA"
        "AAVOAAAAAAAAAAAAAAAAAAAV3AAAAAAAAAAAAAAAAAAAYYAAAAAAAAAAAAAAAAAAAWeAAAAAAAAAAAAAAAAAAAWcAAAAAAAAAAAA"
        "AAAAAAAUYAAAAAAAAAAAAAAAAAAATbAAAAAAAAAAAAAAAAAAAKWAAAAAAAAAAAAAAAAAAAUQAAAAAAAAAAAAAAAAAAAT7AAAAAAA"
        "AAAAAAAAAAAAKZAAAAAAAAAAAAAAAAAAAVTAAAAAAAAAAAAAAAAAAAUKAAAAAAAAAAAAAAAAAAAUPAAAAAAAAAAAAAAAAAAAYUAA"
        "AAAAAAAAAAAAAAAAAYkAAAAAAAAAAAAAAAAAAAKhAAAAAAAAAAAAAAAAAAAURAAAAAAAAAAAAAAAAAAAT2AAAAAAAAAAAAAAAAAA"
        "AM8AAAAAAAAAAAAAAAAAAAUOAAAAAAAAAAAAAAAAAAAUCAAAAAAAAAAAAAAAAAAAUeAAAAAAAAAAAAAAAAAAAVRAAAAAAAAAAAAA"
        "AAAAAAUdAAAAAAAAAAAAAAAAAAAX1AAAAAAAAAAAAAAAAAAAK2AAAAAAAAAAAAAAAAAAAK/AAAAAAAAAAAAAAAAAAALDAAAAAAAA"
        "AAAAAAAAAAAU8AAAAAAAAAAAAAAAAAAALGAAAAAAAAAAAAAAAAAAAUcAAAAAAAAAAAAAAAAAAAUwAAAAAAAAAAAAAAAAAAAWbAAA"
        "AAAAAAAAAAAAAAAAYdAAAAAAAAAAAAAAAAAAAYfAAAAAAAAAAAAAAAAAAAYbAAAAAAAAAAAAAAAAAAAYcAAAAAAAAAAAAAAAAAAA"
        "YiAAAAAAAAAAAAAAAAAAAYaAAAAAAAAAAAAAAAAAAAYeAAAAAAAAAAAAAAAAAAAYgAAAAAAAAAAAAAAAAAAAUMAAAAAAAAAAAAAA"
        "AAAAAUaAAAAAAAAAAAAAAAAAAALZAAAAAAAAAAAAAAAAAAATZAAAAAAAAAAAAAAAAAAAYPAAAAAAAAAAAAAAAAAAAYjAAAAAAAAA"
        "AAAAAAAAAAT1AAAAAAAAAAAAAAAAAAAT0AAAAAAAAAAAAAAAAAAAW1AAAAAAAAAAAAAAAAAAAYRAAAAAAAAAAAAAAAAAAAYhAAAA"
        "AAAAAAAAAAAAAAAXyAAAAAAAAAAAAAAAAAAAUDAAAAAAAAAAAAAAAAAAAWuAAAAAAAAAAAAAAAAAAAT6AAAAAAAAAAAAAAAAAAAW"
        "LAAAAAAAAAAAAAAAAAAAWWAAAAAAAAAAAAAAAAAAAWjAAAAAAAAAAAAAAAAAAAWdAAAAAAAAAAAAAAAAAAATSAAAAAAAAAAAAAAA"
        "AAAAYZAAAAAAAAAAAAAAAAAAAWkAAAAAAAAAAAAAAAAAAAYQAAAAAAAAAAAAAAAAAAAWiAAAAAAAAAAAAAAAAAAAW+AAAAAAAAAA"
        "AAAAAAAAAUbAAAAAAAAAAAAAAAAAAAWhAAAAAAAAAAAAAAAAAAAYmAAAAAAAAAAAAAAAAAAAWYAAAAAAAAAAAAAAAAAAAUGAAAAA"
        "AAAAAAAAAAAAAAYlAAAAAAAAAAAAAAAAAAAYLAAAAAAAAAAAAAAAAAAAUFAAAAAAAAAAAAAAAAAAAYVAAAAAAAAAAAAAAAAAAAYX"
        "AAAAAAAAAAAAAAAAAAAYWAAAAAAAAAAAAAAAAAAAWgAAAAAAAAAAAAAAAAAAAMWAAAAAAAAAAAAAAAAAAAXvAAAAAAAAAAAAAAAA"
        "AAAYTAAAAAAAAAAAAAAAAAAAVdAAAAAAAAAAAAAAAAAAAYBAAAAAAAAAAAAAAAAAAAT4AAAAAAAAAAAAAAAAAAAMfAAAAAAAAAAA"
        "AAAAAAAAUqAAAAAAAAAAAAAAAAAAAUXAAAAAAAAAAAAAAAAAAAUEAAAAAAAAAAAAAAAAAAAUUAAAAAAAAAAAAAAAAAAAUWAAAAAA"
        "AAAAAAAAAAAAAT3AAAAAAAAAAAAAAAAAAAT8AAAAAAAAAAAAAAAAAAAUrAAAAAAAAAAAAAAAAAAAU5AAAAAAAAAAAAAAAAAAAUAA"
        "AAAAAAAAAAAAAAAAAAVSAAAAAAAAAAAAAAAAAAAYOAAAAAAAAAAAAAAAAAAAJ9AAAAAAAAAAAAAAAAAAAUgAAAAAAAAAAAAAAAAA"
        "AAV0AAAAAAAAAAAAAAAAAAALpAAAAAAAAAAAAAAAAAAAYtAAAAAAAAAAAAAAAAAAAYqAAAAAAAAAAAAAAAAAAAUSAAAAAAAAAAAA"
        "AAAAAAAVbAAAAAAAAAAAAAAAAAAAVQAAAAAAAAAAAAAAAAAAAWaAAAAAAAAAAAAAAAAAAAUZAAAAAAAAAAAAAAAAAAAYsAAAAAAA"
        "AAAAAAAAAAAAUNAAAAAAAAAAAAAAAAAAAULAAAAAAAAAAAAAAAAAAAUVAAAAAAAAAAAAAAAAAAAYNAAAAAAAAAAAAAAAAAAATOAA"
        "AAAAAAAAAAAAAAAAATMAAAAAAAAAAAAAAAAAAATPAAAAAAAAAAAAAAAAAAATpAAAAAAAAAAAAAAAAAAATLAAAAAAAAAAAAAAAAAA"
        "ATQAAAAAAAAAAAAAAAAAAATIAAAAAAAAAAAAAAAAAAATHAAAAAAAAAAAAAAAAAAATKAAAAAAAAAAAAAAAAAAATJAAAAAAAAAAAAA"
        "AAAAAATNAAAAAAAAAAAAAAAAAAAXqAAAAAAAAAAAAAAAAAAAYyAAAAAAAAAAAAAAAAAAAV+AAAAAAAAAAAAAAAAAAAVsAAAAAAAA"
        "AAAAAAAAAAAXhAAAAAAAAAAAAAAAAAAAV4AAAAAAAAAAAAAAAAAAAV7AAAAAAAAAAAAAAAAAAAX9AAAAAAAAAAAAAAAAAAAV6AAA"
        "AAAAAAAAAAAAAAAAVoAAAAAAAAAAAAAAAAAAAJ6AAAAAAAAAAAAAAAAAAATsAAAAAAAAAAAAAAAAAAAX5AAAAAAAAAAAAAAAAAAA"
        "XTAAAAAAAAAAAAAAAAAAAWAAAAAAAAAAAAAAAAAAAAVvAAAAAAAAAAAAAAAAAAAJ/AAAAAAAAAAAAAAAAAAAVmAAAAAAAAAAAAAA"
        "AAAAAXYAAAAAAAAAAAAAAAAAAAWCAAAAAAAAAAAAAAAAAAAXzAAAAAAAAAAAAAAAAAAATuAAAAAAAAAAAAAAAAAAAX8AAAAAAAAA"
        "AAAAAAAAAATAAAAAAAAAAAAAAAAAAAAX6AAAAAAAAAAAAAAAAAAAU0AAAAAAAAAAAAAAAAAAAXAAAAAAAAAAAAAAAAAAAAXBAAAA"
        "AAAAAAAAAAAAAAAVaAAAAAAAAAAAAAAAAAAAWSAAAAAAAAAAAAAAAAAAAXXAAAAAAAAAAAAAAAAAAAVfAAAAAAAAAAAAAAAAAAAV"
        "iAAAAAAAAAAAAAAAAAAAVlAAAAAAAAAAAAAAAAAAATBAAAAAAAAAAAAAAAAAAAXgAAAAAAAAAAAAAAAAAAAW8AAAAAAAAAAAAAAA"
        "AAAAWxAAAAAAAAAAAAAAAAAAAXbAAAAAAAAAAAAAAAAAAAXWAAAAAAAAAAAAAAAAAAAWmAAAAAAAAAAAAAAAAAAAWnAAAAAAAAAA"
        "AAAAAAAAALkAAAAAAAAAAAAAAAAAAAWUAAAAAAAAAAAAAAAAAAAXeAAAAAAAAAAAAAAAAAAAVhAAAAAAAAAAAAAAAAAAAW7AAAAA"
        "AAAAAAAAAAAAAAW0AAAAAAAAAAAAAAAAAAAUzAAAAAAAAAAAAAAAAAAAXVAAAAAAAAAAAAAAAAAAAXSAAAAAAAAAAAAAAAAAAAXR"
        "AAAAAAAAAAAAAAAAAAAV5AAAAAAAAAAAAAAAAAAAVwAAAAAAAAAAAAAAAAAAAVgAAAAAAAAAAAAAAAAAAAV1AAAAAAAAAAAAAAAA"
        "AAAMkAAAAAAAAAAAAAAAAAAAV8AAAAAAAAAAAAAAAAAAAV9AAAAAAAAAAAAAAAAAAAWRAAAAAAAAAAAAAAAAAAAXjAAAAAAAAAAA"
        "AAAAAAAAYuAAAAAAAAAAAAAAAAAAAXcAAAAAAAAAAAAAAAAAAAYnAAAAAAAAAAAAAAAAAAAV2AAAAAAAAAAAAAAAAAAAUuAAAAAA"
        "AAAAAAAAAAAAAMwAAAAAAAAAAAAAAAAAAAXfAAAAAAAAAAAAAAAAAAAYDAAAAAAAAAAAAAAAAAAAYoAAAAAAAAAAAAAAAAAAAVNA"
        "AAAAAAAAAAAAAAAAAAVpAAAAAAAAAAAAAAAAAAAUHAAAAAAAAAAAAAAAAAAAVtAAAAAAAAAAAAAAAAAAAXUAAAAAAAAAAAAAAAAA"
        "AAWTAAAAAAAAAAAAAAAAAAAUtAAAAAAAAAAAAAAAAAAAXdAAAAAAAAAAAAAAAAAAAV/AAAAAAAAAAAAAAAAAAAXaAAAAAAAAAAAA"
        "AAAAAAAXZAAAAAAAAAAAAAAAAAAAXQAAAAAAAAAAAAAAAAAAATFAAAAAAAAAAAAAAAAAAAXCAAAAAAAAAAAAAAAAAAAJ+AAAAAAA"
        "AAAAAAAAAAAALNAAAAAAAAAAAAAAAAAAAUxAAAAAAAAAAAAAAAAAAAKyAAAAAAAAAAAAAAAAAAAXDAAAAAAAAAAAAAAAAAAAVqAA"
        "AAAAAAAAAAAAAAAAAVYAAAAAAAAAAAAAAAAAAAXoAAAAAAAAAAAAAAAAAAAVFAAAAAAAAAAAAAAAAAAATiAAAAAAAAAAAAAAAAAA"
        "AToAAAAAAAAAAAAAAAAAAATjAAAAAAAAAAAAAAAAAAAThAAAAAAAAAAAAAAAAAAATgAAAAAAAAAAAAAAAAAAATlAAAAAAAAAAAAA"
        "AAAAAATmAAAAAAAAAAAAAAAAAAATqAAAAAAAAAAAAAAAAAAATkAAAAAAAAAAAAAAAAAAATfAAAAAAAAAAAAAAAAAAATnAAAAAAAA"
        "AAAAAAAAAAAAAAAAAS9AAAAAAAS+AAAAS/AAAAAAAAAAAAAAAAAAAWvAAAAAAAAAAAAAAAAAAAJkAAAAAAAAAAAAAAAAAAAXMAAA"
        "AAAAAAAAAAAAAAAAVXAAAAAAAAAAAAAAAAAAAXHAAAAAAAAAAAAAAAAAAAU3AAAAAAAAAAAAAAAAAAAXrAAAAAAAAAAAAAAAAAAA"
        "TvAAAAAAAAAAAAAAAAAAAXGAAAAAAAAAAAAAAAAAAAVeAAAAAAAAAAAAAAAAAAAU2AAAAAAAAAAAAAAAAAAAWJAAAAAAAAAAAAAA"
        "AAAAAU4AAAAAAAAAAAAAAAAAAAVjAAAAAAAVkAAAAAAAAAAK7AAAAAAAAAAAAAAAAAAAK5AAAAAAAAAAAAAAAAAAAVEAAAAAAAAA"
        "AAAAAAAAAALRAAAAAAAAAAAAAAAAAAAYAAAAAAAAAAAAAAAAAAAALYAAAAAAAAAAAAAAAAAAAXIAAAAAAAAAAAAAAAAAAAYFAAAA"
        "AAAAAAAAAAAAAAAXOAAAAAAAAAAAAAAAAAAAXEAAAAAAAAAAAAAAAAAAAXpAAAAAAAAAAAAAAAAAAAVLAAAAAAAVMAAAAAAAAAAL"
        "vAAAAAAAAAAAAAAAAAAAVCAAAAAAAAAAAAAAAAAAAMCAAAAAAAAAAAAAAAAAAATrAAAAAAAAAAAAAAAAAAAUJAAAAAAAAAAAAAAA"
        "AAAALzAAAAAAAAAAAAAAAAAAAXJAAAAAAAAAAAAAAAAAAAWwAAAAAAAAAAAAAAAAAAAVJAAAAAAAAAAAAAAAAAAAWKAAAAAAAAAA"
        "AAAAAAAAAU1AAAAAAAAAAAAAAAAAAAWGAAAAAAAAAAAAAAAAAAAVrAAAAAAAAAAAAAAAAAAAXPAAAAAAAAAAAAAAAAAAAM2AAAAA"
        "AAAAAAAAAAAAAATtAAAAAAAAAAAAAAAAAAAXLAAAAAAAAAAAAAAAAAAAYGAAAAAAAAAAAAAAAAAAAWPAAAAAAAAAAAAAAAAAAATx"
        "AAAAAAAAAAAAAAAAAAAXnAAAAAAAAAAAAAAAAAAAU9AAAAAAAAAAAAAAAAAAATEAAAAAAAAAAAAAAAAAAAXNAAAAAAAAAAAAAAAA"
        "AAAWBAAAAAAAAAAAAAAAAAAAYpAAAAAAAAAAAAAAAAAAATeAAAAAAAAAAAAAAAAAAAWFAAAAAAAAAAAAAAAAAAAXKAAAAAAAAAAA"
        "AAAAAAAAW9AAAAAAAAAAAAAAAAAAAVcAAAAAAAAAAAAAAAAAAAUmAAAAAAAAAAAAAAAAAAAWMAAAAAAAAAAAAAAAAAAAVnAAAAAA"
        "AAAAAAAAAAAAAUyAAAAAAAAAAAAAAAAAAAUhAAAAAAAAAAAAAAAAAAALgAAAAAAAAAAAAAAAAAAAX3AAAAAAAAAAAAAAAAAAAXlA"
        "AAAAAAAAAAAAAAAAAAMEAAAAAAAAAAAAAAAAAAAMDAAAAAAAAAAAAAAAAAAAYzAAAAAAAAAAAAAAAAAAAMmAAAAAAAAAAAAAAAAA"
        "AAYxAAAAAAAAAAAAAAAAAAAWzAAAAAAAAAAAAAAAAAAAW6AAAAAAAAAAAAAAAAAAAWyAAAAAAAAAAAAAAAAAAAUpAAAAAAAAAAAA"
        "AAAAAAAYvAAAAAAAAAAAAAAAAAAAVxAAAAAAAAAAAAAAAAAAAX7AAAAAAAAAAAAAAAAAAAKvAAAAAAAAAAAAAAAAAAAYCAAAAAAA"
        "AAAAAAAAAAAAU7AAAAAAAAAAAAAAAAAAAW4AAAAAAAAAAAAAAAAAAAXkAAAAAAAAAAAAAAAAAAALEAAAAAAAAAAAAAAAAAAAS8AA"
        "AAAAAAAAAAAAAAAAAVyAAAAAAAAAAAAAAAAAAAVIAAAAAAAAAAAAAAAAAAAWNAAAAAAAAAAAAAAAAAAAWOAAAAAAAAAAAAAAAAAA"
        "AW3AAAAAAAAAAAAAAAAAAAYIAAAAAAAAAAAAAAAAAAAMSAAAAAAAAAAAAAAAAAAAMTAAAAAAAAAAAAAAAAAAAWsAAAAAAAAAAAAA"
        "AAAAAAWqAAAAAAAAAAAAAAAAAAATdAAAAAAAAAAAAAAAAAAAMiAAAAAAAAAAAAAAAAAAAW/AAAAAAAAAAAAAAAAAAAVHAAAAAAAA"
        "AAAAAAAAAAAW5AAAAAAAAAAAAAAAAAAAUoAAAAAAAAAAAAAAAAAAAWVAAAAAAAAAAAAAAAAAAAW2AAAAAAAAAAAAAAAAAAAVzAAA"
        "AAAAAAAAAAAAAAAAX/AAAAAAAAAAAAAAAAAAAVGAAAAAAAAAAAAAAAAAAAYJAAAAAAAAAAAAAAAAAAAYwAAAAAAAAAAAAAAAAAA";
    inline constexpr const char* ZoneNamesChunks[] = {ZoneNamesChunk0};
    inline constexpr Packed ZoneNames{ZoneNamesChunks, 13, 3};

    inline constexpr char MetaKeysChunk0[] =
        "AAAAABAACAADAAFAAGAAIAAKAALAAMAANAAOAAPAAQAARAASAATAAUAAVAAWAAXAAZAAaAAbAAcAAdAAeAAfAAhAAjAAkAAmAAoA"
        "ApAAqAArAAsAAtAAuAAvAAwAAxAAyAAzAA1AA3AA6AA7AA8AA9AA+AA/ABAABBABCABDABEABGABHABIABJABKABOABPABRABSAB"
        "TABUABVABWABXABYABZABaABbABcABeABfABgABhABjABkABlABnABoABpABsABvABwABxAByAB0AB1AB2AB3AB4AB5AB6AB7AB8"
        "AB9AB+AB/ACAACBACCACDACEACFACHACIACKACLACMACNACOACPACQACRACSACTACUACVACWACXACYACZACbACcACeACfACgAChA"
        "CjACkAClACmACpACqACrACtACuACwACyACzAC0AC1AC2AC3AC4AC5AC6AC7AC9";
    inline constexpr const char* MetaKeysChunks[] = {MetaKeysChunk0};
    inline constexpr Packed MetaKeys{MetaKeysChunks, 13, 3};

    inline constexpr char MetaNamesChunk0[] =
        "AY3AY4AY5AAAAAAAAAAAAAY6AAAAAAAAAAAAAAAAY7AAAAAAAAAAAAAAAAY8AAAAAAAAAAAAAAAAY9AAAAAAAAAAAAAY+AY/AZAA"
        "AAAAAAAAAZBAZCAZDAAAAAAAAAAZEAZFAZGAAAAAAAAAAZHAZIAZJAAAAAAAAAAZKAZLAZMAAAAAAAAAAZNAZOAZPAAAAAAAAAAZ"
        "QAZRAZSAAAAAAAAAAZTAZUAZVAAAAAAAAAAZWAZXAZYAAAAAAAAAAZZAZaAZbAAAAAAAAAAZcAZdAZeAAAAAAAAAAZfAZgAZhAAA"
        "AAAAAAAZiAZjAZkAAAAAAAAAAZlAZmAZnAAAAAAAAAAZoAZpAZqAAAAAAAAAAZrAZsAZtAAAAAAAAAAZuAZvAZwAAAAAAAAAAZxA"
        "ZyAZzAAAAAAAAAAZ0AZ1AZ2AAAAAAAAAAZ3AZ4AZ5AAAAAAAAAAZ6AZ7AZ8AAAAAAAAAAZ9AZ+AZ/AAAAAAAAAAaAAaBAaCAAAAA"
        "AAAAAaDAaEAaFAAAAAAAAAAAAAaGAAAAAAAAAAAAAAAAaHAAAAAAAAAAAAAaIAaJAaKAAAAAAAAAAAAAaLAAAAAAAAAAAAAaMAaN"
        "AaOAAAAAAAAAAAAAaPAAAAAAAAAAAAAAAAaQAAAAAAAAAAAAAaRAaSAaTAAAAAAAAAAaUAaVAaWAAAAAAAAAAaXAaYAaZAAAAAAA"
        "AAAAAAaaAAAAAAAAAAAAAAAAabAAAAAAAAAAAAAacAadAaeAAAAAAAAAAafAagAahAAAAAAAAAAaiAajAakAAAAAAAAAAAAAalAA"
        "AAAAAAAAAAAAAAamAAAAAAAAAAAAAAAAanAAAAAAAAAAAAAaoAapAaqAAAAAAAAAAAAAarAAAAAAAAAAAAAasAatAauAAAAAAAAA"
        "AavAawAaxAAAAAAAAAAAAAayAAAAAAAAAAAAAazAa0Aa1AAAAAAAAAAa2Aa3Aa4AAAAAAAAAAa5Aa6Aa7AAAAAAAAAAAAAa8AAAA"
        "AAAAAAAAAAAAa9AAAAAAAAAAAAAAAAbEAAAAAAAAAAAAAAAAa+AAAAAAAAAAAAAAAAa/AAAAAAAAAAAAAbAAbBAbCAAAAAAAAAAA"
        "AAbDAAAAAAAAAAAAAbFAbGAbHAAAAAAAAAAbIAbJAbKAAAAAAAAAAAAAbLAAAAAAAAAAAAAAAAbMAAAAAAAAAAAAAbNAbOAbPAAA"
        "AAAAAAAbQAbRAbSAAAAAAAAAAbTAbUAbVAAAAAAAAAAAAAbWAAAAAAAAAAAAAAAAbXAAAAAAAAAAAAAAAAbYAAAAAAAAAAAAAAAA"
        "bZAAAAAAAAAAAAAAAAbaAAAAAAAAAAAAAAAAbbAAAAAAAAAAAAAbcAbdAbeAAAAAAAAAAbfAbgAbhAAAAAAAAAAbiAbjAbkAAAAA"
        "AAAAAblAbmAbnAAAAAAAAAAboAbpAbqAAAAAAAAAAAAAbrAAAAAAAAAAAAAAAAbsAAAAAAAAAAAAAAAAbtAAAAAAAAAAAAAbuAbv"
        "AbwAAAAAAAAAAAAAbxAAAAAAAAAAAAAbyAbzAb0AAAAAAAAAAAAAb1AAAAAAAAAAAAAAAAb2AAAAAAAAAAAAAb3Ab4Ab5AAAAAAA"
        "AAAb6Ab7Ab8AAAAAAAAAAb9Ab+Ab/AAAAAAAAAAAAAcAAAAAAAAAAAAAAAAAcBAAAAAAAAAAAAAAAAcCAAAAAAAAAAAAAAAAcDAA"
        "AAAAAAAAAAAcEAcFAcGAAAAAAAAAAAAAcHAAAAAAAAAAAAAcIAcJAcKAAAAAAAAAAcLAcMAcNAAAAAAAAAAcOAcPAcQAAAAAAAAA"
        "AAAAcRAAAAAAAAAAAAAAAAcSAAAAAAAAAAAAAAAAcTAAAAAAAAAAAAAcUAcVAcWAAAAAAAAAAcXAcYAcZAAAAAAAAAAcaAcbAccA"
        "AAAAAAAAAAAAcdAAAAAAAAAAAAAceAcfAcgAAAAAAAAAAchAciAcjAAAAAAAAAAckAclAcmAAAAAAAAAAcnAcoAcpAAAAAAAAAAc"
        "qAcrAcsAAAAAAAAAAAAActAAAAAAAAAAAAAAAAcuAAAAAAAAAAAAAcvAcwAcxAAAAAAAAAAcyAczAc0AAAAAAAAAAc1Ac2Ac3AAA"
        "AAAAAAAAAAc4AAAAAAAAAAAAAc5Ac6Ac7AAAAAAAAAAAAAc8AAAAAAAAAAAAAAAAc9AAAAAAAAAAAAAAAAc+AAAAAAAAAAAAAc/A"
        "dAAdBAAAAAAAAAAAAAdCAAAAAAAAAAAAAAAAdDAAAAAAAAAAAAAdEAdFAdGAAAAAAAAAAdHAdIAdJAAAAAAAAAAdKAdLAdMAAAAA"
        "AAAAAAAAdNAAAAAAAAAAAAAAAAdOAAAAAAAAAAAAAAAAdPAAAAAAAAAAAAAAAAdQAAAAAAAAAAAAAAAAdRAAAAAAAAAAAAAAAAdS"
        "AAAAAAAAAAAAAAAAdTAAAAAAAAAAAAAdUAdVAdWAAAAAAAAAAAAAdXAAAAAAAAAAAAAAAAdYAAAAAAAAAAAAAdZAdaAdbAAAAAAA"
        "AAAAAAdcAAAAAAAAAAAAAddAdeAdfAAAAAAAAAAAAAdgAAAAAAAAAAAAAdhAdiAdjAAAAAAAAAAdkAdlAdmAAAAAAAAAAdnAdoAd"
        "pAAAAAAAAAAAAAdqAAAAAAAAAAAAAdrAdsAdtAAAAAAAAAAduAdvAdwAAAAAAAAAAAAAdxAAAAAAAAAAAAAAAAdyAAAAAAAAAAAA"
        "AAAAdzAAAAAAAAAAAAAd0Ad1Ad2AAAAAAAAAAd3Ad4Ad5AAAAAAAAAAAAAd6AAAAAAAAAAAA";
    inline constexpr const char* MetaNamesChunks[] = {MetaNamesChunk0};
    inline constexpr Packed MetaNames{MetaNamesChunks, 13, 3};

    inline constexpr uint16_t Formats[] = {
        1915, 1916, 1917, 1918, 1919, 1920, 0, 0, 0, 0, 0, 1921,
    };

    inline constexpr Table table{
        0x6b6f00000000, 0,
        NameTexts,
        LanguageKeys, LanguageNames, 570,
        nullptr, Packed{}, 0,
        RegionKeys, RegionNames, 294,
        ScriptKeys, ScriptNames, 169,
        AloneKeys, AloneNames, 2,
        CurrencyKeys, CurrencyNames, 167,
        ZoneKeys, ZoneNames, 419,
        MetaKeys, MetaNames, 154,
        Formats,
    };

    // the table registered when the header is included, once a program
    inline Registration registration{&table};
}
