//------------------------------------------------------------------------------
// SGCL: a C++20 application platform
// Copyright (c) 2022-2026 Sebastian Nibisz
// SPDX-License-Identifier: Apache-2.0
//------------------------------------------------------------------------------
#pragma once
#include "detail/registry.h"
#include "ps.h"

#include <cstdint>

// The display names of the locale ps-PK (پښتو), CLDR 46.0: the names of languages,
// regions, scripts, currencies and time zones in it, what differs from ps (included).
// Including this header is all a program does: txt::locale::display_name,
// region::display_name, script::display_name and currency::display_name then
// answer in this language. Generated by tools/cldr_tables.py: do not edit.
namespace sgcl::txt::detail::names::l_ps_PK {
    inline constexpr char8_t NameChunk0[] =
        u8"نوے معياري عربيلوړے سربيفاروئےخاسےناروے بوکمالامريکےفلسطين سيمےد ترکیے او کیکاسو ټاپود فرانسے جنوبي "
        u8"سیمےپاکستانۍ کلدارهپاکستانۍ کلدارےنامعلومه مروجه پېسے(د نامعلومه مروجه پېسو واحد)(نامعلومه مروجه پېس"
        u8"ے)د کمتر شهزاده درے میاشتنۍهرارےالاسکا وختالاسکا معياري وختد الاسکا د ورځے روښانه کولمرکزي وختمرکزي "
        u8"معياري وختمرکزي رڼا ورځے وختختیځ وختختيځ معياري وختختيځ د رڼا ورځے وختد غره د وختد غره معياري وختد غ"
        u8"ره د رڼا ورځے وختپیسفک وختد پیسفک معياري وختپیسفک د رڼا ورځے وختاپیا وختاپیا معياري وختد اپیا د ورځے"
        u8" وختعربي وختعربي معیاري وختد عربي ورځپاڼے وختاتلانتیک وختاتلانتیک معياري وختاتلانتیک د رڼا ورځے وختل"
        u8"وېديځ آستراليا وختآسترالوي لوېديځ معياري وختد اسټرالیا لویدیځ د ورځے وختچين وختچین معیاري وختد چين د"
        u8" رڼا ورځے وختکيوبا وختکیوبا معياري وختکیوبا د رڼا ورځے وختلوېديزے اروپا وختد لودیځے اروپا معیاري وخت"
        u8"د لودیځے اورپا د اوړي وختد فرانسے سویل او انټارټيک وختهوایی الیوتین وختهوایی الیوتین معیاری وختهوایی"
        u8" الیوتین رڼا ورځے وختایران وختایران معياري وختد ایران د ورځے وختاسراییل وختاسراییل معياري وختد اسرای"
        u8"یلو د ورځے وختجاپان وختجاپان معياري وختجاپان د رڼا ورځے وختکوريايي وختکوريايي معياري وختد کوریا د ور"
        u8"ځے د ورځے وختد کرښے ټاټوبي وختلارډ هوي وختلارډ هوي معياري وخترب هاو د ورځے د رڼا وختمکسیکن پیسفک وخت"
        u8"مکسیکن پیسفک معیاری وختمکسیکن پیسفک رڼا ورځے وختنيوزي لېنډ وختنيوزي لېنډ معياري وختد نیوزی لینڈ د ور"
        u8"ځے د رڼا وختنيو فاونډلېنډ وختد نوي فیلډلینډ معیاری وختد نوي فیلډلینډ رڼا ورځے وختسینټ پییرا و ميکلين"
        u8" وختسینټ پییرا و ميکلين معیاری وختسینټ پییرا و ميکلين رڼا ورځے وختسموا وختسموا معياري وختد سموا د ور"
        u8"ځے روښانه کول{0} ({1}){0}, {1}د {0} په وخت{0} معیاری وخت{0} رڼا ورځ وخت{1} ({0}){0} {1}";
    inline constexpr const char8_t* NameChunks[] = {NameChunk0};
    inline constexpr uint16_t NameChunkSizes[] = {2885};
    inline constexpr char NameRefsChunk0[] =
        "AAAAAAAAAAAcAAAtAAA5AABBAABYAABkAAB5AAChAADEAADhAAD+AAEiAAFUAAF6AAGoAAGyAAHFAAHlAAIUAAIlAAJDAAJkAAJz"
        "AAKPAAKxAALEAALhAAMEAAMVAAM2AANaAANpAAOFAAOjAAOyAAPOAAPvAAQGAAQqAARUAAR4AASpAATcAATpAAUDAAUmAAU3AAVV"
        "AAV5AAWZAAXHAAX0AAYpAAZJAAZ2AAamAAa3AAbVAAb1AAcKAAcsAAdSAAdjAAeBAAelAAe6AAfcAAgIAAgnAAg9AAhgAAiIAAim"
        "AAjRAAj/AAkZAAlAAAlzAAmTAAnBAAnyAAocAApTAAqNAAqcAAq4AArjAArsAAr0AAsGAAsdAAs1AAs+AAtF";
    inline constexpr const char* NameRefsChunks[] = {NameRefsChunk0};
    inline constexpr Packed NameRefs{NameRefsChunks, 13, 4};
    inline constexpr Text NameTexts{NameChunks, NameChunkSizes, NameRefs};

    inline constexpr char LanguageKeysChunk0[] =
        "ADPAHCBJiC0B";
    inline constexpr const char* LanguageKeysChunks[] = {LanguageKeysChunk0};
    inline constexpr Packed LanguageKeys{LanguageKeysChunks, 13, 3};

    inline constexpr char LanguageNamesChunk0[] =
        "AADAAFAACAAE";
    inline constexpr const char* LanguageNamesChunks[] = {LanguageNamesChunk0};
    inline constexpr Packed LanguageNames{LanguageNamesChunks, 13, 3};

    inline constexpr const uint64_t* TaggedKeys = nullptr;

    inline constexpr const uint16_t* TaggedNames = nullptr;

    inline constexpr char RegionKeysChunk0[] =
        "AHDAIfAIiALs";
    inline constexpr const char* RegionKeysChunks[] = {RegionKeysChunk0};
    inline constexpr Packed RegionKeys{RegionKeysChunks, 13, 3};

    inline constexpr char RegionNamesChunk0[] =
        "AAHAAIAAJAAG";
    inline constexpr const char* RegionNamesChunks[] = {RegionNamesChunk0};
    inline constexpr Packed RegionNames{RegionNamesChunks, 13, 3};

    inline constexpr const uint32_t* ScriptKeys = nullptr;

    inline constexpr const uint16_t* ScriptNames = nullptr;

    inline constexpr const uint32_t* AloneKeys = nullptr;

    inline constexpr const uint16_t* AloneNames = nullptr;

    inline constexpr char CurrencyKeysChunk0[] =
        "EFyGMY";
    inline constexpr const char* CurrencyKeysChunks[] = {CurrencyKeysChunk0};
    inline constexpr Packed CurrencyKeys{CurrencyKeysChunks, 13, 3};

    inline constexpr char CurrencyNamesChunk0[] =
        "AAKAAAAAKAAAAAAAAAAALAAMAAAAANAAAAAAAAAAAO";
    inline constexpr const char* CurrencyNamesChunks[] = {CurrencyNamesChunk0};
    inline constexpr Packed CurrencyNames{CurrencyNamesChunks, 13, 3};

    inline constexpr char ZoneKeysChunk0[] =
        "AAXACG";
    inline constexpr const char* ZoneKeysChunks[] = {ZoneKeysChunk0};
    inline constexpr Packed ZoneKeys{ZoneKeysChunks, 13, 3};

    inline constexpr char ZoneNamesChunk0[] =
        "AAQAAAAAAAAAAAAAAAAAAAAPAAAAAAAAAAAAAAAAAA";
    inline constexpr const char* ZoneNamesChunks[] = {ZoneNamesChunk0};
    inline constexpr Packed ZoneNames{ZoneNamesChunks, 13, 3};

    inline constexpr char MetaKeysChunk0[] =
        "AAIAAMAANAAOAAPAARAAUAAZAAdAAuAAzABAABEABTABcABfABgABnABvABwAB6ACBACCACRACb";
    inline constexpr const char* MetaKeysChunks[] = {MetaKeysChunk0};
    inline constexpr Packed MetaKeys{MetaKeysChunks, 13, 3};

    inline constexpr char MetaNamesChunk0[] =
        "AARAASAATAAAAAAAAAAAUAAVAAWAAAAAAAAAAAXAAYAAZAAAAAAAAAAAaAAbAAcAAAAAAAAAAAdAAeAAfAAAAAAAAAAAgAAhAAiA"
        "AAAAAAAAAAjAAkAAlAAAAAAAAAAAmAAnAAoAAAAAAAAAAApAAqAArAAAAAAAAAAAsAAtAAuAAAAAAAAAAAvAAwAAxAAAAAAAAAAA"
        "yAAzAA0AAAAAAAAAAAAAA1AAAAAAAAAAAAAA2AA3AA4AAAAAAAAAAA5AA6AA7AAAAAAAAAAA8AA9AA+AAAAAAAAAAA/ABAABBAAA"
        "AAAAAAABCABDABEAAAAAAAAAAAAABFAAAAAAAAAAAAABGABHABIAAAAAAAAAABJABKABLAAAAAAAAAABMABNABOAAAAAAAAAABPA"
        "BQABRAAAAAAAAAABSABTABUAAAAAAAAAABVABWABXAAAAAAAAA";
    inline constexpr const char* MetaNamesChunks[] = {MetaNamesChunk0};
    inline constexpr Packed MetaNames{MetaNamesChunks, 13, 3};

    inline constexpr uint16_t Formats[] = {
        88, 89, 90, 91, 92, 93, 0, 0, 0, 0, 0, 94,
    };

    inline constexpr Table table{
        0x707300000376, 0x707300000000,
        NameTexts,
        LanguageKeys, LanguageNames, 4,
        nullptr, Packed{}, 0,
        RegionKeys, RegionNames, 4,
        Packed{}, Packed{}, 0,
        Packed{}, Packed{}, 0,
        CurrencyKeys, CurrencyNames, 2,
        ZoneKeys, ZoneNames, 2,
        MetaKeys, MetaNames, 25,
        Formats,
    };

    // the table registered when the header is included, once a program
    inline Registration registration{&table};
}
