//------------------------------------------------------------------------------
// SGCL: a C++20 application platform
// Copyright (c) 2022-2026 Sebastian Nibisz
// SPDX-License-Identifier: Apache-2.0
//------------------------------------------------------------------------------
#pragma once
#include "detail/registry.h"
#include "sr-Cyrl.h"

#include <cstdint>

// The display names of the locale sr-Cyrl-BA (српски), CLDR 46.0: the names of languages,
// regions, scripts, currencies and time zones in it, what differs from sr-Cyrl (included).
// Including this header is all a program does: txt::locale::display_name,
// region::display_name, script::display_name and currency::display_name then
// answer in this language. Generated by tools/cldr_tables.py: do not edit.
namespace sgcl::txt::detail::names::l_sr_Cyrl_BA {
    inline constexpr char8_t NameChunk0[] =
        u8"бјелорускибамананканбангласјевероисточни крињемачкишвајцарски високи њемачкисјевернофризијскињемачки"
        u8" (Швајцарска)хаићански креолскисјеверни лурисјеверни ндебеленискоњемачкисјеверни сотосјеверозападни "
        u8"оџибвасјеверни самисјеверни тучонсвијетСјеверноамерички континентСјеверна АфрикаСјеверна и Јужна Аме"
        u8"рикаСјеверна АмерикаСјеверна Европаострво АсенсионОландска острваСен БартелемиБрунејиострво БувеБјел"
        u8"орусијаКокосова (Килинг) острваострво КлипертонЧешка РепубликаЊемачкаФокландска острваФарска острваЈ"
        u8"ужна Џорџија и Јужна Сендвичка острваГвамГвинеја БисаоХонгконг (САО Кине)острво Херд и острва Макдон"
        u8"алдКомориСјеверна КорејаСјеверна МакедонијаМјанмар (Бурма)Сјеверна Маријанска острваострво НорфокНиј"
        u8"уепалестинске територијеРеунионФранцуске јужне територијеСпољна острва САДСвети Винсент и ГренадиниБ"
        u8"ританска Дјевичанска острваАмеричка Дјевичанска острваБосанскохерцеговачка конвертибилна маркабосанс"
        u8"кохерцеговачка конвертибилна маркабосанскохерцеговачке конвертибилне маркeбосанскохерцеговачких конв"
        u8"ертибилних маракаБјелоруска рубљабјелоруска рубљабјелоруске рубљебјелоруских рубљиСјевернокорејски в"
        u8"онсјевернокорејски вонсјевернокорејска вонасјевернокорејских вонаНикарагванска златна кордобаникараг"
        u8"ванска златна кордобаникарагванске златне кордобеникарагванских златних кордобаКоординисано универза"
        u8"лно вријемеUTCДимон д’ИрвилМаквориСвифт КарентРеџајнаРезолутСент ЏонсЛондонБританија, љетње вријемеИ"
        u8"токортормитПорт-о-ПренсДаблинИрска, стандардно вријемеПорторикоЛонгјирПорт ов СпејнБјула, Сјеверна Д"
        u8"акотаНови Салем, Сјеверна ДакотаЦентар, Сјеверна ДакотаВинсенс, ИндијанаИндијанаполисЛуивилВиви, Инд"
        u8"ијанаСент ТомасАвганистан вријемеЦентрално-афричко вријемеИсточно-афричко вријемеЈужно-афричко врије"
        u8"меЗападно-афричко вријемеЗападно-афричко стандардно вријемеЗападно-афричко љетње вријемеАљаскаАљаска"
        u8", стандардно вријемеАљаска, љетње вријемеАмазон вријемеАмазон, стандардно вријемеАмазон, љетње врије"
        u8"меСјеверноамеричко централно вријемеСјеверноамеричко централно стандардно вријемеСјеверноамеричко це"
        u8"нтрално љетње вријемеСјеверноамеричко источно вријемеСјеверноамеричко источно стандардно вријемеСјев"
        u8"ерноамеричко источно љетње вријемеСјеверноамеричко планинско вријемеСјеверноамеричко планинско станд"
        u8"ардно вријемеСјеверноамеричко планинско љетње вријемеСјеверноамеричко пацифичко вријемеСјеверноамери"
        u8"чко пацифичко стандардно вријемеСјеверноамеричко пацифичко летње вријемеАпија вријемеАпија, стандард"
        u8"но вријемеАпија, љетње вријемеАрабијско вријемеАрабијско стандардно вријемеАрабијско љетње вријемеАр"
        u8"гентина вријемеАргентина, стандардно вријемеАргентина, љетње вријемеЗападна Аргентина вријемеЗападна"
        u8" Аргентина, стандардно вријемеЗападна Аргентина, љетње вријемеЈерменија вријемеЈерменија, стандардно"
        u8" вријемеЈерменија, љетње вријемеАтлантско вријемеАтлантско стандардно вријемеАтлантско љетње вријеме"
        u8"Аустралијско централно вријемеАустралијско централно стандардно вријемеАустралијско централно љетње "
        u8"вријемеАустралијско централно западно вријемеАустралијско централно западно стандардно вријемеАустра"
        u8"лијско централно западно љетње вријемеАустралијско источно вријемеАустралијско источно стандардно вр"
        u8"ијемеАустралијско источно љетње вријемеАустралијско западно вријемеАустралијско западно стандардно в"
        u8"ријемеАустралијско западно љетње вријемеАзербејџан вријемеАзербејџан, стандардно вријемеАзербејџан, "
        u8"љетње вријемеАзори вријемеАзори, стандардно вријемеАзори, љетње вријемеБангладеш вријемеБангладеш, с"
        u8"тандардно вријемеБангладеш, љетње вријемеБутан вријемеБоливија вријемеБразилија вријемеБразилија, ст"
        u8"андардно вријемеБразилија, љетње вријемеБрунеј Дарусалум вријемеЗеленортска Острва вријемеЗеленортск"
        u8"а Острва, стандардно вријемеЗеленортска Острва, љетње вријемеЧаморо вријемеЧатам вријемеЧатам, станд"
        u8"ардно вријемеЧатам, љетње вријемеЧиле вријемеЧиле, стандардно вријемеЧиле, љетње вријемеКина вријеме"
        u8"Кинеско стандардно вријемеКина, љетње вријемеБожићно острво вријемеКокосова (Килинг) острва вријемеК"
        u8"олумбија вријемеКолумбија, стандардно вријемеКолумбија, љетње вријемеКукова Острва вријемеКукова Ост"
        u8"рва, стандардно вријемеКукова Острва, полуљетње вријемеКубаКуба, стандардно вријемеКуба, љетње врије"
        u8"меДејвис вријемеДимон д’Ирвил вријемеИсточни Тимор вријемеУскршња острва вријемеУскршња острва, стан"
        u8"дардно вријемеУскршња острва, љетње вријемеЕквадор вријемеСредњоевропско вријемеСредњоевропско станд"
        u8"ардно вријемеСредњоевропско љетње вријемеCETCESTИсточноевропско вријемеИсточноевропско стандардно вр"
        u8"ијемеИсточноевропско љетње вријемеEETEESTЗападноевропско вријемеЗападноевропско стандардно вријемеЗа"
        u8"падноевропско љетње вријемеWETWESTФолкландска Острва вријемеФолкландска Острва, стандардно вријемеФо"
        u8"лкландска Острва, љетње вријемеФиџи вријемеФиџи, стандардно вријемеФиџи, љетње вријемеФранцуска Гвај"
        u8"ана вријемеФранцуско јужно и антарктичко вријемеГалапагос вријемеГамбије вријемеГрузија вријемеГрузи"
        u8"ја, стандардно вријемеГрузија, љетње вријемеГилбертова острва вријемеСредње вријеме по ГриничуGMTИст"
        u8"очни ГренландИсточни Гренланд, стандардно вријемеИсточни Гренланд, љетње вријемеЗападни ГренландЗапа"
        u8"дни Гренланд, стандардно вријемеЗападни Гренланд, љетње вријемеЗаливско вријемеГвајана вријемеХавајс"
        u8"ко-алеутско вријемеХавајско-алеутско стандардно вријемеХавајско-алеутско љетње вријемеХонг Конг вриј"
        u8"емеХонг Конг, стандардно вријемеХонг Конг, љетње вријемеХовд вријемеХовд, стандардно вријемеХовд, ље"
        u8"тње вријемеИндијско стандардно вријемеИндијско океанско вријемеИндокина вријемеЦентрално-индонезијск"
        u8"о вријемеИсточно-индонезијско вријемеЗападно-индонезијско вријемеИран вријемеИран, стандардно вријем"
        u8"еИран, љетње вријемеИркуцк вријемеИркуцк, стандардно вријемеИркуцк, љетње вријемеИзраелско вријемеИз"
        u8"раелско стандардно вријемеИзраелско љетње вријемеЈапанско вријемеЈапанско стандардно вријемеЈапанско"
        u8" љетње вријемеКазахстанско вријемеИсточно-казахстанско вријемеЗападно-казахстанско вријемеКорејско в"
        u8"ријемеКорејско стандардно вријемеКорејско љетње вријемеКошре вријемеКраснојарск вријемеКраснојарск, "
        u8"стандардно вријемеКраснојарск, љетње вријемеКиргистан вријемеЛинијска острва вријемеЛорд Хов вријеме"
        u8"Лорд Хов, стандардно вријемеЛорд Хов, љетње вријемеМагадан вријемеМагадан, стандардно вријемеМагадан"
        u8", љетње вријемеМалезија вријемеМалдиви вријемеМаркиз вријемеМаршалска Острва вријемеМаурицијус врије"
        u8"меМаурицијус, стандардно вријемеМаурицијус, љетње вријемеМосон вријемеМексички ПацификМексички Пациф"
        u8"ик, стандардно вријемеМексички Пацифик, љетње вријемеУлан Батор вријемеУлан Батор, стандардно вријем"
        u8"еУлан Батор, љетње вријеемеМосква вријемеМосква, стандардно вријемеМосква, љетње вријемеМјанмар вриј"
        u8"емеНауру вријемеНепал вријемеНова Каледонија вријемеНова Каледонија, стандардно вријемеНова Каледони"
        u8"ја, љетње вријемеНови Зеланд вријемеНови Зеланд, стандардно вријемеНови Зеланд, љетње вријемеЊуфаунд"
        u8"лендЊуфаундленд, стандардно вријемеЊуфаундленд, љетње вријемеНијуе вријемеострво Норфолк вријемеостр"
        u8"во Норфолк, стандардно вријемеострво Норфолк, љетње вријемеФернандо де Нороња вријемеФернандо де Нор"
        u8"оња, стандардно вријемеФернандо де Нороња, љетње вријемеНовосибирск вријемеНовосибирск, стандардно в"
        u8"ријемеНовосибирск, љетње вријемеОмск вријемеОмск, стандардно вријемеОмск, љетње вријемеПакистан вриј"
        u8"емеПакистан, стандардно вријемеПакистан, љетње вријемеПалау вријемеПапуа Нова Гвинеја вријемеПарагва"
        u8"ј вријемеПарагвај, стандардно вријемеПарагвај, љетње вријемеПеру вријемеПеру, стандардно вријемеПеру"
        u8", љетње вријемеФилипини вријемеФилипини, стандардно вријемеФилипини, љетње вријемеФеникс острва вриј"
        u8"емеСен Пјер и МикелонСен Пјер и Микелон, стандардно вријемеСен Пјер и Микелон, љетње вријемеПиткерн "
        u8"вријемеПонпеј вријемеПјонгјаншко вријемеРеунион вријемеРотера вријемеСахалин вријемеСахалин, стандар"
        u8"дно вријемеСахалин, љетње вријемеСамоа вријемеСамоа, стандардно вријемеСамоа, љетње вријемеСејшели в"
        u8"ријемеСингапур, стандардно вријемеСоломонска Острва вријемеЈужна Џорџија вријемеСуринам вријемеШова "
        u8"вријемеТахити вријемеТајпеј вријемеТајпеј, стандардно вријемеТајпеј, љетње вријемеТаџикистан вријеме"
        u8"Токелау вријемеТонга вријемеТонга, стандардно вријемеТонга, љетње вријемеЧук вријемеТуркменистан ври"
        u8"јемеТуркменистан, стандардно вријемеТуркменистан, љетње вријемеТувалу вријемеУругвај вријемеУругвај,"
        u8" стандардно вријемеУругвај, љетње вријемеУзбекистан вријемеУзбекистан, стандардно вријемеУзбекистан,"
        u8" љетње вријемеВануату вријемеВануату, стандардно вријемеВануату, љетње вријемеВенецуела вријемеВлади"
        u8"восток вријемеВладивосток, стандардно вријемеВладивосток, љетње вријемеВолгоград вријемеВолгоград, с"
        u8"тандардно вријемеВолгоград, љетње вријемеВосток вријемеострво Вејк вријемеострва Валис и Футуна вриј"
        u8"емеЈакутск вријемеЈакутск, стандардно вријемеЈакутск, љетње вријемеЈекатеринбург вријемеЈекатеринбур"
        u8"г, стандардно вријемеЈекатеринбург, љетње вријеме{0} ({1}){0}, {1}{0}{0}, стандардно вријеме{0}, љет"
        u8"ње вријеме{1} ({0}){0} {1}";
    inline constexpr const char8_t* NameChunks[] = {NameChunk0};
    inline constexpr uint16_t NameChunkSizes[] = {16576};
    inline constexpr char NameRefsChunk0[] =
        "AAAAAAAAAAAUAAAoAAA0AABXAABlAACVAAC3AADcAAD/AAEYAAE3AAFPAAFoAAGRAAGqAAHFAAHRAAIEAAIhAAJOAAJtAAKKAAKn"
        "AALEAALdAALrAAMAAAMWAANCAANhAAN+AAOMAAOtAAPGAAQNAAQVAAQuAARQAASIAASUAASxAATWAATxAAUjAAU8AAVGAAVxAAV/"
        "AAWxAAXRAAYAAAY2AAZqAAa4AAcGAAdTAAenAAfGAAflAAgEAAglAAhMAAhzAAicAAjHAAj9AAkzAAlpAAmjAAnhAAnkAAn+AAoM"
        "AAojAAoxAAo/AApQAApcAAqJAAqhAAq3AArDAAryAAsEAAsSAAsqAAtTAAuFAAuwAAvQAAvqAAv2AAwQAAwjAAxGAAx2AAyiAAzK"
        "AAz2AA03AA1uAA16AA2rAA3SAA3tAA4eAA5FAA6HAA7eAA8rAA9pAA+8ABAFABBHABCeABDrABEtABGEABHRABHqABIZABI+ABJf"
        "ABKVABLBABLiABMZABNGABN2ABO8ABP4ABQZABRQABR9ABSeABTUABUAABU6ABWJABXOABYXABZ1ABbJABb/ABdKABeLABfBABgM"
        "ABhNABhwABipABjYABjxABkgABlFABlmABmdABnKABnjABoCABojABpaABqHABq1ABrnABsvABttABuIABuhABvQABv1ABwMABw5"
        "ABxcABxzABylABzIABzyAB0tAB1OAB2FAB2yAB3aAB4YAB5UAB5cAB6JAB6sAB7HAB7wAB8YAB9CAB+CAB+4AB/VACAAACBAACB2"
        "ACB5ACB9ACCqACDsACEkACEnACErACFYACGaACHSACHVACHZACILACJTACKRACKoACLVACL4ACMoACNuACOPACOsACPJACP8ACQl"
        "ACRVACSEACSHACSmACTqACUkACVDACWHACXBACXgACX9ACYtACZyACatACbNACcDACcvACdGACdzACeWACfKACf6ACgZAChTACiJ"
        "ACi/ACjWACkDACkmAClBAClyACmZACm6ACnwACocACo7ACpvACqZACrAACr2ACssACtLACt/ACupACvCACvnACwiACxTACx0ACyg"
        "ACy+ACzyAC0cAC05AC1sAC2VAC20AC3RAC3sAC4aAC49AC52AC6lAC6+AC7dAC8hAC9bAC99AC+1AC/lADAAADAxADBYADB1ADCO"
        "ADCnADDTADEVADFNADFxADGrADHbADHxADIsADJdADJ2ADKgADLgADMWADNHADOOADPLADPwADQrADRcADRzADSgADTDADTiADUX"
        "ADVCADVbADWMADWrADXgADYLADYiADZPADZyADaRADbGADbxADcZADc6ADeAADe8ADfZADf0ADgZADg2ADhRADhuADihADjKADjj"
        "ADkSADk3ADlUADmJADm5ADnhADn+ADoVADowADpLADp8ADqjADrGADrjADr8ADsrADtQADtlADuMADvJADv8ADwXADw0ADxnADyQ"
        "ADyzADzsAD0bAD04AD1rAD2UAD21AD3aAD4VAD5GAD5nAD6eAD7LAD7mAD8KAD9AAD9dAD+QAD+5AD/iAEAhAEBWAEBfAEBnAEBq"
        "AECSAECwAEC5AEDA";
    inline constexpr const char* NameRefsChunks[] = {NameRefsChunk0};
    inline constexpr Packed NameRefs{NameRefsChunks, 13, 4};
    inline constexpr Text NameTexts{NameChunks, NameChunkSizes, NameRefs};

    inline constexpr char LanguageKeysChunk0[] =
        "ABFABNABOACFAEUAHEAJlA5MBpSB53DJDDiTDpvD1CFKN";
    inline constexpr const char* LanguageKeysChunks[] = {LanguageKeysChunk0};
    inline constexpr Packed LanguageKeys{LanguageKeysChunks, 13, 3};

    inline constexpr char LanguageNamesChunk0[] =
        "AABAACAADAAFAAJAALAAPAAEAAHAAIAAKAAMAANAAOAAQ";
    inline constexpr const char* LanguageNamesChunks[] = {LanguageNamesChunk0};
    inline constexpr Packed LanguageNames{LanguageNamesChunks, 13, 3};

    inline constexpr const uint64_t* TaggedKeys = nullptr;

    inline constexpr const uint16_t* TaggedNames = nullptr;

    inline constexpr char RegionKeysChunk0[] =
        "AAeAAzABCABEABMABPABUABhABrABxACtACxADQADSADUADjADlAE2AE5AFqAFsAFvAGAAGPAHDAHrAIiAJEAJVAJZAJbALaALcA"
        "LoALsALuANz";
    inline constexpr const char* RegionKeysChunks[] = {RegionKeysChunk0};
    inline constexpr Packed RegionKeys{RegionKeysChunks, 13, 3};

    inline constexpr char RegionNamesChunk0[] =
        "AAXAAYAAZAAaAAbAAcAAdAAeAAfAAgAAhAAiAAjAAkAAlAAmAAnAAoAApAAqAArAAsAAtAAuAAvAAwAAxAAyAAzAA0AA1AARAASA"
        "ATAAUAAVAAW";
    inline constexpr const char* RegionNamesChunks[] = {RegionNamesChunk0};
    inline constexpr Packed RegionNames{RegionNamesChunks, 13, 3};

    inline constexpr const uint32_t* ScriptKeys = nullptr;

    inline constexpr const uint16_t* ScriptNames = nullptr;

    inline constexpr const uint32_t* AloneKeys = nullptr;

    inline constexpr const uint16_t* AloneNames = nullptr;

    inline constexpr char CurrencyKeysChunk0[] =
        "AgtAsuC4XDkv";
    inline constexpr const char* CurrencyKeysChunks[] = {CurrencyKeysChunk0};
    inline constexpr Packed CurrencyKeys{CurrencyKeysChunks, 13, 3};

    inline constexpr char CurrencyNamesChunk0[] =
        "AA2AAAAA3AAAAA4AAAAA5AA6AAAAA7AAAAA8AAAAA9AA+AAAAA/AAAABAAAAABBABCAAAABDAAAABEAAAABF";
    inline constexpr const char* CurrencyNamesChunks[] = {CurrencyNamesChunk0};
    inline constexpr Packed CurrencyNames{CurrencyNamesChunks, 13, 3};

    inline constexpr char ZoneKeysChunk0[] =
        "AB3AB4AB6ACFACcACdACeACjACkACmACqACrACxACzAC0AC3AC5ADFADGADOAFRAFgAFsAGu";
    inline constexpr const char* ZoneKeysChunks[] = {ZoneKeysChunk0};
    inline constexpr Packed ZoneKeys{ZoneKeysChunks, 13, 3};

    inline constexpr char ZoneNamesChunk0[] =
        "ABdAAAAAAAAAAAAAAAAAAABaAAAAAAAAAAAAAAAAAAABbAAAAAAAAAAAAAAAAAAABcAAAAAAAAAAAAAAAAAAABXAAAAAAAAAAAAA"
        "AAAAAABZAAAAAAAAAAAAAAAAAAABYAAAAAAAAAAAAAAAAAAABRAAAAAAAAAAAAAAAAAAABWAAAAAAAAAAAAAAAAAAABUAAAAAAAA"
        "AAAAAAAAAAABLAAAAAAAAAAAAAAAAAAABMAAAAAAAAAAAAAAAAAAABQAAAAAAAAAAAAAAAAAAAAZAAAAAAAAAAAAAAAAAAABNAAA"
        "AAAAAAAAAAAAAAAABeAAAAAAAAAAAAAAAAAAABKAAAAAAAAAAAAAAAAAAABIAAAAAAAAAAAAAAAAAAABJAAAAAAAAAAAAAAAAAAA"
        "BVAAAAAAAAAAAAAAAAAAAAAAAAABGAAAAAAABHAAAABSAAAAAAABTAAAAAAAAAABOAAAAAAABPAAAAAAAAAAAuAAAAAAAAAAAAAA"
        "AAAA";
    inline constexpr const char* ZoneNamesChunks[] = {ZoneNamesChunk0};
    inline constexpr Packed ZoneNames{ZoneNamesChunks, 13, 3};

    inline constexpr char MetaKeysChunk0[] =
        "AABAACAADAAFAAGAAIAALAAMAANAAOAAPAARAAUAAVAAWAAXAAZAAaAAbAAcAAdAAeAAfAAhAAjAAkAAmAAoAApAArAAsAAtAAuA"
        "AvAAwAAxAAyAAzAA1AA3AA6AA7AA8AA9AA+ABAABBABCABDABEABGABHABIABJABKABOABPABRABSABTABUABVABWABXABYABZAB"
        "aABbABcABeABfABgABjABkABlABnABoABpABsABvABwAByAB0AB1AB2AB3AB4AB5AB6AB7AB8AB9AB+AB/ACAACBACCACDACEACF"
        "ACHACIACKACLACMACNACOACPACQACRACSACTACUACWACXACYACbACcACeACfACgAChACjACkAClACmACpACqACrACtACuACwACyA"
        "CzAC0AC1AC2AC3AC4AC5AC6AC7";
    inline constexpr const char* MetaKeysChunks[] = {MetaKeysChunk0};
    inline constexpr Packed MetaKeys{MetaKeysChunks, 13, 3};

    inline constexpr char MetaNamesChunk0[] =
        "AAAABfAAAAAAAAAAAAAAAABgAAAAAAAAAAAAAAAABhAAAAAAAAAAAAAAAABiAAAAAAAAAAAAABjABkABlAAAAAAAAAABmABnABoA"
        "AAAAAAAAABpABqABrAAAAAAAAAABsABtABuAAAAAAAAAABvABwABxAAAAAAAAAAByABzAB0AAAAAAAAAAB1AB2AB3AAAAAAAAAAB"
        "4AB5AB6AAAAAAAAAAB7AB8AB9AAAAAAAAAAB+AB/ACAAAAAAAAAAACBACCACDAAAAAAAAAACEACFACGAAAAAAAAAACHACIACJAAA"
        "AAAAAAACKACLACMAAAAAAAAAACNACOACPAAAAAAAAAACQACRACSAAAAAAAAAACTACUACVAAAAAAAAAACWACXACYAAAAAAAAAACZA"
        "CaACbAAAAAAAAAACcACdACeAAAAAAAAAAAAACfAAAAAAAAAAAAAAAACgAAAAAAAAAAAAAChACiACjAAAAAAAAAAAAACkAAAAAAAA"
        "AAAAAClACmACnAAAAAAAAAAAAACoAAAAAAAAAAAAACpACqACrAAAAAAAAAACsACtACuAAAAAAAAAACvACwACxAAAAAAAAAAAAACy"
        "AAAAAAAAAAAAAAAACzAAAAAAAAAAAAAC0AC1AC2AAAAAAAAAAC3AC4AC5AAAAAAAAAAC6AC7AC8AAAAAAAAAAAAAC9AAAAAAAAAA"
        "AAAAAAC+AAAAAAAAAAAAAAAAC/AAAAAAAAAAAAADAADBADCAAAAAAAAAAAAADDAAAAAAAAAAAAADEADFADGADHADHADIADJADKAD"
        "LADMADMADNADOADPADQADRADRADSADTADUADVAAAAAAAAAADWADXADYAAAAAAAAAAAAADZAAAAAAAAAAAAAAAADaAAAAAAAAAAAA"
        "AAAADhAAAAAAADiAAAAAAADbAAAAAAAAAAAAAAAADcAAAAAAAAAAAAADdADeADfAAAAAAAAAAAAADgAAAAAAAAAAAAADjADkADlA"
        "AAAAAAAAADmADnADoAAAAAAAAAAAAADpAAAAAAAAAAAAAAAADqAAAAAAAAAAAAADrADsADtAAAAAAAAAADuADvADwAAAAAAAAAAD"
        "xADyADzAAAAAAAAAAAAAD0AAAAAAAAAAAAAAAAD1AAAAAAAAAAAAAAAAD2AAAAAAAAAAAAAAAAD3AAAAAAAAAAAAAAAAD4AAAAAA"
        "AAAAAAAAAAD5AAAAAAAAAAAAAD6AD7AD8AAAAAAAAAAD9AD+AD/AAAAAAAAAAEAAEBAECAAAAAAAAAAEDAEEAEFAAAAAAAAAAAAA"
        "EGAAAAAAAAAAAAAAAAEHAAAAAAAAAAAAAAAAEIAAAAAAAAAAAAAEJAEKAELAAAAAAAAAAAAAEMAAAAAAAAAAAAAENAEOAEPAAAAA"
        "AAAAAAAAEQAAAAAAAAAAAAAAAAERAAAAAAAAAAAAAESAETAEUAAAAAAAAAAEVAEWAEXAAAAAAAAAAAAAEYAAAAAAAAAAAAAAAAEZ"
        "AAAAAAAAAAAAAAAAEaAAAAAAAAAAAAAAAAEbAAAAAAAAAAAAAEcAEdAEeAAAAAAAAAAAAAEfAAAAAAAAAAAAAEgAEhAEiAAAAAAA"
        "AAAEjAEkAElAAAAAAAAAAEmAEnAEoAAAAAAAAAAAAAEpAAAAAAAAAAAAAAAAEqAAAAAAAAAAAAAAAAErAAAAAAAAAAAAAEsAEtAE"
        "uAAAAAAAAAAEvAEwAExAAAAAAAAAAEyAEzAE0AAAAAAAAAAAAAE1AAAAAAAAAAAAAE2AE3AE4AAAAAAAAAAE5AE6AE7AAAAAAAAA"
        "AE8AE9AE+AAAAAAAAAAE/AFAAFBAAAAAAAAAAFCAFDAFEAAAAAAAAAAAAAFFAAAAAAAAAAAAAAAAFGAAAAAAAAAAAAAFHAFIAFJA"
        "AAAAAAAAAFKAFLAFMAAAAAAAAAAFNAFOAFPAAAAAAAAAAAAAFQAAAAAAAAAAAAAFRAFSAFTAAAAAAAAAAAAAFUAAAAAAAAAAAAAA"
        "AAFVAAAAAAAAAAAAAAAAFWAAAAAAAAAAAAAAAAFXAAAAAAAAAAAAAAAAFYAAAAAAAAAAAAAFZAFaAFbAAAAAAAAAAFcAFdAFeAAA"
        "AAAAAAAAAAFfAAAAAAAAAAAAAAAAFgAAAAAAAAAAAAAAAAFhAAAAAAAAAAAAAAAAFiAAAAAAAAAAAAAAAAFjAAAAAAAAAAAAAAAA"
        "FkAAAAAAAAAAAAAAAAFlAAAAAAAAAAAAAFmAFnAFoAAAAAAAAAAAAAFpAAAAAAAAAAAAAAAAFqAAAAAAAAAAAAAFrAFsAFtAAAAA"
        "AAAAAAAAFuAAAAAAAAAAAAAFvAFwAFxAAAAAAAAAAAAAFyAAAAAAAAAAAAAFzAF0AF1AAAAAAAAAAF2AF3AF4AAAAAAAAAAF5AF6"
        "AF7AAAAAAAAAAAAAF8AAAAAAAAAAAAAF9AF+AF/AAAAAAAAAAGAAGBAGCAAAAAAAAAAAAAGDAAAAAAAAAAAAAAAAGEAAAAAAAAAA"
        "AAAAAAGFAAAAAAAAAAAAAGGAGHAGIAAAAAAAAAAGJAGKAGLAAAAAAAAA";
    inline constexpr const char* MetaNamesChunks[] = {MetaNamesChunk0};
    inline constexpr Packed MetaNames{MetaNamesChunks, 13, 3};

    inline constexpr uint16_t Formats[] = {
        396, 397, 398, 399, 400, 401, 0, 0, 0, 0, 0, 402,
    };

    inline constexpr Table table{
        0x73720000006e, 0x737200000000,
        NameTexts,
        LanguageKeys, LanguageNames, 15,
        nullptr, Packed{}, 0,
        RegionKeys, RegionNames, 37,
        Packed{}, Packed{}, 0,
        Packed{}, Packed{}, 0,
        CurrencyKeys, CurrencyNames, 4,
        ZoneKeys, ZoneNames, 24,
        MetaKeys, MetaNames, 142,
        Formats,
    };

    // the table registered when the header is included, once a program
    inline Registration registration{&table};
}
