//------------------------------------------------------------------------------
// SGCL: a C++20 application platform
// Copyright (c) 2022-2026 Sebastian Nibisz
// SPDX-License-Identifier: Apache-2.0
//------------------------------------------------------------------------------
#pragma once
#include "detail/registry.h"
#include "sw.h"

#include <cstdint>

// The display names of the locale sw-CD (Kiswahili), CLDR 46.0: the names of languages,
// regions, scripts, currencies and time zones in it, what differs from sw (included).
// Including this header is all a program does: txt::locale::display_name,
// region::display_name, script::display_name and currency::display_name then
// answer in this language. Generated by tools/cldr_tables.py: do not edit.
namespace sgcl::txt::detail::names::l_sw_CD {
    inline constexpr char8_t NameChunk0[] =
        u8"KiakanKiarabu cha Dunia KilichosanifishwaKiarabu cha AljeriaKiazabajaniKimanksiKigwichiinKihupaKiloj"
        u8"banKikachinKikakoKikomipermyakKikurukhKikumykKikirigiziKilambaKilimburgiKimokshaKimikmakiKimasedonia"
        u8"KimohokiKimossiKingiemboonKiinkoPijini ya NijeriaKikiicheKiarabu cha ChadiKitongo cha SrananKikomoro"
        u8"KisiriaKiudumurtiKiyidiAsia MasharikiAfuganistaniAzabajaniBeniniKodivaaKisiwa cha ChristmasKroeshiaY"
        u8"ordaniLebanoniLishenteniLasembagiLativiaMorokoMyamaNijeriNijeriaNorweNepaliOmaniPuetorikoKatariSudan"
        u8"iSao Tome na PrinsipeChadiTimori ya MasharikiYuan Renminbi ya Chinayuan ya Uchinayuan za UchinaBir y"
        u8"a Uhabeshibirr ya Uhabeshibirr za UhabeshiSarafu ya Kijapaniyen ya Japaniyen za JapaniAriary ya Buki"
        u8"niariari ya Madagaskaariari za MadagaskaUgwiya ya Moritaniaouguiya ya Moritaniaouguiya za MoritaniaR"
        u8"upia ya Shelishelirupia ya Ushelishelirupia za UshelisheliFaranga CFA BEACfaranga ya Afrika ya Kati "
        u8"CFAfaranga za Afrika ya Kati CFAFaranga CFA BCEAOfaranga ya Afrika Magharibi CFAfaranga za Afrika Ma"
        u8"gharibi CFA{0} ({1}){0}, {1}Saa za {0}Saa za wastani za {0}Saa za Mchana za {0}{1} ({0}){0} {1}{1} {"
        u8"0}";
    inline constexpr const char8_t* NameChunks[] = {NameChunk0};
    inline constexpr uint16_t NameChunkSizes[] = {1102};
    inline constexpr char NameRefsChunk0[] =
        "AAAAAAAAAAAGAAApAAA8AABHAABPAABZAABfAABnAABvAAB1AACCAACKAACRAACbAACiAACsAAC0AAC9AADIAADQAADXAADiAADo"
        "AAD5AAEBAAESAAEkAAEsAAEzAAE9AAFDAAFRAAFdAAFmAAFsAAFzAAGHAAGPAAGWAAGeAAGoAAGxAAG4AAG+AAHDAAHJAAHQAAHV"
        "AAHbAAHgAAHpAAHvAAH1AAIJAAIOAAIhAAI3AAJFAAJTAAJiAAJyAAKCAAKUAAKhAAKuAAK+AALRAALkAAL3AAMLAAMfAAMyAANG"
        "AANaAANqAAOHAAOkAAO1AAPUAAPzAAP8AAQEAAQOAAQjAAQ3AARAAARHAARO";
    inline constexpr const char* NameRefsChunks[] = {NameRefsChunk0};
    inline constexpr Packed NameRefs{NameRefsChunks, 13, 4};
    inline constexpr Text NameTexts{NameChunks, NameChunkSizes, NameRefs};

    inline constexpr char LanguageKeysChunk0[] =
        "AArAA6AD2AF5AGJAGrAMpAZRB7pCKwChPCwjC1qC3pC5VC6tDAtDSGDUjDXoDXzDnIDovEBtEajE0VE5OE7iE8yFSN";
    inline constexpr const char* LanguageKeysChunks[] = {LanguageKeysChunk0};
    inline constexpr Packed LanguageKeys{LanguageKeysChunks, 13, 3};

    inline constexpr char LanguageNamesChunk0[] =
        "AABAAEAAFAAOAAQAATAAfAADAAGAAHAAIAAJAAKAALAAMAANAAPAARAASAAUAAVAAWAAXAAYAAZAAaAAbAAcAAdAAe";
    inline constexpr const char* LanguageNamesChunks[] = {LanguageNamesChunk0};
    inline constexpr Packed LanguageNames{LanguageNamesChunks, 13, 3};

    inline constexpr const uint64_t* TaggedKeys = nullptr;

    inline constexpr const uint16_t* TaggedNames = nullptr;

    inline constexpr char RegionKeysChunk0[] =
        "AAhAA1ABAABaABpADqAEdAFGAFNAFZAFaAFgAFsAF/AGBAGJAGKAGiAHCAHMAIFAIVAIgAIoAL3";
    inline constexpr const char* RegionKeysChunks[] = {RegionKeysChunk0};
    inline constexpr Packed RegionKeys{RegionKeysChunks, 13, 3};

    inline constexpr char RegionNamesChunk0[] =
        "AAhAAiAAjAAkAAlAAmAAnAAoAApAAqAArAAsAAtAAuAAvAAwAAxAAyAAzAA0AA1AA2AA3AA4AAg";
    inline constexpr const char* RegionNamesChunks[] = {RegionNamesChunk0};
    inline constexpr Packed RegionNames{RegionNamesChunks, 13, 3};

    inline constexpr const uint32_t* ScriptKeys = nullptr;

    inline constexpr const uint16_t* ScriptNames = nullptr;

    inline constexpr const uint32_t* AloneKeys = nullptr;

    inline constexpr const uint16_t* AloneNames = nullptr;

    inline constexpr char CurrencyKeysChunk0[] =
        "A3ZBaCCoZDThDZVExyGAmGHm";
    inline constexpr const char* CurrencyKeysChunks[] = {CurrencyKeysChunk0};
    inline constexpr Packed CurrencyKeys{CurrencyKeysChunks, 13, 3};

    inline constexpr char CurrencyNamesChunk0[] =
        "AA5AAAAA6AAAAAAAAAAA7AA8AAAAA9AAAAAAAAAAA+AA/AAAABAAAAAAAAAAABBABCAAAABDAAAAAAAAAABEABFAAAABGAAAAAAA"
        "AAABHABIAAAABJAAAAAAAAAABKABLAAAABMAAAAAAAAAABNABOAAAABPAAAAAAAAAABQ";
    inline constexpr const char* CurrencyNamesChunks[] = {CurrencyNamesChunk0};
    inline constexpr Packed CurrencyNames{CurrencyNamesChunks, 13, 3};

    inline constexpr const uint16_t* ZoneKeys = nullptr;

    inline constexpr const uint16_t* ZoneNames = nullptr;

    inline constexpr const uint16_t* MetaKeys = nullptr;

    inline constexpr const uint16_t* MetaNames = nullptr;

    inline constexpr uint16_t Formats[] = {
        81, 82, 83, 84, 85, 86, 0, 87, 0, 0, 0, 88,
    };

    inline constexpr Table table{
        0x7377000000aa, 0x737700000000,
        NameTexts,
        LanguageKeys, LanguageNames, 30,
        nullptr, Packed{}, 0,
        RegionKeys, RegionNames, 25,
        Packed{}, Packed{}, 0,
        Packed{}, Packed{}, 0,
        CurrencyKeys, CurrencyNames, 8,
        Packed{}, Packed{}, 0,
        Packed{}, Packed{}, 0,
        Formats,
    };

    // the table registered when the header is included, once a program
    inline Registration registration{&table};
}
