//------------------------------------------------------------------------------
// SGCL: a C++20 application platform
// Copyright (c) 2022-2026 Sebastian Nibisz
// SPDX-License-Identifier: Apache-2.0
//------------------------------------------------------------------------------
#pragma once
#include "detail/registry.h"

#include <cstdint>

// The display names of the locale tt (татар), CLDR 46.0: the names of languages,
// regions, scripts, currencies and time zones in it.
// Including this header is all a program does: txt::locale::display_name,
// region::display_name, script::display_name and currency::display_name then
// answer in this language. Generated by tools/cldr_tables.py: do not edit.
namespace sgcl::txt::detail::names::l_tt {
    inline constexpr char8_t NameChunk0[] =
        u8"африкаансамхаргарәпЗаманча стандарт гарәпмапучеассамәзәрбайҗанбашкортбалибелорусбембаболгарбенгалити"
        u8"бетбретонбосниякаталансебуаномаричерокиүзәк көрдкорсикачехуэльсданияалманюгары алман (Швейцария)түбә"
        u8"н сорбмальдивдзонг-кхагрекинглизБритания инглизчәсеАмерика инглизчәсеэсперантоиспаниспан (Латин Амер"
        u8"икасы)испан (Европа)эстонбаскфарсыфулафинфилиппинфарерфранцузирландшотланд гэльгалисиягуаранигуҗарат"
        u8"ихаусагавайияһүдһиндхилигайнонхорватюгары сорбгаити креолвенгрәрмәнгерероибибиоиндонезияигбоисландит"
        u8"альянинуктикутяпонгрузинказакъкхмерканнадакореяконканиканурикурухкашмирикөрдкыргызлатинлюксембурглао"
        u8"слитвалатышмендемалагасимаоримакедонмалаяламмонголманипуримогаукмаратхималаймальтабирманепалиниуэгол"
        u8"ландфламандчаньянҗаокситаноромоорияпәнҗабипапьяментополякпуштупортугалпортугал (Европа)кечуакичерето"
        u8"романрумынрусруандасанскритсахасанталисиндһитөньяк саамсингалсловаксловенкөньяк саамлуле-сааминари-с"
        u8"аамколтта-саамсомалиалбансербшведсүриятамилтелугутаҗиктайтигриньятөрекмәнтонгатөректатарүзәк атлас т"
        u8"амазигтуйгырукраинбилгесез телурдуүзбәквендавьетнамволофидишйорубакытайгадиләштерелгән кытайтрадицио"
        u8"н кытайдөньяАфрикаТөньяк АмерикаКөньяк АмерикаОкеанияКөнбатыш АфрикаҮзәк АмерикаКөнчыгыш АфрикаТөнья"
        u8"к АфрикаУрта АфрикаКөньяктагы АфрикаАмерикаТөньяктагы АмерикаКариб бассейныКөнчыгыш АзияКөньяк АзияК"
        u8"өньяк-Көнчыгыш АзияКөньяк ЕвропаАвстралазияМеланезияМикронезия төбәгеПолинезияАзияҮзәк АзияКөнбатыш "
        u8"АзияЕвропаКөнчыгыш ЕвропаТөньяк ЕвропаКөнбатыш ЕвропаСахарадан көньякта АфрикаЛатин АмерикаВознесени"
        u8"е утравыАндорраБерләшкән Гарәп ӘмирлекләреӘфганстанАнтигуа һәм БарбудаАнгильяАлбанияӘрмәнстанАнголаА"
        u8"нтарктикаАргентинаАмерика СамоасыАвстрияАвстралияАрубаАланд утрауларыӘзәрбайҗанБосния һәм Герцеговин"
        u8"аБарбадосБангладешБельгияБуркина-ФасоБолгарияБәхрәйнБурундиБенинСен-БартельмиБермуд утрауларыБрунейБ"
        u8"оливияКариб НидерландларыБразилияБагам утрауларыБутанБуве утравыБотсванаБеларусьБелизКанадаКокос (Ки"
        u8"линг) утрауларыКонго (КДР)Үзәк Африка РеспубликасыКонго - БраззавильШвейцарияКот-д’ИвуарКук утраулар"
        u8"ыЧилиКамерунКытайКолумбияКлиппертон утравыКоста-РикаКубаКабо-ВердеКюрасаоРаштуа утравыКипрЧехия Респ"
        u8"убликасыГерманияДиего ГарсияҖибүтиДанияДоминикаДоминикана РеспубликасыАлжирСеута һәм МелильяЭквадорЭ"
        u8"стонияМисырКөнбатыш СахараЭритреяИспанияЭфиопияЕвропа БерлегеЕврозонаФинляндияФиджиФолкленд утраулар"
        u8"ыМикронезияФарер утрауларыФранцияГабонБерләшкән КорольлекГренадаГрузияФранцуз ГвианасыГернсиГанаГибр"
        u8"алтарГренландияГамбияГвинеяГваделупаЭкваториаль ГвинеяГрецияКөньяк Георгия һәм Көньяк Сандвич утраул"
        u8"арыГватемалаГуамГвинея-БисауГайанаГонконг Махсус Идарәле ТөбәгеХерд утравы һәм Макдональд утрауларыГ"
        u8"ондурасХорватияГаитиВенгрияКанар утрауларыИндонезияИрландияИзраильМэн утравыИндияБританиянең Һинд Ок"
        u8"еанындагы ТерриториясеГыйракИранИсландияИталияДжерсиЯмайкаИорданияЯпонияКенияКыргызстанКамбоджаКириб"
        u8"атиКомор утрауларыСент-Китс һәм НевисТөньяк КореяКөньяк КореяКүвәйтКайман утрауларыКазахстанЛаосЛива"
        u8"нСент-ЛюсияЛихтенштейнШри-ЛанкаЛиберияЛесотоЛитваЛюксембургЛатвияЛивияМароккоМонакоМолдоваЧерногория"
        u8"Сент-МартинМадагаскарМаршалл утрауларыТөньяк МакедонияМалиМьянма (Бирма)МонголияМакао Махсус Идарәле"
        u8" ТөбәгеТөньяк Мариана утрауларыМартиникаМавританияМонтсерратМальтаМаврикийМальдив утрауларыМалавиМек"
        u8"сикаМалайзияМозамбикНамибияЯңа КаледонияНигерНорфолк утравыНигерияНикарагуаНидерландНорвегияНепалНау"
        u8"руНиуэЯңа ЗеландияОманПанамаПеруФранцуз ПолинезиясеПапуа - Яңа ГвинеяФилиппинПакистанПольшаСен-Пьер "
        u8"һәм МикелонПиткэрн утрауларыПуэрто-РикоФәләстин территорияләреПортугалияПалауПарагвайКатарЕрак Океан"
        u8"ияРеюньонРумынияСербияРоссияРуандаСогуд ГарәбстаныСөләйман утрауларыСейшел утрауларыСуданШвецияСинга"
        u8"пурИзге Елена утравыСловенияШпицберген һәм Ян-МайенСловакияСьерра-ЛеонеСан-МариноСенегалСомалиСурина"
        u8"мКөньяк СуданСан-Томе һәм ПринсипиСальвадорСинт-МартенСүрияСвазилендТристан-да-КуньяТеркс һәм Кайкос"
        u8" утрауларыЧадФранциянең Көньяк ТерриторияләреТогоТайландТаҗикстанТокелауТимор-ЛестеТөркмәнстанТунисТ"
        u8"онгаТөркияТринидад һәм ТобагоТувалуТайваньТанзанияУкраинаУгандаАКШ Кече Читтәге утрауларыБерләшкән М"
        u8"илләтләрАКШУругвайҮзбәкстанВатиканСент-Винсент һәм ГренадинВенесуэлаБритания Виргин утрауларыАКШ Вир"
        u8"гин утрауларыВьетнамВануатуУоллис һәм ФутунаСамоаПсевдоакцентларПсевдо-БидиКосовоЙәмәнМайоттаКөньяк "
        u8"АфрикаЗамбияЗимбабвебилгесез төбәккириллгадиләштерелгәнтрадиционязусызбилгесез язуБерләшкән Гарәп Әм"
        u8"ирлекләре дирхамыБерләшкән Гарәп Әмирлекләре дирхамнарыӘфган әфганыӘфган әфганларыАлбания ЛекеАлбани"
        u8"я лекеАрмения драмыАрмения драмнарыАнгола кванзасыАнгола кванзаларыАргентина песосыАргентина песолар"
        u8"ыАвстралия долларыАвстралия долларларыАрубан ФлориныАрубан флориныӘзербайҗан манатыӘзербайҗан манатл"
        u8"арыБосния һәм Герцеговинаның конвертацияләнә торган маркасыБосния һәм Герцеговинаның конвертацияләнә"
        u8" торган маркаларыБарбадос долларыБарбадос долларларыБангладеш такасыБангладеш такаларыБолгар ЛевыБол"
        u8"гар левыБахрейн динарыБахрейн динарларыБурунди франкыБурунди франкларыБермуд долларыБермуд долларлар"
        u8"ыБруней долларыБруней долларларыБоливиа боливианосыБоливиа боливианоларыБразилия реалыБагам долларыБ"
        u8"агам долларларыБутан нгултрумыБутан нгултрумнарыБотсвана пуласыБотсвана пулаларыБеларус сумыБеларус "
        u8"сумнарыБелиз долларыБелиз долларларыКанада долларыКанада долларларыКонголез франкыКонголез франклары"
        u8"Швейцария франкыШвейцария франкларыЧили песосыЧили песоларыкытай юанеюаньКолумбия песосыКолумбия пес"
        u8"оларыКоста-Рика колоныКоста-Рика колоннарыКуба песосыКуба песоларыКабо-Верде эскудосыКабо-Верде эску"
        u8"доларыЧех кронасыЧех кроналарыҖибути франкыҖибути франкларыДания КронасыДания кронасыДоминикана песо"
        u8"сыДоминикана пеосларыАлжир динарыАлжир динарларыМисыр фунтыМисыр фунтларыЭритрея накфасыЭритрея накф"
        u8"аларыЭфиопия бырыЭфиопия бырларыевроФиджи долларыФиджи долларларыФолкленд утраулары фунтыФолкленд ут"
        u8"раулары фунтларыфунт стерлингГрузия лариеГрузия лариларыГана седиеГана седиларыГибралтар фунтыГибрал"
        u8"тар фунтларыГамбия даласиеГамбия даласиларыГвинея франкыГвинея франкларыГватемала кетсалыГватемала к"
        u8"етсалиларыГайана долларыГайана долларларыГонконг долларыГонконг долларларыГондурас лемпирыГондурас л"
        u8"емпирларыГаити гурдыГаити гурдларыВенгрия форинтыВенгрия форинтларыИндонезия рупиясеИндонезия рупиял"
        u8"әреИзраиль яңа шекелеИзраиль яңа шекельләреИндия рупиясеИрак динарыИрак динарларыИран риалыИран риал"
        u8"ларыИсландия КронасыИсландия кронасыЯмайка долларыЯмайка долларларыИордания динарыИордания динарлары"
        u8"япон иенасыиенаКения шиллингыКения шиллингларыКкргызстан сомыКыргызстан сомнарыКамбоджа риелыКамбодж"
        u8"а риелларыКомор утраулары франкыКомор утраулары франкларыТөньяк Корея ВонасыТөньяк Корея вонасыКөнья"
        u8"к Корея ВонасыКөньяк Корея вонасыКувейт динарыКувейт динарларыКайман утраулары долларыКайман утраула"
        u8"ры долларларыКазахстан тәңкәсеКазахстан тәңкәләреЛаос кипыЛаос кипларыЛиван фунтыЛиван фунтларыШри-Л"
        u8"анка рупиясеШри-Ланка рупияләреЛиберия долларыЛиберия долларларыЛесото лотисыЛесото лотисларыЛивия д"
        u8"инарыЛивия динарларыМарокко дирхамыМарокко дирхамнарыМолдавия ЛееМолдавия лееМалагаси ариариясеМалаг"
        u8"аси ариарияләреМакедония денарыМакедония денарларыМьянма кьятыМьянма кьятларыМонголия тугрикыМонголи"
        u8"я тугрикларыМакао патакыМакао патакларыМавритан угиясыМавритан угияларыМаврикий рупиеМаврикий рупиял"
        u8"арыМальдив руфиясеМальдив руфияләреМалавия квачиеМалавия квачиларыМексика песосыМексика песоларыМала"
        u8"йзия ринггитыМалайзия ринггитларыМозамбик метикалыМозамбик метикалларыНамибия долларыНамибия долларл"
        u8"арыНигерия найрасыНигерия найраларыНикарагуа кордовасыНикарагуа кордоваларыНорвегия КронасыНорвегия "
        u8"кронасыНепал рупиясеНепал рупияләреЯңа Зеландия долларыЯңа Зеландия долларларыОман риалыОман риаллар"
        u8"ыПанама бальбоасыПанама бальбоаларыПеру солыПеру солларыПапуа Яңа Гвинея КинасыПапуа Яңа Гвинея кина"
        u8"сыФилиппин песосыФилиппин песоларыПакистан рупиясеПакистан рупияләреПольша злотыеПольша злотыйларыПа"
        u8"рагвай гуаранисыПарагвай гуараниларыКатар риалыКатар риалларыРумыния ЛееРумыния лееСербия динарыСерб"
        u8"ия динарларыРоссия сумысумРуанда франкыРуанда франкларыСогуд Гарәбстаны риалыСогуд Гарәбстаны риалла"
        u8"рыСоломон утраулары долларыСоломон утраулары долларларыСейшел утраулары рупиясыСейшел утраулары рупи"
        u8"яларыСудан фунтыСудан фунтларыШвеция КронасыШвеция кронасыСингапур долларыСингапур долларларыИзге Ел"
        u8"ена утравы фунтыИзге Елена утравы фунтларыСьерра-Леон леоныСьерра-Леоне леоннарыСомали шиллингыСомал"
        u8"и шиллингларыСуринам долларыСуринам долларларыКөньяк Судан фунтыКөньяк Судан фунтларыСан-Томе һәм Пр"
        u8"инсипи добрасыСан-Томеһәм Принсипи добраларыСурия фунтыСурия фунтларыСвази эмалангенисыСвази эмаланг"
        u8"ениларыТайвань БатыТайвань батыТаҗикстан сомонисыТаҗикстан сомониларыТөркмәнстан МанатыТөркмәнстан м"
        u8"анатыТунис динарыТунис динарларыТонга ПаангасыТонга паангасыТөркия ЛирасыТөркия лирасыТринидад һәм Т"
        u8"обаго долларыТринидад һәм Тобаго долларларыЯңа Тайвань долларыЯңа Тайвань долларларыТанзания шиллинг"
        u8"ыТанзания шиллингларыУкраина гривнасыУкраина гривналарыУганда шиллингыУганда шиллингларыАКШ долларыУ"
        u8"ругвай песосыУругвай песоларыҮзбәкстан СомыҮзбәкстан сомыВенесуэла боливарыВенесуэла боливарларыВьет"
        u8"нам ДонгыВьетнам донгыВануату ватыВануату ватларыСамоа ТаласыСамоа таласыҮзәк Африка франкы КФАҮзәк "
        u8"африка франклары КФАКөнчыгыш Кариб долларыКөнчыгыш Кариб долларларыКөнбатыш Африка КФА франкыКөнбаты"
        u8"ш Африка КФА франкларыФранциянең диңгез аръягы җәмгыятьләре франкыФранциянең диңгез аръягы җәмгыятьл"
        u8"әре франкларыбилгесез валюта(билгесез валюта)Йәмән риалыЙәмән риалларыКөньяк Африка РэндыКөньяк Афри"
        u8"ка рэндыЗамбия квачасыЗамбия квачаларыБөтендөнья килештерелгән вакытыUTCбилгесез шәһәрДубайКабулАнти"
        u8"гуаТиранЕреванЛуандаРотераПалмерТролльСёваМоусонДэвисВостокКейсиДюмон д’ЮрвильМакМёрдоРио-ГальегосМе"
        u8"ндосаСан-ХуанУшуайяЛа РиохаСан-ЛуисКатамаркаСальтаЖужуйТукуманКордобаБуэнос-АйресПаго ПагоВенаПертЮк"
        u8"лаДарвинАделаидаБрокен-ХиллМельбурнХобартЛиндеманСиднейБрисбенМаккуориЛорд ХауМариехамнБакуСараевоДа"
        u8"ккаБрюссельУагадугуСофияБахрейнБөҗүмбураПорто-НовоИзге ВарфоломейЛа-ПасКралендейкЭйрунепеРио-БранкоП"
        u8"орту-ВельюБоа-ВистаМанаусКуябаСантаремКампо-ГрандеБелемАрагуайнаСан-ПаулуБаияФорталезаМасейоРесифиНо"
        u8"роньяНассауТхимпхуГаборонеМинскДоусонУайтхорсИнувикВанкуверФорт НельсонДоусон-КрикКрестонЭдмонтонКем"
        u8"бридж БэйРегинаВиннипегРезолютРанкин-ИнлетАтикоканТоронтоИкалуитМонктонГалифаксКаз бухтасыГлейс БэйБ"
        u8"лан-СаблонСент-ДжонсКокосКиншасаЛубумбашиБангиБраззавильЦюрихИдиҗанРаротонгаПасха утравыПунта-Аренас"
        u8"СантьягоДуалаУрумчиШанхайБоготаГаванаРаштуаНикосияФамагустаПрагаБюзингенБерлинДжибутиКопенгагенСанто"
        u8"-ДомингоГалапагос утрауларыГуаякильТаллинКаһирәЭль-АюнАсмэраСеутаМадридАддис-АбебаХельсинкиСтэнлиЧуу"
        u8"кПонпеиКосраэПарижЛибревильЛондонБритания җәйге вакытыТбилисиКайеннаАккраТулеНуукИттоккортоормиитДан"
        u8"марксхавнБанҗулКонакриМалабоАфинКөньяк ДжорджияБиссауГонконгТегусигальпаЗагребПорт-о-ПренсБудапештҖа"
        u8"картаПонтианакМакассарҖәяпураДублинИрландия стандарт вакытыИерусалимКалькуттаЧагосБагдадТәһранРейкья"
        u8"викРимӘмманТокиоНайробиБишкекПномпеньКиритиматиТараваКомороСент-КитсПхеньянСеулКувейтАктауОралАтырау"
        u8"АктобеКостанайКызылордаАлма-АтаВьентьянБәйрүтИзге ЛюсияВадуцКоломбоМонровияМасеруВильнюсРигаТриполиК"
        u8"асабланкаКишиневПодгорицаМаригоАнтананаривуКваджалейнМаджуроСкопьеБамакоЯнгонХовдУлан-БаторМакаоСайп"
        u8"анНуакшотМонсерратБлантайрТихуанаЭрмосильоСьюдад-ХуаресМасатланЧихуахуаБаия-де-БандерасОхинагаМонтер"
        u8"рейМехикоМатаморосМеридаКанкунКуала-ЛумпурКучингМапутоВиндхукНумеаНиамейНорфолкЛагосМанагуаАмстердам"
        u8"ОслоКатмандуЧатемОклендМаскатЛимаТаитиМаркиз утрауларыГамбьеПорт-МорсбиБугенвильМанилаКарачиВаршаваМ"
        u8"икелонПиткэрнГазаҺевронАзор утрауларыМадейраЛиссабонАсунсьонБухарестБелградКалининградМәскәүВолгогра"
        u8"дСаратовӘстерханУльяновскКировСамараЕкатеринбургОмскНовосибирскБарнаулТомскНовокузнецкКрасноярскИрку"
        u8"тскЧитаЯкутскВладивостокХандыгаСахалинУсть-НераМагаданСреднеколымскКамчаткаАнадырьКигалиЭр-РиядГуада"
        u8"лканалМаэҺартумСтокгольмИзге ЕленаЛюблянаЛонгиербиенБратиславаФритаунДакарМогадишоПарамарибоҖубаСан-"
        u8"ТомеТүбәнге Кенәз кварталыДәмәшкъМбабанеГранд ТеркНҗаменКергеленЛомеБангкокДушанбеФакаофоДилиАшхабад"
        u8"ТонгатапуИстанбулПорт-оф-СпейнФунафутиТайпейДар-эс-СаламКиевСимферопольКампалаМидуэйВейкАдакНомеАнко"
        u8"риджЯкутатСиткаДжуноМетлакатлаЛос-АнджелесБойсеФениксДенверБьюла, Төньяк ДакотаНью-Салем, Төньяк Дак"
        u8"отаҮзәк, Төньяк ДакотаЧикагоМеноминиВинсеннес, ИндианаПетербург, ИндианаТелль-Сити, ИндианаНокс, Инд"
        u8"ианаУинамак, ИндианаМаренго, ИндианаИндианаполисЛуисвильВевей, ИндианаМонтичелло, КентуккиДетройтНью"
        u8"-ЙоркМонтевидеоСәмәркандТашкентСент-ВинсентКаракасТортолаСент-ТомасХо Ши МинЭфатеУоллисАпиаАденЙохан"
        u8"несбургЛусакаХарареАкр вакытыАкр стандарт вакытыАкр җәйге вакытыӘфганстан вакытыҮзәк Африка вакытыКө"
        u8"нчыгыш Африка вакытыКөньяк Африка вакытыКөнбатыш Африка вакытыКөнбатыш Африка стандарт вакытыКөнбаты"
        u8"ш Африка җәйге вакытыАляска вакытыАляска стандарт вакытыАляска җәйге вакытыАмазонка вакытыАмазонка с"
        u8"тандарт вакытыАмазонка җәйге вакытыТөньяк Америка үзәк вакытыТөньяк Америка гадәти үзәк вакытыТөньяк"
        u8" Америка җәйге үзәк вакытыТөньяк Америка көнчыгыш вакытыТөньяк Америка гадәти көнчыгыш вакытыТөньяк "
        u8"Америка җәйге көнчыгыш вакытыТөньяк Америка тау вакытыТөньяк Америка гадәти тау вакытыТөньяк Америка"
        u8" җәйге тау вакытыТөньяк Америка Тын океан вакытыТөньяк Америка гадәти Тын океан вакытыТөньяк Америка"
        u8" җәйге Тын океан вакытыАнадырь вакытыАнадырь стандарт вакытыАнадырь җәйге вакытыАпиа вакытыАпиа стан"
        u8"дарт вакытыАпиа җәйге вакытыГарәп вакытыГарәп стандарт вакытыГарәп җәйге вакытыАргентина вакытыАрген"
        u8"тина Стандарт вакытыАргентина җәйге вакытыКөнбатыш Аргентина вакытыКөнбатыш Аргентина стандарт вакыт"
        u8"ыКөнбатыш Аргентина җәйге вакытыАрмения вакытыАрмения стандарт вакытыАрмения җәйге вакытыТөньяк Амер"
        u8"ика атлантик вакытыТөньяк Америка гадәти атлантик вакытыТөньяк Америка җәйге атлантик вакытыҮзәк Авс"
        u8"тралия вакытыАвстралия үзәк стандарт вакытыАвстралия үзәк җәйге вакытыАвстралия үзәк көнбатыш вакыты"
        u8"Австралия үзәк көнбатыш стандарт вакытыАвстралия үзәк көнбатыш җәйге вакытыКөнчыгыш Австралия вакыты"
        u8"Көнчыгыш Австралия стандарт вакытыКөнчыгыш Австралия җәйге вакытыКөнбатыш Австралия вакытыКөнбатыш А"
        u8"встралия стандарт вакытыКөнбатыш Австралия җәйге вакытыӘзербайҗан вакытыӘзербайҗан стандарт вакытыӘз"
        u8"ербайҗан җәйге вакытыАзор утраулары вакытыАзор утраулары стандарт вакытыАзоу утраулары җәйге вакытыБ"
        u8"англадеш вакытыБангладеш стандарт вакытыБангладеш җәйге вакытыБутан вакытыБоливия вакытыБразилиа вак"
        u8"ытыБразилиа стандарт вакытыБразилиа җәйге вакытыБруней-Даруссалам вакытыКабо-Верде вакытыКабо-Верде "
        u8"стандарт вакытыКабо-Верде җәйге вакытыЧаморро стандарт вакытыЧатем вакытыЧатем стандарт вакытыЧатем "
        u8"җәйге вакытыЧили вакытыЧили стандарт вакытыЧили җәйге вакытыКытай вакытыКытай стандарт вакытыКытай җ"
        u8"әйге вакытыРаштуа утравы вакытыКокос утраулары вакытыКолумбия вакытыКолумбия стандарт вакытыКолумбия"
        u8" җәйге вакытыКук утраулары вакытыКук утраулары стандарт вакытыКук утраулары уртача җәйге вакытыКуба "
        u8"вакытыКуба стандарт вакытыКуба җәйге вакытыДэвис вакытыДюмон д’Юрвиль вакытыКөнчыгыш Тимор вакытыПас"
        u8"ха утравы вакытыПасха утравы стандарт вакытыПасха утравы җәйге вакытыЭквадор вакытыҮзәк Европа вакыт"
        u8"ыгадәти Үзәк Европа вакытыҗәйге Үзәк Европа вакытыКөнчыгыш Европа вакытыгадәти Көнчыгыш Европа вакыт"
        u8"ыҗәйге Көнчыгыш Европа вакытыЕрак Көнчыгыш Европа вакытыКөнбатыш Европа вакытыгадәти Көнбатыш Европа"
        u8" вакытыҗәйге Көнбатыш Европа вакытыФолкленд утраулары вакытыФолкленд утраулары стандарт вакытыФолкле"
        u8"нд утраулары җәйге вакытыФиджи вакытыФиджи стандарт вакытыФиджи җәйге вакытыФранцуз Гвиана вакытыФра"
        u8"нцуз көньяк һәм Антарктика вакытыГалапагос утраулары вакытыГамбье вакытыГрузия вакытыГрузия стандарт"
        u8" вакытыГрузия җәйге вакытыГилберт утраулары вакытыГринвич уртача вакытыКөнчыгыш Гренландия вакытыКөн"
        u8"чыгыш Гренландия стандарт вакытыКөнчыгыш Гренландия җәйге вакытыКөнбатыш Гренландия вакытыКөнбатыш Г"
        u8"ренландия стандарт вакытыКөнбатыш Гренландия җәйге вакытыФарсы култыгының стандарт вакытыГайана вакы"
        u8"тыГавай-Алеут вакытыГавай-Алеут стандарт вакытыГавай-Алеут җәйге вакытыГонконг вакытыГонконг стандар"
        u8"т вакытыГонконг җәйге вакытыХовд вакытыХовд стандарт вакытыХовд җәйге вакытыҺинд стандарт вакытыҺинд"
        u8" океаны вакытыҺинд-кытай вакытыҮзәк Индонезия вакытыКөнчыгыш Индонезия вакытыКөнбатыш Индонезия вакы"
        u8"тыИран вакытыИран стандарт вакытыИран җәйге вакытыИркутск вакытыИркутск стандарт вакытыИркутск җәйге"
        u8" вакытыИсраил вакытыИсраил стандарт вакытыИсраил җәйге вакытыЯпон вакытыЯпон стандарт вакытыЯпон җәй"
        u8"ге вакытыПетропавловск-Камчатский вакытыПетропавловск-Камчатский стандарт вакытыПетропавловск-Камчат"
        u8"ский җәйге вакытыКазахстан вакытыКөнчыгыш Казахстан вакытыКөнбатыш Казахстан вакытыКорея вакытыКорея"
        u8" стандарт вакытыКорея җәйге вакытыКосраэ вакытыКрасноярск вакытыКрасноярск стандарт вакытыКрасноярск"
        u8" җәйге вакытыКыргызстан вакытыЛайн утраулары вакытыЛорд Хау вакытыЛорд Хау стандарт вакытыЛорд Хау җ"
        u8"әйге вакытыМагадан вакытыМагадан стандарт вакытыМагадан җәйге вакытыМалайзия вакытыМальдив утраулары"
        u8" вакытыМаркиз утраулары вакытыМаршалл утраулары вакытыМаврикий вакытыМаврикий стандарт вакытыМаврики"
        u8"й җәйге вакытыМоусон вакытыМексика Тыныч океан вакытыМексика Тыныч океан стандартвакытыМексика Тыныч"
        u8" океан җәйге вакытыУлан-Батор вакытыУлан-Батор стандарт вакытыУлан-Батор җәйге вакытыМәскәү вакытыМә"
        u8"скәү стандарт вакытыМәскәү җәйге вакытыМьянма вакытыНауру вакытыНепал вакытыЯңа Каледония вакытыЯңа "
        u8"Каледония стандарт вакытыЯңа Каледония җәйге вакытыЯңа Зеландия вакытыЯңа Зеландия стандарт вакытыЯң"
        u8"а Зеландия җәйге вакытыНьюфаундленд вакытыНьюфаундленд стандарт вакытыНьюфаундленд җәйге вакытыНиуэ "
        u8"вакытыНорфолк утравы вакытыНорфолк утравы стандарт вакытыНорфолк утравы җәйге вакытыФернанду-ди-Норо"
        u8"нья вакытыФернанду-ди-Норонья стандарт вакытыФернанду-ди-Норонья җәйге вакытыНовосибирск вакытыНовос"
        u8"ибирск стандарт вакытыНовосибирск җәйге вакытыОмск вакытыОмск стандарт вакытыОмск җәйге вакытыПакист"
        u8"ан вакытыПакистан стандарт вакытыПакистан җәйге вакытыПалау вакытыПапуа Яңа Гвинея вакытыПарагвай ва"
        u8"кытыПарагвай стандарт вакытыПарагвай җәйге вакытыПеру вакытыПеру стандарт вакытыПеру җәйге вакытыФил"
        u8"иппин вакытыФилиппин стандарт вакытыФилиппин җәйге вакытыФеникс утраулары вакытыСен-Пьер һәм Микелон"
        u8" вакытыСен-Пьер һәм Микелон стандарт вакытыСен-Пьер һәм Микелон җәйге вакытыПиткэрн вакытыПонапе вак"
        u8"ытыПхеньян вакытыРеюньон вакытыРотера вакытыСахалин вакытыСахалин стандарт вакытыСахалин җәйге вакыт"
        u8"ыСамара вакытыСамара стандарт вакытыСамара җәйге вакытыСамоа вакытыСамоа стандарт вакытыСамоа җәйге "
        u8"вакытыСейшел утраулары вакытыСингапур стандарт вакытыСоломон утраулары вакытыКөньяк Джорджия вакытыС"
        u8"уринам вакытыСёва вакытыТаити вакытыТайпей вакытыТайпей стандарт вакытыТайпей җәйге вакытыТаҗикстан "
        u8"вакытыТокелау вакытыТонга вакытыТонга стандарт вакытыТонга җәйге вакытыЧуук вакытыТөркмәнстан вакыты"
        u8"Төркмәнстан стандарт вакытыТөркмәнстан җәйге вакытыТувалу вакытыУругвай вакытыУругвай стандарт вакыт"
        u8"ыУругвай җәйге вакытыҮзбәкстан вакытыҮзбәкстан стандарт вакытыҮзбәкстан җәйге вакытыВануату вакытыВа"
        u8"нуату стандарт вакытыВануату җәйге вакытыВенесуэла вакытыВладивосток вакытыВладивосток стандарт вакы"
        u8"тыВладивосток җәйге вакытыВолгоград вакытыВолгоград стандарт вакытыВолгоград җәйге вакытыВосток вакы"
        u8"тыУэйк утравы вакытыУоллис һәм Футуна вакытыЯкутск вакытыЯкутск стандарт вакытыЯкутск җәйге вакытыЕк"
        u8"атеринбург вакытыЕкатеринбург стандарт вакытыЕкатеринбург җәйге вакытыЮкон вакыты{0} ({1}){0}, {1}{0"
        u8"} вакыты{0} гадәти вакыты{0} җәйге вакыты{1} ({0}){0} {1}";
    inline constexpr const char8_t* NameChunks[] = {NameChunk0};
    inline constexpr uint16_t NameChunkSizes[] = {36758};
    inline constexpr char NameRefsChunk0[] =
        "AAAAAAAAAAASAAAcAAAmAABQAABcAABmAAB6AACIAACQAACeAACoAAC0AADCAADMAADYAADkAADyAAEAAAEIAAEUAAElAAEzAAE5"
        "AAFDAAFNAAFXAAGBAAGUAAGiAAGzAAG7AAHHAAHsAAIPAAIhAAIrAAJVAAJuAAJ4AAKAAAKKAAKSAAKYAAKoAAKyAALAAALMAALj"
        "AALxAAL/AAMPAAMZAAMlAAMtAAM1AANJAANVAANoAAN9AAOHAAORAAOdAAOpAAO7AAPDAAPPAAPdAAPvAAP3AAQDAAQPAAQZAAQn"
        "AAQxAAQ/AARLAARVAARjAARrAAR3AASBAASVAASdAASnAASxAAS7AATLAATVAATjAATzAAT/AAUPAAUbAAUpAAUzAAU/AAVJAAVV"
        "AAVdAAVrAAV9AAWJAAWXAAWhAAWpAAW3AAXLAAXVAAXfAAXvAAYOAAYYAAYgAAYyAAY8AAZCAAZOAAZeAAZmAAZ0AAaAAAaVAAah"
        "AAatAAa5AAbOAAbfAAbyAAcHAAcTAAcdAAclAActAAc3AAdBAAdNAAdXAAddAAdtAAd9AAeHAAeRAAebAAe/AAfJAAfVAAfsAAf0"
        "AAf+AAgIAAgWAAggAAgoAAg0AAg+AAhnAAiEAAiOAAiaAAi1AAjQAAjeAAj7AAkSAAkvAAlIAAldAAl+AAmMAAmvAAnKAAnjAAn4"
        "AAoeAAo3AApNAApfAAqAAAqSAAqaAAqrAArEAArQAArtAAsGAAsjAAtTAAtsAAuNAAubAAvPAAvhAAwFAAwTAAwhAAwzAAw/AAxT"
        "AAxlAAyCAAyQAAyiAAysAAzJAAzdAA0HAA0XAA0pAA03AA1OAA1eAA1sAA16AA2EAA2dAA28AA3IAA3WAA37AA4LAA4oAA4yAA5H"
        "AA5XAA5nAA5xAA59AA6pAA68AA7qAA8LAA8dAA8zAA9MAA9UAA9iAA9sAA98AA+dAA+wAA+4AA/LAA/ZAA/yAA/6ABAdABAtABBE"
        "ABBQABBaABBqABCXABChABDBABDPABDdABDnABEEABESABEgABEuABFJABFZABFrABF1ABGYABGsABHJABHXABHhABIGABIUABIg"
        "ABI/ABJLABJTABJlABJ5ABKFABKRABKjABLGABLSABMjABM1ABM9ABNUABNgABOXABPbABPrABP7ABQFABQTABQwABRCABRSABRg"
        "ABRzABR9ABTMABTYABTgABTwABT8ABUIABUUABUkABUwABU6ABVOABVeABVuABWLABWuABXFABXcABXoABYHABYZABYhABYrABY+"
        "ABZUABZlABZzABZ/ABaJABadABapABazABbBABbNABbbABbvABcEABcYABc5ABdYABdgABd5ABeJABe8ABfqABf8ABgQABgkABgw"
        "ABhAABhhABhtABh7ABiLABibABipABjCABjMABjnABj1ABkHABkZABkpABkzABk9ABlFABlcABlkABlwABl4ABmdABm9ABnNABnd"
        "ABnpABoOABovABpEABpxABqFABqPABqfABqpABrAABrOABrcABroABr0ABsAABsfABtCABthABtrABt3ABuHABunABu3ABviABvy"
        "ABwJABwcABwqABw2ABxEABxbAByCAByUABypAByzABzFABzjAB0UAB0aAB1YAB1gAB1uAB2AAB2OAB2jAB25AB3DAB3NAB3ZAB39"
        "AB4JAB4XAB4nAB41AB5BAB5yAB6XAB6dAB6rAB69AB7LAB76AB8MAB88AB9iAB9wAB9+AB+eAB+oAB/GAB/bAB/nAB/xAB//ACAY"
        "ACAkACA0ACBPACBbACB5ACCLACCXACCuACDxACE6ACFRACFuACGFACGcACG1ACHUACHxACISACIxACJUACJ1ACKcACK3ACLSACLz"
        "ACMaACOFACP0ACQTACQ4ACRXACR6ACSPACSkACS/ACTgACT7ACUcACU3ACVYACVzACWUACW5ACXiACX9ACYWACY1ACZSACZ1ACaS"
        "ACazACbKACbnACcAACcfACc6ACdbACd4ACebACe6ACffACf0ACgNACggACgoAChFAChmACiGACisACjBACjaACj+ACkmACk7AClU"
        "ACltACmMACmlACm+ACnfACoEACobACo4ACpNACpoACqFACqmACq9ACraACriACr7ACsaACtIACt8ACuVACusACvJACvcACv1ACwS"
        "ACw1ACxQACxxACyKACypACzKACzzAC0OAC0vAC1MAC1vAC2OAC2zAC3IAC3jAC4AAC4jAC5EAC5pAC6LAC61AC7OAC7jAC7+AC8R"
        "AC8qAC9JAC9oAC+DAC+kAC/BAC/kAC/5ADABADAcADA9ADBaADB9ADCYADC5ADDjADETADE3ADFbADF/ADGjADG8ADHbADIJADI9"
        "ADJeADKDADKUADKrADLAADLbADL7ADMfADM8ADNfADN4ADOXADOuADPLADPoADQLADQiADQ5ADRcADSDADSiADTHADTeADT7ADUa"
        "ADU/ADVWADVzADWQADWxADXMADXvADYMADYtADZIADZpADaEADajADbEADbrADcMADczADdQADdzADeQADexADfWADf/ADgeADg9"
        "ADhWADhzADiZADjFADjYADjxADkQADkzADlEADlbADmGADmxADnOADnvADoOADoxADpKADprADqOADq1ADrKADrlADr6ADsPADso"
        "ADtHADtcADtiADt7ADuaADvEADv0ADwkADxaADyIADy6ADzPADzqAD0FAD0gAD0/AD1kAD2PAD3AAD3gAD4IAD4lAD5IAD5lAD6I"
        "AD6qAD7SAD8IAD9BAD9WAD9xAD+UAD+7AD/SAD/pAEAMAEAzAEBWAEB5AECQAECtAEDIAEDjAED8AEEVAEFIAEGBAEGlAEHPAEHw"
        "AEIXAEI2AEJZAEJ2AEKZAEKuAELJAELoAEMDAEMeAENBAENqAEODAEOcAEOzAEPQAEPnAEP+AEQnAERWAESAAESwAEThAEUYAEVs"
        "AEXGAEXjAEYCAEYXAEYyAEZWAEZ6AEaVAEa0AEbwAEbzAEcOAEcYAEciAEcwAEc6AEdGAEdSAEdeAEdqAEd2AEd+AEeKAEeUAEeg"
        "AEeqAEfGAEfWAEftAEf7AEgKAEgWAEglAEg0AEhGAEhSAEhcAEhqAEh4AEiPAEigAEioAEiwAEi4AEjEAEjUAEjpAEj5AEkFAEkV"
        "AEkhAEkvAEk/AElOAElgAEloAEl2AEmAAEmQAEmgAEmqAEm4AEnKAEndAEn6AEoFAEoZAEopAEo8AEpRAEpiAEpuAEp4AEqIAEqf"
        "AEqpAEq7AErMAErUAErmAEryAEr+AEsMAEsYAEsmAEs2AEtAAEtMAEtcAEtoAEt4AEuPAEukAEuyAEvCAEvZAEvlAEv1AEwDAEwa"
        "AEwqAEw4AExGAExUAExkAEx5AEyKAEyfAEyyAEy8AEzKAEzcAEzmAEz6AE0EAE0QAE0iAE05AE1QAE1gAE1qAE12AE2CAE2OAE2a"
        "AE2mAE20AE3GAE3QAE3gAE3sAE36AE4OAE4nAE5MAE5cAE5oAE50AE6BAE6NAE6XAE6jAE64AE7KAE7WAE7eAE7qAE72AE8AAE8S"
        "AE8eAE9GAE9UAE9iAE9sAE90AE98AE+cAE+0AE/AAE/OAE/aAE/iAE//AFALAFAZAFAxAFA9AFBTAFBjAFBxAFCDAFCTAFChAFCt"
        "AFDbAFDtAFD/AFEJAFEVAFEhAFEzAFE5AFFDAFFNAFFbAFFnAFF3AFGLAFGXAFGjAFG0AFHCAFHKAFHWAFHgAFHoAFH0AFIAAFIQ"
        "AFIiAFIxAFJBAFJNAFJgAFJqAFJ4AFKIAFKUAFKiAFKqAFK4AFLMAFLaAFLsAFL4AFMQAFMkAFMyAFM+AFNKAFNUAFNcAFNvAFN5"
        "AFOFAFOTAFOlAFO1AFPDAFPVAFPuAFP+AFQOAFQsAFQ6AFRMAFRYAFRqAFR2AFSCAFSZAFSlAFSxAFS/AFTJAFTVAFTjAFTtAFT7"
        "AFUNAFUVAFUlAFUvAFU7AFVHAFVPAFVZAFV4AFWEAFWZAFWrAFW3AFXDAFXRAFXfAFXtAFX1AFYBAFYcAFYqAFY6AFZKAFZaAFZo"
        "AFZ+AFaKAFacAFaqAFa6AFbMAFbWAFbiAFb6AFcCAFcYAFcmAFcwAFdGAFdaAFdoAFdwAFd8AFeSAFegAFeuAFe/AFfNAFfnAFf3"
        "AFgFAFgRAFgeAFg0AFg6AFhGAFhYAFhrAFh5AFiPAFijAFixAFi7AFjLAFjfAFjnAFj2AFkgAFkuAFk8AFlPAFlbAFlrAFlzAFmB"
        "AFmPAFmdAFmlAFmzAFnFAFnVAFntAFn9AFoJAFofAFonAFo9AFpLAFpXAFpfAFpnAFpvAFp/AFqLAFqVAFqfAFqzAFrKAFrUAFrg"
        "AFrsAFsRAFs9AFtgAFtsAFt8AFueAFvAAFvjAFv7AFwZAFw3AFxPAFxfAFx5AFyfAFytAFy8AFzQAFziAFzwAF0HAF0VAF0jAF02"
        "AF1GAF1QAF1cAF1kAF1sAF2EAF2QAF2cAF2vAF3TAF3xAF4QAF4yAF5cAF6CAF6sAF7nAF8cAF81AF9fAF+DAF+gAF/OAF/2AGAn"
        "AGBlAGChAGDaAGEgAGFkAGGTAGHPAGIJAGJDAGKKAGLPAGLqAGMWAGM8AGNRAGN3AGOXAGOuAGPWAGP4AGQXAGRHAGRxAGShAGTi"
        "AGUdAGU4AGVkAGWKAGXDAGYJAGZNAGZ1AGauAGbhAGcaAGdkAGeoAGfYAGgZAGhUAGiEAGjFAGkAAGkhAGlTAGl/AGmnAGngAGoT"
        "AGoyAGpiAGqMAGqjAGq+AGrbAGsJAGsxAGtfAGt/AGuwAGvbAGwHAGweAGxGAGxoAGx9AGyjAGzDAGzaAG0CAG0kAG1KAG10AG2R"
        "AG2/AG3nAG4NAG5EAG6CAG6XAG69AG7dAG70AG8dAG9FAG9pAG+eAG/NAG/oAHAKAHA5AHBmAHCQAHDHAHD8AHEvAHFZAHGQAHHF"
        "AHH1AHI2AHJxAHKIAHKwAHLSAHL6AHM+AHNwAHOJAHOiAHPMAHPwAHQeAHRGAHR4AHS7AHT4AHUqAHVtAHWqAHXnAHYAAHYiAHZV"
        "AHaCAHadAHbJAHbvAHcEAHcqAHdKAHdwAHeSAHeyAHfaAHgKAHg6AHhPAHh1AHiVAHiwAHjcAHkCAHkbAHlFAHlpAHl+AHmkAHnE"
        "AHoAAHpNAHqUAHqzAHrjAHsTAHsqAHtSAHt0AHuNAHuuAHvgAHwMAHwtAHxVAHxxAHyeAHzFAHzgAH0MAH0yAH1PAH19AH2pAH3X"
        "AH30AH4iAH5KAH5jAH6UAH7VAH8RAH8xAH9iAH+NAH+mAH/QAH/0AIANAIAkAIA7AIBhAICYAIDJAIDtAIEiAIFRAIF2AIGsAIHc"
        "AIHxAIIZAIJSAIKFAIK2AIL4AIM0AINXAIOLAIO5AIPOAIP0AIQUAIQxAIRfAISHAISeAITJAITmAIUUAIU8AIVRAIV3AIWXAIW0"
        "AIXiAIYKAIY2AIZoAIarAIboAIcDAIccAIc3AIdSAIdrAIeGAIeyAIfYAIfxAIgbAIg/AIhWAIh+AIigAIjMAIj6AIkoAIlSAIlt"
        "AImCAImZAImyAIncAIoAAIofAIo6AIpRAIp5AIqbAIqwAIrTAIsHAIs1AItOAItpAIuVAIu7AIvaAIwKAIw0AIxPAIx7AIyhAIzA"
        "AIzjAI0XAI1FAI1kAI2UAI2+AI3XAI35AI4mAI4/AI5pAI6NAI6yAI7oAI8YAI8tAI82AI8+AI9OAI9rAI+GAI+PAI+W";
    inline constexpr const char* NameRefsChunks[] = {NameRefsChunk0};
    inline constexpr Packed NameRefs{NameRefsChunks, 13, 4};
    inline constexpr Text NameTexts{NameChunks, NameChunkSizes, NameRefs};

    inline constexpr char LanguageKeysChunk0[] =
        "AAmAAtAAyAAzAA6ABBABFABHABOABPABSABTABhABvABzAB5ACBACFACWACaACsACuACvACzAC0AC1ADBADGADJADPADSADhADkA"
        "DsADuAD1AEBAEFAEJAESAEUAEVAEZAEaAEkAEnAEzAE0AE1AFBAFhAFrAFtAFuAFvAFyAFzAF1AF5AGBAGCAGPAGUAGWAGnAGpAG"
        "rAGsAGuAGyAGzAG0AG5AHFAHMAHZAHjAHtAHyAIBAIMAITAIUAI1AJNAJPAJVAJXAJhAJkAJlAJpAJrAJsAJvAJxAJyAJ2AKBAKF"
        "AKHAKIAKJAKLAKPAKSAKUAKnAKrAKyAK6ALFALJALvAMpAMvANIAZOAguAitAyiA0NA0SA1iBJiBksCA3CEsCJiCRCC3rC5VDSuD"
        "XJDXoDk1EAwEajEwoEw0E2hE2qE2uE2zE8yFNNFXE";
    inline constexpr const char* LanguageKeysChunks[] = {LanguageKeysChunk0};
    inline constexpr Packed LanguageKeys{LanguageKeysChunks, 13, 3};

    inline constexpr char LanguageNamesChunk0[] =
        "AABAACAADAAGAAHAAIAAKAAMAANAAOAAPAAQAARAAWAAXAAYAAZAAaAAdAAeAAfAAgAAjAAkAAnAAoAApAAqAArAAtAAuAAvAAwA"
        "AxAAyAAzAA0AA2AA3AA5AA7AA8AA9AA+ABAABBABCABDABEABFABGABHABIABJABKABMABOABPABQABRABSABTABUABVABXABYAB"
        "ZABaABbABeABfABgABhABiABkABmABnABoABpABqABsABtABuABwAByABzAB0AB1AB2AB5AB6AB7AB8AB9ACCACDACEACFACHACI"
        "ACJACKACLACMACNACOACPACRACSACUACVACWACXACYACZACaACbAAFAAJAALAASAATAAUAAVAAcAAsAA1AA4AA6AA/ABLABNABWA"
        "BcABdABjABrABxAB3AB4AB+AB/ACAACBACGACQACT";
    inline constexpr const char* LanguageNamesChunks[] = {LanguageNamesChunk0};
    inline constexpr Packed LanguageNames{LanguageNamesChunks, 13, 3};

    inline constexpr const uint64_t* TaggedKeys = nullptr;

    inline constexpr const uint16_t* TaggedNames = nullptr;

    inline constexpr char RegionKeysChunk0[] =
        "AAeAAfAAgAAhAAiAAkAAnAAoAAqAAsAAtAAuAAvAAwAAyAAzAA1AA3AA4AA6AA7AA8AA9AA+AA/ABAABCABDABEABFABHABIABJA"
        "BKABMABNABPABQABSABUABVABXABYABZABaABcABdABeABfABgABhABjABmABnABoABpABqABrABxABzAB2AB3AB5AB7ACGACIAC"
        "KACMACOACPACZACaACbACcAChACrACsACtACvACxAC0AC+AC/ADBADCADDADEADFADGADJADKADLADNADOADPADQADRADSADUADW"
        "ADjADlADmADqADsADtAD2AD3AD4AD/AEAAEBAECAEEAEFAEGAEHAETAEbAEdAEeAEuAEwAExAEyAE2AE3AE5AE7AFAAFCAFDAFFA"
        "FGAFHAFNAFPAFWAFXAFYAFZAFaAFdAFgAFiAFjAFkAFlAFmAFnAFqAFrAFsAFtAFuAFvAFwAFxAFyAFzAF0AF1AF2AF3AF4AF5AF"
        "7AF9AF/AGAAGBAGDAGGAGJAGKAGMAGPAGUAGiAGxAG1AG2AG3AG4AG7AG8AG9AG+AHCAHDAHEAHHAHJAHMAHaAHrAH1AH5AH7AH9"
        "AICAIDAIEAIFAIGAIIAIJAIKAILAIMAINAIOAIPAIQAITAIUAIVAIXAIZAIaAIbAIdAIfAIgAIiAIjAIkAImAInAIoAIpAIqAIrA"
        "IuAIwAIyAIzAI2AI4AI+AJEAJFAJKAJQAJRAJTAJVAJXAJZAJbAJgAJnAJzAKAAKJAKKAKTAKoAK3AK/ALLALVALYALaALbALcAL"
        "eALiALkALmALnALoALqALrALsALuAL2AL3AL7AL8AMAAMOAMPAMSAMWANnANoANqANvANwANzAN0AOjAR8";
    inline constexpr const char* RegionKeysChunks[] = {RegionKeysChunk0};
    inline constexpr Packed RegionKeys{RegionKeysChunks, 13, 3};

    inline constexpr char RegionNamesChunk0[] =
        "AC9AC+AC/ADAADBADCADDADEADFADGADHADIADJADKADLADMADNADOADPADQADRADSADTADUADVADWADXADYADZADaADbADcADdA"
        "DeADfADgADhADiADjADkADlADmADnADoADpADqADrADsADtADuADvADwADxADyADzAD0AD1AD2AD3AD4AD5AD6AD7AD8AD9AD+AD"
        "/AEAAEBAECAEDAEEAEFAEGAEHAEIAEJAEKAELAEMAENAEOAEPAEQAERAESAETAEUAEVAEWAEXAEYAEZAEaAEbAEcAEdAEeAEfAEg"
        "AEhAEiAEjAEkAElAEmAEnAEoAEpAEqAErAEsAEtAEuAEvAEwAExAEyAEzAE0AE1AE2AE3AE4AE5AE6AE7AE8AE9AE+AE/AFAAFBA"
        "FCAFDAFEAFFAFGAFHAFIAFJAFKAFLAFMAFNAFOAFPAFQAFRAFSAFTAFUAFVAFWAFXAFYAFZAFaAFbAFcAFdAFeAFfAFgAFhAFiAF"
        "jAFkAFlAFmAFnAFoAFpAFqAFrAFsAFtAFuAFvAFwAFxAFyAFzAF0AF1AF2AF3AF4AF5AF6AF7AF8AF9AF+AF/AGAAGBAGCAGDAGE"
        "AGFAGGAGHAGIAGJAGKAGLAGMAGNAGOAGPAGQAGRAGSAGTAGUAGVAGWAGXAGYAGZAGaAGbAGcAGdAGeAGfAGgAGhAGiAGjAGkAGlA"
        "GmAGnAGoAGpAGqAGrAGsAGtAGuAGvAGwAGxAGyAGzAG0AG1AG2AG3AG4AG5AG6AG7AG8AG9AG+AG/AHAAHBAHCAHDACeACfACgAC"
        "hACiACjACkAClACmACnACoACpACqACrACsACtACuACvACwACxACyACzAC0AC1AC2AC3AC4AC5AC6AC7AC8";
    inline constexpr const char* RegionNamesChunks[] = {RegionNamesChunk0};
    inline constexpr Packed RegionNames{RegionNamesChunks, 13, 3};

    inline constexpr char ScriptKeysChunk0[] =
        "AMgiAeZMBAXTBAXUBUAuBb5FBgaODWMYDWta";
    inline constexpr const char* ScriptKeysChunks[] = {ScriptKeysChunk0};
    inline constexpr Packed ScriptKeys{ScriptKeysChunks, 13, 4};

    inline constexpr char ScriptNamesChunk0[] =
        "AADAHEAHFAHGABFABKABRAHHAHI";
    inline constexpr const char* ScriptNamesChunks[] = {ScriptNamesChunk0};
    inline constexpr Packed ScriptNames{ScriptNamesChunks, 13, 3};

    inline constexpr char AloneKeysChunk0[] =
        "BAXTBAXU";
    inline constexpr const char* AloneKeysChunks[] = {AloneKeysChunk0};
    inline constexpr Packed AloneKeys{AloneKeysChunks, 13, 4};

    inline constexpr char AloneNamesChunk0[] =
        "ACcACd";
    inline constexpr const char* AloneNamesChunks[] = {AloneNamesChunk0};
    inline constexpr Packed AloneNames{AloneNamesChunks, 13, 3};

    inline constexpr char CurrencyKeysChunk0[] =
        "ASkATOAWMAWkAXhAZTAakAbnAdOAgtAhEAiUAjuAkEAkmAmkAnEAniApMApkAqOArwAsuAtEAwkAyGA0GA2QA3ZA3wA5DA6wA7FA"
        "9LBFGBFrBHwBNEBTwBZOBaCBayBlEBlwBxQBysB0TB0wB2kB3GB6RB8kCFkCHMCKHCKmCSSCWTCXSCYkCZSCZrCmkCnkCoZCyzCz"
        "zC0SC2mC4XC5XC7kC8kC9UDArDBQDFyDJEDJsDMkDQkDSMDThDVkDWrDXUDXwDZVDayDbSDbrDcODcyDdODgkDjuDkvDnrDoSDtE"
        "D2yEAiECuEDrEEQEFyEGOEMnEQyEnuEpkEqiErmEwyExEExyEyHEyrEzkE0QE2FE3zE5EE5wE6OE8wE9MFECFFTFG0FHEFHwFJZF"
        "KEFLkFNTFQoFT4FZkFc1FdTFizFnEFq2F50GAmGBkGHmGIGGMYGSyGgyGm3";
    inline constexpr const char* CurrencyKeysChunks[] = {CurrencyKeysChunk0};
    inline constexpr Packed CurrencyKeys{CurrencyKeysChunks, 13, 3};

    inline constexpr char CurrencyNamesChunk0[] =
        "AHJAAAAAAAAAAAAAAAAHKAHLAAAAAAAAAAAAAAAAHMAHNAAAAAAAAAAAAAAAAHOAHPAAAAAAAAAAAAAAAAHQAHRAAAAAAAAAAAAA"
        "AAAHSAHTAAAAAAAAAAAAAAAAHUAHVAAAAAAAAAAAAAAAAHWAHXAAAAAAAAAAAAAAAAHYAHZAAAAAAAAAAAAAAAAHaAHbAAAAAAAA"
        "AAAAAAAAHcAHdAAAAAAAAAAAAAAAAHeAHfAAAAAAAAAAAAAAAAHgAHhAAAAAAAAAAAAAAAAHiAHjAAAAAAAAAAAAAAAAHkAHlAAA"
        "AAAAAAAAAAAAAHmAHnAAAAAAAAAAAAAAAAHoAHpAAAAAAAAAAAAAAAAHqAHrAAAAAAAAAAAAAAAAHsAHtAAAAAAAAAAAAAAAAAAA"
        "HuAAAAAAAAAAAAAAAAHvAHwAAAAAAAAAAAAAAAAHxAHyAAAAAAAAAAAAAAAAHzAH0AAAAAAAAAAAAAAAAH1AH2AAAAAAAAAAAAAA"
        "AAH3AH4AAAAAAAAAAAAAAAAH5AH6AAAAAAAAAAAAAAAAH7AH8AAAAAAAAAAAAAAAAH9AH+AAAAAAAAAAAAAAAAH/AIAAAAAAAAAA"
        "AAAAAAAIBAICAAAAAAAAAAAAAAAAIDAIEAAAAAAAAAAAAAAAAIFAIGAAAAAAAAAAAAAAAAIHAIIAAAAAAAAAAAAAAAAIJAIKAAAA"
        "AAAAAAAAAAAAILAIMAAAAAAAAAAAAAAAAINAIOAAAAAAAAAAAAAAAAIPAIQAAAAAAAAAAAAAAAAIRAISAAAAAAAAAAAAAAAAITAI"
        "UAAAAAAAAAAAAAAAAIVAIWAAAAAAAAAAAAAAAAIXAIYAAAAAAAAAAAAAAAAIZAIaAAAAAAAAAAAAAAAAAAAIbAAAAAAAAAAAAAAA"
        "AIcAIdAAAAAAAAAAAAAAAAIeAIfAAAAAAAAAAAAAAAAAAAIgAAAAAAAAAAAAAAAAIhAIiAAAAAAAAAAAAAAAAIjAIkAAAAAAAAAA"
        "AAAAAAIlAImAAAAAAAAAAAAAAAAInAIoAAAAAAAAAAAAAAAAIpAIqAAAAAAAAAAAAAAAAIrAIsAAAAAAAAAAAAAAAAItAIuAAAAA"
        "AAAAAAAAAAAIvAIwAAAAAAAAAAAAAAAAIxAIyAAAAAAAAAAAAAAAAIzAI0AAAAAAAAAAAAAAAAI1AI2AAAAAAAAAAAAAAAAI3AI4"
        "AAAAAAAAAAAAAAAAI5AI6AAAAAAAAAAAAAAAAAAAI7AAAAAAAAAAAAAAAAI8AI9AAAAAAAAAAAAAAAAI+AI/AAAAAAAAAAAAAAAA"
        "JAAJBAAAAAAAAAAAAAAAAJCAJDAAAAAAAAAAAAAAAAJEAJFAAAAAAAAAAAAAAAAJGAJHAAAAAAAAAAAAAAAAJIAJJAAAAAAAAAAA"
        "AAAAAJKAJLAAAAAAAAAAAAAAAAJMAJNAAAAAAAAAAAAAAAAJOAJPAAAAAAAAAAAAAAAAJQAJRAAAAAAAAAAAAAAAAJSAJTAAAAAA"
        "AAAAAAAAAAJUAJVAAAAAAAAAAAAAAAAJWAJXAAAAAAAAAAAAAAAAJYAJZAAAAAAAAAAAAAAAAJaAJbAAAAAAAAAAAAAAAAJcAJdA"
        "AAAAAAAAAAAAAAAJeAJfAAAAAAAAAAAAAAAAJgAJhAAAAAAAAAAAAAAAAJiAJjAAAAAAAAAAAAAAAAJkAJlAAAAAAAAAAAAAAAAJ"
        "mAJnAAAAAAAAAAAAAAAAJoAJpAAAAAAAAAAAAAAAAJqAJrAAAAAAAAAAAAAAAAJsAJtAAAAAAAAAAAAAAAAJuAJvAAAAAAAAAAAA"
        "AAAAJwAJxAAAAAAAAAAAAAAAAJyAJzAAAAAAAAAAAAAAAAJ0AJ1AAAAAAAAAAAAAAAAJ2AJ3AAAAAAAAAAAAAAAAJ4AJ5AAAAAAA"
        "AAAAAAAAAJ6AJ7AAAAAAAAAAAAAAAAJ8AJ9AAAAAAAAAAAAAAAAJ+AJ/AAAAAAAAAAAAAAAAKAAKBAAAAAAAAAAAAAAAAKCAKDAA"
        "AAAAAAAAAAAAAAKEAKFAAAAAAAAAAAAAAAAKGAKHAAAAAAAAAAAAAAAAKIAKJAAAAAAAAAAAAAAAAKKAKLAAAAAAAAAAAAAAAAKM"
        "AKNAAAAAAAAAAAAAAAAKOAKPAAAAAAAAAAAAAAAAKQAKRAAAAAAAAAAAAAAAAKSAKTAAAAAAAAAAAAAAAAKUAKVAAAAAAAAAAAAA"
        "AAAKWAKXAAAAAAAAAAAAAAAAKYAKZAAAAAAAAAAAAAAAAKaAKbAAAAAAAAAAAAAAAAKcAKdAAAAAAAAAAAAAAAAKeAKfAAAAAAAA"
        "AAAAAAAAKgAKhAAAAAAAAAAAAAAAAKiAKjAAAAAAAAAAAAAAAAKkAKlAAAAAAAAAAAAAAAAKmAKnAAAAAAAAAAAAAAAAKoAKpAAA"
        "AAAAAAAAAAAAAKqAKrAAAAAAAAAAAAAAAAKsAKtAAAAAAAAAAAAAAAAKuAKvAAAAAAAAAAAAAAAAKwAKxAAAAAAAAAAAAAAAAKyA"
        "KzAAAAAAAAAAAAAAAAK0AK1AAAAAAAAAAAAAAAAK2AK3AAAAAAAAAAAAAAAAK4AK5AAAAAAAAAAAAAAAAK6AK7AAAAAAAAAAAAAA"
        "AAK8AK9AAAAAAAAAAAAAAAAK+AK/AAAAAAAAAAAAAAAALAALBAAAAAAAAAAAAAAAALCALDAAAAAAAAAAAAAAAALEALFAAAAAAAAA"
        "AAAAAAALGALHAAAAAAAAAAAAAAAALIALJAAAAAAAAAAAAAAAALKALLAAAAAAAAAAAAAAAALMALNAAAAAAAAAAAAAAAALOALPAAAA"
        "AAAAAAAAAAAALQALRAAAAAAAAAAAAAAAALSALTAAAAAAAAAAAAAAAALUALVAAAAAAAAAAAAAAAALWALXAAAAAAAAAAAAAAAALYAL"
        "ZAAAAAAAAAAAAAAAAAAALaAAAAAAAAAAAAAAAALbALcAAAAAAAAAAAAAAAALdALeAAAAAAAAAAAAAAAALfALgAAAAAAAAAAAAAAA"
        "ALhALiAAAAAAAAAAAAAAAALjALkAAAAAAAAAAAAAAAALlALmAAAAAAAAAAAAAAAALnALoAAAAAAAAAAAAAAAALpALqAAAAAAAAAA"
        "AAAAAALrALsAAAAAAAAAAAAAAAALtALuAAAAAAAAAAAAAAAALvALwAAAAAAAAAAAAAAAALxALyAAAAAAAAAAAAAAAALzAL0AAAAA"
        "AAAAAAAAAAAL1";
    inline constexpr const char* CurrencyNamesChunks[] = {CurrencyNamesChunk0};
    inline constexpr Packed CurrencyNames{CurrencyNamesChunks, 13, 3};

    inline constexpr char ZoneKeysChunk0[] =
        "AAAAABAACAADAAEAAFAAGAAHAAIAAJAAKAALAAMAANAAOAAPAAQAARAASAATAAUAAVAAWAAXAAYAAZAAaAAbAAcAAdAAeAAfAAgA"
        "AhAAiAAjAAkAAlAAmAAnAAoAApAAqAArAAsAAtAAuAAvAAwAAxAAyAAzAA0AA1AA2AA3AA4AA5AA6AA7AA8AA9AA+AA/ABAABBAB"
        "CABDABEABFABGABHABIABJABKABLABMABNABOABPABQABRABSABTABUABVABWABXABYABZABaABbABcABdABeABfABgABhABiABj"
        "ABkABlABmABnABoABpABqABrABsABtABuABvABwABxAByABzAB0AB1AB2AB3AB4AB5AB6AB7AB8AB9AB+AB/ACAACBACCACDACEA"
        "CFACGACHACIACJACKACLACMACNACOACPACQACRACSACTACUACVACWACXACYACZACaACbACcACdACeACfACgAChACiACjACkAClAC"
        "mACnACoACpACqACrACsACtACuACvACwACxACyACzAC0AC1AC2AC3AC4AC6AC7AC8AC9AC+AC/ADAADBADCADDADEADFADGADHADI"
        "ADJADKADLADMADNADOADPADQADRADSADTADUADVADWADXADYADZADaADbADcADdADeADfADgADhADiADjADkADlADmADnADoADpA"
        "DqADrADsADtADuADvADwADxADyADzAD0AD1AD2AD3AD4AD5AD6AD7AD8AD9AD+AD/AEAAEBAECAEDAEEAEFAEGAEHAEIAEJAEKAE"
        "LAEMAENAEOAEPAEQAERAESAETAEUAEVAEWAEXAEYAEZAEaAEbAEcAEdAEeAEfAEgAEhAEiAEjAEkAElAEmAEnAEoAEpAEqAErAEs"
        "AEtAEuAEvAEwAExAEyAEzAE0AE1AFRAFSAFTAFUAFVAFWAFXAFYAFZAFaAFbAFcAFdAFeAFfAFgAFhAFiAFjAFkAFlAFmAFnAFoA"
        "FpAFqAFrAFsAFtAFuAFvAFwAFxAFyAFzAF0AF1AF2AF3AF4AF5AF6AF7AF8AF9AF+AF/AGAAGBAGCAGDAGEAGFAGGAGHAGIAGJAG"
        "KAGLAGMAGNAGOAGPAGQAGRAGSAGTAGUAGVAGWAGXAGYAGZAGaAGbAGcAGdAGfAGgAGhAGiAGjAGkAGlAGnAGoAGpAGqAGrAGsAGt"
        "AGuAGvAGwAGxAGyAGzAG0AG1AG2AG3AG4AG5AG6AG7AG8AG9";
    inline constexpr const char* ZoneKeysChunks[] = {ZoneKeysChunk0};
    inline constexpr Packed ZoneKeys{ZoneKeysChunks, 13, 3};

    inline constexpr char ZoneNamesChunk0[] =
        "ANgAAAAAAAAAAAAAAAAAAAOHAAAAAAAAAAAAAAAAAAAN7AAAAAAAAAAAAAAAAAAAD9AAAAAAAAAAAAAAAAAAAN4AAAAAAAAAAAAA"
        "AAAAAAPJAAAAAAAAAAAAAAAAAAANdAAAAAAAAAAAAAAAAAAAOMAAAAAAAAAAAAAAAAAAAORAAAAAAAAAAAAAAAAAAAPRAAAAAAAA"
        "AAAAAAAAAAANeAAAAAAAAAAAAAAAAAAAMrAAAAAAAAAAAAAAAAAAAN2AAAAAAAAAAAAAAAAAAAPBAAAAAAAAAAAAAAAAAAAN5AAA"
        "AAAAAAAAAAAAAAAAONAAAAAAAAAAAAAAAAAAAQlAAAAAAAAAAAAAAAAAAAQ7AAAAAAAAAAAAAAAAAAANwAAAAAAAAAAAAAAAAAAA"
        "NlAAAAAAAAAAAAAAAAAAAN3AAAAAAAAAAAAAAAAAAAQkAAAAAAAAAAAAAAAAAAANCAAAAAAAAAAAAAAAAAAARrAAAAAAAAAAAAAA"
        "AAAAARpAAAAAAAAAAAAAAAAAAAQoAAAAAAAAAAAAAAAAAAAQ+AAAAAAAAAAAAAAAAAAAQeAAAAAAAAAAAAAAAAAAAQaAAAAAAAAA"
        "AAAAAAAAAANbAAAAAAAAAAAAAAAAAAAPlAAAAAAAAAAAAAAAAAAAOCAAAAAAAAAAAAAAAAAAAQwAAAAAAAAAAAAAAAAAAAL+AAAA"
        "AAAAAAAAAAAAAAANcAAAAAAAAAAAAAAAAAAARqAAAAAAAAAAAAAAAAAAAOOAAAAAAAAAAAAAAAAAAAPgAAAAAAAAAAAAAAAAAAAO"
        "9AAAAAAAAAAAAAAAAAAAQsAAAAAAAAAAAAAAAAAAAQmAAAAAAAAAAAAAAAAAAAO8AAAAAAAAAAAAAAAAAAAOmAAAAAAAAAAAAAAA"
        "AAAAQuAAAAAAAAAAAAAAAAAAAPjAAAAAAAAAAAAAAAAAAAPPAAAAAAAAAAAAAAAAAAAMoAAAAAAAAAAAAAAAAAAAMsAAAAAAAAAA"
        "AAAAAAAAAQpAAAAAAAAAAAAAAAAAAAPAAAAAAAAAAAAAAAAAAAAGkAAAAAAAAAAAAAAAAAAAPhAAAAAAAAAAAAAAAAAAARBAAAAA"
        "AAAAAAAAAAAAAARDAAAAAAAAAAAAAAAAAAADCAAAAAAAAAAAAAAAAAAAL7AAAAAAAAAAAAAAAAAAAM5AAAAAAAAAAAAAAAAAAAMN"
        "AAAAAAAAAAAAAAAAAAAMJAAAAAAAAAAAAAAAAAAAMQAAAAAAAAAAAAAAAAAAAMLAAAAAAAAAAAAAAAAAAAMOAAAAAAAAAAAAAAAA"
        "AAAMSAAAAAAAAAAAAAAAAAAAMMAAAAAAAAAAAAAAAAAAADLAAAAAAAAAAAAAAAAAAAP9AAAAAAAAAAAAAAAAAAAM7AAAAAAAAAAA"
        "AAAAAAAAPXAAAAAAAAAAAAAAAAAAADPAAAAAAAAAAAAAAAAAAAM4AAAAAAAAAAAAAAAAAAADiAAAAAAAAAAAAAAAAAAANYAAAAAA"
        "AAAAAAAAAAAAAMzAAAAAAAAAAAAAAAAAAANoAAAAAAAAAAAAAAAAAAARJAAAAAAAAAAAAAAAAAAAMUAAAAAAAAAAAAAAAAAAANMA"
        "AAAAAAAAAAAAAAAAAAM3AAAAAAAAAAAAAAAAAAAPdAAAAAAAAAAAAAAAAAAARhAAAAAAAAAAAAAAAAAAAMPAAAAAAAAAAAAAAAAA"
        "AAOGAAAAAAAAAAAAAAAAAAAE/AAAAAAAAAAAAAAAAAAARPAAAAAAAAAAAAAAAAAAAPWAAAAAAAAAAAAAAAAAAAPUAAAAAAAAAAAA"
        "AAAAAAANRAAAAAAAAAAAAAAAAAAAMTAAAAAAAAAAAAAAAAAAADwAAAAAAAAAAAAAAAAAAANKAAAAAAAAAAAAAAAAAAAM1AAAAAAA"
        "AAAAAAAAAAAADzAAAAAAAAAAAAAAAAAAAOLAAAAAAAAAAAAAAAAAAANEAAAAAAAAAAAAAAAAAAANJAAAAAAAAAAAAAAAAAAARLAA"
        "AAAAAAAAAAAAAAAAARbAAAAAAAAAAAAAAAAAAAD7AAAAAAAAAAAAAAAAAAANLAAAAAAAAAAAAAAAAAAAMwAAAAAAAAAAAAAAAAAA"
        "AGWAAAAAAAAAAAAAAAAAAANIAAAAAAAAAAAAAAAAAAAM8AAAAAAAAAAAAAAAAAAANXAAAAAAAAAAAAAAAAAAAOJAAAAAAAAAAAAA"
        "AAAAAANWAAAAAAAAAAAAAAAAAAAQtAAAAAAAAAAAAAAAAAAAEQAAAAAAAAAAAAAAAAAAAEZAAAAAAAAAAAAAAAAAAAEdAAAAAAAA"
        "AAAAAAAAAAAN0AAAAAAAAAAAAAAAAAAAEgAAAAAAAAAAAAAAAAAAANVAAAAAAAAAAAAAAAAAAANpAAAAAAAAAAAAAAAAAAAPTAAA"
        "AAAAAAAAAAAAAAAARUAAAAAAAAAAAAAAAAAAARWAAAAAAAAAAAAAAAAAAARSAAAAAAAAAAAAAAAAAAARTAAAAAAAAAAAAAAAAAAA"
        "RZAAAAAAAAAAAAAAAAAAARRAAAAAAAAAAAAAAAAAAARVAAAAAAAAAAAAAAAAAAARXAAAAAAAAAAAAAAAAAAANGAAAAAAAAAAAAAA"
        "AAAAANTAAAAAAAAAAAAAAAAAAAEzAAAAAAAAAAAAAAAAAAAMRAAAAAAAAAAAAAAAAAAARGAAAAAAAAAAAAAAAAAAARaAAAAAAAAA"
        "AAAAAAAAAAMvAAAAAAAAAAAAAAAAAAAMuAAAAAAAAAAAAAAAAAAAPtAAAAAAAAAAAAAAAAAAARIAAAAAAAAAAAAAAAAAAARYAAAA"
        "AAAAAAAAAAAAAAAQqAAAAAAAAAAAAAAAAAAAM9AAAAAAAAAAAAAAAAAAAPmAAAAAAAAAAAAAAAAAAAM0AAAAAAAAAAAAAAAAAAAP"
        "EAAAAAAAAAAAAAAAAAAAFZAAAAAAAAAAAAAAAAAAAPbAAAAAAAAAAAAAAAAAAAPVAAAAAAAAAAAAAAAAAAAMKAAAAAAAAAAAAAAA"
        "AAAARQAAAAAAAAAAAAAAAAAAAPcAAAAAAAAAAAAAAAAAAARHAAAAAAAAAAAAAAAAAAAPaAAAAAAAAAAAAAAAAAAAP2AAAAAAAAAA"
        "AAAAAAAAANUAAAAAAAAAAAAAAAAAAAPZAAAAAAAAAAAAAAAAAAARdAAAAAAAAAAAAAAAAAAAPQAAAAAAAAAAAAAAAAAAANAAAAAA"
        "AAAAAAAAAAAAAARcAAAAAAAAAAAAAAAAAAARCAAAAAAAAAAAAAAAAAAAM/AAAAAAAAAAAAAAAAAAARMAAAAAAAAAAAAAAAAAAARO"
        "AAAAAAAAAAAAAAAAAAARNAAAAAAAAAAAAAAAAAAAPYAAAAAAAAAAAAAAAAAAAFwAAAAAAAAAAAAAAAAAAAQnAAAAAAAAAAAAAAAA"
        "AAARKAAAAAAAAAAAAAAAAAAAOVAAAAAAAAAAAAAAAAAAAQ4AAAAAAAAAAAAAAAAAAAMyAAAAAAAAAAAAAAAAAAAF5AAAAAAAAAAA"
        "AAAAAAAANjAAAAAAAAAAAAAAAAAAANQAAAAAAAAAAAAAAAAAAAM+AAAAAAAAAAAAAAAAAAANNAAAAAAAAAAAAAAAAAAANPAAAAAA"
        "AAAAAAAAAAAAAMxAAAAAAAAAAAAAAAAAAAM2AAAAAAAAAAAAAAAAAAANkAAAAAAAAAAAAAAAAAAANyAAAAAAAAAAAAAAAAAAAM6A"
        "AAAAAAAAAAAAAAAAAAOKAAAAAAAAAAAAAAAAAAARFAAAAAAAAAAAAAAAAAAAMtAAAAAAAAAAAAAAAAAAANZAAAAAAAAAAAAAAAAA"
        "AAOsAAAAAAAAAAAAAAAAAAAO5AAAAAAAAAAAAAAAAAAARjAAAAAAAAAAAAAAAAAAARgAAAAAAAAAAAAAAAAAAAOTAAAAAAAAAAAA"
        "AAAAAAAOIAAAAAAAAAAAAAAAAAAAPSAAAAAAAAAAAAAAAAAAANSAAAAAAAAAAAAAAAAAAARiAAAAAAAAAAAAAAAAAAANHAAAAAAA"
        "AAAAAAAAAAAANFAAAAAAAAAAAAAAAAAAANOAAAAAAAAAAAAAAAAAAAREAAAAAAAAAAAAAAAAAAAMGAAAAAAAAAAAAAAAAAAAMEAA"
        "AAAAAAAAAAAAAAAAAMHAAAAAAAAAAAAAAAAAAAMhAAAAAAAAAAAAAAAAAAAMDAAAAAAAAAAAAAAAAAAAMIAAAAAAAAAAAAAAAAAA"
        "AMAAAAAAAAAAAAAAAAAAAAL/AAAAAAAAAAAAAAAAAAAMCAAAAAAAAAAAAAAAAAAAMBAAAAAAAAAAAAAAAAAAAMFAAAAAAAAAAAAA"
        "AAAAAAQiAAAAAAAAAAAAAAAAAAARoAAAAAAAAAAAAAAAAAAAO2AAAAAAAAAAAAAAAAAAAOkAAAAAAAAAAAAAAAAAAAQZAAAAAAAA"
        "AAAAAAAAAAAOwAAAAAAAAAAAAAAAAAAAOzAAAAAAAAAAAAAAAAAAAQ1AAAAAAAAAAAAAAAAAAAOyAAAAAAAAAAAAAAAAAAAOgAAA"
        "AAAAAAAAAAAAAAAAMqAAAAAAAAAAAAAAAAAAAMkAAAAAAAAAAAAAAAAAAAQxAAAAAAAAAAAAAAAAAAAQLAAAAAAAAAAAAAAAAAAA"
        "O4AAAAAAAAAAAAAAAAAAAOnAAAAAAAAAAAAAAAAAAADZAAAAAAAAAAAAAAAAAAAOeAAAAAAAAAAAAAAAAAAAQQAAAAAAAAAAAAAA"
        "AAAAAO7AAAAAAAAAAAAAAAAAAAQrAAAAAAAAAAAAAAAAAAAMmAAAAAAAAAAAAAAAAAAAQ0AAAAAAAAAAAAAAAAAAAL5AAAAAAAAA"
        "AAAAAAAAAAQyAAAAAAAAAAAAAAAAAAANsAAAAAAAAAAAAAAAAAAAP4AAAAAAAAAAAAAAAAAAAP5AAAAAAAAAAAAAAAAAAAOSAAAA"
        "AAAAAAAAAAAAAAAPLAAAAAAAAAAAAAAAAAAAQPAAAAAAAAAAAAAAAAAAAOXAAAAAAAAAAAAAAAAAAAOaAAAAAAAAAAAAAAAAAAAO"
        "dAAAAAAAAAAAAAAAAAAAL6AAAAAAAAAAAAAAAAAAAQYAAAAAAAAAAAAAAAAAAAP0AAAAAAAAAAAAAAAAAAAPpAAAAAAAAAAAAAAA"
        "AAAAQTAAAAAAAAAAAAAAAAAAAQOAAAAAAAAAAAAAAAAAAAPeAAAAAAAAAAAAAAAAAAAPfAAAAAAAAAAAAAAAAAAAOvAAAAAAAAAA"
        "AAAAAAAAAPNAAAAAAAAAAAAAAAAAAAQWAAAAAAAAAAAAAAAAAAAOZAAAAAAAAAAAAAAAAAAAPzAAAAAAAAAAAAAAAAAAAPsAAAAA"
        "AAAAAAAAAAAAAANrAAAAAAAAAAAAAAAAAAAQNAAAAAAAAAAAAAAAAAAAQKAAAAAAAAAAAAAAAAAAAQJAAAAAAAAAAAAAAAAAAAOx"
        "AAAAAAAAAAAAAAAAAAAOoAAAAAAAAAAAAAAAAAAAOYAAAAAAAAAAAAAAAAAAAOtAAAAAAAAAAAAAAAAAAAF+AAAAAAAAAAAAAAAA"
        "AAAO0AAAAAAAAAAAAAAAAAAAO1AAAAAAAAAAAAAAAAAAAPKAAAAAAAAAAAAAAAAAAAQbAAAAAAAAAAAAAAAAAAARkAAAAAAAAAAA"
        "AAAAAAAAQUAAAAAAAAAAAAAAAAAAAReAAAAAAAAAAAAAAAAAAAOuAAAAAAAAAAAAAAAAAAANnAAAAAAAAAAAAAAAAAAAGKAAAAAA"
        "AAAAAAAAAAAAAQXAAAAAAAAAAAAAAAAAAAQ6AAAAAAAAAAAAAAAAAAARfAAAAAAAAAAAAAAAAAAAOFAAAAAAAAAAAAAAAAAAAOhA"
        "AAAAAAAAAAAAAAAAAANBAAAAAAAAAAAAAAAAAAAOlAAAAAAAAAAAAAAAAAAAQMAAAAAAAAAAAAAAAAAAAPMAAAAAAAAAAAAAAAAA"
        "AANmAAAAAAAAAAAAAAAAAAAQVAAAAAAAAAAAAAAAAAAAO3AAAAAAAAAAAAAAAAAAAQSAAAAAAAAAAAAAAAAAAAQRAAAAAAAAAAAA"
        "AAAAAAAQIAAAAAAAAAAAAAAAAAAAL9AAAAAAAAAAAAAAAAAAAP6AAAAAAAAAAAAAAAAAAADYAAAAAAAAAAAAAAAAAAAEnAAAAAAA"
        "AAAAAAAAAAAADyAAAAAAAAAAAAAAAAAAAEMAAAAAAAAAAAAAAAAAAAP7AAAAAAAAAAAAAAAAAAAOiAAAAAAAAAAAAAAAAAAAOQAA"
        "AAAAAAAAAAAAAAAAAQgAAAAAAAAAAAAAAAAAAAN9AAAAAAAAAAAAAAAAAAAMaAAAAAAAAAAAAAAAAAAAMgAAAAAAAAAAAAAAAAAA"
        "AMbAAAAAAAAAAAAAAAAAAAMZAAAAAAAAAAAAAAAAAAAMYAAAAAAAAAAAAAAAAAAAMdAAAAAAAAAAAAAAAAAAAMeAAAAAAAAAAAAA"
        "AAAAAAMiAAAAAAAAAAAAAAAAAAAMcAAAAAAAAAAAAAAAAAAAMXAAAAAAAAAAAAAAAAAAAMfAAAAAAAAAAAAAAAAAAAAAAAAAL2AA"
        "AAAAAL3AAAAL4AAAAAAAAAAAAAAAAAAAPnAAAAAAAAAAAAAAAAAAAC+AAAAAAAAAAAAAAAAAAAQEAAAAAAAAAAAAAAAAAAAOPAAA"
        "AAAAAAAAAAAAAAAAP/AAAAAAAAAAAAAAAAAAANvAAAAAAAAAAAAAAAAAAAQjAAAAAAAAAAAAAAAAAAAMnAAAAAAAAAAAAAAAAAAA"
        "P+AAAAAAAAAAAAAAAAAAAOWAAAAAAAAAAAAAAAAAAANuAAAAAAAAAAAAAAAAAAAPCAAAAAAAAAAAAAAAAAAANxAAAAAAAAAAAAAA"
        "AAAAAObAAAAAAAOcAAAAAAAAAAEVAAAAAAAAAAAAAAAAAAAETAAAAAAAAAAAAAAAAAAAN8AAAAAAAAAAAAAAAAAAAErAAAAAAAAA"
        "AAAAAAAAAAQ3AAAAAAAAAAAAAAAAAAAEyAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAQ8AAAAAAAAAAAAAAAAAAAQGAAAA"
        "AAAAAAAAAAAAAAAP8AAAAAAAAAAAAAAAAAAAQhAAAAAAAAAAAAAAAAAAAODAAAAAAAOEAAAAAAAAAAFJAAAAAAAAAAAAAAAAAAAN"
        "6AAAAAAAAAAAAAAAAAAAFcAAAAAAAAAAAAAAAAAAAMjAAAAAAAAAAAAAAAAAAANDAAAAAAAAAAAAAAAAAAAFNAAAAAAAAAAAAAAA"
        "AAAAQBAAAAAAAAAAAAAAAAAAAPoAAAAAAAAAAAAAAAAAAAOBAAAAAAAAAAAAAAAAAAAPDAAAAAAAAAAAAAAAAAAANtAAAAAAAAAA"
        "AAAAAAAAAO/AAAAAAAAAAAAAAAAAAAOjAAAAAAAAAAAAAAAAAAAQHAAAAAAAAAAAAAAAAAAAGQAAAAAAAAAAAAAAAAAAAMlAAAAA"
        "AAAAAAAAAAAAAAQDAAAAAAAAAAAAAAAAAAAQ9AAAAAAAAAAAAAAAAAAAPIAAAAAAAAAAAAAAAAAAAMpAAAAAAAAAAAAAAAAAAAQf"
        "AAAAAAAAAAAAAAAAAAAN1AAAAAAAAAAAAAAAAAAAL8AAAAAAAAAAAAAAAAAAAQFAAAAAAAAAAAAAAAAAAAO6AAAAAAAAAAAAAAAA"
        "AAAGyAAAAAAAAAAAAAAAAAAAMWAAAAAAAAAAAAAAAAAAAO+AAAAAAAAAAAAAAAAAAAQCAAAAAAAAAAAAAAAAAAAP1AAAAAAAAAAA"
        "AAAAAAAAOUAAAAAAAAAAAAAAAAAAANfAAAAAAAAAAAAAAAAAAAPFAAAAAAAAAAAAAAAAAAAOfAAAAAAAAAAAAAAAAAAANqAAAAAA"
        "AAAAAAAAAAAAANaAAAAAAAAAAAAAAAAAAAOrAAAAAAAAAAAAAAAAAAAQvAAAAAAAAAAAAAAAAAAAQdAAAAAAAAAAAAAAAAAAAFeA"
        "AAAAAAAAAAAAAAAAAAFdAAAAAAAAAAAAAAAAAAAG/AAAAAAAAAAAAAAAAAAAGAAAAAAAAAAAAAAAAAAAARnAAAAAAAAAAAAAAAAA"
        "AAPrAAAAAAAAAAAAAAAAAAAPyAAAAAAAAAAAAAAAAAAAPqAAAAAAAAAAAAAAAAAAANiAAAAAAAAAAAAAAAAAAARlAAAAAAAAAAAA"
        "AAAAAAAQzAAAAAAAAAAAAAAAAAAAEJAAAAAAAAAAAAAAAAAAAQ5AAAAAAAAAAAAAAAAAAANzAAAAAAAAAAAAAAAAAAAPwAAAAAAA"
        "AAAAAAAAAAAAQcAAAAAAAAAAAAAAAAAAAEeAAAAAAAAAAAAAAAAAAAOpAAAAAAAAAAAAAAAAAAAOAAAAAAAAAAAAAAAAAAAAPGAA"
        "AAAAAAAAAAAAAAAAAPHAAAAAAAAAAAAAAAAAAAPvAAAAAAAAAAAAAAAAAAAQ/AAAAAAAAAAAAAAAAAAAFsAAAAAAAAAAAAAAAAAA"
        "AFtAAAAAAAAAAAAAAAAAAAPkAAAAAAAAAAAAAAAAAAAPiAAAAAAAAAAAAAAAAAAAMVAAAAAAAAAAAAAAAAAAAF8AAAAAAAAAAAAA"
        "AAAAAAP3AAAAAAAAAAAAAAAAAAAN/AAAAAAAAAAAAAAAAAAAPxAAAAAAAAAAAAAAAAAAANhAAAAAAAAAAAAAAAAAAAPOAAAAAAAA"
        "AAAAAAAAAAAPuAAAAAAAAAAAAAAAAAAAOqAAAAAAAAAAAAAAAAAAAQ2AAAAAAAAAAAAAAAAAAAN+AAAAAAAAAAAAAAAAAAARAAAA"
        "AAAAAAAAAAAAAAAARmAAAAAAAAAAAAAAAAAA";
    inline constexpr const char* ZoneNamesChunks[] = {ZoneNamesChunk0};
    inline constexpr Packed ZoneNames{ZoneNamesChunks, 13, 3};

    inline constexpr char MetaKeysChunk0[] =
        "AAAAABAACAADAAFAAGAAIAALAAMAANAAOAAPAAQAARAAUAAVAAWAAXAAZAAaAAbAAcAAdAAeAAfAAhAAjAAkAAmAAoAApAArAAsA"
        "AtAAuAAvAAwAAxAAyAAzAA1AA3AA6AA7AA8AA9AA+AA/ABAABBABCABDABEABGABHABIABJABKABOABPABRABSABTABUABVABWAB"
        "XABYABZABaABbABcABeABfABgABhABjABkABlABnABoABpABsABvABwAByAB0AB1AB2AB3AB4AB5AB6AB7AB8AB9AB+AB/ACAACB"
        "ACCACDACEACFACHACIACKACLACMACNACOACPACQACRACSACTACUACWACXACYACZACbACcACeACfACgAChACjACkAClACmACpACqA"
        "CrACtACuACwACyACzAC0AC1AC2AC3AC4AC5AC6AC7AC9";
    inline constexpr const char* MetaKeysChunks[] = {MetaKeysChunk0};
    inline constexpr Packed MetaKeys{MetaKeysChunks, 13, 3};

    inline constexpr char MetaNamesChunk0[] =
        "ARsARtARuAAAAAAAAAAAAARvAAAAAAAAAAAAAAAARwAAAAAAAAAAAAAAAARxAAAAAAAAAAAAAAAARyAAAAAAAAAAAAARzAR0AR1A"
        "AAAAAAAAAR2AR3AR4AAAAAAAAAAR5AR6AR7AAAAAAAAAAR8AR9AR+AAAAAAAAAAR/ASAASBAAAAAAAAAASCASDASEAAAAAAAAAAS"
        "FASGASHAAAAAAAAAASIASJASKAAAAAAAAAASLASMASNAAAAAAAAAASOASPASQAAAAAAAAAASRASSASTAAAAAAAAAASUASVASWAAA"
        "AAAAAAASXASYASZAAAAAAAAAASaASbAScAAAAAAAAAASdASeASfAAAAAAAAAASgAShASiAAAAAAAAAASjASkASlAAAAAAAAAASmA"
        "SnASoAAAAAAAAAASpASqASrAAAAAAAAAASsAStASuAAAAAAAAAASvASwASxAAAAAAAAAAAAASyAAAAAAAAAAAAAAAASzAAAAAAAA"
        "AAAAAS0AS1AS2AAAAAAAAAAAAAS3AAAAAAAAAAAAAS4AS5AS6AAAAAAAAAAAAAS7AAAAAAAAAAAAAS8AS9AS+AAAAAAAAAAS/ATA"
        "ATBAAAAAAAAAATCATDATEAAAAAAAAAAAAATFAAAAAAAAAAAAAAAATGAAAAAAAAAAAAATHATIATJAAAAAAAAAATKATLATMAAAAAAA"
        "AAATNATOATPAAAAAAAAAAAAATQAAAAAAAAAAAAAAAATRAAAAAAAAAAAAAAAATSAAAAAAAAAAAAATTATUATVAAAAAAAAAAAAATWAA"
        "AAAAAAAAAAATXATYATZAAAAAAAAAATaATbATcAAAAAAAAAAAAATdAAAAAAAAAAAAATeATfATgAAAAAAAAAAThATiATjAAAAAAAAA"
        "ATkATlATmAAAAAAAAAAAAATnAAAAAAAAAAAAAAAAToAAAAAAAAAAAAAAAATvAAAAAAAAAAAAAAAATpAAAAAAAAAAAAAAAATqAAAA"
        "AAAAAAAAATrATsATtAAAAAAAAAAAAATuAAAAAAAAAAAAATwATxATyAAAAAAAAAATzAT0AT1AAAAAAAAAAAAAT2AAAAAAAAAAAAAA"
        "AAT3AAAAAAAAAAAAAT4AT5AT6AAAAAAAAAAT7AT8AT9AAAAAAAAAAT+AT/AUAAAAAAAAAAAAAAUBAAAAAAAAAAAAAAAAUCAAAAAA"
        "AAAAAAAAAAUDAAAAAAAAAAAAAAAAUEAAAAAAAAAAAAAAAAUFAAAAAAAAAAAAAAAAUGAAAAAAAAAAAAAUHAUIAUJAAAAAAAAAAUKA"
        "ULAUMAAAAAAAAAAUNAUOAUPAAAAAAAAAAUQAURAUSAAAAAAAAAAUTAUUAUVAAAAAAAAAAAAAUWAAAAAAAAAAAAAAAAUXAAAAAAAA"
        "AAAAAAAAUYAAAAAAAAAAAAAUZAUaAUbAAAAAAAAAAAAAUcAAAAAAAAAAAAAUdAUeAUfAAAAAAAAAAAAAUgAAAAAAAAAAAAAAAAUh"
        "AAAAAAAAAAAAAUiAUjAUkAAAAAAAAAAUlAUmAUnAAAAAAAAAAAAAUoAAAAAAAAAAAAAAAAUpAAAAAAAAAAAAAAAAUqAAAAAAAAAA"
        "AAAAAAUrAAAAAAAAAAAAAUsAUtAUuAAAAAAAAAAAAAUvAAAAAAAAAAAAAUwAUxAUyAAAAAAAAAAUzAU0AU1AAAAAAAAAAU2AU3AU"
        "4AAAAAAAAAAAAAU5AAAAAAAAAAAAAAAAU6AAAAAAAAAAAAAAAAU7AAAAAAAAAAAAAU8AU9AU+AAAAAAAAAAU/AVAAVBAAAAAAAAA"
        "AVCAVDAVEAAAAAAAAAAAAAVFAAAAAAAAAAAAAVGAVHAVIAAAAAAAAAAVJAVKAVLAAAAAAAAAAVMAVNAVOAAAAAAAAAAVPAVQAVRA"
        "AAAAAAAAAVSAVTAVUAAAAAAAAAAAAAVVAAAAAAAAAAAAAAAAVWAAAAAAAAAAAAAVXAVYAVZAAAAAAAAAAVaAVbAVcAAAAAAAAAAV"
        "dAVeAVfAAAAAAAAAAAAAVgAAAAAAAAAAAAAVhAViAVjAAAAAAAAAAAAAVkAAAAAAAAAAAAAAAAVlAAAAAAAAAAAAAAAAVmAAAAAA"
        "AAAAAAAAAAVnAAAAAAAAAAAAAAAAVoAAAAAAAAAAAAAVpAVqAVrAAAAAAAAAAVsAVtAVuAAAAAAAAAAVvAVwAVxAAAAAAAAAAAAA"
        "VyAAAAAAAAAAAAAAAAVzAAAAAAAAAAAAAAAAV0AAAAAAAAAAAAAAAAV1AAAAAAAAAAAAAAAAV2AAAAAAAAAAAAAAAAV3AAAAAAAA"
        "AAAAAAAAV4AAAAAAAAAAAAAV5AV6AV7AAAAAAAAAAAAAV8AAAAAAAAAAAAAAAAV9AAAAAAAAAAAAAV+AV/AWAAAAAAAAAAAAAAWB"
        "AAAAAAAAAAAAAWCAWDAWEAAAAAAAAAAAAAWFAAAAAAAAAAAAAWGAWHAWIAAAAAAAAAAWJAWKAWLAAAAAAAAAAWMAWNAWOAAAAAAA"
        "AAAAAAWPAAAAAAAAAAAAAWQAWRAWSAAAAAAAAAAWTAWUAWVAAAAAAAAAAAAAWWAAAAAAAAAAAAAAAAWXAAAAAAAAAAAAAAAAWYAA"
        "AAAAAAAAAAAWZAWaAWbAAAAAAAAAAWcAWdAWeAAAAAAAAAAAAAWfAAAAAAAAAAAA";
    inline constexpr const char* MetaNamesChunks[] = {MetaNamesChunk0};
    inline constexpr Packed MetaNames{MetaNamesChunks, 13, 3};

    inline constexpr uint16_t Formats[] = {
        1440, 1441, 1442, 1443, 1444, 1445, 0, 0, 0, 0, 0, 1446,
    };

    inline constexpr Table table{
        0x747400000000, 0,
        NameTexts,
        LanguageKeys, LanguageNames, 147,
        nullptr, Packed{}, 0,
        RegionKeys, RegionNames, 294,
        ScriptKeys, ScriptNames, 9,
        AloneKeys, AloneNames, 2,
        CurrencyKeys, CurrencyNames, 153,
        ZoneKeys, ZoneNames, 416,
        MetaKeys, MetaNames, 148,
        Formats,
    };

    // the table registered when the header is included, once a program
    inline Registration registration{&table};
}
