//------------------------------------------------------------------------------
// SGCL: a C++20 application platform
// Copyright (c) 2022-2026 Sebastian Nibisz
// SPDX-License-Identifier: Apache-2.0
//------------------------------------------------------------------------------
#pragma once
#include "detail/registry.h"
#include "ur.h"

#include <cstdint>

// The display names of the locale ur-IN (اردو), CLDR 46.0: the names of languages,
// regions, scripts, currencies and time zones in it, what differs from ur (included).
// Including this header is all a program does: txt::locale::display_name,
// region::display_name, script::display_name and currency::display_name then
// answer in this language. Generated by tools/cldr_tables.py: do not edit.
namespace sgcl::txt::detail::names::l_ur_IN {
    inline constexpr char8_t NameChunk0[] =
        u8"جدید معیاری عربیاودھیسورانی کردیزرمہکروشینجاوانیزجارجيائىکلالیسٹکنڑکردمگہیمعیاری مراقشی تمازیقیآسان "
        u8"چینیجزیرہ اسینشنجزائر آلینڈجزیرہ بوویتجزائر (کیلنگ) کوکوسجزائر ککجزیرہ کلپرٹنڈیگو گارشیاجزائر فاکلین"
        u8"ڈجزائر فیروفرانسیسی گیاناجزائر ہرڈ و مکڈونلڈجزائر کناریجزائر مارشلجزائر شمالی ماریاناجزیرہ نارفوکجزا"
        u8"ئر پٹکیرنجزائر سلیمانترسٹان دا کونیاجزائر کیکس و ترکیہامریکی بیرونی جزائربرطانوی جزائر ورجنامریکی جز"
        u8"ائر ورجنکوسٹا ریکا کولونکیوبائی پیسوکیپ ورڈی اسکیوڈوبرطانوی پاونڈ سٹرلنگگھانی سیڈیپاکستانی روپیہپاکس"
        u8"تانی روپےساموآئی ٹالاکیمبرج بےگوس بےگلیس بےاکراتھولےاتتوققورتورمیتبوڈاپیسٹگرینڈ ترکافغانستان ٹائمایم"
        u8"یزون ٹائمایمیزون سٹینڈرڈ ٹائمایمیزون سمر ٹائمعرب ٹائمعرب سٹینڈرڈ ٹائمعرب ڈے لائٹ ٹائممغربی ارجنٹینا "
        u8"ٹائممغربی ارجنٹینا سٹینڈرڈ ٹائممغربی ارجنٹینا سمر ٹائمآرمینیا ٹائمآرمینیا سٹینڈرڈ ٹائمآرمینیا سمر ٹا"
        u8"ئمآذربائیجان ٹائمآذربائیجان سٹینڈرڈ ٹائمآذربائیجان سمر ٹائمبنگلہ دیش ٹائمبنگلہ دیش سٹینڈرڈ ٹائمبنگلہ"
        u8" دیش سمر ٹائمبھوٹان ٹائمبولیویا ٹائمبرازیلیا ٹائمبرازیلیا سٹینڈرڈ ٹائمبرازیلیا سمر ٹائمچلی ٹائمچلی س"
        u8"ٹینڈرڈ ٹائمچلی سمر ٹائمکولمبیا ٹائمکولمبیا سٹینڈرڈ ٹائمکولمبیا سمر ٹائمایسٹر آئلینڈ ٹائمایسٹر آئلینڈ"
        u8" سٹینڈرڈ ٹائمایسٹر آئلینڈ سمر ٹائمایکواڈور ٹائموسطی یورپ کا وقتوسطی یورپ کا معیاری وقتوسطی یورپ کا م"
        u8"وسم گرما کا وقتفاک لینڈ آئلینڈز ٹائمفاک لینڈ آئلینڈز سٹینڈرڈ ٹائمفاک لینڈ آئلینڈز سمر ٹائمفرینچ گیان"
        u8"ا ٹائمگالاپاگوز ٹائمجارجیا ٹائمجارجیا سٹینڈرڈ ٹائمجارجیا سمر ٹائمگرین وچ مین ٹائمخلیج سٹینڈرڈ ٹائمگی"
        u8"انا ٹائمانڈیا سٹینڈرڈ ٹائمایران ٹائمایران سٹینڈرڈ ٹائمایران ڈے لائٹ ٹائماسرائیل ٹائماسرائیل سٹینڈرڈ "
        u8"ٹائماسرائیل ڈے لائٹ ٹائممشرقی قزاخستان ٹائممغربی قزاخستان ٹائمکرغستان ٹائممالدیپ ٹائمنیپال ٹائمنیوزی"
        u8" لینڈ ٹائمنیوزی لینڈ سٹینڈرڈ ٹائمنیوزی لینڈ ڈے لائٹ ٹائمفرنانڈو ڈی نورنہا ٹائمفرنانڈو ڈی نورنہا سٹین"
        u8"ڈرڈ ٹائمفرنانڈو ڈی نورونہا سمر ٹائمپاکستان ٹائمپاکستان سٹینڈرڈ ٹائمپاکستان سمر ٹائمپیراگوئے ٹائمپیرا"
        u8"گوئے سٹینڈرڈ ٹائمپیراگوئے سمر ٹائمپیرو ٹائمپیرو سٹینڈرڈ ٹائمپیرو سمر ٹائمروتھیرا ٹائمسورینام ٹائمتاج"
        u8"کستان ٹائمترکمانستان ٹائمترکمانستان سٹینڈرڈ ٹائمترکمانستان سمر ٹائمیوروگوئے ٹائمیوروگوئے سٹینڈرڈ ٹائ"
        u8"میوروگوئے سمر ٹائمازبکستان ٹائمازبکستان سٹینڈرڈ ٹائمازبکستان سمر ٹائموینزوئیلا ٹائمووسٹاک ٹائم{0} ({"
        u8"1}){0}،{1}{0} وقت{0} معیاری وقت{0} دن کا وقت{1} ({0}){0} {1}";
    inline constexpr const char8_t* NameChunks[] = {NameChunk0};
    inline constexpr uint16_t NameChunkSizes[] = {4041};
    inline constexpr char NameRefsChunk0[] =
        "AAAAAAAAAAAeAAAoAAA9AABFAABRAABfAABvAAB9AACDAACJAACRAAC5AADKAADhAAD2AAELAAEtAAE8AAFTAAFoAAGBAAGUAAGv"
        "AAHSAAHnAAH8AAIgAAI3AAJOAAJlAAKBAAKiAALGAALoAAMIAAMmAAM9AANbAAOBAAOUAAOvAAPIAAPfAAPwAAP7AAQIAAQQAAQa"
        "AAQ2AARGAARXAARyAASJAASvAATNAATcAAT6AAUXAAU7AAVuAAWZAAWwAAXWAAX0AAYRAAY9AAZhAAZ7AAakAAbFAAbaAAbxAAcK"
        "AAcyAAdSAAdhAAd/AAeVAAesAAfSAAfwAAgQAAg/AAhmAAh/AAicAAjGAAj6AAkhAAlXAAmFAAmjAAm+AAnTAAn3AAoTAAowAApQ"
        "AApjAAqFAAqYAAq6AArbAAryAAsYAAs9AAthAAuFAAucAAuxAAvEAAvgAAwLAAw1AAxeAAyWAAzIAAzfAA0FAA0jAA08AA1kAA2E"
        "AA2VAA21AA3NAA3kAA37AA4UAA4xAA5dAA6BAA6aAA7CAA7iAA77AA8jAA9DAA9eAA9zAA98AA+EAA+OAA+lAA+5AA/CAA/J";
    inline constexpr const char* NameRefsChunks[] = {NameRefsChunk0};
    inline constexpr Packed NameRefs{NameRefsChunks, 13, 4};
    inline constexpr Text NameTexts{NameChunks, NameChunkSizes, NameRefs};

    inline constexpr char LanguageKeysChunk0[] =
        "AESAFWAFhAFsAFuAF1AbhA1iBFFDQnGjo";
    inline constexpr const char* LanguageKeysChunks[] = {LanguageKeysChunk0};
    inline constexpr Packed LanguageKeys{LanguageKeysChunks, 13, 3};

    inline constexpr char LanguageNamesChunk0[] =
        "AAFAAGAAHAAIAAJAAKAACAADAAEAALAAM";
    inline constexpr const char* LanguageNamesChunks[] = {LanguageNamesChunk0};
    inline constexpr Packed LanguageNames{LanguageNamesChunks, 13, 3};

    inline constexpr const uint64_t* TaggedKeys = nullptr;

    inline constexpr const uint16_t* TaggedNames = nullptr;

    inline constexpr char RegionKeysChunk0[] =
        "AAeAAzABMABUABcABhABzACtACxADDADlAD2AFnAFvAGAAG+AIDAIdAIfAJEAJZAJb";
    inline constexpr const char* RegionKeysChunks[] = {RegionKeysChunk0};
    inline constexpr Packed RegionKeys{RegionKeysChunks, 13, 3};

    inline constexpr char RegionNamesChunk0[] =
        "AAOAAPAAQAARAASAATAAUAAVAAWAAXAAYAAZAAaAAbAAcAAdAAeAAfAAgAAhAAiAAj";
    inline constexpr const char* RegionNamesChunks[] = {RegionNamesChunk0};
    inline constexpr Packed RegionNames{RegionNamesChunks, 13, 3};

    inline constexpr const uint32_t* ScriptKeys = nullptr;

    inline constexpr const uint16_t* ScriptNames = nullptr;

    inline constexpr const uint32_t* AloneKeys = nullptr;

    inline constexpr const uint16_t* AloneNames = nullptr;

    inline constexpr char CurrencyKeysChunk0[] =
        "A5DA6wA7FBxQB0TEFyF50";
    inline constexpr const char* CurrencyKeysChunks[] = {CurrencyKeysChunk0};
    inline constexpr Packed CurrencyKeys{CurrencyKeysChunks, 13, 3};

    inline constexpr char CurrencyNamesChunk0[] =
        "AAkAAAAAAAAAAAAAAAAAAAAlAAAAAAAAAAAAAAAAAAAAmAAAAAAAAAAAAAAAAAAAAnAAAAAAAAAAAAAAAAAAAAoAAAAAAAAAAAAA"
        "AAAAAAApAAAAApAAAAAAAAAAAqAArAAAAAAAAAAAAAAAAAA";
    inline constexpr const char* CurrencyNamesChunks[] = {CurrencyNamesChunk0};
    inline constexpr Packed CurrencyNames{CurrencyNamesChunks, 13, 3};

    inline constexpr char ZoneKeysChunk0[] =
        "AABABMABnABpABqACxAC7AFc";
    inline constexpr const char* ZoneKeysChunks[] = {ZoneKeysChunk0};
    inline constexpr Packed ZoneKeys{ZoneKeysChunks, 13, 3};

    inline constexpr char ZoneNamesChunk0[] =
        "AAvAAAAAAAAAAAAAAAAAAAAsAAAAAAAAAAAAAAAAAAAAuAAAAAAAAAAAAAAAAAAAAtAAAAAAAAAAAAAAAAAAAAzAAAAAAAAAAAAA"
        "AAAAAAAxAAAAAAAAAAAAAAAAAAAAwAAAAAAAAAAAAAAAAAAAAyAAAAAAAAAAAAAAAAAA";
    inline constexpr const char* ZoneNamesChunks[] = {ZoneNamesChunk0};
    inline constexpr Packed ZoneNames{ZoneNamesChunks, 13, 3};

    inline constexpr char MetaKeysChunk0[] =
        "AABAALAAUAAWAAXAAeAAhAAjAAkAAmAAtAAxAA7AA8AA9ABBABDABGABHABJABRABSABWABcABfABkABlABsAB1AB/ACBACFACKA"
        "CNACOACXAChACmACtACwACyAC0AC3";
    inline constexpr const char* MetaKeysChunks[] = {MetaKeysChunk0};
    inline constexpr Packed MetaKeys{MetaKeysChunks, 13, 3};

    inline constexpr char MetaNamesChunk0[] =
        "AAAAA0AAAAAAAAAAAAAA1AA2AA3AAAAAAAAAAA4AA5AA6AAAAAAAAAAA7AA8AA9AAAAAAAAAAA+AA/ABAAAAAAAAAAABBABCABDA"
        "AAAAAAAAABEABFABGAAAAAAAAAAAAABHAAAAAAAAAAAAAAAABIAAAAAAAAAAAAABJABKABLAAAAAAAAAABMABNABOAAAAAAAAAAB"
        "PABQABRAAAAAAAAAABSABTABUAAAAAAAAAAAAABVAAAAAAAAAAAAABWABXABYAAAAAAAAAABZABaABbAAAAAAAAAAAAABcAAAAAA"
        "AAAAAAAAAABhAAAAAAAAAAAAAAAABdAAAAAAAAAAAAABeABfABgAAAAAAAAAAAAABiAAAAAAAAAAAAAAAABjAAAAAAAAAAAAAAAA"
        "BkAAAAAAAAAAAAABlABmABnAAAAAAAAAABoABpABqAAAAAAAAAAAAABrAAAAAAAAAAAAAAAABsAAAAAAAAAAAAAAAABtAAAAAAAA"
        "AAAAAAAABuAAAAAAAAAAAAAAAABvAAAAAAAAAAAAABwABxAByAAAAAAAAAABzAB0AB1AAAAAAAAAAB2AB3AB4AAAAAAAAAAB5AB6"
        "AB7AAAAAAAAAAB8AB9AB+AAAAAAAAAAAAAB/AAAAAAAAAAAAAAAACAAAAAAAAAAAAAAAAACBAAAAAAAAAAAAACCACDACEAAAAAAA"
        "AAACFACGACHAAAAAAAAAACIACJACKAAAAAAAAAAAAACLAAAAAAAAAAAAAAAACMAAAAAAAAAAAA";
    inline constexpr const char* MetaNamesChunks[] = {MetaNamesChunk0};
    inline constexpr Packed MetaNames{MetaNamesChunks, 13, 3};

    inline constexpr uint16_t Formats[] = {
        141, 142, 143, 144, 145, 146, 0, 0, 0, 0, 0, 147,
    };

    inline constexpr Table table{
        0x757200000202, 0x757200000000,
        NameTexts,
        LanguageKeys, LanguageNames, 11,
        nullptr, Packed{}, 0,
        RegionKeys, RegionNames, 22,
        Packed{}, Packed{}, 0,
        Packed{}, Packed{}, 0,
        CurrencyKeys, CurrencyNames, 7,
        ZoneKeys, ZoneNames, 8,
        MetaKeys, MetaNames, 43,
        Formats,
    };

    // the table registered when the header is included, once a program
    inline Registration registration{&table};
}
