//------------------------------------------------------------------------------
// SGCL: a C++20 application platform
// Copyright (c) 2022-2026 Sebastian Nibisz
// SPDX-License-Identifier: Apache-2.0
//------------------------------------------------------------------------------
#pragma once
#include "detail/registry.h"

#include <cstdint>

// The display names of the locale vec (veneto), CLDR 46.0: the names of languages,
// regions, scripts, currencies and time zones in it.
// Including this header is all a program does: txt::locale::display_name,
// region::display_name, script::display_name and currency::display_name then
// answer in this language. Generated by tools/cldr_tables.py: do not edit.
namespace sgcl::txt::detail::names::l_vec {
    inline constexpr char8_t NameChunk0[] =
        u8"afarabcazoacinezeadangmeadigheafreganaghemainuakanaleutianaltài meridionaleamàregoaragonezeoboloangi"
        u8"kaàrabo levantinàraboàrabo moderno standardmapudungunarapàoàrabo najdiasamezeasuasturianatikamecavàr"
        u8"egoawadiaimarazerbaijanbashkirbalucibalinezebasabelorusobenbabetawibenabùlgaroharianvibaluci osident"
        u8"alebojpuribizlamabinisiksikaaniitai dambanbarabanglatibetanbrètonebodoboznìagoakosbuginezeblincatala"
        u8"ncadocayugaatsamciakmacecensebuancigaciamorociukezemariciòctawcìpejancerokeeceyencìcasowcurdo sentra"
        u8"lecìlcotincorsomecifcree sud orientalecree de le pianurecree nord orientalecree mosealgonchin de la "
        u8"Carolinasecocree de le paludizlavo de ciezaciuvashgalezedanezedakotadargwataitatodescotodesco austrì"
        u8"agoalto todesco zvìsarodogribzarmadogribaso sorabodualamaldivianjola fonidzongkadazagaenbueweefikeka"
        u8"jukgregoinglezeingleze australianingleze canadezeingleze britànegoingleze mereganesperantospagnoloes"
        u8"tonianbascoewondopersiandarifulafilandezefilipinfijanfaroezefonfransezefranseze canadezefranseze zvì"
        u8"sarocadianfrìzone setentrionalefurlanfrìzone osidentaleirlandezegagaèlego scosezegeezgilbertezegalis"
        u8"ianguaranìgorontalotodesco zvìsarogujaratigusimanezegwichʼinhausahaidahawaianhaida meridionaleebràeg"
        u8"ohindihilighenomongmong novocroàalto sorabohaitianongarezehupahalkomelemarmenhererointerlenguaibanib"
        u8"ibioindonezianinterlengueigboyi de Sichuaninuktitut canadeze osidentaleilocaningushidoizlandezeitali"
        u8"aninuktitutjaponezelojbanngonbamachamejavanezejeorjancaracalpagocabilkachinjjukanbacabardiantyapmako"
        u8"ndecaoverdiankeniangkorokaingangkhasikoyra cinikikuyukuanyamakazakokakogroelandezekalenjincanbojanki"
        u8"nbunducanarezecoreankonkanikpelecanurikaraciài balkarcareliankurukcashmirishanbalabafiacologniancurd"
        u8"okumykkomicòrnegoKwakwalakuvikirghizolatinjudezmolangilusenburghezelezghiangandalinburghezelìgurolil"
        u8"uetlacotaladinlonbardolingalalaocrèolo de la Luizianaloziluri setentrionalesamialituanletgalianluba "
        u8"katangaluba lulualundadoluómizolujalètonemadurezemagahimaithilimakasarmasàimokshamendemerumaurisianm"
        u8"algasomeetometamarshalezemòchenomaorimicmacminangkabaumasèdonemalayàlammóngolomanipurinu aimunmohawk"
        u8"mosimaratimalezemaltezemundangmultilenguacrekmirandezebirmanerzyenmazandaraninauruannapoletannamanor"
        u8"vejeze bokmalndebele de’l nordbaso todescosàsone basonepalezenewarindonganiasniueanolandezefiamingok"
        u8"wazionorvejeze nynorskngienbonnorvejezenogàin’kondebele de’l sudsoto setentrionalenuernavajochewanya"
        u8"nkoleositanojibwa nord osidentaleojibwa sentraleoji creeojibwa osidentaleokanaganoromoorijaosètegoos"
        u8"agepunjabipangasinanpanpangapapiamentopalauanpidgin nijerianpijinpolacomalesita pasamacuodyprusianpa"
        u8"shtoportoghezeportogheze braziłianportogheze europèocuechuakishrajastanirapanuirarotonganroingarifeg"
        u8"noromanciorundiromenmoldavoronborusoaromenkiniarwandarwasànscritosandaweyakutosanburusantalinganbays"
        u8"angusardosisilianscosezesindicurdo meridionalesami setentrionalesenakoyraboro senisangotashelitshans"
        u8"ingalezesidamozlovacosaraikizlovenlushootseed meridionalesamoansami meridionalesami de’l Lulesami in"
        u8"ariansami skoltshonasoninkésòmaloalbanezeserbosranan tongozwatisahosoto meridionalesalish stretosund"
        u8"anezesukumazvedezesuailisuaili de’l Congocomoriansirìagosileziantamiltutchone meridionaletelugotemne"
        u8"tesotétumtàjegotagishtailandezetaltantigrignatigréturcomanklingontlingittswanatongantoki ponatok pis"
        u8"inturcotarokotorwalitsongatàtarotutchone setentrionaletunbukatuvaluantasawactaitiantuviniantamazigh "
        u8"de l’Atlante sentraleudmurtouigurucrainunbundulengua desconoscùaurduuzbegovendavenetovietnamezemacùa"
        u8"volapükvunjovalonwalserwolaitawaraywarlpiriwolofwukalmikxhosakangrisogayangbenyenbayidishyorubanenga"
        u8"tucantonezezuantamazight standard de’l Marocosinezezuluzunignaun contegnùo lenguìstegozazakimondoÀfr"
        u8"egaMèrega de’l nordMèrega de’l sudOseaniaÀfrega osidentaleMèrega sentraleÀfrega orientaleÀfrega sete"
        u8"ntrionaleÀfrega sentraleÀfrega meridionaleMèregheMèrega setentrionaleCaràibiAzia orientaleAzia merid"
        u8"ionaleAzia de’l sudestEuropa meridionaleAustralaziaMelaneziaRejon micronezianaPolineziaAziaAzia sent"
        u8"raleAzia osidentaleEuropaEuropa orientaleEuropa setentrionaleEuropa osidentaleÀfrega subsaharianaMèr"
        u8"ega LatinaÌzola AsensionAndoraEmirài Àrabi UnìiAfghanistanAntigua e BarbudaAnguilaAlbaniaArmeniaAngo"
        u8"laAntàrtideArjentinaSamòa mereganeÀustriaAustraliaArubaÌzole AlandAzerbaijanBoznia e ErzegòvinaBarba"
        u8"dosBangladeshBeljoBurkina FazoBulgarìaBareinBurundiBeninS. BartolomèoBermudaBrunéiBoliviaPaezi Basi "
        u8"caraìbeghiBrazileBahamasButanÌzola BuvetBotzwanaBelorusiaBelizeCànadaÌzole Cocos (Keeling)Repùblega "
        u8"Democràtega de’l CongoRepùblega SentrafreganaRepùblega de’l CongoZvìsaraCosta d’AvorioÌzole CookCile"
        u8"CàmerunSinaColonbiaÌzola de ClippertonSarcCosta RicaCubaCao VerdoCuraçaoÌzola de NadaleSiproCechiaJe"
        u8"rmaniaDiego GarciaJibutiDanimarcaDoménegaRepùblega DomeneganaAljerìaCeuta e MelilaÈcuadorEstoniaEjit"
        u8"oSahara OsidentaleEritrèaSpagnaEtiopiaUnion europèaEurozonaFinlandaFijiÌzole MalvineMicroneziaÌzole "
        u8"FàroeFransaGabonRegno UnìoGranadaJeorjaGuyana fransezeGuernseyGanaGibilteraGroenlandaGanbiaGuinèaGua"
        u8"dalupaGuinèa EcuatorialeGreciaGeorgia de’l sud e Sandwich de’l sudGuatemalaGuamGuinèa BisàoGuyanaRAS"
        u8" de Hong KongÌzole Heard e McDonaldHondurasCroasiaHaitiOngarìaÌzole CanarieIndoneziaIrlandaIzraeleÌz"
        u8"ola de ManIndiaTeritorio britànego de l’Osèano IndianIracIranIzlandaItaliaJerseyJamàegaJordaniaJapon"
        u8"KenyaKirghizistanCanbojaKiribatiÌzole ComoreS. Cristofer e NevisCorèa de’l nordCorèa de’l sudKuwaitÌ"
        u8"zole CaimanKazakistanLaosLìbanoS. LusìaLiechtensteinSri LankaLiberiaLezotoLituaniaLusenburgoLetoniaL"
        u8"ibiaMarocoMònacoMoldaviaMontenegroS. Martin (Fransa)MadagascarÌzole MarshallMasedonia de’l nordMaliM"
        u8"yanmar (Birmania)MongoliaRAS de MacàoÌzole Mariane setentrionaliMartinigaMauritaniaMontseratMaltaÌzo"
        u8"le MaurisioMaldiveMalawiMèsegoMalèiziaMozanbigoNamibiaNova CaledoniaNigerÌzola NorfolkNigeriaNicarag"
        u8"uaPaezi BasiNorvejaNepalNauruNiueNova ZelandaOmanPànamaPerùPolinezia fransezePapua Nova GuinèaFilipi"
        u8"nePakistanPoloniaS. Piero e MichelonÌzole PitcairnPortoricoTeritori palestineziPortogaloPalàuParaguà"
        u8"iCatarOseania perifèregaÌzola ReunionRomaniaSerbiaRusiaRuandaArabia SaudìaÌzole SalomonÌzole SeiselS"
        u8"udanZvesiaSingaporeÌzola S. ÈlenaZloveniaZvàlbard e Jan MayenZlovachiaSiera LeonSan MarinSènegalSoma"
        u8"liaSurinameSud SudanS. Tomazo e PrìnsipeEl SalvadorS. Martin (Paezi Basi)SiriaEsuatiniTristan de Cug"
        u8"naTurks e CaicosCiadTeritori fransezi de’l sudTogoTailandiaTajikistanTokelàuTimor EstTurkmenistanTun"
        u8"izìaTongaTurchiaTrinidà e TabacoTuvaluTaiwanTanzaniaUcrainaUgandaÌzołe perifèreghe mereganeNasion Un"
        u8"ìeStadi UnìiUruguàiUzbekistanVateganS. Vincenso e GranadineVenesuelaÌzole Vèrjini britànegheÌzole Vè"
        u8"rjini mereganeVietnamVanuatuWallis e FutunaSamòaPseudo asentiPseudo bidiKòsovoYemenÌzole MaioteSudàf"
        u8"regaZanbiaZinbaweRejon desconosùaadlamalbaneze caucàzegoahomnastaliqamàrego inperialeavèstegobamunva"
        u8"hbatakbengalezebaiksukibopomofobrahmibraillebuhidsilabaro aborìjeno canadeze unifegàcariochamcheroke"
        u8"ecorazmiancoptosipro minòegosipriotosirìlegozlavo de cieza antigodevanàgaridives akurudeseretduploya"
        u8"n stenografàjeroglìfeghi ejisianielbasanelimàegoetiòpegogarayglagolìtegogunjalagondi masaramgòtegogr"
        u8"antagurung khemagurmukihan co bopomofohangulhanhanunoosenpiotradisionalehatranhiraganajeroglìfeghi a"
        u8"natòleghipahaw hmongniakeng puachu hmongsilabari japoneziongareze antigoitàlego antigojamokayah lika"
        u8"tanakakawikarostikmerkojikikitan celokanadakirat raikaitilanalatin frakturlatin gaèlegolepchalinbuli"
        u8"near Alinear Bfraserlisiolidiomahajanmandàegomanighèomarchenmedefaidrinmeroìtego corsivomeroìtegomod"
        u8"imromeitéimultaninag mundarinandinagariàrabo antigo de’l nordnabatèonewanushuogamol cikiol onalorcon"
        u8"ozmaniauigur antigopalmirenpau cin haupèrmego antigopagspapalavo de le iscrisionpalavo salterofeniso"
        u8"fonètego de Pollardparto de le iscrisionzovghirejanghanifirùnegosamaritanàrabo antigo de’l sudsauras"
        u8"htrascritura de i segnishaviansharadasidamkudawadisogdiansogdian antigosora sonpengsoyonbosunuwarsyl"
        u8"oti nagrisirìago estrànjelosirìago osidentalesirìago orientaletagbanwatakritai letai lu senpiotangut"
        u8"tai viettifinagtagalogthanatirutatangsatodhritototigalariugarìtegovaibeita kukjuwarang sitiwanchoper"
        u8"sian antigocugniforme sumero acadianyezidiyizanabazar cuadràreditànotasion matemàtegaemojisìnbolimig"
        u8"a scritocomundesconosùohan senpiohan tradisionaledirham de i Emirài Àrabi Unìiafgan afghanistanafgan"
        u8"i afghanistanlek albanezelek albanezidram armendram armenikwanza angolezekwanza angolezipezos arjent"
        u8"inpezos arjentinidòlaro australiandòlari australianifiorin arubanezefiorini arubanezimanat azerbaija"
        u8"nmanat azerbaijanimarco convertìbile de la Boznia e Erzegòvinamarchi convertìbili de la Boznia e Erz"
        u8"egòvinadòlaro barbadezedòlari barbadezitaka bangladezetaka bangladezilev bùlgarolev bùlgaridìnaro ba"
        u8"reinezedìnari bareinezifranco burundezefranchi burundezidòlaro bermudezedòlari bermudezidòlaro brune"
        u8"iandòlari bruneianibolivianbolivianireal brazilianreal brazilianidòlaro bahamezedòlari bahamezigultr"
        u8"um butanezegultrum butanezipula botzwanezepula botzwanezirublo belorusorubli belorusidòlaro belizene"
        u8"zedòlari belizenezidòlaro canadezedòlari canadezifranco congolezefranchi congolezifranco zvìsarofran"
        u8"chi zvìsaripezos cilenpezos cileniyuan sinezeyuan sinezipezos colonbianpezos colonbianicolonbo costa"
        u8"ricancolonbi costaricanipezos cubanpezos cubaniscudo caoverdianscudi caoverdianicorona cecacorone ce"
        u8"chefranco jibutianfranchi jibutianicorona danezecorone danezipezos domeneganpezos domeneganidìnaro a"
        u8"ljerindìnari aljerinisterlina ejisianasterline ejisianenakfa eritrèonakfa eritrèibir etiòpegobir eti"
        u8"òpeghieurodòlaro fijiandòlari fijianisterlina malvinezesterline malvinezisterlina inglezesterline in"
        u8"glezilari jeorjanlari jeorjanicedi ganezecedi ganezisterlina gibilteranasterline gibilteranedalaso g"
        u8"anbiandalasi ganbianifranco guineanfranchi guineaniquetzal guatemalezequetzal guatemalezidòlaro guya"
        u8"nezedòlari guyanezidòlaro hongkongezedòlari hongkongezilenpira hondurezelenpira hondurezigordo haiti"
        u8"angordi haitianifiorin ongarezefiorini ongarezirupìa indonezianarupìe indonezianenovo siglo izraelia"
        u8"nnovi sigli izraelianirupìa indianarupìe indianedìnaro irachendìnari irachenirial iranianrial irania"
        u8"nicorona izlandezecorone izlandezidòlaro jamaegandòlari jamaeganidìnaro jordaniandìnari jordanianiye"
        u8"n japonezeyen japoneziselin kenianselini kenianisom kirghizistansom kirghizistanirial canbojanrial c"
        u8"anbojanifranco comorianfranchi comorianiwon nordcoreanwon nordcoreaniwon sudcoreanwon sudcoreanidìna"
        u8"ro kuwaitiandìnari kuwaitianidòlaro caimanezedòlari caimanezitenge kazakistantenge kazakistanikip la"
        u8"osiankip laosianisterlina libanezesterline libanezirupìa srilankezerupìe srilankezidòlaro liberiandò"
        u8"lari liberianiloti lezotianloti lezotianidìnaro lìbegodìnari lìbeghidirham marochindirham marochinil"
        u8"eu moldavoleu moldaviariari malgasoariari malgasidìnaro masèdonedìnari masèdonikiat birmankiat birma"
        u8"nitugrik móngolotugrik móngolipataca macaenapatache macaeneughija mauritanughija mauritanirupìa maur"
        u8"isianarupìe maurisianerupìa maldivianarupìe maldivianekwacha malawiankwacha malawianipezos meseganpe"
        u8"zos meseganiringit malezianringit malezianimetical mozanbiganmetical mozanbiganidòlaro namibiandòlar"
        u8"i namibianinaira nigeriananaire nigerianecòrdoba nicaraguezecòrdoba nicaraguezicorona norvejezecoron"
        u8"e norvejezirupìa nepalezerupìe nepalezidòlaro neozelandezedòlari neozelandezirial omanezerial omanez"
        u8"ibalbòa panamezebalbòa panamezisoles peruviansoles peruvianikina papuaianakine papuaianepezos filipi"
        u8"npezos filipinirupìa pakistanarupìe pakistanezloty polacozloty polachiguaranì paraguaianguaranì para"
        u8"guaianirial catarianrial catarianileu romenleu romenidìnaro serbodìnari serbirublo rusorubli rusifra"
        u8"nco ruandezefranchi ruandezirial saudìorial saudìidòlaro salomonezedòlari salomonezirupìa seiselezer"
        u8"upìe seiselezisterlina sudanezesterline sudanezicorona zvedezecorone zvedezidòlaro singaporiandòlari"
        u8" singaporianisterlina de Sant’Èlenasterline de Sant’Èlenaleon sierleonezeleoni sierleoneziselin sòma"
        u8"loselini sòmalidòlaro surinamezedòlari surinamezisterlina sud sudanezesterline sud sudanezidobra de "
        u8"S. Tomazo e Prìnsipesterlina sirianasterline sirianelilangeni esuatinlilangeni esuatinibat tailandez"
        u8"ebat tailandezisomoni tajikistansomoni tajikistanimanat turkmenistanmanat turkmenistanidìnaro tunizi"
        u8"ndìnari tunizinipaʻanga tonganpaʻanga tonganilira turcalire turchedòlaro de Trinidà e Tabacodòlari d"
        u8"e Trinidà e Tabaconovo dòlaro taiwanezenovi dòlari taiwaneziselin tanzanezeselini tanzanezigrivna uc"
        u8"rainagrivne ucraineselin ugandezeselini ugandezidòlaro meregandòlari mereganipezos uruguaianpezos ur"
        u8"uguaianisom uzbekistansom uzbekistanibolìvar venesuelanbolìvar venesuelanidong vietnamezedong vietna"
        u8"mezivatu vanuatianvatu vanuatianitala samoantala samoanifranco CFA de l’Àfrega sentralefranchi CFA d"
        u8"e l’Àfrega sentraledòlaro caraìbegodòlari caraìbeghifranco CFA de l’Àfrega osidentalefranchi CFA de "
        u8"l’Àfrega osidentalefranco CFPfranchi CFPmoneda desconosùa(moneda desconosùa)rial yemenidarial yemenì"
        u8"irand sudafreganrand sudafreganikwacha zanbiankwacha zanbianiOra universale coordenadaUTCSità descon"
        u8"osùaDubàiTiranaJèrevanRio GàlegosCòrdobaPango PangoVienaAdelàideBrizbaneÌzola MacquarieÌzola Lord Ho"
        u8"weDacaBruselUagadugùBujunburaPorto NovoEirunepéCuiabàCanpo GrandeSan PoloMaceióFernando de NoronhaTi"
        u8"npuS. JoaniÌzole CocosLubunbashiBanghìZurigoAbijanÌzola RarotongaÌzola de PascuaDualaUrumchiShanghài"
        u8"BogotàL’AvanaFamagostaPragaBüsingenCopenaghenAljeriGalàpagosTalinEl CairoEl AjunAzmaraCèutaAdis Abeb"
        u8"aÌzole ChuukÌzola PonpèiÌzola KosraeParijiLondraOra d’istà britànegaTiblisiCayenaAcraJibilteraConacr"
        u8"iAteneGeorgia de’l sudBisàoPorto PrìnsipeMakasarOra d’istà irlandezeJeruzalemeCalcutaCiagosBagdadTeh"
        u8"eranRekiavikRomaAmanBiskekPnom PenAtolo KiritimatiAtollo TarawaS. CristoferSeulCaimanAktàuOuralAtyrà"
        u8"uAktobeKostanàiKizilordaAlmatiVientianColonboMazeruTrìpoliCazablancaPodgorisaAtolo KwajaleinUlan Bàt"
        u8"orMacàoÌzola SaipànNuakchotÌzole MaldiveJuárezBaia de BanderasMontereySità de’l MèsegoCancunKuala Lu"
        u8"npurNouméaÀmsterdamOzloKatmandùÌzola NauruÌzola NiueÌzole CiatemMascateÌzola TaitiÌzole MarcheziÌzol"
        u8"e GambierPorto MoresbyÌzola BougainvilleVarsaviaMichelonÌzola PitcairnÌzole AzoreÌzola MadèiraLizbon"
        u8"aAsunsionBucarestBelgradoKaliningradoMoscaVolgogradoAstrahanUliànoskYekaterinburgoNovokuznietskKrazn"
        u8"ayarskCitaHàndigaSacalinUst-GneraZrédnekolimskKamciatkaAnàdyrRiadÌzola GuadalcanalMahéCartumStocolma"
        u8"Ìzola S. ElenaLublianaBratizlavaMogadisoÌzola S. TomazoDamascoNbabaneJamenaLoméDusanbéAtolo FakaofoA"
        u8"zgabadTùneziÌzola TongatapuÌstanbulPorto de SpagnaAtolo FunafutiTaipéiDar es SalamKievSinferòpoliKan"
        u8"palaAtolo MidwayAtolo WakeLos ÀngelesDènverBeulah (Nord Dakota)New Salem (Nord Dakota)Center (Nord D"
        u8"akota)Vincennes (Indiana)Petersburg (Indiana)Tell City (Indiana)Knox (Indiana)Winamac (Indiana)Maren"
        u8"go (Indiana)IndianàpolisVevay (Indiana)Monticello (Kentucky)SamarcandaTaskentS. VincensoTòrtolaS. To"
        u8"mazoÌzola EfateÌzola WallisDumont d’UrvilleAtikokanNuukIttoqqortoormiitYangonMéridaLower Prince’s Qu"
        u8"arterHo Chi MinhOra de l’AfghanistanOra de l’Àfrega sentraleOra de l’Àfrega orientaleOra de l’Àfrega"
        u8" meridionaleOra de l’Àfrega osidentaleOra normale de l’Àfrega osidentaleOra d’istà de l’Àfrega oside"
        u8"ntaleOra de l’AlaskaOra normale de l’AlaskaOra d’istà de l’AlaskaOra de l’AmasoniaOra normale de l’A"
        u8"masoniaOra d’istà de l’AmasoniaOra de’l nord Amèrega sentraleOra normale de’l nord Amèrega sentraleO"
        u8"ra d’istà de’l nord Amèrega sentraleOra de’l nord Amèrega orientaleOra normale de’l nord Amèrega ori"
        u8"entaleOra d’istà de’l nord Amèrega orientaleOra de’l nord Amèrega de le montagneOra normale de’l nor"
        u8"d Amèrega de le montagneOra d’istà de’l nord Amèrega de le montagneOra de’l PasìfegoOra normale de’l"
        u8" PasìfegoOra d’istà de’l PasìfegoOra de ApiaOra normale de ApiaOra d’istà de ApiaOra de l’ArabiaOra "
        u8"normale de l’ArabiaOra d’istà de l’ArabiaOra de l’ArjentinaOra normale de l’ArjentinaOra d’istà de l"
        u8"’ArjentinaOra de l’Arjentina osidentaleOra normale de l’Arjentina osidentaleOra d’istà de l’Arjentin"
        u8"a osidentaleOra de l’ArmeniaOra normale de l’ArmeniaOra d’istà de l’ArmeniaOra de l’AtlàntegoOra nor"
        u8"male de l’AtlàntegoOra d’istà de l’AtlàntegoOra de l’Australia sentraleOra normale de l’Australia se"
        u8"ntraleOra d’istà de l’Australia sentraleOra de l’Australia sentro osidentaleOra normale de l’Austral"
        u8"ia sentro osidentaleOra d’istà de l’Australia sentro osidentaleOra de l’Australia orientaleOra norma"
        u8"le de l’Australia orientaleOra d’istà de l’Australia orientaleOra de l’Australia osidentaleOra norma"
        u8"le de l’Australia osidentaleOra d’istà de l’Australia osidentaleOra de l’AzerbaijanOra normale de l’"
        u8"AzerbaijanOra d’istà de l’AzerbaijanOra de le AzoreOra normale de le AzoreOra d’istà de le AzoreOra "
        u8"de’l BangladeshOra normale de’l BangladeshOra d’istà de’l BangladeshOra de’l ButanOra de la BoliviaO"
        u8"ra de BraziliaOra normale de BraziliaOra d’istà de BraziliaOra de’l BrunéiOra de Cao VerdoOra normal"
        u8"e de Cao VerdoOra d’istà de Cao VerdoOra de ChamoroOra de le Ìzole CiatemOra normale de le Ìzole Cia"
        u8"temOra d’istà de le Ìzole CiatemOra de’l CileOra normale de’l CileOra d’istà de’l CileOra de la Sina"
        u8"Ora normale de la SinaOra d’istà de la SinaOra de l’Ìzola de NadaleOra de le Ìzole CocosOra de la Co"
        u8"lonbiaOra normale de la ColonbiaOra d’istà de la ColonbiaOra de le Ìzole CookOra normale de le Ìzole"
        u8" CookOra d’istà de le Ìzole CookOra de CubaOra normale de CubaOra d’istà de CubaOra de DavisOra de D"
        u8"umont d’UrvilleOra de’l Timor EstOra de l’Ìzola de PascuaOra normale de l’Ìzola de PascuaOra d’istà "
        u8"de l’Ìzola de PascuaOra de l’ÈcuadorOra de l’Europa sentraleOra normale de l’Europa sentraleOra d’is"
        u8"tà de l’Europa sentraleOra de l’Europa orientaleOra normale de l’Europa orientaleOra d’istà de l’Eur"
        u8"opa orientaleOra de l’Europa stra orientaleOra de l’Europa osidentaleOra normale de l’Europa osident"
        u8"aleOra d’istà de l’Europa osidentaleOra de le Ìzole MalvineOra normale de le Ìzole MalvineOra d’istà"
        u8" de le Ìzole MalvineOra de le Ìzole FijiOra normale de le Ìzole FijiOra d’istà de le Ìzole FijiOra d"
        u8"e la Guyana fransezeOra de le Tere fransezi de’l sud e de l’AntàrtegoOra de le GalàpagosOra de le Ìz"
        u8"ole GambierOra de la JeorjaOra normale de la JeorjaOra d’istà de la JeorjaOra de le Ìzole GilbertOra"
        u8" de’l meridian de GreenwichOra de la Groenlanda orientaleOra normale de la Groenlanda orientaleOra d"
        u8"’istà de la Groenlanda orientaleOra de la Groenlanda osidentaleOra normale de la Groenlanda osidenta"
        u8"leOra d’istà de la Groenlanda osidentaleOra de’l GolfoOra de la GuyanaOra de Hawai e AleutineOra nor"
        u8"male de Hawai e AleutineOra d’istà de Hawai e AleutineOra de Hong KongOra normale de Hong KongOra d’"
        u8"istà de Hong KongOra de HovdOra normale de HovdOra d’istà de HovdOra de l’IndiaOra de l’Osèano India"
        u8"nOra de l’IndosinaOra de l’Indonezia sentraleOra de l’Indonezia orientaleOra de l’Indonezia osidenta"
        u8"leOra de l’IranOra normale de l’IranOra d’istà de l’IranOra de IrkutskOra normale de IrkutskOra d’is"
        u8"tà de IrkutskOra de IzraeleOra normale de IzraeleOra d’istà de IzraeleOra de’l JaponOra normale de’l"
        u8" JaponOra d’istà de’l JaponOra de’l KazakistanOra de’l Kazakistan orientaleOra de’l Kazakistan oside"
        u8"ntaleOra de la CorèaOra normale de la CorèaOra d’istà de la CorèaOra de l’Ìzola KosraeOra de Krasnoy"
        u8"arskOra normale de KrasnoyarskOra d’istà de KrasnoyarskOra de’l KirghizistanOra de le Ìzole Ecuatori"
        u8"aliOra de l’Ìzola Lord HoweOra normale de l’Ìzola Lord HoweOra d’istà de l’Ìzola Lord HoweOra de Mag"
        u8"adanOra normale de MagadanOra d’istà de MagadanOra de la MaleziaOra de le Ìzole MaldiveOra de le Ìzo"
        u8"le MarcheziOra de le Ìzole MarshallOra de le Ìzole MaurisioOra normale de le Ìzole MaurisioOra d’ist"
        u8"à de le Ìzole MaurisioOra de MawsonOra de’l Mèsego de’l PasìfegoOra normale de’l Mèsego de’l Pasìfeg"
        u8"oOra d’istà de’l Mèsego de’l PasìfegoOra de Ulan BàtorOra normale de Ulan BàtorOra d’istà de Ulan Bà"
        u8"torOra de MoscaOra normale de MoscaOra d’istà de MoscaOra de Myanmar (Birmania)Ora de l’Ìzola NauruO"
        u8"ra de’l NepalOra de la Nova CaledoniaOra normale de la Nova CaledoniaOra d’istà de la Nova Caledonia"
        u8"Ora de la Nova ZelandaOra normale de la Nova ZelandaOra d’istà de la Nova ZelandaOra de TeranovaOra "
        u8"normale de TeranovaOra d’istà de TeranovaOra de l’Ìzola NiueOra de l’Ìzola NorfolkOra normale de l’Ì"
        u8"zola NorfolkOra d’istà de l’Ìzola NorfolkOra de Fernando de NoronhaOra normale de Fernando de Noronh"
        u8"aOra d’istà de Fernando de NoronhaOra de NovosibirskOra normale de NovosibirskOra d’istà de Novosibi"
        u8"rskOra de OmskOra normale de OmskOra d’istà de OmskOra de’l PakistanOra normale de’l PakistanOra d’i"
        u8"stà de’l PakistanOra de le Ìzole PalàuOra de la Papua Nova GuinèaOra de’l ParaguàiOra normale de’l P"
        u8"araguàiOra d’istà de’l ParaguàiOra de’l PerùOra normale de’l PerùOra d’istà de’l PerùOra de le Ìzole"
        u8" FilipineOra normale de le Ìzole FilipineOra d’istà de le Ìzole FilipineOra de le Ìzole FenizeOra de"
        u8" S. Piero e MichelonOra normale de S. Piero e MichelonOra d’istà de S. Piero e MichelonOra de le Ìzo"
        u8"le PitcairnOra de l’Ìzola PonpèiOra de PyongyangOra de l’Ìzola ReunionOra de RotheraOra de SakalinOr"
        u8"a normale de SakalinOra d’istà de SakalinOra de le Ìzole SamòaOra normale de le Ìzole SamòaOra d’ist"
        u8"à de le Ìzole SamòaOra d’istà de le Ìzole SeiselOra de SingaporeOra de le Ìzole SalomonOra de la Geo"
        u8"rgia de’l sudOra de’l SurinameOra de SyowaOra de l’Ìzola TaitiOra de TaipéiOra normale de TaipéiOra "
        u8"d’istà de TaipéiOra de’l TajikistanOra de le Ìzole TokelàuOra de le Ìzole TongaOra normale de le Ìzo"
        u8"le TongaOra d’istà de le Ìzole TongaOra de’l ChuukOra de’l TurkmenistanOra normale de’l Turkmenistan"
        u8"Ora d’istà de’l TurkmenistanOra de le Ìzole TuvaluOra de l’UruguàiOra normale de l’UruguàiOra d’istà"
        u8" de l’UruguàiOra de l’UzbekistanOra normale de l’UzbekistanOra d’istà de l’UzbekistanOra de le Ìzole"
        u8" VanuatuOra normale de le Ìzole VanuatuOra d’istà de le Ìzole VanuatuOra de’l VenesuelaOra de Vladiv"
        u8"ostokOra normale de VladivostokOra d’istà de VladivostokOra de VolgogradoOra normale de VolgogradoOr"
        u8"a d’istà de VolgogradoOra de VostokOra de l’Atolo WakeOra de le Ìzole Wallis e FutunaOra de YakutskO"
        u8"ra normale de YakutskOra d’istà de YakutskOra de EkaterinburgoOra normale de EkaterinburgoOra d’istà"
        u8" de EkaterinburgoOra de’l Yukon{0} ({1}){0}, {1}Ora {0}Ora normale {0}Ora d’istà {0}{1} ({0}){0}"
        u8"\u202F{1}";
    inline constexpr const char8_t* NameChunks[] = {NameChunk0};
    inline constexpr uint16_t NameChunkSizes[] = {23220};
    inline constexpr char NameRefsChunk0[] =
        "AAAAAAAAAAAEAAAKAAARAAAYAAAeAAAlAAAqAAAuAAAyAAA6AABMAABUAABdAABiAABoAAB3AAB9AACUAACeAAClAACxAAC4AAC7"
        "AADDAADLAADTAADYAADdAADnAADuAAD0AAD8AAEAAAEIAAENAAETAAEXAAEfAAEnAAE4AAE/AAFGAAFKAAFRAAFVAAFcAAFjAAFp"
        "AAFwAAF4AAF8AAGFAAGJAAGRAAGVAAGcAAGgAAGmAAGrAAGxAAG2AAG8AAHAAAHHAAHOAAHSAAHaAAHiAAHpAAHuAAH2AAIEAAIN"
        "AAISAAIXAAIpAAI7AAJOAAJXAAJvAAJzAAKEAAKSAAKZAAKfAAKlAAKrAAKxAAK2AAK9AALPAALkAALqAALvAAL0AAL/AAMEAAMN"
        "AAMWAAMdAAMjAAMnAAMqAAMuAAM0AAM5AANAAANSAANiAAN0AAODAAOMAAOUAAOcAAOhAAOnAAOuAAOyAAO2AAO/AAPGAAPLAAPS"
        "AAPVAAPdAAPuAAP/AAQFAAQbAAQhAAQ0AAQ9AAQ/AARPAARTAARdAARlAARtAAR2AASGAASOAASSAASYAAShAASmAASrAASyAATD"
        "AATLAATQAATZAATdAATmAATrAAT2AAT9AAUFAAUJAAUTAAUYAAUeAAUpAAUtAAUzAAU9AAVIAAVMAAVZAAV2AAV8AAWCAAWFAAWO"
        "AAWVAAWeAAWmAAWsAAWyAAW5AAXBAAXIAAXTAAXYAAXeAAXhAAXmAAXvAAXzAAX6AAYEAAYLAAYPAAYXAAYcAAYmAAYsAAY0AAY6"
        "AAY+AAZJAAZRAAZZAAZhAAZpAAZvAAZ2AAZ7AAaBAAaRAAaZAAaeAAamAAauAAazAAa8AAbBAAbGAAbKAAbSAAbaAAbeAAbmAAbr"
        "AAbyAAb3AAcEAAcMAAcRAAccAAcjAAcpAAcvAAc0AAc8AAdDAAdGAAdcAAdgAAdyAAd3AAd9AAeGAAeSAAecAAehAAenAAerAAev"
        "AAe2AAe+AAfEAAfMAAfTAAfZAAffAAfkAAfoAAfxAAf4AAf9AAgBAAgLAAgTAAgYAAgeAAgpAAgyAAg8AAhEAAhLAAhUAAhaAAhe"
        "AAhkAAhqAAhxAAh4AAiDAAiHAAiQAAiWAAicAAinAAiuAAi3AAi7AAjLAAjeAAjqAAj2AAj+AAkEAAkKAAkOAAkUAAkcAAkkAAkq"
        "AAk7AAlDAAlMAAlSAAlYAAlqAAl8AAmAAAmGAAmLAAmTAAmZAAmvAAm+AAnGAAnXAAnfAAnkAAnpAAnxAAn2AAn9AAoHAAoPAAoZ"
        "AAogAAovAAo0AAo6AApOAApVAApbAAplAAp6AAqNAAqUAAqYAAqhAAqoAAqyAAq4AAq/AArHAArMAArRAArYAArdAArhAArnAAry"
        "AAr1AAr/AAsGAAsMAAsTAAsaAAshAAsmAAsrAAszAAs6AAs/AAtQAAtiAAtmAAt0AAt5AAuBAAuFAAuOAAuUAAubAAuiAAuoAAu/"
        "AAvFAAvVAAvlAAvxAAv7AAwAAAwIAAwPAAwXAAwcAAwoAAwtAAwxAAxBAAxOAAxXAAxdAAxkAAxqAAx9AAyFAAyNAAyVAAyaAAyu"
        "AAy0AAy5AAy9AAzDAAzKAAzQAAzaAAzgAAzoAAzuAAz2AAz9AA0EAA0KAA0QAA0ZAA0iAA0nAA0tAA00AA06AA1BAA1XAA1eAA1m"
        "AA1tAA10AA18AA2cAA2jAA2oAA2uAA21AA3IAA3MAA3SAA3XAA3dAA3nAA3tAA31AA36AA3/AA4FAA4MAA4RAA4ZAA4eAA4gAA4m"
        "AA4rAA4xAA41AA48AA5BAA5HAA5NAA5UAA5dAA5hAA6BAA6HAA6LAA6PAA6sAA6yAA63AA6+AA7RAA7jAA7qAA78AA8MAA8dAA8y"
        "AA9CAA9VAA9dAA9yAA96AA+IAA+YAA+qAA+8AA/HAA/QAA/iAA/rAA/vAA/8ABALABARABAhABA1ABBGABBaABBoABB3ABB9ABCR"
        "ABCcABCtABC0ABC7ABDCABDIABDSABDbABDqABDyABD7ABEAABEMABEWABEqABEyABE8ABFBABFNABFWABFcABFjABFoABF2ABF9"
        "ABGEABGLABGhABGoABGvABG0ABHAABHIABHRABHXABHeABH0ABIYABIwABJHABJPABJfABJqABJuABJ2ABJ6ABKCABKWABKaABKk"
        "ABKoABKxABK5ABLJABLOABLUABLcABLoABLuABL3ABMAABMVABMdABMrABMzABM6ABM/ABNQABNYABNeABNlABNzABN7ABODABOH"
        "ABOVABOfABOsABOyABO3ABPCABPJABPPABPeABPmABPqABPzABP9ABQDABQKABQTABQmABQsABRUABRdABRhABRvABR1ABSFABSc"
        "ABSkABSrABSwABS4ABTGABTPABTWABTdABTqABTvABUZABUdABUhABUoABUuABU0ABU8ABVEABVJABVOABVaABVhABVpABV2ABWK"
        "ABWcABWtABWzABXAABXKABXOABXVABXeABXrABX0ABX7ABYBABYJABYTABYaABYfABYlABYsABY0ABY+ABZQABZaABZpABZ+ABaC"
        "ABaUABacABapABbFABbOABbYABbhABbmABb1ABb8ABcCABcJABcSABcbABciABcwABc1ABdDABdKABdTABddABdkABdpABduABdy"
        "ABd+ABeCABeJABeOABegABeyABe6ABfCABfJABfcABfrABf0ABgIABgRABgXABggABglABg4ABhGABhNABhTABhYABheABhsABh6"
        "ABiHABiMABiSABibABirABizABjIABjRABjbABjkABjsABjzABj7ABkEABkZABkkABk6ABk/ABlHABlXABllABlpABmFABmJABmS"
        "ABmcABmkABmtABm5ABnBABnGABnNABneABnkABnqABnyABn5ABn/ABocABooABozABo7ABpFABpMABpjABpsABqHABqfABqmABqt"
        "ABq8ABrCABrPABraABrhABrmABrzABr9ABsDABsKABsbABsgABszABs3ABs/ABtRABtaABtfABtiABtnABtwABt4ABuAABuGABuN"
        "ABuSABu3ABu8ABvAABvIABvRABvWABvkABvsABv1ABwKABwVABwgABwnABw7ABxRABxYABxhABxqABxvABx7AByCAByPAByWAByc"
        "AByoAByvABy+ABzEABzHABzOABzUABzgABzmABzuAB0HAB0SAB0mAB03AB1GAB1VAB1ZAB1hAB1pAB1tAB10AB14AB1+AB2IAB2O"
        "AB2XAB2cAB2gAB2tAB27AB3BAB3GAB3OAB3WAB3cAB3hAB3mAB3tAB32AB3/AB4GAB4RAB4jAB4tAB4xAB40AB47AB5CAB5NAB5Y"
        "AB5xAB55AB59AB6CAB6GAB6NAB6UAB6ZAB6gAB6sAB60AB6/AB7OAB7UAB7qAB74AB7+AB8SAB8nAB8tAB8zAB85AB9AAB9JAB9h"
        "AB9rAB9+AB+FAB+MAB+RAB+ZAB+gAB+uAB+6AB/BAB/IAB/UAB/oAB/7ACANACAVACAaACAgACAtACAzACA7ACBCACBJACBOACBU"
        "ACBaACBgACBkACBsACB2ACB5ACCEACCPACCVACCjACC8ACDCACDEACDVACDcACDwACD1ACD9ACEIACENACEYACEiACEyACFSACFj"
        "ACF1ACGBACGNACGXACGiACGxACHAACHOACHdACHvACICACISACIjACIzACJEACJyACKhACKyACLDACLSACLhACLtACL5ACMKACMb"
        "ACMrACM8ACNNACNeACNuACN/ACOHACOQACOeACOtACO9ACPNACPdACPtACP8ACQLACQZACQnACQ5ACRLACRbACRrACR7ACSMACSb"
        "ACSrACS2ACTCACTNACTYACTnACT3ACUJACUcACUnACUzACVDACVUACVfACVrACV6ACWLACWYACWlACW0ACXEACXTACXjACX0ACYF"
        "ACYTACYhACYuACY8ACZAACZOACZdACZvACaBACaRACahACatACa6ACbFACbQACbkACb4ACcGACcVACcjACczACdGACdZACdpACd5"
        "ACeMACefACewACfBACfOACfcACfrACf7ACgNACgfACgzAChIAChWAChkAChzACiDACiPACicACisACi8ACjMACjdACjuACkAACkM"
        "ACkYACkkACkyAClCAClTAClgACluACl9ACmOACmcACmrACm4ACnGACnXACnpACn6ACoLACobACosACo3ACpDACpUACplACp2ACqH"
        "ACqXACqoACq1ACrDACrSACriACrxACsBACsMACsXACslACszACtEACtVACtgACtsACt7ACuKACuYACunACu2ACvGACvXACvoACv5"
        "ACwKACwZACwpACw2ACxEACxTACxjACx1ACyIACyYACypACy4ACzHACzbACzvACz/AC0PAC0eAC0tAC1BAC1VAC1hAC1tAC19AC2N"
        "AC2bAC2qAC24AC3GAC3TAC3hAC3xAC4BAC4NAC4aAC4tAC5BAC5OAC5cAC5lAC5vAC58AC6JAC6TAC6dAC6sAC68AC7IAC7UAC7m"
        "AC74AC8IAC8YAC8pAC86AC9IAC9WAC9pAC99AC+WAC+vAC+/AC/QAC/dAC/rAC/9ADAPADAkADA5ADBXADBnADB3ADCIADCaADCo"
        "ADC2ADDHADDZADDrADD+ADENADEdADEsADE8ADFGADFRADFtADGJADGfADG1ADHEADHUADHiADHwADH+ADINADIcADIsADI7ADJL"
        "ADJZADJoADJ7ADKPADKeADKtADK7ADLKADLVADLhADMDADMmADM4ADNLADNvADOUADOeADOpADO7ADPPADPcADPpADP4ADQIADQW"
        "ADQlADQ+ADRBADRSADRYADReADRmADRyADR6ADSFADSKADSTADSbADSrADS7ADS/ADTFADTOADTXADThADTqADTxADT9ADUFADUM"
        "ADUfADUkADUsADU4ADVCADVJADVPADVVADVlADV1ADV6ADWBADWKADWRADWaADWjADWoADWxADW7ADXBADXLADXQADXYADXfADXl"
        "ADXrADX1ADYBADYPADYcADYiADYoADZAADZHADZNADZRADZaADZhADZmADZ4ADZ+ADaNADaUADarADa1ADa8ADbCADbIADbPADbX"
        "ADbbADbfADblADbtADb9ADcKADcWADcaADcgADcmADcrADcyADc4ADdBADdKADdQADdYADdfADdlADdtADd3ADeAADePADeaADeg"
        "ADeuADe2ADfEADfLADfbADfjADf3ADf9ADgJADgQADgaADgeADgnADgzADg+ADhLADhSADheADhtADh7ADiIADibADijADirADi6"
        "ADjGADjVADjcADjkADjsADj0ADkAADkFADkPADkXADkgADkuADk7ADlGADlKADlSADlZADliADlwADl5ADmAADmEADmWADmbADmh"
        "ADmpADm4ADnAADnKADnSADniADnpADnwADn2ADn7ADoDADoQADoXADoeADouADo3ADpGADpUADpbADpnADprADp3ADp+ADqKADqU"
        "ADqgADqnADq7ADrSADrmADr5ADsNADsgADsuADs/ADtQADtdADtsADuBADuLADuSADudADulADuuADu6ADvHADvZADvhADvlADv1"
        "ADv7ADwCADwaADwlADw7ADxWADxyADyQADytADzSADz5AD0KAD0jAD0+AD1RAD1sAD2JAD2qAD3TAD3+AD4gAD5KAD52AD6dAD7M"
        "AD79AD8RAD8tAD9LAD9WAD9pAD9+AD+PAD+oAD/DAD/XAD/zAEARAEAwAEBXAECAAECSAECsAEDIAEDdAED6AEEZAEE2AEFbAEGC"
        "AEGoAEHWAEIGAEIkAEJKAEJyAEKRAEK4AELhAEL2AEMTAEMyAENBAENYAENxAEOGAEOjAEPCAEPSAEPjAEPyAEQJAEQiAEQ0AERE"
        "AERcAER2AESEAESbAES6AETbAETqAEUBAEUaAEUoAEU+AEVWAEVxAEWHAEWZAEWzAEXPAEXkAEYBAEYgAEYrAEY+AEZTAEZfAEZ4"
        "AEaMAEanAEbKAEbvAEcCAEccAEc+AEdiAEd9AEegAEfFAEflAEgBAEglAEhLAEhjAEiDAEilAEi6AEjXAEj2AEkPAElFAElZAElx"
        "AEmBAEmZAEmzAEnLAEnrAEoJAEovAEpXAEp2AEqdAErGAErWAErmAEr9AEscAEs9AEtNAEtlAEt/AEuKAEudAEuyAEvCAEvbAEvu"
        "AEwLAEwpAExIAExXAExuAEyHAEyVAEyrAEzDAEzRAEznAEz/AE0PAE0nAE1BAE1WAE11AE2VAE2lAE29AE3XAE3vAE4BAE4bAE43"
        "AE5OAE5qAE6FAE6oAE7NAE7bAE7xAE8JAE8aAE8yAE9LAE9kAE99AE+eAE/BAE/OAE/xAFAcAFBJAFBbAFB1AFCRAFCdAFCxAFDH"
        "AFDgAFD3AFEHAFEfAFE/AFFhAFF3AFGVAFG1AFHEAFHbAFH0AFIKAFIjAFJEAFJnAFKBAFKjAFLHAFLZAFLzAFMPAFMaAFMtAFNC"
        "AFNVAFNwAFONAFOkAFPAAFPUAFPwAFQOAFQeAFQ2AFRQAFRpAFSKAFStAFTEAFTeAFUAAFUkAFU9AFVWAFVmAFV/AFWNAFWbAFWx"
        "AFXJAFXgAFX/AFYgAFZBAFZRAFZpAFaFAFaYAFakAFa7AFbJAFbfAFb3AFcMAFclAFc7AFdZAFd5AFeJAFegAFe/AFfgAFf3AFgK"
        "AFglAFhCAFhXAFh0AFiTAFirAFjLAFjtAFkBAFkTAFktAFlJAFlaAFlzAFmOAFmbAFmwAFnQAFneAFn0AFoMAFogAFo8AFpaAFpq"
        "AFpzAFp7AFqCAFqRAFqiAFqrAFq0";
    inline constexpr const char* NameRefsChunks[] = {NameRefsChunk0};
    inline constexpr Packed NameRefs{NameRefsChunks, 13, 4};
    inline constexpr Text NameTexts{NameChunks, NameChunkSizes, NameRefs};

    inline constexpr char LanguageKeysChunk0[] =
        "AAhAAiAAmAArAAtAAuAAyAAzAA2AA5AA6ABBABFABHABJABNABOABPABSABTABhABlABoABvABzAB1AB2AB5ACBACFACWACaAClA"
        "CsACuACvACzAC0AC1ADBADGADJADKADPADSADZADhADkADsADuAD1AD2AEBAEFAEJAESAEUAEVAEZAEaAEhAEkAElAEnAEpAEvAE"
        "zAE0AE1AFBAFWAFhAFpAFqAFrAFsAFtAFuAFvAFyAFzAF1AF2AF3AF5AGBAGCAGHAGJAGOAGPAGUAGVAGWAGnAGoAGpAGrAGsAGu"
        "AGyAGzAG0AG5AHBAHCAHEAHFAHHAHMAHOAHPAHSAHWAHZAHjAHtAHyAHzAIBAIMAITAIUAI1AJNAJOAJPAJVAJXAJhAJjAJkAJlA"
        "JnAJpAJrAJsAJtAJuAJvAJxAJyAJzAJ0AJ1AJ2AJ3AKBAKFAKHAKIAKJAKLAKOAKPAKSAKTAKUAKZAKnAKrAKyAK6ALFALJALPAL"
        "hALvAMIAMpAMvANBANIANVARlASBASZATxAUuAWFAWUAXOAXQAYDAZOAZQAZTAZhAZ0AaKAbhAgsAguAgzAitAi3Ai6AjjAjuAkP"
        "AkuAmBAmPAmUApYApzAqnAsuAwkAw5AxoAxwAyiAznA0LA0NA0PA0QA0SA0ZA0jA1iA2DA5HA5KA5LA5MA5NA5SA53BArBAyBA2B"
        "DyBFFBHpBJiBKhBMvBNHBRVBTJBVhBbvBksBnuBpDBpSBqyBwhBy6B0sB3yB53B66B7pCApCA3CA4CEsCGuCHKCJiCKwCKyCRBCR"
        "CCV0CWPCXIChPCjvCmjCwhCwiCwjCwqCwtCxECxnCyFCyhCyuCzPCzwC0BC0RC1qC2OC2iC3rC4FC5DC5MC5VC5iC5mC5oC6tC7r"
        "C8WDAkDAnDC6DEqDEsDF0DGEDGvDH1DH6DJDDJtDKHDKhDKuDKvDKzDK5DQkDQnDQpDQrDQzDSGDSuDSyDTFDToDTvDUODUjDUuD"
        "XJDXlDXoDXzDahDasDazDbsDc2DdODgwDgxDiTDi3DkhDk1DmnDnIDnnDovDpvDqzDsuD1CD1DD1TD1XD1hD5hEAnEAtEAwEA1EB"
        "tEEzEItEJHEajEgqEgwEgyEkHEkmEnmEqwErrEwkEwoEwxEw0ExBExQExuExvEyIEyoEyzE0JE0OE0kE1yE2IE2hE2qE2uE2zE3L"
        "E5OE55E6SE6rE7iE8yE9MFBlFCtFCvFC0FD4FEUFEnFGIFGJFHrFIJFJWFJXFKNFKtFLMFLxFM2FNNFSNFWiFXEFijFm3FquFwlF"
        "wsFwyFxQF61GAsGHSGHnGQ2GRCGZMGalGjoGquGsYGtB";
    inline constexpr const char* LanguageKeysChunks[] = {LanguageKeysChunk0};
    inline constexpr Packed LanguageKeys{LanguageKeysChunks, 13, 3};

    inline constexpr char LanguageNamesChunk0[] =
        "AABAACAAGAAJAAMAANAARAAWAAaAAcAAdAAeAAiAAmAAqAAvAAwAAxAAyAA0AA4AA9ABAABKABRABTABUABVABWABaABiABkABnA"
        "BqABrABwABxAByABzAB1AB3AB4AB6AB7AB9ACDACEACGACJACKACNACPACRACVACWACaACcACdACgAChACiAClACmACnACoACsAC"
        "tACuACvACwAC0AC1ADEADFADGADIADKADMADNADQADUADYADaADbADeADfADiADkADlADrADsADxADzAD5AEDAEGAEIAELAEMAEN"
        "AESAETAEUAEZAEcAEfAEgAEjAElAEoAErAEtAEwAEzAE0AE2AE8AE9AE+AFAAFHAFKAFLAFOAFVAFWAFXAFaAFcAFeAFlAFoAFqA"
        "FtAFwAFyAF0AF2AF7AF9AF+AF/AGBAGDAGFAGHAGIAGNAGPAGTAGVAGXAGZAGcAGdAGgAGjAGkAGpAGtAGuAGxAGyAGzAG1AG3AG"
        "5AG+AHBAHGAHHAHKAHMAHNAADAAEAAFAAHAAIAAKAALAAOAAPAAQAATAAUAAVAAXAAYAAZAAbAAfAAgAAhAAjAAkAAlAAnAAoAAp"
        "AArAAsAAtAAuAAzAA1AA2AA3AA5AA6AA7AA8AA+AA/ABBABCABDABEABFABGABHABIABJABLABMABNABOABPABQABSABXABYABZA"
        "BdABeABfABgABhABjABlABmABoABpAB0AB5AB8ACAACBACCACFACHACIACLACMACOACQACSACTACUACXACYACZACbACeACfACjAC"
        "kACpACqACrACxACyACzAC2AC3AC4AC5AC6AC7AC8AC9AC+AC/ADAADBADCADDADHADJADLADOADPADRADSADTADVADWADXADZADc"
        "ADdADgADhADjADmADnADoADpADqADtADuADvADwADyAD0AD1AD2AD3AD4AD6AD7AD8AD9AD+AD/AEAAEBAECAEEAEFAEHAEJAEKA"
        "EOAEPAEQAERAEVAEWAEXAEYAEaAEbAEdAEeAEhAEkAEmAEnAEqAEsAEuAEvAExAEyAE1AE3AE4AE5AE6AE7AE/AFBAFCAFDAFEAF"
        "FAFGAFIAFJAFPAFQAFRAFSAFTAFUAFZAFbAFdAFfAFgAFhAFiAFjAFkAFmAFnAFpAFrAFsAFuAFvAFxAFzAF1AF3AF4AF5AF6AF8"
        "AGAAGCAGEAGGAGKAGLAGMAGOAGQAGRAGSAGUAGWAGYAGaAGbAGeAGfAGhAGiAGlAGmAGnAGoAGqAGrAGsAGvAGwAG0AG2AG4AG6A"
        "G7AG8AG9AG/AHAAHCAHDAHEAHFAHIAHJAHLAHOAHPAHQ";
    inline constexpr const char* LanguageNamesChunks[] = {LanguageNamesChunk0};
    inline constexpr Packed LanguageNames{LanguageNamesChunks, 13, 3};

    inline constexpr const uint64_t* TaggedKeys = nullptr;

    inline constexpr const uint16_t* TaggedNames = nullptr;

    inline constexpr char RegionKeysChunk0[] =
        "AAeAAfAAgAAhAAiAAkAAnAAoAAqAAsAAtAAuAAvAAwAAyAAzAA1AA3AA4AA6AA7AA8AA9AA+AA/ABAABCABDABEABFABHABIABJA"
        "BKABMABNABPABQABSABUABVABXABYABZABaABcABdABeABfABgABhABiABjABmABnABoABpABqABrABxABzAB2AB3AB5AB7ACGAC"
        "IACKACMACOACPACZACaACbACcAChACrACsACtACvACxAC0AC+AC/ADBADCADDADEADFADGADJADKADLADNADOADPADQADRADSADU"
        "ADWADjADlADmADqADsADtAD2AD3AD4AD/AEAAEBAECAEEAEFAEGAEHAETAEbAEdAEeAEuAEwAExAEyAE2AE3AE5AE7AFAAFCAFDA"
        "FFAFGAFHAFNAFPAFWAFXAFYAFZAFaAFdAFgAFiAFjAFkAFlAFmAFnAFqAFrAFsAFtAFuAFvAFwAFxAFyAFzAF0AF1AF2AF3AF4AF"
        "5AF7AF9AF/AGAAGBAGDAGGAGJAGKAGMAGPAGUAGiAGxAG1AG2AG3AG4AG7AG8AG9AG+AHCAHDAHEAHHAHJAHMAHaAHrAH1AH5AH7"
        "AH9AICAIDAIEAIFAIGAIIAIJAIKAILAIMAINAIOAIPAIQAITAIUAIVAIXAIZAIaAIbAIdAIfAIgAIiAIjAIkAImAInAIoAIpAIqA"
        "IrAIuAIwAIyAIzAI2AI4AI+AJEAJFAJKAJQAJRAJTAJVAJXAJZAJbAJgAJnAJzAKAAKJAKKAKTAKoAK3AK/ALLALVALYALaALbAL"
        "cALeALiALkALmALnALoALqALrALsALuAL2AL3AL7AL8AMAAMOAMPAMSAMWANnANoANqANvANwANzAN0AOjAR8";
    inline constexpr const char* RegionKeysChunks[] = {RegionKeysChunk0};
    inline constexpr Packed RegionKeys{RegionKeysChunks, 13, 3};

    inline constexpr char RegionNamesChunk0[] =
        "AHwAHxAHyAHzAH0AH1AH2AH3AH4AH5AH6AH7AH8AH9AH+AH/AIAAIBAICAIDAIEAIFAIGAIHAIIAIJAIKAILAIMAINAIOAIPAIQA"
        "IRAISAITAIUAIVAIWAIXAIYAIZAIaAIbAIcAIdAIeAIfAIgAIhAIiAIjAIkAIlAImAInAIoAIpAIqAIrAIsAItAIuAIvAIwAIxAI"
        "yAIzAI0AI1AI2AI3AI4AI5AI6AI7AI8AI9AI+AI/AJAAJBAJCAJDAJEAJFAJGAJHAJIAJJAJKAJLAJMAJNAJOAJPAJQAJRAJSAJT"
        "AJUAJVAJWAJXAJYAJZAJaAJbAJcAJdAJeAJfAJgAJhAJiAJjAJkAJlAJmAJnAJoAJpAJqAJrAJsAJtAJuAJvAJwAJxAJyAJzAJ0A"
        "J1AJ2AJ3AJ4AJ5AJ6AJ7AJ8AJ9AJ+AJ/AKAAKBAKCAKDAKEAKFAKGAKHAKIAKJAKKAKLAKMAKNAKOAKPAKQAKRAKSAKTAKUAKVAK"
        "WAKXAKYAKZAKaAKbAKcAKdAKeAKfAKgAKhAKiAKjAKkAKlAKmAKnAKoAKpAKqAKrAKsAKtAKuAKvAKwAKxAKyAKzAK0AK1AK2AK3"
        "AK4AK5AK6AK7AK8AK9AK+AK/ALAALBALCALDALEALFALGALHALIALJALKALLALMALNALOALPALQALRALSALTALUALVALWALXALYA"
        "LZALaALbALcALdALeALfALgALhALiALjALkALlALmALnALoALpALqALrALsALtALuALvALwALxALyALzAL0AL1AL2AL3AHRAHSAH"
        "TAHUAHVAHWAHXAHYAHZAHaAHbAHcAHdAHeAHfAHgAHhAHiAHjAHkAHlAHmAHnAHoAHpAHqAHrAHsAHtAHuAHv";
    inline constexpr const char* RegionNamesChunks[] = {RegionNamesChunk0};
    inline constexpr Packed RegionNames{RegionNamesChunks, 13, 3};

    inline constexpr char ScriptKeysChunk0[] =
        "AJGNAJ0CAKHtAMgiAMguAMmpAMmuANp0AQWJAQW1AQZzAQaLARXHASFzAT4PAUgoAUgpAVTpAVUEAYVtAYXTAYZJAaAtAaCyAaJT"
        "Ab4UAcGuAcJUAeZMAeZTAhbBAiQrAjzyAk5UAlYMAp8wArBBArMtAtEJA4ZBA5XyA7AnA73HA73NA76IA8guA8irA9VSA9VoA9ZV"
        "BAXCBAXHBAXJBAXPBAXTBAXUBAaSBBRSBCZBBDK3BDXHBDXQBEl0BFXHBNAsBQWvBQbBBUAuBYWJBYXBBYbpBaAyBaGyBaHqBaaT"
        "BbiBBb5FBcgpBdEJBgXBBgXvBgaGBgaHBgaOBhYDBiWiBiXBBiXCBiZ1BmRpBmSJBoUKBoVhBoXEBoXJBoZDBpSGBpXEBpZDBpZP"
        "BrMtBryJBr3HBsnvBtCpBtWUBuWyBwTtBwXEBwZCBwg0BxbhBy3vB00VB5wtB7BrB7gvB8loB8shB8zlB82hB9TyCAWNCAajCBZN"
        "CCAnCCGJCCGQCCHYCDJECEqJCIQnCSnHCT0HCVXSCYWyCYZCCYayCZ3XCaA3CaJECaSECaXECaXICbzkCbzvCb5BCb8vCdXECdXV"
        "CeWPCeZDCeZFCeZKCeZOCgTiCgVyCgWFCgWVCgWsCgXHCgbUChWVChnHCh2HCiAhCiApCiRUCiZICjphCjySCj6PClaHCpwyCwUp"
        "CyaIC4ZBC40PDECvDE64DJdJDKUpDQXCDSXIDTaIDU8lDU8tDWMYDWc5DWta";
    inline constexpr const char* ScriptKeysChunks[] = {ScriptKeysChunk0};
    inline constexpr Packed ScriptKeys{ScriptKeysChunks, 13, 4};

    inline constexpr char ScriptNamesChunk0[] =
        "AL4AL5AL6AARAL7AL8ACgAL9AAgAL+AL/AMAAMBAMCAMDAMEAMFAA2AMGAA8AMHAMIAMJAMKAMLAMMAMNAMOAMPAMQAMRAMSABfA"
        "MTAMUAMVAMWAMXAMYAMZAC1AMaAMbAMcAMdAMeABqACNAMfAMgAMhAMiAMjAMkAMlAMmAMnACVAMoAMpAMqAMrAMsAMtAMuAMvAC"
        "0ACwAMwAMxAMyAMzAM0AM1AM2AM3ADNAM4AM5AM6ADsAM7AM8ADfAM9AM+AM/ANAANBANCANDANEAD9ANFANGANHANIAEAANJANK"
        "AEMANLAENANMANNANOAEZANPANQANRANSANTAEvANUANVANWANXANYAE9AE/ANZANaANbANcANdANeANfANgANhANiANjANkANlA"
        "NmANnANoANpANqANrANsANtANuANvAFwANwANxANyANzAGFAN0AN1AGLAN2AN3AN4AN5AN6AN7AN8AGNAN9AN+AGPAN/AOAAOBAG"
        "VAAxAOCAODAOEAOFAOGAOHAOIAOJAOKAOLAOMAONAOOAOPAOQAORAOSAOTAOUAOVAOWAOX";
    inline constexpr const char* ScriptNamesChunks[] = {ScriptNamesChunk0};
    inline constexpr Packed ScriptNames{ScriptNamesChunks, 13, 3};

    inline constexpr char AloneKeysChunk0[] =
        "BAXTBAXU";
    inline constexpr const char* AloneKeysChunks[] = {AloneKeysChunk0};
    inline constexpr Packed AloneKeys{AloneKeysChunks, 13, 4};

    inline constexpr char AloneNamesChunk0[] =
        "AOYAOZ";
    inline constexpr const char* AloneNamesChunks[] = {AloneNamesChunk0};
    inline constexpr Packed AloneNames{AloneNamesChunks, 13, 3};

    inline constexpr char CurrencyKeysChunk0[] =
        "ASkATOAWMAWkAXhAZTAakAbnAdOAgtAhEAiUAjuAkEAkmAmkAnEAniApMApkAqOArwAsuAtEAwkAyGA0GA2QA3ZA3wA5DA6wA7FA"
        "9LBFGBFrBHwBNEBTwBZOBaCBayBlEBlwBxQBysB0TB0wB2kB3GB6RB8kCFkCHMCKHCKmCSSCWTCXSCYkCZSCZrCmkCnkCoZCyzCz"
        "zC0SC2mC4XC5XC7kC8kC9UDArDBQDFyDJEDJsDMkDQkDSMDThDVkDWrDXUDXwDZVDayDbSDbrDcODcyDdODgkDjuDkvDnrDoSDtE"
        "D2yEAiECuEDrEEQEFyEGOEMnEQyEnuEpkEqiErmEwyExEExyEyHEyrEzkE0QE2FE3zE5EE5wE6OE8wE9MFECFFTFG0FHEFHwFJZF"
        "KEFLkFNTFQoFT4FZkFc1FdTFizFnEFq2F50GAmGBkGHmGIGGMYGSyGgyGm3";
    inline constexpr const char* CurrencyKeysChunks[] = {CurrencyKeysChunk0};
    inline constexpr Packed CurrencyKeys{CurrencyKeysChunks, 13, 3};

    inline constexpr char CurrencyNamesChunk0[] =
        "AOaAAAAAAAAAAAAAAAAAAAObAAAAObAAAAAAAAAAOcAOdAAAAOdAAAAAAAAAAOeAOfAAAAOfAAAAAAAAAAOgAOhAAAAOhAAAAAAA"
        "AAAOiAOjAAAAOjAAAAAAAAAAOkAOlAAAAOlAAAAAAAAAAOmAOnAAAAOnAAAAAAAAAAOoAOpAAAAOpAAAAAAAAAAOqAOrAAAAOrAA"
        "AAAAAAAAOsAOtAAAAOtAAAAAAAAAAOuAOvAAAAOvAAAAAAAAAAOwAOxAAAAOxAAAAAAAAAAOyAOzAAAAOzAAAAAAAAAAO0AO1AAA"
        "AO1AAAAAAAAAAO2AO3AAAAO3AAAAAAAAAAO4AO5AAAAO5AAAAAAAAAAO6AO7AAAAO7AAAAAAAAAAO8AO9AAAAO9AAAAAAAAAAO+A"
        "O/AAAAO/AAAAAAAAAAPAAPBAAAAPBAAAAAAAAAAPCAPDAAAAPDAAAAAAAAAAPEAPFAAAAPFAAAAAAAAAAPGAPHAAAAPHAAAAAAAA"
        "AAPIAPJAAAAPJAAAAAAAAAAPKAPLAAAAPLAAAAAAAAAAPMAPNAAAAPNAAAAAAAAAAPOAPPAAAAPPAAAAAAAAAAPQAPRAAAAPRAAA"
        "AAAAAAAPSAPTAAAAPTAAAAAAAAAAPUAPVAAAAPVAAAAAAAAAAPWAPXAAAAPXAAAAAAAAAAPYAPZAAAAPZAAAAAAAAAAPaAPbAAAA"
        "PbAAAAAAAAAAPcAPdAAAAPdAAAAAAAAAAPeAPfAAAAPfAAAAAAAAAAPgAPhAAAAPhAAAAAAAAAAPiAPjAAAAPjAAAAAAAAAAPkAP"
        "lAAAAPlAAAAAAAAAAPmAPnAAAAPnAAAAAAAAAAPoAPpAAAAPpAAAAAAAAAAPqAPrAAAAAAAAAAAAAAAAAAAPsAAAAPsAAAAAAAAA"
        "APtAPuAAAAPuAAAAAAAAAAPvAPwAAAAPwAAAAAAAAAAPxAPyAAAAPyAAAAAAAAAAPzAP0AAAAP0AAAAAAAAAAP1AP2AAAAP2AAAA"
        "AAAAAAP3AP4AAAAP4AAAAAAAAAAP5AP6AAAAP6AAAAAAAAAAP7AP8AAAAP8AAAAAAAAAAP9AP+AAAAP+AAAAAAAAAAP/AQAAAAAQ"
        "AAAAAAAAAAAQBAQCAAAAQCAAAAAAAAAAQDAQEAAAAQEAAAAAAAAAAQFAQGAAAAQGAAAAAAAAAAQHAQIAAAAQIAAAAAAAAAAQJAQK"
        "AAAAQKAAAAAAAAAAQLAQMAAAAQMAAAAAAAAAAQNAQOAAAAQOAAAAAAAAAAQPAQQAAAAQQAAAAAAAAAAQRAQSAAAAQSAAAAAAAAAA"
        "QTAQUAAAAQUAAAAAAAAAAQVAQWAAAAQWAAAAAAAAAAQXAQYAAAAQYAAAAAAAAAAQZAQaAAAAQaAAAAAAAAAAQbAQcAAAAQcAAAAA"
        "AAAAAQdAQeAAAAQeAAAAAAAAAAQfAQgAAAAQgAAAAAAAAAAQhAQiAAAAQiAAAAAAAAAAQjAQkAAAAQkAAAAAAAAAAQlAQmAAAAQm"
        "AAAAAAAAAAQnAQoAAAAQoAAAAAAAAAAQpAQqAAAAQqAAAAAAAAAAQrAQsAAAAQsAAAAAAAAAAQtAQuAAAAQuAAAAAAAAAAQvAQwA"
        "AAAQwAAAAAAAAAAQxAQyAAAAQyAAAAAAAAAAQzAQ0AAAAQ0AAAAAAAAAAQ1AQ2AAAAQ2AAAAAAAAAAQ3AQ4AAAAQ4AAAAAAAAAAQ"
        "5AQ6AAAAQ6AAAAAAAAAAQ7AQ8AAAAQ8AAAAAAAAAAQ9AQ+AAAAQ+AAAAAAAAAAQ/ARAAAAARAAAAAAAAAAARBARCAAAARCAAAAAA"
        "AAAARDAREAAAAREAAAAAAAAAARFARGAAAARGAAAAAAAAAARHARIAAAARIAAAAAAAAAARJARKAAAARKAAAAAAAAAARLARMAAAARMA"
        "AAAAAAAAARNAROAAAAROAAAAAAAAAARPARQAAAARQAAAAAAAAAARRARSAAAARSAAAAAAAAAARTARUAAAARUAAAAAAAAAARVARWAA"
        "AARWAAAAAAAAAARXARYAAAARYAAAAAAAAAARZARaAAAARaAAAAAAAAAARbARcAAAARcAAAAAAAAAARdAReAAAAReAAAAAAAAAARf"
        "ARgAAAARgAAAAAAAAAARhARiAAAARiAAAAAAAAAARjARkAAAARkAAAAAAAAAARlARmAAAARmAAAAAAAAAARnARoAAAARoAAAAAAA"
        "AAARpARqAAAARqAAAAAAAAAARrARsAAAARsAAAAAAAAAARtARuAAAARuAAAAAAAAAARvARwAAAARwAAAAAAAAAARxARyAAAARyAA"
        "AAAAAAAARzAR0AAAAR0AAAAAAAAAAR1AR2AAAAR2AAAAAAAAAAR3AR4AAAAR4AAAAAAAAAAR5AR6AAAAR6AAAAAAAAAAR7AR8AAA"
        "AR8AAAAAAAAAAR9AR+AAAAR+AAAAAAAAAAR/ASAAAAASAAAAAAAAAAASBASCAAAASCAAAAAAAAAASDASEAAAASEAAAAAAAAAASFA"
        "SGAAAASGAAAAAAAAAASHASIAAAASIAAAAAAAAAASJASKAAAASKAAAAAAAAAASLASMAAAASMAAAAAAAAAASNASOAAAASOAAAAAAAA"
        "AASPASQAAAAAAAAAAAAAAAAAAASRAAAASRAAAAAAAAAASSASTAAAASTAAAAAAAAAASUASVAAAASVAAAAAAAAAASWASXAAAASXAAA"
        "AAAAAAASYASZAAAASZAAAAAAAAAASaASbAAAASbAAAAAAAAAAScASdAAAASdAAAAAAAAAASeASfAAAASfAAAAAAAAAASgAShAAAA"
        "ShAAAAAAAAAASiASjAAAASjAAAAAAAAAASkASlAAAASlAAAAAAAAAASmASnAAAASnAAAAAAAAAASoASpAAAASpAAAAAAAAAASqAS"
        "rAAAASrAAAAAAAAAASsAStAAAAStAAAAAAAAAASuASvAAAASvAAAAAAAAAASwASxAAAASxAAAAAAAAAASyASzAAAASzAAAAAAAAA"
        "AS0AS1AAAAS1AAAAAAAAAAS2AS3AAAAS3AAAAAAAAAAS4AS5AAAAS5AAAAAAAAAAS6AS7AAAAS7AAAAAAAAAAS8AS9AAAAS9AAAA"
        "AAAAAAS+AS/AAAAS/AAAAAAAAAATAATBAAAATCAAAAAAAAAATCATDAAAATDAAAAAAAAAATEATFAAAATFAAAAAAAAAATGATHAAAAT"
        "HAAAAAAAAAATI";
    inline constexpr const char* CurrencyNamesChunks[] = {CurrencyNamesChunk0};
    inline constexpr Packed CurrencyNames{CurrencyNamesChunks, 13, 3};

    inline constexpr char ZoneKeysChunk0[] =
        "AAAAABAACAADAAEAAGAAIAALAAMAANAAOAAPAARAASAATAAUAAaAAbAAgAAiAAmAAnAAoAArAAtAAuAAvAAwAAxAAyAA2AA6ABBA"
        "BDABJABNABOABRABSABVABWABXABaABbABfABhABjABoABrABsABxABzAB0AB1AB2AB3AB4AB5AB6AB9ACAACEACGACHACLACQAC"
        "SACTACVACXACbACcACdACeACgACjACkACmACwACxACzAC0AC1AC2AC3AC4AC+ADFADGADQADRADSADTADUADVADWADXADYADdADe"
        "ADfADgADhADiADjADlADmADnADvADxADzAD0AD1AD2AD5AD7AD9AD/AECAEDAEGAEHAEIAEJAEKAELAEMAENAEOAEPAERAESAETA"
        "EUAEVAEWAEZAEaAEbAEcAEfAEgAEhAEjAEkAElAEmAEnAEoAEpAErAEsAEyAFRAFSAFTAFUAFVAFWAFXAFZAFaAFbAFdAFfAFgAF"
        "hAFkAFlAFnAFoAFqAFrAFsAFtAFyAFzAF0AF1AF2AF3AF5AF7AF+AGBAGCAGDAGEAGGAGHAGJAGKAGMAGOAGPAGQAGRAGTAGUAGV"
        "AGWAGXAGaAGbAGcAGdAGfAGhAGiAGjAGkAGnAGoAGpAGrAGsAGtAGuAGvAGwAGxAGyAGzAG0AG1AG2AG3AG4AG5AG6AG7AG8AG9";
    inline constexpr const char* ZoneKeysChunks[] = {ZoneKeysChunk0};
    inline constexpr Packed ZoneKeys{ZoneKeysChunks, 13, 3};

    inline constexpr char ZoneNamesChunk0[] =
        "AToAAAAAAAAAAAAAAAAAAAUEAAAAAAAAAAAAAAAAAAAT7AAAAAAAAAAAAAAAAAAAT0AAAAAAAAAAAAAAAAAAAT5AAAAAAAAAAAAA"
        "AAAAAATmAAAAAAAAAAAAAAAAAAAUJAAAAAAAAAAAAAAAAAAATaAAAAAAAAAAAAAAAAAAAT3AAAAAAAAAAAAAAAAAAAUnAAAAAAAA"
        "AAAAAAAAAAAT6AAAAAAAAAAAAAAAAAAAUGAAAAAAAAAAAAAAAAAAAVxAAAAAAAAAAAAAAAAAAAItAAAAAAAAAAAAAAAAAAATrAAA"
        "AAAAAAAAAAAAAAAAT4AAAAAAAAAAAAAAAAAAAV0AAAAAAAAAAAAAAAAAAAVdAAAAAAAAAAAAAAAAAAAVnAAAAAAAAAAAAAAAAAAA"
        "TlAAAAAAAAAAAAAAAAAAAUlAAAAAAAAAAAAAAAAAAAVlAAAAAAAAAAAAAAAAAAAViAAAAAAAAAAAAAAAAAAAVmAAAAAAAAAAAAAA"
        "AAAAAUtAAAAAAAAAAAAAAAAAAATZAAAAAAAAAAAAAAAAAAATbAAAAAAAAAAAAAAAAAAAVjAAAAAAAAAAAAAAAAAAAUmAAAAAAAAA"
        "AAAAAAAAAAVrAAAAAAAAAAAAAAAAAAAH1AAAAAAAAAAAAAAAAAAATPAAAAAAAAAAAAAAAAAAAVIAAAAAAAAAAAAAAAAAAAUwAAAA"
        "AAAAAAAAAAAAAAATuAAAAAAAAAAAAAAAAAAATeAAAAAAAAAAAAAAAAAAAUzAAAAAAAAAAAAAAAAAAAUDAAAAAAAAAAAAAAAAAAAU"
        "bAAAAAAAAAAAAAAAAAAAUvAAAAAAAAAAAAAAAAAAAWNAAAAAAAAAAAAAAAAAAATQAAAAAAAAAAAAAAAAAAATdAAAAAAAAAAAAAAA"
        "AAAAInAAAAAAAAAAAAAAAAAAAV4AAAAAAAAAAAAAAAAAAAIvAAAAAAAAAAAAAAAAAAATcAAAAAAAAAAAAAAAAAAAWOAAAAAAAAAA"
        "AAAAAAAAAJEAAAAAAAAAAAAAAAAAAAJNAAAAAAAAAAAAAAAAAAATvAAAAAAAAAAAAAAAAAAAV/AAAAAAAAAAAAAAAAAAAWBAAAAA"
        "AAAAAAAAAAAAAAV9AAAAAAAAAAAAAAAAAAAV+AAAAAAAAAAAAAAAAAAAWDAAAAAAAAAAAAAAAAAAAV8AAAAAAAAAAAAAAAAAAAWA"
        "AAAAAAAAAAAAAAAAAAAWCAAAAAAAAAAAAAAAAAAAJnAAAAAAAAAAAAAAAAAAAWEAAAAAAAAAAAAAAAAAAAV3AAAAAAAAAAAAAAAA"
        "AAAWSAAAAAAAAAAAAAAAAAAATgAAAAAAAAAAAAAAAAAAAKNAAAAAAAAAAAAAAAAAAAWRAAAAAAAAAAAAAAAAAAAUyAAAAAAAAAAA"
        "AAAAAAAAVDAAAAAAAAAAAAAAAAAAAUxAAAAAAAAAAAAAAAAAAAKPAAAAAAAAAAAAAAAAAAAThAAAAAAAAAAAAAAAAAAAV5AAAAAA"
        "AAAAAAAAAAAAAV7AAAAAAAAAAAAAAAAAAAV6AAAAAAAAAAAAAAAAAAAKkAAAAAAAAAAAAAAAAAAAUKAAAAAAAAAAAAAAAAAAAVuA"
        "AAAAAAAAAAAAAAAAAAKtAAAAAAAAAAAAAAAAAAATfAAAAAAAAAAAAAAAAAAAWPAAAAAAAAAAAAAAAAAAAIKAAAAAAAAAAAAAAAAA"
        "AATjAAAAAAAAAAAAAAAAAAAUZAAAAAAAAAAAAAAAAAAAJ3AAAAAAAAAAAAAAAAAAAWJAAAAAAAAAAAAAAAAAAAWHAAAAAAAAAAAA"
        "AAAAAAAWIAAAAAAAAAAAAAAAAAAAWMAAAAAAAAAAAAAAAAAAATVAAAAAAAAAAAAAAAAAAAUiAAAAAAAAAAAAAAAAAAAUUAAAAAAA"
        "AAAAAAAAAAAAVZAAAAAAAAAAAAAAAAAAAUcAAAAAAAAAAAAAAAAAAAUfAAAAAAAAAAAAAAAAAAAVqAAAAAAAAAAAAAAAAAAAUeAA"
        "AAAAAAAAAAAAAAAAAUQAAAAAAAAAAAAAAAAAAAIHAAAAAAAAAAAAAAAAAAAUVAAAAAAAAAAAAAAAAAAAIMAAAAAAAAAAAAAAAAAA"
        "AUOAAAAAAAAAAAAAAAAAAAVTAAAAAAAAAAAAAAAAAAAUkAAAAAAAAAAAAAAAAAAAVkAAAAAAAAAAAAAAAAAAATXAAAAAAAAAAAAA"
        "AAAAAATMAAAAAAAAAAAAAAAAAAAVoAAAAAAAAAAAAAAAAAAATwAAAAAAAAAAAAAAAAAAAUNAAAAAAAAAAAAAAAAAAAVYAAAAAAAA"
        "AAAAAAAAAAAU4AAAAAAAAAAAAAAAAAAAVUAAAAAAAAAAAAAAAAAAAVSAAAAAAAAAAAAAAAAAAAU0AAAAAAAAAAAAAAAAAAAUrAAA"
        "AAAAAAAAAAAAAAAAULAAAAAAAAAAAAAAAAAAAU8AAAAAAAAAAAAAAAAAAAVRAAAAAAAAAAAAAAAAAAAUdAAAAAAAAAAAAAAAAAAA"
        "UWAAAAAAAAAAAAAAAAAAAKyAAAAAAAAAAAAAAAAAAAUgAAAAAAAAAAAAAAAAAAAUhAAAAAAAAAAAAAAAAAAAWQAAAAAAAAAAAAAA"
        "AAAAAVaAAAAAAAAAAAAAAAAAAAWTAAAAAAAAAAAAAAAAAAAVVAAAAAAAAAAAAAAAAAAAWFAAAAAAAAAAAAAAAAAAAUaAAAAAAAAA"
        "AAAAAAAAAATtAAAAAAAAAAAAAAAAAAAVXAAAAAAAAAAAAAAAAAAAVwAAAAAAAAAAAAAAAAAAAWGAAAAAAAAAAAAAAAAAAAUCAAAA"
        "AAAAAAAAAAAAAAAURAAAAAAAAAAAAAAAAAAATiAAAAAAAAAAAAAAAAAAAUqAAAAAAAAAAAAAAAAAAATsAAAAAAAAAAAAAAAAAAAV"
        "WAAAAAAAAAAAAAAAAAAAUjAAAAAAAAAAAAAAAAAAAVQAAAAAAAAAAAAAAAAAAATOAAAAAAAAAAAAAAAAAAAVFAAAAAAAAAAAAAAA"
        "AAAAJbAAAAAAAAAAAAAAAAAAAImAAAAAAAAAAAAAAAAAAAJAAAAAAAAAAAAAAAAAAAAVGAAAAAAAAAAAAAAAAAAAUSAAAAAAAAAA"
        "AAAAAAAAAUIAAAAAAAAAAAAAAAAAAAVfAAAAAAAAAAAAAAAAAAATTAAAAAAAAAAAAAAAAAAATUAAAAAAAAAAAAAAAAAAATWAAAAA"
        "AAAAAAAAAAAAAAAAAAAATJAAAAAAATKAAAATLAAAAAAAAAAAAAAAAAAAU2AAAAAAAAAAAAAAAAAAAHxAAAAAAAAAAAAAAAAAAAVO"
        "AAAAAAAAAAAAAAAAAAAUHAAAAAAAAAAAAAAAAAAAVKAAAAAAAAAAAAAAAAAAAVhAAAAAAAAAAAAAAAAAAATYAAAAAAAAAAAAAAAA"
        "AAAVJAAAAAAAAAAAAAAAAAAATyAAAAAAAAAAAAAAAAAAATzAAAAAAAAAAAAAAAAAAAAAAAAAAAAUMAAAAAAAAAAUFAAAAAAAAAAA"
        "AAAAAAAAJfAAAAAAAAAAAAAAAAAAAVtAAAAAAAAAAAAAAAAAAAVLAAAAAAAAAAAAAAAAAAAVyAAAAAAAAAAAAAAAAAAAVHAAAAAA"
        "AAAAAAAAAAAAAVgAAAAAAAAAAAAAAAAAAAUAAAAAAAAUBAAAAAAAAAAJ9AAAAAAAAAAAAAAAAAAAKBAAAAAAAAAAAAAAAAAAAVMA"
        "AAAAAAAAAAAAAAAAAAU3AAAAAAAAAAAAAAAAAAAT/AAAAAAAAAAAAAAAAAAAUoAAAAAAAAAAAAAAAAAAATxAAAAAAAAAAAAAAAAA"
        "AAUTAAAAAAAAAAAAAAAAAAALEAAAAAAAAAAAAAAAAAAAVzAAAAAAAAAAAAAAAAAAAVeAAAAAAAAAAAAAAAAAAAT2AAAAAAAAAAAA"
        "AAAAAAATNAAAAAAAAAAAAAAAAAAAVPAAAAAAAAAAAAAAAAAAALmAAAAAAAAAAAAAAAAAAATSAAAAAAAAAAAAAAAAAAAVNAAAAAAA"
        "AAAAAAAAAAAAVCAAAAAAAAAAAAAAAAAAATnAAAAAAAAAAAAAAAAAAAUPAAAAAAAAAAAAAAAAAAAIoAAAAAAAAAAAAAAAAAAATkAA"
        "AAAAAAAAAAAAAAAAAJuAAAAAAAAAAAAAAAAAAAVcAAAAAAAAAAAAAAAAAAAUuAAAAAAAAAAAAAAAAAAAKRAAAAAAAAAAAAAAAAAA"
        "ALzAAAAAAAAAAAAAAAAAAAK0AAAAAAAAAAAAAAAAAAAVBAAAAAAAAAAAAAAAAAAAU7AAAAAAAAAAAAAAAAAAATqAAAAAAAAAAAAA"
        "AAAAAAWKAAAAAAAAAAAAAAAAAAAVpAAAAAAAAAAAAAAAAAAAVvAAAAAAAAAAAAAAAAAAAT1AAAAAAAAAAAAAAAAAAAU/AAAAAAAA"
        "AAAAAAAAAAAVbAAAAAAAAAAAAAAAAAAAUXAAAAAAAAAAAAAAAAAAAT+AAAAAAAAAAAAAAAAAAAUpAAAAAAAAAAAAAAAAAAAU+AAA"
        "AAAAAAAAAAAAAAAAV1AAAAAAAAAAAAAAAAAAAU5AAAAAAAAAAAAAAAAAAAU6AAAAAAAAAAAAAAAAAAAKaAAAAAAAAAAAAAAAAAAA"
        "U1AAAAAAAAAAAAAAAAAAATRAAAAAAAAAAAAAAAAAAAKwAAAAAAAAAAAAAAAAAAAVEAAAAAAAAAAAAAAAAAAAT9AAAAAAAAAAAAAA"
        "AAAAAVAAAAAAAAAAAAAAAAAAAATpAAAAAAAAAAAAAAAAAAAUsAAAAAAAAAAAAAAAAAAAU9AAAAAAAAAAAAAAAAAAAUYAAAAAAAAA"
        "AAAAAAAAAAVsAAAAAAAAAAAAAAAAAAAT8AAAAAAAAAAAAAAAAAAAV2AAAAAAAAAAAAAAAAAAAWLAAAAAAAAAAAAAAAAAA";
    inline constexpr const char* ZoneNamesChunks[] = {ZoneNamesChunk0};
    inline constexpr Packed ZoneNames{ZoneNamesChunks, 13, 3};

    inline constexpr char MetaKeysChunk0[] =
        "AABAACAADAAFAAGAAIAALAAMAANAAOAAPAARAAUAAVAAWAAXAAZAAaAAbAAcAAdAAeAAfAAhAAjAAkAAmAAoAApAArAAsAAtAAuA"
        "AvAAwAAxAAyAAzAA1AA3AA6AA7AA8AA9AA+AA/ABAABBABCABDABEABGABHABIABJABKABOABPABRABSABTABUABVABWABXABYAB"
        "ZABaABbABcABeABfABgABjABkABlABnABoABpABsABvABwAByAB0AB1AB2AB3AB4AB5AB6AB7AB8AB9AB+AB/ACAACBACCACDACE"
        "ACFACHACIACKACLACMACNACOACPACQACRACSACTACUACWACXACYACbACcACeACfACgAChACjACkAClACmACpACqACrACtACuACwA"
        "CyACzAC0AC1AC2AC3AC4AC5AC6AC7AC9";
    inline constexpr const char* MetaKeysChunks[] = {MetaKeysChunk0};
    inline constexpr Packed MetaKeys{MetaKeysChunks, 13, 3};

    inline constexpr char MetaNamesChunk0[] =
        "AAAAWUAAAAAAAAAAAAAAAAWVAAAAAAAAAAAAAAAAWWAAAAAAAAAAAAAAAAWXAAAAAAAAAAAAAWYAWZAWaAAAAAAAAAAWbAWcAWdA"
        "AAAAAAAAAWeAWfAWgAAAAAAAAAAWhAWiAWjAAAAAAAAAAWkAWlAWmAAAAAAAAAAWnAWoAWpAAAAAAAAAAWqAWrAWsAAAAAAAAAAW"
        "tAWuAWvAAAAAAAAAAWwAWxAWyAAAAAAAAAAWzAW0AW1AAAAAAAAAAW2AW3AW4AAAAAAAAAAW5AW6AW7AAAAAAAAAAW8AW9AW+AAA"
        "AAAAAAAW/AXAAXBAAAAAAAAAAXCAXDAXEAAAAAAAAAAXFAXGAXHAAAAAAAAAAXIAXJAXKAAAAAAAAAAXLAXMAXNAAAAAAAAAAXOA"
        "XPAXQAAAAAAAAAAXRAXSAXTAAAAAAAAAAAAAXUAAAAAAAAAAAAAAAAXVAAAAAAAAAAAAAXWAXXAXYAAAAAAAAAAAAAXZAAAAAAAA"
        "AAAAAXaAXbAXcAAAAAAAAAAAAAXdAAAAAAAAAAAAAXeAXfAXgAAAAAAAAAAXhAXiAXjAAAAAAAAAAXkAXlAXmAAAAAAAAAAAAAXn"
        "AAAAAAAAAAAAAAAAXoAAAAAAAAAAAAAXpAXqAXrAAAAAAAAAAXsAXtAXuAAAAAAAAAAXvAXwAXxAAAAAAAAAAAAAXyAAAAAAAAAA"
        "AAAAAAXzAAAAAAAAAAAAAAAAX0AAAAAAAAAAAAAX1AX2AX3AAAAAAAAAAAAAX4AAAAAAAAAAAAAX5AX6AX7AAAAAAAAAAX8AX9AX"
        "+AAAAAAAAAAAAAX/AAAAAAAAAAAAAYAAYBAYCAAAAAAAAAAYDAYEAYFAAAAAAAAAAYGAYHAYIAAAAAAAAAAAAAYJAAAAAAAAAAAA"
        "AAAAYKAAAAAAAAAAAAAAAAYRAAAAAAAAAAAAAAAAYLAAAAAAAAAAAAAAAAYMAAAAAAAAAAAAAYNAYOAYPAAAAAAAAAAAAAYQAAAA"
        "AAAAAAAAAYSAYTAYUAAAAAAAAAAYVAYWAYXAAAAAAAAAAAAAYYAAAAAAAAAAAAAAAAYZAAAAAAAAAAAAAYaAYbAYcAAAAAAAAAAY"
        "dAYeAYfAAAAAAAAAAYgAYhAYiAAAAAAAAAAAAAYjAAAAAAAAAAAAAAAAYkAAAAAAAAAAAAAAAAYlAAAAAAAAAAAAAAAAYmAAAAAA"
        "AAAAAAAAAAYnAAAAAAAAAAAAAAAAYoAAAAAAAAAAAAAYpAYqAYrAAAAAAAAAAYsAYtAYuAAAAAAAAAAYvAYwAYxAAAAAAAAAAYyA"
        "YzAY0AAAAAAAAAAAAAY1AAAAAAAAAAAAAAAAY2AAAAAAAAAAAAAAAAY3AAAAAAAAAAAAAY4AY5AY6AAAAAAAAAAAAAY7AAAAAAAA"
        "AAAAAY8AY9AY+AAAAAAAAAAAAAY/AAAAAAAAAAAAAAAAZAAAAAAAAAAAAAAZBAZCAZDAAAAAAAAAAZEAZFAZGAAAAAAAAAAAAAZH"
        "AAAAAAAAAAAAAAAAZIAAAAAAAAAAAAAAAAZJAAAAAAAAAAAAAAAAZKAAAAAAAAAAAAAZLAZMAZNAAAAAAAAAAAAAZOAAAAAAAAAA"
        "AAAZPAZQAZRAAAAAAAAAAZSAZTAZUAAAAAAAAAAZVAZWAZXAAAAAAAAAAAAAZYAAAAAAAAAAAAAAAAZZAAAAAAAAAAAAAAAAZaAA"
        "AAAAAAAAAAAZbAZcAZdAAAAAAAAAAZeAZfAZgAAAAAAAAAAZhAZiAZjAAAAAAAAAAAAAZkAAAAAAAAAAAAAZlAZmAZnAAAAAAAAA"
        "AZoAZpAZqAAAAAAAAAAZrAZsAZtAAAAAAAAAAZuAZvAZwAAAAAAAAAAZxAZyAZzAAAAAAAAAAAAAZ0AAAAAAAAAAAAAAAAZ1AAAA"
        "AAAAAAAAAZ2AZ3AZ4AAAAAAAAAAZ5AZ6AZ7AAAAAAAAAAZ8AZ9AZ+AAAAAAAAAAAAAZ/AAAAAAAAAAAAAaAAaBAaCAAAAAAAAAAA"
        "AAaDAAAAAAAAAAAAAAAAaEAAAAAAAAAAAAAAAAaFAAAAAAAAAAAAAAAAaGAAAAAAAAAAAAAAAAaHAAAAAAAAAAAAAaIAaJAaKAAA"
        "AAAAAAAaLAaMAaNAAAAAAAAAAAAAaOAAAAAAAAAAAAAAAAaPAAAAAAAAAAAAAAAAaQAAAAAAAAAAAAAAAAaRAAAAAAAAAAAAAAAA"
        "aSAAAAAAAAAAAAAAAAaTAAAAAAAAAAAAAAAAaUAAAAAAAAAAAAAaVAaWAaXAAAAAAAAAAAAAaYAAAAAAAAAAAAAAAAaZAAAAAAAA"
        "AAAAAaaAabAacAAAAAAAAAAAAAadAAAAAAAAAAAAAaeAafAagAAAAAAAAAAAAAahAAAAAAAAAAAAAaiAajAakAAAAAAAAAAalAam"
        "AanAAAAAAAAAAaoAapAaqAAAAAAAAAAAAAarAAAAAAAAAAAAAasAatAauAAAAAAAAAAavAawAaxAAAAAAAAAAAAAayAAAAAAAAAA"
        "AAAAAAazAAAAAAAAAAAAAAAAa0AAAAAAAAAAAAAa1Aa2Aa3AAAAAAAAAAa4Aa5Aa6AAAAAAAAAAAAAa7AAAAAAAAAAAA";
    inline constexpr const char* MetaNamesChunks[] = {MetaNamesChunk0};
    inline constexpr Packed MetaNames{MetaNamesChunks, 13, 3};

    inline constexpr uint16_t Formats[] = {
        1724, 1725, 1726, 1727, 1728, 1729, 0, 1730, 0, 0, 0, 1730,
    };

    inline constexpr Table table{
        0x76656300000000, 0,
        NameTexts,
        LanguageKeys, LanguageNames, 448,
        nullptr, Packed{}, 0,
        RegionKeys, RegionNames, 295,
        ScriptKeys, ScriptNames, 190,
        AloneKeys, AloneNames, 2,
        CurrencyKeys, CurrencyNames, 153,
        ZoneKeys, ZoneNames, 233,
        MetaKeys, MetaNames, 144,
        Formats,
    };

    // the table registered when the header is included, once a program
    inline Registration registration{&table};
}
