//------------------------------------------------------------------------------
// SGCL: a C++20 application platform
// Copyright (c) 2022-2026 Sebastian Nibisz
// SPDX-License-Identifier: Apache-2.0
//------------------------------------------------------------------------------
#pragma once

#include "detail/public_suffix_table.h"
#include "../ip.h"
#include "../../core/aliases.h"
#include "../../core/string.h"
#include "../../txt/idna.h"

#include <cstdint>
#include <string>
#include <string_view>

namespace sgcl::net::http {
    // The Public Suffix List (https://publicsuffix.org): the suffixes under
    // which anyone may register a name of their own ("com", "co.uk",
    // "github.io"), so that "example.co.uk" is one site and "co.uk" none.
    // A cookie jar refuses a cookie set for a whole suffix by it; a program
    // asks it which site a host belongs to (Go's x/net/publicsuffix).
    //
    // The list is embedded (detail/public_suffix_table.h, generated by
    // tools/gen_public_suffix.py; MPL-2.0, NOTICE at the root), its rules
    // with "*" and "!" exceptions, of both sections: the ICANN one, and the
    // private one (domains whose owners ask that their subdomains be kept
    // apart: github.io, blogspot.com), which browsers use too. The host is
    // looked up by the list's algorithm: the rule of the most labels that
    // matches, an exception before any, "*" when none does (the last label).
    //
    // A host is taken as a URL gives it: a name in ASCII in any case (lower
    // case is compared), or in Unicode, which is converted to A-labels by
    // IDNA (UTS #46) first; a dot at its end is left out. The answers are in
    // lower case and A-labels. An IP address, an empty name, an empty label
    // or a name IDNA refuses has no suffix: "".
    enum class suffix_rules : uint8_t {
        all,     // both sections, as browsers and Go's publicsuffix
        icann    // the ICANN section alone
    };

    // The public suffix of host: "co.uk" for "www.example.co.uk", "github.io"
    // for "me.github.io", "com" for "com"; "" for no host
    string public_suffix(const string& host, suffix_rules rules = suffix_rules::all) noexcept;

    // The registrable domain (eTLD+1, the "site"): the public suffix and
    // the label before it, "example.co.uk" for "www.example.co.uk"; "" when
    // the host is a public suffix itself, or no host
    string registrable_domain(const string& host, suffix_rules rules = suffix_rules::all) noexcept;

    // Whether host is a public suffix: "co.uk", "github.io", "com", and any
    // name of one label
    bool is_public_suffix(const string& host, suffix_rules rules = suffix_rules::all) noexcept;

    namespace detail {
        // The key at the slot's word, compared with key
        SGCL_INLINE_HOT bool psl_slot_is(uint32_t w, std::string_view key) noexcept {
            if (((w >> 6) & 0xFF) != key.size()) {
                return false;
            }
            const char* name = PslNames[w >> 30] + ((w >> 14) & 0xFFFF);
            return std::string_view(name, key.size()) == key;
        }

        // The six bits of the key at the hash h (FNV-1a 32 of its bytes from
        // the last), or -1 when the list has no such key
        SGCL_INLINE_HOT int psl_bits(std::string_view key, uint32_t h) noexcept {
            uint32_t i = h & (PslSlotCount - 1);
            for (;;) {
                uint32_t w = PslSlots[i];
                if (w == 0) {
                    return -1;
                }
                if (psl_slot_is(w, key)) {
                    return int(w & 63);
                }
                i = (i + 1) & (PslSlotCount - 1);
            }
        }

        // The length in bytes of the public suffix at the end of host, a
        // name in lower-case ASCII without a dot at its end; 0 for an empty
        // host or one whose last label is empty. Each suffix of host, from
        // the last label, is looked up with the hash carried on from the
        // one before; a suffix the list has no key for ends the walk (every
        // parent of a key is a key)
        inline size_t public_suffix_length(std::string_view host, bool icann_only = false) noexcept {
            uint32_t h = 2166136261u;
            size_t best = 0;
            size_t before = 0;           // the length of the suffix one label shorter
            bool wild_above = false;     // "*." under that suffix is a rule
            size_t i = host.size();
            for (;;) {
                size_t j = i;
                while (j > 0 && host[j - 1] != '.') {
                    --j;
                    h = (h ^ uint8_t(host[j])) * 16777619u;
                }
                if (j == i) {
                    return before;   // an empty label: what was found below it
                }
                const size_t len = host.size() - j;
                if (best == 0) {
                    best = len;      // the rule "*": the last label
                }
                int found = psl_bits(host.substr(j), h);
                uint32_t bits = found < 0 ? 0 : uint32_t(found);
                // the private section's three bits counted, or not
                bits = icann_only ? (bits & 7) : ((bits | (bits >> PslPrivateShift)) & 7);
                if (bits & PslException) {
                    return before;   // the exception's suffix: its first label off
                }
                if ((bits & PslRule) || wild_above) {
                    best = len;
                }
                if (found < 0 || j == 0) {
                    return best;
                }
                wild_above = (bits & PslWild) != 0;
                before = len;
                --j;
                h = (h ^ uint8_t('.')) * 16777619u;
                i = j;
            }
        }

        // host as the list compares it: lower-case ASCII, A-labels, no dot
        // at its end; nullopt for an IP address, an empty name or label, or
        // a name IDNA refuses
        inline optional<std::string> psl_host(std::string_view host) noexcept {
            if (!host.empty() && host.back() == '.') {
                host.remove_suffix(1);
            }
            if (host.empty() || host.find(':') != std::string_view::npos || (host.front() == '[' && host.back() == ']')) {
                return nullopt;
            }
            std::string out;
            bool ascii = true;
            for (char c : host) {
                ascii = ascii && uint8_t(c) < 0x80;
            }
            if (ascii) {
                out.assign(host);
                for (auto& c : out) {
                    c = (c >= 'A' && c <= 'Z') ? char(c + 32) : c;
                }
            } else {
                if (host.size() > 4096) {
                    return nullopt;
                }
                auto r = txt::idna::to_ascii(string(host), txt::idna::options::whatwg());
                if (!r) {
                    return nullopt;
                }
                out.assign(r->view());
                if (!out.empty() && out.back() == '.') {
                    out.pop_back();
                }
            }
            if (out.empty() || out.front() == '.' || out.back() == '.' || out.find("..") != std::string::npos) {
                return nullopt;
            }
            // an IPv4 address in any of the forms a URL takes: its last label a number
            size_t last = out.rfind('.');
            std::string_view tail = std::string_view(out).substr(last == std::string::npos ? 0 : last + 1);
            bool number = !tail.empty();
            for (char c : tail) {
                number = number && ((c >= '0' && c <= '9') || c == 'x');
            }
            if (number && tail.front() >= '0' && tail.front() <= '9') {
                return nullopt;
            }
            return out;
        }
    }

    inline string public_suffix(const string& host, suffix_rules rules) noexcept {
        auto h = detail::psl_host(host.view());
        if (!h) {
            return string();
        }
        size_t n = detail::public_suffix_length(*h, rules == suffix_rules::icann);
        return string(std::string_view(*h).substr(h->size() - n));
    }

    inline string registrable_domain(const string& host, suffix_rules rules) noexcept {
        auto h = detail::psl_host(host.view());
        if (!h) {
            return string();
        }
        size_t n = detail::public_suffix_length(*h, rules == suffix_rules::icann);
        if (n >= h->size()) {
            return string();
        }
        size_t from = h->rfind('.', h->size() - n - 2);
        from = from == std::string::npos ? 0 : from + 1;
        return string(std::string_view(*h).substr(from));
    }

    inline bool is_public_suffix(const string& host, suffix_rules rules) noexcept {
        auto h = detail::psl_host(host.view());
        return h && detail::public_suffix_length(*h, rules == suffix_rules::icann) == h->size();
    }
}
