// Generated by tools/dotenv_oracle.py (GNU bash, version 3.2.57(1)-release (arm64-apple-darwin25)): do not edit.
#pragma once
#include <string_view>
namespace dotenv_oracle {
struct read_case { std::string_view name; std::string_view text; std::string_view value; };
inline constexpr read_case reads[] = {
    {"empty", "", ""},
    {"comments and blank lines", "# a comment\x0a""\x0a""   # an indented comment\x0a""A=1\x0a""", "A=1;"},
    {"plain values", "A=1\x0a""B=hello\x0a""C=http://example.com/path\x3f""x=1\x0a""D=a,b,c\x0a""E=--flag\x0a""", "A=1;B=hello;C=http://example.com/path\x3f""x=1;D=a,b,c;E=--flag;"},
    {"empty values", "A=\x0a""B=''\x0a""C=\"\"\x0a""", "A=;B=;C=;"},
    {"export", "export A=1\x0a""export B='two'\x0a""export\x09""C=\"three\"\x0a""", "A=1;B=two;C=three;"},
    {"comments after values", "A=1 # one\x0a""B='two' # two\x0a""C=\"three\"\x09""# three\x0a""D=#notacomment\x0a""E= # empty\x0a""", "A=1;B=two;C=three;D=#notacomment;E=;"},
    {"single quotes are literal", "A='$HOME ${X} \\n \\t # not a comment'\x0a""B='\"double\" inside'\x0a""", "A=$HOME ${X} \\x5cn \\x5ct # not a comment;B=\"double\" inside;"},
    {"single quotes over lines", "A='line one\x0a""line two\x0a""\x0a""line four'\x0a""", "A=line one\\x0aline two\\x0a\\x0aline four;"},
    {"double quotes over lines", "A=\"line one\x0a""line two\"\x0a""", "A=line one\\x0aline two;"},
    {"double quotes keep single ones", "A=\"it's\"\x0a""", "A=it's;"},
    {"expansion of earlier keys", "A=one\x0a""B=$A\x0a""C=${A}\x0a""D=\"${A}-$A\"\x0a""E=${A}${A}$A\x0a""F=\"pre${A}post\"\x0a""", "A=one;B=one;C=one;D=one-one;E=oneoneone;F=preonepost;"},
    {"expansion of unset names", "A=$NOPE\x0a""B=\"${NOPE}\"\x0a""C=x${NOPE}y\x0a""", "A=;B=;C=xy;"},
    {"defaults", "A=one\x0a""B=${A:-default}\x0a""C=${NOPE:-default}\x0a""D=${NOPE-default}\x0a""E=\x0a""F=${E:-colon}\x0a""G=${E-nocolon}\x0a""H=\"${NOPE:-two words}\"\x0a""", "A=one;B=one;C=default;D=default;E=;F=colon;G=;H=two words;"},
    {"alternates", "A=one\x0a""E=\x0a""B=${A:+alt}\x0a""C=${NOPE:+alt}\x0a""D=${E:+alt}\x0a""F=${E+alt}\x0a""G=${NOPE+alt}\x0a""", "A=one;B=alt;C=;D=;E=;F=alt;G=;"},
    {"nested defaults", "A=one\x0a""B=${NOPE:-$A}\x0a""C=${NOPE:-${A}}\x0a""D=${NOPE:-${ALSO:-deep}}\x0a""E=\"${NOPE:-x${A}y}\"\x0a""", "A=one;B=one;C=one;D=deep;E=xoney;"},
    {"dollar alone", "A=$\x0a""B=cost$\x0a""C=\"$ 5\"\x0a""", "A=$;B=cost$;C=$ 5;"},
    {"redefinition uses the earlier value", "A=1\x0a""A=${A}2\x0a""B=$A\x0a""", "A=12;B=12;"},
    {"last wins", "A=1\x0a""B=2\x0a""A=3\x0a""", "A=3;B=2;"},
    {"underscores and digits in keys", "_A=1\x0a""A_B_9=2\x0a""a=3\x0a""", "A_B_9=2;_A=1;a=3;"},
    {"crlf lines", "A=1\x0d""\x0a""B='two'\x0d""\x0a""C=\"three\"\x0d""\x0a""", "A=1\\x0d;B=two\\x0d;C=three\\x0d;"},
    {"unicode", "A=za\xc5""\xbc""\xc3""\xb3""\xc5""\x82""\xc4""\x87""\x0a""B='\xe6""\x97""\xa5""\xe6""\x9c""\xac""\xe8""\xaa""\x9e""'\x0a""C=\"\xf0""\x9f""\x98""\x80"" ${B}\"\x0a""", "A=za\\xc5\\xbc\\xc3\\xb3\\xc5\\x82\\xc4\\x87;B=\\xe6\\x97\\xa5\\xe6\\x9c\\xac\\xe8\\xaa\\x9e;C=\\xf0\\x9f\\x98\\x80 \\xe6\\x97\\xa5\\xe6\\x9c\\xac\\xe8\\xaa\\x9e;"},
};
}
