//------------------------------------------------------------------------------
// SGCL: a C++20 application framework
// Copyright (c) 2022-2026 Sebastian Nibisz
// SPDX-License-Identifier: Apache-2.0
//------------------------------------------------------------------------------
// The tests of the W3C suite where this reader decides otherwise than the
// suite, each by design — no DTD is read — with the reason. Made from a
// run of xml_conformance.cpp and read through by hand: every "accepted"
// document has its error inside its DTD (the descriptions of the suite name
// productions 45-83 and the WFCs of entities and parameter entities, all
// of the DTD), every "refused" one refers to an entity its DTD declares,
// every "canonical" one wants an attribute only its DTD gives.
#pragma once

namespace {
    struct ConformanceOutcome {
        const char* id;
        const char* outcome;     // accepted (a not-wf test read), refused (a wf test refused), canonical (read, written otherwise)
        const char* reason;
    };

    const ConformanceOutcome ConformanceExpected[] = {
        {"attlist01", "accepted", "an error inside the DTD's internal subset, which is skipped, not read"},
        {"attlist02", "accepted", "an error inside the DTD's internal subset, which is skipped, not read"},
        {"attlist03", "accepted", "an error inside the DTD's internal subset, which is skipped, not read"},
        {"attlist04", "accepted", "an error inside the DTD's internal subset, which is skipped, not read"},
        {"attlist05", "accepted", "an error inside the DTD's internal subset, which is skipped, not read"},
        {"attlist06", "accepted", "an error inside the DTD's internal subset, which is skipped, not read"},
        {"attlist07", "accepted", "an error inside the DTD's internal subset, which is skipped, not read"},
        {"attlist08", "accepted", "an error inside the DTD's internal subset, which is skipped, not read"},
        {"attlist09", "accepted", "an error inside the DTD's internal subset, which is skipped, not read"},
        {"cond01", "accepted", "an error inside the DTD's internal subset, which is skipped, not read"},
        {"cond02", "accepted", "an error inside the DTD's internal subset, which is skipped, not read"},
        {"content01", "accepted", "an error inside the DTD's internal subset, which is skipped, not read"},
        {"content02", "accepted", "an error inside the DTD's internal subset, which is skipped, not read"},
        {"content03", "accepted", "an error inside the DTD's internal subset, which is skipped, not read"},
        {"decl01", "accepted", "an error inside the DTD's internal subset, which is skipped, not read"},
        {"dtd04", "accepted", "an error inside the DTD's internal subset, which is skipped, not read"},
        {"dtd05", "accepted", "an error inside the DTD's internal subset, which is skipped, not read"},
        {"dtd07", "accepted", "an error inside the DTD's internal subset, which is skipped, not read"},
        {"empty", "refused", "a reference to an entity the DTD declares: no DTD is read"},
        {"ext01", "refused", "a reference to an entity the DTD declares: no DTD is read"},
        {"ext02", "refused", "a reference to an entity the DTD declares: no DTD is read"},
        {"ibm-invalid-P32-ibm32i01.xml", "canonical", "an attribute the DTD gives a default or a type other than CDATA: no DTD is read"},
        {"ibm-invalid-P32-ibm32i03.xml", "canonical", "an attribute the DTD gives a default or a type other than CDATA: no DTD is read"},
        {"ibm-invalid-P32-ibm32i04.xml", "canonical", "an attribute the DTD gives a default or a type other than CDATA: no DTD is read"},
        {"ibm-invalid-P56-ibm56i03.xml", "canonical", "an attribute the DTD gives a default or a type other than CDATA: no DTD is read"},
        {"ibm-invalid-P58-ibm58i01.xml", "canonical", "the second canonical form, with the DTD's notations"},
        {"ibm-invalid-P58-ibm58i02.xml", "canonical", "the second canonical form, with the DTD's notations"},
        {"ibm-not-wf-P29-ibm29n03.xml", "accepted", "an error inside the DTD's internal subset, which is skipped, not read"},
        {"ibm-not-wf-P29-ibm29n07.xml", "accepted", "an error inside the DTD's internal subset, which is skipped, not read"},
        {"ibm-not-wf-P30-ibm30n01.xml", "accepted", "an error in an external DTD or entity, which is never loaded"},
        {"ibm-not-wf-P31-ibm31n01.xml", "accepted", "an error in an external DTD or entity, which is never loaded"},
        {"ibm-not-wf-P45-ibm45n01.xml", "accepted", "an error inside the DTD's internal subset, which is skipped, not read"},
        {"ibm-not-wf-P45-ibm45n02.xml", "accepted", "an error inside the DTD's internal subset, which is skipped, not read"},
        {"ibm-not-wf-P45-ibm45n03.xml", "accepted", "an error inside the DTD's internal subset, which is skipped, not read"},
        {"ibm-not-wf-P45-ibm45n04.xml", "accepted", "an error inside the DTD's internal subset, which is skipped, not read"},
        {"ibm-not-wf-P45-ibm45n05.xml", "accepted", "an error inside the DTD's internal subset, which is skipped, not read"},
        {"ibm-not-wf-P45-ibm45n06.xml", "accepted", "an error inside the DTD's internal subset, which is skipped, not read"},
        {"ibm-not-wf-P46-ibm46n01.xml", "accepted", "an error inside the DTD's internal subset, which is skipped, not read"},
        {"ibm-not-wf-P46-ibm46n02.xml", "accepted", "an error inside the DTD's internal subset, which is skipped, not read"},
        {"ibm-not-wf-P46-ibm46n03.xml", "accepted", "an error inside the DTD's internal subset, which is skipped, not read"},
        {"ibm-not-wf-P46-ibm46n04.xml", "accepted", "an error inside the DTD's internal subset, which is skipped, not read"},
        {"ibm-not-wf-P46-ibm46n05.xml", "accepted", "an error inside the DTD's internal subset, which is skipped, not read"},
        {"ibm-not-wf-P47-ibm47n01.xml", "accepted", "an error inside the DTD's internal subset, which is skipped, not read"},
        {"ibm-not-wf-P47-ibm47n02.xml", "accepted", "an error inside the DTD's internal subset, which is skipped, not read"},
        {"ibm-not-wf-P47-ibm47n03.xml", "accepted", "an error inside the DTD's internal subset, which is skipped, not read"},
        {"ibm-not-wf-P47-ibm47n04.xml", "accepted", "an error inside the DTD's internal subset, which is skipped, not read"},
        {"ibm-not-wf-P47-ibm47n05.xml", "accepted", "an error inside the DTD's internal subset, which is skipped, not read"},
        {"ibm-not-wf-P47-ibm47n06.xml", "accepted", "an error inside the DTD's internal subset, which is skipped, not read"},
        {"ibm-not-wf-P48-ibm48n01.xml", "accepted", "an error inside the DTD's internal subset, which is skipped, not read"},
        {"ibm-not-wf-P48-ibm48n02.xml", "accepted", "an error inside the DTD's internal subset, which is skipped, not read"},
        {"ibm-not-wf-P48-ibm48n03.xml", "accepted", "an error inside the DTD's internal subset, which is skipped, not read"},
        {"ibm-not-wf-P48-ibm48n04.xml", "accepted", "an error inside the DTD's internal subset, which is skipped, not read"},
        {"ibm-not-wf-P48-ibm48n05.xml", "accepted", "an error inside the DTD's internal subset, which is skipped, not read"},
        {"ibm-not-wf-P48-ibm48n06.xml", "accepted", "an error inside the DTD's internal subset, which is skipped, not read"},
        {"ibm-not-wf-P48-ibm48n07.xml", "accepted", "an error inside the DTD's internal subset, which is skipped, not read"},
        {"ibm-not-wf-P49-ibm49n01.xml", "accepted", "an error inside the DTD's internal subset, which is skipped, not read"},
        {"ibm-not-wf-P49-ibm49n02.xml", "accepted", "an error inside the DTD's internal subset, which is skipped, not read"},
        {"ibm-not-wf-P49-ibm49n03.xml", "accepted", "an error inside the DTD's internal subset, which is skipped, not read"},
        {"ibm-not-wf-P49-ibm49n04.xml", "accepted", "an error inside the DTD's internal subset, which is skipped, not read"},
        {"ibm-not-wf-P49-ibm49n05.xml", "accepted", "an error inside the DTD's internal subset, which is skipped, not read"},
        {"ibm-not-wf-P49-ibm49n06.xml", "accepted", "an error inside the DTD's internal subset, which is skipped, not read"},
        {"ibm-not-wf-P50-ibm50n01.xml", "accepted", "an error inside the DTD's internal subset, which is skipped, not read"},
        {"ibm-not-wf-P50-ibm50n02.xml", "accepted", "an error inside the DTD's internal subset, which is skipped, not read"},
        {"ibm-not-wf-P50-ibm50n03.xml", "accepted", "an error inside the DTD's internal subset, which is skipped, not read"},
        {"ibm-not-wf-P50-ibm50n04.xml", "accepted", "an error inside the DTD's internal subset, which is skipped, not read"},
        {"ibm-not-wf-P50-ibm50n05.xml", "accepted", "an error inside the DTD's internal subset, which is skipped, not read"},
        {"ibm-not-wf-P50-ibm50n06.xml", "accepted", "an error inside the DTD's internal subset, which is skipped, not read"},
        {"ibm-not-wf-P50-ibm50n07.xml", "accepted", "an error inside the DTD's internal subset, which is skipped, not read"},
        {"ibm-not-wf-P51-ibm51n01.xml", "accepted", "an error inside the DTD's internal subset, which is skipped, not read"},
        {"ibm-not-wf-P51-ibm51n02.xml", "accepted", "an error inside the DTD's internal subset, which is skipped, not read"},
        {"ibm-not-wf-P51-ibm51n03.xml", "accepted", "an error inside the DTD's internal subset, which is skipped, not read"},
        {"ibm-not-wf-P51-ibm51n04.xml", "accepted", "an error inside the DTD's internal subset, which is skipped, not read"},
        {"ibm-not-wf-P51-ibm51n05.xml", "accepted", "an error inside the DTD's internal subset, which is skipped, not read"},
        {"ibm-not-wf-P51-ibm51n06.xml", "accepted", "an error inside the DTD's internal subset, which is skipped, not read"},
        {"ibm-not-wf-P51-ibm51n07.xml", "accepted", "an error inside the DTD's internal subset, which is skipped, not read"},
        {"ibm-not-wf-P52-ibm52n01.xml", "accepted", "an error inside the DTD's internal subset, which is skipped, not read"},
        {"ibm-not-wf-P52-ibm52n03.xml", "accepted", "an error inside the DTD's internal subset, which is skipped, not read"},
        {"ibm-not-wf-P53-ibm53n01.xml", "accepted", "an error inside the DTD's internal subset, which is skipped, not read"},
        {"ibm-not-wf-P53-ibm53n02.xml", "accepted", "an error inside the DTD's internal subset, which is skipped, not read"},
        {"ibm-not-wf-P53-ibm53n03.xml", "accepted", "an error inside the DTD's internal subset, which is skipped, not read"},
        {"ibm-not-wf-P53-ibm53n04.xml", "accepted", "an error inside the DTD's internal subset, which is skipped, not read"},
        {"ibm-not-wf-P53-ibm53n05.xml", "accepted", "an error inside the DTD's internal subset, which is skipped, not read"},
        {"ibm-not-wf-P53-ibm53n06.xml", "accepted", "an error inside the DTD's internal subset, which is skipped, not read"},
        {"ibm-not-wf-P53-ibm53n07.xml", "accepted", "an error inside the DTD's internal subset, which is skipped, not read"},
        {"ibm-not-wf-P53-ibm53n08.xml", "accepted", "an error inside the DTD's internal subset, which is skipped, not read"},
        {"ibm-not-wf-P54-ibm54n01.xml", "accepted", "an error inside the DTD's internal subset, which is skipped, not read"},
        {"ibm-not-wf-P54-ibm54n02.xml", "accepted", "an error inside the DTD's internal subset, which is skipped, not read"},
        {"ibm-not-wf-P55-ibm55n01.xml", "accepted", "an error inside the DTD's internal subset, which is skipped, not read"},
        {"ibm-not-wf-P55-ibm55n02.xml", "accepted", "an error inside the DTD's internal subset, which is skipped, not read"},
        {"ibm-not-wf-P55-ibm55n03.xml", "accepted", "an error inside the DTD's internal subset, which is skipped, not read"},
        {"ibm-not-wf-P56-ibm56n01.xml", "accepted", "an error inside the DTD's internal subset, which is skipped, not read"},
        {"ibm-not-wf-P56-ibm56n02.xml", "accepted", "an error inside the DTD's internal subset, which is skipped, not read"},
        {"ibm-not-wf-P56-ibm56n03.xml", "accepted", "an error inside the DTD's internal subset, which is skipped, not read"},
        {"ibm-not-wf-P56-ibm56n04.xml", "accepted", "an error inside the DTD's internal subset, which is skipped, not read"},
        {"ibm-not-wf-P56-ibm56n05.xml", "accepted", "an error inside the DTD's internal subset, which is skipped, not read"},
        {"ibm-not-wf-P56-ibm56n06.xml", "accepted", "an error inside the DTD's internal subset, which is skipped, not read"},
        {"ibm-not-wf-P56-ibm56n07.xml", "accepted", "an error inside the DTD's internal subset, which is skipped, not read"},
        {"ibm-not-wf-P57-ibm57n01.xml", "accepted", "an error inside the DTD's internal subset, which is skipped, not read"},
        {"ibm-not-wf-P58-ibm58n01.xml", "accepted", "an error inside the DTD's internal subset, which is skipped, not read"},
        {"ibm-not-wf-P58-ibm58n02.xml", "accepted", "an error inside the DTD's internal subset, which is skipped, not read"},
        {"ibm-not-wf-P58-ibm58n03.xml", "accepted", "an error inside the DTD's internal subset, which is skipped, not read"},
        {"ibm-not-wf-P58-ibm58n04.xml", "accepted", "an error inside the DTD's internal subset, which is skipped, not read"},
        {"ibm-not-wf-P58-ibm58n05.xml", "accepted", "an error inside the DTD's internal subset, which is skipped, not read"},
        {"ibm-not-wf-P58-ibm58n06.xml", "accepted", "an error inside the DTD's internal subset, which is skipped, not read"},
        {"ibm-not-wf-P58-ibm58n07.xml", "accepted", "an error inside the DTD's internal subset, which is skipped, not read"},
        {"ibm-not-wf-P58-ibm58n08.xml", "accepted", "an error inside the DTD's internal subset, which is skipped, not read"},
        {"ibm-not-wf-P59-ibm59n01.xml", "accepted", "an error inside the DTD's internal subset, which is skipped, not read"},
        {"ibm-not-wf-P59-ibm59n02.xml", "accepted", "an error inside the DTD's internal subset, which is skipped, not read"},
        {"ibm-not-wf-P59-ibm59n03.xml", "accepted", "an error inside the DTD's internal subset, which is skipped, not read"},
        {"ibm-not-wf-P59-ibm59n04.xml", "accepted", "an error inside the DTD's internal subset, which is skipped, not read"},
        {"ibm-not-wf-P59-ibm59n05.xml", "accepted", "an error inside the DTD's internal subset, which is skipped, not read"},
        {"ibm-not-wf-P59-ibm59n06.xml", "accepted", "an error inside the DTD's internal subset, which is skipped, not read"},
        {"ibm-not-wf-P60-ibm60n01.xml", "accepted", "an error inside the DTD's internal subset, which is skipped, not read"},
        {"ibm-not-wf-P60-ibm60n02.xml", "accepted", "an error inside the DTD's internal subset, which is skipped, not read"},
        {"ibm-not-wf-P60-ibm60n03.xml", "accepted", "an error inside the DTD's internal subset, which is skipped, not read"},
        {"ibm-not-wf-P60-ibm60n04.xml", "accepted", "an error inside the DTD's internal subset, which is skipped, not read"},
        {"ibm-not-wf-P60-ibm60n05.xml", "accepted", "an error inside the DTD's internal subset, which is skipped, not read"},
        {"ibm-not-wf-P60-ibm60n06.xml", "accepted", "an error inside the DTD's internal subset, which is skipped, not read"},
        {"ibm-not-wf-P60-ibm60n08.xml", "accepted", "an error inside the DTD's internal subset, which is skipped, not read"},
        {"ibm-not-wf-P61-ibm61n01.xml", "accepted", "an error in an external DTD or entity, which is never loaded"},
        {"ibm-not-wf-P62-ibm62n01.xml", "accepted", "an error in an external DTD or entity, which is never loaded"},
        {"ibm-not-wf-P62-ibm62n02.xml", "accepted", "an error in an external DTD or entity, which is never loaded"},
        {"ibm-not-wf-P62-ibm62n03.xml", "accepted", "an error in an external DTD or entity, which is never loaded"},
        {"ibm-not-wf-P62-ibm62n04.xml", "accepted", "an error in an external DTD or entity, which is never loaded"},
        {"ibm-not-wf-P62-ibm62n05.xml", "accepted", "an error in an external DTD or entity, which is never loaded"},
        {"ibm-not-wf-P62-ibm62n06.xml", "accepted", "an error in an external DTD or entity, which is never loaded"},
        {"ibm-not-wf-P62-ibm62n07.xml", "accepted", "an error in an external DTD or entity, which is never loaded"},
        {"ibm-not-wf-P62-ibm62n08.xml", "accepted", "an error in an external DTD or entity, which is never loaded"},
        {"ibm-not-wf-P63-ibm63n01.xml", "accepted", "an error inside the DTD's internal subset, which is skipped, not read"},
        {"ibm-not-wf-P63-ibm63n02.xml", "accepted", "an error inside the DTD's internal subset, which is skipped, not read"},
        {"ibm-not-wf-P63-ibm63n03.xml", "accepted", "an error inside the DTD's internal subset, which is skipped, not read"},
        {"ibm-not-wf-P63-ibm63n04.xml", "accepted", "an error inside the DTD's internal subset, which is skipped, not read"},
        {"ibm-not-wf-P63-ibm63n05.xml", "accepted", "an error inside the DTD's internal subset, which is skipped, not read"},
        {"ibm-not-wf-P63-ibm63n06.xml", "accepted", "an error inside the DTD's internal subset, which is skipped, not read"},
        {"ibm-not-wf-P63-ibm63n07.xml", "accepted", "an error inside the DTD's internal subset, which is skipped, not read"},
        {"ibm-not-wf-P64-ibm64n01.xml", "accepted", "an error inside the DTD's internal subset, which is skipped, not read"},
        {"ibm-not-wf-P64-ibm64n02.xml", "accepted", "an error inside the DTD's internal subset, which is skipped, not read"},
        {"ibm-not-wf-P64-ibm64n03.xml", "accepted", "an error inside the DTD's internal subset, which is skipped, not read"},
        {"ibm-not-wf-P65-ibm65n01.xml", "accepted", "an error inside the DTD's internal subset, which is skipped, not read"},
        {"ibm-not-wf-P65-ibm65n02.xml", "accepted", "an error inside the DTD's internal subset, which is skipped, not read"},
        {"ibm-not-wf-P66-ibm66n01.xml", "accepted", "an error inside the DTD's internal subset, which is skipped, not read"},
        {"ibm-not-wf-P66-ibm66n03.xml", "accepted", "an error inside the DTD's internal subset, which is skipped, not read"},
        {"ibm-not-wf-P66-ibm66n05.xml", "accepted", "an error inside the DTD's internal subset, which is skipped, not read"},
        {"ibm-not-wf-P66-ibm66n07.xml", "accepted", "an error inside the DTD's internal subset, which is skipped, not read"},
        {"ibm-not-wf-P66-ibm66n09.xml", "accepted", "an error inside the DTD's internal subset, which is skipped, not read"},
        {"ibm-not-wf-P66-ibm66n11.xml", "accepted", "an error inside the DTD's internal subset, which is skipped, not read"},
        {"ibm-not-wf-P68-ibm68n07.xml", "accepted", "an error inside the DTD's internal subset, which is skipped, not read"},
        {"ibm-not-wf-P69-ibm69n06.xml", "accepted", "an error inside the DTD's internal subset, which is skipped, not read"},
        {"ibm-not-wf-P69-ibm69n07.xml", "accepted", "an error inside the DTD's internal subset, which is skipped, not read"},
        {"ibm-not-wf-P72-ibm72n02.xml", "accepted", "an error inside the DTD's internal subset, which is skipped, not read"},
        {"ibm-not-wf-P72-ibm72n03.xml", "accepted", "an error inside the DTD's internal subset, which is skipped, not read"},
        {"ibm-not-wf-P72-ibm72n04.xml", "accepted", "an error inside the DTD's internal subset, which is skipped, not read"},
        {"ibm-not-wf-P72-ibm72n05.xml", "accepted", "an error inside the DTD's internal subset, which is skipped, not read"},
        {"ibm-not-wf-P72-ibm72n06.xml", "accepted", "an error inside the DTD's internal subset, which is skipped, not read"},
        {"ibm-not-wf-P73-ibm73n01.xml", "accepted", "an error inside the DTD's internal subset, which is skipped, not read"},
        {"ibm-not-wf-P73-ibm73n03.xml", "accepted", "an error inside the DTD's internal subset, which is skipped, not read"},
        {"ibm-not-wf-P74-ibm74n01.xml", "accepted", "an error inside the DTD's internal subset, which is skipped, not read"},
        {"ibm-not-wf-P75-ibm75n01.xml", "accepted", "an error inside the DTD's internal subset, which is skipped, not read"},
        {"ibm-not-wf-P75-ibm75n05.xml", "accepted", "an error inside the DTD's internal subset, which is skipped, not read"},
        {"ibm-not-wf-P75-ibm75n06.xml", "accepted", "an error inside the DTD's internal subset, which is skipped, not read"},
        {"ibm-not-wf-P75-ibm75n12.xml", "accepted", "an error inside the DTD's internal subset, which is skipped, not read"},
        {"ibm-not-wf-P76-ibm76n01.xml", "accepted", "an error inside the DTD's internal subset, which is skipped, not read"},
        {"ibm-not-wf-P76-ibm76n02.xml", "accepted", "an error inside the DTD's internal subset, which is skipped, not read"},
        {"ibm-not-wf-P76-ibm76n03.xml", "accepted", "an error inside the DTD's internal subset, which is skipped, not read"},
        {"ibm-not-wf-P76-ibm76n04.xml", "accepted", "an error inside the DTD's internal subset, which is skipped, not read"},
        {"ibm-not-wf-P76-ibm76n05.xml", "accepted", "an error inside the DTD's internal subset, which is skipped, not read"},
        {"ibm-not-wf-P76-ibm76n06.xml", "accepted", "an error inside the DTD's internal subset, which is skipped, not read"},
        {"ibm-not-wf-P76-ibm76n07.xml", "accepted", "an error inside the DTD's internal subset, which is skipped, not read"},
        {"ibm-not-wf-P77-ibm77n03.xml", "accepted", "an error inside the DTD's internal subset, which is skipped, not read"},
        {"ibm-not-wf-P77-ibm77n04.xml", "accepted", "an error inside the DTD's internal subset, which is skipped, not read"},
        {"ibm-not-wf-P79-ibm79n01.xml", "accepted", "an error inside the DTD's internal subset, which is skipped, not read"},
        {"ibm-not-wf-P79-ibm79n02.xml", "accepted", "an error inside the DTD's internal subset, which is skipped, not read"},
        {"ibm-not-wf-P82-ibm82n02.xml", "accepted", "an error inside the DTD's internal subset, which is skipped, not read"},
        {"ibm-not-wf-P82-ibm82n03.xml", "accepted", "an error inside the DTD's internal subset, which is skipped, not read"},
        {"ibm-not-wf-P82-ibm82n04.xml", "accepted", "an error inside the DTD's internal subset, which is skipped, not read"},
        {"ibm-not-wf-P82-ibm82n08.xml", "accepted", "an error inside the DTD's internal subset, which is skipped, not read"},
        {"ibm-not-wf-P83-ibm83n01.xml", "accepted", "an error inside the DTD's internal subset, which is skipped, not read"},
        {"ibm-not-wf-P83-ibm83n03.xml", "accepted", "an error inside the DTD's internal subset, which is skipped, not read"},
        {"ibm-not-wf-P83-ibm83n04.xml", "accepted", "an error inside the DTD's internal subset, which is skipped, not read"},
        {"ibm-not-wf-P83-ibm83n05.xml", "accepted", "an error inside the DTD's internal subset, which is skipped, not read"},
        {"ibm-not-wf-P83-ibm83n06.xml", "accepted", "an error inside the DTD's internal subset, which is skipped, not read"},
        {"ibm-valid-P09-ibm09v01.xml", "refused", "a reference to an entity the DTD declares: no DTD is read"},
        {"ibm-valid-P09-ibm09v02.xml", "refused", "a reference to an entity the DTD declares: no DTD is read"},
        {"ibm-valid-P09-ibm09v03.xml", "refused", "a reference to an entity the DTD declares: no DTD is read"},
        {"ibm-valid-P09-ibm09v04.xml", "refused", "a reference to an entity the DTD declares: no DTD is read"},
        {"ibm-valid-P09-ibm09v05.xml", "refused", "a reference to an entity the DTD declares: no DTD is read"},
        {"ibm-valid-P10-ibm10v01.xml", "refused", "a reference to an entity the DTD declares: no DTD is read"},
        {"ibm-valid-P10-ibm10v02.xml", "refused", "a reference to an entity the DTD declares: no DTD is read"},
        {"ibm-valid-P10-ibm10v03.xml", "refused", "a reference to an entity the DTD declares: no DTD is read"},
        {"ibm-valid-P10-ibm10v04.xml", "refused", "a reference to an entity the DTD declares: no DTD is read"},
        {"ibm-valid-P10-ibm10v05.xml", "refused", "a reference to an entity the DTD declares: no DTD is read"},
        {"ibm-valid-P10-ibm10v06.xml", "refused", "a reference to an entity the DTD declares: no DTD is read"},
        {"ibm-valid-P10-ibm10v07.xml", "refused", "a reference to an entity the DTD declares: no DTD is read"},
        {"ibm-valid-P10-ibm10v08.xml", "refused", "a reference to an entity the DTD declares: no DTD is read"},
        {"ibm-valid-P28-ibm28v02.xml", "refused", "a reference to an entity the DTD declares: no DTD is read"},
        {"ibm-valid-P29-ibm29v01.xml", "refused", "a reference to an entity the DTD declares: no DTD is read"},
        {"ibm-valid-P29-ibm29v02.xml", "refused", "a reference to an entity the DTD declares: no DTD is read"},
        {"ibm-valid-P32-ibm32v01.xml", "canonical", "an attribute the DTD gives a default or a type other than CDATA: no DTD is read"},
        {"ibm-valid-P32-ibm32v02.xml", "refused", "a reference to an entity the DTD declares: no DTD is read"},
        {"ibm-valid-P32-ibm32v03.xml", "canonical", "an attribute the DTD gives a default or a type other than CDATA: no DTD is read"},
        {"ibm-valid-P32-ibm32v04.xml", "canonical", "an attribute the DTD gives a default or a type other than CDATA: no DTD is read"},
        {"ibm-valid-P43-ibm43v01.xml", "refused", "a reference to an entity the DTD declares: no DTD is read"},
        {"ibm-valid-P56-ibm56v08.xml", "canonical", "the second canonical form, with the DTD's notations"},
        {"ibm-valid-P57-ibm57v01.xml", "canonical", "the second canonical form, with the DTD's notations"},
        {"ibm-valid-P58-ibm58v01.xml", "canonical", "the second canonical form, with the DTD's notations"},
        {"ibm-valid-P58-ibm58v02.xml", "canonical", "the second canonical form, with the DTD's notations"},
        {"ibm-valid-P67-ibm67v01.xml", "refused", "a reference to an entity the DTD declares: no DTD is read"},
        {"ibm-valid-P70-ibm70v01.xml", "canonical", "the second canonical form, with the DTD's notations"},
        {"ibm-valid-P78-ibm78v01.xml", "refused", "a reference to an entity the DTD declares: no DTD is read"},
        {"ibm-valid-P82-ibm82v01.xml", "canonical", "the second canonical form, with the DTD's notations"},
        {"inv-not-sa02", "refused", "a reference to an entity the DTD declares: no DTD is read"},
        {"invalid-bo-1", "refused", "a reference to an entity the DTD declares: no DTD is read"},
        {"invalid-bo-2", "refused", "a reference to an entity the DTD declares: no DTD is read"},
        {"invalid-bo-3", "refused", "a reference to an entity the DTD declares: no DTD is read"},
        {"invalid-bo-4", "refused", "a reference to an entity the DTD declares: no DTD is read"},
        {"invalid-bo-5", "refused", "a reference to an entity the DTD declares: no DTD is read"},
        {"invalid-bo-6", "refused", "a reference to an entity the DTD declares: no DTD is read"},
        {"invalid-not-sa-022", "canonical", "an attribute the DTD gives a default or a type other than CDATA: no DTD is read"},
        {"invalid-sa-140", "refused", "a reference to an entity the DTD declares: no DTD is read"},
        {"invalid-sa-141", "refused", "a reference to an entity the DTD declares: no DTD is read"},
        {"not-sa01", "canonical", "the second canonical form, with the DTD's notations"},
        {"not-sa02", "refused", "a reference to an entity the DTD declares: no DTD is read"},
        {"not-sa03", "refused", "a reference to an entity the DTD declares: no DTD is read"},
        {"not-sa04", "refused", "a reference to an entity the DTD declares: no DTD is read"},
        {"not-wf-not-sa-001", "accepted", "an error in an external DTD or entity, which is never loaded"},
        {"not-wf-not-sa-002", "accepted", "an error inside the DTD's internal subset, which is skipped, not read"},
        {"not-wf-not-sa-003", "accepted", "an error in an external DTD or entity, which is never loaded"},
        {"not-wf-not-sa-004", "accepted", "an error in an external DTD or entity, which is never loaded"},
        {"not-wf-not-sa-006", "accepted", "an error in an external DTD or entity, which is never loaded"},
        {"not-wf-not-sa-007", "accepted", "an error in an external DTD or entity, which is never loaded"},
        {"not-wf-not-sa-008", "accepted", "an error in an external DTD or entity, which is never loaded"},
        {"not-wf-not-sa-009", "accepted", "an error in an external DTD or entity, which is never loaded"},
        {"not-wf-sa-054", "accepted", "an error inside the DTD's internal subset, which is skipped, not read"},
        {"not-wf-sa-057", "accepted", "an error inside the DTD's internal subset, which is skipped, not read"},
        {"not-wf-sa-058", "accepted", "an error inside the DTD's internal subset, which is skipped, not read"},
        {"not-wf-sa-059", "accepted", "an error inside the DTD's internal subset, which is skipped, not read"},
        {"not-wf-sa-060", "accepted", "an error inside the DTD's internal subset, which is skipped, not read"},
        {"not-wf-sa-061", "accepted", "an error inside the DTD's internal subset, which is skipped, not read"},
        {"not-wf-sa-062", "accepted", "an error inside the DTD's internal subset, which is skipped, not read"},
        {"not-wf-sa-064", "accepted", "an error inside the DTD's internal subset, which is skipped, not read"},
        {"not-wf-sa-065", "accepted", "an error inside the DTD's internal subset, which is skipped, not read"},
        {"not-wf-sa-066", "accepted", "an error inside the DTD's internal subset, which is skipped, not read"},
        {"not-wf-sa-067", "accepted", "an error inside the DTD's internal subset, which is skipped, not read"},
        {"not-wf-sa-068", "accepted", "an error inside the DTD's internal subset, which is skipped, not read"},
        {"not-wf-sa-069", "accepted", "an error inside the DTD's internal subset, which is skipped, not read"},
        {"not-wf-sa-078", "accepted", "an error inside the DTD's internal subset, which is skipped, not read"},
        {"not-wf-sa-079", "accepted", "an error inside the DTD's internal subset, which is skipped, not read"},
        {"not-wf-sa-080", "accepted", "an error inside the DTD's internal subset, which is skipped, not read"},
        {"not-wf-sa-082", "accepted", "an error inside the DTD's internal subset, which is skipped, not read"},
        {"not-wf-sa-084", "accepted", "an error inside the DTD's internal subset, which is skipped, not read"},
        {"not-wf-sa-086", "accepted", "an error inside the DTD's internal subset, which is skipped, not read"},
        {"not-wf-sa-087", "accepted", "an error inside the DTD's internal subset, which is skipped, not read"},
        {"not-wf-sa-089", "accepted", "an error inside the DTD's internal subset, which is skipped, not read"},
        {"not-wf-sa-091", "accepted", "an error inside the DTD's internal subset, which is skipped, not read"},
        {"not-wf-sa-113", "accepted", "an error inside the DTD's internal subset, which is skipped, not read"},
        {"not-wf-sa-114", "accepted", "an error inside the DTD's internal subset, which is skipped, not read"},
        {"not-wf-sa-121", "accepted", "an error inside the DTD's internal subset, which is skipped, not read"},
        {"not-wf-sa-122", "accepted", "an error inside the DTD's internal subset, which is skipped, not read"},
        {"not-wf-sa-123", "accepted", "an error inside the DTD's internal subset, which is skipped, not read"},
        {"not-wf-sa-124", "accepted", "an error inside the DTD's internal subset, which is skipped, not read"},
        {"not-wf-sa-125", "accepted", "an error inside the DTD's internal subset, which is skipped, not read"},
        {"not-wf-sa-126", "accepted", "an error inside the DTD's internal subset, which is skipped, not read"},
        {"not-wf-sa-127", "accepted", "an error inside the DTD's internal subset, which is skipped, not read"},
        {"not-wf-sa-128", "accepted", "an error inside the DTD's internal subset, which is skipped, not read"},
        {"not-wf-sa-129", "accepted", "an error inside the DTD's internal subset, which is skipped, not read"},
        {"not-wf-sa-130", "accepted", "an error inside the DTD's internal subset, which is skipped, not read"},
        {"not-wf-sa-131", "accepted", "an error inside the DTD's internal subset, which is skipped, not read"},
        {"not-wf-sa-132", "accepted", "an error inside the DTD's internal subset, which is skipped, not read"},
        {"not-wf-sa-133", "accepted", "an error inside the DTD's internal subset, which is skipped, not read"},
        {"not-wf-sa-134", "accepted", "an error inside the DTD's internal subset, which is skipped, not read"},
        {"not-wf-sa-135", "accepted", "an error inside the DTD's internal subset, which is skipped, not read"},
        {"not-wf-sa-136", "accepted", "an error inside the DTD's internal subset, which is skipped, not read"},
        {"not-wf-sa-137", "accepted", "an error inside the DTD's internal subset, which is skipped, not read"},
        {"not-wf-sa-138", "accepted", "an error inside the DTD's internal subset, which is skipped, not read"},
        {"not-wf-sa-139", "accepted", "an error inside the DTD's internal subset, which is skipped, not read"},
        {"not-wf-sa-158", "accepted", "an error inside the DTD's internal subset, which is skipped, not read"},
        {"not-wf-sa-160", "accepted", "an error inside the DTD's internal subset, which is skipped, not read"},
        {"not-wf-sa-161", "accepted", "an error inside the DTD's internal subset, which is skipped, not read"},
        {"not-wf-sa-162", "accepted", "an error inside the DTD's internal subset, which is skipped, not read"},
        {"not-wf-sa-180", "accepted", "an error inside the DTD's internal subset, which is skipped, not read"},
        {"not-wf-sa-183", "accepted", "an error inside the DTD's internal subset, which is skipped, not read"},
        {"not-wf-sa-184", "accepted", "an error inside the DTD's internal subset, which is skipped, not read"},
        {"notation01", "canonical", "the second canonical form, with the DTD's notations"},
        {"nwf-dtd00", "accepted", "an error inside the DTD's internal subset, which is skipped, not read"},
        {"nwf-dtd01", "accepted", "an error inside the DTD's internal subset, which is skipped, not read"},
        {"o-p09fail1", "accepted", "an error in an external DTD or entity, which is never loaded"},
        {"o-p09fail2", "accepted", "an error in an external DTD or entity, which is never loaded"},
        {"o-p09fail3", "accepted", "an error inside the DTD's internal subset, which is skipped, not read"},
        {"o-p12fail1", "accepted", "an error inside the DTD's internal subset, which is skipped, not read"},
        {"o-p12fail2", "accepted", "an error inside the DTD's internal subset, which is skipped, not read"},
        {"o-p12fail3", "accepted", "an error inside the DTD's internal subset, which is skipped, not read"},
        {"o-p12fail4", "accepted", "an error inside the DTD's internal subset, which is skipped, not read"},
        {"o-p12fail5", "accepted", "an error inside the DTD's internal subset, which is skipped, not read"},
        {"o-p12fail6", "accepted", "an error inside the DTD's internal subset, which is skipped, not read"},
        {"o-p12fail7", "accepted", "an error inside the DTD's internal subset, which is skipped, not read"},
        {"o-p30fail1", "accepted", "an error in an external DTD or entity, which is never loaded"},
        {"o-p31fail1", "accepted", "an error in an external DTD or entity, which is never loaded"},
        {"o-p43pass1", "refused", "a reference to an entity the DTD declares: no DTD is read"},
        {"o-p45fail2", "accepted", "an error inside the DTD's internal subset, which is skipped, not read"},
        {"o-p45fail3", "accepted", "an error inside the DTD's internal subset, which is skipped, not read"},
        {"o-p45fail4", "accepted", "an error inside the DTD's internal subset, which is skipped, not read"},
        {"o-p46fail1", "accepted", "an error inside the DTD's internal subset, which is skipped, not read"},
        {"o-p46fail2", "accepted", "an error inside the DTD's internal subset, which is skipped, not read"},
        {"o-p46fail3", "accepted", "an error inside the DTD's internal subset, which is skipped, not read"},
        {"o-p46fail4", "accepted", "an error inside the DTD's internal subset, which is skipped, not read"},
        {"o-p46fail5", "accepted", "an error inside the DTD's internal subset, which is skipped, not read"},
        {"o-p46fail6", "accepted", "an error inside the DTD's internal subset, which is skipped, not read"},
        {"o-p47fail1", "accepted", "an error inside the DTD's internal subset, which is skipped, not read"},
        {"o-p47fail2", "accepted", "an error inside the DTD's internal subset, which is skipped, not read"},
        {"o-p47fail3", "accepted", "an error inside the DTD's internal subset, which is skipped, not read"},
        {"o-p47fail4", "accepted", "an error inside the DTD's internal subset, which is skipped, not read"},
        {"o-p48fail1", "accepted", "an error inside the DTD's internal subset, which is skipped, not read"},
        {"o-p48fail2", "accepted", "an error inside the DTD's internal subset, which is skipped, not read"},
        {"o-p51fail1", "accepted", "an error inside the DTD's internal subset, which is skipped, not read"},
        {"o-p51fail2", "accepted", "an error inside the DTD's internal subset, which is skipped, not read"},
        {"o-p51fail3", "accepted", "an error inside the DTD's internal subset, which is skipped, not read"},
        {"o-p51fail4", "accepted", "an error inside the DTD's internal subset, which is skipped, not read"},
        {"o-p51fail5", "accepted", "an error inside the DTD's internal subset, which is skipped, not read"},
        {"o-p51fail6", "accepted", "an error inside the DTD's internal subset, which is skipped, not read"},
        {"o-p51fail7", "accepted", "an error inside the DTD's internal subset, which is skipped, not read"},
        {"o-p52fail1", "accepted", "an error inside the DTD's internal subset, which is skipped, not read"},
        {"o-p53fail1", "accepted", "an error inside the DTD's internal subset, which is skipped, not read"},
        {"o-p53fail2", "accepted", "an error inside the DTD's internal subset, which is skipped, not read"},
        {"o-p53fail3", "accepted", "an error inside the DTD's internal subset, which is skipped, not read"},
        {"o-p53fail4", "accepted", "an error inside the DTD's internal subset, which is skipped, not read"},
        {"o-p53fail5", "accepted", "an error inside the DTD's internal subset, which is skipped, not read"},
        {"o-p54fail1", "accepted", "an error inside the DTD's internal subset, which is skipped, not read"},
        {"o-p55fail1", "accepted", "an error inside the DTD's internal subset, which is skipped, not read"},
        {"o-p56fail1", "accepted", "an error inside the DTD's internal subset, which is skipped, not read"},
        {"o-p56fail2", "accepted", "an error inside the DTD's internal subset, which is skipped, not read"},
        {"o-p56fail3", "accepted", "an error inside the DTD's internal subset, which is skipped, not read"},
        {"o-p56fail4", "accepted", "an error inside the DTD's internal subset, which is skipped, not read"},
        {"o-p56fail5", "accepted", "an error inside the DTD's internal subset, which is skipped, not read"},
        {"o-p57fail1", "accepted", "an error inside the DTD's internal subset, which is skipped, not read"},
        {"o-p58fail1", "accepted", "an error inside the DTD's internal subset, which is skipped, not read"},
        {"o-p58fail2", "accepted", "an error inside the DTD's internal subset, which is skipped, not read"},
        {"o-p58fail3", "accepted", "an error inside the DTD's internal subset, which is skipped, not read"},
        {"o-p58fail4", "accepted", "an error inside the DTD's internal subset, which is skipped, not read"},
        {"o-p58fail5", "accepted", "an error inside the DTD's internal subset, which is skipped, not read"},
        {"o-p58fail6", "accepted", "an error inside the DTD's internal subset, which is skipped, not read"},
        {"o-p58fail7", "accepted", "an error inside the DTD's internal subset, which is skipped, not read"},
        {"o-p58fail8", "accepted", "an error inside the DTD's internal subset, which is skipped, not read"},
        {"o-p59fail1", "accepted", "an error inside the DTD's internal subset, which is skipped, not read"},
        {"o-p59fail2", "accepted", "an error inside the DTD's internal subset, which is skipped, not read"},
        {"o-p59fail3", "accepted", "an error inside the DTD's internal subset, which is skipped, not read"},
        {"o-p60fail1", "accepted", "an error inside the DTD's internal subset, which is skipped, not read"},
        {"o-p60fail2", "accepted", "an error inside the DTD's internal subset, which is skipped, not read"},
        {"o-p60fail3", "accepted", "an error inside the DTD's internal subset, which is skipped, not read"},
        {"o-p60fail4", "accepted", "an error inside the DTD's internal subset, which is skipped, not read"},
        {"o-p60fail5", "accepted", "an error inside the DTD's internal subset, which is skipped, not read"},
        {"o-p61fail1", "accepted", "an error in an external DTD or entity, which is never loaded"},
        {"o-p62fail1", "accepted", "an error in an external DTD or entity, which is never loaded"},
        {"o-p62fail2", "accepted", "an error in an external DTD or entity, which is never loaded"},
        {"o-p63fail1", "accepted", "an error in an external DTD or entity, which is never loaded"},
        {"o-p63fail2", "accepted", "an error in an external DTD or entity, which is never loaded"},
        {"o-p64fail1", "accepted", "an error in an external DTD or entity, which is never loaded"},
        {"o-p64fail2", "accepted", "an error in an external DTD or entity, which is never loaded"},
        {"o-p68pass1", "refused", "a reference to an entity the DTD declares: no DTD is read"},
        {"o-p70fail1", "accepted", "an error inside the DTD's internal subset, which is skipped, not read"},
        {"o-p71fail1", "accepted", "an error inside the DTD's internal subset, which is skipped, not read"},
        {"o-p71fail2", "accepted", "an error inside the DTD's internal subset, which is skipped, not read"},
        {"o-p72fail2", "accepted", "an error inside the DTD's internal subset, which is skipped, not read"},
        {"o-p72fail3", "accepted", "an error inside the DTD's internal subset, which is skipped, not read"},
        {"o-p72fail4", "accepted", "an error inside the DTD's internal subset, which is skipped, not read"},
        {"o-p73fail1", "accepted", "an error inside the DTD's internal subset, which is skipped, not read"},
        {"o-p73fail2", "accepted", "an error inside the DTD's internal subset, which is skipped, not read"},
        {"o-p73fail3", "accepted", "an error inside the DTD's internal subset, which is skipped, not read"},
        {"o-p73fail4", "accepted", "an error inside the DTD's internal subset, which is skipped, not read"},
        {"o-p73fail5", "accepted", "an error inside the DTD's internal subset, which is skipped, not read"},
        {"o-p74fail1", "accepted", "an error inside the DTD's internal subset, which is skipped, not read"},
        {"o-p74fail2", "accepted", "an error inside the DTD's internal subset, which is skipped, not read"},
        {"o-p74fail3", "accepted", "an error inside the DTD's internal subset, which is skipped, not read"},
        {"o-p75fail1", "accepted", "an error inside the DTD's internal subset, which is skipped, not read"},
        {"o-p75fail2", "accepted", "an error inside the DTD's internal subset, which is skipped, not read"},
        {"o-p75fail3", "accepted", "an error inside the DTD's internal subset, which is skipped, not read"},
        {"o-p75fail4", "accepted", "an error inside the DTD's internal subset, which is skipped, not read"},
        {"o-p75fail5", "accepted", "an error inside the DTD's internal subset, which is skipped, not read"},
        {"o-p75fail6", "accepted", "an error inside the DTD's internal subset, which is skipped, not read"},
        {"o-p76fail1", "accepted", "an error inside the DTD's internal subset, which is skipped, not read"},
        {"o-p76fail2", "accepted", "an error inside the DTD's internal subset, which is skipped, not read"},
        {"o-p76fail3", "accepted", "an error inside the DTD's internal subset, which is skipped, not read"},
        {"o-p76fail4", "accepted", "an error inside the DTD's internal subset, which is skipped, not read"},
        {"pr-xml-little", "refused", "a reference to an entity the DTD declares: no DTD is read"},
        {"pr-xml-utf-16", "refused", "a reference to an entity the DTD declares: no DTD is read"},
        {"pr-xml-utf-8", "refused", "a reference to an entity the DTD declares: no DTD is read"},
        {"pubid01", "accepted", "an error inside the DTD's internal subset, which is skipped, not read"},
        {"pubid02", "accepted", "an error inside the DTD's internal subset, which is skipped, not read"},
        {"pubid03", "accepted", "an error inside the DTD's internal subset, which is skipped, not read"},
        {"pubid04", "accepted", "an error inside the DTD's internal subset, which is skipped, not read"},
        {"pubid05", "accepted", "an error inside the DTD's internal subset, which is skipped, not read"},
        {"rmt-e2e-15a", "refused", "a reference to an entity the DTD declares: no DTD is read"},
        {"rmt-e2e-15e", "refused", "a reference to an entity the DTD declares: no DTD is read"},
        {"rmt-e2e-15f", "refused", "a reference to an entity the DTD declares: no DTD is read"},
        {"rmt-e2e-15h", "refused", "a reference to an entity the DTD declares: no DTD is read"},
        {"rmt-e2e-18", "refused", "a reference to an entity the DTD declares: no DTD is read"},
        {"rmt-e2e-19", "refused", "a reference to an entity the DTD declares: no DTD is read"},
        {"rmt-e3e-12", "accepted", "an error inside the DTD's internal subset, which is skipped, not read"},
        {"rmt-e3e-13", "refused", "a reference to an entity the DTD declares: no DTD is read"},
        {"rmt-ns10-012", "accepted", "an error inside the DTD's internal subset, which is skipped, not read"},
        {"rmt-ns10-043", "accepted", "an error inside the DTD's internal subset, which is skipped, not read"},
        {"rmt-ns10-044", "accepted", "an error inside the DTD's internal subset, which is skipped, not read"},
        {"sa02", "refused", "a reference to an entity the DTD declares: no DTD is read"},
        {"sa03", "refused", "a reference to an entity the DTD declares: no DTD is read"},
        {"sa04", "refused", "a reference to an entity the DTD declares: no DTD is read"},
        {"sa05", "canonical", "the second canonical form, with the DTD's notations"},
        {"sgml04", "accepted", "an error inside the DTD's internal subset, which is skipped, not read"},
        {"sgml05", "accepted", "an error inside the DTD's internal subset, which is skipped, not read"},
        {"sgml06", "accepted", "an error inside the DTD's internal subset, which is skipped, not read"},
        {"sgml07", "accepted", "an error inside the DTD's internal subset, which is skipped, not read"},
        {"sgml08", "accepted", "an error inside the DTD's internal subset, which is skipped, not read"},
        {"sgml09", "accepted", "an error inside the DTD's internal subset, which is skipped, not read"},
        {"sgml10", "accepted", "an error inside the DTD's internal subset, which is skipped, not read"},
        {"sgml11", "accepted", "an error inside the DTD's internal subset, which is skipped, not read"},
        {"sgml12", "accepted", "an error inside the DTD's internal subset, which is skipped, not read"},
        {"sgml13", "accepted", "an error inside the DTD's internal subset, which is skipped, not read"},
        {"v-pe00", "refused", "a reference to an entity the DTD declares: no DTD is read"},
        {"v-pe02", "refused", "a reference to an entity the DTD declares: no DTD is read"},
        {"v-pe03", "refused", "a reference to an entity the DTD declares: no DTD is read"},
        {"v-sgml01", "canonical", "an attribute the DTD gives a default or a type other than CDATA: no DTD is read"},
        {"valid-ext-sa-001", "refused", "a reference to an entity the DTD declares: no DTD is read"},
        {"valid-ext-sa-002", "refused", "a reference to an entity the DTD declares: no DTD is read"},
        {"valid-ext-sa-003", "refused", "a reference to an entity the DTD declares: no DTD is read"},
        {"valid-ext-sa-004", "refused", "a reference to an entity the DTD declares: no DTD is read"},
        {"valid-ext-sa-005", "refused", "a reference to an entity the DTD declares: no DTD is read"},
        {"valid-ext-sa-006", "refused", "a reference to an entity the DTD declares: no DTD is read"},
        {"valid-ext-sa-007", "refused", "a reference to an entity the DTD declares: no DTD is read"},
        {"valid-ext-sa-008", "refused", "a reference to an entity the DTD declares: no DTD is read"},
        {"valid-ext-sa-009", "refused", "a reference to an entity the DTD declares: no DTD is read"},
        {"valid-ext-sa-011", "refused", "a reference to an entity the DTD declares: no DTD is read"},
        {"valid-ext-sa-012", "refused", "a reference to an entity the DTD declares: no DTD is read"},
        {"valid-ext-sa-013", "refused", "a reference to an entity the DTD declares: no DTD is read"},
        {"valid-ext-sa-014", "refused", "a reference to an entity the DTD declares: no DTD is read"},
        {"valid-not-sa-003", "canonical", "an attribute the DTD gives a default or a type other than CDATA: no DTD is read"},
        {"valid-not-sa-004", "canonical", "an attribute the DTD gives a default or a type other than CDATA: no DTD is read"},
        {"valid-not-sa-005", "canonical", "an attribute the DTD gives a default or a type other than CDATA: no DTD is read"},
        {"valid-not-sa-006", "canonical", "an attribute the DTD gives a default or a type other than CDATA: no DTD is read"},
        {"valid-not-sa-007", "canonical", "an attribute the DTD gives a default or a type other than CDATA: no DTD is read"},
        {"valid-not-sa-008", "canonical", "an attribute the DTD gives a default or a type other than CDATA: no DTD is read"},
        {"valid-not-sa-009", "canonical", "an attribute the DTD gives a default or a type other than CDATA: no DTD is read"},
        {"valid-not-sa-010", "canonical", "an attribute the DTD gives a default or a type other than CDATA: no DTD is read"},
        {"valid-not-sa-011", "canonical", "an attribute the DTD gives a default or a type other than CDATA: no DTD is read"},
        {"valid-not-sa-012", "canonical", "an attribute the DTD gives a default or a type other than CDATA: no DTD is read"},
        {"valid-not-sa-013", "canonical", "an attribute the DTD gives a default or a type other than CDATA: no DTD is read"},
        {"valid-not-sa-014", "canonical", "an attribute the DTD gives a default or a type other than CDATA: no DTD is read"},
        {"valid-not-sa-015", "canonical", "an attribute the DTD gives a default or a type other than CDATA: no DTD is read"},
        {"valid-not-sa-016", "canonical", "an attribute the DTD gives a default or a type other than CDATA: no DTD is read"},
        {"valid-not-sa-017", "canonical", "an attribute the DTD gives a default or a type other than CDATA: no DTD is read"},
        {"valid-not-sa-018", "canonical", "an attribute the DTD gives a default or a type other than CDATA: no DTD is read"},
        {"valid-not-sa-019", "canonical", "an attribute the DTD gives a default or a type other than CDATA: no DTD is read"},
        {"valid-not-sa-020", "canonical", "an attribute the DTD gives a default or a type other than CDATA: no DTD is read"},
        {"valid-not-sa-021", "canonical", "an attribute the DTD gives a default or a type other than CDATA: no DTD is read"},
        {"valid-not-sa-023", "canonical", "an attribute the DTD gives a default or a type other than CDATA: no DTD is read"},
        {"valid-not-sa-024", "canonical", "an attribute the DTD gives a default or a type other than CDATA: no DTD is read"},
        {"valid-not-sa-025", "canonical", "an attribute the DTD gives a default or a type other than CDATA: no DTD is read"},
        {"valid-not-sa-026", "canonical", "an attribute the DTD gives a default or a type other than CDATA: no DTD is read"},
        {"valid-not-sa-028", "canonical", "an attribute the DTD gives a default or a type other than CDATA: no DTD is read"},
        {"valid-not-sa-029", "canonical", "an attribute the DTD gives a default or a type other than CDATA: no DTD is read"},
        {"valid-not-sa-031", "refused", "a reference to an entity the DTD declares: no DTD is read"},
        {"valid-sa-023", "refused", "a reference to an entity the DTD declares: no DTD is read"},
        {"valid-sa-024", "refused", "a reference to an entity the DTD declares: no DTD is read"},
        {"valid-sa-044", "canonical", "an attribute the DTD gives a default or a type other than CDATA: no DTD is read"},
        {"valid-sa-045", "canonical", "an attribute the DTD gives a default or a type other than CDATA: no DTD is read"},
        {"valid-sa-046", "canonical", "an attribute the DTD gives a default or a type other than CDATA: no DTD is read"},
        {"valid-sa-053", "refused", "a reference to an entity the DTD declares: no DTD is read"},
        {"valid-sa-058", "canonical", "an attribute the DTD gives a default or a type other than CDATA: no DTD is read"},
        {"valid-sa-066", "refused", "a reference to an entity the DTD declares: no DTD is read"},
        {"valid-sa-068", "refused", "a reference to an entity the DTD declares: no DTD is read"},
        {"valid-sa-069", "canonical", "the second canonical form, with the DTD's notations"},
        {"valid-sa-076", "canonical", "the second canonical form, with the DTD's notations"},
        {"valid-sa-080", "canonical", "an attribute the DTD gives a default or a type other than CDATA: no DTD is read"},
        {"valid-sa-085", "refused", "a reference to an entity the DTD declares: no DTD is read"},
        {"valid-sa-086", "refused", "a reference to an entity the DTD declares: no DTD is read"},
        {"valid-sa-087", "refused", "a reference to an entity the DTD declares: no DTD is read"},
        {"valid-sa-088", "refused", "a reference to an entity the DTD declares: no DTD is read"},
        {"valid-sa-089", "refused", "a reference to an entity the DTD declares: no DTD is read"},
        {"valid-sa-090", "canonical", "the second canonical form, with the DTD's notations"},
        {"valid-sa-091", "canonical", "the second canonical form, with the DTD's notations"},
        {"valid-sa-094", "canonical", "an attribute the DTD gives a default or a type other than CDATA: no DTD is read"},
        {"valid-sa-096", "canonical", "an attribute the DTD gives a default or a type other than CDATA: no DTD is read"},
        {"valid-sa-097", "canonical", "an attribute the DTD gives a default or a type other than CDATA: no DTD is read"},
        {"valid-sa-108", "refused", "a reference to an entity the DTD declares: no DTD is read"},
        {"valid-sa-110", "refused", "a reference to an entity the DTD declares: no DTD is read"},
        {"valid-sa-111", "canonical", "an attribute the DTD gives a default or a type other than CDATA: no DTD is read"},
        {"valid-sa-114", "refused", "a reference to an entity the DTD declares: no DTD is read"},
        {"valid-sa-115", "refused", "a reference to an entity the DTD declares: no DTD is read"},
        {"valid-sa-117", "refused", "a reference to an entity the DTD declares: no DTD is read"},
        {"valid-sa-118", "refused", "a reference to an entity the DTD declares: no DTD is read"},
    };
}
