//------------------------------------------------------------------------------
// SGCL: a C++20 application framework
// Copyright (c) 2022-2026 Sebastian Nibisz
// SPDX-License-Identifier: Apache-2.0
//------------------------------------------------------------------------------
#pragma once

// Generated by tools/stencil_oracle.go: do not edit.
//
// What Go's text/template writes for the subset of the syntax both sides
// share, over one shape of data that tests/txt/template.cpp builds the
// same way. The source of that program says which cases are deliberately
// not here and why.

namespace oracle {
    struct TemplateCase {
        const char* source;
        const char* want;
    };

    inline constexpr TemplateCase GoTemplateTests[] = {
        {"hello {{.name}}", "hello ada lovelace"},
        {"{{.user.first}} {{.user.last}}", "ada lovelace"},
        {"{{.n}}", "42"},
        {"{{.pi}}", "3.14159"},
        {"{{.whole}}", "88"},
        {"{{.admin}}", "true"},
        {"{{.guest}}", "false"},
        {"{{.empty}}!", "!"},
        {"nothing happens here", "nothing happens here"},
        {"", ""},
        {"{{if .admin}}yes{{else}}no{{end}}", "yes"},
        {"{{if .guest}}yes{{else}}no{{end}}", "no"},
        {"{{if .zero}}yes{{else}}no{{end}}", "no"},
        {"{{if .n}}yes{{else}}no{{end}}", "yes"},
        {"{{if .empty}}yes{{else}}no{{end}}", "no"},
        {"{{if .name}}yes{{else}}no{{end}}", "yes"},
        {"{{if .tags}}some{{else}}none{{end}}", "some"},
        {"{{if .nolist}}some{{else}}none{{end}}", "none"},
        {"{{if .user}}some{{else}}none{{end}}", "some"},
        {"a{{if .admin}}B{{end}}c", "aBc"},
        {"a{{if .guest}}B{{end}}c", "ac"},
        {"{{if .guest}}a{{else if .admin}}b{{else}}c{{end}}", "b"},
        {"{{if .guest}}a{{else if .zero}}b{{else}}c{{end}}", "c"},
        {"{{if .admin}}a{{else if .zero}}b{{else}}c{{end}}", "a"},
        {"{{range .tags}}[{{.}}]{{end}}", "[one][two][three]"},
        {"{{range .tags}}{{.}}-{{$.n}} {{end}}", "one-42 two-42 three-42 "},
        {"{{range .nolist}}x{{end}}", ""},
        {"{{range .nolist}}x{{else}}empty{{end}}", "empty"},
        {"{{range .tags}}x{{else}}empty{{end}}", "xxx"},
        {"{{range .rows}}{{.who}}:{{if .on}}on{{else}}off{{end}} {{end}}", "ada:on bob:off "},
        {"{{range .tags}}{{range $.tags}}.{{end}}|{{end}}", "...|...|...|"},
        {"{{with .user}}{{.first}} {{.last}}{{end}}", "ada lovelace"},
        {"{{with .empty}}yes{{else}}no{{end}}", "no"},
        {"{{with .nolist}}yes{{else}}no{{end}}", "no"},
        {"{{with .user}}{{.first}}{{end}}-{{.name}}", "ada-ada lovelace"},
        {"a{{/* nothing at all */}}b", "ab"},
        {"{{/* only a comment */}}", ""},
        {"a   {{- .n}}", "a42"},
        {"{{.n -}}   b", "42b"},
        {"a   {{- .n -}}   b", "a42b"},
        {"line\n  {{- if .admin}}on{{end}}", "lineon"},
        {"{{.name | upper}}", "ADA LOVELACE"},
        {"{{.name | title}}", "Ada Lovelace"},
        {"{{.spaced | trim}}!", "Countess!"},
        {"{{.name | upper | lower}}", "ada lovelace"},
        {"{{.empty | default \"anon\"}}", "anon"},
        {"{{.name | default \"anon\"}}", "ada lovelace"},
        {"{{.zero | default 7}}", "7"},
        {"{{.n | default 7}}", "42"},
        {"{{range .tags}}{{. | upper}} {{end}}", "ONE TWO THREE "},
        {"{{.n}}%", "42%"},
    };
}
