# SGCL: a C++20 application platform
# Copyright (c) 2022-2026 Sebastian Nibisz
# SPDX-License-Identifier: Apache-2.0
#
# The oracle for the dotenv of sgcl/encoding (dotenv.h): bash, which reads the
# subset of .env that shell and dotenv agree on (plain unquoted values, single
# quotes, double quotes without backslashes, $NAME, ${NAME}, ${NAME:-x},
# ${NAME-x}, ${NAME:+x}, ${NAME+x}), each case sourced with `set -a` in an
# empty environment and the variables it set written out as a C++ header the
# tests include:
#
#     python3 tools/dotenv_oracle.py tests/encoding/dotenv/corpus.env-list > tests/encoding/dotenv_tests.h
#
# The value of a case: its variables sorted by name, NAME=value; each, the value
# with \xNN for bytes outside printable ASCII and for ';' and '\'; or "error"
# when bash fails on it.
import os
import subprocess
import sys
import tempfile


def escape(s):
    out = ''
    for b in s:
        if 0x20 <= b < 0x7F and b not in b';\\':
            out += chr(b)
        else:
            out += '\\x%02x' % b
    return out


def read(text, workdir):
    path = os.path.join(workdir, 'case.env')
    with open(path, 'wb') as f:
        f.write(text)
    script = 'set -a; . "$1" || exit 3; env -0'
    base = subprocess.run(['/bin/bash', '--noprofile', '--norc', '-c', 'env -0'], env={}, capture_output=True).stdout.split(b'\0')
    r = subprocess.run(['/bin/bash', '--noprofile', '--norc', '-c', script, '_', path], env={}, capture_output=True)
    if r.returncode != 0 or r.stderr:
        return 'error'
    names = {e.split(b'=', 1)[0] for e in base if e}
    names.add(b'_')
    got = {}
    for e in r.stdout.split(b'\0'):
        if not e:
            continue
        k, v = e.split(b'=', 1)
        if k not in names:
            got[k] = v
    return ''.join('%s=%s;' % (k.decode(), escape(got[k])) for k in sorted(got))


def cases(path):
    data = open(path, 'rb').read()
    out = []
    at = data.find(b'#%%% ')
    while at >= 0:
        nl = data.index(b'\n', at)
        name = data[at + 5:nl].decode()
        nxt = data.find(b'\n#%%% ', nl)
        if nxt < 0 or name == 'end':
            break
        out.append((name, data[nl + 1:nxt + 1]))
        at = nxt + 1
    return out


def cstr(b):
    out = '"'
    for c in b:
        ch = chr(c)
        if ch in '"\\':
            out += '\\' + ch
        elif 0x20 <= c < 0x7F and ch != '?':
            out += ch
        else:
            out += '\\x%02x""' % c
    return out + '"'


print('// Generated by tools/dotenv_oracle.py (%s): do not edit.' % subprocess.run(['/bin/bash', '--version'], capture_output=True, text=True).stdout.splitlines()[0])
print('#pragma once\n#include <string_view>\nnamespace dotenv_oracle {')
print('struct read_case { std::string_view name; std::string_view text; std::string_view value; };')
print('inline constexpr read_case reads[] = {')
with tempfile.TemporaryDirectory() as d:
    for name, text in cases(sys.argv[1]):
        print('    {%s, %s, %s},' % (cstr(name.encode()), cstr(text), cstr(read(text, d).encode())))
print('};\n}')
