// Writes sgcl/compress/detail/brotli_dictionary.h: Brotli's static dictionary
// and its 121 transforms (RFC 7932, Appendices A and B) and the lookup tables
// of the literals' context modes (section 7.1), taken from the tables
// libbrotli carries (the same data as the RFC's appendices), as spec data for
// the decoder and the encoder of sgcl::compress::brotli. The data keeps its
// own license (MIT, Copyright 2013 Google Inc.; NOTICE at the root of the tree).
//
//   cc -O1 tools/gen_brotli_dictionary.c -L/opt/homebrew/opt/brotli/lib -lbrotlicommon -o /tmp/gen_brotli_dictionary
//   /tmp/gen_brotli_dictionary > sgcl/compress/detail/brotli_dictionary.h
//
// The structures below are libbrotli's (common/dictionary.h, common/transform.h
// of brotli 1.x), declared here to read what its two exported functions return.
#include <stddef.h>
#include <stdint.h>
#include <stdio.h>

typedef struct {
    uint8_t size_bits_by_length[32];
    uint32_t offsets_by_length[32];
    size_t data_size;
    const uint8_t* data;
} Dictionary;

typedef struct {
    uint16_t prefix_suffix_size;
    const uint8_t* prefix_suffix;
    const uint16_t* prefix_suffix_map;
    uint32_t num_transforms;
    const uint8_t* triplets;
    const uint8_t* params;
    int16_t cut_off[10];
} Transforms;

const Dictionary* BrotliGetDictionary(void);
const Transforms* BrotliGetTransforms(void);
extern const uint8_t _kBrotliContextLookupTable[2048];

static void string_of(const Transforms* t, unsigned id, char* out) {
    const uint8_t* p = t->prefix_suffix + t->prefix_suffix_map[id];
    unsigned n = p[0];
    char* o = out;
    *o++ = '"';
    for (unsigned i = 1; i <= n; ++i) {
        unsigned c = p[i];
        if (c == '"' || c == '\\') {
            o += sprintf(o, "\\%c", c);
        } else if (c >= 0x20 && c < 0x7F) {
            *o++ = (char)c;
        } else {
            o += sprintf(o, "\\x%02x\" \"", c);
        }
    }
    *o++ = '"';
    *o = 0;
}

int main(void) {
    const Dictionary* d = BrotliGetDictionary();
    const Transforms* t = BrotliGetTransforms();
    if (d->data_size != 122784 || t->num_transforms != 121) {
        fprintf(stderr, "unexpected sizes: %zu bytes, %u transforms\n", d->data_size, t->num_transforms);
        return 1;
    }
    printf("//------------------------------------------------------------------------------\n");
    printf("// SGCL: a C++20 application platform\n");
    printf("// Brotli's static dictionary and transforms: data of RFC 7932, under its own license\n");
    printf("// SPDX-License-Identifier: MIT\n");
    printf("//------------------------------------------------------------------------------\n");
    printf("#pragma once\n\n");
    printf("// Generated by tools/gen_brotli_dictionary.c from libbrotli 1.2.0's tables,\n");
    printf("// which are RFC 7932's Appendix A (the dictionary) and Appendix B (the\n");
    printf("// transforms): do not edit. The notice of that data:\n");
    printf("//\n");
    printf("//   Copyright 2013 Google Inc. All Rights Reserved.\n");
    printf("//   Distributed under MIT license.\n");
    printf("//   See file LICENSE for detail or copy at https://opensource.org/licenses/MIT\n");
    printf("//\n");
    printf("// The rest of the library is Apache-2.0; this file is that data's and\n");
    printf("// stays MIT (NOTICE at the root of the tree).\n\n");
    printf("#include <cstdint>\n\n");
    printf("namespace sgcl::compress::detail {\n");
    printf("    inline constexpr uint32_t BrotliDictionarySize = %zu;\n\n", d->data_size);
    printf("    // The bits of a word's index within its length (4..24), and where the words of a length begin\n");
    printf("    inline constexpr uint8_t BrotliDictionaryBits[25] = {");
    for (int i = 0; i < 25; ++i) {
        printf("%s%u", i ? ", " : "", d->size_bits_by_length[i]);
    }
    printf("};\n");
    printf("    inline constexpr uint32_t BrotliDictionaryOffsets[25] = {");
    for (int i = 0; i < 25; ++i) {
        printf("%s%u", i ? ", " : "", d->offsets_by_length[i]);
    }
    printf("};\n\n");
    printf("    // The dictionary's bytes, eight to a word, the first in the low byte\n");
    printf("    inline constexpr uint64_t BrotliDictionaryWords[%zu] = {\n", d->data_size / 8);
    for (size_t w = 0; w < d->data_size / 8; ++w) {
        uint64_t v = 0;
        for (int b = 7; b >= 0; --b) {
            v = (v << 8) | d->data[w * 8 + (size_t)b];
        }
        printf("%s0x%016llxull,%s", w % 6 == 0 ? "        " : " ", (unsigned long long)v, w % 6 == 5 ? "\n" : "");
    }
    printf("\n    };\n\n");
    printf("    // A transform: a prefix, an operation on the word (0 identity, 1..9 the last\n");
    printf("    // n bytes left out, 10 the first letter upper-cased, 11 all of them, 12..20\n");
    printf("    // the first n - 11 bytes left out), a suffix\n");
    printf("    struct BrotliTransform {\n");
    printf("        const char* prefix;\n");
    printf("        uint8_t type;\n");
    printf("        const char* suffix;\n");
    printf("    };\n\n");
    printf("    // The literals' context of the two bytes before, by mode (LSB6, MSB6, UTF8,\n");
    printf("    // Signed): BrotliContextLut[512 * mode + p1] | BrotliContextLut[512 * mode + 256 + p2]\n");
    printf("    inline constexpr uint8_t BrotliContextLut[2048] = {\n");
    for (int i = 0; i < 2048; ++i) {
        printf("%s%u,%s", i % 32 == 0 ? "        " : " ", _kBrotliContextLookupTable[i], i % 32 == 31 ? "\n" : "");
    }
    printf("    };\n\n");
    printf("    inline constexpr BrotliTransform BrotliTransforms[%u] = {\n", t->num_transforms);
    char a[256], b[256];
    for (unsigned i = 0; i < t->num_transforms; ++i) {
        string_of(t, t->triplets[3 * i], a);
        string_of(t, t->triplets[3 * i + 2], b);
        printf("        {%s, %u, %s},   // %u\n", a, t->triplets[3 * i + 1], b, i);
    }
    printf("    };\n");
    printf("}\n");
    return 0;
}
