#!/usr/bin/env python3
# The data of RFC 7541 the HPACK coder needs, read from the RFC's text:
# the static table (Appendix A) and the Huffman code (Appendix B), written
# to sgcl/net/http/detail/h2/hpack_tables.h. Specification data, not code;
# tests/net/http/hpack.cpp checks the header against the RFC file again.
#
#   python3 tools/hpack_tables.py ~/Programming/oracles/rfc7541/rfc7541.txt
import re
import sys

src = sys.argv[1] if len(sys.argv) > 1 else '~/Programming/oracles/rfc7541/rfc7541.txt'
out = sys.argv[2] if len(sys.argv) > 2 else 'sgcl/net/http/detail/h2/hpack_tables.h'
text = open(src.replace('~', __import__('os').path.expanduser('~'), 1)).read()

a = text[text.index('Appendix A.  Static Table Definition'):text.index('Appendix B.  Huffman Code')]
static = []
for m in re.finditer(r'^\s*\|\s*(\d+)\s*\|\s*(\S+)\s*\|\s*(.*?)\s*\|\s*$', a, re.M):
    static.append((int(m.group(1)), m.group(2), m.group(3)))
assert [i for i, _, _ in static] == list(range(1, 62)), 'static table: 61 entries expected'

b = text[text.index('Appendix B.  Huffman Code'):text.index('Appendix C.  Examples')]
codes = {}
for m in re.finditer(r'^\s*(?:\'.\'\s*)?(?:EOS\s*)?\(\s*(\d+)\)\s*\|([01|]+)\s+([0-9a-f]+)\s+\[\s*(\d+)\]', b, re.M):
    sym, bits, hexcode, length = int(m.group(1)), m.group(2).replace('|', ''), int(m.group(3), 16), int(m.group(4))
    assert len(bits) == length and int(bits, 2) == hexcode, 'symbol %d: bits and hex disagree' % sym
    codes[sym] = (hexcode, length)
assert sorted(codes) == list(range(257)), 'Huffman: 257 symbols expected, got %d' % len(codes)

lines = []
lines.append('''//------------------------------------------------------------------------------
// SGCL: a C++20 application platform
// Copyright (c) 2022-2026 Sebastian Nibisz
// SPDX-License-Identifier: Apache-2.0
//------------------------------------------------------------------------------
#pragma once

#include <cstdint>
#include <string_view>

// Generated by tools/hpack_tables.py from RFC 7541 (Appendix A, the static
// table; Appendix B, the Huffman code). Do not edit: the data of the
// specification, checked against the RFC's text by tests/net/http/hpack.cpp.
namespace sgcl::net::http::detail::h2 {
    struct StaticField {
        std::string_view name;
        std::string_view value;
    };

    // Appendix A: the 61 entries, index 1 at [0]
    inline constexpr StaticField static_table[61] = {''')
for i, n, v in static:
    lines.append('        {"%s", "%s"},   // %d' % (n, v, i))
lines.append('''    };

    struct HuffmanCode {
        uint32_t code;     // aligned to the least significant bit
        uint8_t bits;
    };

    // Appendix B: the code of each octet, and of EOS at [256]
    inline constexpr HuffmanCode huffman_codes[257] = {''')
for sym in range(257):
    c, l = codes[sym]
    lines.append('        {0x%x, %d},   // %d' % (c, l, sym))
lines.append('''    };
}
''')
open(out, 'w').write('\n'.join(lines))
print('wrote', out, len(static), 'static entries,', len(codes), 'codes')
