# SGCL: a C++20 application platform
# Copyright (c) 2022-2026 Sebastian Nibisz
# SPDX-License-Identifier: Apache-2.0
#
# The oracle for the INI of sgcl/encoding (ini.h): Python's configparser as
# ini.h's dialect states it (RawConfigParser, strict, no interpolation, keys in
# their case, comments on lines of their own, a blank line ending a value),
# asked to read the same texts, the sections it reads written out as a C++
# header the tests include:
#
#     clang++ -std=c++20 -O1 -I. tools/ini_written.cpp -framework CoreFoundation -framework Security \
#         -framework Accelerate -framework CoreGraphics -framework ImageIO -o ini_written
#     ./ini_written > written.ini-list
#     python3 tools/ini_oracle.py tests/encoding/ini/corpus.ini-list written.ini-list > tests/encoding/ini_tests.h
#
# The value of a case: each section in order as [name] and its keys in order as
# key=value; (the section of the keys before the first header as []; \xNN for bytes outside printable ASCII and for ';', '[', ']',
# '=' and '\'), or "error" when configparser refuses the text.
import configparser
import sys


def escape(s):
    out = ''
    for b in s.encode('utf-8'):
        if 0x20 <= b < 0x7F and b not in b';[]=\\':
            out += chr(b)
        else:
            out += '\\x%02x' % b
    return out


GLOBAL = '\x01global'


def read(text):
    def parser():
        p = configparser.RawConfigParser(strict=True, empty_lines_in_values=False, interpolation=None,
                                         default_section='\x00none', comment_prefixes=('#', ';'),
                                         inline_comment_prefixes=None, allow_no_value=False)
        p.optionxform = str
        return p
    p = parser()
    try:
        p.read_string(text)
    except configparser.MissingSectionHeaderError:
        # ini.h's one stated difference of reading: keys before the first
        # header are the section "" (configparser refuses them), read here as
        # a section of a name no text has
        p = parser()
        try:
            p.read_string('[' + GLOBAL + ']\n' + text)
        except configparser.Error:
            return 'error'
    except configparser.Error:
        return 'error'
    out = ''
    for s in p.sections():
        out += '[' + escape('' if s == GLOBAL else s) + ']'
        for k, v in p.items(s):
            out += escape(k) + '=' + escape(v) + ';'
    return out


def cases(path):
    data = open(path, 'rb').read().decode('utf-8')
    out = []
    at = data.find('#%%% ')
    while at >= 0:
        nl = data.index('\n', at)
        name = data[at + 5:nl]
        nxt = data.find('\n#%%% ', nl)
        if nxt < 0 or name == 'end':
            break
        out.append((name, data[nl + 1:nxt + 1]))
        at = nxt + 1
    return out


def cstr(s):
    out = '"'
    for c in s.encode('utf-8'):
        ch = chr(c)
        if ch in '"\\':
            out += '\\' + ch
        elif 0x20 <= c < 0x7F and ch != '?':
            out += ch
        else:
            out += '\\x%02x""' % c
    return out + '"'


print('// Generated by tools/ini_oracle.py (Python %s configparser): do not edit.' % sys.version.split()[0])
print('#pragma once\n#include <string_view>\nnamespace ini_oracle {')
print('struct read_case { std::string_view name; std::string_view text; std::string_view value; };')
print('inline constexpr read_case reads[] = {')
for path in sys.argv[1:]:
    for name, t in cases(path):
        # configparser reads lines as universal newlines: a text's \r\n are its line ends
        print('    {%s, %s, %s},' % (cstr(name), cstr(t), cstr(read(t))))
print('};\n}')
