// SGCL: a C++20 application framework
// Copyright (c) 2022-2026 Sebastian Nibisz
// SPDX-License-Identifier: Apache-2.0
//
// The oracle for sgcl/math/random.h: Go's math/rand/v2 over its ChaCha8
// source, asked for what tests/math/random.cpp checks, the answers
// written out as a C++ header the test includes. Run it from the root of
// the tree:
//
//     go run tools/math_oracle.go > tests/math/random_vectors.h
//
// The cases, each named because an oracle checks nothing it is not given:
//
//   - the first thousand Uint64s for the key of the C2SP sample (past the
//     372 the specification lists, so rekeyings 3 to 8 are in) and for
//     the key math::random(42) uses: 42 little-endian and 24 zero bytes;
//   - Int64N for the bounds 1, 2, 3, 6, 7, 1000, 2^32, 2^32 + 1, 2^62,
//     2^62 + 1, 2^63 - 1 and 3·2^61 — the powers of two take the mask,
//     the others Lemire's multiplication, and the large odd ones reach its
//     rejection often — twenty draws each from a fresh random(7);
//   - Float64, twenty draws from random(7);
//   - Perm(10) and Perm(1000) from random(7) (Fisher-Yates from the back).
//
// The distributions (NormFloat64, ExpFloat64) are Go's own ziggurats and
// not the ones of random.h, so they are not asked.
package main

import (
	"encoding/binary"
	"fmt"
	"math/rand/v2"
	"strings"
)

func seedKey(seed uint64) [32]byte {
	var k [32]byte
	binary.LittleEndian.PutUint64(k[:8], seed)
	return k
}

func words(name string, vs []uint64) {
	fmt.Printf("    inline constexpr uint64_t %s[] = {\n", name)
	for i := 0; i < len(vs); i += 4 {
		var parts []string
		for _, v := range vs[i:min(i+4, len(vs))] {
			parts = append(parts, fmt.Sprintf("0x%016x", v))
		}
		fmt.Printf("        %s,\n", strings.Join(parts, ", "))
	}
	fmt.Println("    };")
	fmt.Println()
}

func main() {
	fmt.Print(`//------------------------------------------------------------------------------
// SGCL: a C++20 application framework
// Copyright (c) 2022-2026 Sebastian Nibisz
// SPDX-License-Identifier: Apache-2.0
//------------------------------------------------------------------------------
// Generated by tools/math_oracle.go from Go's math/rand/v2; do not edit.
#pragma once

#include <cstddef>
#include <cstdint>

namespace math_vectors {
`)
	var ascii [32]byte
	copy(ascii[:], "ABCDEFGHIJKLMNOPQRSTUVWXYZ123456")
	for _, c := range []struct {
		name string
		key  [32]byte
	}{{"go_ascii_key", ascii}, {"go_seed_42", seedKey(42)}} {
		src := rand.NewChaCha8(c.key)
		vs := make([]uint64, 1000)
		for i := range vs {
			vs[i] = src.Uint64()
		}
		words(c.name, vs)
	}

	bounds := []int64{1, 2, 3, 6, 7, 1000, 1 << 32, 1<<32 + 1, 1 << 62, 1<<62 + 1, 1<<63 - 1, 3 << 61}
	fmt.Println("    // Int64N(bound), twenty draws from a fresh random(7) for each bound")
	fmt.Println("    struct BoundedDraws { int64_t bound; int64_t draws[20]; };")
	fmt.Println("    inline constexpr BoundedDraws go_int64n[] = {")
	for _, b := range bounds {
		r := rand.New(rand.NewChaCha8(seedKey(7)))
		var parts []string
		for range 20 {
			parts = append(parts, fmt.Sprintf("%d", r.Int64N(b)))
		}
		fmt.Printf("        {%d, {%s}},\n", b, strings.Join(parts, ", "))
	}
	fmt.Println("    };")
	fmt.Println()

	r := rand.New(rand.NewChaCha8(seedKey(7)))
	fmt.Println("    // Float64, twenty draws from random(7)")
	fmt.Println("    inline constexpr double go_float64[] = {")
	for range 20 {
		fmt.Printf("        %x,\n", r.Float64())
	}
	fmt.Println("    };")
	fmt.Println()

	for _, n := range []int{10, 1000} {
		r := rand.New(rand.NewChaCha8(seedKey(7)))
		p := r.Perm(n)
		fmt.Printf("    // Perm(%d) from random(7)\n", n)
		fmt.Printf("    inline constexpr size_t go_perm_%d[] = {\n", n)
		for i := 0; i < len(p); i += 16 {
			var parts []string
			for _, v := range p[i:min(i+16, len(p))] {
				parts = append(parts, fmt.Sprintf("%d", v))
			}
			fmt.Printf("        %s,\n", strings.Join(parts, ", "))
		}
		fmt.Println("    };")
		fmt.Println()
	}
	fmt.Println("}")
}
