#!/usr/bin/env python3
# SGCL: a C++20 application framework
# Copyright (c) 2022-2026 Sebastian Nibisz
# SPDX-License-Identifier: Apache-2.0
#
# The tables of the ziggurats behind math::random's next_normal and
# next_exponential (Marsaglia and Tsang, "The Ziggurat Method for
# Generating Random Variables", Journal of Statistical Software 5(8),
# 2000): 128 layers for the normal distribution, 256 for the exponential,
# the recurrences of the paper with its constants. Written out as literals
# rather than computed where the program starts, so that the tables — and
# with them the numbers random(seed) gives — are the same bits on every
# platform whatever its exp and log round to. Run from the root of the
# tree:
#
#     python3 tools/math_tables.py > sgcl/math/detail/ziggurat.h
#
# One change to the paper: its draws are 32 bits, the index taken from
# the same bits as the value (the correlation Doornik pointed out in
# 2005); here the index is the low bits of a 64-bit draw and the value
# the 56 bits above them, so the thresholds are scaled by 2^56.
import math

M = 2.0 ** 56


def normal():
    dn = 3.442619855899
    tn = dn
    vn = 9.91256303526217e-3
    k = [0] * 128
    w = [0.0] * 128
    f = [0.0] * 128
    q = vn / math.exp(-0.5 * dn * dn)
    k[0] = int((dn / q) * M)
    k[1] = 0
    w[0] = q / M
    w[127] = dn / M
    f[0] = 1.0
    f[127] = math.exp(-0.5 * dn * dn)
    for i in range(126, 0, -1):
        dn = math.sqrt(-2.0 * math.log(vn / dn + math.exp(-0.5 * dn * dn)))
        k[i + 1] = int((dn / tn) * M)
        tn = dn
        f[i] = math.exp(-0.5 * dn * dn)
        w[i] = dn / M
    return k, w, f


def exponential():
    de = 7.697117470131487
    te = de
    ve = 3.949659822581572e-3
    k = [0] * 256
    w = [0.0] * 256
    f = [0.0] * 256
    q = ve / math.exp(-de)
    k[0] = int((de / q) * M)
    k[1] = 0
    w[0] = q / M
    w[255] = de / M
    f[0] = 1.0
    f[255] = math.exp(-de)
    for i in range(254, 0, -1):
        de = -math.log(ve / de + math.exp(-de))
        k[i + 1] = int((de / te) * M)
        te = de
        f[i] = math.exp(-de)
        w[i] = de / M
    return k, w, f


def emit(name, values, kind):
    print(f"    inline constexpr {kind} {name}[{len(values)}] = {{")
    per = 4 if kind == "uint64_t" else 3
    for i in range(0, len(values), per):
        row = values[i:i + per]
        if kind == "uint64_t":
            text = ", ".join(f"{v}ull" for v in row)
        else:
            text = ", ".join(float.hex(v) for v in row)
        print(f"        {text},")
    print("    };")
    print()


def main():
    nk, nw, nf = normal()
    ek, ew, ef = exponential()
    print("""//------------------------------------------------------------------------------
// SGCL: a C++20 application framework
// Copyright (c) 2022-2026 Sebastian Nibisz
// SPDX-License-Identifier: Apache-2.0
//------------------------------------------------------------------------------
// Generated by tools/math_tables.py; do not edit.
#pragma once

#include <cstdint>

// The ziggurats of math::random (random.h): for each layer the threshold
// below which a draw is inside the layer's rectangle (k, scaled by 2^56),
// the width that turns a draw into a value (w), and the density at the
// layer's edge (f). Normal: 128 layers, the tail beyond 3.442619855899;
// exponential: 256 layers, the tail beyond 7.697117470131487.
namespace sgcl::math::detail {""")
    emit("NormalK", nk, "uint64_t")
    emit("NormalW", nw, "double")
    emit("NormalF", nf, "double")
    emit("ExponentialK", ek, "uint64_t")
    emit("ExponentialW", ew, "double")
    emit("ExponentialF", ef, "double")
    print("    inline constexpr double NormalTail = 3.442619855899;")
    print("    inline constexpr double ExponentialTail = 7.697117470131487;")
    print("}")


if __name__ == "__main__":
    main()
