// SGCL: a C++20 application framework
// Copyright (c) 2022-2026 Sebastian Nibisz
// SPDX-License-Identifier: Apache-2.0
//
// The oracle for big_integer::is_probable_prime: Go's math/big ProbablyPrime,
// asked about numbers tests/math/number.cpp checks, the answers written
// out as a C++ header. Run it from the root of the tree:
//
//     go run tools/math_primes_oracle.go > tests/math/prime_vectors.h
//
// The cases, each named because an oracle checks nothing it is not given:
//
//   - 1500 odd 64-bit numbers from a fixed seed, and for every twentieth
//     the next prime after it with the odd numbers between: below 2^64
//     ProbablyPrime(0) is Baillie–PSW, which is exact there;
//   - products of two primes of 32 bits (the hard composites for trial
//     division) and the odd numbers just below 2^64;
//   - 400 odd numbers of 128 bits, 200 of 256, 40 of 1024 and 10 of 2048,
//     with the next prime after a fifth of them and the four odd numbers
//     below it, asked with ProbablyPrime(20);
//   - products of two primes of 512 bits.
package main

import (
	"fmt"
	"math/big"
	"math/rand/v2"
)

var r = rand.New(rand.NewPCG(20260925, 7))

func randomOdd(bits int) *big.Int {
	x := new(big.Int)
	for i := 0; i < (bits+63)/64; i++ {
		x.Lsh(x, 64)
		x.Or(x, new(big.Int).SetUint64(r.Uint64()))
	}
	x.SetBit(x, bits-1, 1)
	x.Rsh(x, uint(x.BitLen()-bits))
	x.SetBit(x, 0, 1)
	return x
}

type entry struct {
	v     *big.Int
	prime bool
}

var out []entry

func add(v *big.Int, rounds int) {
	out = append(out, entry{new(big.Int).Set(v), v.ProbablyPrime(rounds)})
}

// v and every odd number after it up to and with the next prime; for
// long numbers only the last `keep` of those before the prime
func addRun(v *big.Int, rounds int, keep int) {
	x := new(big.Int).Set(v)
	var run []*big.Int
	for {
		run = append(run, new(big.Int).Set(x))
		if x.ProbablyPrime(rounds) {
			break
		}
		x.Add(x, big.NewInt(2))
	}
	if keep > 0 && len(run) > keep+1 {
		run = append(run[:1], run[len(run)-keep-1:]...)
	}
	for _, y := range run {
		add(y, rounds)
	}
}

func prime(bits int) *big.Int {
	x := randomOdd(bits)
	for !x.ProbablyPrime(20) {
		x.Add(x, big.NewInt(2))
	}
	return x
}

func main() {
	for i := 0; i < 1500; i++ {
		v := randomOdd(64)
		if i%20 == 0 {
			addRun(v, 0, 0)
		} else {
			add(v, 0)
		}
	}
	for i := 0; i < 100; i++ {
		p, q := prime(32), prime(32)
		add(new(big.Int).Mul(p, q), 0)
	}
	top := new(big.Int).Lsh(big.NewInt(1), 64)
	for i := 1; i < 200; i += 2 {
		add(new(big.Int).Sub(top, big.NewInt(int64(i))), 0)
	}
	for _, c := range []struct{ bits, count int }{{128, 400}, {256, 200}, {1024, 40}, {2048, 10}} {
		for i := 0; i < c.count; i++ {
			v := randomOdd(c.bits)
			if i%5 == 0 {
				addRun(v, 20, 4)
			} else {
				add(v, 20)
			}
		}
	}
	for i := 0; i < 5; i++ {
		add(new(big.Int).Mul(prime(512), prime(512)), 20)
	}
	fmt.Print(`//------------------------------------------------------------------------------
// SGCL: a C++20 application framework
// Copyright (c) 2022-2026 Sebastian Nibisz
// SPDX-License-Identifier: Apache-2.0
//------------------------------------------------------------------------------
// Generated by tools/math_primes_oracle.go from Go's math/big; do not edit.
// A number in hexadecimal and whether ProbablyPrime called it prime.
#pragma once

namespace prime_vectors {
    struct Case { const char* value; bool prime; };
    inline constexpr Case cases[] = {
`)
	for _, e := range out {
		fmt.Printf("        {\"%s\", %v},\n", e.v.Text(16), e.prime)
	}
	fmt.Print("    };\n}\n")
}
