// SGCL: a C++20 application platform
// Copyright (c) 2022-2026 Sebastian Nibisz
// SPDX-License-Identifier: Apache-2.0
//
// The oracle for sgcl/math/big_float.h: Go's math/big.Float, asked what
// tests/math/big_float.cpp checks, the answers written out as a C++ header.
// Run it from the root of the tree:
//
//     go run tools/math_float_oracle.go > tests/math/float_vectors.h
//
// The semantics are the C++ type's, which are Go's for a receiver of
// precision 0: a result takes the larger precision of its operands and the
// mode of the left one. Every value is written exactly in Go's 'p' format
// (the hexadecimal mantissa and the binary exponent), which the C++ side
// reads back exactly and writes the same way.
//
//   - parse: decimal and hexadecimal texts at precisions 1 to 300 in each of
//     the six modes;
//   - + - * / of pairs of values of precisions 24, 53, 64, 113 and 200 in
//     each mode, signed zeros and infinities among them (the operations
//     that would be NaN are left out: Go panics, the C++ throws);
//   - sqrt at those precisions in each mode;
//   - Text in e, f and g with -1 and 10 digits, and x with -1 and 5 digits;
//     Float64; Int (cut towards zero); SetRat of fractions.
package main

import (
	"fmt"
	"math"
	"math/big"
	"strconv"
	"strings"
)

var modes = []big.RoundingMode{big.ToNearestEven, big.ToNearestAway, big.ToZero, big.AwayFromZero, big.ToNegativeInf, big.ToPositiveInf}

// the C++ rounding's enumerator of a Go mode
func modeIndex(m big.RoundingMode) int {
	switch m {
	case big.ToNearestEven:
		return 0
	case big.ToNearestAway:
		return 1
	case big.ToZero:
		return 4
	case big.AwayFromZero:
		return 3
	case big.ToNegativeInf:
		return 6
	default:
		return 5
	}
}

func lit(s string) string { return strconv.Quote(s) }

func p(f *big.Float) string { return lit(f.Text('p', 0)) }

func cdouble(d float64) string {
	if math.IsInf(d, 1) {
		return "Inf"
	}
	if math.IsInf(d, -1) {
		return "-Inf"
	}
	if d == 0 && math.Signbit(d) {
		return "-0.0"
	}
	return strconv.FormatFloat(d, 'x', -1, 64)
}

// A text rounded once to the precision: a decimal through big.Rat and
// SetRat, whose quotient is rounded correctly (ParseFloat scales by powers
// of ten at a precision of its own and may round twice: "9.999…9" at two
// bits came out 12, not 8); hexadecimal, signed zeros and infinities by
// ParseFloat, exact for them
func parse(s string, prec uint, mode big.RoundingMode) *big.Float {
	if !strings.Contains(s, "0x") && !strings.Contains(s, "Inf") && s != "-0" {
		r, ok := new(big.Rat).SetString(s)
		if !ok {
			panic(s)
		}
		return new(big.Float).SetPrec(prec).SetMode(mode).SetRat(r)
	}
	f, _, err := big.ParseFloat(s, 0, prec, mode)
	if err != nil {
		panic(s + ": " + err.Error())
	}
	return f
}

func main() {
	var b strings.Builder
	w := func(format string, args ...any) { fmt.Fprintf(&b, format+"\n", args...) }
	w("//------------------------------------------------------------------------------")
	w("// SGCL: a C++20 application platform")
	w("// Copyright (c) 2022-2026 Sebastian Nibisz")
	w("// SPDX-License-Identifier: Apache-2.0")
	w("//------------------------------------------------------------------------------")
	w("// Generated by tools/math_float_oracle.go from Go's math/big.Float; do not")
	w("// edit. Values in Go's 'p' format; modes as sgcl::rounding's enumerators.")
	w("#pragma once")
	w("")
	w("namespace float_vectors {")
	w("    inline constexpr double Inf = __builtin_inf();")
	w("")

	texts := []string{"1", "0.1", "-0.1", "3.14159265358979323846264338327950288419716939937510", "2.5", "-2.5", "0.5",
		"1e100", "-1e-100", "123456789012345678901234567890", "0x1.8p3", "0x.cp-1", "-0x1.fffffffffffffp1023",
		"1e-320", "4.9406564584124654e-324", "0.3", "7", "1048575.5", "0.0000000000000000000000000001",
		"9.999999999999999999999999999999999999", "0", "-0", "1e1000", "-7e-1000"}
	precs := []uint{1, 2, 10, 24, 53, 64, 100, 300}
	w("    // a text, a precision, a mode, and the value parse makes")
	w("    struct Parse { const char* text; unsigned precision; int mode; const char* value; };")
	w("    inline constexpr Parse parses[] = {")
	for _, t := range texts {
		for _, pr := range precs {
			for _, m := range modes {
				w("        {%s, %d, %d, %s},", lit(t), pr, modeIndex(m), p(parse(t, pr, m)))
			}
		}
	}
	w("    };")
	w("")

	// operands: the texts at 300 bits, rounded to each precision
	opPrecs := []uint{24, 53, 64, 113, 200}
	opTexts := []string{"1", "-0.1", "3.14159265358979323846264338327950288419716939937510", "2.5", "1e100",
		"-1e-100", "123456789012345678901234567890", "-7", "0.333333333333333333333333333333333333333333",
		"1e-30", "0", "-0", "Inf", "-Inf", "1048575.5"}
	type operand struct {
		f    *big.Float
		text string
	}
	var ops []operand
	for i, t := range opTexts {
		pr := opPrecs[i%len(opPrecs)]
		f := parse(t, 300, big.ToNearestEven)
		g := new(big.Float).SetPrec(pr).SetMode(big.ToNearestEven).Set(f)
		ops = append(ops, operand{g, g.Text('p', 0)})
	}
	w("    // a and its precision, b and its precision, a's mode; a + b, a - b, a * b, a / b (empty")
	w("    // when Go panics: the C++ throws)")
	w("    struct Op { const char* a; unsigned pa; const char* b; unsigned pb; int mode; const char* sum;")
	w("                const char* difference; const char* product; const char* quotient; };")
	w("    inline constexpr Op ops[] = {")
	for _, x := range ops {
		for _, y := range ops {
			for _, m := range modes {
				a := new(big.Float).SetPrec(x.f.Prec()).SetMode(m).Set(x.f)
				pr := a.Prec()
				if y.f.Prec() > pr {
					pr = y.f.Prec()
				}
				res := func(op func(z, a, b *big.Float) *big.Float) (s string) {
					defer func() {
						if recover() != nil {
							s = lit("")
						}
					}()
					z := new(big.Float).SetPrec(pr).SetMode(m)
					return p(op(z, a, y.f))
				}
				w("        {%s, %d, %s, %d, %d, %s, %s, %s, %s},", lit(x.text), x.f.Prec(), lit(y.text), y.f.Prec(),
					modeIndex(m), res((*big.Float).Add), res((*big.Float).Sub), res((*big.Float).Mul), res((*big.Float).Quo))
			}
		}
	}
	w("    };")
	w("")
	w("    // a value (at its precision, with the mode), the precision, the mode: its square root")
	w("    struct Sqrt { const char* value; unsigned precision; int mode; const char* root; };")
	w("    inline constexpr Sqrt roots[] = {")
	for _, t := range []string{"2", "3", "0.5", "1e100", "1e-100", "123456789012345678901234567890", "4", "0.0625", "0", "-0",
		"2.0000000000000000000000000000001", "Inf", "0x1p-1000", "0x1.8p999"} {
		f := parse(t, 300, big.ToNearestEven)
		for _, pr := range []uint{1, 24, 53, 64, 113, 200} {
			for _, m := range modes {
				x := new(big.Float).SetPrec(pr).SetMode(m).Set(f)
				z := new(big.Float).SetPrec(pr).SetMode(m)
				z.Sqrt(x)
				w("        {%s, %d, %d, %s},", p(x), pr, modeIndex(m), p(z))
			}
		}
	}
	w("    };")
	w("")
	w("    // a value: Text in g, e, f with -1 and 10 digits, x with -1 and 5, Float64, Int")
	w("    struct Text { const char* value; unsigned precision; const char* g; const char* e; const char* f; const char* g10;")
	w("                  const char* e10; const char* f10; const char* x; const char* x5; double to_double; const char* integer; };")
	w("    inline constexpr Text texts[] = {")
	textValues := append([]string{}, texts...)
	textValues = append(textValues, "0.000012345", "123456", "1234567", "0.0001", "0.00001", "100", "1e21", "999999.5",
		"0.000099999999", "1.5", "-1.5", "0x1p-1074", "0x1p-1075", "0x1.0000000000001p-1074", "0x1.fffffffffffff8p1023")
	for _, t := range textValues {
		for _, pr := range []uint{24, 53, 64, 200} {
			f := parse(t, pr, big.ToNearestEven)
			d, _ := f.Float64()
			in := "inf"
			if !f.IsInf() {
				i, _ := f.Int(nil)
				in = i.String()
			}
			w("        {%s, %d, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s},", p(f), pr, lit(f.Text('g', -1)), lit(f.Text('e', -1)),
				lit(f.Text('f', -1)), lit(f.Text('g', 10)), lit(f.Text('e', 10)), lit(f.Text('f', 10)), lit(f.Text('x', -1)),
				lit(f.Text('x', 5)), cdouble(d), lit(in))
		}
	}
	w("    };")
	w("")
	w("    // a fraction, a precision, a mode: SetRat's value")
	w("    struct Rat { const char* fraction; unsigned precision; int mode; const char* value; };")
	w("    inline constexpr Rat rats[] = {")
	for _, t := range []string{"1/3", "-2/3", "1/10", "22/7", "-355/113", "1/1024", "123456789012345678901234567890/7", "5/1"} {
		r, _ := new(big.Rat).SetString(t)
		for _, pr := range []uint{1, 24, 53, 113} {
			for _, m := range modes {
				x := new(big.Float).SetPrec(pr).SetMode(m)
				x.SetRat(r)
				w("        {%s, %d, %d, %s},", lit(t), pr, modeIndex(m), p(x))
			}
		}
	}
	w("    };")
	w("}")
	fmt.Print(b.String())
}
