# SGCL: a C++20 application platform
# Copyright (c) 2022-2026 Sebastian Nibisz
# SPDX-License-Identifier: Apache-2.0
#
# The oracle for the TOML of sgcl/encoding (toml.h): Python's tomllib (the
# standard library's TOML 1.0 reader) asked to read the same texts, the values
# it reads written out as a C++ header the tests include:
#
#     clang++ -std=c++20 -O1 -I. tools/toml_written.cpp -framework CoreFoundation -framework Security \
#         -framework Accelerate -framework CoreGraphics -framework ImageIO -o toml_written
#     ./toml_written > written.toml-list
#     python3 tools/toml_oracle.py tests/encoding/toml/corpus.toml-list written.toml-list > tests/encoding/toml_tests.h
#
# The texts: the corpus (the spec's examples and the edge cases of every
# construct, valid and not, separated by lines "#%%% name") and the documents
# the writer of toml.h writes of random values. For each, the value as one
# line: s"text" a string (\xNN for bytes outside printable ASCII), i an
# integer, f the 16 hex digits of a float's bits (nan as f-nan), b1 or b0, O
# an offset date-time as Unix seconds and microseconds, L a local date-time,
# D a local date, T a local time (fractions as six digits: Python keeps
# microseconds), [ ] an array, { } a table with its keys sorted. Or "error".
import datetime
import math
import struct
import sys
import tomllib


def text(s):
    out = '"'
    for b in s.encode('utf-8'):
        c = chr(b)
        if c in '"\\':
            out += '\\' + c
        elif 0x20 <= b < 0x7F:
            out += c
        else:
            out += '\\x%02x' % b
    return out + '"'


def dump(v):
    if isinstance(v, bool):
        return 'b1' if v else 'b0'
    if isinstance(v, int):
        return 'i%d' % v
    if isinstance(v, float):
        return 'f-nan' if math.isnan(v) else 'f' + struct.pack('>d', v).hex()
    if isinstance(v, str):
        return 's' + text(v)
    if isinstance(v, datetime.datetime):
        if v.tzinfo is not None:
            epoch = datetime.datetime(1970, 1, 1, tzinfo=datetime.timezone.utc)
            delta = v - epoch
            seconds = delta.days * 86400 + delta.seconds
            return 'O%d.%06d' % (seconds, delta.microseconds)
        return 'L%04d-%02d-%02dT%02d:%02d:%02d.%06d' % (v.year, v.month, v.day, v.hour, v.minute, v.second, v.microsecond)
    if isinstance(v, datetime.date):
        return 'D%04d-%02d-%02d' % (v.year, v.month, v.day)
    if isinstance(v, datetime.time):
        return 'T%02d:%02d:%02d.%06d' % (v.hour, v.minute, v.second, v.microsecond)
    if isinstance(v, list):
        return '[ ' + ''.join(dump(x) + ' ' for x in v) + ']'
    if isinstance(v, dict):
        return '{ ' + ''.join(text(k) + '=' + dump(v[k]) + ' ' for k in sorted(v, key=lambda k: k.encode('utf-8'))) + '}'
    raise TypeError(type(v))


def read(t):
    try:
        return dump(tomllib.loads(t))
    except (tomllib.TOMLDecodeError, ValueError, OverflowError):
        return 'error'


def cases(path):
    data = open(path, 'rb').read().decode('utf-8', errors='surrogateescape')
    out = []
    at = data.find('#%%% ')
    while at >= 0:
        nl = data.index('\n', at)
        name = data[at + 5:nl]
        nxt = data.find('\n#%%% ', nl)
        if nxt < 0 or name == 'end':
            break
        out.append((name, data[nl + 1:nxt + 1]))
        at = nxt + 1
    return out


def cstr(s):
    out = '"'
    for b in s.encode('utf-8', errors='surrogateescape'):
        c = chr(b)
        if c in '"\\':
            out += '\\' + c
        elif 0x20 <= b < 0x7F and c != '?':
            out += c
        else:
            out += '\\x%02x""' % b
    return out + '"'


print('// Generated by tools/toml_oracle.py (Python %s tomllib): do not edit.' % sys.version.split()[0])
print('#pragma once\n#include <string_view>\nnamespace toml_oracle {')
print('struct read_case { std::string_view name; std::string_view text; std::string_view value; };')
print('inline constexpr read_case reads[] = {')
for path in sys.argv[1:]:
    for name, t in cases(path):
        print('    {%s, %s, %s},' % (cstr(name), cstr(t), cstr(read(t))))
print('};\n}')
