// SGCL: a C++20 application platform
// Copyright (c) 2022-2026 Sebastian Nibisz
// SPDX-License-Identifier: Apache-2.0
//
// The oracle for XXH32 and XXH64 of sgcl/hash (xxhash.h): libxxhash, the
// reference implementation (Homebrew's xxhash), asked the questions below
// and its answers written out as the C++ header the tests include:
//
//     cc -O2 -I/opt/homebrew/opt/xxhash/include tools/xxhash_oracle.c \
//         -L/opt/homebrew/opt/xxhash/lib -lxxhash -o /tmp/xxhash_oracle
//     /tmp/xxhash_oracle > tests/hash/xxhash_vectors.h
//
// What is asked (the patterns are those of tools/hash_oracle.go: 0 random
// from splitmix64 seeded 1, 1 zeros, 2 0xFF, 3 rising i mod 256): every
// length 0-300 of the random pattern with the seed 0, and the four
// patterns at the lengths about a stripe (16 and 32 bytes) and up to a
// megabyte with four seeds (0, 1, 2^32-1 or 2^64-1, the golden ratio).
// When libxxhash is found at build time, the tests also ask it directly.
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <xxhash.h>

static uint64_t seeds[] = {0, 1, 0xffffffffffffffffull, 0x9e3779b97f4a7c15ull};

static unsigned char* pattern(int kind, size_t n) {
    unsigned char* b = calloc(n + 8, 1);
    if (kind == 0) {
        uint64_t s = 1;
        for (size_t i = 0; i < n; i += 8) {
            s += 0x9e3779b97f4a7c15ull;
            uint64_t z = s;
            z = (z ^ (z >> 30)) * 0xbf58476d1ce4e5b9ull;
            z = (z ^ (z >> 27)) * 0x94d049bb133111ebull;
            z ^= z >> 31;
            for (int k = 0; k < 8; ++k) {
                b[i + k] = (unsigned char)(z >> (8 * k));
            }
        }
    } else if (kind == 2) {
        memset(b, 0xff, n + 8);
    } else if (kind == 3) {
        for (size_t i = 0; i < n + 8; ++i) {
            b[i] = (unsigned char)i;
        }
    }
    return b;
}

static void row(int kind, size_t n, int seed) {
    unsigned char* b = pattern(kind, n);
    printf("{%d,%zu,%d,0x%08x,0x%016llx},\n", kind, n, seed, XXH32(b, n, (uint32_t)seeds[seed]),
           (unsigned long long)XXH64(b, n, seeds[seed]));
    free(b);
}

int main(void) {
    printf("// Generated by tools/xxhash_oracle.c from libxxhash %u; do not edit. The\n", XXH_versionNumber());
    printf("// header of the generator says how to run it and which cases were asked.\n");
    printf("#pragma once\n\n#include <cstdint>\n\nnamespace xxhash_vectors {\n");
    printf("    // pattern: 0 random (splitmix64 from 1, little-endian), 1 zeros,\n");
    printf("    // 2 0xFF, 3 rising (i mod 256); seed: an index into seeds (XXH32 takes\n");
    printf("    // its low 32 bits)\n");
    printf("    inline constexpr uint64_t seeds[] = {0, 1, 0xffffffffffffffff, 0x9e3779b97f4a7c15};\n\n");
    printf("    struct Row {\n        int pattern;\n        uint32_t length;\n        int seed;\n        uint32_t xxh32;\n        uint64_t xxh64;\n    };\n\n");
    printf("    inline constexpr Row rows[] = {\n");
    for (size_t n = 0; n <= 300; ++n) {
        row(0, n, 0);
    }
    static const size_t lengths[] = {0, 1, 3, 4, 5, 7, 8, 9, 15, 16, 17, 31, 32, 33, 47, 48, 63, 64, 65, 1000, 4095, 4096, 65537, 1048576};
    for (int kind = 0; kind < 4; ++kind) {
        for (int seed = 0; seed < 4; ++seed) {
            for (size_t i = 0; i < sizeof lengths / sizeof lengths[0]; ++i) {
                if (kind == 0 && seed == 0 && lengths[i] <= 300) {
                    continue;
                }
                row(kind, lengths[i], seed);
            }
        }
    }
    printf("    };\n}\n");
    return 0;
}
